### ISSUE TITLE
GLControl flicker when covered by window

### ISSUE THREAD

**Issue by thefiddler** [opentk/opentk#10]
Originally posted at http://www.opentk.com/node/3456

"I have been working for 2 years with 2010 opengl version with no problems. I have updated to 2013 and now, with ATI, if a tooltip or child window overlaps the opengl context, that dirty region is repainted, but not the rest! Any Idea?"

The issue appears to be caused by https://github.com/opentk/opentk/commit/d9afed2d1069fcf0dd6ece449e8d5de194f3ce4a and disappears when reverted.

However, according to MSDN, the changes brought in by this commit are suggested or required for OpenGL on Windows. From http://msdn.microsoft.com/en-us/library/windows/desktop/dd369049(v=vs.85).aspx

"An OpenGL window has its own pixel format. Because of this, only device contexts retrieved for the client area of an OpenGL window are allowed to draw into the window. As a result, an OpenGL window should be created with the WS_CLIPCHILDREN and WS_CLIPSIBLINGS styles. Additionally, the window class attribute should not include the CS_PARENTDC style."

Which means that according to the official documentation, this commit is actually correct.

More information about the impact of this change is required:
- is this issue specific to Ati cards, or does it also appear on Nvidia / Intel?
- is it possible that this limitation was relaxed on Vista+ (due to the DWM)? If we revert this commit, do we still get correct behavior on WinXP?

**Comment by Krythic** [comment]
As of 5/5/2016, I am still experiencing this bug. It happens when a child window is either behind or in front of the GLControl.
