### ISSUE TITLE
OpenTK.Audio fails to work under Ubuntu 19.10

### ISSUE THREAD

**Issue by morphx666** [opentk/opentk#1002]
### Description

To test the library I created a project using `Visual Studio 2019` that targets `.NET Framework 4.8` using the sample files from the [Parrot](https://github.com/mono/opentk/tree/master/Source/Examples/OpenAL/1.1) audio capture sample.

The sample works just fine under Windows, but when running it under Ubuntu (using mono) it doesn't detect any audio recording devices; that is, `AudioCapture.AvailableDevices` returns an empty list.

I was also able to verify that `OpenTK` doesn't seem to detect under what platform it's running.
Under both Windows and Linux I get these results when querying the values of the `OpenTK.Configuration` class:

```
RunningOnWindows=False
RunningOnX11=False
RunningOnUnix=False
RunningOnSdl2=False
RunningOnLinux=False
RunningOnMacOS=False
RunningOnMono=False
RunningOnAndroid=False
RunningOnIOS=False
```

### Repro steps

1. Create a C# project using Visual Studio which includes the source files from the Parrot sample

2. Install the OpenTK 3.1.0 package from NuGet

3. Compile the project

4. Run the compiled code under Ubuntu

### Expected behavior

- It should detect that the platform it is running on.
- It should detect the audio input devices, just as it does under Windows.

### Actual behavior

- No input/recording devices are detected
- The library doesn't detect under which platform it's running

### Related information 

* Ubuntu 19.10
* OpenTK 3.1.0 (NuGet)
* Project targets .NET Framework 4.8 (I did try several different frameworks)
* mono 5.18.0.240

**Comment by NogginBops** [comment]
What happens if you try to create a graphics context or try to get keyboard or mouse input?
It looks like opentk doesn't find a platform factory to use, so it will probably error out if you try to do anything related to that.

Can you also check what openAL version it reports you are running and check that `Alc.IsExtensionPresent(IntPtr.Zero, "ALC_ENUMERATION_EXT")` and `Alc.IsExtensionPresent(IntPtr.Zero, "ALC_EXT_CAPTURE")` returns true.

**Comment by morphx666** [comment]
Now I got this error (under Ubuntu):

```
Unhandled Exception:
System.DllNotFoundException: openal32.dll
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.Alc.IsExtensionPresent(intptr,string)
  at Parrot.Parrot..ctor () [0x00026] in <ae8e7434066c4110b5edaaafc4b2e216>:0 
  at (wrapper remoting-invoke-with-check) Parrot.Parrot..ctor()
  at Parrot.Parrot.Main () [0x00001] in <ae8e7434066c4110b5edaaafc4b2e216>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: openal32.dll
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.Alc.IsExtensionPresent(intptr,string)
  at Parrot.Parrot..ctor () [0x00026] in <ae8e7434066c4110b5edaaafc4b2e216>:0 
  at (wrapper remoting-invoke-with-check) Parrot.Parrot..ctor()
  at Parrot.Parrot.Main () [0x00001] in <ae8e7434066c4110b5edaaafc4b2e216>:0
```

It seems that OpenTK is defaulting to Windows, since it cannot identify the underlying platform.

**Comment by jvbsl** [comment]
Did you copy the OpenTK.dll.config(or smth like that) to the Output directory. It should contain the dll mappings

**Comment by morphx666** [comment]
No, I hadn't set the "Copy to Output  Directory" option.

The error message now indicates that it cannot find libopenal.so.1

I guess I missing some package?

**Comment by morphx666** [comment]
Querying `apt` for the list of installed packages I get this:

```
libopenal-data/eoan,eoan,now 1:1.19.1-1 all [residual-config]
libopenal-dev/eoan 1:1.19.1-1 amd64
libopenal-dev/eoan 1:1.19.1-1 i386
libopenal1/eoan 1:1.19.1-1 amd64
libopenal1/eoan 1:1.19.1-1 i386
libopenalpr-data/eoan,eoan 2.3.0-1.1 all
libopenalpr-dev/eoan 2.3.0-1.1 amd64
libopenalpr-dev/eoan 2.3.0-1.1 i386
libopenalpr2/eoan 2.3.0-1.1 amd64
libopenalpr2/eoan 2.3.0-1.1 i386
```

**Comment by morphx666** [comment]
Ok, so just installed `libopenal1` and now it's working perfectly.
Thank you so much!
