### ISSUE TITLE
Minimalist OpenTK project structure

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#1005]
Some of these points have been discussed informally in the chat, but I want to consolidate them as an official issue in order to develop and keep track of an integrated proposal to a problem I see in the new OpenTK 4.0 structure.

One of the things that myself, and I'm sure many others, appreciated about the original OpenTK was its minimalism: with a single NuGet package and no extra dependencies the consumer had access to windowing, blazing fast GL bindings, sound, and input.

With the move to .NET Core, the pressure is now high that OpenTK becomes more flexible, and therefore more modular. This is totally understandable and even required by some of the platforms who simply will not support everything. However, I have the feeling that somewhere along the road things went too far: I have counted a total of 24 different assemblies split between Audio, Windowing, Input, and Graphics.

I don't think this is useful in practice, and I want to argue for a return to minimalism in the OpenTK project structure. I propose to split the project across its 4 main axis, with a core DLL simply named OpenTK:

* **OpenTK**
* **OpenTK.Audio**
* **OpenTK.Graphics**
* **OpenTK.Input**
* **OpenTK.Window**

Notice that there is no **OpenTK.Mathematics**. I don't think you can meaningfully decouple the `Vector` and `Matrix` types from the rest of the other modules: they are the glue that binds everything else together in **OpenTK**. Insisting on doing so just introduces additional pain points to everything else unnecessarily. You can think of the **OpenTK** as being **OpenTK.Mathematics**. If you just want to use the **OpenTK** math types, then you simply import the main **OpenTK** library and you have access to them without depending on any windowing, input, audio or graphics bindings.

A brief rundown of what would be in each library:

* **OpenTK.Audio** - All OpenAL bindings (including extensions). These are just managed wrappers, the modularity comes from OpenAL extension system itself, there is no need for the wrapper itself to be micro-modular, especially when OpenAL itself is not evolving much AFAIK.

* **OpenTK.Graphics** - These are the OpenGL bindings, which can for now use the old generator, but in the future will use the new Fody Generator.

* **OpenTK.Input** - This is all the HID stuff.

* **OpenTK.Window** - This contains the windowing library chosen to create and host the OpenTK GameWindow. This assembly will represent the library of choice supported by the OpenTK team to create cross-platform windows. There will be interfaces in place to allow users to bring in their own windowing system and connect it with the graphics bindings, but I don't think our team will have the bandwidth to support multiple implementations.

I was sitting for a while yesterday contemplating the project structure, and this was the only partition that I could come up with that made sense to me, but I most definitely would love to hear feedback and comments/criticisms!

**P.S.:** Note that I used the old namespace **OpenTK** - that was entirely intentional - but please don't take it out on the rest of the proposal

**Comment by subchannel13** [comment]
I'd like to have math types separated from graphics. My particular use case is a game with logic in DLL and GUI in EXE that links that DLL. OpenTK 3.1 in referenced only in GUI part so DLL has homebrew vectors and EXE has conversion methods to plug them to OpenTK. If your proposal of base OpenTK would contain only what is in opentk/src/OpenToolkit.Core/ (I haven't built code locally to check actual assembly) + math stuff, I'd be fine.

**Comment by glopesdev** [comment]
@subchannel13 that was exactly the proposal, the base OpenTK would be just OpenToolkit.Core + OpenToolkit.Mathematics

I agree math types should be separate from graphics, there would be no graphics related APIs in base OpenTK.

**Comment by PJB3005** [comment]
The "more complicated" project structure definitely has a reason behind it. The splitting of the windowing assemblies for example means you can more meaningfully use the API in your own NuGet library (say a library for handling input specially) in a way that's cross-platform (mobile AND desktop). 

Though yes, whether the complexity here will not just fly completely over people's heads is up for debate.

**Comment by glopesdev** [comment]
@PJB3005 I completely agree there was a justified need for splitting up the project structure. For example, re. windowing, the proposal presented here did include splitting up into **OpenTK.Window** and **OpenTK.Input**.

What this issue was targeting were places where it felt to me things were overdone (e.g. OpenTK.Audio previously had 20 different assemblies, one for each extension). I believe many of these have since been addresses. I am close to having back some free time to look into this, so I would be happy to review the issue and update its status.

**Comment by varon** [comment]
@glopesdev  - closing as we basically ended up going with something similar. Also have the metapackage now too.
