### ISSUE TITLE
Refactor OpenAL namespace and assembly names for consistency

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#1006]
### Description

Traditionally, OpenTK namespaces were organized around broad categories before implementation (e.g. `OpenTK.Graphics` for OpenGL, and `OpenTK.Audio` for OpenAL). This placed emphasis on clarity of functionality before implementation.

In the new OpenTK project organization, the OpenAL implementation has been moved into an `OpenTK.OpenAL` namespace / assembly. For consistency I suggest these should be grouped under the namespace `OpenTK.Audio`.

There are two possibilities:
1. Follow OpenTK 3.x convention and refactor to `OpenTK.Audio`;
2. Follow the same convention for graphics bindings and refactor to `OpenTK.Audio.OpenAL`.

To be honest, I would prefer to minimize disruption as a first step, and simply refactor to the namespace `OpenTK.Audio` (or `OpenToolkit.Audio` in the new scheme). This is especially true if the long-term future plans are to stick to OpenAL as the audio implementation. Fortunately OpenAL doesn't have the issue with profiles that OpenGL has, so there is no need to keep nesting namespaces.

**Comment by deccer** [comment]
@glopesdev It feels like we spoke about it already, but I keep forgetting things. Since Noggi is working on OpenAL, would it make sense to close this issue? I believe we found a namespace we are (at least the three of us) are happy about?

**Comment by varon** [comment]
Should be implemented/addressed as best we can.
