### ISSUE TITLE
GL.ObjectLabel always fails with "GL_INVALID_VALUE in glObjectLabel(name = X)"

### ISSUE THREAD

**Issue by arakis** [opentk/opentk#1010]
### Description

Getting always `GL_INVALID_VALUE in glObjectLabel(name = X)` when using `GL.Objectlabel`. But the label is correctly applied (visible in RenderDoc). I don't know how to use/query glGet/GL_MAX_LABEL_LENGTH, there's no GL.Get(). Even if glGet(GL_MAX_LABEL_LENGTH) is 0, how to increase it?

### Repro steps

Please provide the steps required to reproduce the problem

```
var name = "xxx";
GL.ObjectLabel(obj.ObjectLabelIdentifier, obj.Handle, name.Length, name);
```
or
```
var name = "xxx\0";
GL.ObjectLabel(obj.ObjectLabelIdentifier, obj.Handle, -1, name);
```

### Expected behavior

Accepting the label without error/warning.

Reference: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glObjectLabel.xhtml

### Actual behavior

Currently, it's accepting the label (it's visible in RenderDoc), but an error is generated.

### Related information 

* Gentoo
* X11 Backend
* Nuget, OpenTK 3.1
* Mono
* no workaround possible

**Comment by deccer** [comment]
Did you specify Debug in the GameWindow constructor?

**Comment by arakis** [comment]
This was a greate hint! I changed it to Debug. But now, i always get the following crash output:
```
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  83
  Current serial number in output stream:  80
```
My constructor: `base(width, height, GraphicsMode.Default, title, GameWindowFlags.Default, DisplayDevice.Default, 4, 3, GraphicsContextFlags.Debug)`

And the very first line of my `Program.Main()`:
```
            Toolkit.Init(new ToolkitOptions
            {
                Backend = PlatformBackend.PreferX11,
            });
```
(i cannot use SDL, i don't know why, i will never find the backend, even without Debug X11 is working all the time fine, so it's ok for me).

**Comment by deccer** [comment]
Can you check if extension `GL_ARB_debug_output` is supported on your platform? (it should be supported from gl 4.3 onwards)

Also why the specific call to Toolkit.Init?

**Comment by deccer** [comment]
Oh and can you also confirm your current setup supports gl 4.3.

If you happen to be inside a linux vm, running Mesa <20 it wont work for some reason.

**Comment by arakis** [comment]
I got GL.ObjectLabel working. It didn't worked before because the texture/object have to be bound first (at least one time).

But generally, i can't get the app started when using Debug Context. It will immediately crash.

With  Default context, i can confirm, that `GL_ARB_debug_output`  is enabled. Checked this this code:
```
            int numExtensions;
            GL.GetInteger(GetPName.NumExtensions, out numExtensions);
            for (var i = 0; i < numExtensions; i++)
            {
                var extName = GL.GetString(StringNameIndexed.Extensions, i);
                Console.WriteLine(extName);
            }
```

Regarding your `Toolkit.Init` question: Without explicit setting the prefered Backend, i will always get this error:
```
OpenTK.Graphics.GraphicsContextException: Invalid window
  at OpenTK.Platform.SDL2.Sdl2GraphicsContext..ctor
```

And it would be "amazong" to get Debug_output working without using renderdoc.

This is my current setup:
```
            _debugProcCallback = DebugCallback;
            _debugProcCallbackHandle = GCHandle.Alloc(_debugProcCallback);
            GL.DebugMessageCallback(_debugProcCallback, IntPtr.Zero);
            GL.Enable(EnableCap.DebugOutput);
            GL.Enable(EnableCap.DebugOutputSynchronous);
```
After enabling it, i get immidietly a `SIGSEGV` (default context, Debug context isnt working).

I'm not using a VM. It's running on a Thinkpad T580 with Intel UHD 620, Linux `Gentoo`, and this code:
```
            var vendor = GL.GetString(StringName.Vendor);
            var version = GL.GetString(StringName.Version);
            var shadingLanguageVersion = GL.GetString(StringName.ShadingLanguageVersion);
            var renderer = GL.GetString(StringName.Renderer);

            Console.WriteLine($"Vendor: {vendor}, version: {version}, shadinglangVersion: {shadingLanguageVersion}, renderer: {renderer}");
```
produces this output:
```
Vendor: Intel Open Source Technology Center, version: 4.6 (Core Profile) Mesa 19.3.2, shadinglangVersion: 4.60, renderer: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2)
```

**Comment by deccer** [comment]
Im sorry for the late reply. Also thank you for providing all the information.

Are you calling 
```cs
GLFWBindingsContext context = new GLFWBindingsContext();
GL.LoadBindings(context);
```
somewhere by any chance, either in your derived `GameWindow::OnLoad` or in some custom Init method somewhere, before any other call to `GL.*`?

Also since Sdl2 seems to not work for you, and out of curiousity, do you have sdl installed there?

Hmm and about mesa. I am struggling with mesa 19.3 myself, and cant seem to get a context > 3.3 to get running.

**Comment by arakis** [comment]
There's no method `GL.LoadBindings` (Latest official OpenTK nuget package v3.1.0, using GL class in OpenGL4 namespace).

Of course, i have sdl2 installed :-)
```
# Gentoo Linux, all compiled from source
$ equery list mesa libsdl2
[IP-] [  ] media-libs/mesa-19.3.2:0
[IP-] [  ] media-libs/libsdl2-2.0.10:0
```

**Comment by PJB3005** [comment]
@deccer This is for 3.x so GLFW is not relevant.

@arakis the binding for `GL.DebugMessageCallback` is broken in 3.x. See #880 for a workaround.

**Comment by arakis** [comment]
GL.DebugMessageCallback is working in OpenTK4. thx for the hints @deccer and @PJB3005
