### ISSUE TITLE
Making cursor invisible does not lock cursor in window

### ISSUE THREAD

**Issue by RickLadestein** [opentk/opentk#1021]
### Description

When assigning CursorVisible variable in GameWindow the value false, the cursor does not lock itself inside the window and can be moved outside the window. The tutorial says:

`CursorVisible= false; `
After this call, wherever we move the mouse it won't be visible and it should not leave the window. This is perfect for an FPS camera system.

### Repro steps
1. Set CursorVisible to false inside an active window
2. Move cursor outside of window when cursor is invisible

### Expected behavior
Cursor should reset its position after firing a MouseMove event so delta coordinates can be extracted.

### Actual behavior
Cursor location is not locked and can be moved outside of window.

### Related information 

* Operating system: Windows 10 Home
* OpenTK 3.1.0
* .Net framework 4.7.2

### Workarounds
You could manually set mouse position after every MouseMove event but then it fires an extra MouseMove event which causes frame stutter.

**Comment by RickLadestein** [comment]
I dont know if this question has already been answered but i could not find any relevant info on my issue

**Comment by RickLadestein** [comment]
Just did some testing and this issue only occurs for me when i use 3.1.0,
i tried using 3.0.1 and this fixed it.

It seems like this is a bug in the latest version

**Comment by george-tsiros** [comment]
Out of curiosity, how would you move the cursor manually yourself?

**Comment by tyronx** [comment]
I think this is merely a misunderstanding. As of version 3.1.0 the `CursorVisible` does just that, making the cursor invisible. The new `CursorGrabbed` property actually takes care of keeping the cursor centered.

**Comment by RickLadestein** [comment]
Thanks for your reply, i did not know that `CursorGrabbed` had that function.
I was following the tutorial and did some searching but i always had this cursor problem.
I think the tutorial should be updated then.

**Comment by tyronx** [comment]
Good point, I've now made 2 pull requests to update the tutorial and tutorial code. I think this issue can be safely closed now.
