### ISSUE TITLE
Stability of latest master branch

### ISSUE THREAD

**Issue by arakis** [opentk/opentk#1022]
It seems, it's not possible to use the latest official release with .NET Core (correct me, if I'm wrong).

What is the current situation of the latest master branch version? Could it be used for production environments, is it stable, will it be changed heavily in the future? What about a pre-release? (as simply as git Tag).

**Comment by varon** [comment]
Thanks for asking!

It's almost there. We're expecting a pre-release as soon as we get PR #1013 for OpenAL merged in.

As for stability, it's pretty good, but I'd suggest waiting for pre-release packages before you start experimenting with anything beyond test code.

**Comment by arakis** [comment]
I try to port my OpenTK3 App to OpenToolkit4, targeting netcore3.0. I get an AccessViolationException at startup:

![image](https://user-images.githubusercontent.com/1831942/76153058-f6e1b680-60c6-11ea-96ac-fa0f6a0c6d38.png)

Btw.: How to specify the backend like with `Toolkit.Init(new ToolkitOptions { Backend = PlatformBackend.PreferX11 });` in OpenTK3? If you wonder why I need this: I was never able to init the (autodetected) SDL backend when using mesa-19.3.2 on Gentoo (SDL2 is installed, of course).

**Comment by NogginBops** [comment]
@arakis In 4.0 there is only one glfw backend so you won't have the sdl problem. What I think you need to do is init the opengl bindings go get them to work. Should be something like `GL.Init` or something similar, not entirely sure what it is called.

**Comment by arakis** [comment]
I'm sure you mean LoadBindings. But `GL.LoadBindings(new OpenToolkit.GraphicsLibraryFramework.GLFWBindingsContext())` will not help. I call it very early. As soon I make any OpenGL calls, I ran into an AccessViolationException. System: Windows, .NET core app 3.0, x64.

Don't get me wrong. My primary problem is not with Windowing or SDL. A window is opening and visible (but all white). My Primary problem is, even a simple GL.ClearColor call will not work.

**Comment by NepNet** [comment]
I had a similar problem when I tried to draw inside a gtk widget as a workaround I created a GameWindow in an async bubble and destroy it then on the realized event of the said gtk widget made it's context current and it works, not sure if that's the best aproach but seems that I can't load the gl bindings with the context created by gtk as current

**Comment by varon** [comment]
@arakis / @NepNet  - 99% of the time this is due to the bindings not being loaded correctly.

@arakis  - you're 100% right on the method call, but the timing for it can be somewhat important.
The preconditions for it to work are:
- There must be a created OpenGL context.
- The OpenGL Context must be _current_.
- If you are using `new OpenToolkit.GraphicsLibraryFramework.GLFWBindingsContext()`, then it needs to be called after all of the GLFW windowing/context has been set up.
- If you are using another framework @NepNet - you might need to create your own implementation of `IBindingsContext` that calls to the appropriate `getProcAddress`.

**Comment by arakis** [comment]
The way sounds interesting. But there are not any samples for the new framework. The only samples (Tests) in the master branch have the only todo with windowing itself.

So it would be super sweet of you could provide a small piece of code, that does the following in the end result:

- Showing window
- Called GL.ClearColor(blue) to see a blue OpenGL scene (Please, no Triangle :-D )
In the best case, the sample code should run both on Windows and Linux.

I think that's all that I need to get my OpenTK4 Migration running.

**Comment by varon** [comment]
@frederikja163 
@deccer 

Have working examples. I'm pretty sure they can help here.

**Comment by frederikja163** [comment]
https://github.com/frederikja163/VoxelEngine
Not really an example to say, but it works just fine

You need to make sure you are creating the opengl context on the thread you call the opengl functions from. And you need to make sure glfw has been inititalized

**Comment by arakis** [comment]
I can confirm that the latest master is now quiet stable. I got all stuff working several days ago. Thx @varon for the hints.
