### ISSUE TITLE
DllNotFoundException: openal32.dll when using OpenAL with OpenTK3

### ISSUE THREAD

**Issue by arakis** [opentk/opentk#1023]
### Description

Can't create `AudioContext`.

### Repro steps

Create an Instance of AudioContext:
```c#
public static void Main(string[] args)
{
    AudioContext context = new AudioContext();
}
```

Optional: Create a config File (OpenTK.dll.config or MyApp.exe.config):
```xml
<configuration>
  <dllmap os="linux" dll="openal.dll" target="/usr/lib64/libopenal.so.1"/>
</configuration>
```
(`/usr/lib64/libopenal.so.1` exists. And the OS is 64 bit, mono is running the app 64 bit, too).

### Expected behavior

A working AudioContext.

### Actual behavior

I get this error:
System.DllNotFoundException: openal32.dll

### Related information 

* Operating system: Linux Gentoo
* X11 backend, openal.so.1 installed
* OpenTK 3 (latest official)
* What runtime: Mono

**Comment by Vassalware** [comment]
I'm not sure if it'll help, but it looks like the error is regarding `openal32.dll`, but you're remapping `openal.dll`. Have you tried remapping `openal32.dll` instead?

**Comment by Agusss19** [comment]
Same issue here, using the same code you posted.

**Related Information**
- MacOSx HighSierra 10.13.6
- OpenTK 3.1.0 (latest official)

**Comment by NogginBops** [comment]
@arakis, @Agusss19 have you tried what Vassalware was suggesting above? To me that looks like that is what is happening here.

**Comment by Agusss19** [comment]
@NogginBops yes, I did it and it didn't work. I will post you all the code:

**Environment**

- .Net Core 3.1.101
- MacOSx HighSierra 10.13.6
- OpenTK 3.1.0 (latest official)

**.csproj**
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="3.1.0" NoWarn="NU1701"/>
    <None Include="OpenTK.dll.config" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
```

**Main.cs**
```csharp
public static void Main(string[] args)
{
    AudioContext context = new AudioContext();
}
```

**OpenTK.dll.config**
```xml
<configuration>
  <dllmap os="linux" dll="opengl32.dll" target="libGL.so.1"/>
  <dllmap os="linux" dll="glu32.dll" target="libGLU.so.1"/>
  <dllmap os="linux" dll="openal32.dll" target="libopenal.so.1"/>
  <dllmap os="linux" dll="alut.dll" target="libalut.so.0"/>
  <dllmap os="linux" dll="opencl.dll" target="libOpenCL.so"/>
  <dllmap os="linux" dll="libX11" target="libX11.so.6"/>
  <dllmap os="linux" dll="libXi" target="libXi.so.6"/>
  <dllmap os="linux" dll="SDL2.dll" target="libSDL2-2.0.so.0"/>
  <dllmap os="osx" dll="opengl32.dll" target="/System/Library/Frameworks/OpenGL.framework/OpenGL"/>
  <dllmap os="osx" dll="openal32.dll" target="/System/Library/Frameworks/OpenAL.framework/OpenAL" />
  <dllmap os="osx" dll="alut.dll" target="/System/Library/Frameworks/OpenAL.framework/OpenAL" />
  <dllmap os="osx" dll="libGLES.dll" target="/System/Library/Frameworks/OpenGLES.framework/OpenGLES" />
  <dllmap os="osx" dll="libGLESv1_CM.dll" target="/System/Library/Frameworks/OpenGLES.framework/OpenGLES" />
  <dllmap os="osx" dll="libGLESv2.dll" target="/System/Library/Frameworks/OpenGLES.framework/OpenGLES" />
  <dllmap os="osx" dll="opencl.dll" target="/System/Library/Frameworks/OpenCL.framework/OpenCL"/>
  <dllmap os="osx" dll="SDL2.dll" target="libSDL2.dylib"/>
  <!-- XQuartz compatibility (X11 on Mac) -->
  <dllmap os="osx" dll="libGL.so.1" target="/usr/X11/lib/libGL.dylib"/>
  <dllmap os="osx" dll="libX11" target="/usr/X11/lib/libX11.dylib"/>
  <dllmap os="osx" dll="libXcursor.so.1" target="/usr/X11/lib/libXcursor.dylib"/>
  <dllmap os="osx" dll="libXi" target="/usr/X11/lib/libXi.dylib"/>
  <dllmap os="osx" dll="libXinerama" target="/usr/X11/lib/libXinerama.dylib"/>
  <dllmap os="osx" dll="libXrandr.so.2" target="/usr/X11/lib/libXrandr.dylib"/>
</configuration>
```

**Comment by NogginBops** [comment]
@Agusss19  You problem here is that you are using opentk 3.1 with .NET core. This is not supported. Either you wait for the release of opentk 4.0 or you switch to .NET framework and use mono. Also, dllmap is not supported in .NET core either so providing one won't help when using core.

**Comment by Agusss19** [comment]
@NogginBops I was suspecting .net core was the cause. Opentk graphics stuff works very well with .net core in macOS so I belived audio stuff was going to work too. By the way, thanks for the answers I will wait for OpenTK 4.0.

**Comment by NogginBops** [comment]
@Agusss19 It's actually interesting that opentk 3.1 (opengl) works well with .net core on macos and openal doesn't... It's probably got to do with the fact that openal uses dllimport while opengl doesn't. If you want to try to get openal working you could try compiling openal-soft, rename it to `openal32.dylib` and place it in the executable path. That might get the dllimport to find the library.

**Comment by tyronx** [comment]
This issue can be closed, no?

**Comment by jvbsl** [comment]
I guess so. Thanks for all the help
