### ISSUE TITLE
Provide better package descriptions

### ISSUE THREAD

**Issue by xPaw** [opentk/opentk#1026]
v4 splits opentk into multiple separate packages, but they all have the exact same description as can be seen here: https://www.nuget.org/packages?q=opentoolkit

As a result, it's harder than it should be to tell which packages I need.

**Comment by varon** [comment]
Thanks for the suggestion.

The general expectation is you'll just install the MetaPackage which bundles everything you need.
https://www.nuget.org/packages/OpenTK

Definitely this is something we can improve going forwards, and would love some help in getting this sorted.

**Comment by varon** [comment]
Fixed by #1049
