### ISSUE TITLE
MouseButton.Right and MouseButton.Middle are swapped

### ISSUE THREAD

**Issue by GeorchW** [opentk/opentk#1030]
### Description

In the GameWindow.MouseDown and MouseUp events, the MouseButton provided by the OpenToolkit.Windowing.Common.MouseButtonEventArgs parameter are providing wrong values in the Button property: when pressing/releasing the middle mouse button (wheel), MouseButton.Right is returned, and vice versa.

### Repro steps

1. Create a GameWindow
2. Hook into the MouseUp and MouseDown events and log the MouseButtonEventArgs.Button property

Example code: 
```csharp
var gameWindow = new GameWindow(GameWindowSettings.Default, NativeWindowSettings.Default);
gameWindow.MouseDown += e => Console.WriteLine(e.Button + " down");
gameWindow.MouseUp += e => Console.WriteLine(e.Button + " up");
gameWindow.Run();
```

### Expected behavior

MouseButton.Right is returned when pressing/releasing the right mouse button.

MouseButton.Middle is returned when pressing/releasing the middle mouse button (usually the wheel).

### Actual behavior

MouseButton.Middle is returned when pressing/releasing the right mouse button.

MouseButton.Right is returned when pressing/releasing the middle mouse button (usually the wheel).

### Related information 

* Operating system: Linux/GLFW
* OpenTK 4.0.0-pre3
* dotnetcore 3.1.103

**Comment by GeorchW** [comment]
I've just looked it up - OpenTK has it the other way around [(enum definition)](https://github.com/opentk/opentk/blob/d5b45e9161b0b88e092abf85716353f6b24015f6/src/OpenToolkit.Windowing.Common/Input/Enums/MouseButton.cs#L25) than GLFW does [(docs)](https://www.glfw.org/docs/latest/group__buttons.html).

Two possibilities for solving this: either swap the enum values, or flip them around in the callback from GLFW [(here)](https://github.com/opentk/opentk/blob/d5b45e9161b0b88e092abf85716353f6b24015f6/src/OpenToolkit.Windowing.Desktop/NativeWindow.cs#L684). I guess the former is more attractive, given that not many people rely on the OpenTK 4.0 enum values yet.

**Comment by NogginBops** [comment]
Yeah they should be corrected in opentk. If you would like you can open a or with the change, should be a pretty easy change to make. But it's you don't want to create the pr that's fine (just say that you won't do it so someone else feels like they are able to :) ).

**Comment by GeorchW** [comment]
Am I getting you right that the enums should be adapted? If yes, then I can make a PR, sure. If that's the case I guess we should also make Left an alias for MouseButton1 etc., copying the GLFW behaviour.

**Comment by varon** [comment]
We want to match GLFW behaviour. Would love a PR on this.
