### ISSUE TITLE
excess functionality in GL.DrawArrays

### ISSUE THREAD

**Issue by mertwole** [opentk/opentk#1031]
this is valid code in OpenTK:
GL.DrawArrays(PrimitiveType.Quads, 0, 4);
but invalid in OpenGL because 

> mode
> Specifies what kind of primitives to render. Symbolic constants GL_POINTS, GL_LINE_STRIP, GL_LINE_LOOP, GL_LINES, GL_LINE_STRIP_ADJACENCY, GL_LINES_ADJACENCY, GL_TRIANGLE_STRIP, GL_TRIANGLE_FAN, GL_TRIANGLES, GL_TRIANGLE_STRIP_ADJACENCY, GL_TRIANGLES_ADJACENCY and GL_PATCHES are accepted.

I think wrapper shouldn't provide excess functionality (i was surprized that glDrawArrays(GL_QUADS, 0, 4); throws GL_INVALID_ENUM in OpenGL and spent 20 minutes on debugging)

**Comment by varon** [comment]
Thanks for the report.


This matches the documentation/expected behaviour pretty accurately. What would you suggest?

**Comment by varon** [comment]
(Keeping in mind that the `PrimitiveTypes` enum is used in a bunch of other places where `PrimitiveType.Quads` is actually accepted.

**Comment by mertwole** [comment]
But OpenTK dont have separate documentation as i know and therefore implementation should accurately match official documentation, shouldn't it? At the moment its unclear how QUADS are actually implemented in OpenTK without reading source code.

**Comment by varon** [comment]
In C-OpenGL, those are ints. You can provide any value you like to `glDrawArrays` - if it's wrong you'll get a runtime error.
