### ISSUE TITLE
Improve Box Primitives

### ISSUE THREAD

**Issue by arakis** [opentk/opentk#1033]
OpenTK ships with powerful Mathematics namespace, it's even useful if you're not using OpenGL Graphics. Especially Matrix and Vertex structs are very mature.

But I'm not very happy with the Box primitives, especially Box2. This are my first thoughts:
- No X, Y, Right or Bottom property without accessing Min or Max struct.
- the constructor takes min, max instead of location, size.
- there's even no static FromSize method (as an alternative)
- No Width or Height Property (or SizeX/SizeY).
- No Zero/Empty (Default) Property like with Vector.Zero.
- an "Identity" static property could make sense, too. (0,0,1,1)

The question is:
- What will be more used, if you construct a box, location, size or min,max?
- What will the developer normally expect? Especially if you need to convert stuff between Box2 and Rect of other libraries.
- Maybe Box2 is not a "Rect" in classic meaning? But even Window.ClientRectangle uses Box2.

As I told in the beginning, most primitives are very mature. So you can use them in nearly every place as "primary" struct and use only third-party structs for their interfaces. So, in most cases, you don't need to convert them very often. Even the harmony within OpenTk.Mathematics is very well.

So it would be a shame to implement a custom Rect struct because of some small details.

One reason for the min,max maybe that it needs compatible with box3 or box4. For box3 you can use: Left, Right, Top, Bottom, Front, Back. For Box4, no idea. This may not be homogenous than, but it's an acceptable tradeoff.

Let's discuss what we should do now. I would be fully responsible for creating a PR after we decided what changes we want. Because we're still in Preview, it's not too late to make changes on Box2.

**Comment by varon** [comment]
The reason we decided upon these, from what I can recall, is that Box2 uses integers.

What happens if you set the size to 3? Our current system, as best we can avoids this.

**Comment by NogginBops** [comment]
@varon We have `Box2` (uses float), `Box2d` (uses double) and `Box2i` (ints). We also have these with `Box3/Box3d/Box3i` for 3 dimensions.

I like the position/size setup more. And think that that could also apply to `Box3` as well, unless there is a good reason for the min/max versions.

I think that the min/max should be converted into properties instead (get and set) and then we can move the internal representation to position/size.

**Comment by Vassalware** [comment]
I'm entirely for moving these types to store position and size as state, and adding properties and functions to fill the gaps and add the missing features.

I definitely think position and size is more in-line with what you'd expect from a type like this.

One comment, though: I'm not sure what an 'Identity' property would mean on a box-like object. To me, "Identity" means something in the context of a specific operation. I'm not sure what operation that would be for a box.

**Comment by NogginBops** [comment]
There is the concept of a unit cube (Cube with all sides 1). That could be extended to `Box2` by having a square with side 1. That would be the closest to an identity I can imagine. There could also be the zero size rect/cube at position zero, but that is less useful imo.

**Comment by arakis** [comment]
@NogginBops got the point of Identity property. But in general, this is optional and the main complaint is not having position/size style.

Generally, you can say, the position/size style is an unwritten "standard".

So, if nobody as no doubts anymore, I will start with the Box migrations and do a PR then.

**Comment by frederikja163** [comment]
The reason we went with min/max for the internal storage last time was because of perfomance for collision detection

**Comment by arakis** [comment]
Here's my first draft: #1037

**Comment by varon** [comment]
Closing, as we now have an open PR for this.
