### ISSUE TITLE
Can't create any shape

### ISSUE THREAD

**Issue by Gionson13** [opentk/opentk#1035]
### Description

I'm trying to make a square in OpenTK 4 but it doesn't render.

I tried other shapes and it doesn't work
### Repro steps

Here's the code:
```
namespace program
{
    class Program
    {

        private static GameWindow window

        static void Main(string[] args)
        {
            window = new GameWindow(GameWindowSettings.Default, NativeWindowSettings.Default);
            window.UpdateFrame += Update;
            window.RenderFrame += Render;
            window.Load += Setup;
            window.Run();
        }

        private static void Setup()
        {
            GLFWBindingsContext context = new GLFWBindingsContext();
            GL.LoadBindings(context);
            GL.ClearColor(Color4.Red);
        }

        private static void Update(FrameEventArgs obj)
        {
        }

        private static void Render(FrameEventArgs obj)
        {
            GL.Clear(ClearBufferMask.ColorBufferBit);

            GL.Begin(PrimitiveType.Quads);

            GL.Color3(Color.Blue);
            GL.Vertex2(0, 0);
            GL.Vertex2(1, 0);
            GL.Vertex2(1, -1);
            GL.Vertex2(0, -1);

            GL.End();

            window.SwapBuffers();
        }
}
```

### Expected behavior

It should draw a blue rectangle in a red space (background)

### Actual behavior

It draws a red space (background) without the blue rectangle

### Related information 

* Windows 10
* OpenTK 4.0.0-pre4
* .NET Framework

**Comment by NogginBops** [comment]
You are using the fixed function pipeline that was deprecated since OpenGL 3+, and has generally not been used since like ~2000. Modern GL doesn't support `Quad` primitives, so it can't be expected to work.

I recommend following the OpenGL tutorial on [learnopengl.com](learnopengl.com) if you are new to OpenGL. (You can also join our discord to get more realtime help)

**Comment by ThomasD13** [comment]
I tried the same before 2 years with OpenTK 3.0. The result was, just do it with Triangles, Quads do not work.
As NogginBops suggested, I would also highly suggest that you don't use the old fixed pipeline anymore.

**Comment by PJB3005** [comment]
I should note: the fixed function pipeline totally should still work. You will however have to request a compatibility OpenGL context explicitly, as OpenTK 4 defaults to Core profile.

Example code:

```cs
var settings = NativeWindowSettings.Default;

settings.Profile = ContextProfile.Compatability;
settings.APIVersion = new Version(3, 2);

window = new GameWindow(GameWindowSettings.Default, settings);
```
