### ISSUE TITLE
No way to free context in multi-threaded GameWindow (4.0.0-pre9)

### ISSUE THREAD

**Issue by aschuhardt** [opentk/opentk#1052]
### Description

There is no `Context` property accessible from within a class inheriting from `GameWindow`.

Because of this I cannot see a way to make multithreading work; there's no way to call `Context.MakeCurrent(0)` at the end of a function to free the GL context for other threads to use.

Calling `MakeCurrent` will always result in an Exception as the context can't be free'd.

### Repro steps

1. Create a new project, add the below class and call .Run() on a new instance of it:

```
    class ExampleWindow : GameWindow
    {
        public ExampleWindow() : base(
            new GameWindowSettings { IsMultiThreaded = true },
            new NativeWindowSettings())
        {
        }

        protected override void OnRenderFrame(FrameEventArgs args)
        {
            MakeCurrent();
            base.OnRenderFrame(args);
        }
    }
```

### Expected behavior

I expect to see a new window with no exceptions thrown.

### Actual behavior

```
OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWException
  HResult=0x80131500
  Message=WGL: Failed to make context current: The requested resource is in use. 
  Source=OpenToolkit.Windowing.Desktop
  StackTrace:
   at OpenToolkit.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__5_0(ErrorCode errorCode, String description)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.glfwMakeContextCurrent(Window* window)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFW.MakeContextCurrent(Window* window)
   at OpenToolkit.Windowing.Desktop.NativeWindow.MakeCurrent()
```

### Related information 

* Operating system: Windows 10 64-bit
* OpenTK version: 4.0.0-pre9
* Runtime: CoreCLR

**Comment by jvbsl** [comment]
While I already found the problem why it crashes and have a fix for it(only locally for now). Do you have a suggestion how MakeContextCurrent(null) could look?
Currently we do not have a Context class and in my opinion it does not make sense to have a function for that inside NativeWindow, as it is independant of the window itself.
Readding a Context class, or any better ideas?

**Comment by aschuhardt** [comment]
On Sun, May 03, 2020 at 03:51:49AM -0700, jvbsl wrote:
> While I already found the problem why it crashes and have a fix for it(only locally for now). Do you have a suggestion how MakeContextCurrent(null) could look?
> Currently we do not have a Context class and in my opinion it does not make sense to have a function for that inside NativeWindow, as it is independant of the window itself.
> Readding a Context class, or any better ideas?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/opentk/opentk/issues/1052#issuecomment-623090811

I don't have anything to add here, I am not sure what the best way to
approach this would be.
