### ISSUE TITLE
Changing ClientSize of a GameWindow does not change the Width and Height on Linux

### ISSUE THREAD

**Issue by Trashtalk217** [opentk/opentk#1053]
### Description

When adjusting the ClientSize of a GameWindow on Linux, the Width and Height do not change with it.

### Repro steps

I've made a minimum working example project that you can see [here](https://github.com/Trashtalk217/OpenTK-bug), but the problem lies in this snippet:

#### Case 1
```
using System;
using System.Drawing;
using OpenTK;

namespace Template
{
    public class OpenTKApp : GameWindow
    {
        protected override void OnLoad(EventArgs e)
        {
            Console.WriteLine(Width.ToString() + " " + Height.ToString());
            ClientSize = new Size(1200, 800);
            Console.WriteLine(Width.ToString() + " " + Height.ToString());
            Height = 800;
            Width = 1200;
            Console.WriteLine(Width.ToString() + " " + Height.ToString());
        }

        public static void Main(string[] args)
        {
            // entry point
            using (OpenTKApp app = new OpenTKApp()) { app.Run(30.0, 0.0); }
        }
    }
}
```
There are also some other permutations of this code which cause problems, for which I'll provide the OnLoad methods from this point, the rest stays the same.

#### Case 2
```
protected override void OnLoad(EventArgs e)
{
    Console.WriteLine(Width.ToString() + " " + Height.ToString());
    ClientSize = new Size(1200, 800);
    Console.WriteLine(Width.ToString() + " " + Height.ToString());
}
```
#### Case 3
```
protected override void OnLoad(EventArgs e)
{
    Console.WriteLine(Width.ToString() + " " + Height.ToString());
    Height = 800;
    Width = 1200;
    Console.WriteLine(Width.ToString() + " " + Height.ToString());
}
```

### Expected behavior

I've tested these three cases on Windows and I've gotten the following expected results.

#### Case 1
````
960 720
1200 800
1200 800
````
#### Case 2
````
960 720
1200 800
````
#### Case 3
````
960 720
1200 800
````
And all the windows created were the same size.

### Actual behavior
On Linux the behaviour was as follows:

#### Case 1
````
640 480
640 480
1200 800
````
#### Case 2
````
640 480
640 480
````
#### Case 3
````
640 480
1200 480 // !!!
````
The interesting thing here was that, while the Width and Height was unchanged in Case 2 the window created did have the right size, just like in Case 1. But in Case 3 the Height for some reason decided that it didn't want to update. And I got a very wide window out of that.

### Related information 

I'm using Linux Mint with the Cinnamon desktop environment. I also used OpenTK version 3.2, gotten through NuGet. I compiled it through Mono and Case 1 in the examples is probably a decent workaround, even though it doesn't mirror the Windows behaviour it does eventually get there.

If you need help reproducing the bug, or think that I forgot something, please ask. I'll be glad to help out hunting down this bug.

**Comment by Trashtalk217** [comment]
I've put my workaround and put it into a method, for anyone else to use with the same problem.
```
private void SetTrueSize(int width, int height)
{
    ClientSize = new Size(width, height);
    Width = width;
    Height = height;
}
```
It's flimsy, inelegant and annoying, but it works.

**Comment by Trashtalk217** [comment]
This bug is weird. I've been looking more into it and found that Width and Height sometimes just don't work  at all.

I've got a separate project that is very similar to the minimal working example I've shared before. There's just slightly more stuff. When I implement the fix I've previously shared, it does work. It however works **most** of the time. I've started and closed the project 28 times and 23 times I got the right resolution: 1200 x 800. The other 5 times I got 1200 x 480, meaning that the Height variable decided to not update.

I've also tested this in my bug report project, so you can test it yourself. It did seem a bit more rare. I've tested 72 times, give or take one. And it worked well 71 times. One time I however got a 640 x 800 resolution, so the Width decided to not update this time.

This is werid, like, really weird and I hope anyone has any clue what could be going on.

**Comment by Trashtalk217** [comment]
@NogginBops, has mentioned in the discord, that changing ClientSize shouldn't have any effect since the setter is empty: [source](https://github.com/opentk/opentk/blob/3.x/src/OpenTK/Platform/Linux/LinuxNativeWindow.cs#L498)

**Comment by RNG42** [comment]
`public static void Main(string[] args)
{
	// entry point
	using (OpenTKApp app = new OpenTKApp()) 
	{ 
		app.ClientSize = new Size(1200, 800);
		app.Run(30.0, 0.0);
	}
}`

You can try it this way, should work fine.

**Comment by varon** [comment]
This should be fixed in 4.x, especially with some recent improvements we made.
