### ISSUE TITLE
System.AccessViolationException (Does openTK run on vb.net?)

### ISSUE THREAD

**Issue by tcaudilllg** [opentk/opentk#1054]
### Description

I can't create a shader using openTK in vb.net

### Repro steps

Please provide the steps required to reproduce the problem

1.         VertexShaderID = OpenGL.GL.CreateShader(OpenGL.ShaderType.VertexShader)

### Expected behavior

create shader

### Actual behavior

System.AccessViolationException at that line

### Related information 

I've seen few examples showing openTK running on vb.net, only C#. Can openTK use shaders on vb.net?

Does

* Windows 10
* Native
* NuGet 3.1, GLcontrol 3.1
* .NET Framework 3.5
* Workarounds (if any)

**Comment by jvbsl** [comment]
We'd need a little more information about the project, I'm pretty sure creating the shader isn't the only thing you do, what calls to opentk do you do before that?

**Comment by tcaudilllg** [comment]
None. I create the control and load the shader text from file, then the shader creation.

**Comment by NogginBops** [comment]
If you could send us a repro that would be great. 
Often `AccessViolationException`s don't happen exactly where they are reported. 
Often they are related to drawing to many vertices than the bound buffer has, leading to reading out of bounds.

**Comment by tcaudilllg** [comment]
Imports System
Imports System.IO
Imports System.Windows.Forms
Imports OpenTK
Imports OpenTK.Graphics
Imports OpenTK.Graphics.OpenGL
Imports OpenTK.Graphics.OpenGL4
Imports OpenTK.Platform
Imports OpenTK.Platform.Windows




Public Class Form1


    Dim GLcontext As OpenTK.GLControl
    Dim verticesGL() As Integer = { _
-1, -1, -1, 0, 0, -1, 1, -1, -1, 0, 0, -1, 1, 1, -1, 0, 0, -1, _
1, 1, -1, 0, 0, -1, -1, 1, -1, 0, 0, -1, -1, -1, -1, 0, 0, -1}
    Dim VertexShaderID As Integer
    Dim FragmentShaderID As Integer
    Dim ProgramID As Integer


    Public Sub Initialize()

        GLcontext = New GLControl

        Dim VertexShaderStr As String
        Dim FragmentShaderStr As String
        Try
            'VertexShaderStr = File.ReadAllText("Simple_VS.glsl")
            'FragmentShaderStr = File.ReadAllText("Simple_FS.glsl")
        Catch
            MsgBox("failed read")
        End Try
        MsgBox("check")
        ' VertexShaderID = OpenGL.GL.CreateShader(OpenGL.ShaderType.VertexShader)
        ' OpenGL.GL.ShaderSource(VertexShaderID, VertexShaderStr)
        ' OpenGL.GL.CompileShader(VertexShaderID)

        VertexShaderStr = "void main()\n{\n    gl_Position = vPosition;\n}\n"

        FragmentShaderStr = "\nvoid main()\n{\ngl_FragColor = vec4(0,0,0,1);\n}\n"
        Dim FragmentShaderID As Integer = OpenGL4.GL.CreateShader(OpenGL4.ShaderType.FragmentShader)
        'OpenGL.GL.ShaderSource(FragmentShaderID, FragmentShaderStr)
        'OpenGL.GL.CompileShader(FragmentShaderID)

        'ProgramID = OpenGL.GL.CreateProgram
        'OpenGL.GL.AttachShader(ProgramID, VertexShaderID)
        ' OpenGL.GL.AttachShader(ProgramID, FragmentShaderID)
        'OpenGL.GL.LinkProgram(ProgramID)


    End Sub

    Private Sub Form1_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Me.SetStyle(ControlStyles.AllPaintingInWmPaint Or ControlStyles.Opaque, True) 'Do not draw form?s background\
        Me.Height = 953
        Me.Width = 1150
        Me.Text = "test"
        Me.TopMost = True

        Initialize()


    End Sub


    Private Sub Form1_Paint(ByVal sender As Object, ByVal e As System.Windows.Forms.PaintEventArgs) 'Handles Me.Paint


    End Sub
End Class

**Comment by jvbsl** [comment]
Try using the HandleCreated-Event of the GLControl for OpenGL initialization stuff, and not the Initialize method

**Comment by varon** [comment]
VB is unsupported.
