### ISSUE TITLE
Possible to exclude parts from compile or build? Compile or build only parts?

### ISSUE THREAD

**Issue by george-tsiros** [opentk/opentk#1056]
Suppose a subset of OpenTK such that it remains internally consistent. 

Is it feasible to compile only that subset of OpenTK?

For example, if I do not plan on using any of the OpenAL types/bindings, may I build OpenTK without OpenAL?

Thank you for your time and attention.

**Comment by NogginBops** [comment]
What version of OpenTK are you thinking of? In OpenTK 3.x it all gets bundled into one dll, but you could possibly remove the openal from source and rebuild it locally and get what you want.
If you are thinking about the OpenTK 4, the preview packages are already split into smaller components like math, opengl, and openal. So there you just have to reference the nuget packages you want and leave the ones you don't want.

**Comment by george-tsiros** [comment]
I managed to hack it so that anything non-windows or non-openGL4 is excluded. Debug dll dropped from 5ish MB to 2.2 MB. Would be nice if i could build only the parts that the program uses, but that's further down the line.

**Comment by varon** [comment]
Closing. OpenTK 4.x is now modular.
