### ISSUE TITLE
4.0-pre9.1 GameWindow WindowBorder set doesn't affect resize

### ISSUE THREAD

**Issue by jorisdg** [opentk/opentk#1057]
### Description

Setting the window border when instantiating gamewindow works. But changing it after instantiation doesn't seem to have any effect.

### Repro steps

Setting WindowBorder anywhere outside of the settings passed in the constructor has no effect on the behavior of the window. Simplest possible code below. But even setting the border during an update frame or whatever doesn't change the resizing behavior.

public class Window : GameWindow
{
        public Window()
            : base(GameWindowSettings.Default, NativeWindowSettings.Default)
        {
             WindowBorder = WindowBorder.Fixed;
        }
}

### Expected behavior

WindowBorder is get/set, so expect window to stop/start allowing resize when changed.

### Actual behavior

Only the initial state passed into the constructor with the native settings is applied.

### Related information 

* Windows 10
* Native backend
* NuGet 4.0.0-pre9.1
* .NET Core 3.1

**Comment by NogginBops** [comment]
@jorisdg is this issue solved in 4.0.3?

**Comment by jorisdg** [comment]
Thanks for pinging me. I confirmed it is now working as expected in 4.0.3! Thank you!

**Comment by varon** [comment]
Should be solved.
