### ISSUE TITLE
LoadBindings ist not working (4.0.0-pre.10)

### ISSUE THREAD

**Issue by Eric-Arz** [opentk/opentk#1060]
### Description

I was trying to render into a Gtk# GLArea using OpenTK. I wasn't able to initialize the OpenGL bindings without having to create a OpenTK dummy window first. Toolkit.Init() seems to have been removed and i am not able to get OpenTK 4.0 to work with Gtk#.

### Repro steps

```
using Gtk;
using OpenToolkit.Graphics.OpenGL4;
using OpenToolkit.Windowing.GraphicsLibraryFramework;

namespace OpenTK_GTK_
{
	class Viewport : GLArea
	{
		protected override bool OnRender(Gdk.GLContext context)
		{
			GL.ClearColor(0.3f, 0.3f, 0.3f, 1.0f);
			GL.Clear(ClearBufferMask.ColorBufferBit);

			return true;
		}
	}

	class MainWindow : Gtk.Window
	{
		public MainWindow() : base(WindowType.Toplevel)
		{
			this.Add(new Viewport());
		}
	}

	class Program
	{
		static void Main(string[] args)
		{
			GLFW.Init();
			GL.LoadBindings(new GLFWBindingsContext());

			Application.Init();

			var window = new MainWindow();
			window.ShowAll();

			Application.Run();
		}
	}
}
```

### Expected behavior

OpenTK GL.* functions being initialized and the window getting cleared with the specified color.

### Actual behavior

Application just terminates after the first call to GL.ClearColor. 

If i replace `GLFW.Init(); GL.LoadBindings(new GLFWBindingsContext());` with the creation of a dummy GameWindow everything works as it should. 

Initializing OpenTk without creating a window seems not to be possible at the moment.

### Related information 

Windows 10 and Ubuntu 19 + .NetCore 3.0

**Comment by NepNet** [comment]
It is possible but you need to make another BindingsContext, for example for Linux you can just make a class that Extends IBindingsContext and add those 3 lines 
`public IntPtr GetProcAddress(string procName) => glXGetProcAddress(procName);
[DllImport("libGL", CharSet = CharSet.Ansi)]
private static extern IntPtr glXGetProcAddress(string procName);`
as for windows I tried with glwGetProcAddress in opengl32 but doesn't seems to works properly even with an active context. While glX doesn't need an opengl context wgl does

**Comment by Eric-Arz** [comment]
@NepNet This is not a clean cross platform solution. I worked with OpenGL bindings in other languages before. Initializing the bindings is something that should be a 1-liner provided by the library.

**Comment by jvbsl** [comment]
Well like all cross platform solutions it is a one liner for the cases it is implemented for. As we use GLFW we do not currently have the possibility to provide a way for creating a context for external windows. So either we implement that in OpenTK, or we provide a solution, with which everyone can implement those special cases themselves. Ofc it would be desireable to have a one line solution for everything, but unfortunately there is some work involved. E.g. for WinForms it currently means either using another native library backend for context creation, or implementing the functionality completely in C#

**Comment by Eric-Arz** [comment]
@jvbsl I am not talking about creating a context for an external window, i am talking about loading the GL functions so you can use OpenTK with other window systems that provide their own context.

**Comment by varon** [comment]
@Eric-Arz  - this is very easy to achieve. See #1097 and #1155 .

**Comment by varon** [comment]
If this is still an issue with 4.3.0+, please re-open it.
