### ISSUE TITLE
Missing compressed formats in the SizedInternalFormat enum

### ISSUE THREAD

**Issue by Cyphall** [opentk/opentk#1061]
Functions like `GL.TexStorage2D` can only work with sized internal formats.
However, with some personal testing, I figured this function can work with compressed formats, and with some research, I found that these compressed formats are indeed listed on the [glTexStorage2D wiki page](https://www.khronos.org/opengl/wiki/GLAPI/glTexStorage2D).

Could these formats be added to the SizedInternalFormat enum?

Note: I don't know if other GL functions also use sized-only formats, and I don't know if these functions can also handle compressed formats. This might be worth checking before making the modification.

EDIT: OpenTK version 4.0.0-pre9.1

**Comment by NogginBops** [comment]
I agree that we want to have the compressed formats be available without casting when using `GL.TexStorage2D`.

I think this is a thing that is missing in Khronos official xml definitions.
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml
There are three different categories of values that can be passed as an internal format, where one of them is the compressed formats. 
So the compressed formats I don't think are considered a sized internal format but are rather their own category (compressed formats).

As a workaround you could pass a compressed format from the compressed format enum and cast it to a `SizedInternalFormat`.

Ps. 
You really should include the OpenTK version you are talking about.

**Comment by NogginBops** [comment]
There are other functions that use `SizedInternalFormat` that can't deal with compressed formats. Also, according the specification only "Copyable" compressed formats are allowed in the `glTexStorage*D` functions, which makes making a proper enum group for this more complicated.
https://registry.khronos.org/OpenGL/specs/gl/glspec46.core.pdf page 215

So the "official" solution is going to be casting the required compressed format like this: `(SizedInternalFormat)All.SomeCompressedFormat` or `(SizedInternalFormat)InternalFormat.SomeCompressedFormat`.
