### ISSUE TITLE
GLFW callback setters crash when called with null as parameter

### ISSUE THREAD

**Issue by Cyphall** [opentk/opentk#1063]
### Description

GLFW callback setters accept `null` as argument, but the wrapper method use `Marshal.GetFunctionPointerForDelegate` without null-checking, which cannot accept `null` delegates.
A null check should be done, sending `IntPtr.Zero` to the internal native method if the provided delegate is `null`.

### Expected behavior

The GLFW callback setters don't crash when called with `null` as parameter.

### Actual behavior

The GLFW callback setters crash when called with `null` as parameter.

### Related information 

Windows 10 x64
OpenTK version 4.0.0-pre9.1
.NET Core 3.1
Workaround: send a non-null delegate which does nothing.

**Comment by jvbsl** [comment]
or even better, as we are using DllImport now, we can just use delegates directly in the extern declaration.
Thanks for finding that.
