### ISSUE TITLE
GLFWNative loading wrong shared library

### ISSUE THREAD

**Issue by gtkramer** [opentk/opentk#1064]
### Description

I am following the instructions on the [OpenTK getting started guide for creating a window](https://opentk.net/learn/chapter1/1-creating-a-window.html), making only _slight_ deviations along the way to account for the API changes that are coming for OpenTK 4.0.  With this minimal code, an incorrect libglfw.so shared library is being loaded and a blank window cannot be created.

### Repro steps

1. Create a console application with the following .csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.0.0-pre9.1" />
  </ItemGroup>

</Project>
```

and the following RenderWindow.cs:

```
using OpenToolkit.Windowing.Desktop;
using OpenToolkit.Mathematics;

namespace AdditiveManufacturing.GUI {
    public class RenderWindow : GameWindow {
        public RenderWindow() : base(GameWindowSettings.Default, NativeWindowSettings.Default) {
            // GameWindowSettings
            RenderFrequency = 60;
            UpdateFrequency = 60;
            // NativeWindowSettings
            IsEventDriven = true;
            Title = "Render Window";
            Size = new Vector2i(640, 640);
        }
    }
}
```

and the following `Main` function.

```
public static void Main(string[] args) {
    using (RenderWindow render = new RenderWindow()) {
        render.Run();
    }
}
```

2. Run `dotnet run` and receive the following stacktrace given below.

### Expected behavior

When running the compiled binary, no stack trace occurs saying that the libglfw.so shared library cannot be found when it exists in the NuGet redistribution of glfw and has been copied into the destination bin folder.

### Actual behavior

The following exception is received when running an application for making a blank window:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'OpenToolkit.Windowing.Desktop.NativeWindowSettings' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libglfw.so.3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibglfw.so.3: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenToolkit.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenToolkit.Windowing.Desktop.NativeWindowSettings..ctor()
   at OpenToolkit.Windowing.Desktop.NativeWindowSettings..cctor()
```

Poking around the source code, I suspect there's a problem in [GLFWNative.cs](https://github.com/opentk/opentk/blob/master/src/OpenToolkit.Windowing.GraphicsLibraryFramework/GLFWNative.cs) compared to the packaged distribution on NuGet.  Nuget packages libglfw.so.3.3 (found at path /home/george/.nuget/packages/opentoolkit.redist.glfw/3.3.0-pre20190419183326/runtimes/linux-x64/native/libglfw.so.3.3), but the source code is looking for libglfw.so.3.  Making a symbolic link in the bin directory allows a blank window to pop up.

### Related information 

* Operating system: Arch Linux
* SDL or Native backend: Native backend
* What version of OpenTK: 4.0.0-pre9.1 from NuGet
* What runtime: CoreCLR, dotnet core 3.1.103
* Workarounds: Create a symblink `ln -s libglfw.so.3.3 libglfw.so.3` in the bin directory of the compiled application after running `dotnet run`

**Comment by jvbsl** [comment]
https://github.com/opentk/opentk/issues/1058
Thanks for the detailed report, we already know, and will fix it as well.

**Comment by gtkramer** [comment]
Ah, I swore I looked for other issues that were similar, but I guess I didn't go a good enough digging.  Thanks!  Feel free to close this then.

**Comment by jvbsl** [comment]
No problem, I'm gonna leave it open, as the other one was already closed and that one is much more clear in the title what it i about.
Will be closed when the issue is fixed.
