### ISSUE TITLE
4.0 - Quaternion and Quaterniond behave differently

### ISSUE THREAD

**Issue by djgaven588** [opentk/opentk#1065]
### Description
When using the double version of Quaternion (Quaterniond), it behaves differently than Quaternion. The only place I have found this so far, is the constructor for Quaterniond.

### Repro steps
Log the results of the following calculations:
- Quaternion.FromEulerAngles(DegreesToRadians(90), 0, 0) * new Vector3(0,0,1)
- Quaterniond.FromEulerAngles(DegreesToRadians(90), 0, 0) * new Vector3d(0,0,1)

The results are 0, -1, 0, and 0, 0, 1. Obviously not the same.

### Expected behavior
When using Quaterniond, I would expect the functionality to behave the exact same (only difference being the usage of doubles or floats.

### Actual behavior
Quaterniond does not operate the same as Quaternion. Viewing the source code of both Quaternion and Quaterniond, you can see that in the constructor at minimum is different. Other changes have not been noticed yet, although it is possible.

### Related information 
Windows 10
OpenTK 4
Nuget, 4.0.0-pre9.1
.Net Core 3.1

**Comment by djgaven588** [comment]
Comparing closer, it seems there are many differences in calculations between the two classes, comparing the two text files, it seems this is mostly related to converting to and from euler angles.

**Comment by leezer3** [comment]
PR submitted to fix this for both 3.0 and 4.0

The behaviour in Quaternion appears correct, QuaternionD incorrect.
(This matches Unity et. al, and behaves as expected)
