### ISSUE TITLE
Suggestion for usability improvements

### ISSUE THREAD

**Issue by omicronZero** [opentk/opentk#1066]
### Description
In the current version, it is rather hard to develop for specific versions as they are mixed in one specific GL-class.
I would suggest to separate the different versions into separate classes that are named by the profile that defines them (e.g., GL32).

As I guess that the newest version of OpenGL will very often be used for development, I would also suggest to have a class that contains the newest core profile. I would suggest adding compatibility profiles in separate classes (e.g., GL32Compatibility or GL32.Compatibility). This ought to be done with respect to naming collisions that are easy to prevent and can give additional information. The suggested use would then be to add an import "using GL = OpenTK.Graphics.GL32" or alike making it easy to change the version via a regular expression while enabling switching to newer or older versions

Furthermore, the current OpenTK-Library is rather large and would become even larger if you were to handle it the way I suggested above. Personally, I do not use most of the namespaces except the ones in OpenTK.Graphics.OpenGL4 and I expect that most users will do the same. Thus, moving the different core profile versions together with their compatibility profiles to assemblies would be a good idea. 

The suggestion that the newest core profile is made accessible through an additional library would also go in line with nugets relevance/usage functionality as it would probably keep the nuget package on the top list. A good description of how to use the specific OpenTK versions and that they exist would furthermore make it possible for authors requiring specific OpenGL-profiles to actually find what they need. I expect them to read the description to actually find out whether the library matches their needs. It would then be of no concern if the specific profiles would not be on the top list of nuget.
However, I would like to note that having it this way may require the nuget-package versions to go along with the core profile versions to prevent breaking users' code (e.g., `<OTKMajor>.<OGLMajor>.<OGLMinor>.<OTKBuild>` - not really beautiful, I know ;-) Maybe you have a better idea).

**Comment by varon** [comment]
Thanks for the great suggestion. We had a huge discussion on this over Discord, and it's something we're looking at for OpenTK 5.0.
