### ISSUE TITLE
Dotnet publish for Linux with "/p:PublishSingleFile=true" fails

### ISSUE THREAD

**Issue by gergelydaniel** [opentk/opentk#1070]
### Description

When I run `dotnet publish` in a .NET Core project using OpenTK 4.0.0-pre9.1, it works just fine, however when I run `dotnet publish -r linux-x64 -c release /p:PublishSingleFile=true` it fails.

Note: It works if I specify a Windows target (`dotnet publish -r win10-x64 -c release /p:PublishSingleFile=true`), it only fails for Linux target

### Repro steps

1. Create a Hello World project using .NET Core and OpenTK 4.0.0-pre9.1
2. Try to publish a self contained binary for Linux using `dotnet publish -r linux-x64 -c release /p:PublishSingleFile=true`

### Expected behavior
Build succeeds

### Actual behavior

Build fails with following output:

```
/usr/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [/home/daniel/repositories/rnd/OpenTkTest/OpenTkTest.csproj]
/usr/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018: System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath [/home/daniel/repositories/rnd/OpenTkTest/OpenTkTest.csproj]
/usr/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [/home/daniel/repositories/rnd/OpenTkTest/OpenTkTest.csproj]
/usr/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [/home/daniel/repositories/rnd/OpenTkTest/OpenTkTest.csproj]
/usr/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/home/daniel/repositories/rnd/OpenTkTest/OpenTkTest.csproj]
/usr/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/daniel/repositories/rnd/OpenTkTest/OpenTkTest.csproj]
/usr/share/dotnet/sdk/3.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(881,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/daniel/repositories/rnd/OpenTkTest/OpenTkTest.csproj]
```

### Related information 

* Operating system: Ubuntu 20.04
* What version of OpenTK: `<PackageReference Include="OpenTK" Version="4.0.0-pre9.1" />`
* What runtime: OutputType:Exe, TargetFramework: netcoreapp3.1

**Comment by Cyphall** [comment]
I get the same problem when targetting `win-x64` instead of `win10-x64`.

It happens in both 4.0.0-pre9.1 and 4.0.0-pre9.2.

**Comment by MV10** [comment]
https://github.com/dotnet/sdk/issues/3465

**Comment by varon** [comment]
We're using FAKE to handle our build. The official build system is done via `build.cmd` or `build.sh`. Do these work on your systems?

**Comment by varon** [comment]
Please re-open this if it is still an issue on the latest previews/netcore 3.1.
