### ISSUE TITLE
StartVisible = false not working

### ISSUE THREAD

**Issue by moritz-h** [opentk/opentk#1071]
### Description

Window is visible even when setting `StartVisible = false` in NativeWindowSettings.

### Repro steps

Empty new .Net Core project with following code in main:
```c#
var settings = new NativeWindowSettings()
{
    StartVisible = false,
};
var win = new NativeWindow(settings);
Thread.Sleep(10000);
```

### Expected behavior

Window is hidden.

### Actual behavior

Window is shown.

### Related information 

* Windows 10
* OpenTK v4.0.0-pre9.1 NuGet
* .Net Core 3.1

I tried the following workaround:
```c#
var win = new NativeWindow(settings)
{
    IsVisible = false
};
```
But there is still a short flickering of the window visible.

**Comment by moritz-h** [comment]
I tried to investigate this a litte more and found a few things within the NativeWindow class:
- The reason that the window always starts visible is here: https://github.com/opentk/opentk/blob/4.0.0-pre9.1/src/OpenToolkit.Windowing.Desktop/NativeWindow.cs#L585
Setting a window state will make the window visible (even minimize will show the icon in the task bar), as the window state setter will call the according GLFW functions, which seem to always show the window. I thought of maybe the visible property should be added as a new window state, or maybe the window state setter just ignores setting a state when the window is hidden. But both ways do not really feel like a clean solution.
- The private state variables `_title`, `_currentMonitor` and `_isVisible` seems to be never updated. Therefore asking the public getters will always return the initial state, not the current state. There seems to be different options to fix it. Update the setters to save the state ot at least for _isVisible it may be possible to drop the private state completely and ask GLFW directly for the current state like this is done for the WindowState
- There is may a general inconsistency within the API especially when looking at #616. For example the `_isFocused` property is updated within the callback and therefore behaves asynchronously, while other properties like `_windowBorder` are updated directly in the setter method and therefore behaves synchronously.

**Comment by NogginBops** [comment]
@moritz-h Issue #616 doesn't relate to opentk 4, because the X11 backend doesn't in opentk 4.
It's all glfw in opentk 4, so if there is a similar issue there it's an issue with glfw or our use of it.

**Comment by moritz-h** [comment]
@NogginBops Perhaps my explanation about #616 in this context is a little bit missleading. I am not meaning #616 directly, I wanted to mention the inconsistency within the NativeWindow API by mixing syncron and asyncron property behavior. But #616 is the reason under the hood, why this problem in practice may becomes visible.

I know OpenTK 4 will use GLFW, but GLFW uses X11 and has exactly the same problem as #616. (I did not try with OpenTK, but also experienced that a lot with GLFW directly in C++ applications.)
I know you can probably do nothing about this, but what I tried to mention is, that the native window class perhaps want to use a consinstent interface by either passing the GLFW behaviour or do it all syncronous on its own with cached state variables. Currently there is a mixture:
Look at the difference between WindowBorder and IsFocused. Window border will currently always be syncron because the state value is saved directly in the setter. IsFocused is updated in the GLFW callback function and thefore is asyncron (in practicle this will depend on the window manager and is the #616 problem).

This problem already occured in #1076. There syncron behaviour was expected, but _size is updated asyncronously in the resize callback. (Btw. with #1076 _size is now updated twice, once directly and once in the callback.)

I think it also would be ok to accept GLFW behaviour, and document that read directly after write is may not a good idea, but then it perhaps improves the NativeWindow API if all properties have constent behaviour (as long as this is possible, i know may not all properties could be read from GLFW like for example the title).

**Comment by NogginBops** [comment]
I understand now what you where saying. Thanks for clarifying.
This doesn't have a super clear answer as people would expect the properties to update synchronously as they do in opentk 3.x.
But as the underlying api isn't synced maybe our layer shouldn't be synced.

I also think that doing stuff as close to the way glfw does it might benefit us by allowing workarounds that work with glfw to work with opentk (not sure how important this should be though...).
