### ISSUE TITLE
Shared context with multiple windows

### ISSUE THREAD

**Issue by moritz-h** [opentk/opentk#1072]
### Description

Feature Request:
It would be nice to be able to use context sharing between multiple windows. For GLFW part see: https://www.glfw.org/docs/3.3/context_guide.html#context_sharing
But currently OpenTK has hardcoded a null pointer during GLFW window creation.

Perhaps you could add a parameter to NativeWindowSettings, which allows to specify another NativeWindow, which is then used for context sharing.

**Comment by jvbsl** [comment]
Is fixed with https://github.com/opentk/opentk/pull/1122 and already available in the newest prerelease, thanks for calling attention to it ;)
