### ISSUE TITLE
netcore on Windows : Failed to create OpenGL context

### ISSUE THREAD

**Issue by devel0** [opentk/opentk#1074]
### Description

same code on linux works, while in windows generate error ( see detail on Actual behavior )

### Repro steps

Please provide the steps required to reproduce the problem

1. clone example from [here](https://github.com/devel0/example-netcore-opentk.git)

2. enter the `example-netcore-opentk`

3. issue `dotnet run`

*note*: dotnet 3.1 or 5.0preview required

### Expected behavior

same code executed from Ubuntu works:
![image](https://user-images.githubusercontent.com/13405008/83575939-e5c30d00-a530-11ea-97f0-46f233db3874.png)

### Actual behavior

in win10 I got follow error:
```
Z:\00-tmp\example-netcore-opentk>dotnet run
Unhandled exception. OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWException: WGL: Failed to create OpenGL context
   at OpenToolkit.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__5_0(ErrorCode errorCode, String description)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenToolkit.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenToolkit.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
   at BasicTriangle.Program..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) in Z:\00-tmp\example-netcore-opentk\Program.cs:line 50
   at BasicTriangle.Program.Main() in Z:\00-tmp\example-netcore-opentk\Program.cs:line 145
```

### Related information 

* Operating system ( win10 )
* Native backend ( glfw3-x64.dll )
* What version of OpenTK (nuget https://www.nuget.org/packages/OpenTK/4.0.0-pre9.1)
* What runtime
```
Z:\00-tmp\example-netcore-opentk>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.4.20258.7
 Commit:    65f0fc2cad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.4.20258.7\

Host (useful for support):
  Version: 5.0.0-preview.4.20251.6
  Commit:  47ec733ba7

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.4.20258.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.4.20257.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.4.20251.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
* Workarounds

**Comment by jvbsl** [comment]
Is it in a virtual machine?
Which OpenGL version is on the Windows machine?

**Comment by devel0** [comment]
Sorry, that's the reason, I just tried in host win10 and everything works as expected, so the problem seems related to virtualbox GL driver

Below info you requested, but I think that this issue can be closed.

![image](https://user-images.githubusercontent.com/13405008/83729367-c5d23d00-a647-11ea-9dfa-8b6993987113.png)

**Comment by jvbsl** [comment]
Well I don't think that it can't work under the VM.
Could you perhaps use that software to determine the OGL version?
https://www.realtech-vr.com/home/glview

**Comment by devel0** [comment]
of course, attached xml report
as you can see the driver is mesa, that is a sw renderer, but it should the mode which a vm map a 3d graphics, not one-one but through a mapping between hw-mesasw I think.

nfo:
![image](https://user-images.githubusercontent.com/13405008/83814515-f608f280-a6be-11ea-8aa6-49ef7550b112.png)


bench:
![image](https://user-images.githubusercontent.com/13405008/83814387-ec7f8a80-a6be-11ea-9ee2-8efb5e6a9c92.png)

It for something works but seems not fully implemented maybe, btw when I test http://www.kevs3d.co.uk/dev/shaders/waves5.html from host I got 60 fps while from VM without 3d accel I got something like 5 fps but with vm 3d accel I got around 33 fps so that is better than nothing.

report xml:
[glview-SVGA3D; build_ RELEASE;  .XML.log](https://github.com/opentk/opentk/files/4732913/glview-SVGA3D.build_.RELEASE.XML.log)

**Comment by devel0** [comment]
following I tested that from glfw c++ the [gears](https://github.com/glfw/glfw/blob/bf1c62b2612dba79365e836830fe2a6105adbe78/examples/gears.c#L318) example work ( I used current git version ) either under VM

![image](https://user-images.githubusercontent.com/13405008/84975731-73ece500-b126-11ea-9ae2-327854cf7052.png)

**Comment by jvbsl** [comment]
![image](https://user-images.githubusercontent.com/13928225/93491865-7966f080-f90a-11ea-93c9-27f2a68f61bd.png)
` new NativeWindowSettings() { Title = "Rendering Window", APIVersion = new Version(2,1), Profile = ContextProfile.Any })`
That works for me, of course with these drivers(the same you have I guess) you only have OpenGL 2.1 capability, but it works in my Win 10 VM.
Therefore I'm gonna close this issue ;)
