### ISSUE TITLE
Question. Rendering quad to Bitmap

### ISSUE THREAD

**Issue by MartinStokelj** [opentk/opentk#1082]
Hello, with perspective correction I draw quad image (https://stackoverflow.com/questions/58917579/draw-image-with-opengl)

               if (!backgroundColor.HasValue)
                    backgroundColor = new Pen(Fill).Color;
                GL.Color4(backgroundColor.Value);

                lock (bitmapSync)
                {
                    if (bitmap != null)
                        createTexture();
                }

                GL.Enable(EnableCap.Texture2D);
                GL.BindTexture(TextureTarget.Texture2D, texture);

                // center point
                GPoint localTargetPosition = MainForm.instance.gMapControl.FromLatLngToLocalWithOffset(targetPosition);
                // determines distances to center for all vertexes
                double dUL = Common.distance(new double[] { LocalPoints[0].X, LocalPoints[0].Y }, new double[] { localTargetPosition.X, localTargetPosition.Y });
                double dUR = Common.distance(new double[] { LocalPoints[1].X, LocalPoints[1].Y }, new double[] { localTargetPosition.X, localTargetPosition.Y });
                double dLR = Common.distance(new double[] { LocalPoints[2].X, LocalPoints[2].Y }, new double[] { localTargetPosition.X, localTargetPosition.Y });
                double dLL = Common.distance(new double[] { LocalPoints[3].X, LocalPoints[3].Y }, new double[] { localTargetPosition.X, localTargetPosition.Y });

                var texCoords = new[]
                {
                    new Vector4(0, 0, 1, 1),
                    new Vector4(1, 0, 1, 1),
                    new Vector4(1, 1, 1, 1),
                    new Vector4(0, 1, 1, 1)
                };

                texCoords[0] *= (float)((dUL + dLR) / dLR);
                texCoords[1] *= (float)((dUR + dLL) / dLL);
                texCoords[2] *= (float)((dLR + dUL) / dUL);
                texCoords[3] *= (float)((dLL + dUR) / dUR);

                GL.Begin(PrimitiveType.Quads);
                {
                    //GL.TexCoord2(0, 0); //UL  LocalPoints[0] gimbalUL
                    //GL.TexCoord2(1, 0); //UR  LocalPoints[1] gimbalUR
                    //GL.TexCoord2(1, 1); //LR  LocalPoints[2] gimbalLR
                    //GL.TexCoord2(0, 1); //LL  LocalPoints[3] gimbalLL
                    GL.TexCoord4(texCoords[0]); GL.Vertex4(LocalPoints[0].X, LocalPoints[0].Y, 1, 1);
                    GL.TexCoord4(texCoords[1]); GL.Vertex4(LocalPoints[1].X, LocalPoints[1].Y, 1, 1);
                    GL.TexCoord4(texCoords[2]); GL.Vertex4(LocalPoints[2].X, LocalPoints[2].Y, 1, 1);
                    GL.TexCoord4(texCoords[3]); GL.Vertex4(LocalPoints[3].X, LocalPoints[3].Y, 1, 1);
                }

                GL.End();
                GL.Disable(EnableCap.Texture2D);

                float wid = Stroke.Width;
                Color col = Stroke.Color;

                if (wid > 0)
                {
                    for (int i = 0; i < LocalPoints.Count; i++)
                    {
                        int j = (i + 1) % LocalPoints.Count;
                        GMapControl.line(LocalPoints[i].X, LocalPoints[i].Y, LocalPoints[j].X, LocalPoints[j].Y, wid, col);
                    }
                }

My question is how I can now grab this rendered image in to Bitmap? As you can see the image is not rectangle anymore but its quad (its not scaled rectangle). I need to grab rendered texture only of this object and not the screen.

I tryed a lot of function found on internet like:
public Bitmap GetBitmap(int Width, int Height)
public Bitmap CaptureScreen(int width, int height)
public Bitmap GrabScreenshot(int w, int h)
public Bitmap GetTexture(int AttachmentIndex, Bitmap bmp)
public Bitmap TakeScreenshot(int w, int h)

All functions need like width/height for rectanble, but I don't know hot to get this for Quad.
I want to get rendered quad image as bitmap which should be rectangle with transparency.
Any suggestions?

**Comment by MartinStokelj** [comment]
No suggestions?

**Comment by jvbsl** [comment]
It is not really clear to me which image you want to grab? The rendered result? then you could render your stuff into a framebuffer and get it's pixel data

**Comment by NogginBops** [comment]
I think suggestions for this will be easier to get in the discord.
It is not clear what you are trying to achieve and as a lot of answers in opengl are; "it depends".

So my suggestion is to join the discord and explain what it is you are trying to do and someone might have a suggestion.

**Comment by MartinStokelj** [comment]
> It is not really clear to me which image you want to grab? The rendered result? then you could render your stuff into a framebuffer and get it's pixel data

I want to catch only rendered bitmap not screenshot since screenshot will contan also other images witch are drawn over this bitmap. 
Extra explanation: I am getting video image 1280/720 when this image is rendered on GMap the size is arrownd 150pixels (depend on zoom level) also the image is rotated so the actual size of bitmap is different.
I need this rendered image so I can make image stitching and from it Orthomosaic.

**Comment by MartinStokelj** [comment]
> I think suggestions for this will be easier to get in the discord.

I don't understand what you mean whith this, what is this "discord"

**Comment by NogginBops** [comment]
There is a discord server for the opentk community (discord is a chat and voice service somewhat like skype or slack).
You can find discord here: https://discord.gg
And the link to the opentk server here: https://discord.gg/6HqD48s (this is also in the readme.md)

But it's understandable if you just want to keep this question on github

**Comment by MartinStokelj** [comment]
After help on "discord" we have manage to create frame buffer FBO but the output is always empty Transparent image.
Any suggestion what is the problem?

[code7.txt](https://github.com/opentk/opentk/files/4904745/code7.txt)

**Comment by MartinStokelj** [comment]
Any suggestions?

**Comment by MartinStokelj** [comment]
I want to draw in to FBO and save the bitmap, then I need to draw this FBO also on the screen. Can someone look the code for mistakes https://github.com/opentk/opentk/files/4904745/code7.txt

**Comment by subchannel13** [comment]
> I want to draw in to FBO and save the bitmap, then I need to draw this FBO also on the screen. Can someone look the code for mistakes https://github.com/opentk/opentk/files/4904745/code7.txt

Can you please move the discussion and code review to Discord. There is no indication of an issue (bug) with OpenTK.

**Comment by MartinStokelj** [comment]
Closing ... no indication of an issue ...

**Comment by NogginBops** [comment]
The code examples given doesn't give any confidence in your understanding of opengl basics. FBOs are a somewhat complex opengl concept that requires understanding of how modern opengl is done. Your code is using the immediate mode opengl api which has been deprecated for a long time and been obsolete for even longer. I gave you a link to https://learnopengl.com which is a good tutorial to follow to learn modern opengl concepts. For other resources you can look at the pinned messages in the #support channel on discord. If you have questions after trying to learn from these resources you can ask in #support in the discord.
