### ISSUE TITLE
GLFW doesn't run on mac

### ISSUE THREAD

**Issue by tzachshabtay** [opentk/opentk#1083]
### Description

I'm trying to port an existing working OpenTK3 app to OpenTK4.
I'm running on a mac.

- First issue, on startup (compiles fine):
`Unable to load shared library 'libglfw.3.dylib' or one of its dependencies.`
I can see that in the bin folder the `libglfw.so.3.3` was copied but not the dylib, so I'm guessing there's some issue with how you bundle it.

I've downloaded the binary myself and put in the folder which works around the first issue.

- And then I hit a second issue:
```
Unhandled exception. OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWException: NSGL: The targeted version of macOS only supports forward-compatible core profile contexts for OpenGL 3.2 and above
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFWNative.glfwCreateWindow(Int32 width, Int32 height, Byte* title, Monitor* monitor, Window* share)
   at OpenToolkit.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__5_0(ErrorCode errorCode, String description)
   at OpenToolkit.Windowing.GraphicsLibraryFramework.GLFW.CreateWindow(Int32 width, Int32 height, String title, Monitor* monitor, Window* share)
   at OpenToolkit.Windowing.Desktop.NativeWindow..ctor(NativeWindowSettings settings)
   at OpenToolkit.Windowing.Desktop.GameWindow..ctor(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
```
I don't know if you use `GLFW.NET` or if you rolled your own, but [I saw a fix for that same issue in GLFW.NET](https://github.com/ForeverZer0/glfw-net/pull/30).

- Also, an additional question: I didn't see what's the equivalent (if there is an equivalent) to the `OpenTK.Toolkit.Init();` statement from OpenTK3?

### Repro steps

Please provide the steps required to reproduce the problem

1. Build & Debug `DemoQuest.Desktop` from https://github.com/tzachshabtay/MonoAGS/tree/opentk4, this should get you to the first issue

2. Download the mac binary directly from [GLFW website](https://www.glfw.org/download.html), copy the `dylib` file to the bin/Debug/netcoreapp3.1 folder. Debug again, you should now hit the second issue.

### Expected behavior

GLFW should run.

### Actual behavior

Exception on startup.

### Related information 

* Operating system- macOS Mojave Version 10.14
* SDL or Native backend- GLFW? Is it possible not to use it with OpenTK4?
* What version of OpenTK (Installer, NuGet, Source Code)- 4.0.0-pre9.1 from nuget
* What runtime (.NET Framework, CoreCLR, Mono)- netcoreapp3.1

**Comment by mewh** [comment]
Have you tried setting the flags of the NativeWindowSettings to ContextFlags.ForwardCompatible?

For example, in F# I managed to get a window opening using these settings:
```
let gws = GameWindowSettings.Default
let nws = NativeWindowSettings()
nws.Size <- Vector2i(800, 600)
nws.Title <- "Test"
nws.Flags <- ContextFlags.ForwardCompatible
nws.API <- ContextAPI.OpenGL
nws.APIVersion <- Version(3, 3)
nws.Profile <- ContextProfile.Core
```

**Comment by tzachshabtay** [comment]
Thanks @mewh this solves the second issue. Should this be made the default?

**Comment by mewh** [comment]
No problem. Seems like it's required by GLFW for macOS.
https://www.glfw.org/faq.html#41---how-do-i-create-an-opengl-30-context

**Comment by NogginBops** [comment]
It can't be made the default because we don't know if the user is actually running on mac or if the person is going to request a 3.0+ context.
OpenTK is meant to be a low level wrapper for c#, creating only minimal nice to haves that make using c# and OpenGL together easier. We don't want to start doing platform dependent hacks and stuff.
Apple has decided that they will only support `ForwardCompatible` contexts, those details are for the user to handle.

**Comment by tzachshabtay** [comment]
What are the consequences of having a forward compatible context on windows and linux?

**Comment by NogginBops** [comment]
You can read about what Forward compatible means here: https://www.khronos.org/opengl/wiki/OpenGL_Context#Forward_compatibility

**Comment by jvbsl** [comment]
Could you try whether the first issue is now fixed with the newest prerelease, as it should now include the library for macos. Would be highly appreciated.

**Comment by varon** [comment]
Closing as this *should* be fixed. Thanks for all of the report and help in addressing this.
