### ISSUE TITLE
Create OpenGL context without window

### ISSUE THREAD

**Issue by joa77** [opentk/opentk#1085]
### Description

I need to create an OpenGL context without any Windows. My application is a console App, which creates graphics and stores them to files with SkiaSharp, which needs a valid OpenGL context for GPU accelerated drawing.

I searched throw the documentation and various stackoverflow question and issues on this Rrepository, but i couldn't find an answer to do this.

### Related information 

* Operating system: Windows, MacOS and Linux
* SDL or Native backend
* OpenTK from NuGet
* CoreCLR

**Comment by NogginBops** [comment]
What version of OpenTK is this?

**Comment by joa77** [comment]
Currently tried it with 3.2, because 4.0 is not marked as stable

**Comment by NogginBops** [comment]
In OpenTK 3 you can use `Toolkit.Init(...)` to initialize the bindings without creating a window.
You will still need to make the opengl context current through some means though.

**Comment by joa77** [comment]
Will this resolved with OpenTK 4 ?

**Comment by jvbsl** [comment]
What do you mean resolved? It is possible in OTK 3

**Comment by joa77** [comment]
@jvbsl can you show me how?

**Comment by jvbsl** [comment]
Create an invisible Window, and use the context from there. That's the way to go with OGL(unfortunately). Only few context creation libraries are able to create a context without a window(e.g. MESA software renderer)

**Comment by joa77** [comment]
Unfortunately this only works on systems with a window system. On command line only servers this would not work or am I wrong here?

**Comment by jvbsl** [comment]
OpenGL has no standard way to work without a windowing system. On Linux you would e.g. use Xfvb or something similar, as a virtual X11 server, on which you can create windows.

**Comment by HugoPeters1024** [comment]
@joa77 ever got such a thing working? I'm interested in making cli based gpgpu programs with compute shaders.

**Comment by NogginBops** [comment]
I'm going to close this, OpenTK will probably only support context creation for systems with a windowing system. Any use case that needs windowless OpenGL will have to initialize the context themselves and create a `IBindingsContext` and pass it to `GL.LoadBindings` to initialize the bindings themselves.
