### ISSUE TITLE
[4.0] OpenGL context is not initialized in 4.0.0-pre9.2

### ISSUE THREAD

**Issue by NoneGiven** [opentk/opentk#1100]
### Description

When updating from `4.0.0-pre9.1` to `4.0.0-pre9.2`, a simple program using the fixed function pipeline no longer renders anything.

### Repro steps

```csharp
using System;
using OpenToolkit.Graphics.OpenGL;
using OpenToolkit.Mathematics;
using OpenToolkit.Windowing.Common;
using OpenToolkit.Windowing.Desktop;

namespace GlTest
{
    internal static class Program
    {
        public static void Main()
        {
            GameWindowSettings settings = GameWindowSettings.Default;
            settings.RenderFrequency = 60;
            settings.UpdateFrequency = 60;
            NativeWindowSettings native = NativeWindowSettings.Default;
            native.Size = new Vector2i(800, 600);
            native.Profile = ContextProfile.Compatability;
            native.APIVersion = new Version(3, 2);
            RenderWindow window = new RenderWindow(settings, native);
            window.Run();
        }
    }

    public class RenderWindow : GameWindow
    {
        public RenderWindow(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings)
            : base(gameWindowSettings, nativeWindowSettings)
        {
        }

        protected override void OnLoad()
        {
            GL.ClearColor(0f, 0f, 0f, 1f);
            base.OnLoad();
        }

        protected override void OnRenderFrame(FrameEventArgs args)
        {
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
            GL.GetFloat(GetPName.Viewport, out Vector4 viewport);
            float aspect = (viewport.Z - viewport.X) / (viewport.W - viewport.Y);
            GL.MatrixMode(MatrixMode.Projection);
            float fov = MathHelper.DegreesToRadians(80.0f);
            var perspectiveMatrix = Matrix4.CreatePerspectiveFieldOfView(fov, aspect, 0.1f, 100.0f);
            GL.LoadMatrix(ref perspectiveMatrix);

            GL.Color3(1f, 0f, 0f);
            GL.Begin(PrimitiveType.Triangles);
            GL.Vertex3(3f, 3f, -5f);
            GL.Vertex3(-3f, 3f, -5f);
            GL.Vertex3(0f, -3f, -5f);
            GL.End();

            SwapBuffers();
            base.OnRenderFrame(args);
        }
    }
}
```

### Expected behavior

`4.0.0-pre9.1`:

<img src="https://user-images.githubusercontent.com/2163967/88994525-99891480-d2b6-11ea-910d-90437671be92.png" alt="expected" width="400px">

### Actual behavior

`4.0.0-pre9.2`:

<img src="https://user-images.githubusercontent.com/2163967/88994475-76f6fb80-d2b6-11ea-8dc0-5e749b2fd088.png" alt="actual" width="400px">

I also noticed that calls to `GL.CreateShader` are returning 0 and shaders cannot be compiled.

### Related information 

* Windows 10
* OpenTK NuGet
* .NET Core 3.1

**Comment by HugoPeters1024** [comment]
You mentioned there were shader compilation problems, could you also share the shader source and compilation error log?

**Comment by jvbsl** [comment]
And the logs of OpenGL would be interesting as well. Either use DebugMessageCallback for that or do a GetError after every line. So that we can no what seems to be the problem and at which line it occures.

**Comment by NoneGiven** [comment]
@HugoPeters1024 @jvbsl `GetError` returns `InvalidOperation` on every line, even in `OnLoad` before anything happens. I don't seem to get anything from `DebugMessageCallback`, although I don't know if that code is set up correctly.

As for the shaders, there is no error log, because `GL.CreateShader` is returning 0 so there's nothing to compile into.

In short -- it seems like there isn't an OpenGL context at all.

**Comment by HugoPeters1024** [comment]
Not entirely sure, but clearColor might be deprecated, try glClear(GL_COLOR_BUFFER_BIT)

**Comment by NogginBops** [comment]
`glClearColor` is not deprecated, clear color sets the color of the clear and `glClear` executes the actual clear.

**Comment by skyloutyr** [comment]
Likely related to #1096 as simply making the context current anywhere within the GL thread will fix the issue. For example, for me simply calling this.MakeCurrent() in a load event handler did the trick.

**Comment by NogginBops** [comment]
Yep that would do it. We should figure out how we want that to work.
My vote is for making binding null as the context as a method of native window or something similar, because that will solve the problem and give the most flexibility but I think some people didn't want that solution, don't remember why though.

**Comment by myblindy** [comment]
I just ran into the same issue, this has nothing to do with the fixed pipeline (I'm not using it), shader compilation or anything else like this, there is already an `InvalidOperation` OpenGL error in `OnLoad`.

**Comment by jvbsl** [comment]
Did you also read the discussion under the issue? E.g. have you tried what @skyloutyr has suggested?

**Comment by NoneGiven** [comment]
This is fixed in pre9.6. `MakeCurrent` is no longer required.
