### ISSUE TITLE
Unable to load DLL 'glfw3' 4.0.0-pre9.3

### ISSUE THREAD

**Issue by felixkraas** [opentk/opentk#1108]
### Description

Creating a new window creates the following error:

System.DllNotFoundException: 'Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)'

### Repro steps

1. Try to create a GameWindow instance.

2. Run the Programm.

### Expected behavior

glfw3.dll should be found.

### Actual behavior

glfw3.dll is not found.
Inspecting the output directory showed that the dll(s) for glfw are actually named glfw3-x64.dll and glfw3-x86.dll

### Related information 

* Windows 10 Pro x64
* 4.0.0-pre9.3 from NuGet
* Latest .Net Core 3.X
* Workaround: manually rename glfw3-x64.dll to glfw3.dll in the bin directory.

**Comment by jvbsl** [comment]
Could you please try now by explicitely adding the newest opentoolkit.redist.glfw package. Don't forget to remove your output folder to be sure that it actually works like it should.

**Comment by felixkraas** [comment]
Installed opentoolkit.redist.glfw version 3.3.0-pre20200829200313 and now it is working.

**Comment by jvbsl** [comment]
Should now directly work with 4.0.0-pre9.4+
