### ISSUE TITLE
License info is incorrect

### ISSUE THREAD

**Issue by pavelpe** [opentk/opentk#1113]
Hi,

OpenTK v.3.2.0 nuget package license info path is incorrect. It navigates to 
`https://github.com/opentk/opentk/blob/master/License.txt` 

while the right path should be `License.md`

I believe the problem origins in: 
`public string DefaultLicenseFile = "License.txt";`

This is minor issue, but it might fail automatic script to retrieve license for this nuget.

**Comment by NogginBops** [comment]
This has been fixed with https://github.com/opentk/opentk/commit/c0ea17b2286c19517bed259c1316eced35ae4772
