### ISSUE TITLE
OpenTK 4 pre 9.4 GLFWNative.cs missing glfwGetWin32Window

### ISSUE THREAD

**Issue by Metric** [opentk/opentk#1120]
Would be great to add this in as an enhancement, so we can get the actual HWND IntPtr of the Window.

The HWND IntPtr is important when dealing directly with Win32 api calls, such as using PeekMessageW. 

Currently GLFW does not implement direct support for the Win32 API of tablet pen support. Thus, the only known way to get the pen message is to PeekMessageW in a loop before glfwPollEvents.

**Comment by NogginBops** [comment]
This is fixed in pre9.6

**Comment by jvbsl** [comment]
fixed with https://github.com/opentk/opentk/pull/1132
