### ISSUE TITLE
RenderTime always 0

### ISSUE THREAD

**Issue by Gribochek277** [opentk/opentk#1123]
### Description

RenderTime property of GameWindow always equal 0

### Expected behavior

Property should return time used for rendering a frame.

### Actual behavior

Value always 0;

### Related information 

* Operating system - Windows 10
* What version of OpenTK (Installer, NuGet, Source Code) - 4.0.0-pre9.4
* What runtime (.NET Framework, CoreCLR, Mono) - tried at .Net Core 3.0, .Net 5.0 preview

**Comment by NogginBops** [comment]
This is interesting, the code just defines the member and then just doesn't do anything with it.

**Comment by Gribochek277** [comment]
Yea, in version 3.x there was an assignment to similar variable, which was very handy for library consumers:
[UpdateTime](https://github.com/opentk/opentk/blob/d8b0aacf157756f20ebfc381d6b345fd002c2a30/src/OpenTK/GameWindow.cs#L743)
and it in RaiseUpdateFrame method was simple logic for calculating it:
[Update UpdateTime property](https://github.com/opentk/opentk/blob/d8b0aacf157756f20ebfc381d6b345fd002c2a30/src/OpenTK/GameWindow.cs#L465)
I don't know the reasons why it works now not like that, but if you see no concerns here it would be very handy fix\improvement.

**Comment by NogginBops** [comment]
@Gribochek277 I just made a pull request to fix this issue, it would be great if you could look at the change and see if it's does what you expect it to do.
