### ISSUE TITLE
[Keyboard] KeyboardState issues

### ISSUE THREAD

**Issue by jstefanelli** [opentk/opentk#1145]
### Description

Hi, first proper reported issue for me.
I'm having problems with GameWindow's keyboard state "missing" events. Keys keep returning "pressed" after the KeyUp event fires correctly with no other KeyDown events

### Repro steps

1. Create simple OpenTK app ([example](https://github.com/jstefanelli/OTKBugTest/blob/master/OTKBugTest/Program.cs))

2. Press any key with some interval and monitor the GameWindow's KeyboardState

### Expected behavior

Key in question should follow the flow of KeyUp/KeyDown events

### Actual behavior

Some events are skipped by KeyboardState
[Video Link](https://jstefanelli.com/files/otk.mp4)

### Related information 

* OS: Win10 x64 2004
* Backend: GLFW (I think?)
* OpenTK Version: OpenTK 4.0.0-pre9.8 Nuget
* Runtime: netcoreapp 3.1
* Workaround: Do not use KeyboardState. Keep track of your state through events

**Comment by varon** [comment]
Thanks for the report. Should be fixed by #1149
