### ISSUE TITLE
[3.x] X11 sigabrt

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#1151]
### Description

Some users are reporting this sigabrt when exiting my game. Anyone have any clues on how to track this down? Full crash log : [sigabrt.txt](https://github.com/opentk/opentk/files/5317665/sigabrt.txt)

> 	Native Crash Reporting
> Got a SIGABRT while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 

[...]

>	Managed Stacktrace:
>	  at <unknown> <0xffffffff>
>	  at OpenTK.Platform.X11.Functions:XIfEvent <0x000b3>
>	  at System.Threading.ThreadHelper:ThreadStart_Context <0x000ae>
>	  at System.Threading.ExecutionContext:RunInternal <0x0018f>

[...]

### Related information 
* Linux / Mono
* OpenTK 3.1

**Comment by varon** [comment]
Hrm. This is a really strange error.

One thing that comes to mind is that some unsafe native functions are being called after the context/whatever is being destroyed.

Do you get the same error on an empty `GameWindow`?

**Comment by jvbsl** [comment]
How do you exit your application at that point? To me it seems to be happening in the event loop, probably when the window get's destroyed but it still tries to use it for event processing

**Comment by varon** [comment]
Bump for question answers @tyronx

**Comment by tyronx** [comment]
> Do you get the same error on an empty GameWindow?

Ok, I would need to test that with said user, I'll see if i can get that info

> How do you exit your application at that point? To me it seems to be happening in the event loop, probably when the window get's destroyed but it still tries to use it for event processing

I do this here 
```
try
            {
                window?.Exit();
            }
            catch (Exception)
            {
                // We don't care about this exception
            }

            Environment.Exit(0);
```

**Comment by tyronx** [comment]
Said user wrote me it only crashed like 1 in 10 times. I asked him if it still happens. He'll report back and then I'll send him a minimal sample app.

**Comment by varon** [comment]
Hrm. Environment.Exit isn't exactly the cleanest exit for an application. That might be the root cause.

**Comment by tyronx** [comment]
What is the cleanest exit for an application then?

**Comment by subchannel13** [comment]
Probably `Exit()` on a `GameWindow` object or whatever windowing you use.

**Comment by tyronx** [comment]
Thanks for the info, I'll remove the Environment.Exit() and see if the users issue disappears

**Comment by varon** [comment]
Thanks, let's hope this solves it!

**Comment by NogginBops** [comment]
@tyronx did it fix the issue?
It would be great if we could close this issue knowing this was the solution.

**Comment by tyronx** [comment]
Ah yes. I've had no new reports regarding this, assuming it to be fixed. 👌
