### ISSUE TITLE
.NET 4.8 support

### ISSUE THREAD

**Issue by ondrasvoboda** [opentk/opentk#1160]
### Description

I'm not able to update OpenTK 3.2.0 to 4.0.1 via Nuget. Getting following error:

Could not install package 'OpenTK.Compute 4.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

### Related information 

* Windows 10 
* .NET Framework 4.8

**Comment by NogginBops** [comment]
OpenTK 4.0 only supports .NET Core. 
For .Net framework you should use OpenTK 3.2 (which is still supported for framework).

**Comment by ondrasvoboda** [comment]
OK, thanks for info. Do you plan to support .NET framework in the future 4.* releases or it will be Core only?

**Comment by jvbsl** [comment]
4.x will be .Net Core 3.1+ only
5.x will be .Net 5+ only
