### ISSUE TITLE
Keyboard keys get stuck after locking the machine

### ISSUE THREAD

**Issue by MNAngelova** [opentk/opentk#1165]
I have a laptop that runs Win 10, when I press the Win key+ L to lock the screen both keys get stuck. So when I unlock my PC, L is constantly being pressed down (IsKeyDown is constantly true).  The only way to stop this is to press the key again, which is not a great solution. 
I saw there was a similar issue being raised before but it was closed without it being resolved. 
https://github.com/opentk/opentk/issues/59

Just like in the previously raised issue I get the state of the keyboard the following way:

                         KeyboardState keyboard = Keyboard.GetState();

Then I get the state of the key:

                         bool L = keyboard.IsKeyDown(Key.L))

I have tried the following things:

- Different keyboards (One of them is Logitech and the other one is from a Dell Laptop)

- Running the application in x64 and x86

- Restarting the machine as suggested in the previous ticket

- Attempting on different machines (this issues has happened on two other machines (all Win 10))

The operating system is Windows 10 Pro 64 bit (10.0, build 18363)

The laptops are high spec so I doubt there is shortage of resources. 

- Intel® Xeon® Processor E3-1535M v6

- Nvidia Quadro M2200

- 32GB RAM

The keyboards are UK (British) English layout

Is there any solution/workaround for this issue?

Thanks :)

**Comment by NogginBops** [comment]
What version of OpenTK are you using?

**Comment by MNAngelova** [comment]
For OpenTK we use version 3.0.1

**Comment by NogginBops** [comment]
What happens if you press the key that is stuck again? Is it still stuck or does it get unstuck?

**Comment by MNAngelova** [comment]
If I press the L key again, while it is stuck, that will get it unstuck

**Comment by varon** [comment]
@MNAngelova  - Thanks for the report.  This is an incredibly thorough investigation into the issues.

How viable is it for you guys to upgrade to OpenTK 4.0? This has a totally different input system and should absolutely fix the issue you're experiencing.

**Comment by varon** [comment]
Thanks for the report. Hope you can update to 3.3! Should be resolved by #1178!
