### ISSUE TITLE
Could not install package 'OpenTK.Compute 4.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2',

### ISSUE THREAD

**Issue by Jirara** [opentk/opentk#1188]
### Description

Visual Studio 2019 nuget package install failure

Hey, I admit to being a total noob at this, but I didn't know where to go to find this information - I tried to follow along and use nuget to install, and I keep hitting this error:

Could not install package 'OpenTK.Compute 4.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2',

I tried each version of .NETFramework that is available in my install (3.0, 3.5, 4.0, 4.5, 4.6, 4.6.##) and I couldn't get any of them to work. What version of .NetFramework is this targeting? Alternatively, I downloaded the zip file directly and thought I would add the references, but I didn't see .dll files, so I thought maybe it hasn't been built, but didn't see .c files, either. Is there a resource for that initial setup for those of use who are just getting started and can't get past the IDE setup phase?

### Repro steps

Steps to Reproduce

1. Install Visual Studio 2019

2. Open nuget package manager > Install-Package OpenTK

### Expected behavior

Able to download and reference files

### Actual behavior

Appears to be incompatible with most versions of .NETFramework - can't find the one it is compatible with. 

### Related information 

* Operating system: Windows 10
* SDL or Native backend: Planning to use OpenGL
* What version of OpenTK (Installer, NuGet, Source Code): Attempted NuGet and Source (but got lost with source after not finding the files I Expected)
* What runtime (.NET Framework, CoreCLR, Mono): .NET Framework
* Workarounds (if any); Unknown

**Comment by Jirara** [comment]
I read over the line about .NET Core 3.1 in the Readme, so I'm going to go back and try that. This may be an install issue with .NET more than anything. I'll close this if that fixes it.

**Comment by NogginBops** [comment]
OpenTK 4.0 only supports .net core.
OpenTK 3.3 supports .net framework and mono (and is still receiving bug fixes and still very usable).

**Comment by Jirara** [comment]
That was what I needed. Thank you for answering this! I just ran nuget for 3.3 and it worked perfectly.

**Comment by NogginBops** [comment]
If you have any more questions about opentk or anything like it, feel free to join the discord server.
The support channel is a great place to get often real-time answers.
