### ISSUE TITLE
Struggling with View Projection Matrices

### ISSUE THREAD

**Issue by BJDubb** [opentk/opentk#1191]
I'm writing an engine with OpenTK 4.1.0 and its all working perfectly as expected up until now. I'm trying to add a Model-View-Projection system and I feel like I have written all of the code correctly, however, I am unable to get MVP system to work.

Pre- MVP integration, I have this:
### Basic OpenTK rendering with ImGui for debugging
![image](https://user-images.githubusercontent.com/47697544/98509420-465f2e80-22b5-11eb-8e9d-f92be203fa70.png)

I know that every system I have written so far (Events, Render Pipeline) all works fine. The point where I get lost is in this block of code which lives in the run loop.
```
shader.Bind();
shader.SetMatrix4("uViewProjection", camera.ViewProjectionMatrix);
```
If the matrix being set on the shader is `OpenTK.Mathematics.Matrix4.Identity`, it works fine. But when I try to use the View-Projection matrix from my camera, I get this:
### View Projection set as custom matrix
![image](https://user-images.githubusercontent.com/47697544/98509771-ee74f780-22b5-11eb-85c1-ff56363ddd6e.png)

This leads me to believe that the source of my problem is coming from the camera. However, upon inspection and through debugging, I can't seem to find where the problem occurs. I have a slight feeling it has to do with Row-Major/Column-Major but I have no clue what they are or how to solve them. (Transpose on the `GL.UniformMatrix4` call is `true` also)
```
public class OrthographicCamera
{
    public Matrix4 ProjectionMatrix = Matrix4.Identity;

    public Matrix4 ViewMatrix = Matrix4.Identity;

    public Matrix4 ViewProjectionMatrix = Matrix4.Identity;

    private Vector3 position;
    public Vector3 Position { get => position; set { position = value; RecalculateViewMatrix(); } }

    private Vector3 rotation;
    public Vector3 Rotation { get => rotation; set { rotation = value; RecalculateViewMatrix(); } }


    public OrthographicCamera(float left, float right, float bottom, float top)
    {
        ProjectionMatrix = Matrix4.CreateOrthographicOffCenter(left, right, bottom, top, -1, 1);

        ViewProjectionMatrix = ProjectionMatrix * ViewMatrix;
    }

    private void RecalculateViewMatrix()
    {
        Matrix4 transform = Matrix4.CreateTranslation(position) * 
                            Matrix4.CreateRotationX(rotation.X) * 
                            Matrix4.CreateRotationY(rotation.Y) * 
                            Matrix4.CreateRotationZ(rotation.Z);

        ViewMatrix = Matrix4.Invert(transform);
        ViewProjectionMatrix = ProjectionMatrix * ViewMatrix;
    }
}
```
Any help would seriously be appreciated as I am only very new to graphics programming.

**Comment by NogginBops** [comment]
This indeed looks like a row-major vs column-major issue.
My first recommendation would be to read my explanation about row vs column major matrices in [this](https://github.com/opentk/opentk/issues/687#issuecomment-711425379) issue.

To be able to say anything concrete on this issue you would also have to show the shader source and your `glUniform` call.
If you want to get more real time help you can get that on the discord.

**Comment by BJDubb** [comment]
@NogginBops here is the source for both shaders:
### Vertex
```
#version 330 core


layout(location = 0) in vec3 aPosition;
layout(location = 1) in vec3 aColor;

uniform mat4 uViewProjection;

out vec3 oColor;

void main()
{
    gl_Position = uViewProjection * vec4(aPosition, 1.0);
    oColor = aColor;
}
```

### Fragment
```
#version 330 core

in vec3 oColor;

out vec4 FragColor;

void main()
{
    FragColor = vec4(oColor, 1);
}
```

and here is the actual `GL.Uniform` call:   (`this` is a implicit cast from a custom `Shader` class to `GL_SHADER_ID`)
```
public void SetMatrix4(string name, bool transpose, Matrix4 data)
{
    GL.UseProgram(this);
    GL.UniformMatrix4(GL.GetUniformLocation(this, name), transpose, ref data);
}
```

**Comment by BJDubb** [comment]
### Solution

The problem was in fact a row-major vs column-major issue.

The solution in my case was to flip the multiplication of the 
`ProjectionMatrix * ViewMatrix` to be `ViewMatrix * ProjectionMatrix` in my custom `Shader` class and to flip the multiplication in my GLSL shader from 
`gl_Position = uViewProjection * vec4(aPosition, 1.0);` to `gl_Position = vec4(aPosition, 1.0) * uViewProjection;`

Big thanks to @NogginBops
