### ISSUE TITLE
OpenTK 4.1 and GraphicsContext

### ISSUE THREAD

**Issue by Masclaux** [opentk/opentk#1192]
### Description

Hello,

I'm currently migrating my old engine from OpenTK 1 to 4.10 and one of the object I'am using to bind openTK GL context to my SDL2 (via SDL2-CS) windowing system is gone.

My current sources work with the last OpenTK 3 version and I see the a lot of classes from OpenTK.Graphics disappear during the 4.0 evolution.

I see on the changelog that the version 4 is really a big release and a lot of rewrite had been done. 

Does it exist a new way to doing that ? 

Thanks  !
Jérémy

### Repro steps

Try to use GraphicsContext class

`            GraphicsContext openTKGraphicsContext = new GraphicsContext(new ContextHandle(_glContext)
                , (proc) => SDL_GL_GetProcAddress(proc), () => new ContextHandle(SDL_GL_GetCurrentContext()));   `

### Expected behavior

I should be able to bind my context.

### Actual behavior

Stuck a compile time unresolved reference

### Related information 

* Windows 10 Home
* SDL2-CS (SDL 2.0.12)
* OpenTK  4.10 (NuGet)
* Net Core 3.1

**Comment by NogginBops** [comment]
In 4.0 the thing I think you are looking for is [`IBindingsContext`]() combined with `GL.LoadBindings(IBindingsContext)` (the name might not be 100% correct).
You might also want to look into [`IGraphicsContext`](https://github.com/opentk/opentk/blob/master/src/OpenTK.Windowing.Common/Interfaces/IGraphicsContext.cs) if you have doing things with contexts like multithreading.

`IBindingsContext` is for loading the bindings, i.e. `glGetProcAddress`.
`IGraphicsContext` is for operations such as `MakeCurrent` and `SwapBuffers`.

Hope this helps you figure out a solution. 🙂

**Comment by Masclaux** [comment]
Hi that perfect !

Here a snippet for future searches.

`    class SDLBidingContext : IBindingsContext
    {
        public IntPtr GetProcAddress(string procName)
        {
            return SDL_GL_GetProcAddress(procName);
        }
    }
}`

During initialization

`            _glContext = SDL_GL_CreateContext(_nativeWindow);

            var sdlContext = new SDLBidingContext();
            GL.LoadBindings(sdlContext);`

and that all. It so much better than before.

Thank for your help !
