### ISSUE TITLE
OnRenderFrame FrameEventArgs hitches on window drag

### ISSUE THREAD

**Issue by varon** [opentk/opentk#1195]
### Description

At the moment, the rendering is frozen during window dragging. If the window is dragged for a long time, `FrameEventArgs` can end up with insanely large time steps (which can cause all sorts of other issues).

Either:

- We should continue to render while dragging.
- Pause the timer during the drag completely.

**Comment by NogginBops** [comment]
Moving this to `4.8.0` as this is technically is a breaking change and it likely needs changes to the update loop that should be done after #1538 and #1430

**Comment by NogginBops** [comment]
GLFW doesn't provide a way to detect when a window is "grabbed" on windows (`WM_ENTERSIZEMOVE`/`WM_EXITSIZEMOVE`). We could hook into the window proc in windows to intercept these messages, this might be the solution we have to go for. But for `4.8.0` I'm going to leave this unfixed, and put it towards `4.8.1` behind a feature switch most likely.
