### ISSUE TITLE
NativeWindowSettings.StartVisible = false has no effect

### ISSUE THREAD

**Issue by Tarcontar** [opentk/opentk#1202]
### Description

Creating a `GameWindow` with `NativeWindowSettings.StartVisible = false` has no effect. The window still opens visible.

### Repro steps

1. var nativeSettings = new NativeWindowSettings { StartVisible = false; }

2. var window = new GameWindow(new WindowSettings(), nativeSettings);

### Expected behavior

The window should not be visible.

### Actual behavior

The window is visible (e.g. each unittest using such a window creates a dedicated visible window).

### Related information 

* Operating system: Win10
* SDL or Native backend: OpenGL
* What version of OpenTK (Installer, NuGet, Source Code) v4.2.0
* What runtime (.NET Framework, CoreCLR, Mono) .Net 5.0
* Workarounds (if any) None

**Comment by varon** [comment]
Thank you for the report. Should be fixed by 4.3.0!
