### ISSUE TITLE
Unable to install OpenTK4.x for .NET 4.7.2 target

### ISSUE THREAD

**Issue by DimaS86** [opentk/opentk#1208]
Hello! I tried to update my OpenTK 3.1, but couldn't do that, because it says:
Error Could not install package 'OpenTK.Compute 4.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by NogginBops** [comment]
OpenTK 4 doesn't work on .net framework it only supports .net core.
OpenTK 3 is still supported for .net framework applications.

So if you want to use .net framework OpenTK 3 is the version you want.
