### ISSUE TITLE
Rename OpenTK.OpenAL assembly

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#1209]
For consistency with the rest of the project structure, the project `OpenTK.OpenAL` and corresponding nuget package should be renamed to `OpenTK.Audio` or `OpenTK.Audio.OpenAL`.

**Comment by varon** [comment]
Agreed. We should do this for 5.x

**Comment by NogginBops** [comment]
As I'm already doing some breaking changes to the OpenAL bindings I think getting this into `4.8.0` will be a win.
