### ISSUE TITLE
Hii,  i'm new for opentk , but i do evry thin correct in my project. the problem is when the object is far from the camera (ex: 1000-1300) it didn't shown :(. while i'm using prespective_projection between (0.1, 10000) for close and far planes.

### ISSUE THREAD

**Issue by mynameisdeveloper** [opentk/opentk#1211]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe.

### Related information 

* Operating system
* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code)
* What runtime (.NET Framework, CoreCLR, Mono)
* Workarounds (if any)

**Comment by varon** [comment]
This is a question for #support on Discord. Come join us!
