### ISSUE TITLE
Make OpenTK.Input.Keyboard replacemet available in OpenTK 4+

### ISSUE THREAD

**Issue by Pilzinsel64** [opentk/opentk#1212]
### Description

I am porting my applications to .NET 5 from .NET Framework 4.8. Now, one of my last two problems is that OpenTK.Input.Keyboard isn't present anymore in OpenTK 4. It was brilliant in OpenTK 3 and I wish to see it in newer versions outside of a GameWindow (I am using the GLWpfControl on my own UI).

If it isn't possible to use the KeyboardState management outside a GameWindow, do you know a good replacement for that also works in the background and for Windows Forms in .NET Core? Currently I don't know a replacement that matches the needs I had to OpenTK.Input.Keyboard.

Thanks!

### Expected behavior

Get KeyboardSate also outside of a GameWindow.

### Actual behavior

Only in GameWindow is a property with a managed instance of KeyboardSate.

### Related information 

* Windows 10
* OpenTK 4.3.0
* .NET 5

**Comment by Hromon** [comment]
o/
Event's native window?

**Comment by Pilzinsel64** [comment]
You mean create an empty GameWindow and use the Keyboard of that? Doesn't that only get the real key states of the GameWindow or also system wide, like OpenTK.Input.Keyboard? Or what do you mean? 
The problem for me is: I don't use the game/native window. I use the GLWpfControl and have an own UI (also an own custom form in a seperate library that doesn't depend on OpenTK).

**Comment by varon** [comment]
@Pilzinsel64  - WPF provides it's own input stack, which you would need to hook into.

The reason KeyboardState is not available is that our input system is now coming from GLFW. If you are on another windowing system like Avalonia, GLFW, etc, then you will need to use their native input systems.

**Comment by Pilzinsel64** [comment]
Ah, I understand. Make sense. I will close this then, as it will probably never get implemented.
However, I already found a workaround (until I find a better solution): I use the OpenTK 3 lib (with renamed namespaces) parallel to OpenTK 4 (works well in .NET Core) to use the KeyboardState class. It works well for now until I found a better solution.
