### ISSUE TITLE
Can't install OpenTK with .NET Framework 4.7.1

### ISSUE THREAD

**Issue by AidenWilkins** [opentk/opentk#1215]
Tried to install OpenTK 4.3.0 today for .NET Framework 4.7.1
While installing from NuGet I receive the error 

"Could not install package 'OpenTK.Compute 4.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework"

The only version I can install is OpenTK 3.3.1. Anything in the 4.x.x I cannot.
Anyway to use the latest with .NET Framework 4.7.1?

**Comment by uzername** [comment]
.Net core only

**Comment by NogginBops** [comment]
Opentk 4 is .net core only.
Opentk 3 works on .net framework and mono.

Opentk 3 is still receiving bug fixes etc so there should be no problem using that version.

**Comment by AidenWilkins** [comment]
Ok, thank you
