### ISSUE TITLE
OpenTK 4.3.0 - Context.SwapBuffers intermittently very slow

### ISSUE THREAD

**Issue by lfricken** [opentk/opentk#1216]
### Description

With no other GL calls or really any code running in OnUpdateFrame or OnRenderFrame, the call to Context.SwapBuffers will randomly fall in the range [30ms, 100ms] once every few seconds. For most of that time, it is taking less than 1ms and I can achieve over 300 FPS. But once every 5-10 seconds, the call takes ~50ms.

### Repro steps

1. Copy paste the code into a simple example OpenTK program.

2. Run it and watch the window.

### Expected behavior

Context.SwapBuffers should consistently take almost no time at all, especially while drawing nothing.

### Actual behavior

Context.SwapBuffers takes ~50ms sometimes.

### Related information 

* **Operating system:** Windows 10 with GeForce GTX 970 (Updated drivers yesterday)
* **What version of OpenTK:** Nuget Package (OpenTK 4.3.0) (Latest as of today)
* **What runtime:** .NET Core 3.1 - Console Application

I first experienced this while using OpenTK.NetStandard 1.0.5.32, but switched to this to see if the issue still exists, and it does. I have tried all 4 permutations of [Vsync, Fullscreen] and they all give the same results.

Project build is set to:

- **Optimize code**
- **Allow unsafe code**
- **Define TRACE constant**
- **Platform target: Any CPU**

In static void Main():

                using (var window = new Window())
                {
                    window.Run(60, 60);
                }

In the GameWindow inheritance class, assumed to be called Window in the above code:

        protected override void OnUpdateFrame(FrameEventArgs e)
        {
            monitor.Restart();
            base.OnUpdateFrame(e);
            monitor.Stop();
            if (monitor.Elapsed.TotalSeconds > 0.023f)
            {
                Console.WriteLine($"{nameof(OnUpdateFrame)} was slow: {Math.Round(monitor.Elapsed.TotalSeconds, 3)}");
            }
        }
        protected override void OnRenderFrame(FrameEventArgs e)
        {
            base.OnRenderFrame(e);
            monitor.Restart();
            Context.SwapBuffers();
            monitor.Stop();
            if (monitor.Elapsed.TotalSeconds > 0.023f)
            {
                Console.WriteLine($"{nameof(Context.SwapBuffers)} was slow: {Math.Round(monitor.Elapsed.TotalSeconds, 3)}");
            }
        }
        Stopwatch monitor = new Stopwatch();

![image](https://user-images.githubusercontent.com/6675120/101992105-73b54880-3c76-11eb-9f4f-b0af02826486.png)

**Comment by NogginBops** [comment]
Thank you for the well written report.

The first suspicion I get when reading this issue is that it's related to one of two things:
First suspicion is that it's GC related.
Second one is related to multithreaded optimization in the nvidia driver.

There should exist some way to print to the console when GC pauses happen, and that way figure out if it's GC related.
The easier test is probably the nvidia multithreaded optimization thing. Basically add your application to the nvidia control panel and disable multithreaded optimization and see if that fixes the problem.

**Comment by lfricken** [comment]
My game engine was having GC related lags, which I tracked down and fully addressed. I agree it does feel like a garbage collection issue, but this code does not show any collections by the GC during the slow code. This should count any type of .Net garbage collection, and it shows none.

I'm not an expert in C#, is it possible there are garbage collections that aren't visible to me?

Surround the swap buffer call:

            GCStartLog();
            Context.SwapBuffers();
            GCEndLog(nameof(OnRenderFrame));

Then add these methods:

        void GCStartLog()
        {
            for (int gen = 0; gen < 3; ++gen)
            {
                _gcCollections[gen] = GC.CollectionCount(gen);
            }
        }
        void GCEndLog(string caller)
        {
            for (int gen = 0; gen < 3; ++gen)
            {
                int newVal = GC.CollectionCount(gen);
                if (newVal > _gcCollections[gen])
                    Console.Write($"Garbage Collection for gen {gen} in caller {caller}");
            }
        }
        int[] _gcCollections = new int[3];

**Comment by varon** [comment]
Great report.

Just FYI, even if you call the GC manually it may still execute anyway at an indeterminate time by itself. Your best bet is using a GC free region around the code and timing instead.

See
https://docs.microsoft.com/en-us/dotnet/api/system.gc.trystartnogcregion?view=net-5.0

**Comment by NogginBops** [comment]
I would test the multi-threaded optimization hypothesis first, as that is the easiest one to test.
The symptoms match pretty well with other people who have had problems with that.

**Comment by varon** [comment]
Agree with @NogginBops here.

**Comment by lfricken** [comment]
**That was the solution**
I was in a hurry and missed that part of the post, so thanks for calling it out again!
What work exactly is that setting multi-threading, and why did it cause this issue? I see the setting description mentions that it should be off for older games (directly using OpenGL?)
Are there other NVIDIA control panel settings that I should know about?

**Comment by NogginBops** [comment]
> **That was the solution: disabling the _Threaded optimization_ setting for the application in the NVIDIA Control Panel** which took me a while to figure out was different from GeForce Experience 🤦
> Also I was in a hurry and missed that part of the post, so thanks for calling it out again! 🤦 🤦
> 
> 1. What work exactly is that setting multi-threading, and why did it cause this issue? I see the setting description mentions that it should be off for older games (directly using OpenGL?)
> 2. Are there other NVIDIA control panel settings that I should know about?
> 3. I first saw this issue when calling GL.GetUniformLocation or GL.GetAttribLocation, so I removed those calls assuming they were just slow and not recommended. But it looks like the issue just crops up on the first SwapBuffers or Get***Location call. Is that just because they are blocking? I've added them back and not seen any issues. Are those ok to use every frame?

1. I'm not 100% sure what that setting actually means. I've searched quite a lot online for documentation on it, but I've not found anything that says what it actually does.
2. What you kind of should know is that the driver settings can override any of the settings that you yourself set in the application. So I would take a look in the settings and get a feel for what can be changed. There are some arcane settings in there, but multithreaded optimization is one that has been creating the most noticable issues.
3. You should call `SwapBuffers` every frame, it is what ends the fame. `glGetUniformLocation` could be fine to call every frame, but it could also incur extra overhead (it does shader reflection), so caching these results in a dictionary per shader is a good idea. The uniform locations will not changed during the lifetime of a shader.

Closing this as the issue has been figured out.
