### ISSUE TITLE
2662 errors in Visual Studio 2019 when I double click OpenTK.sln

### ISSUE THREAD

**Issue by mrmsbarnes** [opentk/opentk#1222]
### Description

I download the code from this repository as a zip file.  I unzip the file to a separate folder.  Exploring the unzipped folder, I find OpetTK.sln.  I double click the solution, Visual Studio 2019 starts, and after a few moments it reports 2662 errors of the FS3033, FS3039, FS0072, and other varieties.  Shouldn't this package contain what it needs to build?  Where do I find complete instructions for building version 4.4.0?

* Windows 10 Pro
* SDL or Native backend (don't know what this is)
* What version of OpenTK (Installer, NuGet, Source Code) ---> Source Code
* What runtime (.NET Framework, CoreCLR, Mono)  Visual Studio 2019 turns (Not Responding) when I try to find out.
* 
Microsoft Visual Studio Community 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA110
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.554.20160
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.554.20160
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.554.20160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Nesting   2.6.85
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.8.20241.2
Conda support for Python projects.

Python - Django support   16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.8.20241.2
Profiling support for Python projects.

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

**Comment by NogginBops** [comment]
See [this comment](https://github.com/opentk/opentk/issues/1163#issuecomment-749290354) for details for some pointer in building opentk.

Highlight is:
There are some projects that are not used and can be unloaded (all errors should be in these projects).
And you need to run `./build.cmd` before building inside of visual studio.

**Comment by mrmsbarnes** [comment]
Thank you, Julius.  It would be so helpful to me and others if this comment were somehow incorporated in a README.md or some such at https://github.com/opentk/opentk

Do you know varon?

**Comment by NogginBops** [comment]
This could be added to the readme.
The reason this hasn't been put in the readme yet is because it wasn't meant to stay the way it is.
But it seems like it will remain like this for the immediate future so adding it to the readme makes sense.

I will add it to the readme in a few days.

Yes I know varon.

**Comment by mrmsbarnes** [comment]
To John Häger,

I was looking for instant gratification.  I realize now that even .NET 5.0 is not in fully settled.

But I do hope OpenTK assembles enough muscle to get it better how-to’d when and as possible.  Thank you.

**Comment by NogginBops** [comment]
If you want something that "just works":tm: then i recommend using .net 5 (or .net core 3.1) and downloading OpenTK as a nuget package.

If you are looking for tutorials in using OpenTK 4 I can refer you to this comment for more information.
https://github.com/opentk/opentk/issues/1210#issuecomment-735368701

**Comment by mrmsbarnes** [comment]
Thanks, I’ll look at this again when there’s a better Chapter1.  In Program.cs maybe ‘new Window’ should be ‘new GameWindow’.  I don’t know.

**Comment by NogginBops** [comment]
Not sure what you are referring to in chapter 1. There is a class defined in chapter 1 called `Window`.
The current tutorials are pretty good.

What is it you would like to be better about them?

**Comment by mrmsbarnes** [comment]
I follow your ‘#1210 (comment) <https://github.com/opentk/opentk/issues/1210#issuecomment-735368701> ’ link to https://github.com/opentk/opentk/issues/1210#issuecomment-735368701

There it says ‘ <https://github.com/inputusernamehere/LearnOpenTK/tree/feature/4.0> Here is a more convenient link to that repo’,  ‘Here’ is at https://github.com/inputusernamehere/LearnOpenTK/tree/feature/4.0

I open “Chapter1”. It has 1-CreatingAWindow.  That has Program.cs.  Program.cs has

 

using OpenTK.Mathematics;

using OpenTK.Windowing.Desktop;

 

namespace LearnOpenTK

{

    public static class Program

    {

        private static void Main()

        {

            var nativeWindowSettings = new NativeWindowSettings()

            {

                Size = new Vector2i(800, 600),

                Title = "LearnOpenTK - Creating a Window",

            };

 

            // To create a new window, create a class that extends GameWindow, then call Run() on it.

            using (var window = new Window(GameWindowSettings.Default, nativeWindowSettings))

           {

                window.Run();

            }

 

            // And that's it! That's all it takes to create a window with OpenTK.

        }

    }

}

 

Line 17 gave me an error when I tried to build.

 

The real problem was coercing Visual Studio 2019 Community into making a solution having 1-CreatingAWindow.csproj (or its contents) as the project file.  Not easy.  At least you know now what I was referring to.

Maybe example dotnet or .sln files would help in the future.

Thanks for all your help.  I’ll check opentk again in a couple months.

**Comment by NogginBops** [comment]
I think you are missing a file. In chapter 1 there are two files. The other one contains the definition for `Window`.

**Comment by NogginBops** [comment]
Ideally we don't even want to distribute source as a "tutorial". Because that just leads people to copy paste code and not actually learn something from it.
If you read the tutorial on the site opentk.net and reference the 4.0 repo you found for api changes you are going to have a much better tutorial.
