### ISSUE TITLE
Question: Can I use this for Image generation from OBJ 3d files in a docker container in K8S?

### ISSUE THREAD

**Issue by ewassef** [opentk/opentk#1225]
### Description

I have a need to be able to request different image assets, transparent PNG, SVG & JPG that are automatically generated from bare-bone OBJ files. Say, for example, you are building a custom product and want to add different features and options to it. Once complete, we want to generate a report to be sent via email, displayed in a web browser or in a native app. 

Ideally, we want this to be behind an API in Kubernetes in .NET containers running on Linux nodes.

### Repro steps

Generate a side view of a product from OBJ file to a PNG with 50% opacity and transparent background

1. Load OBJ file stream  (Textures optional)

2. Apply scene, camera and lighting
3. Export to PNG and return PNG Stream
 
* Operating system : VS2019, Windows DEV machine, Linix Docker image

**Comment by NogginBops** [comment]
OpenTK is a low level wrapper around OpenGL. 
We don't provide anything on top of OpenGL except a few math structs that make working with opengl more convenient. 

We do not handle anything related to file-formats, reading nor writing.

You can definitely render images using OpenGL (png compression you will need to do yourself, opengl can give you raw pixel data), but if your K8s cluster doesn't have a gpu then it's not going to work. You will also need to create a headless OpenGL context which comes with it's own complications.

If you are looking for a high level library for 3d rendering to png images, this is not it.
