### ISSUE TITLE
Migrating to OpenTK 4

### ISSUE THREAD

**Issue by CaiB** [opentk/opentk#1226]
### Description
After migrating my project from OpenTK 3 ([OpenTK.NetStandard](https://www.nuget.org/packages/OpenTK.NetStandard/) actually) to OpenTK 4, there are hundreds of errors. I browsed the GitHub and website to find a migration guide to give guidelines on what needs to be changed or updated in order to get everything sorted out, but found nothing.

Either I'm just dense and unable to find this (please make it more prominent if so), or there is no clear, single source of information on how to complete this migration. While a lot of it is relatively simple, with namespace changes, there are some things I see where there is more nuance, and not having any guidance is... concerning.

(I removed the rest of the template as it doesn't make sense, this isn't a specific case)

### Related information 
* Windows 10 / Linux
* OpenTK from NuGet
* .NET Core 3.1 -> .NET 5

**Comment by NogginBops** [comment]
At the moment there is no written guide to migrating.
My guess is that most of the errors are due to some namespace changes.
Most of the other changes are related to windowing and input.

Below I will link to some projects using OpenTK 4 so you can figure out how they migrate to the new api:
- https://github.com/opentk/LearnOpenTK - Mostly gl stuff, but it creates a window and some keyboard stuff.
- https://github.com/NogginBops/ImGui.NET_OpenTK_Sample/blob/opentk4.0/Dear%20ImGui%20Sample/ImGuiController.cs#L201 - here is an example of using the new input APIs.

If you have any more specific questions you are welcome to ask them here or in the discord and we can help you figure it out. 🙂

**Comment by CaiB** [comment]
Previously I was able to both get and set `GameWindow.ClientSize` in order to set the size of my window based on the size of the content, rather than content + border + decoration. While it looks like I can still get this size as `GameWindow.ClientSize.X` and `GameWindow.ClientSize.Y`, this no longer permits setting the property.

I found one super ugly way to do it, please let me know if there is a nicer way to accomplish this:
```C#
/// <summary> The width of the window contents, in pixels. </summary>
public int Width
{
    get => this.ClientSize.X;
    set => this.ClientRectangle = new Box2i(this.ClientRectangle.Min, new Vector2i(this.ClientRectangle.Min.X + value, this.ClientRectangle.Max.Y));
}

/// <summary> The height of the window contents, in pixels. </summary>
public int Height
{
    get => this.ClientSize.Y;
    set => this.ClientRectangle = new Box2i(this.ClientRectangle.Min, new Vector2i(this.ClientRectangle.Max.X, this.ClientRectangle.Min.Y + value));
}
```

Thanks!

**Comment by CaiB** [comment]
I have one more question, a much more nitpicky one. I've noticed ever since moving to OpenTK 4, probably due to the new window handling, that there's quite a bit going on when my application opens.

Previously, the window opened a few frames later, once everything was configured, ready, and OpenGL had the 1st frame ready. It was nice and smooth.  
Now I have a default white "OpenTK Window" open, then close, then a correctly-sized white window opens, turns black, then the first frame gets rendered. Overall, the delay between nothing open to rendering frames is about the same, it just appears that the new system tries to get _something_ on the screen before everything is ready.

I'd prefer to suppress anything from opening until it's all configured and ready to go. Is there an easy way to do this?

Here's a comparison of the old vs new, at 1/12th speed:
Old:
![opentkold](https://user-images.githubusercontent.com/6701127/103735212-6bfd7100-4fa2-11eb-8efe-d62a2cb12b25.gif)


New:
![opentknew](https://user-images.githubusercontent.com/6701127/103735219-6f90f800-4fa2-11eb-81d9-4567894ab059.gif)

When the `"Reading config for DisplayOpenGL ..."` line gets printed is when the `GameWindow` class gets initialized. (The new system immediately opens the first window now)  
After that, it will read some more data from the config file, like the window size. This gets applied at that time.  
Finally, once all the config has been read and everything ready, I call `Run();` in the `GameWindow`. (The old system shows the window now)  
Please let me know if there's something else I should do instead.

**Comment by NogginBops** [comment]
I could take a look at this tomorrow if you send me a repro of the startup thing.

The first issue you mentioned showed me that the window size handling code seems a bit off. So that is something we can probably fix.

The second one sounds like it might be fixable, but I'm not sure. Would have to look closer at a repro to be able to figure that one out.

**Comment by CaiB** [comment]
Thanks for the quick response!

If you want to look at it in the full project, you can download the built project and/or source code here:
Old version: https://github.com/CaiB/ColorChord.NET/releases/tag/auto-v0.6.0.105
New version: https://github.com/CaiB/ColorChord.NET/releases/tag/auto-v0.6.0.108

The old version is built on .NET Core 3.1, new one .NET 5.

The default `config.json` that it uses won't 100% match the output you see above but should exhibit the same behaviour. Let me know if you want the one I used.

If you want me to make a minimal project that just has the stuff needed to show the behaviour, let me know, I can probably put something together. If you're just going to work with my code as-is, the config parsing happens in `ColorChord.NET/ColorChord.cs:107` which will construct a `ColorChord.NET/Outputs/DisplayOpenGL` (Extends `GameWindow`), then call `DisplayOpenGL.ApplyConfig()`, where width & height get set, and finally `DisplayOpenGL.Start()`.

**Comment by NogginBops** [comment]
This first issue I find is that you are passing the default `NativeWindowSettings`, which defaults to `StartVisible = true`, which is likely not what you want in this case.

I would also recommend that if you can, you should send as much data through the window settings as possible as that will minimize the amount of things the OS will have to do to a hidden window (OSes are weird and they all do weird things with hidden windows).

Here is the property in question:
https://github.com/opentk/opentk/blob/master/src/OpenTK.Windowing.Desktop/NativeWindowSettings.cs#L135

And then before you call `Run()` set the `IsVisible` property of the window to `true`.

Hope this helps you with the issue of the weird flashing.

**Comment by NogginBops** [comment]
I've started looking into the sizing issue and it's indeed just a missing part of the API, but I am pretty busy at the moment so I might not get to it for the next two weeks or something.
While looking at the sizing part of the code I realized there are some issues with it that should ideally be fixed (edge case stuff mostly).
I posted kind of a summary of the issue on the discord, so someone there might want to fix it before I get to it.

**Comment by CaiB** [comment]
[I've updated the code with your suggestions](https://github.com/CaiB/ColorChord.NET/commit/9c9e29c73b2c45850d1bbef2b955b8f2d75f9b0c), and it's working well now.

Sadly due to how my config reading is structured right now, having all of the settings ready at the time of the constructor being called is not easy. Hopefully in the future when I restructure how my config reading works I'll be able to get that working nicely as well.

I'm not in a big rush to get the nicer window sizing API, it seems to work well as it is now, just a bit cumbersome to use. That said, please let me know when this work is completed so I can use the new features.

Thanks for all the help!

**Comment by CaiB** [comment]
Well, sadly I have encountered a new issue. I downloaded the [latest autobuild of my application](https://github.com/CaiB/ColorChord.NET/releases/tag/auto-v0.6.0.113) on a different, non-dev computer, and updated my .NET Runtime from Core 3.1 to 5.0. Upon running my program, I get this fun error:

`System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)`

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'OpenTK.Windowing.Desktop.NativeWindowSettings' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'glfw' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..ctor()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..cctor()
   --- End of inner exception stack trace ---
   at ColorChord.NET.Outputs.DisplayOpenGL.SetupNativeWindow() in C:\projects\colorchord-net\ColorChord.NET\Outputs\DisplayOpenGL.cs:line 46
   at ColorChord.NET.Outputs.DisplayOpenGL..ctor(String name) in C:\projects\colorchord-net\ColorChord.NET\Outputs\DisplayOpenGL.cs:line 38
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ColorChord.NET.ColorChord.CreateObject[InterfaceType](String fullName, JToken configEntry, Boolean complexConfig) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 126
   at ColorChord.NET.ColorChord.ReadConfig() in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 107
   at ColorChord.NET.ColorChord.Main(String[] args) in C:\projects\colorchord-net\ColorChord.NET\ColorChord.cs:line 32
```

I was able to run the OpenTK 3-based version on this same computer without issue.

Please let me know if it makes sense for me to open a separate issue about this. I found #1108 but this was apparently resolved and seemed slightly different.

System Info:
- Windows 10 Pro x64 2004 (19041.685)
- Intel HD Graphics 4000 (Driver ver 10.18.10.4252, date 2015-07-09) / AMD Radeon HD 7800M Series (Driver ver 26.20.12028.2, date 2019-08-15)
- .NET 5.0

**Comment by NogginBops** [comment]
I think it makes sense to open a separate issue regarding this.
One thing you could test is if you create a build from a new project and see if you can open a window or if you get the same issue.

**Comment by CaiB** [comment]
Tested that as well, same issue. Moving to #1228.

**Comment by NogginBops** [comment]
Closing this issue as it seems mostly resolved, and the parts that are unresolved are in #1228 

If this is not true then feel free to reopen the issue
