### ISSUE TITLE
GPL v3 license present in project source

### ISSUE THREAD

**Issue by pl-ai** [opentk/opentk#1229]
### Description

The repository contains GPL-3.0 and 3.0+ files although the overall license says MIT.

### Repro steps

Please provide the steps required to reproduce the problem

1. For OpenTK v3.1.0:
     ./src/OpenTK/Platform/Egl/EglException.cs is GPL-3.0
     ./src/Generator.Rewrite/Program.cs is GPL-3.0+

2. For OpenTK v4.4.0
     opentk-master/src/Generator.Rewrite/Program.cs is GPL-3.0+

### Expected behavior

All source files to have MIT license.

### Actual behavior

Some source files have GPL licenses.

### Related information 

* Operating system
* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code)
* What runtime (.NET Framework, CoreCLR, Mono)
* Workarounds (if any)

**Comment by varon** [comment]
Thanks for alerting us to this, @pl-ai !

None of the current maintainers team had any idea of this. We did not merge or author this code. Thankfully, the EGLException isn't used anywhere in the codebase, but we'll take steps to remove that and update the packages.

We were also unaware of the licensing of the Rewriter. Fortunately, we do not distribute the Rewriter code, as this is an optional internal tool, so the package licensing for both 3.x and 4.x can remain MIT.

Work is underway on OpenTK 5.0, which completely removes the need for the Rewriter, which should bring our entire repository in line with the expected licensing.

For now, we will also list the current rewriter as being GPL in the THIRD_PARTIES.md.

**Comment by pl-ai** [comment]
Thank you varon. Could you provide an ETA on when you will update the packages?

**Comment by NogginBops** [comment]
I think I will be able to do the relevant PRs this weekend. So if no-one has made a PR before then I will probably make one.
