### ISSUE TITLE
How to install opentk *offline*?

### ISSUE THREAD

**Issue by Speckiwassonst** [opentk/opentk#1230]
Hello,

in former times, it didn't seem a problem to install opentk offline - after simply having downloaded a .zip or sth. like that.

Today the only possibilities seem to be 

a) downloading opentk-master.zip with the necessity of building it myself - facultatively *being online*. Had to try it on a friend's machine - our employer simply hates this »cloud-here - cloud-there«. Some day - he says - you'll even be allowed to go to the rest-room only provided you're connected to the internet :->>. Build.cmd produced nothing but error-after-error, in the end terminating without notice.

b) this nuget-stuff, again only working when being online.

For both cases, we get no permission.

Is there a possibility of obtaining a current opentk version ready-to-use (just like in former times), that can simply be distributed locally to the machines it is needed for? Or is the only possibility one of the ways mentioned above? Then - as our boss said - we'll abandon C#, .Net and simply turn to Java with pure OpenGL...

Is there anybody who can help?

**Comment by NogginBops** [comment]
There are some alternatives for doing this.
Firstly the build *should* work. Though atm a working build will produce a lot of errors during build.
If you could provide parts of the log with some of the errors that would be great.

There are ways to download nuget packages for offline use.
What you do is go to the nuget site https://www.nuget.org/packages/OpenTK/
Then you click the `Download package` link:
![image](https://user-images.githubusercontent.com/3778357/104652221-110dfd00-56b9-11eb-90a4-cf7cc1cb0108.png)

This will give you a `.nupkg` file that you can either put into an offline nuget source repo (possibly in the version system you use) or you could unzip the package (`.nupkg` is actually just a zip file) and extract the `.dll` files from there and then reference those in your project.

**Comment by Speckiwassonst** [comment]
Thank you for your quick response, I appreciate your help very much. Having had quite a long time without programming etc., things have changed considerably.

Concerning the logs you talked about, I might have a look sometime the next days and post some.

The download of the .nupkgs already happened. But there seems to be another problem, concerning the »main«-file (opentk.4.4.0.nupkg). Generally they all have similar content, i. e. file-types & folders, but unlike the additional dependency files, the first one only has package- & _rels-folders - but no lib-folder containing a .dll-file as the others.

Hope the guys al NuGet just forgot to put it inside & will correct their mistake soon.

Cheers

JS

**Comment by NogginBops** [comment]
The fact that the "main" package doesn't have any dlls in it is actually fine. 
It should only exists to reference in all of the dependencies.
If you where using a local nuget stream/repo/whatever they are called you would just have to reference the main package.
But that doesn't apply if you are extracting the dlls.
So you just reference all the dlls you find and it should work.

**Comment by Speckiwassonst** [comment]
Then I ' ll have a try. Thank you very much :-)

Kind regards

JS

**Comment by NogginBops** [comment]
Any updates on this?

**Comment by moon672** [comment]
Just use nuget. It will download all the necessary files for opentk when you it to a project for the first time. Those opentk files will be then stored locally on your machine. So, if you the nuget package any other package afterward, you don't have redownload all of them; the local files will be used.

**Comment by NogginBops** [comment]
Closing this as I'm assuming it worked.
