### ISSUE TITLE
Add Support for gl_sharing in OpenCL

### ISSUE THREAD

**Issue by JanTamis** [opentk/opentk#1236]
Can we add support for: [https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/gl_sharing.html](url)

**Comment by NogginBops** [comment]
We currently don't have anyone that is very active in improving the OpenCL bindings.
I agree that this is probably something that we want to support, but I can't say when this will be implemented.

If you need this feature then it doesn't look like a ton of work to implement the functions needed. If you ping me in the discord I can walk you through how to add the bindings yourself.

**Comment by NogginBops** [comment]
I think #1245 closed this issue.
