### ISSUE TITLE
Cannot install via NuGet

### ISSUE THREAD

**Issue by gitblogger** [opentk/opentk#1239]
### Description

Trying to install into a project that targets .NET framework 3.5 on visual Studio 2019. Getting the following error:
Could not install package 'OpenTK.Compute 4.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

### Repro steps

1. Open nuGet package manager.
2. Search for and select OpenTK.
3. Click "Install" and click "OK" on the next dialog.

### Expected behavior

Successful download and installation.

### Actual behavior

Throws an error:

Could not install package 'OpenTK.Compute 4.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		

### Related information 

* Operating system: Windows 10 20H2
* SDL or Native backend: None that I know of
* What version of OpenTK (Installer, NuGet, Source Code): NuGet latest version
* What runtime (.NET Framework, CoreCLR, Mono): .NET Framework 3.5
* Workarounds (if any): None that I know of.

**Comment by NogginBops** [comment]
OpenTK 4 targets .net core 3.1. It will not work on .net framework.
If you need to run OpenTK on .net framework, you want to go for OpenTK 3.
OpenTK 3 is still getting PRs merged so there is no reason such reason to not use OpenTK 3.

**Comment by MindKafuu** [comment]
Hey, I have the same problem. I really need how to fix it. 

Could not install package 'OpenTK.Compute 4.6.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		

It work at OpenTK 3 but I need to use matrix4.

**Comment by NogginBops** [comment]
Did you read my answer?
You need to install OpenTK 4.

In opentk 4 the math types live in the `OpenTK.Mathematics` namespace so that is likely why `Matrix4` stops working after the upgrade.

**Comment by MindKafuu** [comment]
@NogginBops Yes, I tried to install OpenTK 4 every version but it doesn't work for me

Could not install package 'OpenTK.Compute###  4.0.0'. You are trying to install this package into a project that targets '.NETF
ramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.

**Comment by NogginBops** [comment]
Ah I see now, you are trying to install OpenTK 4 into a project that is targeting .net framework. This will not work as I've explained above. You will either have to update to .net core or use OpenTK 3.
