### ISSUE TITLE
[Question] Why Window* WindowPtr and not IntPtr WindowPtr?

### ISSUE THREAD

**Issue by typpos** [opentk/opentk#1242]
Why does OpenTK define the opaque GLFW window handle as a pointer to an empty struct, Window*, and not as an IntPtr? The use of Window* cascades the need to use  "unsafe" throught the code base and I don't think OpenTK actually ever makes use of the pointer.

**Comment by NogginBops** [comment]
This is a handle that is exposed to people who want to interact with GLFW more directly than the normal `NativeWindow` and `GameWindow` API lets you.
I remember that there was a discussion about what type to expose, I don't remember exactly but I think the idea was that people you want to use the window handle know what they are doing, and using `unsafe` we can have that as a "opt in" thing for people who know what they are doing.

You can easily cast the pointer to `IntPtr` by just casting `(IntPtr)window.WindowPtr`, and or if you are extending `GameWindow` or `NativeWindow` you can easily shadow the original property with your own property with the type you want.

**Comment by typpos** [comment]
Thanks for your time.

I think you implicitly answered my question: There isn't an architecture requirement; it was simply a choice made.

I would have gone (nad preferred) the other way round, ie, by default use IntPtr and let "people who know" cast that into a pointer. I do simple things and constantly need to use "unsafe". 

Example: "Close the NativeWindow when it wants to die, but don't exit the application because I have multiple windows". How to do that? My approach: `unsafe { GLFW.DestroyWindow(w.WindowPtr);` so it needs unsafe even though it's a "simple" thing.  (Admittedly, I'm newish to OpenTK and there might be better ways)

**Comment by NogginBops** [comment]
You can use the `NativeWindow.Close()`, but that exits the internal `Run()` loop. So if you are relying on that loop I think what you currently do is a working workaround (if it works ofc). You could make/override your own `Close()` if you wanted to minimize the use of `unasafe`.

Closing this issue as it's been answered.
