### ISSUE TITLE
OpenTK.Graphics on UWP

### ISSUE THREAD

**Issue by AkshayFT** [opentk/opentk#1243]
### Description
Trying to create a UWP app which uses OpenGL via OpenTK.

### Repro steps

1. Install OpenTK.Graphics via NuGet.

### Expected behavior

Should be able to install OpenTK.Graphics on UWP.

### Actual behavior
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package restore failed. Rolling back package changes for 'FTWritingUWP'.				
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393). Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-arm. Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x86. Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x86-aot. Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x64. Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-arm-aot. Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x64-aot. Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	
Error	NU1202	Package OpenTK.Graphics 4.5.0 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-arm64-aot. Package OpenTK.Graphics 4.5.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	FTWritingUWP	C:\Users\aksha\source\repos\FTWritingUWP\FTWritingUWP\FTWritingUWP.csproj	1	

```
Attached Screenshot

### Related information 

Edition	Windows 10 Pro
Version	20H2
Installed on	‎23-‎02-‎2021
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0

* SDL or Native backend
* OpenTK 4.5.0
* UWP

![OpenTK_With_UWP](https://user-images.githubusercontent.com/43599387/109606034-0ebe1000-7b4c-11eb-869e-94b201db2cf2.PNG)

**Comment by NogginBops** [comment]
I'm guessing you are aware that OpenGL doesn't run on UWP and you are planning on using something like ANGLE?

The full OpenTK package currently only works on .net core.

If you want to use ANGLE with OpenTK what you can do is download the `OpenTK.Graphics` nuget package.
This package contains the actual gl bindings with basically none of the windowing stuff.
What you can then do is use ANGLE to create a context and wrap that in a `IBindingsContext` and pass it to `GL.LoadBindings`. Which will load the bindings so that you can call gles functions

**Comment by NogginBops** [comment]
I accidentally closed the issue with my comment...

**Comment by AkshayFT** [comment]
Got it!
I feel this issue should not belong here. Hence closing.

It'll be helpful, if someone could point out the resources to use OpenTK with ANGLE Compatibility.

**Comment by NogginBops** [comment]
I'm not 100% sure of how to get OpenTK 4 working with ANGLE.
There are a few things you need to get it working:
1. Ability to call ANGLE functions from C#. This can be done using `DllImport` and [PInvoke](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke) without too much pain.
2. Use the EGL functions in ANGLE to create a gl context of some sort (idk exactly how this would would work, you would need to read some ANGLE documentation and probably some UWP documentation).
3. When you've got ANGLE creating a context you can create an implementation of `IBindingsContext` that just wraps the function `glGetProcAddress` exposed by either ANGLE EGL or ANGLE OpenGL ES.
4. Then you can pass that `IBindingsContext` to `OpenTK.Graphics.ES30.GL.LoadBindings` and then you can use the bindings provided by OpenTK

**Comment by mediaexplorer74** [comment]
> 

Very interesting dialog, indeed :) Did you have some simplest examples of Angle+OpenTK+UWP combination using? =)

**Comment by NogginBops** [comment]
I unfortunately don't have any samples of ANGLE being used with OpenTK, nor anything related to UWP.
