### ISSUE TITLE
OpenTK.Core.Exceptions.BindingsNotRewrittenException: "Rewrite.exe has not been run."

### ISSUE THREAD

**Issue by saskathex** [opentk/opentk#1259]
### Description

Upgrade from 4.6.0 to 4.6.1. raises an BindingsNotRewrittenException "Rewrite.exe has not been run.". Switching back to 4.6.0 and 4.5.0 everything works as expected

### Repro steps

Extended OpenTK example: Calling var version = GL.GetString(StringName.Version);
 call raises exception.

### Expected behavior

To work correctly. 

### Actual behavior

OpenTK.Core.Exceptions.BindingsNotRewrittenException: "Rewrite.exe has not been run."

### Related information 

* Windows 10
* Native Backend
* OpenTK 4.6.1 nuget package
* .Net 5.0

**Comment by csobsidian** [comment]
Getting the same here using 4.6.1.

First call to GL.ClearColor(); raises exception.

Windows 10
OpenTK 4.6.1 nuget package
.Net Core 3.1

**Comment by NogginBops** [comment]
We are working on a fix for the issue. The latest release made some changes to how the packages need to be built, we thought we fixed it for 4.6.1 but it seems we missed a part of the fix.

The current workaround is to use .net 5 or use OpenTK 4.5.0.
Hopefully it will be fixed with a 4.6.2 later today or tomorrow.

**Comment by csobsidian** [comment]
Thanks for the quick response.

Just to be clear, according to OP and my test just now, switching to .NET 5 does not resolve the issue. The only solution is to revert to an earlier version of OpenTK.

**Comment by NogginBops** [comment]
Ok thanks for the heads-up about .net 5. I know 4.6.0 worked fine on .net 5 (I'm running that version in my own project), but 4.6.1 might have broken .net 5.

**Comment by NogginBops** [comment]
@saskathex @csobsidian 4.6.2 should hopefully fix all of the issues with 4.6.0 and 4.6.1.
https://www.nuget.org/packages/OpenTK/4.6.2

**Comment by vfrz** [comment]
4.6.2 has fixed it for me!

**Comment by saskathex** [comment]
Everythings works as expected with 4.6.2. Thank you for the quick response and fixing.
