### ISSUE TITLE
The while/if conditions in the update/render dispatch methods make no sense.

### ISSUE THREAD

**Issue by burnss9** [opentk/opentk#1264]
https://github.com/opentk/opentk/blob/0b3797c018e5289ea6f927cbce1ac1b56b2070e5/src/OpenTK.Windowing.Desktop/GameWindow.cs#L297-L334

**Comment by burnss9** [comment]
After staring at this for a long time I think they may actually be correct but whew there must be a better way to write this

**Comment by frederikja163** [comment]
Not sure what the issue is, could you please either specify the issue and version or close the issuee.
