### ISSUE TITLE
OpenTK Says 360 controller has no vibration

### ISSUE THREAD

**Issue by Meerkov** [opentk/opentk#1266]
### Description
The capabilities reads that it has no left or right motor, and refuses to vibrate when calling SetVibration(1, 1).

**Comment by NogginBops** [comment]
What version of OpenTK are you using?

**Comment by varon** [comment]
Closing. Two weeks with no extra info. Please re-open with a better report.

**Comment by Meerkov** [comment]
Answered offline: all version are effected. But I was using 3
