### ISSUE TITLE
singular `GL.Delete*` overloads cause crashes

### ISSUE THREAD

**Issue by user11681** [opentk/opentk#1277]
### Description
Singular `OpenTK.Graphics.OpenGL.GL.Delete*(in uint)` overloads cast handles to `uint*`, producing invalid pointers and causing a silent crash.

### Repro steps
1. Generate a buffer (or other object; I tested with buffer, texture and vertex array) and store its handle.
2. Pass the handle to `OpenTK.Graphics.OpenGL.GL.DeleteBuffer(in uint)`.

### Expected behavior
The invocation completes successfully and the application proceeds as normal.

### Actual behavior
The invocation crashes the application without producing any information.

### Related information 
* Artix Linux
* Backend: native
* OpenTK 5.0.0-pre.3 from NuGet
* Runtime: .NET Core 5.0
* Workarounds: the `OpenTK.Graphics.OpenGL.GL.Delete*s(int, in uint)` methods, which use `fixed` instead of casting

**Comment by NogginBops** [comment]
Thanks for the report.
OpenTK 5 is quite early in it's life and there are quite a few issues related to pointer handling for the different overloads.
If you want something stable I recommend using OpenTK 4 or OpenTK 3.

This should be quite easy to fix.
Me and @frederikja163 are going to revisit our pointer handling for the overloads when we have time to do so. But we are both quite busy at the moment so it might be a little while.

**Comment by frederikja163** [comment]
Closing as this is fixed by #1281, thanks for the report, please let us know if you find other errors in otk5. Early adopters are crucial in finding bugs early in the project.
