### ISSUE TITLE
Version 3.3.2 missing enums for opengl 4.6 GL_ARB_indirect_parameters

### ISSUE THREAD

**Issue by robbyxp1** [opentk/opentk#1319]
### Description
There appears to be missing enum identifiers in enum.BufferTarget and enum.GetIndexedPName for the following 4.6 additional parameter buffer.

From https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_indirect_parameters.txt:

New Tokens

    Accepted by the <target> parameters of BindBuffer, BufferData,
    BufferSubData, MapBuffer, UnmapBuffer, GetBufferSubData,
    GetBufferPointerv, MapBufferRange, FlushMappedBufferRange,
    GetBufferParameteriv, and CopyBufferSubData:

        PARAMETER_BUFFER_ARB                                    0x80EE

    Accepted by the <value> parameter of GetIntegerv, GetBooleanv, GetFloatv,
    and GetDoublev:

        PARAMETER_BUFFER_BINDING_ARB                            0x80EF

### Repro steps

1. Try defined GL.BindBuffer(BufferTarget.ParameterBuffer, 0) - it fails
2. Missing   GL.GetInteger(GetIndexedPName.ParameterBufferBinding)

### Expected behavior

GL.BindBuffer(BufferTarget.ParameterBuffer, bufid) etc

Please provide a description of the behavior you expect.

### Related information 
OpenGL 3.3.2  .Net NUGET package.

* Workarounds (if any)
   GL.BindBuffer((BufferTarget)0x80ee, Id); - this works, and i've demonstrated it.

**Comment by robbyxp1** [comment]
Also, in the definition of  GL.MultiDrawElementsIndirectCount

       public static void MultiDrawElementsIndirectCount(PrimitiveType mode, All type, IntPtr indirect, IntPtr drawcount, int maxdrawcount, int stride);

Should not type All actually be DrawElementsType as per its simpler operation:

        public static void MultiDrawElementsIndirect(PrimitiveType mode, DrawElementsType type, IntPtr indirect, int drawcount, int stride);

**Comment by NogginBops** [comment]
Are these enum values missing from the `All` enum too?
Otherwise a workaround is using the `All` enum to find the value you want and then cast that to the appropriate enum type.

**Comment by NogginBops** [comment]
This will be fixed in 4.7.2!

**Comment by robbyxp1** [comment]
This also needs fixing on the 3.x code set, as people are still using .net framework. Thanks

**Comment by NogginBops** [comment]
Fair enough, reopening this issue and assigning it to the next OpenTK 3 milestone.
