### ISSUE TITLE
+ instead of - in Box2i.Center

### ISSUE THREAD

**Issue by g7ChoGXh** [opentk/opentk#1325]
### Description

It seems like there is a `+` instead of a `-` in the `HalfSize` part of the `Box2i.Center` property.

### Repro steps

Create a `Box2i` with `Min` = (264; 432) and `Max` = (536; 492).

### Expected behavior

`Center` should be between `Min` and `Max` componentwise, in this case (400; 462).

### Actual behavior

`Center` = (664; 894).

### Related information 

OpenTK NuGet Version: 4.6.4

Workarounds:
* Implement `Center` extension method as `Min + HalfSize`.
* Convert the `Box2i` into a `Box2` and use its `Center` property.

**Comment by g7ChoGXh** [comment]
Relates to #1033 and #1037.

**Comment by NogginBops** [comment]
Thanks for the bug report!
The implementation for `Box2i.Center` is indeed broken and it looks like `Box3i.Center` also contains the same bug.

For some reason it's implemented like this...
```cs
public Vector2 Center
{
    get => ((_min + _max).ToVector2() * 0.5f) + _min.ToVector2();
}
```

If no-one has made a PR before 4.6.5 is ready I'll make a PR for 4.6.5.

**Comment by NogginBops** [comment]
On closer inspection it seems like a lot of the `Box2i` and `Box3i` implementations can be significantly improved for both code clarity and performance.

**Comment by g7ChoGXh** [comment]
Thanks for the quick reaction! I think your fix did introduce a possible arithmetic overflow, though: When finding the midpoint of two `int`s, adding and halving the sum will overflow on the addition for particularly large values. `min + (min - max) * 0.5` is less efficient but avoids the overflow.

**Comment by NogginBops** [comment]
Great catch!
Should have waited just a few more minutes before making a release...

I'll make a new release shortly with the new fix.

**Comment by g7ChoGXh** [comment]
Awesome, thanks for your effort!
