### ISSUE TITLE
Create window with GLFW or openTK GameWindow

### ISSUE THREAD

**Issue by LuisMerinoP** [opentk/opentk#1342]
This is not an issue, but a quiestion. 
Found there are two way to open a window + inpuSystem:

1.- With the brand new GLFW-based windowing and intput systems:

```
class Program {
    static unsafe void Main(string[] args) {
      GLFW.Init();
      Window* window = GLFW.CreateWindow(800, 800, "GLFW", null, null);

      while (!GLFW.WindowShouldClose(window)) {

        GLFW.SwapBuffers(window);
        GLFW.PollEvents();
      }
  }
```
2.- With the creating window tutorial approach here, correcting the code a bit.

```
class Program {
    static unsafe void Main(string[] args) {    
      using (Game game = new Game(800, 600, "LearnOpenTK"))  {
        //Run takes a double, which is how many frames per second it should strive to reach.
        //You can leave that out and it'll just update as fast as the hardware will allow it.
        game.Run();
      }
    }
  }
```
Being the Game class (code slightly corrected from the tutorial [source](https://opentk.net/learn/chapter1/1-creating-a-window.html)):

```
public class Game: GameWindow
{
  public Game(int width, int height, string title) : base(GameWindowSettings.Default, NativeWindowSettings.Default) { }
  protected override void OnUpdateFrame(FrameEventArgs e) {
    //KeyboardState input = Keyboard.GetState();

    if (IsKeyDown(Keys.Escape))
    {
      //Exit();
      Close();
    }
    base.OnUpdateFrame(e);
  }
}

```
In one hand I am familiar with the GLFW library and input system from some c++ adventures, but not though with the idea of handling unsafe code. Although I might be familiar with c++ memory management and pointers, I am not with c#. Moreover this is a very mature window + input library.

On the other, the openTK windowing + input approach seems to be very simple, the one adviced in the tutorial and apparently better embedded in openTK overall.

Any caveats or pros and cons about the facts that might support one windowing + input system or the other?

Thanks for any comments

**Comment by PJB3005** [comment]
> Although I might be familiar with c++ memory management and pointers, I am not with c#

C# allows you to use raw pointers like you can in C (you have to enable unsafe code), so if you wanted to you could use the raw native GLFW almost exactly like you would in C. 

> Any caveats or pros and cons about the facts that might support one windowing + input system or the other?

Generally, using our own classes (`GameWindow` or `NativeWindow`) is easier and simpler to use for most users of the library and provides more idiomatic C# APIs. For most use cases they should be absolutely sufficient. Of course, in some advanced cases you may want to access the native functions instead (e.g. interop) so providing the raw native API directly is always a goal.

**Comment by LuisMerinoP** [comment]
Thanks for your comment.

> using our own classes is easier and simpler to use for most users of the library and provides more idiomatic C# APIs.
100% agreed. Classes are really simple an direct to the point. 

> so if you wanted to you could use the raw native GLFW almost exactly like you would in C.
That is what I though, but I cannot achieve it. Seems I am missing a step in creating an openGL context and loading the binidings. I tried to replicate what `NativeWindow` class code does in the `InitializeGlBindings`. (Seems it does what [glew](http://glew.sourceforge.net/basic.html) or [glad](https://github.com/Dav1dde/glad) does to have finally the opengl functions available).

This is what I tried so far:

```
class Program
  {
    private static void InitializeGlBindings()
    {
      // We don't put a hard dependency on OpenTK.Graphics here.
      // So we need to use reflection to initialize the GL bindings, so users don't have to.

      // Try to load OpenTK.Graphics assembly.
      Assembly assembly;
      try
      {
        assembly = Assembly.Load("OpenTK.Graphics");
      }
      catch
      {
        // Failed to load graphics, oh well.
        // Up to the user I guess?
        // TODO: Should we expose this load failure to the user better?
        return;
      }

      var provider = new GLFWBindingsContext();

      void LoadBindings(string typeNamespace)
      {
        var type = assembly.GetType($"OpenTK.Graphics.{typeNamespace}.GL");
        if (type == null)
        {
          return;
        }

        var load = type.GetMethod("LoadBindings");
        load?.Invoke(null, new object[] { provider });
      }

      LoadBindings("ES11");
      LoadBindings("ES20");
      LoadBindings("ES30");
      LoadBindings("OpenGL");
      LoadBindings("OpenGL4");
    }

    unsafe static void init(Window* window) {
      GLFW.WindowHint(WindowHintClientApi.ClientApi, ClientApi.OpenGlApi);
      GLFWGraphicsContext Context = new GLFWGraphicsContext(window);
      Context.MakeCurrent();
      InitializeGlBindings();

      GL.Enable(EnableCap.DepthTest);
      GL.Enable(EnableCap.ScissorTest);
      GL.Enable(EnableCap.Blend);
      GL.Enable(EnableCap.TextureCubeMapSeamless);
    }
    static unsafe void Main(string[] args)
    {
      GLFW.Init();
      Window* window = GLFW.CreateWindow(800, 800, "GLFW", null, null);
      GLFW.MakeContextCurrent(window);
      GLFW.WindowHint(WindowHintBool.Resizable, true);
      init(window);


      while (!GLFW.WindowShouldClose(window))
      {

        GL.Clear(ClearBufferMask.ColorBufferBit);
        GLFW.SwapBuffers(window);
        GLFW.PollEvents();
      }
    }     
  }
```
But cannot get it to work. Not a big deal, because I can use the `GameWindow` class working like a charm, but would be nice to have the chance of working directly with the GLFW api, in case there could be som functionality to explore
 or if it you get mad because just cannot make it work just like I got :)

thanks

**Comment by NogginBops** [comment]
I think it would be easier to just call the
```cs
OpenTK.Graphics.OpenGL4.GL.LoadBindings(IBindingsContext bindingsContext)
```
function directly instead of doing the reflection stuff.

**Comment by LuisMerinoP** [comment]
Thanks for the suggestion, that makes sense. Not sure how to work out the whole LoadBindings process.
I tried:

```
      IBindingsContext context = new GLFWBindingsContext();
      OpenTK.Graphics.OpenGL4.GL.LoadBindings(context);
```

But didnt work. 
On the other hand `OpenTK.Graphics.OpenGL4.GL.LoadBindings(IBindingsContext bindingsContext)` can be done in the last version (4.6.7) but not in the latest (5.0.0). The ``OpenTK.Graphics.OpenGL4` is not an available namespace.

**Comment by NogginBops** [comment]
OpenTK 5 is in pre-release and it changes some of the namespace names and how stuff gets loaded.
If you want a "stable" release use 4.6.7.

**Comment by LuisMerinoP** [comment]
Okay, I just got the default offered by the nuget package manager :)

**Comment by NogginBops** [comment]
Can you show the stack trace for the exception you are getting when using glfw?

**Comment by LuisMerinoP** [comment]
Just the app shows this exception: `System.InvalidOperationException: 'You need to initialize the OpenGL binding first by calling LoadBindings() or creating a compatible OpenGL window.'`  on the first GL function call

**Comment by LuisMerinoP** [comment]
[#869](https://github.com/opentk/opentk/issues/869) and [867](https://github.com/opentk/opentk/pull/867) seem very realted to this

**Comment by PJB3005** [comment]
In that code snippet you are initializing the bindings for the `OpenGL4` namespace but using the bindings from the `OpenGL` namespace. Change the `LoadBindings` line to simply `GL.LoadBindings(new GLFWBindingsContext());` and it should work.

**Comment by LuisMerinoP** [comment]
Yes that was the problem. Thanks a lot. Posting the working snippet in case this helps anyone:

```
using OpenTK.Graphics.OpenGL4;
using OpenTK.Windowing.GraphicsLibraryFramework;

class Program
{
    unsafe static void init()
    {
        GL.ClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        GL.Enable(EnableCap.DepthTest);
        GL.Enable(EnableCap.ScissorTest);
        GL.Enable(EnableCap.Blend);
        GL.Enable(EnableCap.TextureCubeMapSeamless);
    }
    static unsafe void Main(string[] args)
    {
        GLFW.Init();

        GLFW.WindowHint(WindowHintBool.Resizable, true);
        Window* window = GLFW.CreateWindow(800, 800, "GLFW", null, null);
        GLFW.MakeContextCurrent(window);
        GL.LoadBindings(new GLFWBindingsContext());
            
        init();

        while (!GLFW.WindowShouldClose(window))
        {

            GL.Clear(ClearBufferMask.ColorBufferBit);

            GLFW.SwapBuffers(window);
            GLFW.PollEvents();
        }
    }
}
```
