### ISSUE TITLE
Question:  NeoKabuto port to OpenTK 4?

### ISSUE THREAD

**Issue by mludlum** [opentk/opentk#1343]
### Description
I was thinking of porting the NeoKabuto OpenTKTutorial Samples to OpenTK 4.  Wanted to get feedback before taking this on.  
I use OpenTK in a Geo Positioning application that I converted from Manage DirectX 9.   I know enough to be dangerous.  My value here would be converting the projects over to .NET 5, OpenTK 4 and getting the code to compile and run.

1.  Does a port exist already?  Couldn't find it.
2.  Is it a good idea?   Would it be helpful?
3.  Any suggestions?

**Comment by NogginBops** [comment]
From what I could see of the NeoKebuto OpenTK tutorials they seem to be following some very old OpenTK tutorial/sample code which in turn uses deprecated OpenGL features.
My recommendation is not learning legacy OpenGL as it's very different than current OpenGL severely limits you in both performance and ability render nice graphics.

We have new tutorials available which do not use the deprecated features and instead follows along with https://learnopengl.com which is a great tutorial for modern OpneGL.


OpenTK website tutorial for OpenTK 3: https://opentk.net/learn/chapter1/0-opengl.html
LearnOpenTK tutorial for OpenTK 4: https://github.com/opentk/LearnOpenTK (there is a OpenTK 3 branch too).

I would recommend a combination of learnopengl.com the opentk website and the LearnOpenTK repo.

To answer your questions:
1. There is no port that I know of. But there are other more modern tutorials.
2. It might be a learning experience, but you would be learning legacy opengl. And I would consider teaching people legacy opengl as not helpful. But that might just be me.
3. See tutorial links above.

**Comment by mludlum** [comment]
I see your point and glad I asked.  I've seen the LearnOpenTK projects.  I'm using VAOs and VBOs in my own code.   Is that what you mean by modern OpenGL?   

I was looking at the neo tutorials because I need to pull in 3D models and animate them.  Tutorial 7 has that.  It would be nice if there were an example in LearnOpenTK.   I could attempt to convert the Tutorial 7 to the LearnOpenTK methods and submit a Pull Request to LearnOpenTK.    Ideally, I could use a framework for loading models from obj or fbx files, texturing and animating them.   Do you know of an example?

**Comment by NogginBops** [comment]
Loading 3d models is also something that https://learnopengl.com (and the OpenTK tutorials)  walk through. 
Animating them is a little harder if you are talking about something like skinned bone animations.
It could be nice to have a C#/OpenTK example/sample of how to setup that, but from what I could read on the NeoKabuto blog it doesn't seem Tutorial 7 covers animation.

**Comment by mludlum** [comment]
Can you  point me to the model loading example in OpenTK tutorials?   I'm not finding it.  I started translating the cpp code to C# from the learnopengl includes.

**Comment by NogginBops** [comment]
I thought that the OpenTK tutorials did some model loading stuff, but it seems like it doesn't. learnopengl.com does do some model loading in one of the tutorials.
You can use something like assimp to load your models or you can write your own .obj parser. None of which is super complicated.

**Comment by mludlum** [comment]
Yep, I thinking converting the LearnOpenGL examples that use assimp is the way to go.  Thanks.
