### ISSUE TITLE
Rendering or texture mapping differs between net31 and net5/net6

### ISSUE THREAD

**Issue by NoneGiven** [opentk/opentk#1345]
### Description

I can see this being a difficult issue to debug and it could even end up being a .NET bug. Because my project is a renderer for old Nintendo DS file formats, it uses compatibility mode for OpenGL 3.2 and a lot of deprecated immediate mode APIs. Please bear with me.

There are several apparent texture mapping bugs that manifest when I upgrade the project from .NET Core 3.1 to either .NET 5 or .NET 6. I tried multiple versions of OpenTK 4 and all of them reproduce the issues. I'm currently using 4.6.7.

Here's an example. Some parts of the texture have shifted around, and the eye (which is using mirrored repeat and a kind of decal rendering) is partially hidden behind the head. .NET Core 3.1 is on the left, .NET 6 on the right.

<a href="https://user-images.githubusercontent.com/2163967/141695111-b7bb2e88-acab-4b31-8039-a6d1f0ec33e7.png"><img src="https://user-images.githubusercontent.com/2163967/141695111-b7bb2e88-acab-4b31-8039-a6d1f0ec33e7.png" height="300" alt="bug-1-1"></a> <a href="https://user-images.githubusercontent.com/2163967/141695122-39134e1c-d694-4a6b-aca9-db424187b641.png"><img src="https://user-images.githubusercontent.com/2163967/141695122-39134e1c-d694-4a6b-aca9-db424187b641.png" height="300" alt="bug-1-2"></a>

I'm doing model rendering by compiling immediate mode calls with `GL.NewList`, and I verified that the commands I'm sending for this model are the same whether on net31 or net6, so whatever mysterious impact the .NET version switch is having, I'm fairly sure it's not on my code.

### Repro steps

Right now the steps to reproduce are just "run the whole project," which I can provide steps to do, but obviously isn't ideal as a repro. Let me know if you have any ideas what could be causing this, or if you need the steps or a separate/minimal repro to debug it.

### Related information 

* Windows 10

**Comment by PJB3005** [comment]
Have you checked with e.g. RenderDoc if you could spot what the difference is? I can't think of any changes in OpenTK that could cause a difference like this, assuming you're using the same GL calls. 

It may be a long shot but I recall that [.NET Core 3 changed the behavior of float parsing and such to be more consistent and IEEE-754 compliant](https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/). Is it possible this changed something?

**Comment by NogginBops** [comment]
Renderdoc probably won't work with immediate mode and fixed function pipeline stuff. But you might have better luck with something like nVidia nSight.

**Comment by NoneGiven** [comment]
I'll look into it when I get a chance.

**Comment by NoneGiven** [comment]
Finally looking into this again. I think the issue has to do with drawing non-planar quads with GL_QUADS. I'm going to confirm and try to make a minimal repro soon, but I wanted to check with you guys first how much this is even expected to work, or if it's undefined behavior due to triangulation or whatever.

Of course, even if it's UB, it seems extremely weird that changing the .NET runtime and nothing else would have an effect on it, and imo that makes it worth debugging.

**Comment by NoneGiven** [comment]
So, it is an issue caused by non-planar quads. If I manually triangulate and draw the polygon with GL_TRIANGLES, I get the same correct results on net5 and net6 as I do with GL_QUADS on net31.

However, the issue is not actually the .NET runtime -- it's the GPU. My dedicated graphics card was being used when I was running, the net31 executable, and the integrated graphics were being used when the running the net6 executable. Evidently the integrated makes bad decisions when triangulating quads. Switching to dedicated makes things look right on net6 while using GL_QUADS.

Closing as there's no bug in OpenTK.
