### ISSUE TITLE
5.0.0-pre.6 missing UniformMatrix2

### ISSUE THREAD

**Issue by ItsSammyM** [opentk/opentk#1352]
missing all GL.UniformMatrix2();

Windows 10
NuGet
.NET Framework
5.0.0-pre.6

**Comment by utkumaden** [comment]
As promised I'm here to deliver more information on this issue.

The following functions are missing overloads which take the OpenTK Matrix types as an input parameter by reference:
* `GL.UniformMatrix?f` (where `?` is any valid dimension.)
* `GL.UniformMatrix?x?f` (where both `?` are any valid dimensions)

Example signature:
```cs
void UniformMatrix2f(int location, bool transpose in float value) {}
void UniformMatrix2f(int location, bool transpose, ReadOnlySpan<float> value) {}
```

Conversely `GL.UniformMatrix?d` and `GL.UniformMatrix?x?d` are generated with only the matrix types as overloads (in case this isn't intended behaviour).

```cs
void UniformMatrix2d(int location, bool transpose, in Matrix2d value) {}
void UniformMatrix2d(int location, bool transpose, ReadOnlySpan<Matrix2d> value) {}
```

Affects OpenTK 5.0 prereleases, discovered on 5.0-pre.6

Possibly a generator or a specification XML bug.

Pinging @frederikja163 and @NogginBops as this might interest you.

**Comment by utkumaden** [comment]
I just realized this a duplicate of #1326 @NogginBops. Should I move the above comment to #1326 or keep it here?

**Comment by NogginBops** [comment]
It's fine to leave this as it is. Not that these issues are linked I can just close them both when i fix this issue :)
Unless @frederikja163 has time to take a look before I get to it?
