### ISSUE TITLE
"Learn" material is outdated >:|

### ISSUE THREAD

**Issue by KRC2000** [opentk/opentk#1353]
### Description

I guess some reorganisation happened, and now the guide is misleading.
For example at "Camera" guide, to control camera it says:

```
protected override void OnUpdateFrame(FrameEventArgs e)
{
    if (!Focused) // check to see if the window is focused
    {
        return;
    }

    KeyboardState input = Keyboard.GetState();

    //.......
}
```

Kill me but I can't find "Keyboard" class anywhere. 
Also window creating is messed up, something changed and now its impossible to follow steps.
### Repro steps

Just go to the https://opentk.net/learn/index.html and read that

### Expected behavior

Everything is up to date, to create a window it tells you to go to OpenTK.Windowing.Desktop not OpenTK.Graphics

### Actual behavior
Its like made for other library

### Related information 

* Operating system - Don't have one
* SDL or Native backend (if using OpenTK 3.x) - I don't even know
* What version of OpenTK (Installer, NuGet, Source Code) - One that you get when clicking "Download"
* What runtime (.NET Framework, CoreCLR, Mono) - what are those
* Workarounds (if any) - Looking for dumbass youtube videos

**Comment by NogginBops** [comment]
The website has a tutorial written for OpenTK 3 on it, and unfortunately that has not been updated to OpenTK 4.
However there is a repo that contains basically the same tutorial content but written in code and with comments updated for OpenTK 4 here: https://github.com/opentk/LearnOpenTK

I will look at adding a notice in the beginning of the tutorial linking to the OpenTK 4 tutorial to the website before we get the tutorial up to date.

**Comment by KRC2000** [comment]
Damn thats pretty cool, I mean its a shame that it exists but not that reachable. Anyway thanks for info!

**Comment by NogginBops** [comment]
Closing this as there is a link to the OpenTK 4 tutorials on the site now. Now we just got to get the tutorials ported over proper.
