### ISSUE TITLE
Suggestion: Add simple image loading library to opentk

### ISSUE THREAD

**Issue by JamesC01** [opentk/opentk#1354]
I'm not sure if this is out of the scope of what opentk wants to be, but I feel like it fits with the "toolkit" part of the name. In the learnopentk example, the pixel format of Bitmap.LockBits() doesn't match with the pixel format passed to TexImage2D.

LockBits() pixel format: 32bppArgb
TexImage2D pixel format: Bgra

Doesn't really mirror well. It would be nice if these things were more consistent. Maybe making an internal image loading library, even if it's just simple would be better.

Also, getting a pointer to the image data isn't hard, but isn't the most straightforward looking.

using (var image = new Bitmap(imagePath))
{
    var data = image.LockBits(...);
    var dataPointer = data.Scan0;
}

It would be nice if it worked more like stbi_load, which just directly passes back a pointer to the data. I think it would be a good choice to write a simple set of functions similar to stb_image for opentk. I'd add it in, but I know I'll end up doing it the wrong way, so I'd rather make a suggestion instead.

**Comment by daerogami** [comment]
Are we talking about OpenTK 3? Because OpenTK 4+ is no longer NET Framework (now its NET standard/Core/5+) so there is no `System.Drawing` library (closest replacement is a third-party library, [SixLabors.ImageSharp](https://github.com/SixLabors/ImageSharp))
Someone correct me if I'm wrong, I've been out of the loop for a bit.

**Comment by JamesC01** [comment]
@daerogami  https://www.nuget.org/packages/System.Drawing.Common

**Comment by ohtrobinson** [comment]
This is especially relevant now that they deprecated support for Linux. I think this is a great idea, but like you said, could be a bit out of scope of the project.

**Comment by daerogami** [comment]
I don't think System.Drawing.Common ever supported Unix. I thought it was akin to Windows Forms, enough people asked for it so it was ported over to .NET Standard with the caveat it would only ever function on Windows. I believe the intent moving forwards on OpenTK is to maintain cross-platform compatibility. ImageSharp could be a candidate though it has a different license and I can't recall what the stance here is on "Apache Licence 2.0".
I agree with the sentiment that the toolkit should be just that, a collection of utilities. IIRC, modularity was added in OpenTK 4 so it's feasible to add interfaces for image management and have a plugin that implements said interfaces with ImageSharp. Again, I've been out of the loop, so treat everything I say with a bit of skepticism.

**Comment by seanofw** [comment]
Rather than adding STB image functions to OpenTK, why not just use the library someone else already made that does _exactly_ that?  https://github.com/StbSharp/StbImageSharp

**Comment by NogginBops** [comment]
It's unfortunate that they decided to drop linux support for `System.Drawing.Common` in .net 6.
I think the best option atm is to use something like StbImageSharp. Performance leaves something to be desired but maybe they can take PRs.

**Comment by PJB3005** [comment]
I can't claim to have used it but TechnologicalPizza on the C# Discord mentioned their C# port of stb to me once. Might be worth evaluating: https://github.com/TechnologicalPizza/StbSharp.Image/

**Comment by ohtrobinson** [comment]
I've been using StbImageSharp that @NogginBops suggested in my engine and I see no performance issues, runs just as well as it did with system.drawing.

It's a good replacement, easy to use and for most uses I can see provides similar functions to bitmap. I've yet to try saving textures to a file but I believe it supports it(?)

**Comment by utkumaden** [comment]
Sorry to bump this thread this late, I think it could be fairly easy to provide the barest minimum PNG reader, but somebody would have to provide that, and I don't think anybody is interested in writing it at the moment. I think we would really need more hands on deck to maintain anything more than that. I'm open to the idea but I have my doubts it would come to fruition.

**Comment by seanofw** [comment]
PNG is a fairly large, complex metafile format, with a complex compression scheme, multiple interlacing algorithms, several color formats, lots of kinds of metadata, and some really weird corner cases (like the 64K limit for an `IDAT` chunk) within it — the published PNG textbook is over 300 pages long and doesn't even discuss how the Deflate algorithm works.  There are plenty of free libraries out there that support PNG just fine; we really shouldn't be spend our limited development resources implementing another one.

**Comment by utkumaden** [comment]
I really meant "bare minimum", just getting as the most common RGBA32 color space, deflate compressed PNG images. Implementing every single defined case is plenty of work. I know people in our very server who have implemented similar PNG decoders for their own projects, as they knew their requirements.

Unfortunately image decoding libraries have been a complete pain in the .NET core world, and since people can no longer trust that System.Drawing will work on other platforms, there is a very real need for a well written one in .NET. In the past people were recommending SixLabors ImageSharp, however their odd licensing policies, and the fact that the library is awfully slow has put people off.

I'm not saying we should spend our already constrained resources on rolling our own image decoder, as there are many many internal issues in the library that are higher priority, even after the 5.0 release. I think we should be on the lookout for people interested in developing such libraries and directly or indirectly support them, perhaps by convincing them to work under the OpenTK umbrella.

**Comment by daerogami** [comment]
I'm confused as to what is being requested here. Pulling in a NuGet package of `SixLabors.ImageSharp` or `StbImageSharp` should be sufficient. StbImageSharp is public domain, so there shouldn't be a licensing concern.

**Comment by seanofw** [comment]
To follow on what @daerogami said:  For performance, the `StbiSharp` library (not to be confused with `StbImageSharp`) is a wrapper around an actual compiled C DLL, so it runs as fast as the stbi decoder does (which is _fast_!).  So you have your pick of open-source liberally-licensed libraries for loading images and even saving images, and they're both quite capable:  I'm not sure why another library is really needed beyond them.

**Comment by NogginBops** [comment]
There is a tradeoff when taking on a dependency that itself has a native dependency. It increases the places where the library will break when run on weird stuff of weird configurations.

I would also like to make sure, we are talking about adding this as a dependency to the tutorials? And not to OpenTK proper?

I don't think OpenTK should ship it's own image decoder as that is a whole project in and of itself and OpenTK is already suffering from not enough maintainter time. Not saying it's entirely out of question but I think we have bigger issues that need to take priority (like merging OpenTK 4 PRs and getting OpenTK 5 ready, and then getting rid of GLFW).

**Comment by seanofw** [comment]
I agree that OpenTK should _not_ ship with an image library.  I suggested `StbiSharp` and `StbImageSharp` as good answers when people ask, "How do I load an image?"  And we could use them in the tutorials too to encourage that answer.

The tradeoff between the two is that `StbiSharp` is pure C with a C# wrapper, so it's less portable but it's super-fast; while `StbImageSharp` is a C# port of the STB image code, so it's not as fast, but it runs everywhere.  (It still uses C-style coding internally, with pointers inside `unsafe` blocks; it's a straight, automatic port of the original code, so it's not a _lot_ slower, but it's still not going to run as fast being JITed as a good optimizing C compiler would make it.)

The `StbImageSharp` team also ported some of the other libraries to C#, so if you need to _write_ images, they have an answer for that too.

With those libraries existing, I see zero reason to write or maintain our own.  They're both MIT-licensed, just like the STB code they rely on, so they're free to reuse anywhere for any reason.  I really think those should be our default answers when someone says, "How do I load an image?"

**Comment by NogginBops** [comment]
The website tutorials now use `StbImageSharp`, I will consider that good enough and close this issue now.
