### ISSUE TITLE
NativeWindow.CursorGrabbed and NativeWindow.CursorVisible behaviour should be separated

### ISSUE THREAD

**Issue by Visne** [opentk/opentk#1356]
### Description

Currently, setting `CursorGrabbed` to true will set `CursorVisible` to false, and setting `CursorVisible` to true will set `CursorGrabbed` to false. 
Meanwhile, setting `CursorGrabbed` to false does NOT set `CursorVisible` to true.

This means that these two properties are weirdly intertwined with illogical behaviour, and do more than the names would suggest.

My proposal is to completely separate these two properties, such that they actually do what their names suggest. This will also make it possible to have a visible cursor while the cursor is grabbed, which might be intended behaviour in some rare circumstances. 

### Related information 

* Operating system: Windows 10
* OpenTK Version: NuGet 5.0.0-pre.6
* Runtime: .NET 6

**Comment by ohtrobinson** [comment]
imo, I think just making it a singular property with an enum value is better,
something like: `CursorState = CursorState.Captured` etc..
GLFW (to my knowledge) only has three allowable cursor states, `Visible`, `Hidden`, and `Captured` (where the mouse is both hidden and locked to the window) and I think an enum could fit that perfectly (I use it in my own game engine and it works fine.)

**Comment by NogginBops** [comment]
Making it into an enum seems like the best option to me. I agree that the current setup doesn't make a lot of sense, and it would be a lot less confusing to have an enum that can bring to light this behavior.

**Comment by Visne** [comment]
That sounds like the best way then yeah.
