### ISSUE TITLE
Missing ArbShaderObjects enum

### ISSUE THREAD

**Issue by ghost** [opentk/opentk#136]
Hi
I just found something that missing on ArbShaderObjects Enumeration that used on GL.Arb.CreateShaderObject()

The missing enums are VertexShaderArb and FragmentShaderArb
but they are available in All Enum (All.VertexShaderArb and All.FragmentShaderArb)

I don't know if an explicit cast can solve the problem or not but currently i used this to resolve this problem (since i am haven't test the code yet, just trying to translating C++ code into C# language):
GL.Arb.CreateShaderObject((ArbShaderObjects)All.VertexShaderArb);

Thank you
Hope you can resolve this! :D

**Comment by daerogami** [comment]
Closed due to age.
