### ISSUE TITLE
OnUnload() isn't being invoked

### ISSUE THREAD

**Issue by adfcf** [opentk/opentk#1361]
### Description

OnUnload() from GameWindow is supposed to be executed after the game loop, and before OpenGL context being destroyed. It's not executed at all.

### Related information 

* Apparently, OnUnload() is invoked by Close(), which can only called by the user. I think it should be at the end of Run(), right after the game loop.

**Comment by NogginBops** [comment]
Thanks for the report! 
I must have fumbled this when I changed how the closing of windows worked.
Will have a fix for this in the next release.

I'm not sure if there are any "good" workarounds. You can call your own unload function directly after `gamewindow.Run()` returns and that should be basically the same thing.
