### ISSUE TITLE
How to request compatibility profile

### ISSUE THREAD

**Issue by JulianStambuk** [opentk/opentk#1362]
### Description

This is just a question. Is there any way to request a compatibility profile when creating a window with OpenTK 4.6.7?

Something like:
```cs
NativeWindowSettings windowSettings = new NativeWindowSettings();
windowSettings.Flags = ContextFlags.Compatibility;
```

### Related information 

I need to use `GL >= 4.x`, but don't want to dispense deprecated functionality like drawing with `PrimitiveType.Quads`. That means I have to request a compatibility profile which I dont see any way to do. Interestingly enough I seem to get a compatibility profile by default in OpenTK 3.1.0.

**Comment by NogginBops** [comment]
You set context profile via the `Profile` property of `NativeWindowSettings`.
In OpenTK 4 we default to a Core profile in an effort to reduce legacy API usage.
I would also urge you too to consider dropping deprecated functionality like quad primitives as they only really are more trouble than they are worth.

**Comment by JulianStambuk** [comment]
Thanks - I should have looked closer. Sure most deprecated functionality like all the legacy fixed function stuff should definitely be avoided, but I don't see whats wrong with rendering a screen quad instead of two triangles. Or doing a draw call without a VAO bound and instead fetching the data from like a SSBO. I even remember a case where rasterizing cubes using quads was noticeable faster than triangles.
