### ISSUE TITLE
OpenTK in Blazor (WebAssembly)

### ISSUE THREAD

**Issue by Daendel** [opentk/opentk#1364]
Hello. I was wondering if OpenTK can be used in Blazor (WebAssembly). I didn't find any information on it.
If so, how can I use it?
Thanks in advance!

**Comment by NogginBops** [comment]
You cannot currently use OpenTK on the client side when using Blazor as you would need to use webgl which we don't have bindings for. You could possibly setup the server to use OpenTK but that is likely not what you want to accomplish.

**Comment by daerogami** [comment]
Noting as related to #1355
