### ISSUE TITLE
(Question) Is there a way to go about automatic garbage collection for OpenGL objects?

### ISSUE THREAD

**Issue by wildniklin** [opentk/opentk#1368]
I've been trying to figure out how to **automatically garbage collect OpenGL handles/objects** using the **C# finalizer**, after doing so, my project kept giving me a cryptic error message; "`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`".

For a while, I had no luck while searching up the issue, there were a lot of unrelated results.
Fast forward 2-3 weeks later, finally, I found out that OpenGL only works on one thread, and not on one application.

It was quite unexpected, but now I see why the finalizer wasn't working, since GC was on a different thread than the main thread.

### Is there a way to go about automatic garbage collection for OpenGL objects?

I want to keep the frontend simple for any user to use, and not for them to call Dispose() manually all the time, my project involves a lot of multiple references (object trees, etc.), so it's difficult to manually keep track of what's referenced and what isn't.

```csharp
// Disposing

public void Dispose() {
    Dispose(true);
    GC.SuppressFinalize(this);
}

private bool disposed = false;
protected virtual void Dispose(bool disposing) {
    if(!disposed) {
        // Throws when Program object is collected...
        GL.DeleteProgram(ptr);

        disposed = true;
    }
}

~Program() => Dispose(false);
```

**Comment by NogginBops** [comment]
The finalizer in C# is run on the garbage collector thread, and calling OpenGL functions from a thread that does not have a current OpenGL context will cause all kinds of issues. 
A common way to fix this is to register the object for deletion in the finalizer and then deleting it on the main thread at the end of the frame.

My recommendation is to not rely on garbage collection though as the garbage collector has no concept of vram and cannot know when it needs to free objects that have most of their memory cost on the GPU, so the garbage collector will not do a great job at freeing the right objects at the right times.

Explicit control of these kind of resources is almost always going to result in better resource usage and better performance too.

**Comment by wildniklin** [comment]
> A common way to fix this is to register the object for deletion in the finalizer and then deleting it on the main thread at the end of the frame.

That could actually work...

Thank you for your help.

I will modify the behavior of the manual Dispose method to directly delete the handle, instead of wasting so much power on adding to the deletion list, so that there's availability for any user to choose.

###### I'll report back here if this doesn't work for some unknown reason.

**Comment by wildniklin** [comment]
Quick update: It works. This comment is probably completely unnecessary but I just want you to know that it works.
