### ISSUE TITLE
Running idle still costs 30-50% of cpu

### ISSUE THREAD

**Issue by villermen** [opentk/opentk#137]
I'm clueless as to why a GameWindow uses 30-50% of the CPU when it's just running (having created a simple project that just creates a gamewindow and runs it without parameters.). After doing a few profiler tests I've noticed that System.ni.dll takes up 20% of all the GameWindow.Run samples and another 20% inside of GameWindow.DispatchUpdateAndRenderFrame (64%). This is just findings, and might not have anything to do with it but I'm still curious as to what this is and why it's gobbling up so much CPU.

This relates to my 'Game Engine of sorts' having trouble running smoothly at 100 updates per second and using up to 100% of my 4th core while running idle. Again while profiling System.ni.dll and DispatchUpdateAnRenderFrame seem to be the bottlenecks (this leaves very little room for logic). Also ProcessEvents and especially readbit from keyboards seem to take way more cpu time than needed (but this might be a fault on my part).

Is there anything I am doing wrong here? (Do I not grasp how to use a GameWindow?) 

I am on Windows 8.1 64x (32-bit exe) with an i5 at 4x2.79GHz by the way, if that changes anything.

**Comment by Raptor2277** [comment]
I have the same issue, video link: https://www.youtube.com/watch?v=hJf3bTR0Zqo

**Comment by mellinoe** [comment]
@Raptor2277 Did you read the discussion above?

**Comment by Raptor2277** [comment]
@mellione Yes, I've tried all the things mentioned above. Still the same result.

**Comment by varon** [comment]
There was a LONG discussion of this in https://github.com/opentk/opentk/pull/472

While this may not be EXACTLY the same thing, I'd argue that it's essentially a non-issue.

Most games are going to want to run as fast as possible, and don't particularly mind about potentially maxing out one core.
If they really did care, they'd probably need to implement their own timing anyway, as concluded in #472, which would resolve this.
