### ISSUE TITLE
Add support for AL_SOFT_loop_points extension

### ISSUE THREAD

**Issue by ohtrobinson** [opentk/opentk#1372]
Currently, the OpenAL bindings are missing the ability to set sample loop points, which is an extension offered by OpenAL Soft.
The documentation is here: https://openal-soft.org/openal-extensions/SOFT_loop_points.txt

It would be a very useful feature to have, especially for looping music in games.

I am currently using OpenTK 4.6.7.

**Comment by NogginBops** [comment]
@ohtrobinson I opened a PR to fix this. It would be great if you could take a look and confirm that it would fix your issue :)
