### ISSUE TITLE
Vector structs are missing (vectorType / vector) and (vector / vector) operators

### ISSUE THREAD

**Issue by wildniklin** [opentk/opentk#1385]
In the vector structs, there are these division operators, but only for `vector / vectorType` or, say `Vector3 / float`, and not vice versa.
In all of the vector structs in mathematics, as far as I know.

Multiplication has `vector * vector`, `vector * vectorType`, and `vectorType * vector`. Component wise obviously.
I see no reason to not add this for division as well.

https://github.com/opentk/opentk/blob/0fb73c06650ad2bf9b06d100f7d5638aaa9c7405/src/OpenTK.Mathematics/Vector/Vector3.cs#L1490-L1503

And of course, don't forget the explicit operator methods.

OpenTK: NuGet 4.6.7 and again, missing on latest in master at github.

**Comment by NogginBops** [comment]
There are reasons for not providing `vector / vector` operations, but those reasons are mostly the same for `vector * vector` operations (namely that formal math doesn't have an element wise multiplication/division of two vectors).
We've had discussions about this before but I'm not sure what the latest discussion concluded with.
Personally I think this is something we should add as it's quite clear that `vector / vector` would be a component wise operation.

**Comment by wildniklin** [comment]
> Personally I think this is something we should add as it's quite clear that `vector / vector` would be a component wise operation.

Personally I think the same.

I've seen many people confuse the component-wise multiplication operator with dot product, but I think component wise operators would make more sense in programming, and keeping dot product as a separate method, as of like right now.

I've had lots of situations where I needed to divide a vector with a vector, so might as well just add it?

**Comment by utkumaden** [comment]
For reference next time, if you find an operator override missing, you can create an extension method in the meantime while we fix it, rather than doing it like that many many times.

E.G.
```cs
internal static class MissingOperators {
    internal static Vector4 DivideComponentWise(this Vector 4 a, Vector4 b)
    {
        return new Vector4(a.x / b.x, a.y / b.y, a.z / b.z, a.w / b.w);
    }
}
```

```cs
Vector4 a, b, c;
/* ... */

c = a.DivideComponentWise(b);
```

**Comment by NogginBops** [comment]
You don't even need an extension for this, `Vector3.Divide(Vector3, Vector3)` exists.

**Comment by wildniklin** [comment]
What about the one with the left hand side and right hand side flipped?

https://github.com/opentk/opentk/blob/fcb5dfa2a4686a8068c69b712026635adc4b047d/src/OpenTK.Mathematics/Vector/Vector3i.cs#L692-L706

This with flipped params but for multiplication exists.

https://github.com/opentk/opentk/blob/fcb5dfa2a4686a8068c69b712026635adc4b047d/src/OpenTK.Mathematics/Vector/Vector3i.cs#L663-L676

As we are very familiar with compound assignment operators, just doing this would work, unlike multiplication where order doesn't matter, so that one has compound assignment.

```csharp
public static Vector3i operator /(int scale, Vector3i vec) {
    vec.X = scale / vec.X;
    vec.Y = scale / vec.Y;
    vec.Z = scale / vec.Z;
    return vec;
}
```

In all of the vector structs of course. I just chose Vector3i randomly without a reason.

Thanks :)

**Comment by NogginBops** [comment]
Is there a real world use that justifies this?

**Comment by wildniklin** [comment]
Well, yes? Does it hurt to add a small feature that some developers will eventually use at some point?

```csharp
Vector3 inv = 1f / new Vector3(some value);
Vector3 mul = 2.52f * new Vector3(some value);
```

And since this exists for multiplication, I can't see any reason why this is a bad idea.

**Comment by NogginBops** [comment]
There is maintenance cost to adding operators, and adding something just cuz is not good motivation.
And in not sure if this is actually useful in any meaningful way.
