### ISSUE TITLE
Negative unit vectors?

### ISSUE THREAD

**Issue by wildniklin** [opentk/opentk#1386]
Currently, the vector structs have static unit vector fields, but only positive ones, so wouldn't it make sense to add negative ones as well?

I know that you could just do this: `-Vector3.UnitX`, but just filling in the small gaps would make the mathematics library a whole.

By any chance if this gets added, all I currently don't know is what it should be called, since UnitX doesn't have any syntax providing that it's positive or negative, and naming them UnitNX/NUnitX (N for negative) is honestly gross, so I have no idea.

Keep in mind that this is just a suggestion, it's not even that important.

Version: NuGet 4.6.7 and GitHub

**Comment by NogginBops** [comment]
`-Vector3.UnitX` is good enough.
For them to be added I would need to get a good reason for why and a need for them which doesn't exist.

**Comment by wildniklin** [comment]
Nevermind

**Comment by wildniklin** [comment]
Does `-Vector3.UnitX` (negate operation included) necessarily cost more than `Vector3.UnitNX` (negative preset), or does the compiler realize that it could be pre-calculated (it's not a `const`, it's a `static readonly`) before runtime?
