### ISSUE TITLE
No equivalent to glfwGetX11Display

### ISSUE THREAD

**Issue by 20kdc** [opentk/opentk#1396]
### Description

When using GLFW, a method, `GetX11Display`, required to setup a Vulkan surface on an X11 display using GLFW is not present.

### Repro steps

Look through GLFW documentation for `GetX11Display` or equivalent.

### Expected behavior

Such a method exists.

### Actual behavior

Such a method does not exist.

### Related information 

* Operating system: Linux
* GLFW
* Nuget (OpenTK 4.5.0 but appears to apply to Master)
* .NET Core
* Workaround: Manually add a DLL import for `glfwGetX11Display`

**Comment by NogginBops** [comment]
Must have forgotten to add this function when I added the native access functions. I can make a PR for this sometime in the coming days

**Comment by NogginBops** [comment]
@20kdc I've made a PR now!
https://github.com/opentk/opentk/pull/1397
