### ISSUE TITLE
OpenTK GL.VertexArrayAttribIFormat incorrect binding definition

### ISSUE THREAD

**Issue by oozierus** [opentk/opentk#1399]
### Description

GL.VertexArrayAttribIFormat expects incorrect type for parameter "type".
Now accepting: VertexAttribType
Should accept: VertexAttribIntegerType

### Repro steps

1. use GL.VertexArrayAttribIFormat in your code
2. pass variable of type VertexAttribIntegerType as "type" parameter
3. error:  Cannot resolve method 'VertexArrayAttribIFormat(int, int, int, OpenTK.Graphics.OpenGL4.VertexAttribIntegerType, int)', candidates are:
  void VertexArrayAttribIFormat(int, int, int, OpenTK.Graphics.OpenGL4.VertexAttribType, int) (in class GL)
  void VertexArrayAttribIFormat(uint, uint, int, OpenTK.Graphics.OpenGL4.VertexAttribType, uint) (in class GL)

### Expected behavior

Function GL.VertexArrayAttribIFormat should expect VertexAttribIntegerType as "type" parameter. As it is for GL.VertexAttribIFormat and GL.VertexAttribIPointer.

**Alternative: merge VertexAttribType and VertexAttribIntegerType into VertexAttribType. Binary values are the same.**

### Related information 
OpenTK version 4.7.1

**Comment by NogginBops** [comment]
Fixed with #1438
