### ISSUE TITLE
WindowBorder=Hidden while window is not visible causes it to never show up

### ISSUE THREAD

**Issue by NogginBops** [opentk/opentk#1405]
### Description

This is a bug in GLFW which can be tracked here: https://github.com/glfw/glfw/issues/2060

### Repro steps

Set `WindowBorder=Hidden` and `StartVisible=false` in `NativeWindowSettings` and try to show the window.

### Expected behavior

An window will appear with no window border.

### Actual behavior

The window appears in the tray, but will not be visible.

### Related information 

* Window 10 21h1
* OpenTK 4.7.1
* .NET 6

### Workarounds (if any)

Avoid setting `WindowBorder=Hidden` in `NativeWindowSettings` or before the window is visible. 
Setting `WindowBorder=Hidden` will work after the window is shown.

**Comment by qwerty1874** [comment]
Thanks so much, I can create no border window but I can't move it. What should I do?

**Comment by NogginBops** [comment]
@qwerty1874 this seems like a completely separate issue. If it's possible could you open a new issue?
