### ISSUE TITLE
JoystickState WasButtonPressed not working when window frequency is set

### ISSUE THREAD

**Issue by jorisdg** [opentk/opentk#1410]
### Description

Using OpenTK 4.7.1
When a window has an update frequency set, JoystickState.WasButtonDown and JoystickState.IsButtonDown are both true on the first frame a button is pressed. When a window has no frequency, it works as expected.

### Repro steps

Attached simple repro C# console program file. It's a CS file but had to rename to TXT to attach.
[Class1.txt](https://github.com/opentk/opentk/files/8367681/Class1.txt)

### Expected behavior

It is expected the first frame a button isbuttondown, the WasButtonDown is false.

### Actual behavior

When an update frequency is set, the wasbuttondown is always true when isbuttondown is true.
When no update frequency is set, it works as expected.

### Related information 

* Windows 11
* Native, OpenTK 4.7.1 from NuGet
* .NET 6

[Class1.txt](https://github.com/opentk/opentk/files/8367681/Class1.txt)

**Comment by NogginBops** [comment]
This is because `ProcessEvents()` is called as fast as possible in the loop that is waiting to call `OnUpdateFrame`, this causes the input to have been updated multiple times per frame which the current/previous logic doesn't handle.

**Comment by NogginBops** [comment]
This should be basically fixed with #1436. But #1430 for 4.7.3 (or possibly 4.8.0) is going to have a more thorough redesign of the internals of the input stuff so it should be the "proper" fix.
