### ISSUE TITLE
Ubuntu "No GLXFB Configs returned" Error When Creating A GameWindow

### ISSUE THREAD

**Issue by Nebula-Developer** [opentk/opentk#1411]
### Description

On my fresh Ubuntu machine, a simple GameWindow script appears to fail, returning:

    Unhandled exception. 
    OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: GLX: No 
    GLXFBConfigs returned
       at OpenTK.Windowing.Desktop.GLFWProvider.<>c. 
    <.cctor>b__5_0(ErrorCode errorCode, String description)

### Repro steps

Please provide the steps required to reproduce the problem

1. Dotnet Console Project
2. Default Native and GameWindow settings. (window.Run())

### Expected behavior

Should create a basic window - as usual..

### Actual behavior

Crashes when creating the window, rather than running it. (Return error above)
I think the issue is with the graphics? I tried updating my graphics, changing dotnet and opentk versions, but nothing seemed to work.

### Related information 

* Operating system - Ubuntu 20.04
* SDL or Native backend (if using OpenTK 3.x) - No
* What version of OpenTK (Installer, NuGet, Source Code) - (Dotnet Add Package) 4.7.1 OpenTK
* What runtime (.NET Framework, CoreCLR, Mono) - .NET Framework 6.0
* Workarounds (if any) - Could not find any.

GLXINFO Dump:
[glxinfo.txt](https://github.com/opentk/opentk/files/8378519/glxinfo.txt)

**Comment by utkumaden** [comment]
Please add the command line output of `glxinfo` to the issue as I asked in discord.

For example
```bash
glxinfo > glxinfo.txt
```
then upload `glxinfo.txt`.
If it is not installed, use `sudo apt install mesa-utils`

**Comment by Nebula-Developer** [comment]
Sorry about that, just updated it.

**Comment by Nebula-Developer** [comment]
Reinstalled Ubuntu, and somehow fixed itself. Went onto Arch in the meantime, and it was fine on there as well. Thanks for all the help.
