### ISSUE TITLE
[Question] Best approach for multiple windows

### ISSUE THREAD

**Issue by LuisMerinoP** [opentk/opentk#1415]
As imgui.Net's multiple viewport is not yet supported for opengl, a workaround is to have many `GLFW` windows to have for example the typicall game engine scene and game views, or just scenes with different cameras or whatever.
Checking the opetk's `GameWindow` this does not seam feasable, as the `Window.Run()` keeps the main thread "stucking" the code execution in the `Run()` like so:

```
static void Main() {
    Window wnd1 = new Window();  
    wnd1.Run(); //execution stuck here. On win1 close, keeps on and wnd2 opens  
    Window wnd2 = new Window();  
    wnd2.Run();
}
```
Thought of a new thread for the second window, but does not seem advisable. With `GLFW`, direct access to the update while loop and context forward to the window with `GLFW.MakeContextCurrent()` seems quite feasable, like so: 

```
using OpenTK.Graphics.OpenGL4;
using OpenTK.Windowing.GraphicsLibraryFramework;
using System;

class Program {
    static int newWidth = 0, newHeight = 0;

    static unsafe void Main(string[] args) {
        GLFW.Init();
        Window* window = GLFW.CreateWindow(800, 800, "GLFW", null, null);
        GLFW.MakeContextCurrent(window);
        GL.LoadBindings(new GLFWBindingsContext());
        GLFW.WindowHint(WindowHintBool.Resizable, true);
        GLFW.WindowHint(WindowHintClientApi.ClientApi, ClientApi.OpenGlApi);
        GLFW.MakeContextCurrent(window);
        GL.ClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        Window* window1 = GLFW.CreateWindow(800, 800, "GLFW", null, null);
        GLFW.MakeContextCurrent(window1);
        GL.ClearColor(0f, 1f, 0f, 1.0f);

        while (!GLFW.WindowShouldClose(window) && !GLFW.WindowShouldClose(window1)) {
            GLFW.MakeContextCurrent(window);
            GL.Clear(ClearBufferMask.ColorBufferBit);
            GLFW.SwapBuffers(window);
            GLFW.MakeContextCurrent(window1);
            GL.Clear(ClearBufferMask.ColorBufferBit);
            GLFW.SwapBuffers(window1);
            GLFW.PollEvents();
        }
    }
}
```

However this involves renouncing to the `GameWindow` API. Don's see how to run two windows and allocate the respective contexts. Was it never meant to be used for multiple windows? Any caveat/advice regarding how to handle multiple windows/viewports is appreciated.

**Comment by NogginBops** [comment]
Basically what you have to do is create you own loop where you do something like:
```cs
GameWindow win1 = ...;
GameWindow win2 = ...;

while (ShouldExit == false)
{
    win1.MakeCurrent();
    // render to win1
    win2.MakeCurrent();
    // render to win2
    // You only need to call this on one of the windows.
    // This is where the current api is the most broken.
    // You need to call ProcessEvents on every window to update it's input state
    // but ProcessEvents also calls glfwPollEvents() which means that it's going to trigger updates for all windows.
    // This means that there is currently no "correct" way for all windows to have correct input state
    win1.ProcessEvents();
}
```

A potential solution is to make the private `ProcessInputEvents()` method public and allow people to call it before calling glfws `PollEvents()`. 
Supporting multiple windows is something we want to support but we don't really have any dogfooding for that right now. I recently started to look at multiple imgui viewports with OpenTK and realized we really needed to do something about the api for multiple windows.

If you want a workaround you can always go for straight glfw like you say.

Another interesting idea would be to copy the source for `GameWindow` and modify it so that it's more suitable for multiple windows. That might even allow you to make a PR which the changes you felt where needed.

**Comment by LuisMerinoP** [comment]
Thanks a lot for such a fast and good answer. Back to you with some comments.

1.- // This means that there is currently no "correct" way for all windows to have correct input state
I think I do not get to understand this. As far as I understand that is one `ProcessEvents` method or `glfwPollEvents` method is global for all the windows, which will invoke all the callbacks for the occurred events/inputs for that frame. As long as that occurs for the respective windows isolatedly that is fine. I tried that out, and for example a `Console.WriteLine` log on space press accurs for the respective window having the focus, which is the desired behaviour. Guess that under the hood, the event takes place only in the window that has the focus so that is fine.
Moreover if this is a GLFW thing (meaning the gloabal `glfwPollEvents`), there would be no `GameWindow` modification/PR that could isolate the event/input callback invokation, as it is part of the GLFW core functioning. Is that correct?

2.- `IsExiting` is not working as I expect. I tried it in OpenTk version 4.6.7, and although it returns: `public unsafe bool IsExiting => GLFW.WindowShouldClose(WindowPtr);`, It is always returning false. If I do `GLFW.WindowShouldClose(WindowPtr);` it does work (actually is what used in the child `GameWindow`). Has nothing to do with the multiple window thing. This happens only with one unique window up to what I tried.

```
static unsafe void Main(string[] args) {
        GameWindow win1 = new GameWindow(GameWindowSettings.Default, new NativeWindowSettings() { Size = new Vector2i(1600, 900), APIVersion = new Version(4, 5) });
        win1.MakeCurrent();
        GL.ClearColor(0.2f, 0.3f, 0.3f, 1.0f);
        while (!GLFW.WindowShouldClose(win1.WindowPtr)) {
            win1.MakeCurrent();
            GL.Clear(ClearBufferMask.ColorBufferBit);
            win1.SwapBuffers();
            GL.Clear(ClearBufferMask.ColorBufferBit);

            win1.ProcessEvents();
            Console.WriteLine($"is win1 exiting: {win1.IsExiting}");
        }
        Console.WriteLine($"is win1 exiting: {win1.IsExiting}");
    }
```
`IsExiting` is always returning false. Either has another purpose or this might be a bug. I can open a separated issue for this if that ir helpful.

3.- Regarding Imgui, the multivieport feature makes it possible to have viewports out of the glfw window, so its a multi-window/vieport system on its own as as the imguis render viewports can be used to render graphics. It has examples for all the rendering apis + OS, so I think I would be very interesting to have that available. From a total lack of knowledge, if its as "easy" as achieving the glfw+opengl c# bindings from the original c++ library, It could worth giving that a try. If there is no interest in coupling the whole imgui stuff to opentk itself, could be of use to get only the windowing features on top of glfw for docking and viewports windowing functionality. Even if not of opentk itself, to have the viewport imgui feature be compatible with the imgui.net bindings (or other) would be massive.
Not experienced on that though so I find it a bit scary. Moreover I checked the imgui.Net repo & docs, and there seem to be difficulties in making the multiviewport feature work for openGL, however the c++ library does it so al the heavy lifting should already done by the c++ library and should come along with the c# bindings. If there is interest in this feature, its within reach for a non experience person in c# bindings to c++ libraries and maybe find some help here, I could give that a try.

Thanks for your comments

**Comment by NogginBops** [comment]
1. One call to `ProcessEvents()` will indeed process events for all windows, but for OpenTKs input system to work properly `ProcessInputEvents()` needs to be called on all windows before `glfwPollEvents()` is called.
The required order should be something like:
```cs
foreach (GameWindow window in Windows) window.ProcessInputEvents();
GLFW.ProcessEvents();
```
But the only api exposed currently is:
```cs
public void ProcessEvents()
{
    ProcessInputEvents();
    GLFW.PollEvents();
}
```
Which doesn't allow you to call `ProcessInputEvents()` without also calling `glfwPollEvents()`.

2. This is fixed in OpenTK 4.7.1, there where some issues with `IsExiting`. See #1338

3. We won't be including dear imgui into OpenTK, but I'm maintaining a imgui sample here where I've started some work on making mulitple viewports work.
Though It might be worth to look at just directly porting over the glfw+opengl backends into c#. Might be easier than reinventing the wheel.

**Comment by NogginBops** [comment]
@LuisMerinoP I've opened a PR here that does a quick fix for this issue. https://github.com/opentk/opentk/pull/1417

**Comment by LuisMerinoP** [comment]
thanks a lot for the support @NogginBops, I will give it a look and let you know shortly, when I find the time

**Comment by LuisMerinoP** [comment]
Checked that the PR was merged already! makes sense. Another option could be to keep a `private static NativeWindow[] window instances` variable in the class, updated in the constructor with all the instances created so that the `ProcessInputEvents` is done "automatically" for every window when `ProcessEvents` is called and `ProcessInputEvents` could be kept private. 
Anyhow making `ProcessInputEvents` public is a very direct and simple solution.
Thanks a lot.

**Comment by NogginBops** [comment]
I've not tested it to actually work with multiple windows, but it should work in theory.
If it turns out it doesn't work we'll do a more "proper" solution for this.
