### ISSUE TITLE
Update loop tries to make up even for hours of lost frames

### ISSUE THREAD

**Issue by DaKook** [opentk/opentk#1434]
### Description

When `UpdateFrequency` for a `GameWindow` is set to > 0, the update loop will try to make up for lost frames. This makes sense... when it's only a few frames. But if several frames are lost, say, hours of frames, it could end up trying to catch up for minutes. It would make sense to have a way to turn this off, or to make it only do so if it's less than a specified number of frames.

### Repro steps

Reproduction is easy:
1. Create an instance of the `GameWindow` class, with `UpdateFrequency` set to > 0 (say, 60).
2. Add an `EventHandler` for `UpdateFrame`, and write some code so that you can see how fast it is running.
3. Run the `GameWindow`, and while it is running at the specified FPS, insert a breakpoint (or otherwise stop the update loop; say, put your computer to sleep)
4. Wait a while, then resume the application.

### Expected behavior

The `GameWindow` should continue running normally, at the specified FPS.

### Actual behavior

The `GameWindow` will have unlimited update frequency until it catches up, then will resume with the specified `UpdateFrequency`.

### Related information 

* Operating system: Windows 11
* OpenTK version: 4.6.7 (installed via NuGet Package Manager)
* Runtime: .Net Core 3.1
* Workarounds: Alternative run loop by seanofw: https://gist.github.com/seanofw/49648280ce4618acd5b908fe0f6c3575

**Comment by NogginBops** [comment]
This is now fixed with #1435
