### ISSUE TITLE
No Overload for Vector3i in GL.ProgramUniform2-4 or GL.Uniform2-4

### ISSUE THREAD

**Issue by jklw10** [opentk/opentk#1444]
### Description

No overload for int vector 2-4 in gl.ProgramUniform2-4().
using separate integers works but trying to shove a Vector3i in just auto casts it and causes errors.

### Repro steps

try to write to a shaders ivec3 with GL.ProgramUniform3() while using a Vector3I as input.
it will cast to Vector3 and fail.

### Expected behavior

Having an overload for vector2i, vector3i and vector4i (and doubles)

### Actual behavior

there is only one with separated integers, doubles or halves.

### Related information 

* What runtime (.NET Framework, CoreCLR, Mono)
.net6
* Workarounds (if any)
Have to use the separated int,double,half x,y,z,w overload to be able to access integer uniforms.

**Comment by NogginBops** [comment]
This is a duplicate of #1240
