### ISSUE TITLE
EnqueueReadBuffer<T>() uses sizeof(float) not sizeof(T)

### ISSUE THREAD

**Issue by Ed-Silver** [opentk/opentk#1453]
### Description

EnqueueReadBuffer<T>() is hard coded to use the sizeof(float) to calculate buffer length, not the sizeof(T) that could be anything eg: a byte array.

### Repro steps

Use EnqueueReadBuffer with something that isn't a float array (where sizeof(T) != sizeof(float))

### Expected behavior

Should correctly calculate the size of the buffer for any type T.

### Actual behavior

Only correctly calculates size when T is type float.

### Related information 

* Operating system: Windows 10
* What version of OpenTK: NuGet
* What runtime :.NET Framework
* Workarounds: copy the function but use sizeof(T), use that instead.

**Comment by NogginBops** [comment]
I see the bug in the code.
https://github.com/opentk/opentk/blob/082c8d228d0def042b11424ac002776432f44f47/src/OpenTK.Compute/OpenCL/CL.cs#L1041-L1054

What version of OpenTK is this? You're saying you are using .Net Framework but I can't find that this bug in the OpenTK 3 source, it's only present in the OpenTK 4 source.
