### ISSUE TITLE
GLFW WindowHintBool.MousePassthrough Invalid

### ISSUE THREAD

**Issue by MarioGK** [opentk/opentk#1463]
### Repro steps

```
GLFW.WindowHint(WindowHintBool.Decorated,false);
GLFW.WindowHint(WindowHintBool.MousePassthrough,true);
```

Gives `GLFW Error(InvalidEnum): Invalid window hint 0x0002000D` error

### Related information 

* Windows 11
* OpenTK.Windowing.GraphicsLibraryFramework 4.7.4
* OpenTK 4.7.4
* .NET 7 Preview

**Comment by NogginBops** [comment]
This is a feature introduced in GLFW 3.4, which is not yet released. OpenTK 4.7.4 has GLFW bindings for GLFW 3.3.7 which is the latest stable release. It's possible that I could maybe publish a preview package for the `OpenTK.glfw.redist` nuget package that could be used to get access to some version of GLFW 3.4, but I'm not sure how easy that is to create with our current setup for creating those packages.
