### ISSUE TITLE
Can not set value in GLSL if that value doen't calculated in main function.

### ISSUE THREAD

**Issue by MingGuys** [opentk/opentk#1464]
### Description
Look at this simple GLSL file
`#version 330 core

layout(location = 0) in vec3 aPosition;

layout(location = 1) in vec2 aTexCoord;

out vec2 texCoord;

uniform mat4 model;
uniform mat4 view;
uniform mat4 projection;
uniform float TEST;
void main(void)
{
    texCoord = aTexCoord;

    gl_Position = vec4(aPosition, 1.0) * model * view * projection;
}`
I can set variable model,view,projection success!But when I set TEST variable with float value,This will fail.Because key "TEST" is not present.
All keys in GLSL file are founded by this code

`GL.GetProgram(Handle, GetProgramParameterName.ActiveUniforms, out var numberOfUniforms);`

I was wondering.Why restrict to set variable if this variable is not present in main function?
I think even if variable is not present in main,I can still set this parameter value .

My system info is here:
Windows 10
Visual studio 2022
OpenTK  4.7.1

**Comment by NogginBops** [comment]
This is something every drivers shader compiler does. They aggressively optimize your shader. On the GPU the less memory your shader needs the more of them you can run at the same time, so keeping unused variables around could affect performance negatively.

This isn't really a problem in the api as passing a location of `-1` to functions like `glUniform*` will be ignored completely.

**Comment by MingGuys** [comment]
> This is something every drivers shader compiler does. They aggressively optimize your shader. On the GPU the less memory your shader needs the more of them you can run at the same time, so keeping unused variables around could affect performance negatively.
> 
> This isn't really a problem in the api as passing a location of `-1` to functions like `glUniform*` will be ignored completely.

Thanks.Very clean and clear!This behavior cause some problems when debugging some code.If anyone is wondering like me.Now ,They won't!
