### ISSUE TITLE
I have some questions in learning OPENTK

### ISSUE THREAD

**Issue by qwerty1874** [opentk/opentk#1480]
### Description

I have some questions in learning OPENTK.Textures

### Questions 

1. I noticed in function `OnRenderFrame`, the three functions `GL.BindVertexArray(_vertexArrayObject)`, `_texture.Use(TextureUnit.Texture0)` and `_shader.Use()`, I've tried removing them and it doesn't seem to make a difference, so can I consider them unnecessary?

2. Regarding the enum 'TextureUnit' there are only 'Texture0' to 'Texture31', does this mean that in total only 32 textures can be rendered per frame?

3. How to use a transparent texture, because now it's black.

**Comment by NogginBops** [comment]
1. No the are not unnecessary, if you have more than one vao, texture, or shader these calls are the ones that bind them for use in the next draw call. The tutorials go through this.
2. The OpenGL standard only guarantees 32 texture slots (maybe only 16 in some older versions, but I'm not sure), but the driver will tell you how many it supports if you call `GL.GetInteger` with the right enum (look at the documentation to find it).
3. You need to enable blending, which you can learn about here https://learnopengl.com/Advanced-OpenGL/Blending
 Transparency in 3d graphics is a surprisingly hard/complicated task, so beware. But if you are only blending 2d textures it's probably fine.
