### ISSUE TITLE
Missing source files in OpenTK 3.x branch

### ISSUE THREAD

**Issue by Michael-5430** [opentk/opentk#1482]
### Description

Cannot compile the version 3.3.2 of OpenTK because of missing source files.

### Repro steps

1. git clone https://github.com/opentk/opentk.git
2. git checkout 3.x
3. open OpenTK.sln with Visual Studio
4. build project OpenTK => failed

### Expected behavior

build project OpenTK should succeed.

### Actual behavior

build project OpenTK failed with messages "Source file '*' not found." for
OpenTK\Properties\AssemblyInfo.cs
OpenTK\Graphics\OpenGL\GLEnums.cs
OpenTK\Graphics\OpenGL\GL.cs
OpenTK\Graphics\ES20\ES20.cs
OpenTK\Graphics\ES20\ES20Enums.cs
OpenTK\Graphics\ES11\ES11.cs
OpenTK\Graphics\ES11\ES11Enums.cs
OpenTK\Graphics\OpenGL4\GL4.cs
OpenTK\Graphics\OpenGL4\GL4Enums.cs

### Related information 

* Windows 10
* OpenTK 3.x source code (Commit 4f524c13)
* .NET Framework 4.8

**Comment by NogginBops** [comment]
You have to run `build.cmd` or `build.sh` once for the build inside visual studio to work.

You can look inside these scripts if you want to find out the steps they do if you do them individually. Though most work is done in a F# script, which might be hard to read if you aren't used to it.

**Comment by Michael-5430** [comment]
Thank you for the fast response, @NogginBops.
After checking out the source again I could run the `build.cmd` successfully.
