### ISSUE TITLE
Is a VB (on .NET 6+) welcome here or do I just simply "back away"?

### ISSUE THREAD

**Issue by DualBrain** [opentk/opentk#1484]
### Description

Noticed a statement in the FAQ that is answered with... 

"OpenTK is an OpenGL/CL/AL library for managed .NET languages like C# and F#. You can use OpenTK with managed C++ (i.e., C++/CLI), but you neither need it nor likely want it for plain C++."

A mention of C# and F#.

I also noticed that "C# pointers" will be leveraged in the future, will this impact languages outside of C#, or is OpenTK going to become a C# only project.

I also did a cursory exploration of some older *Issues* and there was at least one (https://github.com/opentk/opentk/issues/1054) that flat out states: "VB is unsupported." Is this truly the official stance or is there simply no one willing to put in the effort / contribute?

I'm sorry if this comes across a somewhat controversial, but as I see it right now, the behavior toward a VB dev seems very negative with the initial review and puts me in a position to have to question whether or not it's worth the time to invest so I'm testing the waters to see if this indeed the case or is there a desire to have support but lacking individuals to help?  I'll add, it does seem odd that the project that used to exist that now points to this as the successor *DID* welcome/support such.

### Repro steps

N/A

### Expected behavior

I'd expect a .NET library to work with, I don't know, .NET regardless of language choice.

### Actual behavior

Seems to be a question regarding whether this is the case; before I spend too much time digging in, like to get a lay of the land.  If a VB dev and their contributions aren't welcome, I can simply move along.  However, if that isn't the case, then...

### Related information 

N/A

**Comment by NogginBops** [comment]
Sorry for the late response!

C# function pointers will not be part of the public API for OpenTK so it will continue to work with Visual Basic.

Both OpenTK 3 and OpenTK 4 should work with VB (if VB even runs on .net 5+?). We have some people in the discord actively using Visual Basic (for whatever reason they have).

Generally this is a "C# first" kind of library as this is what most consumers are using. But if there are simple things we can do to make it easier to use in other CLR languages (F#, VB) then why not.
If we would be required to make substantial changes to be able to work with VB we probably wouldn't, but great news is that OpenTK should already work with VB.

Give it a shot and see how it goes. If you encounter any issues you can open an issue here or come and talk to us about it on discord.

**Comment by DualBrain** [comment]
Good to hear, I'll be happy to add it to the list of similar frameworks to experiment with (exploration at this point).

Thanks.
