### ISSUE TITLE
EGL bindings missing

### ISSUE THREAD

**Issue by jgcodes2020** [opentk/opentk#1485]
### Description
Previous versions of OpenTK provided a namespace `OpenTK.Platform.Egl` which in turn provided the `Egl` binding class for EGL.
The current versions do not.

### Related information 

* Operating system: Linux
* SDL or Native backend (if using OpenTK 3.x)
* What version of OpenTK: NuGet, 4.7.4
* What runtime: .NET 
* Workarounds: Roll my own bindings to libEGL.so

**Comment by NogginBops** [comment]
Should be possible to do something similar as what was done with the WGL bindings here: https://github.com/opentk/opentk/commit/ae05f9c354817c80361850ab0e32720bf0908c47
