### ISSUE TITLE
MathHelper.NormalizeRadians() returns angles out of the stated range

### ISSUE THREAD

**Issue by FlashX64** [opentk/opentk#1486]
### Description

`MathHelper.NormalizeRadians()` differs from the behavior of `MathHelper.NormalizeAngle()` and actually returns incorrect results.

### Expected behavior

The method should never return an angle less than -Pi.
I suppose [there](https://github.com/opentk/opentk/blob/f115f53a0f4900e17c456d12b5cf1e5e0272ba40/src/OpenTK.Mathematics/MathHelper.cs#L1220) should be just `Pi` instead of `PiOver2`.

### Actual behavior

The method returns an angle less than -Pi for inputs in the range (Pi/2, Pi].

**Comment by NogginBops** [comment]
I'm guessing this relates to OpenTK 4?

**Comment by NogginBops** [comment]
Yeah looking at the code it's definitely not correct.
If you want to give making a PR a shot that's fine with me, otherwise I can fix this at some point before 4.7.5

**Comment by FlashX64** [comment]
> I'm guessing this relates to OpenTK 4?

It relates to OpenTK 5 as well.

**Comment by NogginBops** [comment]
Any fixed to OpenTK 4 will eventually get ported to OpenTK 5 also.
