### ISSUE TITLE
Missing equivalent enum for 'GL_PROGRAM_BINARY_LENGTH'.

### ISSUE THREAD

**Issue by Kneesnap** [opentk/opentk#1498]
### Description

There is no OpenTK equivalent of 'GL_PROGRAM_BINARY_LENGTH'
This makes using glGetProgramBinary difficult as the length of the program cannot be determined with glGetProgram.

OpenTK Version: v4.7.4

### Repro steps

N/A

### Expected behavior

I expect to see an enum equivalent for 'GL_PROGRAM_BINARY_LENGTH' in the 'OpenTK.Graphics.OpenGL.GetProgramParameterName' enum.

### Actual behavior

I do not see any such enum.

### Related information 

* Operating system: Windows 10
* SDL or Native backend (if using OpenTK 3.x) N/A
* What version of OpenTK (Installer, NuGet, Source Code)
* What runtime (.NET Framework, CoreCLR, Mono) .NET Core 5.0
* Workarounds (if any) N/A

**Comment by NogginBops** [comment]
As a workaround you can find the enum in the `All` enum, and then cast that to the `GetProgramParameterName` enum.
