### ISSUE TITLE
Matrix4.CreateFromQuaternion don't work correctly

### ISSUE THREAD

**Issue by Paulius0706** [opentk/opentk#1526]
### Description

Matrix4.CreateFromQuaternion(Quaternion quaternion) don't work correctly. This always trys to go to near 0 radians and completly stops rotation. Matrix4 RotationX RotationY RotationZ combination works correctly.

### Repro steps

1. Define how we rotate mesh in mesh class
```csharp
public void UpdateRender()
{
    if (this.position == this.lastPosition && this.rotation == this.lastRotation && this.scale == this.lastScale) return;
    this.lastPosition = new Vector3(this.position);
    this.lastRotation = new Quaternion(this.lastRotation.Xyz);
    this.lastScale = new Vector3(this.scale);
    Matrix4 transform =
        Matrix4.CreateScale(this.scale)
        * Matrix4.CreateFromQuaternion(this.rotation) // RotationX RotationY RotationZ combination works correctly
        * Matrix4.CreateTranslation(this.position);
    for (int i = 0; i < this.vertices.Length; i++)
    {
        buffer[i].Position = new Vector3(new Vector4(this.vertices[i], 1) * transform);
    }
    this.vertexBuffer.SetData(buffer, buffer.Length);
}
```
2. OnLoad() create specific mesh
```csharp
this.meshes = new List<Mesh>();
meshes.Add(new BoxMesh(new Vector3(0, 0, 0.5f), new  Vector3(0.5f,0.5f,1f), new Quaternion(0,MathHelper.DegreesToRadians(45f),0) ) );
meshes.Add(new QuadMesh(new Vector3(1, 1, 0),new Vector3(10,10,10)));
// instantiate create shader and uniforms for camera
```
3. OnUpdateFrame() add rotation to specific mesh
```csharp
meshes[0].rotation.Z += MathHelper.DegreesToRadians(180f * ((float)e.Time));
// update camera and its movement
```
5. OnRenderFrame() Update and render mesh
```csharp
foreach (Mesh mesh in this.meshes) { mesh.UpdateRender(); }
// do depthControl clearBuffer and shader stuff 
foreach (Mesh mesh in this.meshes) { mesh.Render(); } //do all drawing
```

### Expected behavior

Object on screen shoud rotate 360 degrees in z axis every 2s and it don't change Y rotation

### Actual behavior

Object periodicly slowing down rotation to 180 degrees and stops. Y rotation straightens out. 
Picture shows semifinal state and Z rotation in degress

### Related information 

* Operating system Windows10
* What version of OpenTK: NuGet 4.7.5
* What runtime: NET Framework
* Workarounds (if any)

![sasd](https://user-images.githubusercontent.com/79274503/197516664-240f1a81-2ee5-4b12-a441-192ae12695c8.png)

**Comment by NogginBops** [comment]
I've edited the issue to have the code formatted correctly.

**Comment by NogginBops** [comment]
You are misunderstanding how quaternions are used, you are using them as if they represent XYZ angles when they don't.
So operations like:
```csharp
this.lastRotation = new Quaternion(this.lastRotation.Xyz);

meshes[0].rotation.Z += MathHelper.DegreesToRadians(180f * ((float)e.Time));
```
make no sense.

You almost never want to modify the components of a quaternion by themselves (you are almost always going to get a non-normal quaternion which you don't want).
Instead you want to make your "base" operation multiplication of quaternions.

So I would do this instead of what you are doing above:
```csharp
// you also have a bug here, lastRotation = lastRotation
// this.lastRotation = new Quaternion(this.lastRotation.Xyz);
this.lastRotation = this.Rotation;

meshes[0].rotation *= Quaternion.FromAxisAngle(Vector3.Y, MathHelper.DegreesToRadians(180f * ((float)e.Time)));
```

**Comment by NogginBops** [comment]
Not related to this issue in particular. It seems like you are modifying vertex data in C# and uploading it to the GPU every frame, this is likely something you don't want to do. This is much better done in a vertex shader.

You can read our OpenGL tutorial here: https://opentk.net/learn/chapter1/2-hello-triangle.html?tabs=onload-opentk4%2Conrender-opentk4%2Cresize-opentk4

**Comment by Paulius0706** [comment]
you ment to say that 
1. matrix operations shoud be performed in shader and send only matrixes ?
2. matrix shoud be created in shader from given additional variables (like objectPosition rotation and scale) in shader?
3. that C# buffer array in code is being referenced by shader buffer and only need to set once?
4. need some kind guard so when change dont exist from last render frame, dont modify data?

**Comment by NogginBops** [comment]
> Do you ment to say that:
> 
> 1. matrix operations shoud be performed in shader and send only matrixes ?

Yes and no, you might want to construct the full model view projection matrix on the CPU and then do the `position * matrix` part in the vertex shader.

> 2. matrix shoud be created in shader from given additional variables (like objectPosition rotation and scale) in shader?

No, create your matrices like you are doing on the CPU.
> 3. that C# buffer array in code is being referenced by shader buffer and only need to set once?

Not 100% sure of what you are saying here, but my guess is, yes? 
Normally you upload your model data to the GPU once and transform it using the vertex shader.
> 4. need some kind guard so when change dont exist from last render frame, dont modify data?

I don't understand this question. 
But generally, don't modify vertex data on the CPU (especially if you are just transforming a mesh), and when using a vertex shader all of your transformations are going to be applied every frame (this is not a problem, this is what GPUs are meant to do).

**Comment by Paulius0706** [comment]
thanks
