### ISSUE TITLE
Build Can't Find NET6

### ISSUE THREAD

**Issue by Jillinger** [opentk/opentk#1527]
### Description

I believe this is a test run

> **_dotnet fake run build.fsx_** 

executed after running 'build.cmd'.
However, it results in an error
> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.25'.

### Repro steps

I followed [these steps](https://github.com/opentk/opentk).

```
git clone https://github.com/opentk/opentk   # Download source code from git
cd opentk                                    # Enter the source directory
./build.cmd / ./build.sh                     # Run the bootstrap/build script for your platform
```

### Expected behavior

Shouldn't dotnet version 6.0 be used instead of 2.1?

### Actual behavior

The files are located in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1 to 6.0
but they are being looked for in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.25 where these files are missing, but there is a json file - Microsoft.NETCore.App.deps.json.
Is that file used to install the dependencies? Should I do that, amd how?

### Related information 

I'm using a Windows OS, and I think the OpenTK version may be 3.3.3. Not sure.
I think I may no longer have .net 2.1, since 6.0 is the latest version being used, and 2.1 is no longer supported.

There must be a solution to the problem, I'm sure.
What that is, I would like to know.

**Comment by NogginBops** [comment]
The different projects in OpenTK target `netstandard2.1` and `netcoreapp3.1`, so if you don't have the tooling to build projects targeting these frameworks the build will likely fail.

If you want to compile OpenTK for your own needs you can update all of the csproj files to target `net6.0` instead.

If installing the correct framework or changing the target framework doesn't work, then it might be a more involved issue.

**Comment by Jillinger** [comment]
> If you want to compile OpenTK for your own needs you can update all of the csproj files to target `net6.0` instead.

Thanks..
Would that mean opening the projects in Visual Studio, and configuring the properties there, or is there another way?

**Comment by NogginBops** [comment]
That is one way, you could also open all of the `.csproj` files in any editor and change the target framework there.

**Comment by Jillinger** [comment]
> That is one way, you could also open all of the `.csproj` files in any editor and change the target framework there.

Thanks.
