### ISSUE TITLE
Problem with rendering Triangles from VertexPointer

### ISSUE THREAD

**Issue by alexzupo** [opentk/opentk#1530]
### Description

Hi, i have memory pointer to vertex array and Color array, with this pointer i'm able to draw all points all lines correctly. But if want to draw a triangles nothing appear.

The code for rendering is that:

           **'This display all vertex points Perfects**
            GL.VertexPointer(3, VertexPointerType.Float, Vector3.SizeInBytes, puntatore_vertici_STL.AddrOfPinnedObject)
            GL.ColorPointer(4, ColorPointerType.UnsignedByte, 4, puntatore_colori_STL.AddrOfPinnedObject)
            GL.DrawArrays(PrimitiveType.Points, 0, STL.Count * 3)
            GL.DisableClientState(ArrayCap.ColorArray)
            GL.DisableClientState(ArrayCap.VertexArray)

          **'This display all vertex lines Perfects**
            GL.VertexPointer(3, VertexPointerType.Float, Vector3.SizeInBytes, puntatore_vertici_STL.AddrOfPinnedObject)
            GL.ColorPointer(4, ColorPointerType.UnsignedByte, 4, puntatore_colori_STL.AddrOfPinnedObject)
            GL.DrawArrays(PrimitiveType.Lines, 0, STL.Count * 3)
            GL.DisableClientState(ArrayCap.ColorArray)
            GL.DisableClientState(ArrayCap.VertexArray)

          **'This DON'T function , nothing appear**
            GL.VertexPointer(3, VertexPointerType.Float, Vector3.SizeInBytes, puntatore_vertici_STL.AddrOfPinnedObject)
            GL.ColorPointer(4, ColorPointerType.UnsignedByte, 4, puntatore_colori_STL.AddrOfPinnedObject)
            GL.DrawArrays(PrimitiveType.Triangles, 0, STL.Count)
            GL.DisableClientState(ArrayCap.ColorArray)
            GL.DisableClientState(ArrayCap.VertexArray)

I don't understan why.....

**Comment by alexzupo** [comment]
1) I'm using a v3.3.3 , the code running in Visual Basics.
2) I don't understand where change "Profile = Compatibility in the NativeWindowSettings."
3) What functions you mean old or obsolete, you can specify exactly??

**Comment by NogginBops** [comment]
> I'm using a v3.3.3 , the code running in Visual Basics.

> I don't understand where change "Profile = Compatibility in the NativeWindowSettings."

I assumed you where using OpenTK 4, so the settings I was referring to isn't the same in OpenTK 3. In OpenTK 3 you get a compatibility context if you don't specify `GraphicsContextFlags.ForwardCompatible` in the `GameWindow` constructor.

> What functions you mean old or obsolete, you can specify exactly??

`glVertexPointer`, `glColorPointer`, and `glDisableClientState` are all deprecated functions in modern OpenGL.

**Comment by NogginBops** [comment]
Closing this as I don't think there is much more to say. But feel free to reopen if that is not the case.
