### ISSUE TITLE
Support for TransparentFramebuffer and many other WindowAttribs missing

### ISSUE THREAD

**Issue by KingRikkie** [opentk/opentk#1536]
### Description

NativeWindow seems very limited in terms of windowing hints, TransparentFramebuffer is missing entirely, as well as many other ones. 

### Expected behavior

`GLFW.SetWindowAttrib(wPtr, 0x0002000A, true)` should work in the GLFW intended way.

### Actual behavior

Calling `GLFW.WindowHint(WindowHintBool.TransparentFramebuffer, true)` before the NativeWindow has been initialized does not work, fair enough as it is probably being overruled by the Constructor of NativeWindow somewhere. However calling `GLFW.SetWindowAttrib()` does apparently not support TransparentFrameBuffer at all, in fact only a very few of the numerous WindowAttribs are available. Calling `GLFW.SetWindowAttrib(wPtr, (WindowAttribute)WindowHintBool.TransparentFramebuffer, true);` breaks the application, even though GLFW should support this natively.

### Possible Fix

Instead of the narrow `WindowAttribute`, `GLFW.SetWindowAttrib()` should take a regular `WindowHintBool`.

### Related information 

* Manjaro Kernel 6
* OpenGL 4.6
* .NET 7

**Comment by NogginBops** [comment]
Do you have any more examples of missing window hints? Which ones are most important to you?

You could potentially try calling `GLFW.SetWindowAttrib(gameWindow.WindowPtr, ...)` in `OnLoad` (while the window is hidden), depending on when the hints needs to be called.

**Comment by NogginBops** [comment]
I've just opened a PR that will be merged with 4.7.6. If you have any more options that you feel are missing feel free to comment here or in the PR.
