### ISSUE TITLE
Unable to get build.cmd to work

### ISSUE THREAD

**Issue by aybe** [opentk/opentk#1543]
### Description

The script fails to run to the end, explanations given below.

### Repro steps

Chronology of events:

**There is a hard dependency on .NET 6.0.200 SDK:**

I figured out that anything that is 6.0.* must be uninstalled beforehand else it'll never work.

The output for reference: [log1.txt](https://github.com/opentk/opentk/files/10100408/log1.txt)

**Now it builds but then fails at RewriteBindings:**

> RewriteBindings         00:00:19.5163417   (Could not parse `sdk.version` from global.json at 'C:\Users\aybe\source\repos\opentk\global.json': Could not find file 'C:\Users\aybe\source\repos\opentk\global.json'.)

Not sure what is supposed to create that file, but it hasn't.

The output for reference: [log2.txt](https://github.com/opentk/opentk/files/10100429/log2.txt)

As suggested in the output, I edited the script so that it runs `fake -v run ...` instead:

> Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'

But that didn't really give any hint as on why it fails, just few more stack traces.

The output for reference: [log3.txt](https://github.com/opentk/opentk/files/10100503/log3.txt)

Any ideas are more than welcome, thank you.

### Related information 

* Microsoft Windows [Version 10.0.19044.2251]
* latest OpenTK as of today: https://github.com/opentk/opentk/commit/6553fc777e07ee3436b2ec789f43c72561301fcf

**Comment by NogginBops** [comment]
This is fixed with #1520 as `build.cmd` and `build.sh` is no longer needed to build from visual studio, it will only be needed when building nuget packages.

I would guess this is where something is breaking,
https://github.com/opentk/opentk/blob/6553fc777e07ee3436b2ec789f43c72561301fcf/build.fsx#L129-L132

or something more hidden in FAKE that causes a hard dependency on a specific SDK version.

**Comment by aybe** [comment]
Amazing, thank you 😀
