### ISSUE TITLE
[OpenTK 5.0] Fix non-blittable parameter types for UnmanagedCallersOnly methods

### ISSUE THREAD

**Issue by japajoe** [opentk/opentk#1546]
So I ran the generator for OpenTK which works lovely, although quickly I was met with this error:

_System.InvalidProgramException: Non-blittable parameter types are invalid for UnmanagedCallersOnly methods.
   at OpenTK.Graphics.OpenGL.GL.VertexAttribPointer(UInt32 index, Int32 size, VertexAttribPointerType type, Boolean normalized, Int32 stride, Void* pointer)_

After a question on the Discord server it became clear that we can't pass Boolean types to methods with the UnmanagedCallersOnly attribute. I will try to give a quick rundown of the problem in this specific case and how I got it to work in the end.

Here is the original function a user calls, and the unmanaged delegate:

```csharp
private static delegate* unmanaged<uint, int, VertexAttribPointerType, bool, int, void*, void> _VertexAttribPointer_fnptr = &VertexAttribPointer_Lazy;

public static void VertexAttribPointer(uint index, int size, VertexAttribPointerType type, bool normalized, int stride, void* pointer) => _VertexAttribPointer_fnptr(index, size, type, normalized, stride, pointer);

[UnmanagedCallersOnly]
private static void VertexAttribPointer_Lazy(uint index, int size, VertexAttribPointerType type, bool normalized, int stride, void* pointer)
{
    _VertexAttribPointer_fnptr = (delegate* unmanaged<uint, int, VertexAttribPointerType, bool, int, void*, void>)GLLoader.BindingsContext.GetProcAddress("glVertexAttribPointer");
    _VertexAttribPointer_fnptr(index, size, type, normalized, stride, pointer);
}
```

Here is what I modified (in essence just changed the bool into a byte):

```csharp
private static delegate* unmanaged<uint, int, VertexAttribPointerType, byte, int, void*, void> _VertexAttribPointer_fnptr = &VertexAttribPointer_Lazy;

public static void VertexAttribPointer(uint index, int size, VertexAttribPointerType type, byte normalized, int stride, void* pointer) => _VertexAttribPointer_fnptr(index, size, type, normalized, stride, pointer);

[UnmanagedCallersOnly]
private static void VertexAttribPointer_Lazy(uint index, int size, VertexAttribPointerType type, byte normalized, int stride, void* pointer)
{
    _VertexAttribPointer_fnptr = (delegate* unmanaged<uint, int, VertexAttribPointerType, byte, int, void*, void>)GLLoader.BindingsContext.GetProcAddress("glVertexAttribPointer");
    _VertexAttribPointer_fnptr(index, size, type, normalized, stride, pointer);
}
```

As a consumer of the API, you never call the functions in GL.Native.cs directly, but rather through GL.Overloads.cs. I changed the function in GL.Overloads.cs from this:

```csharp
public static unsafe void VertexAttribPointer(uint index, int size, VertexAttribPointerType type, bool normalized, int stride, nint offset)
{
    void* pointer = (void*)offset;
    VertexAttribPointer(index, size, type, normalized, stride, pointer);
}
```

Into this:

```csharp
public static unsafe void VertexAttribPointer(uint index, int size, VertexAttribPointerType type, bool normalized, int stride, nint offset)
{
    void* pointer = (void*)offset;
    VertexAttribPointer(index, size, type, normalized ? (byte)1 : (byte)0, stride, pointer);
}
```

From a user's point of view nothing changes, but the exception in this instance is gone. I must note that there are many functions in GL.Native with the same problem so it's very widespread across OpenGL/OpenGLES1/OpenGLES3. After fixing all these manually I finally had a working application with ImGui running.

**Comment by NogginBops** [comment]
This was apparently already fixed in #1471 specifically fec6535bdd829d0e918a9269a3d4bd834e43ee77
