### ISSUE TITLE
Basic .NET 6 application segfaults after shutting down on Ubuntu in WSL

### ISSUE THREAD

**Issue by NinovanderMark** [opentk/opentk#1548]
### Description

A very basic OpenTK application runs fine on Windows, but causes a segmentation fault when running from WSL.

I understand this is a bit of an edge-case, but I was super excited to get a proper cross-platform graphics application running with .NET, and having no spare Linux systems to play around with, WSL with support for GUI applications was too tempting to resist.

### Repro steps

Using the following sample application

*Program.cs*
```csharp
class Program
{
	static int Main(string[] args)
	{
		Console.WriteLine("Application started");

		using (Game game = new Game(1024, 768, "Learning OpenTK"))
		{
			game.Run();
		}

		Console.WriteLine("Application terminated");
		return 0;
	}
}
```
*Game.cs*
```csharp
public class Game : GameWindow
{
	public Game(int width, int height, string title)
		: base(GameWindowSettings.Default, new NativeWindowSettings() { Size = (width, height), Title = title })
	{
	}

	protected override void OnUpdateFrame(FrameEventArgs e)
	{
		base.OnUpdateFrame(e);

		KeyboardState input = KeyboardState;

		if (input.IsKeyDown(Keys.Escape))
		{
			Close();
		}
	}
}
```

Publishing this application using the following publishing profile from Visual Studio 2022:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>\\wsl.localhost\Ubuntu-22.04\home\ninovdmark\opentk-sample</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
</Project>
```

### Expected behavior

The application terminates normally.

### Actual behavior

The application seems to run fine, but ends in a segmentation fault when run from Ubuntu 22.04 through WSL on Windows 10

![image](https://user-images.githubusercontent.com/6692167/206196555-9707351b-7669-4896-a05a-b0d809fbcc7c.png)

### Related information 

* OS: Windows 10 22H2 running WSL 2 with Ubuntu 22.04
* OpenTK version: 4.7.5 (from NuGet)
* Runtime: .NET 6
* WSL version: 1.0.0.0
* Kernel version: 5.15.74.2
* WSLg version: 1.0.47
* MSRDC version: 1.2.3575
* Direct3D version: 1.606.4
* DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
* Windows version: 10.0.19045.2311

**Comment by NogginBops** [comment]
I'm not super familiar with what debugging options are available in Ubuntu (or WSL) but is there some way to know approximately where the code fails? Like a function or a core dump?

My initial guess is that it has something to do with glfw and us trying to load the dll, but without knowing in what part of the code the issue happens in it's hard to know for sure. 
It will probably be a little while before I can test this case for myself so if you are able to provide more details on the segfault itself that would be great.

(if no better methods are available maybe you can attach the VS debugger to WSL and step through the code and see where it fails?)

**Comment by NinovanderMark** [comment]
The curious thing is that everything seems to work perfectly fine, the segmentation fault doesn't come into play until after I shut down the application. I can see the last `Console.WriteLine()` pop up in the terminal, so I imagine it's probably something to do with cleaning up resources.

Running it from `gdb` gives me the following output:

```
Thread 10 "SimpleOpenTK" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff7d55d640 (LWP 2697)]
0x00007fff30e9d391 in ?? () from /usr/lib/wsl/drivers/nvlt.inf_amd64_0e3c491f201d0b53/libnvwgf2umx.so
```

**Comment by NogginBops** [comment]
Yeah this seems like a WSL2/Nvidia driver bug.
We can be thankful that the segfault only happens when exiting the application.
