### ISSUE TITLE
IGlHandleStruct

### ISSUE THREAD

**Issue by frederikja163** [opentk/opentk#1552]
### Description

Add interface for all GlHandles
Makes it possible to take a generic GlHandle for methods like GL.ObjectLabel.

**Comment by NogginBops** [comment]
Without generic implementations of those functions `GL.ObjectLabel(identifier, IGLHandle name, int length, string label)` would cause boxing, so the function should be 
```cs
public void ObjectLabel<THandle>(identifier, THandle name, int length, string label) where THandle : IGLHandle
```

This would also have to work with the fact that by default typed handles are turned off.

**Comment by frederikja163** [comment]
> This would also have to work with the fact that by default typed handles are turned off.

Not sure what you mean about this. But i didn't necessarily mean we should provide the overload for ObjectLabel. But in user code it would be possible to do stuff of that nature or similar. For example in my project using OpenTK 5, i have a base class for all GLObjects. `public abstract class GLObjectBase<T> : IDisposeable` But i would like to add a constraint to the template type. So it could only be a GL Handle.

**Comment by NogginBops** [comment]
Ah I see! Yeah we can add a common interface to the different handles sure.

> > This would also have to work with the fact that by default typed handles are turned off.

> Not sure what you mean about this.

In the next prerelease typed handles is going to be turned off. See #1545

**Comment by utkumaden** [comment]
One issue is that as it stands the typed handles are enums. Enums cannot implement interfaces. A struct can however.

**Comment by NogginBops** [comment]
> One issue is that as it stands the typed handles are enums. Enums cannot implement interfaces. A struct can however.

They are not enums atm? They are structs.

**Comment by utkumaden** [comment]
I stand corrected, had to go back and verify.

**Comment by NogginBops** [comment]
I'm going to close this issue as we are not going to have this interface in OpenTK 5.0.
