### ISSUE TITLE
Polygon fill error?

### ISSUE THREAD

**Issue by lansalot** [opentk/opentk#1556]
Am seeing a strange fill when using PrimitiveTtype.Polygon with it going outside the boundaries. Using OpenTK 3.3.3 (as nuget wouldn't pull updates for 4.7.5), the same code renders the polygon as its line outside (ignore the red boundary). I've seen some threads referring to inability to fill polygons, but that thread is 7years old. Is the only solution still to convert to triangles, what are my options here? Thanks
https://stackoverflow.com/questions/32495064/how-correctly-draw-a-polygon-with-opentk

### Repro steps

Please provide the steps required to reproduce the problem

```
GL.Begin(PrimitiveType.Polygon); // outside border is drawn with LineLoop, exact same code
  // render each point in the part as a piece of the polygon
  for (int ipoint = 0; ipoint < CRatePolygons.PolyParts[ipoly].Parts[ipart].PolyPoint.Count; ipoint++)
    {
      {
        GL.Vertex3(
          CRatePolygons.PolyParts[ipoly].Parts[ipart].PolyPoint[ipoint].easting, 
          CRatePolygons.PolyParts[ipoly].Parts[ipart].PolyPoint[ipoint].northing,
          0);
        }
      }
GL.End();
```

Ends up looking like this:
https://ibb.co/tHW5dFm

### Expected behavior

Polygon should be filled in correctly

### Actual behavior

Polygon fills outside the boundaries

### Related information 

Win2011, VS2019, targetting dotnet 4.6 in c#, nuget installer.

**Comment by NogginBops** [comment]
Using the immediate mode opengl api has been deprecated since 1998 and generally is not used. GPUs only ever fill triangles so by converting your polygon to triangles you are always going to get a more consistent result. 
What you could make sure is that you have compatibility mode enabled and that your GPU vendor doesn't have bugs related to immediate mode rendering and polygon filling.

**Comment by lansalot** [comment]
Ah, I checked the version packaged with source, it mentioned version 1.3 in the DLL properties, but I wasn't sure that was accurate and tried nuget to update. Triangles it is then - is there anything in OpenTK that'll do that optimally, or am I better with Triangle.Net perhaps?

**Comment by NogginBops** [comment]
Also, `GL_POLYGON` (or `PrimitiveType.Polygon`) only renders convex polygons, and it does look like you are rendering a concave polygon, which will not work correctly.

See:
https://stackoverflow.com/questions/15556929/opengl-gl-polygon-concave-polygon-doesnt-color-in
https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glBegin.xml#:~:text=with%20independent%20data.-,GL_POLYGON,-Draws%20a%20single

**Comment by NogginBops** [comment]
> Ah, I checked the version packaged with source, it mentioned version 1.3 in the DLL properties, but I wasn't sure that was accurate and tried nuget to update. Triangles it is then - is there anything in OpenTK that'll do that optimally, or am I better with Triangle.Net perhaps?

OpenTK doesn't have any triangulation built in so you are either going to have to do it yourself or find a library to do it. Never heard of Triangle.Net but it might work.

**Comment by lansalot** [comment]
Thank you very much for the quick response - that'll save my wasting a lot of time going down blind alleys!

**Comment by lansalot** [comment]
https://github.com/wo80/Triangle.NET is the one I was referring to incidentally.
