### ISSUE TITLE
`OpenTK.Mathematics.Vector3h` does not implement math operators

### ISSUE THREAD

**Issue by BoyBaykiller** [opentk/opentk#1565]
### Description

`Vector3h` does not implement any math operators as shown below.

```cs
OpenTK.Mathematics.Vector3h a = new Vector3h();
OpenTK.Mathematics.Vector3h b = new Vector3h();

// all of these produce compile errors
a + b;
a - b;
a * b;
a / b;
```

### Expected behavior

I would expect all of them to be there just like with the other vector types.

### Related information 

Using OpenTK 4.x.

**Comment by NogginBops** [comment]
This requires us to either update OpenTK to .net 7 to get `System.Half` that has math operators implemented, or implement our own `Half` math operators. 
Neither seems like something well do for OpenTK 4 anytime soon.

**Comment by BoyBaykiller** [comment]
Fortunately `OpenTK.Mathematics.Half` already implements all operators.

**Comment by BoyBaykiller** [comment]
Nevermind I thought it does because
```cs
Half a = new Half(1.0f);
Half b = new Half(1.0f);
var result = b - a;
```
worked but it implicitly converts before performing the operation. So `result` is actually of type `float`.

**Comment by NogginBops** [comment]
I think we should close this as this as we probably won't implement this for either OpenTK 4 or OpenTK 5 as both of these are targeting .net versions lower than .net 7 where `System.Half` gets math operators.
