### ISSUE TITLE
[OpenAL] Low Audio Quality

### ISSUE THREAD

**Issue by Khhs167** [opentk/opentk#1573]
### Description

Audio loaded and played back using OpenAL is low quality/has higher frequencies cut off

### Repro steps

Please provide the steps required to reproduce the problem

1. Load an MP3 using MP3Sharp(or maybe any other library, haven't found any other though)
2. Set up OpenAL
3. Play back the file

### Expected behavior

I get the same audio as I would get with e.g VLC, Audacity or any other audio player

### Actual behavior

The audio playback *works*, only that higher frequencies are cut off

### Related information 

Arch Linux
PulseAudio
OpenTK 5.0.0-pre8(used to be written as "latest", changed it though)
.NET 7

Submitted issue on MP3Sharps end: [ZaneDubya/MP3Sharp issue #43](https://github.com/ZaneDubya/MP3Sharp/issues/24)

I will attach related files

Source code: [audio_source.zip](https://github.com/opentk/opentk/files/10824883/audio_source.zip)
Input mp3 and recording of output(mp3 is copyright ATLUS, I don't expect it to stay up) [input-output.zip](https://github.com/opentk/opentk/files/10824888/input-output.zip)

Related to the source code, there's a simple resource system that loads in file data, and the setup process is as follows:
1. Initialize audio context
2. Load AudioClip using the resource system(the Load function is fed the mp3 file and file name)
3. Play back using a while loop to make sure the program doesn't stop before the sound ends

I hope everything is correctly submitted, and I'm open to requests and providing further information!

Hopefully this is just an issue on my end lol.

**Comment by Khhs167** [comment]
I'd like to add that the OpenTK version seems to be 5.0.0 pre-8, I'll update the main post too

**Comment by NogginBops** [comment]
The OpenAL code is the same for both OpenTK 4 and 5 so this sold affect both.

I haven't had time to look at the source code completely, but looking at it quickly I couldn't find anything. Is it possible for you to provide a complete reproducible that can be compiled? That way I could test and see if I can reproduce the issue on my computer

**Comment by Khhs167** [comment]
I pushed an example, it is somewhat hackily assembled but it works. Further testing is needed, but something definitely sounds off on my end.

Repo: https://github.com/Khhs167/OpenALIssueExample

**Comment by Khhs167** [comment]
I might've been able to resolve this issue via `alsoft-config`, and thus it doesn't have to be an issue on the OpenTK side.

Cannot guarantee this however, and I do not remember my steps to "fix" the problem.

**Comment by Khhs167** [comment]
After further testing, I believe that was the issue.

Closing now :)
