### ISSUE TITLE
Support for portable apps on Windows

### ISSUE THREAD

**Issue by i255** [opentk/opentk#1574]
### Description

I would like to use OpenTK in a portable app (without installer). Visual C++ Redistributable dependency is a problem for me. Why don't you use the "lib-static-ucrt" build of GLFW instead of "lib-vc2019"? Is it just the 100kb size difference? In my tests it worked on machines without VC runtime. Could you use it in the glfw-redist package? Is the "lib-static-ucrt" build supported by OpenTK or should I expect issues with it?

### Repro steps

OpenTK crashes with System.DllNotFoundException: Dll was not found, if Visual C++ Redistributable is missing

### Expected behavior

No exception is thrown

### Actual behavior

Exception is thrown

### Related information 

Windows, .NET 6.0, no Visual C++ Redistributable

**Comment by NogginBops** [comment]
There is no particular reason for why we use `lib-vc2019` instead of `lib-static-ucrt`. I'm guessing there is not built in way to ship both in `glfw-redist`, but it should definitely be possible to change to `lib-static-ucrt` unless that has some drawback compared to `lib-vc2019`.

**Comment by i255** [comment]
Thanks for your reply. The only drawback I see is the size (additional 100kb). The static version has much less dependencies:

```
Microsoft (R) COFF/PE Dumper Version 14.35.32215.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file glfw3_ucrt.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    GDI32.dll
    SHELL32.dll

-------

Dump of file glfw3_vs2019.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    GDI32.dll
    SHELL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
```

**Comment by NogginBops** [comment]
Sorry for taking so long to do anything about this issue.
I've just merged PR that changes the dependency to the static-ucrt build of glfw.
https://github.com/opentk/glfw-redist/pull/8

It's going to trigger a build of a prerelease package that you can explicitly build and test for your project. Then we can possibly merge that for OpenTK `4.8.0`.

**Comment by NogginBops** [comment]
@i255 I never followed up on this, but can you verify that explicitly downloading [this version](https://www.nuget.org/packages/OpenTK.redist.glfw/3.3.8-pre20230410192105) of the glfw redist package together with OpenTK solves this problem?

**Comment by i255** [comment]
Yes, it works without VC redist

**Comment by NogginBops** [comment]
Perfect! Then I will make sure to make a new glfw redist package for `4.8.0` that contains the portable binaries and make it the default.
