### ISSUE TITLE
Draw a CvMat with OpenTK

### ISSUE THREAD

**Issue by yhrgsp** [opentk/opentk#1577]
I'm trying to draw a CvMat with OpenTK. I have created a code that generates a random gradient and renders it on the screen, but no matter what I do, I always get a black screen instead of a gradient-colored screen. I am actually drawing something because the GL.ClearColor is showing me the color I set. Here's my code:

    private readonly TimeSpan targetFrameTime = TimeSpan.FromSeconds(1.0 / 30);
    private DateTime lastRenderTime;
    public Window1()
    {
        InitializeComponent();

        var settings = new GLWpfControlSettings
        {
            MajorVersion = 4,
            MinorVersion = 5
        };
        OpenTkControl.Start(settings);

    }

    private void OpenTkControl_OnRender(TimeSpan delta)
    {
        // Limit the number of renders per second
        TimeSpan timeSinceLastRender = DateTime.Now - lastRenderTime;
        if (timeSinceLastRender < targetFrameTime)
        {
            return;
        }
        lastRenderTime = DateTime.Now;
        Mat testMat = new Mat(255, 255, MatType.CV_8UC3);

        Cv2.Randu(testMat, new Scalar(0, 0, 0), new Scalar(255, 255, 255));

        for (int y = 0; y < testMat.Rows; y++)
        {
            for (int x = 0; x < testMat.Cols; x++)
            {
                Vec3b color = testMat.Get<Vec3b>(y, x);
                color.Item0 = (byte)(x * 255 / testMat.Cols);
                color.Item1 = (byte)(y * 255 / testMat.Rows);
                color.Item2 = 0;
                testMat.Set<Vec3b>(y, x, color);
            }
        }

        GL.ClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
        GL.Begin(BeginMode.Quads);
        GL.TexCoord2(0.0f, 0.0f);
        GL.Vertex2(0.0f, 0.0f);
        GL.TexCoord2(1.0f, 0.0f);
        GL.Vertex2(OpenTkControl.ActualWidth, 0.0f);
        GL.TexCoord2(1.0f, 1.0f);
        GL.Vertex2(OpenTkControl.ActualWidth, OpenTkControl.ActualHeight);
        GL.TexCoord2(0.0f, 1.0f);
        GL.Vertex2(0.0f, OpenTkControl.ActualHeight);
        GL.End();
        GL.MatrixMode(MatrixMode.Projection);
        GL.LoadIdentity();
        GL.Ortho(0, OpenTkControl.ActualWidth, OpenTkControl.ActualHeight, 0, -1, 1);
        GL.MatrixMode(MatrixMode.Modelview);
        GL.LoadIdentity();
        GL.Enable(EnableCap.Texture2D);
        GL.GenTextures(1, out int textureId);
        GL.BindTexture(TextureTarget.Texture2D, textureId);
        GL.PixelStore(PixelStoreParameter.UnpackAlignment, 1);
        GL.DrawPixels(testMat.Width, testMat.Height, PixelFormat.Rgb, PixelType.UnsignedByte, testMat.Data);

        OpenTkControl.InvalidateVisual();

    }
thanks

**Comment by NogginBops** [comment]
You are using legacy opengl calls such as glBegin and glEnd. This is only supported if you create a compatibility profile, you need to set the profile in the glwpfsettings.

Though I recommend not using the deprecated parts of OpenGL.

**Comment by yhrgsp** [comment]
Can you show me example?
I tried for a long time but I couldn't draw mat..

**Comment by NogginBops** [comment]
You need to set `settings.GraphicsProfile = Compatibility`.

But I would recommend following a more modern tutorial, for example our own OpenTK tutorial
https://opentk.net/learn/chapter1/0-opengl.html

**Comment by yhrgsp** [comment]
Thanks, setting settings.GraphicsProfile = Compatibility works perfectly.
However, when I resize the Mat to the exact GLWpfControl size, it draws it in something like 4/5 of the GLWpfControl size.
Here's the updated render function:

    private void OpenTkControl_OnRender(TimeSpan delta)
        {
            TimeSpan timeSinceLastRender = DateTime.Now - lastRenderTime;
            if (timeSinceLastRender < targetFrameTime)
            {
                return;
            }
            lastRenderTime = DateTime.Now;
            GL.ClearColor(0.0f, 0.0f, 222.0f, 1.0f);
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
            GL.MatrixMode(MatrixMode.Projection);
            GL.LoadIdentity();
            GL.Ortho(0, OpenTkControl.ActualWidth, OpenTkControl.ActualHeight, 0, -1, 1);
            GL.MatrixMode(MatrixMode.Modelview);
            GL.LoadIdentity();
            GL.Enable(EnableCap.Texture2D);
            GL.BindTexture(TextureTarget.Texture2D, 0);
            GL.PixelStore(PixelStoreParameter.UnpackAlignment, 1);
            Cv2.Resize(_frame, _frame, new OpenCvSharp.Size((int)OpenTkControl.ActualWidth, (int)OpenTkControl.ActualHeight), 0, 0, InterpolationFlags.Nearest);
            GL.DrawPixels(_frame.Width, _frame.Height, PixelFormat.Bgr, PixelType.UnsignedByte, _frame.Data);
            OpenTkControl.InvalidateVisual();

        }

**Comment by NogginBops** [comment]
> Thanks, setting settings.GraphicsProfile = Compatibility works perfectly. However, when I resize the Mat to the exact GLWpfControl size, it draws it in something like 4/5 of the GLWpfControl size. Here's the updated render function:
> 
> ```
> private void OpenTkControl_OnRender(TimeSpan delta)
>     {
>         TimeSpan timeSinceLastRender = DateTime.Now - lastRenderTime;
>         if (timeSinceLastRender < targetFrameTime)
>         {
>             return;
>         }
>         lastRenderTime = DateTime.Now;
>         GL.ClearColor(0.0f, 0.0f, 222.0f, 1.0f);
>         GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
>         GL.MatrixMode(MatrixMode.Projection);
>         GL.LoadIdentity();
>         GL.Ortho(0, OpenTkControl.ActualWidth, OpenTkControl.ActualHeight, 0, -1, 1);
>         GL.MatrixMode(MatrixMode.Modelview);
>         GL.LoadIdentity();
>         GL.Enable(EnableCap.Texture2D);
>         GL.BindTexture(TextureTarget.Texture2D, 0);
>         GL.PixelStore(PixelStoreParameter.UnpackAlignment, 1);
>         Cv2.Resize(_frame, _frame, new OpenCvSharp.Size((int)OpenTkControl.ActualWidth, (int)OpenTkControl.ActualHeight), 0, 0, InterpolationFlags.Nearest);
>         GL.DrawPixels(_frame.Width, _frame.Height, PixelFormat.Bgr, PixelType.UnsignedByte, _frame.Data);
>         OpenTkControl.InvalidateVisual();
> 
>     }
> ```

This sounds like a GLWpfControl issue, if you could open an issue about this here https://github.com/opentk/GLWpfControl that would be great.
Going to close this issue as it seems the original issue has been solved.
