### ISSUE TITLE
Add a EuclideanLengthSquared method

### ISSUE THREAD

**Issue by 15hayden** [opentk/opentk#1587]
### Description

Feature request: add a EuclideanLengthSquared method to Vector2i, Vector3i, and Vector4i.
It would return an int (or a long I suppose, in case of particularly large vectors), and would be a copy of EuclideanLength without the square root.

**Comment by NogginBops** [comment]
I see no reason why this couldn't be added.

What is the use case where you want to use this feature?

**Comment by MH1702** [comment]
If you want to compare distances, like knowing whether one object is further away than another, the "true distance" doesnt matter. So it would be slightly faster, since square roots are notoriously slow operations.

**Comment by utkumaden** [comment]
Odd that the floating point vectors have `Distance` and `DistanceSquared` properties, but integer vectors have `EuclidianDistance` and no squared variant. Maybe next release should consider deprecating the different names and add this.

**Comment by NogginBops** [comment]
> Maybe next release should consider deprecating the different names and add this.

What are you suggesting we deprecate? 
To me this only seems like an addition?

**Comment by utkumaden** [comment]
* Add LengthSquared to VectorNi
* New property, VectorNi.Length which replaces VectorNi.EuclidianLength
* Put [Obsolete()] over `VectorNi.EuclidianLength`.

Just for consistency sake.

**Comment by NogginBops** [comment]
I don't think we should have a length on integer vectors as that is not really a closed operation. I think it's better for people to explicitly state what kind of norm they want for their integer vectors.

But I don't think the name of these properties are that important, as you are unlikely choose the wrong one and create a bug
