### ISSUE TITLE
Expose Raw Mouse Input option in OpenTK 4

### ISSUE THREAD

**Issue by Avibah** [opentk/opentk#1589]
### Description
(Feature request) Expose Raw Mouse Input option in OpenTK 4 (and 5). In 3.x, this behavior is enabled by default, but in 4.x and beyond it is only accessible via a call to `GLFW.SetInputMode(...)` and `NativeWindow.CursorState` must be set to `Grabbed` to see the effects.
Exposing this option would bring back the cursor precision available in 3.x without having to go to glfw directly.
### Related Information
- OpenTK 4.x
- OpenTK 5.x

**Comment by NogginBops** [comment]
Sorry for letting this issue fall through the cracks. This will be fixed for OpenTK `4.8.0`.
