### ISSUE TITLE
.NET MAUI GL Control [Android Side]

### ISSUE THREAD

**Issue by ibluesun** [opentk/opentk#1592]
### Description

Using Maui with OpenGL to achieve the cross platform dream.

### Repro steps

Created a native view for MAUI using their [Create a custom control using handlers](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/create) tutorial

### Expected behavior

GL.ClearColor to work correctly  in the OnSurfaceCreated function 

```
    public void OnSurfaceCreated(IGL10 gl, Javax.Microedition.Khronos.Egl.EGLConfig config)
    {

        _CurrentContext = EGL14.EglGetCurrentContext();
        _CurrentDisplay = EGL14.EglGetCurrentDisplay();


        EGL_VERSION = EGL14.EglQueryString(_CurrentDisplay, EGL14.EglVersion);

        _AndroidContextNativeHandle = new IntPtr(_CurrentContext.NativeHandle);


        //GLES20.GlClearColor(1f, 0f, 0f, 1f);


        GL.ClearColor(0, 1, 1, 1);

    }
```

### Actual behavior

Exception occurred complaining about API wasn't bounded  or Context wasn't created

### Related information 

* Android
* OpenTK (NuGet)
* MAUI

### Workarounds

```
public class AndroidOpenTKBindingsContext : IBindingsContext
{


    [DllImport("/system/lib64/libEGL.so", EntryPoint = "eglGetProcAddress")]
    public static extern IntPtr EglGetProcAddress(string procName);


    public IntPtr GetProcAddress(string procName)
    {
        var glfunc = EglGetProcAddress(procName);

        return glfunc;
       
    }
}
```
#### Quick description of how to make a MAUI native view

- First you need to get it from its corresponding nuget package.
- Second a binding of its functions should be done  .. please have a look inside  `AndroidOpenTKBindingContext`
- In the MauiOpenGLHandler  in the `CreatePlatformView`  .. the `GL.LoadBindings(OpenTKBinder);`  were called  .. then the native view of android were created
- Rendering occurs in the `AndroidOpenGLRenderer`  ..  in this location  you can use  the Android GLES20  class or the OpenTK  GL  class .. the two apis will work.

there is a published repository with working project for the whole work around [MauiOpenGL](https://github.com/ibluesun/MauiOpenGL)

**Comment by NogginBops** [comment]
I can't remember if we fixed this on discord or not. Is this still an issue?

**Comment by NogginBops** [comment]
I think this particular issue is fixed with the "workaround". It's the Intended way to get this working. Will open an issue about potentially making a MAUI component in the future though.

**Comment by ibluesun** [comment]
> I think this particular issue is fixed with the "workaround". It's the Intended way to get this working. Will open an issue about potentially making a MAUI component in the future though.

yes .. making a maui component for opentk would be a good start  ..  I was trying with WinUI 3 stuff .. the native underlying with maui  but no luck  yet  .. tends out I need to learn how to create DirectX first under the same circumstances.
