### ISSUE TITLE
GLFW: Fullscreen window does not minimise (AutoIconify) when it loses focus - resulting in frozen screen

### ISSUE THREAD

**Issue by radfast** [opentk/opentk#1593]
### Description

OpenTK version 4.7.7, running in .NET 7.0

On a Windows platform only.  This issue does not occur in a Linux build. 

**You may need to be on a single-monitor system to see this issue occurring.  A multi-monitor system may mask the issue or it may even be intended behavior on a multi-monitor setup - some people prefer to set AutoIconify to false on a multi-monitor setup.**

When AutoIconify is set to true, and a `GameWindow` which has `WindowState.Fullscreen` loses current focus, in two situations out of three - see list following - it is not minimised (iconified), instead it remains fullscreen on top of all other windows.   This results in an apparently frozen PC, because the GameWindow remains on screen but is unresponsive.  When the issue has occurred, even pressing Alt+Tab then does not change the GameWindow from remaining fullscreen and on top, therefore the PC can appear to be locked up and completely unresponsive.

List of three situations where focus can be lost:
1.  GameWindow.Run() throws an unhandled Exception - the described issue **occurs**
2.  If running a Debug build from inside an IDE (for example Visual Studio Community 2022) and a breakpoint is reached - the described issue **occurs**
3.  GameWindow.Run() is running normally and the user presses Alt-Tab - the described issue does **not** occur, the GameWindow minimises correctly

### Repro steps

1. Step A

In Windows, please create a small project with the following code, adapted from https://github.com/opentk/LearnOpenTK/tree/master/Chapter1/1-CreatingAWindow
(note: from the three files in that repo, keep `1-CreatingAWindow.csproj`, replace `Program.cs` with the code below, and delete `Window.cs` as its Window class is now included in the below).

```using OpenTK.Mathematics;
using OpenTK.Windowing.Common;
using OpenTK.Windowing.Desktop;
using OpenTK.Windowing.GraphicsLibraryFramework;

namespace LearnOpenTK
{
    public static class Program
    {
        private static void Main()
        {
            var nativeWindowSettings = new NativeWindowSettings()
            {
                Size = new Vector2i(800, 600),
                Title = "OpenTK iconify bug",
                WindowState= WindowState.Fullscreen,    // <--- only Fullscreen window has the bug
                Flags = ContextFlags.ForwardCompatible,
            };

            GLFW.WindowHint(WindowHintBool.AutoIconify, true);     // <--- first attempt to have correct AutoIconify behavior (though this is the default already)
            using (var window = new Window(GameWindowSettings.Default, nativeWindowSettings))
            {
                unsafe { GLFW.SetWindowAttrib(window.WindowPtr, WindowAttribute.AutoIconify, true); }        // <--- second attempt to have correct AutoIconify behavior (though this is the default already)
                window.Run();
            }
        }
    }

    public class Window : GameWindow
    {
        public Window(GameWindowSettings gameWindowSettings, NativeWindowSettings nativeWindowSettings) : base(gameWindowSettings, nativeWindowSettings)
        { }

        protected override void OnUpdateFrame(FrameEventArgs e)
        {
            if (KeyboardState.IsKeyDown(Keys.Escape)) Close();

            if (KeyboardState.IsKeyDown(Keys.E)) throw new System.Exception("Test exception");  // <--- For testing AutoIconify, trigger an exception when E is pressed

            base.OnUpdateFrame(e);
        }

        protected override void OnMinimized(MinimizedEventArgs e)
        {
            base.OnMinimized(e);   // <--- If an exception is thrown while the window is running, Program loses control before this line is reached
        }
    }
}
```

2. Step B

Try running Program.cs from the command line `dotnet run`.  Try also running the code in Debug and Release builds, inside an IDE such as Visual Studio Community 2022.  

In all three cases, press the E key to cause the issue.

### Expected behavior

I would expect `AutoIconify:true` to work as described in the documentation.

After an exception (for example pressing the E key in the example code), the GameWindow should be minimised.  It should be promptly and immediately minimised whenever the app providing the GameWindow loses focus and surrenders control to another app (whether that is the OS shell or the IDE).

### Actual behavior

The GameWindow is not minimised, when an exception occurs, instead it remains fullscreen and unresponsive.   The mouse pointer can be moved but mouse clicks have no effect.

In some situations when reproducing this issue, the mouse pointer becomes the [Windows wait cursor](https://en.wikipedia.org/wiki/Windows_wait_cursor) after ~1 second.  

When the issue occurs the GameWindow remains on screen and unresponsive until its process is terminated, meaning the PC appears locked.  In fact the PC is **not** locked, other processes are still running and Alt+Tab can switch between processes, it's just the user cannot see what they are doing and everything except the GameWindow is **invisible**.  Keyboard controls in the other (invisible) processes still work normally, and the user can therefore shut down the GameWindow app using a keyboard sequence if they have the key presses memorised.  For example, running in Debug mode from inside the Visual Studio IDE and the user pressed Alt+Tab the correct number of times to (invisibly) switch focus to Visual Studio, the user can then press Shift+F5 inside Visual Studio to terminate the app.   The user can also Alt+Tab back to the GameWindow and then press Alt+F4 to bring up the End Process dialog box and exit that way. 

### Possible cause

It appears that GameWindow's own code to iconify the window might not be being reached, if an exception or breakpoint takes control away from the process.  Certainly, the callback code - in the example code above, that's the `OnMinimised()` method - is not reached in the case of an exception or breakpoint.

### Related information 

* Operating system:  tested on **Windows 10 Pro**, two different versions (1903 and 22H2)
* What version of OpenTK (Installer, NuGet, Source Code):  **4.7.7 fetched from NuGet today**
* What runtime (.NET Framework, CoreCLR, Mono):  **.NET 7.0**.   Also seen in NetCoreApp 3.1 as used in the LearnOpenTK example
* Workarounds (if any):  see next comment

@Th3Dilli has also tested the issue and can reproduce it consistently, using the code example above or our app's own code.  We are two of the dev team for the game Vintage Story - https://www.vintagestory.at/

**Comment by radfast** [comment]
As an attempted workaround in our app, we have set `AppDomain.CurrentDomain.UnhandledException` with a handler whose first line is like this:

        private void HandleUnhandledException(object sender, UnhandledExceptionEventArgs e)    {
            unsafe   {
                GLFW.IconifyWindow(gamewindow.WindowPtr);
            }

            // ...
        }

Even this is not successful at resolving the issue, the GameWindow seems completely borked after it was supposed to iconify but didn't iconify.

**Comment by NogginBops** [comment]
Unfortunately this is kind of the expected behavior for this setup. When a breakpoint is reached or an exception is thrown the application code stops funning and the debugger takes over. This means that the window can no longer respond to window messages or do anything to alter the state of the program at the point of the breakpoint or exception (and this is a good thing for debugging). So auto-iconify is working correctly, it's just that the auto-iconify code is never being run as the program has stopped.

This isn't really something we can really solve as keeping the window fullscreen while debugging is often desirable, the workaround you've presented for exceptions is a workable option when working on a single monitor.

**Comment by NogginBops** [comment]
Going to close this as `wontfix` as there isn't really a solution, and there exists a workaround.
