### ISSUE TITLE
GLFW not found when publishing Linux ARM builds

### ISSUE THREAD

**Issue by MV10** [opentk/opentk#1604]
I am using the OpenTK 4.7.7 package with .NET 6.0.18. I am testing a very basic program which mostly matches one of the simple tutorial examples, which runs as expected under Win 10 Pro x64, both within Visual Studio in debug and standalone (published release build). I am trying to get it to run on a Raspberry Pi 4B running 32-bit Raspbian (which is currently Debian 11 Bullseye). Other .NET6 applications are running correctly on the Pi, so I know the basic .NET runtime installation is fine.

I should probably also explain I went with the 32-bit OS because I read the Pi GPU is 32-bit only, and there are possible complexities getting a 64-bit program to work smoothly with the GPU. No idea if that's at all relevant with .NET or this library in the mix, or if that claim is even true. If someone knows for sure and tells me that 64-bit is the way to go (I know as a rule of thumb it's faster), it's relatively easy for me to switch. Currently this Pi is dedicated to this little project, I wouldn't be losing any other work.

When I set the publishing target to a release build for Linux 32-bit ARM (RID `linux-arm`), executing the application results in:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'glfw' or one of its dependencies.
```

The files in the publish output directory are as follows (the project/executable name was `Complexity` as I was messing around with a bunch of vert color nonsense), and there are no subdirectories:
```
Complexity
Complexity.deps.json
Complexity.dll
Complexity.pdb
Complexity.runtimeconfig.json
OpenTK.Compute.dll
OpenTK.Core.dll
OpenTK.Graphics.dll
OpenTK.Input.dll
OpenTK.Mathematics.dll
OpenTK.OpenAL.dll
OpenTK.Windowing.Common.dll
OpenTK.Windowing.Desktop.dll
OpenTK.Windowing.GraphicsLibraryFramework.dll
shader.frag
shader.vert
```

I don't think this is a 32-bit / 64-bit problem, as a test I also targeted RID `linux-arm64` and the same files were published (obviously they won't run on my 32-bit OS).

When I set the publishing target to `win-x86` or `win-x64` a GLFW DLL is present in the output directory. Then I noticed that if I set the publishing target to Portable, the outputs are Windows-style `.exe` and `.dll` filenames, but I also find a `runtimes` subdirectory which contains directories with versions of GLFW matching these:
```
linux-x64
osx-arm64
osx-x64
win-x64
win-x86
```

Since it isn't listed in the Portable `runtimes` directory, is any Linux ARM architecture supported? Should a GLFW `.so` or `.dll` be provided in the publish directory for Linux ARM targets. Or am I expected to figure out how to install it from some third-party source? Perhaps I need to build it myself from your `glfw-redist` repository?

I like what I see in OpenTK so far (although if I get this working, my next nagging issue will be how to execute it windowlessly, full-screen, from a text mode CLI with no X support, or at least without the full X GUI running)... I _really_ don't want to have to go back to crusty old plain C OpenGL and cheesy non-VS IDEs! 😁

**Comment by utkumaden** [comment]
It might just be because we don't have ARM builds for the redist. (Don't quote me on that) If you install GLFW on the target OS, it should work, as long as it is in the LD_LIBS path.

**Comment by MV10** [comment]
A Debian package search does list it:

https://packages.debian.org/search?keywords=glfw&searchon=all&suite=stable&section=all

>**Package libglfw3**
    bookworm (stable) (libs): portable library for OpenGL, window and input (x11 libraries)
    3.3.8-1: amd64 arm64 armel armhf i386 mips64el mipsel ppc64el s390x

APT on Pi seems to think `armhf` is the correct package (hopefully that means 32-bit given `arm64` is listed above):
```
$ sudo apt install libglfw3
Selecting previously unselected package libglfw3:armhf.
```

The program does find it ... then crashes with a different exception:
```
Unhandled exception. OpenTK.Windowing.GraphicsLibraryFramework.GLFWException: The GLFW library is not initialized
   at OpenTK.Windowing.Desktop.GLFWProvider.<>c.<.cctor>b__10_0(ErrorCode errorCode, String description)
Aborted
```

Heh heh, not sure if this is progress or not!

**Comment by utkumaden** [comment]
That's some progress, since it doesn't seem to be failing in framework code for P/Invoke. Now we have to figure out why GLFW is not initialized. Since the stack trace has anonymous methods this is going to be kind of hard. I'll see what the maintainer thinks, but we might need a debug build of OpenTK.

**Comment by MV10** [comment]
Thanks.

For the record, _this_ mostly-Windows-guy just learned that `armhf` indicates (H)ardware (F)loating-point support, and those builds are indeed 32-bit, as all 64-bit ARM always has HF support.

While I wait, I'll see if I can get VS remote debug working (read about it, never tried it). If it ends up being easy, I'll clone and see if I can get a debug build loaded up, too.

**Comment by NogginBops** [comment]
Thanks for the very detailed issue.
Can you show the code you are running when you are getting the "glfw is not initialized"?

If it's easy to build we could add arm builds for glfw to the redist package, I've already added the ability to change

**Comment by NogginBops** [comment]
Accidentally pressed the close issue button.

**Comment by MV10** [comment]
Sure, but with minor exceptions in the render loop, it's just the `Game` class from the vertex color portion of the tutorial. 

I assume it's failing on the constructor:

```c#
public Game(int width, int height, string title)
    : base(GameWindowSettings.Default, new NativeWindowSettings() { Size = (width, height), Title = title })
{ }
```

Haven't been able to get VS to debug properly. It'll connect and it "thinks" it's debugging, but breakpoints don't work and so on. Looks like it might be a known issue, somebody else filed this a couple weeks ago:

https://developercommunity.visualstudio.com/t/remote-debugging-on-Linux-over-SSH-does/10382775

**Comment by NogginBops** [comment]
We have members on our discord that have gotten opengl running on RPi using EGL, which could possibly work on a headless server. 
So that is a place to look for advice on that.

**Comment by MV10** [comment]
For what it's worth, I get the same error on a 64-bit OS and build (and, of course, using the `arm64` libglfw3 package).

But I suspect that the Debian package isn't appropriate for Raspbian based on things I've read about other graphics libs.

**Comment by MV10** [comment]
Removed the Debian lib and built it from source... Had to copy the .so to the app directory but ended up with the same initialization error.

Towards the end of this Pi forum post, this person mentions some things he had to change in the GLFW sample code, wondering if maybe any of that looks familiar or relevant? Perhaps something a build target `#if` block could apply, for example.

https://forums.raspberrypi.com/viewtopic.php?t=222264#p1662063

Also, EGL won't work with the Pi 4's VC6 GPU, for what it's worth.

**Comment by MV10** [comment]
Probably not super-useful, but just for the heck of it I tried GDB for remote-debug instead of Managed Code, and to my surprise it does connect and work partially even though it reports that it assumes the wrong architecture (x86_64). Breakpoints even work. It breaks on the exception, but at that point I can't do much since it wants to step into something lower level. Anyway here's the contents of the Output window to the point of the exception.

I was wondering which GLFW lib it required, it does tell me `Inferior loaded /home/jon/pi-fx/libglfw.so.3`...

```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
[New LWP 985]
[New LWP 986]
[New LWP 987]
[New LWP 988]
[New LWP 989]
[New LWP 991]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__GI___poll (timeout=0, nfds=1, fds=0xff87f0e0) at ../sysdeps/unix/sysv/linux/poll.c:29
[New Thread 0xf062f440 (LWP 1072)]
Stopped due to shared library event (no libraries added or removed)
Stopped due to shared library event:
  Inferior loaded /home/jon/pi-fx/libglfw.so.3
Stopped due to shared library event (no libraries added or removed)
Stopped due to shared library event:
  Inferior loaded /lib/arm-linux-gnueabihf/libX11.so.6
    /lib/arm-linux-gnueabihf/libxcb.so.1
    /lib/arm-linux-gnueabihf/libXau.so.6
    /lib/arm-linux-gnueabihf/libXdmcp.so.6
    /lib/arm-linux-gnueabihf/libbsd.so.0
    /lib/arm-linux-gnueabihf/libmd.so.0
Stopped due to shared library event (no libraries added or removed)
=library-unloaded,id="/lib/arm-linux-gnueabihf/libX11.so.6",target-name="/lib/arm-linux-gnueabihf/libX11.so.6",host-name="/lib/arm-linux-gnueabihf/libX11.so.6",thread-group="i1"
=library-unloaded,id="/lib/arm-linux-gnueabihf/libxcb.so.1",target-name="/lib/arm-linux-gnueabihf/libxcb.so.1",host-name="/lib/arm-linux-gnueabihf/libxcb.so.1",thread-group="i1"
=library-unloaded,id="/lib/arm-linux-gnueabihf/libXau.so.6",target-name="/lib/arm-linux-gnueabihf/libXau.so.6",host-name="/lib/arm-linux-gnueabihf/libXau.so.6",thread-group="i1"
=library-unloaded,id="/lib/arm-linux-gnueabihf/libXdmcp.so.6",target-name="/lib/arm-linux-gnueabihf/libXdmcp.so.6",host-name="/lib/arm-linux-gnueabihf/libXdmcp.so.6",thread-group="i1"
=library-unloaded,id="/lib/arm-linux-gnueabihf/libbsd.so.0",target-name="/lib/arm-linux-gnueabihf/libbsd.so.0",host-name="/lib/arm-linux-gnueabihf/libbsd.so.0",thread-group="i1"
=library-unloaded,id="/lib/arm-linux-gnueabihf/libmd.so.0",target-name="/lib/arm-linux-gnueabihf/libmd.so.0",host-name="/lib/arm-linux-gnueabihf/libmd.so.0",thread-group="i1"
Stopped due to shared library event:
  Inferior unloaded /lib/arm-linux-gnueabihf/libX11.so.6
    /lib/arm-linux-gnueabihf/libxcb.so.1
    /lib/arm-linux-gnueabihf/libXau.so.6
    /lib/arm-linux-gnueabihf/libXdmcp.so.6
    /lib/arm-linux-gnueabihf/libbsd.so.0
    /lib/arm-linux-gnueabihf/libmd.so.0

Thread 1 "Complexity" hit Catchpoint 1 (exception thrown), 0xf7b4cee0 in __cxa_throw () from /lib/arm-linux-gnueabihf/libstdc++.so.6
Exception 'winrt::hresult_error' thrown at 0xF7B4CEE0 in __cxa_throw.
```

**Comment by MV10** [comment]
Good news, got it working!

I implemented the changes noted in that Rapsberry Pi forum post (and it also continues to work this way on my relatively new, high-end Windows hardware, not surprisingly).

Window creation is now as follows:

```csharp
public Game(int width, int height, string title)
    : base(GameWindowSettings.Default, 
          new NativeWindowSettings() 
          {
              API = ContextAPI.OpenGLES,      // new
              APIVersion = new Version(3,0),  // new
              Profile = ContextProfile.Core,  // new
              Size = (width, height), 
              Title = title 
          })
{ }
```

The one setting from that Pi forum post that I'm unsure about is this, but perhaps it doesn't matter?

`glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);`

I also changed the shader defs to `#version 300 es` and added the ES-specific precision statement to the frag shader:

```glsl
#version 300 es
precision mediump float;

out vec4 FragColor;  
in vec3 ourColor;
  
void main()
{
    FragColor = vec4(ourColor, 1.0);
}
```

So .... now that we know Raspberry Pi requirements, how can I help you guys figure out a pain-free "it just works" fix?

**Comment by MV10** [comment]
This morning I added some console output so I could track how long it runs before it hangs -- and it doesn't hang any more. I'm on my third run and it has survived about 20 to 30 minutes each time, whereas yesterday it would hang after only about four or five minutes.

But yesterday I was trying all kinds of things without a reboot, including all those initialization failures / crashes, as well as unsuccessful attempts to attach the VS remote debugger, so perhaps I just caused a problem in the driver or some other system somewhere.

I also experimentally removed the locally-copied GLFW library that I built from source, then re-installed the Debian GLFW lib via APT, and that appears to work, too. I've posted in the Pi forum asking if that's "safe" to use, given that I have read many of the Pi graphics libraries are specific to the Pi in some way (sadly, the Broadcom VideoCore 6 GPU is saddled with all kinds of Super Secret NDA nonsense).

I'd still like to know if there is a `NativeWindowSettings` property equivalent to that GLFW hint from the Pi post:

`glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);`

However, I'd say it's safe to consider how to support the Pi in OpenTK if you want to proceed along those lines.

It would appear to be as simple as "install the GLFW library" and apply the GLES 3.1 native properties -- perhaps those properties could be baked into OpenTK somewhere? Though I'd certainly understand if you preferred to just document it, I doubt Pi users are a large part of your user base!

**Comment by MV10** [comment]
Turns out the hang has something to do with switching out of `WindowState.Fullscreen` back to windowed mode.

Under Linux this can be pretty complicated as you have the x11 server, the window manager, the desktop environment, etc. -- the Pi 4 OS defaults to a desktop called LXDE. It doesn't hang on every switch, but I can't flip back and forth more than about two or three times. 

I haven't had any problems going back and forth in Windows.

The switching code in `OnUpdateFrame` is trivial, for what it's worth:

```csharp
var input = KeyboardState;

if (input.IsKeyDown(Keys.Escape))
{
    Close();
}

if (input.IsKeyReleased(Keys.Space))
{
    WindowState = (WindowState == WindowState.Fullscreen) ? WindowState.Normal : WindowState.Fullscreen;
}
```

**Comment by MV10** [comment]
Noticed this 2022 comment about Fullscreen-related freezing, so perhaps that's not specific to what I'm doing?

https://github.com/opentk/opentk/issues/1387#issuecomment-1038153887

**Comment by MV10** [comment]
I'm going to close this since the original issue is resolved.

From the OpenTK standpoint, if you want to support Raspberry Pi users, it may be as simple as a documentation change -- it looks like off-the-shelf GLFW via `apt install` works, and the other `NativeWindow` changes to target OGLES 3.1 (or 3.2) are needed. But if you want to put GLFW into your redist project, please feel free to ping me, I'm glad to help.

I still have the problem where it hangs switching in and out of full screen, but I'll open a separate issue for that.

Really appreciate everyone's time.
