### ISSUE TITLE
Textures render on Win10 but not on Linux (RPi)

### ISSUE THREAD

**Issue by MV10** [opentk/opentk#1606]
I almost hate to ask about this because my program is relatively simple, but has anyone seen a case where `GL.TexImage2D` doesn't work with a `float` buffer (yet doesn't return any errors)? As the subject says, the program renders a texture to a quad which works as expected in Windows 10 Pro x64, but does not work in Linux (latest Raspberry Pi 4B running their OS based on 32-bit Debian "Bullseye" and the default LXDE GUI). I'm using .NET6 and the current 4.x OpenTK package, targeting OpenGL ES 3.1 or 3.2 (same results either way, but 3.1 is officially supported by the Pi).

The program uses OpenAL to capture audio, and it converts this to various textures representing PCM/wave, frequency, and volume. As a test, I render to a simple window taken from the "Texture" tutorial to continuously output one of these textures, which is updated every time the audio buffer is filled (as you might imagine, the render loop frequency is much higher than the audio buffer fill rate). I know audio-capture is working on the Pi because I can toggle the program between texture updates and Console-based "rendering" of the audio buffers that feed texture generation. 

On Windows it looks like this (scrolling upwards; everything above row zero is history data), but running on the Pi, there is no texture, the quad is blank / black.

![image](https://github.com/opentk/opentk/assets/794270/04a37038-8559-49b1-bd17-1f5c3e3e6707)

I sprinkled AL/GL error checks throughout the code, and none of those report any problems. The x11 log file looks normal, nothing but routine startup / shutdown stuff (I read somewhere that some OpenGL implementations might log errors there).

As a sanity check, I added StbImageSharp to the project and loaded up a JPEG similar to what the Texture tutorial shows, although I did modify it to better approximate what my app does: the `GL.TexImage2D` call happens every frame (since the sound textures are constantly updated from the PCM buffer as the program runs), and I explicitly set the texture `uniform` by name (which has no effect either way for this simple test, but I was trying everything). The JPEG-as-texture loads just fine, this is a screenshot of the Pi GUI:

![image](https://github.com/opentk/opentk/assets/794270/39e4c9ee-ce0d-4750-a004-324ef9f6de27)

The only important difference I can see between the JPEG version and the audio-data version is that the audio data is a `float` array -- and again, it works perfectly under Windows, but not at all on the Pi.

This is the function which turns a 4096x128 `float` array named `ChannelBuffer` into a 1024x128 texture... simple stuff:

```csharp
public void GenerateTexture()
{
    if (Handle == UninitializedTexture)
    {
        Handle = GL.GenTexture();
    }

    GL.ActiveTexture(AssignedTextureUnit);
    GL.BindTexture(TextureTarget.Texture2D, Handle);

    GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapS, (int)TextureWrapMode.ClampToEdge);
    GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapT, (int)TextureWrapMode.ClampToEdge);
    GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)TextureMinFilter.Linear);
    GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)TextureMagFilter.Linear);

    GL.TexImage2D(TextureTarget.Texture2D, 0, PixelInternalFormat.Rgba, PixelWidth, Height, 0, PixelFormat.Rgba, PixelType.Float, ChannelBuffer);

    ErrorLogging.OpenGLErrorCheck($"{nameof(AudioTextureData)}.{nameof(GenerateTexture)}");
}
```

Nothing special in my render override, either:

```csharp
protected override void OnRenderFrame(FrameEventArgs e)
{
    base.OnRenderFrame(e);

    if (Audio.BufferTimestamp < LastBufferTimestamp) return;
   
    if(ShowConsole)
    {
        RenderToConsole();
        return;
    }

    Shader.Use();

    GL.BindVertexArray(VertexArrayObject);

    Audio.DebugColorChannels = true; // true: use visible color channel instead of alpha
    Audio.UpdateTextures();

    int textureHandle = DemoMode switch
    {
        AudioTextureType.Wave => Audio.TextureSoundHistory.Handle,
        AudioTextureType.Volume => Audio.TextureVolumeHistory.Handle,
        AudioTextureType.Frequency => Audio.TextureFrequencyHistory.Handle
    };

    TextureUnit texUnit = DemoMode switch
    {
        AudioTextureType.Wave => Audio.TextureSoundHistory.AssignedTextureUnit,
        AudioTextureType.Volume => Audio.TextureVolumeHistory.AssignedTextureUnit,
        AudioTextureType.Frequency => Audio.TextureFrequencyHistory.AssignedTextureUnit
    };

    Shader.SetTexture("audioTexture", textureHandle, texUnit);

    GL.DrawElements(PrimitiveType.Triangles, indices.Length, DrawElementsType.UnsignedInt, 0);

    SwapBuffers();

    ErrorLogging.OpenGLErrorCheck($"{nameof(TexWindow)}.{OnRenderFrame}");
}
```

Is it safe to assume GLFW doesn't care about any such thing, given that it happily renders the JPEG? I only mention GLFW because I had a thread recently about GLFW issues on the Pi ... I'm currently using the Debian APT-installed library, but I read older messages on the Pi forum suggesting that it may be necessary to compile it myself. I did that once before, so I will probably try that again, but since the JPEG texture works, I'd be surprised if windowing abstractions do anything more complicated than providing a render target.

Eventually I will ask in the Pi forum, too, but if anyone answers at all, they'll probably blow it off because I'm using a wrapper library -- and frankly because they _really_ hate Microsoft and resent .NET playing in their back yard. That has a low probability of success.

Assuming nobody has a super-handy answer like, "Oh yeah, you need to do XYZ to use floats," can someone offer ideas or suggestions about how to troubleshoot this further?

**Comment by MV10** [comment]
Apparently float textures are considered an extension in OpenGL ES, but they are supported, I added this and it reports true:

```csharp
var exts = GL.GetString(StringName.Extensions);
Console.WriteLine($"GL_OES_texture_float? {exts.Contains("GL_OES_texture_float")}");
```

**Comment by NogginBops** [comment]
If [Renderdoc](https://renderdoc.org) works on RPi that could be worth a shot to see if it says anything of interest.

**Comment by MV10** [comment]
Yeah, I haven't used it before, but I was thinking about that, too.

But to keep things simple, I created a bare-minimum reproduction (Pi GL ES Test ... piglets! ha...)

https://github.com/MV10/piglets

It just uses clock milliseconds to cycle through the green channel on a 4096x128 float array.

Works on Win10, black screen on the Pi...

**Comment by MV10** [comment]
Bah, RenderDoc:

> On linux only 64-bit x86 is supported

**Comment by MV10** [comment]
RenderDoc doesn't _officially_ support ARM32 but the folks behind the Raspberry Pi provide a build anyway, although it seems like the Texture tab doesn't want to render correctly, so that might make things tricky.

It can at least grab frames on the Pi:

![image](https://github.com/opentk/opentk/assets/794270/d66551d4-1763-4804-acd3-9925c0c3d2d0)

...versus frames grabbed on Windows x64:

![image](https://github.com/opentk/opentk/assets/794270/2b3abf4d-ba8e-449d-86e2-2c4597da4e4e)

I don't know how to use RenderDoc, but it does look "suspicious" to me that _on Windows_ when I load a capture and click the Textures tab on the `SwapBuffers` command, the quad is black, not green.

![image](https://github.com/opentk/opentk/assets/794270/23db7b35-8dc2-44db-bfed-45e58833ed34)

**Comment by MV10** [comment]
Yeah I must be doing something wrong, on my other JPG / unsigned byte test, RenderDoc does show the filled quad on the Texture tab.

![image](https://github.com/opentk/opentk/assets/794270/05d9b0c5-3717-4a4e-aeed-785a314e8fb9)

**Comment by MV10** [comment]
Some interesting details... I altered the repro so that the spacebar toggles between floats (green channel) and bytes (red channel). Extremely trivial changes:

```csharp
// in the render method:
if(ShowFloats)
{
    FloatChannelBuffer[red + 1] = millisec;
}
else
{
    ByteChannelBuffer[red] = (byte)(255f * millisec);
}

// and a little further down:
if(ShowFloats)
{
    GL.TexImage2D(TextureTarget.Texture2D, 0, PixelInternalFormat.Rgba, 
      PixelWidth, Height, 0, PixelFormat.Rgba, 
      PixelType.Float, FloatChannelBuffer);
}
else
{
    GL.TexImage2D(TextureTarget.Texture2D, 0, PixelInternalFormat.Rgba, 
      PixelWidth, Height, 0, PixelFormat.Rgba, 
      PixelType.UnsignedByte, ByteChannelBuffer);
}
```

On Windows, RenderDoc correctly captures the byte texture (the quad is red on the Texture tab), but still doesn't seem to like the float textured quads when I toggle the other way.

![image](https://github.com/opentk/opentk/assets/794270/63aca116-7c2c-4f3b-b4d7-eaf1a0ebb206)

![image](https://github.com/opentk/opentk/assets/794270/7c730b70-d5b3-4c93-81f8-45fd73339da9)

My first test on the Pi seemed as if nothing changed, no texture was shown for float _or_ byte buffers. 

Then I changed the flag so that it defaults to bytes instead of floats, and that _does_ work ... until I toggle to floats, then float still fails to render, and after that bytes won't render either. (It looks like RenderDoc can "see" the byte version until I toggle to floats, the capture thumbnail shows the red fill, but the RenderDoc Texture tab still doesn't work right on the Pi, so I can't say for sure...)

**Comment by MV10** [comment]
Bah... my bug: `PixelInternalFormat.Rgba` instead of `PixelInternalFormat.Rgba32f`... because of the way Intellisense orders those options (not alphabetically) I didn't realize there were variations like 16f and 32f. I've written shaders for many years, but always inside some engine. Live and learn I guess.

Strange that it _visually_ works on Windows anyway, but I guess RenderDoc having problems under Windows was still indirectly the hint I needed.
