### ISSUE TITLE
[4.x] Missing glGet enums for KHR_debug.

### ISSUE THREAD

**Issue by utkumaden** [opentk/opentk#1611]
### Description
The following `glGetInteger` values associated with the core extension `KHR_debug` are missing from the `GetPName` enum:

* `GetPName.DebugLoggedMessages`
* `GetPName.DebugNextLoggedMessageLength`
* `GetPName.DebugGroupStackDepth`

However they are available as their `All` enum:
* `All.DebugLoggedMessages`
* `All.DebugNextLoggedMessageLength`
* `All.DebugGroupStackDepth`

### Expected behavior
Since `KHR_debug` is a core extension and part of the OpenGL API now, it should be possible to use the extension enum values without resorting to a vendor enum or `All`.

### Related information 

* Operating system: Any
* OpenTK 4.7.7
* Runtime: Any
* Workarounds: Cast an `All` enum value to `GetPName`

**Comment by NogginBops** [comment]
Turns out this is slightly more work that I would like for it to get into `4.8.1`, so I'm going to retarget this for `4.8.2`.
