### ISSUE TITLE
Cannot run Hello World application using OpenTK 4.8.0 on Ubuntu 22.04-x64

### ISSUE THREAD

**Issue by dockeratso** [opentk/opentk#1620]
### Description

It is not possible to run an simple  console application using  .NET 7.0 with OpenTK 4..8.0 dependency on Ubuntu 22.04-x64 

### Repro steps

Setup a Ubuntu 22.04-x64 as a VM or as a wsl (Windows subsystem for Linux).  
Install dotnet 7

Create a console application as follows:

dotnet new console --name TestOpenTK
cd TestOpenTK
dotnet add package OpenTK --version 4.8.0

Copy the following into the Program.cs file:

using OpenTK.Windowing.Desktop;
using (var window = new GameWindow(new GameWindowSettings(), new NativeWindowSettings()
{
    StartVisible  = false,
}))
{
}

Compile the console application using;
dotnet run

### Expected behavior

No error ( and maybe a window being shown somems)

### Actual behavior

Note that the glfw file is not even found. See log below. Then I try to make a copy of the so-file libglfw.so.3.3
to libglfw.so  (both in the same folder bin/Debug/net7.0/runtimes/linux-x64/native/)

Then it is found but then  I get the following error: version `GLIBC_2.34' not found
If I check the current installed version of libc6:
libc6 is already the newest version (2.35-0ubuntu3.1).

Output log:

scienta@LAPTOP-QCF8OEO6:/mnt/c/Users/scienta/Downloads/TestOpenTK$ dotnet run
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'glfw' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/glfw.so: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/wayland/glfw.so: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/glfw.so: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/glfw.so: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/libglfw.so: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/wayland/libglfw.so: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/libglfw.so: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/libglfw.so: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/glfw: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/wayland/glfw: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/glfw: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/glfw: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/libglfw: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/runtimes/linux-x64/native/wayland/libglfw: cannot open shared object file: No such file or directory
/snap/dotnet-sdk/216/shared/Microsoft.NETCore.App/7.0.9/libglfw: cannot open shared object file: No such file or directory
/mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Debug/net7.0/libglfw: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.LoadLibrary(String libraryName, Version version, Assembly assembly, Nullable`1 searchPath)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.<>c.<.cctor>b__3_0(String name, Assembly assembly, Nullable`1 path)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFWNative.glfwInit()
   at OpenTK.Windowing.GraphicsLibraryFramework.GLFW.Init()
   at OpenTK.Windowing.Desktop.GLFWProvider.EnsureInitialized()
   at OpenTK.Windowing.Desktop.NativeWindowSettings..ctor()
   at Program.<Main>$(String[] args) in /mnt/c/Users/scienta/Downloads/TestOpenTK/Program.cs:line 3

**Comment by dockeratso** [comment]
I tested again with the prerelease of dotnet 8 (.NET 8.0.0-preview.6) and there was no problem to run the code.  It seems to be a problem with version of libc.

**Comment by dockeratso** [comment]
This problem is related to the snap version of dotnet. See issue: https://github.com/dotnet/runtime/issues/89471
If dotnet is installed by (apt-get install) then there is no longer an issue.

**Comment by NogginBops** [comment]
Good job on finding the issue! Going to close this issue as its not necessarily related to OpenTK.
