### ISSUE TITLE
Cannot publish Hello World application using OpenTK 4.8.0  on Ubuntu 22.04-x64

### ISSUE THREAD

**Issue by dockeratso** [opentk/opentk#1621]
### Description

It is not possible to publish an simple console application using .NET 7.0 with OpenTK 4..8.0

### Repro steps

Setup a Ubuntu 22.04-x64 as a VM or as a wsl (Windows subsystem for Linux).
Install dotnet 7

Create a console application as follows:

dotnet new console --name TestOpenTK
cd TestOpenTK
dotnet add package OpenTK --version 4.8.0

Copy the following into the Program.cs file:

using OpenTK.Windowing.Desktop;
using (var window = new GameWindow(new GameWindowSettings(), new NativeWindowSettings()
{
StartVisible = false,
}))
{
}

Publish the application to produce binary executable:

dotnet publish -c Release -r ubuntu.22.04-x64

### Expected behavior

No errors. A correct built and published application

### Actual behavior

Error with conflict:

dotnet publish -c Release -r ubuntu.22.04-x64
MSBuild version 17.6.8+c70978d4d for .NET
  Determining projects to restore...
  Restored /mnt/c/Users/scienta/Downloads/TestOpenTK/TestOpenTK.csproj (in 1.63 sec).
/snap/dotnet-sdk/216/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1156,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/mnt/c/Users/scienta/Downloads/TestOpenTK/TestOpenTK.csproj]
  TestOpenTK -> /mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Release/net7.0/ubuntu.22.04-x64/TestOpenTK.dll
/snap/dotnet-sdk/216/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /home/scienta/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/libglfw.so.3.3, /home/scienta/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/wayland/libglfw.so.3.3. [/mnt/c/Users/scienta/Downloads/TestOpenTK/TestOpenTK.csproj]

### Related information 

There is no problem to build for another target like Windows 10:
dotnet publish -c Release -r win10-x64

See log:

dotnet publish -c Release -r win10-x64
MSBuild version 17.6.8+c70978d4d for .NET
  Determining projects to restore...
  Restored /mnt/c/Users/scienta/Downloads/TestOpenTK/TestOpenTK.csproj (in 1.82 sec).
/snap/dotnet-sdk/216/sdk/7.0.306/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1156,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/mnt/c/Users/scienta/Downloads/TestOpenTK/TestOpenTK.csproj]
  TestOpenTK -> /mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Release/net7.0/win10-x64/TestOpenTK.dll
  TestOpenTK -> /mnt/c/Users/scienta/Downloads/TestOpenTK/bin/Release/net7.0/win10-x64/publish/

**Comment by dockeratso** [comment]
It is still not possible publish the project above using dotnet 8.

 dotnet publish -r ubuntu.22.04-x64
MSBuild version 17.7.0+5785ed5c2 for .NET
  Determining projects to restore...
  Restored /home/scienta/testar/TestOpenTK/TestOpenTK.csproj (in 240 ms).
/home/scienta/dotnet/sdk/8.0.100-preview.6.23330.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/scienta/testar/TestOpenTK/TestOpenTK.csproj]
  TestOpenTK -> /home/scienta/testar/TestOpenTK/bin/Release/net8.0/ubuntu.22.04-x64/TestOpenTK.dll
/home/scienta/dotnet/sdk/8.0.100-preview.6.23330.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /home/scienta/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/libglfw.so.3.3, /home/scienta/.nuget/packages/opentk.redist.glfw/3.3.8.38/runtimes/linux-x64/native/wayland/libglfw.so.3.3. [/home/scienta/testar/TestOpenTK/TestOpenTK.csproj]

**Comment by dockeratso** [comment]
This problem is related to the snap version of dotnet. See issue: https://github.com/dotnet/runtime/issues/89471
If dotnet is installed by (apt-get install) then there is no longer an issue.

**Comment by NogginBops** [comment]
Closing this issue as its not directly a OpenTK issue.
