### ISSUE TITLE
OpenTK 4.8, elusive InvalidOperationException

### ISSUE THREAD

**Issue by mludlum** [opentk/opentk#1630]
### Description
I'm requesting guidance to troubleshoot an InvalidOperation error.  I'm at a loss on what's causing the error and how to find the real issue.  My DebugMessageCallback isn't called.  

I have an OpenTK 4.8 Windows Desktop application that displays text and graphics.  I'm using VAOs.   A few simple shaders (some with textures).   There can be 1-3 windows using GLControl, but usually two.   I'm calling GL.GetError() after every GL call.  We have several installations of this application and on a few of them, I get and InvalidOperation error.  This can happen on a BindBuffer or BindVertexArray call.

I can never reproduce the error on my Windows 11, RTX 2070 Super development machine.  It seems to happen on machines with integrated graphics.   

### Related information 

* Operating system:  Windows 10 or 11
* SDL or Native backend (if using OpenTK 3.x)
* What version of OpenTK (Installer, NuGet, Source Code):  OpenTK 4.8
* What runtime (.NET Framework, CoreCLR, Mono)
* Workarounds (if any)

**Comment by jvbsl** [comment]
Do you have multiple threads e.g. one thread per window message loop? And do they share any OpenGL resources? I had something similar in the past which was only problematic on windows while using OpenGL context sharing. Where at random times while updating vaos and vbos I got an exception (can't quite remember what exception it was exactly). Perhaps important is that my contexts changed threads.
I did not find any great solution except doing thread synchronization by keeping my contexts on one thread each and never switching the thread a context is on. The synchronization between the threads was then done manually

**Comment by mludlum** [comment]
The application has a ton of threads from async methods, background services, etc.  But for the GLControl, I do all of my GL calls from the paint method.  I will look to see if I have any async calls from there.  That would probably cause the issue.  Thanks.

**Comment by jvbsl** [comment]
It would be especially interesting if the threads of your different GL-control paint methods are different. And if each GL Control has a different context. Best would be ofc. if you could get a minimal example to run, which has the same exception.

**Comment by mludlum** [comment]
I seem to have fixed this by putting a mutex around all of my code that used GL.MakeCurrent.  I assumed that each window had it's own context and that it was thread safe in that respect.

**Comment by NogginBops** [comment]
Making a context current is not a thread-safe operation (which is kind of unintuitive at first), you need to sync that between threads yourself.
