### ISSUE TITLE
Is there any external debugging software available to debug OpenTk 3D application?

### ISSUE THREAD

**Issue by YamingZ** [opentk/opentk#1633]
I've tried RenderDoc, but it doesn't work for debugging OpenTK 3D applications.
Could you give me some recommendations?

**Comment by jvbsl** [comment]
It works for me on Linux and Windows. Did you use Renderdoc using other applications before, or is it your first time? Because imho is the usage of rd a little bit finicky.
What OS are you on? Which OpenTK version? How does the not working part manifest in Renderdoc?

**Comment by NogginBops** [comment]
Renderdoc should work fine for debugging OpenTK applications, I've done it on both windows 10 and Linux.

There are other GPU vendor specific programs like Nvidia night, but renderdoc is generally easier to use

**Comment by NogginBops** [comment]
Going to close this due to inactivity. If this is somehow an issue you can either reopen this issue with more details so we can figure out how to get renderdoc working, or you can open a new issue for it.
