### ISSUE TITLE
Typo in `RenderFrequency` deprecation message

### ISSUE THREAD

**Issue by NoneGiven** [opentk/opentk#1635]
The string is "Use UpdateFrame instead. We no longer separate UpdateFrame and RenderFrame."

I think it should say "Use UpdateFrequency" instead of "Use UpdateFrame."

For comparison, the deprecation message on `RenderTime` is "Use UpdateTime instead. We no longer separate UpdateFrame and RenderFrame."

**Comment by NogginBops** [comment]
Thanks for opening this issue!

Yeah, this was a typo that slipped into the `4.8.0` release.
Will have this fixed for `4.8.1`.

**Comment by postmeback** [comment]
Hey, I have created a PR for this. Would request to have a look.
