### ISSUE TITLE
Setting WindowState in code fires OnResize before WindowState property changes

### ISSUE THREAD

**Issue by MV10** [opentk/opentk#1640]
Just as the subject indicates, the `OnResize` event fires while `WindowState` still reflects the _previous_ state.

Tested in OpenTK 4.8.0.

I added a simple toggle in `OnUpdateFrame` between `WindowState.Normal` and `WindowState.Fullscreen` and wrote a console message, and also wrote a message for the `OnResize` state and event args. The first line is program startup, which is fine. You can see in the second set that the resize has taken place, but `WindowState` is still set to `Normal`, and similarly, on the toggle back to windowed mode on the third set, the state doesn't change before the event is called.

```
OnResize, WindowState Normal, size (960,540).

Changing WindowState to Fullscreen.
OnResize, WindowState Normal, size (3840,2160).

Changing WindowState to Normal.
OnResize, WindowState Fullscreen, size (960,540).
```

However, minimize / maximize (using the title bar buttons) does seem work as expected:

```
OnResize, WindowState Minimized, size (0,0).

OnResize, WindowState Normal, size (960,540).

OnResize, WindowState Maximized, size (3840,2041).
```

I haven't looked at the code behind the `WindowState` property, but because `Normal` from the title bar buttons works, I suspect it's some sort of sequence-of-events problem in the setter. (Wild guess.)

**Comment by NogginBops** [comment]
A fix for this has been released in `4.8.1`.
