### ISSUE TITLE
[Open TK 4] Platform Detection issue for Android (& IOS?)

### ISSUE THREAD

**Issue by Mrcubix** [opentk/opentk#1645]
### Description

Currently, Only OpenGL is known to work Android, The same can't be said about OpenCL & OpenAL, which currently encounter an error while trying to differentiate between a normal linux system & Android.

An exception is occurring during the library name resolving process of the 2 mentioned librairies.
It is difficult to exactly differentiate these 2 platforms without the use of a more up to date SDK (at Least .NET 5), but this isn't exactly a possibility here.

### Repro steps

1. Build an app, destined to run on android (for example, an avalonia.xplat template)
2. Attempt to use any of the OpenAL functions.
3. An exception occur due to the platform being unknown.

### Expected behavior

Android should either be detected as its own platform.

### Actual behavior

An Exception occur trying to differentiate between a normal linux system & Android.

### Related information 

* Version of OpenTK : Nuget (OpenTK 4.7.7)
* Runtime : .NET 7

Here is an example of the content of `RuntimeInformations` on an Android device :

![image](https://github.com/kcat/openal-soft/assets/39861216/a0d06fc6-2f56-4515-9a48-3c0061c83f79)

Ignore the presence of `RuntimeIdentifier`, only present since .NET 5.

As you can see, it does not contain the necessary information to differentiate between the 2 platforms.
Therefore a choice is in order to figure out how this case should be handled.

### Possible fixes

Currently, there are ~2~ a possibility~ies~:

- Check for the presence of the `/system/build.prop` file, which should be doable without root privileges.
- ~Remove this check altogether, making it consistent with the OpenGL wrapper.~

There could be a third possibility, probably through abstraction, by allowing users to inherit a parent or default resolver and and overriding the necessary properties and functions. Whether .NET would allow such a thing has to be seen.

Implementation of Possibility 1 :

```cs
public string Android => "libopenal.so";

public string GetLibraryName()
{
    if (File.Exists("/system/build.prop")) // Android
    {
        return Android;
    }
    else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
    {
        return Linux;
    }
    ...
    else
    {
        throw new NotSupportedException($"The library name couldn't be resolved for the given platform ('{RuntimeInformation.OSDescription}').");
    }
}
```

**Comment by xingyun86** [comment]
> ### Description
> 
> Currently, Only OpenGL is known to work Android, The same can't be said about OpenCL & OpenAL, which currently encounter an error while trying to differentiate between a normal linux system & Android.
> 
> An exception is occurring during the library name resolving process of the 2 mentioned librairies. It is difficult to exactly differentiate these 2 platforms without the use of a more up to date SDK (at Least .NET 5), but this isn't exactly a possibility here.
> ### Repro steps
> 
>     1. Build an app, destined to run on android (for example, an avalonia.xplat template)
> 
>     2. Attempt to use any of the OpenAL functions.
> 
>     3. An exception occur due to the platform being unknown.
> 
> 
> ### Expected behavior
> 
> Android should either be detected as its own platform.
> ### Actual behavior
> 
> An Exception occur trying to differentiate between a normal linux system & Android.
> ### Related information
> 
>     * Version of OpenTK : Nuget (OpenTK 4.7.7)
> 
>     * Runtime : .NET 7
> 
> 
> Here is an example of the content of `RuntimeInformations` on an Android device :
> 
> ![image](https://user-images.githubusercontent.com/39861216/269397721-a0d06fc6-2f56-4515-9a48-3c0061c83f79.png)
> 
> Ignore the presence of `RuntimeIdentifier`, only present since .NET 5.
> 
> As you can see, it does not contain the necessary information to differentiate between the 2 platforms. Therefore a choice is in order to figure out how this case should be handled.
> ### Possible fixes
> 
> Currently, there are ~2~ a possibility~ies~:
> 
>     * Check for the presence of the `/system/build.prop` file, which should be doable without root privileges.
> 
>     * ~Remove this check altogether, making it consistent with the OpenGL wrapper.~
> 
> 
> There could be a third possibility, probably through abstraction, by allowing users to inherit a parent or default resolver and and overriding the necessary properties and functions. Whether .NET would allow such a thing has to be seen.
> 
> Implementation of Possibility 1 :
> 
> ```cs
> public string Android => "libopenal.so";
> 
> public string GetLibraryName()
> {
>     if (File.Exists("/system/build.prop")) // Android
>     {
>         return Android;
>     }
>     else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
>     {
>         return Linux;
>     }
>     ...
>     else
>     {
>         throw new NotSupportedException($"The library name couldn't be resolved for the given platform ('{RuntimeInformation.OSDescription}').");
>     }
> }
> ```

Same to me. I use opentk 4.8.0， and I build openal.so with android。But cannot set lib path in apk。

**Comment by NogginBops** [comment]
Moving this to the `4.8.2` milestone so that we can track and verify that this issue actually gets solved by #1646 .

**Comment by Mrcubix** [comment]
Library name still need to not end with .1 to be properly embedded into an android application by xamarin dependent frameworks

**Comment by NogginBops** [comment]
I've changed it to search for `libopenal.so` on android in 6b1ba9d117d5899671b62b87c01bc86499fe5cfb.

We should still document how to get this working somewhere, either we keep this issue open or we can open a separate issue for that. If you are able to write down the steps needed to get OpenAL to work on android that would be great.

**Comment by Mrcubix** [comment]
Seem to be working as intended on android since 4.8.1, closed.

**Comment by XiaofengdiZhu** [comment]
@Mrcubix Hello, Can you tell me how to use OpenGL correctly on Android?  
This is my code:
```csharp
OpenTK.Windowing.GraphicsLibraryFramework.GLFWBindingsContext provider = new();
OpenTK.Graphics.ES30.GL.LoadBindings(provider);
```
The exception:

![Image](https://github.com/user-attachments/assets/604daba7-840f-49ad-8756-9339a6b8972b)
