### ISSUE TITLE
WindowState Fullscreen issues in 4.8.1

### ISSUE THREAD

**Issue by MV10** [opentk/opentk#1647]
Observations testing the #1640 fix (Setting WindowState in code fires OnResize before WindowState property changes):

The startup OnResize fires normally. Switching from Normal to Fullscreen works normally. However, switching back to Normal does not work. The WindowState property changes, but the OnResize event does not change, and the window itself remains in Fullscreen mode. This is my test output, note the lack of OnResize between the last two lines:

```
OnResize ClientSize 960,540  WindowState Normal
OnUpdateFrame changing WindowState from Normal to Fullscreen
OnResize ClientSize 3840,2160  WindowState Fullscreen
OnUpdateFrame changing WindowState from Fullscreen to Normal
  << no OnResize event here, window is still full-screen >>
OnUpdateFrame changing WindowState from Normal to Fullscreen
```

The window titlebar Minimize / Maximize buttons appear to work normally and the property value changes before OnResize is fired. This sequence was various combination of using titlebar buttons only:

```
OnResize ClientSize 960,540  WindowState Normal
OnResize ClientSize 0,0  WindowState Minimized
OnResize ClientSize 960,540  WindowState Normal
OnResize ClientSize 3840,2041  WindowState Maximized
OnResize ClientSize 960,540  WindowState Normal
OnResize ClientSize 3840,2041  WindowState Maximized
OnResize ClientSize 0,0  WindowState Minimized
OnResize ClientSize 3840,2041  WindowState Maximized
OnResize ClientSize 960,540  WindowState Normal
```

However, the sequence of Maximized by button, then Fullscreen by code, then Normal by code, results in a non-maximized window which is missing the window border and title bar, and the WindowState still reflects Fullscreen:

```
OnResize ClientSize 960,540  WindowState Normal
OnResize ClientSize 3840,2041  WindowState Maximized
OnUpdateFrame changing WindowState from Maximized to Fullscreen
OnResize ClientSize 3840,2160  WindowState Fullscreen
OnUpdateFrame changing WindowState from Fullscreen to Normal
OnResize ClientSize 984,587  WindowState Fullscreen
  << window is normal-size/location but without titlebar or border >>
```

**Comment by NogginBops** [comment]
Tested this PR and it works perfectly! 
Thanks for a great PR!
