### ISSUE TITLE
Unable to load openal library when built with nativeaot targeting android

### ISSUE THREAD

**Issue by emmauss** [opentk/opentk#1677]
### Description
Net 8 adds support for android NativeAot using the target linux-bionic-arm64. Though it's running on android, all platform checking api reports as running under linux, and thus opentk native resolvers will attempt to load linux libraries. This throws an error similar to this;
`Unhandled Exception: System.DllNotFoundException: Could not load the dll 'libopenal.so.1' (this load is intercepted, specified in DllImport as 'AL').`
This occured when attempting to load openal on android using a native aot library. The openal library soname and file name is libopenal.so, but resolvers attempt to load libopenal.so.1. I've attempted patching the soname and still throws the same error.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a simple .net class library. Add native exports to call `OpenTK.Audio.OpenAL.ALC.OpenDevice` through jni. Set to publish with native aot.
2. Publish it as a library. simple steps detailed here, https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/android-bionic.md
3. Create an android project in android studio. Create a class to load the build library, and add the built library to the jniLibs. Call the jni imported function in MainActivity.OnCreate

### Expected behavior

OpenAl libraries load. Even if it requires patching the soname

### Actual behavior

App crashes with `Unhandled Exception: System.DllNotFoundException: Could not load the dll 'libopenal.so.1' (this load is intercepted, specified in DllImport as 'AL').`

### Related information 

* Operating system : Android 13
* SDL or Native backend (if using OpenTK 3.x)
* What version of OpenTK (Installer, NuGet, Source Code) : Nuget
* What runtime (.NET Framework, CoreCLR, Mono) :  NativeAOT
* Workarounds (if any)

**Comment by NogginBops** [comment]
What version of OpenTK are you using?

**Comment by emmauss** [comment]
I previously used 4.7.7. I updated to 4.8.1, and tried again. Same crash.
https://github.com/opentk/opentk/blob/19f4e04ee807731138c40e420fb05e753261f4c9/src/OpenAL/OpenTK.Audio.OpenAL/OpenALLibraryNameContainer.cs#L47 . This check is never true when targeting linux-bionic, which nativeaot does for android.

**Comment by NogginBops** [comment]
Implemented a fix in #1683 which allows you do write
```cs
OpenALLibraryNameContainer.OverridePath = "libopenal.so";
```
to overwrite and platform logic (this allows you to supplement or create your own platform logic).
