### ISSUE TITLE
Add support for OpenGL ES 3.2

### ISSUE THREAD

**Issue by Khhs167** [opentk/opentk#1687]
I genuinely think it wouldn't hurt to support OpenGL ES 3.2.

It's been supported on Android since 2016, it's used in game engines like Godot, it actually has an up-to-date API similar to that of OpenGL 3.x(roughly) and should not be overlooked. We also have maintained bindings of OpenGL ES 2 and 1, so I don't see why not.

I know about #443, and I chose to overlook it.

Sorry for the (possible) mess btw...

**Comment by NogginBops** [comment]
Can we clarify what you are asking for. 
If you are looking for the GL ES 3.2 entry points they (should) exist in the bindings (in the `OpenTK.Graphics.ES30` namespace). 
Or are you asking for opengl es context creation support?

**Comment by NogginBops** [comment]
Also it would be good to mention what version of OpenTK you want this for. 3, 4, or 5?

**Comment by Khhs167** [comment]
I noticed that this might be something missing from Silk.NET instead of OpenTK :sweat_smile:

But if something happens to be missing, I'd guess it should be 5? 5 is the next major version, and adding more API support feels like a major addition.

**Comment by NogginBops** [comment]
OpenTK 5 used the latest khronos spec for OpenGL and OpenGL ES. It should contain all entry points that exist in OpenGL.

The most likely case is that OpenTK 4 is missing some of the OpenGL ES 3.1 and 3.2 entry points as pointed out by @BoyBaykiller in the discord. 
I'll look into updating the OpenTK 4 bindings for OpenTK `4.9.0`.
