### ISSUE TITLE
OpenTK.OpenAL 4.8.1 not present on nuget.org

### ISSUE THREAD

**Issue by marysaka** [opentk/opentk#1689]
I noticed that OpenTK.OpenAL wasn't updated for 4.8.1 or 4.8.0.

Would it be possible to get a new release?

This is required for Ryujinx to update to latest of 4.x

**Comment by NogginBops** [comment]
I might have forgotten to write about it in the release notes, but the package has been renamed as `OpenTK.Audio.OpenAL`.

Will see if I can update the release notes on GitHub, and mark the new package as the successor on nuget.

**Comment by marysaka** [comment]
> I might have forgotten to write about it in the release notes, but the package has been renamed as `OpenTK.Audio.OpenAL` (to match the namespace).
> 
> Will see if I can update the release notes on GitHub, and mark the new package as the successor on nuget.

Thank you for the info, will move to it.

**Comment by NogginBops** [comment]
I've added a deprecation message to the last `OpenTK.OpenAL` package with a link to the newer package, this was the best I could do with the tools nuget gives me.
I've also updated the `4.8.0` release notes to also explicitly mention that the nuget package has changed name.
