### ISSUE TITLE
replace all "ref" statement for "in" instead

### ISSUE THREAD

**Issue by caverna** [opentk/opentk#1694]
So far I understood, the plans to use System.Numerics are on hold. But still we can use in an indirect way when setting uniforms variables, using ref statement, like "GL.Uniform3(location, 1, ref value.X);"

The problem is that doesn't play well when you try to use proxy classes to allow unit tests using mock ups.

For example, that's supposed to work, but somehow Moq is not able to match that:
glMock.Setup(x => x.Uniform3(It.IsAny<int>(), It.IsAny<int>(), ref It.Ref<Vector3>.IsAny)).Verifiable();

But instead if "in" statement is used for the function definition, the variable still be used as reference, but as readonly in C#

Since GL class has no need to modify variables, it only makes sense to set is readonly, unless the opengl native calls has limitations.

**Comment by utkumaden** [comment]
The OpenTK3 generator (which OpenTK4 uses) was written when there was no in parameters in C#. Currently there are no plans to update this generator any further. I believe OpenTK5 generators generate not only span overloads but also in parameters.

**Comment by caverna** [comment]
understood, just in case anyone steps on this same situation, this workaroud does the trick:
`        fixed (float* tmp = &value.X)
            GL.Uniform3(location, 1, ref *tmp);`
the only draw back is that you have to set your project as "unsafe"

**Comment by NogginBops** [comment]
You should also be able to use `Unsafe.AsRef<T>(in value)` to get a ref in a simpler way, though it might be worth thinking if its appropriate as you are no longer pinning the object (which may or may not be necessary).

**Comment by NogginBops** [comment]
Closing this issue. In the new bindings generator for OpenTK 5 we do generate `ref` vs `in` parameters where appropriate. So with the workaround and the new bindings generator this should not longer be a problem.
