### ISSUE TITLE
ALSourcei.SourceState missing

### ISSUE THREAD

**Issue by 32BitFelix** [opentk/opentk#1710]
### Description

The enum AL.SourceState is missing.

### Repro steps

1. Open editor

2. Check for ALSourci.SourceState's existence

### Expected behavior

ALSource.SourceSate

### Actual behavior

ALSourcei.SourceState not

### Related information 

* Windows 10
* OpenTK 4.8.1
* NuGet
* .Net Framework

**Comment by NogginBops** [comment]
`ALGetSourcei` contains this enum. As this enum value can only be used in `AL.GetSource`.

The documentation is referencing the wrong function and enum. Will fix that.
