### ISSUE TITLE
Creating Opengl 2.0 Context is not supported but why?

### ISSUE THREAD

**Issue by 1ner1** [opentk/opentk#1726]
I used this library in 2020 when I last used it I was able to create Opengl 2.1 contexts and use the fixed function pipeline functionality.
FFP is really useful for visual debugging it's a huge time saver for quick debugging (eg: Testing Model Loading, Animations and as a fallback just in case if Modern Opengl is somehow now available) then it can be yanked off from the project.

Using

```cs
        APIVersion = new Version(3, 2),
        Profile = ContextProfile.Compatability
```
 
 Does not crash unlike using 2.0 which brings up super confusing error me ssage " Forward-compatibility is only defined for OpenGL version 3.0 and above" from GLFW and attempting to do use anything else is not possible, it's really messy sitation.
 
 But by using 3.2 there's still a problem
 
 Anything that involves FFP returns Invalid Operation reproduction steps are simple
 
 
 create a new blank project
 
 set api version to 3 2
 enable compatibility mode
 attempt to draw a triangle
use GL.GetError

observe the InvalidOperation

The documentation states Opengl 2.0 is not supported but what changed in the time? Why it cannot be supported?

**Comment by NogginBops** [comment]
In OpenGL versions before 3.1 there is no concept of "profiles" so to create a context with a lower version you need to specify ```cs
Profile = ContextProfile.Any.
Flags = ContextFlags.Default, // This is important as it defaults to ForwardCompatible which isn't defined in OpenGL 2.0.
```.

To create a 3.2 context with compatibility features enabled (i.e. fixed-function and immediate mode) you need to set the following setttings:
```cs
Version = new Version(3, 2),
Profile = ContextProfile.Compatibility,
Flags = ContextFlags.Default, // This is important as it defaults to ForwardCompatible which disables deprecated legacy features. 
```
