### ISSUE TITLE
Update OpenTK 5 to use .NET 8

### ISSUE THREAD

**Issue by BoyBaykiller** [opentk/opentk#1728]
### Description

.NET 8 ist the newest LTS release so we should use that for OpenTK 5.
It's currently using .NET 7.

**Comment by NogginBops** [comment]
Some of the newest branches/PRs for OpenTK 5 use .net 8. I just haven't put in the time to make the build system to be compatible with .net 8, but I'm probably going to soon.

**Comment by NogginBops** [comment]
This is apparently not possible due to issues with FAKE, see https://github.com/fsprojects/FAKE/pull/2776

**Comment by NogginBops** [comment]
Ok I was able to get something working in https://github.com/opentk/opentk/pull/1714/commits/39c1743091ae2e66f2e5e0e9b51f5c59e1d224db I think. But the `paket` version that FAKE uses doesn't know how to parse `.net8.0` so it's not able to create nuget packages using .net8.0.

**Comment by NogginBops** [comment]
This is fixed with #1714
