### ISSUE TITLE
Comments do not match implementation for Matrix4.Rotation* functions

### ISSUE THREAD

**Issue by Xerxes004** [opentk/opentk#1729]
https://github.com/opentk/opentk/blob/38d4e664ef69633657ec2598779d99256163b6d1/src/OpenTK.Mathematics/Matrix/Matrix4.cs#L886

As seen in the snippet above, the rotation matrices generated perform a clockwise rotation, not a counter-clockwise one.

This same error occurs for the X and Y rotations as well.

To reproduce, draw a line using this transformation:

```C#
Matrix4.CreateRotationZ(MathF.PI / 4f)
```

**Comment by Xerxes004** [comment]
Note, changing the code to match the comment would produce a breaking change. The comments should probably just be updated to reflect the code, instead.

**Comment by NogginBops** [comment]
Are you sure you are actually getting a clockwise rotation? In default OpenGL the Z axis is oriented towards the camera (-Z is forward) so riding counter clockwise around positive Z would result in a clockwise rotation viewed from the camera.

**Comment by Xerxes004** [comment]
If +Z is towards the viewer and -Z is towards the screen, then I'm pretty sure the implementation does not match the comments.

Unless I'm reading something wrong, the Z matrix created here is not what I would have expected.

This is the implementation of CreateRotationZ for example:

https://github.com/opentk/opentk/blob/38d4e664ef69633657ec2598779d99256163b6d1/src/OpenTK.Mathematics/Matrix/Matrix4.cs#L888-L898

This is from the Learn OpenGL site:
![image](https://github.com/user-attachments/assets/29354dd4-696a-4b89-87f1-21223db1623a)

**Comment by Xerxes004** [comment]
*(I deleted my previous message just to triple check the rotation matrix stuff).*

I am using the default camera position, so -Z should be away from me, towards the screen, right?

Regardless, unless I'm missing something, the code doesn't seem to match the rotation matrices I would expect.

Here's the code:

https://github.com/opentk/opentk/blob/38d4e664ef69633657ec2598779d99256163b6d1/src/OpenTK.Mathematics/Matrix/Matrix4.cs#L888-L898

And here is a snippet from Wikipedia on what that matrix should look like for counter-clockwise rotation:

![image](https://github.com/user-attachments/assets/22c327c4-78f7-4d75-90d8-105acfaf0830)

**Comment by NogginBops** [comment]
Sorry for not replying for a little bit.
OpenTK math follows the DirectX tradition of row-major matrices, with row vectors and "pre-multiplication" (I.e. left-to-right multiplication). This is results in OpenTK matrices being the transpose of what you would normally see in math, this is why the `-sin θ` and `sin θ` are switched.

**Comment by Xerxes004** [comment]
Ok, that would make sense as far as the code is concerned. But if the positive Z axis is towards the viewer (i.e. straight out from the screen), then I still think I am misunderstanding something. When I get some time, I will make a small example to make sure I have this right in my head.

**Comment by Xerxes004** [comment]
I was able to recreate the bug here:

https://github.com/Xerxes004/GLWpfControl/tree/rotation_test

You may need to change the project file for your environment; I had to change it to `net8.0-windows` for mine.

**Comment by NogginBops** [comment]
@Xerxes004 Sorry for not answering earliner.

> `gl_Position = transform * vec4(vPosition, 0, 1);`

This is the issue in your project, as I said OpenTK does "pre-multiplication" or left-to-right multiplication of matrices.
The correct line would be `gl_Position = vec4(vPosition, 0, 1) * transform;` which results in the correct rotation.

**Comment by NogginBops** [comment]
I figured out the issue. I was forgetting that the default you often in OpenGL use two different coordinate spaces, one is NDC (normalized device coordinates) which is a left-handed coordinate system as seen in the right of the image below.
But then there is the "camera space" which has a convention of -Z being forward, and I was confused thinking this was the normal as that is what you almost always work with (as seen in the left of the image).

So in our case we expect it to rotate counter clockwise as we are not using a projection matrix, so the Z axis is forward.
![image](https://github.com/user-attachments/assets/dc678e12-f458-4f6f-8763-30e88ea4f60c)
https://www.songho.ca/opengl/gl_projectionmatrix.html

**Comment by Xerxes004** [comment]
Thank you for the explanation, that makes a lot of sense. I have been using a right-hand system for all of my elements, so I should be able to fix everything by projecting into the left hand system.
