### ISSUE TITLE
Missing 3.3.1 Tag & Release

### ISSUE THREAD

**Issue by ClaudiusR** [opentk/opentk#1737]
Hi,
I cannot find the Source Code related to https://www.nuget.org/packages/OpenTK/3.3.1

Would it be possible to add it?

**Comment by NogginBops** [comment]
This seems like the commit where the 3.3.1 was released. https://github.com/opentk/opentk/commit/24963ed3ab63e76ffb81a797cc8dc7e9a8143213

I'll create a release and tag for it when I'm at my computer.

**Comment by ClaudiusR** [comment]
Thank you very much, this would help a lot! 👍

**Comment by NogginBops** [comment]
I've added the tag and release here: https://github.com/opentk/opentk/releases/tag/3.3.1
