### ISSUE TITLE
.NET 8.0 MacOS app frameworks linking error

### ISSUE THREAD

**Issue by Dobowicz** [opentk/opentk#1743]
### Description

I have a .net8.0 MacOS app project to which I want to add OpenTK now to generate some pictures in the background. I have added OpenTK 4.8.2 NuGet package to it, but when I try to build the app I get the libraries linking error.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create .net8.0-macos app project
2. Add OpenTK 4.8.2 NuGet package
3. Try to build the project

### Expected behavior

The app should be built.

### Actual behavior

Build error is encountered:
```
10>Xamarin.Shared.Sdk.targets(1641,3): Error  : clang++ exited with code 1:
ld: framework not found OpenGLES
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Related information 

* Operating system: MacOS 14.6
* OpenTK 4.8.2 from NuGet
* .NET 8.0
* The only workaround I could find was to remove OpenGLES entry from `obj/Debug/net8.0-macos/osx/linker-items/_LinkerFrameworks.items`file, but it is regenerated after every clean of project

**Comment by NogginBops** [comment]
Ok, I think I have narrowed this down to us using `DllImport("libGLESv2")` in our bindings which is triggering the macos workload to add `OpenGLES` to the linker frameworks. Not sure exactly what we can do about this atm, but I will continue experimenting at a later time. 

Some links:
https://l.messenger.com/l.php?u=https%3A%2F%2Fgithub.com%2Fxamarin%2Fxamarin-macios%2Fblob%2Ff36102ace3aab48849f61089876e602ca5f8e5bb%2Ftools%2Fcommon%2FAssembly.cs%23L570C12-L570C21&h=AT1vPoPsQPw1rwESscMrtNxOTnEO64a0xLfdjsft8wLPj9wkNURWZqJvaTUwO5c-vz0v-O4sl3mwmb7tdxv0mnU_iVUWL2ITmPbjsnWPIMuQmobHr6SIbSZWMYojqfv4Q7tsdQ

**Comment by NogginBops** [comment]
Another potential hint here is that this is only triggered if OpenTK is referenced as a nuget package, using a `<ProjectReference />` doesn't trigger this error.

**Comment by NogginBops** [comment]
I have found this workaround for now. Adding this to the csproj should allow you to build the project without manually having to remove the `_LinkerFrameworks.items` item for OpenGLES.
```xml
<Target Name="RemoveOpenGLES" BeforeTargets="_ComputeLinkNativeExecutableInputs" AfterTargets="_LoadLinkerOutput">
    <ItemGroup>
        <_LinkerFrameworks Remove="OpenGLES" />
    </ItemGroup>
</Target>
```

**Comment by NogginBops** [comment]
Ok, it seems like this issue arrises from the binder generating code with `DllImport`s with references to `libGLESv2.dll` which then gets removed in the re-writer step. But it seems like the rewriter doesn't remove the module references from the rewritten dll..

Not sure what it will break if we remove these module references, but it's worth a try.
