### ISSUE TITLE
Unable to start a NativeWindow hidden on MacOS

### ISSUE THREAD

**Issue by crackstin** [opentk/opentk#1745]
### Description

When creating a window with IsVisible set to false, a window appears, similar to #1632, but as far as I can tell the cause is unrelated. I'm unsure as to how I could provide more information as everything executes as expected when I stepped through with a debugger, even tested setting the window hint natively with C++/GLFW 3.3.4 and it worked.

### Repro steps

```
NativeWindow w = new NativeWindow(new NativeWindowSettings() { APIVersion = new Version(4, 1), StartVisible = false });
Console.Writeline(w.IsVisible);
while (!w.IsExiting) GLFW.WaitEvents();
```

### Expected behavior

The window should not be visible and the console should print False.

### Actual behavior

The console prints False, but the window is visible.

### Related information 

* MacOS 14.5 on Intel Processor
* OpenTK 4.8.2
* .NET 6.0
* Jetbrains Rider 2024.1.2

**Comment by NogginBops** [comment]
This seems to be caused by this GLFW bug: https://github.com/glfw/glfw/issues/1300
