### ISSUE TITLE
StrongName this library

### ISSUE THREAD

**Issue by RFBomb** [opentk/opentk#1754]
### Description

This library does not appear to be strongnamed. As such, no application that requires strong naming (or any library that wants to be strong named) can reference this. 

Case in point, ScottPlott can not strong name the WPF library because this is not strong named.
https://github.com/ScottPlot/ScottPlot/pull/4295

```
ScottPlot -> /home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5/bin/Release/net6.0/ScottPlot.dll
CSC : error CS8002: Referenced assembly 'GLWpfControl, Version=4.2.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF_nrhcqgoa_wpftmp.csproj::TargetFramework=net6.0-windows]
CSC : error CS8002: Referenced assembly 'OpenTK.Mathematics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF_nrhcqgoa_wpftmp.csproj::TargetFramework=net6.0-windows]
CSC : error CS8002: Referenced assembly 'OpenTK.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF_nrhcqgoa_wpftmp.csproj::TargetFramework=net6.0-windows]
CSC : error CS8002: Referenced assembly 'GLWpfControl, Version=4.2.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj::TargetFramework=net6.0-windows]
CSC : error CS8002: Referenced assembly 'OpenTK.Mathematics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj::TargetFramework=net6.0-windows]
CSC : error CS8002: Referenced assembly 'OpenTK.Graphics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name. [/home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/ScottPlot.WPF.csproj::TargetFramework=net6.0-windows]
  ScottPlot.WPF -> /home/runner/work/ScottPlot/ScottPlot/src/ScottPlot5/ScottPlot5 Controls/ScottPlot.WPF/bin/Release/net6.0-windows/ScottPlot.WPF.dll
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Attempt to use this in an application that is strongly named.
2. Application crash due to this not being strong named.

### Workarounds (if any)
- Don't strong name the application (this is problematic for ClickOnce)
- Dev Strong name it themselves by duplicating the repo and including it in your project structure or internal nuget server
- Work around the issue using an external signer, such as https://brutaldev.com/post/net-assembly-strong-name-signer 

### Discord Discussion Summary :

- Not high priority, but potentially feasible.
- Would have to verify it plays nice with the assembly-rewriting during build process and any old signing code
- Needs more support before looking into this 

I'm OK using workaround signing for now, as its a small user-base application with dev team of 1.

**Comment by RFBomb** [comment]
See #1755

**Comment by NogginBops** [comment]
We usually keep the issue open until the pr has been merged.

**Comment by RFBomb** [comment]
Wow, I haven't had a chance to look at this, but I saw you working on it. Great work, I had gotten pulled onto other things (and wasn't sure best way to continue after I got a roadblock). 

Much appreciated for looking at this!
