### ISSUE TITLE
[5.0] Don't use `ref readonly` paramter for singularized functions like `DeleteVertexArray(ref readonly int array)`

### ISSUE THREAD

**Issue by BoyBaykiller** [opentk/opentk#1756]
### Description

Singuralized functions like GL.DeleteVertexArray, GL.DeleteBuffer, GL.DeleteFramebuffer generated by OpenTK currently take in the GL-name as a `ref readonly` paramter because the plural counterparts also do. This requires the user to add `in` or `ref` on the callsite for no reason. OpenGL delete functions like `GL.DeleteProgram` also take by balue. So we should probably pass by value too. Before 5.0-pre.12 this wasn't an issue because we used `in` instead, which doesnt require any attributes on the callsite.

User currently gets this warning when trying to pass by value.
![image](https://github.com/user-attachments/assets/12b188e9-b650-438d-aea4-8c04a8a66b9c)

### Related information 
OpenTK 5.0-pre.12

**Comment by Lancelotbronner** [comment]
This also prevents using readonly fields to store handles.
