### ISSUE TITLE
strange opentk 4.9.1 nuget package contents (OpenTK.Graphics.4.8.2 - Copy.zip)

### ISSUE THREAD

**Issue by AlexandreAlison** [opentk/opentk#1780]
Hello,

I updated the OpenTk nuget packages to version 4.9.1 in our software  and had an error:
![image](https://github.com/user-attachments/assets/0d6154f5-fcef-47e5-84e1-2feaca124dcb)

I was trying to solve the issue but I found this :
![image](https://github.com/user-attachments/assets/73d1e867-63c1-4353-be96-1edd40f9e7ab)
![image](https://github.com/user-attachments/assets/d2b90c61-d023-4fee-bfae-b7f9aa1e59d8)
![image](https://github.com/user-attachments/assets/fbd0b231-79f6-4899-b810-20a201dbf5e6)

this zip file is probably not needed.

Best Regards

Alex

**Comment by NogginBops** [comment]
Thanks for reporting this. I had some troubles when creating the nuget package for `4.9.0`, and apparently some of those issues make it into `4.9.1`.
I'll release `4.9.2` were I fix the nuget package to remove this file.

**Comment by NogginBops** [comment]
Though looking at the error I'm not sure this file is what is causing it... 
The zip file in the `OpenTK` package shouldn't be used for anything, so the error you are getting is likely unrelated to the zip file. I think...

**Comment by AlexandreAlison** [comment]
no the issue is no related to this 

thanks

**Comment by NogginBops** [comment]
Yeah, something related to the signing of the packages seems more likely to be the problem.
How are you referencing the `OpenTK` package? `<PackageReference>`?
Are you combining `4.9.1` and `4.8.2`?

**Comment by AlexandreAlison** [comment]
not directly 
![image](https://github.com/user-attachments/assets/cf6d500d-ab74-4214-9d1f-4fa5a5fd67f9)

**Comment by NogginBops** [comment]
Ok, so you are only referencing `OpenTK.GLControl`? Then you should be getting `OpenTK 4.8.2` though?

**Comment by NogginBops** [comment]
I tried making a winforms project and added `OpenTK.GLControl` `4.0.1` to it and it seemed like there was an initial issue where I wasn't able to add the control through the designer, but I was able to add it through code and start the project that way.
After I had gotten the program to start once, I was able to add the GLControl through the designer.

**Comment by NogginBops** [comment]
I'm going to release `4.9.2` now, it will remove the erroneous zip file in the nuget package, but I'm not sure it will fix this issue specifically.
I think this is more likely a `GLControl` issue, so if you could open a separate issue there that would be good: https://github.com/opentk/GLControl

**Comment by NogginBops** [comment]
Ok, I'm able to reproduce this issue!
It seems like using `OpenTK.GLControl/4.0.1` with `OpenTK/4.9.2` causes the error.

**Comment by NogginBops** [comment]
My guess is that this has to do with `OpenTK.GLControl` not knowing about the signed `4.9.2` assemblies, or something like that.
Will make a new OpenTK.GLControl release and see if that works.

**Comment by NogginBops** [comment]
Ok @AlexandreAlison, I've found a workaround.
Adding `<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />` to your project will fix this issues for `4.9.1` and `4.9.2`.
I think this has something to do with the deprecation of the `5.0.0` version of the `System.Runtime.CompilerServices.Unsafe` package causing weirdness in the package resolution logic.

Will see if I can make a proper fix soon.

**Comment by AlexandreAlison** [comment]
that s also my guess. Thanks a lot.

**Comment by AlexandreAlison** [comment]
(as info I opened https://github.com/opentk/GLControl/issues/41)

**Comment by NogginBops** [comment]
@AlexandreAlison just to confirm, in `4.9.2` the zip file is not longer in the `OpenTK` package right?
If that is the case then I think we can close this issue and keep https://github.com/opentk/GLControl/issues/41 open.

**Comment by AlexandreAlison** [comment]
![image](https://github.com/user-attachments/assets/7028c6ec-b77a-41a4-b0de-0f30d16c6e5e)

yes this is solved. This ticket can be closed. Thanks
