### ISSUE TITLE
X11 in combination with GLES (EGL) does not work (DllNotFoundException libGL.so.1)

### ISSUE THREAD

**Issue by maaikel** [opentk/opentk#183]
When running on Linux Enlightenment with only GLES (EGL) I cannot create a GameWindow with the Embedded flag. 
Glx is used which is dependent on libGL.so.1. libGL.so.1 is not supported in an environment with only GLES. 

EglX11PlatformFactory base class is X11Factory
The CreateNativeWindow function create's a X11GLNative instance. 
X11GLNative uses the X11GraphicsMode which uses the Glx class.

**Comment by maaikel** [comment]
Has this issue ever been fixed? Is there a new release available?

**Comment by daerogami** [comment]
Closed due to age.
