### ISSUE TITLE
Windows 8.1 - Cursor & GameWindow Issues

### ISSUE THREAD

**Issue by SK83RJOSH** [opentk/opentk#184]
On Windows 8.1 (not sure about other Windows versions), there seems to be an issue with the cursor when deselecting a window.

Here's a good [post](http://www.opentk.com/node/3787) about how to reproduce the issue.

My steps are as follows:
- In Visual Studio create a new (console) project
- Use NuGet to add OpenTK as a dependency (Using .Net 4.0)
- Create a new GameWindow without changing any of it's attributes
- Run the application, and deselect the window by selecting another application

The cursor should stick to the native window, and in some cases, the window won't even lose focus.

[Example video](https://dl.dropboxusercontent.com/u/17381137/ShareX/2014/09/2014-09-26_04-53-28.webm)

As the OpenTK forum post suggests, this issue seems to have something to do with SDL. Although I haven't been able to correct the problem by adding SDL to my output directory. So I suspect there are some other factors at play.

It's also worth noting that different WindowBorder states don't seem to work on 8.1 either. Including Hidden and Fixed, hidden results in a window with no controls, and fixed results in a normal window.

![Hidden result](http://i.imgur.com/JKfbfsy.png)

**Comment by varon** [comment]
Closing since it's from 2014.
