### ISSUE TITLE
GameWindow.ProcessEvents() does not prevent window from being marked busy if called on a different thread than where the GameWindow was created.

### ISSUE THREAD

**Issue by LaylConway** [opentk/opentk#189]
I've got a system where I have to create the game window on a different thread than where ProcessEvents will be called. This causes the window to remain marked busy. OpenGL rendering does however work on this separate thread.

**Comment by Frassle** [comment]
#193 merged. You'll get an exception if you attempt this now, making clear that this is not supported.

**Comment by LaylConway** [comment]
Sorry for not verifying back when you made the pull request, I must have missed the notification.
