### ISSUE TITLE
No way to set WGL_SWAP_METHOD_ARB

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#191]
As described in http://www.opentk.com/node/3829.

We need a way for the user to specify what swap mode they want to use. This probably has related concepts in the other platforms we support not just WGL.

We could either define a new platform agnostic swap parameter to display mode that we then translate to the platform dependent code, or add a way to pass platform specific parameters from display mode to the platform.

**Comment by daerogami** [comment]
Closed due to age.
