### ISSUE TITLE
Dragging/resizing window freezes rendering/updates

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#196]
From [forum post](http://www.opentk.com/node/3838):

> When dragging the window on Windows the program basically freezes (this is due to Win32's annoying model loop). I thought this was fixed here http://www.opentk.com/node/1218
> 
> I can upload code to the way my prototype SharpDX implementation handles rendering. It looks out for special SYSCOMMAND messages, this message is received before the 500ms delay of ENTERSIZEMOVE. When a specific range of SYSCOMMAND messages are received I start a System.Windows.Forms.Timer to provide temporary rendering/update looping since the normal looping would now be blocked (although is slower, but that doesn't matter as long as the game is still updating fast enough). Once the model loop ends, the normal render loop should be able to continue again, inside the normal loop is checks to see if the timer is ticking and disables it.
> 
> I am on x64 Windows 8.1 Pro and just using OpenTK.dll (no other dependencies).

**Comment by RyanJEC** [comment]
any updates on this?

**Comment by varon** [comment]
No idea, we'll need a PR here.
