### ISSUE TITLE
No way to check if a window has been maximized during an OnResize event

### ISSUE THREAD

**Issue by OverworldTheme** [opentk/opentk#198]
In WinForms, when a window has been maximized, the WindowState value will be set to FormWindowState.Maximzed before invoking the OnSizeChanged event.

Currently, as far as I can tell there's no way to check for this in an OpenTK GameWindow. OnResize is called before OnWindowStateChanged, and the WindowState value is not updated until after OnResize has been called.

**Comment by daerogami** [comment]
I intend on testing these behaviors to see if anything has changed; however, I only have a Windows 10 machine and an Ubuntu 16 server currently at my disposal. Recent tests (similar to those above) from other platforms would be greatly appreciated.

**Comment by varon** [comment]
Issue from 2014. Closing. Re-open if you need it.
