### ISSUE TITLE
CompressedTexSubImage2D should use InternalPixelFormat.

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#203]
[Forum post](http://www.opentk.com/node/3852)

CompressedTexSubImage2D's format parameter should be PixelInternalFormat not PixelFormat.

**Comment by daerogami** [comment]
> Hi
> I'm trying to upload compressed textures to another, larger compressed texture using CompressedTexSubImage2D, but I'm getting an Invalid_enum error. The only good examples I can find of doing this specify a format in the tex sub image call equal to the internal format of the large texture. In my case, this should be CompressedRgbaS3tcDxt5Ext. However PixelFormat doesn't contain a value for compressed texture formats, so I'm assuming that that is the cause for the invalid enum.
> Currently my code for uploading looks like this:
> GL.CompressedTexSubImage2D(TextureTarget.Texture2D, 0, (int)tilePosition.X, (int)tilePosition.Y, _tileSize, _tileSize, PixelFormat.Rgba, data.Length, data);
> which doesn't work. I would expect to be able to specify the following:
> GL.CompressedTexSubImage2D(TextureTarget.Texture2D, 0, (int)tilePosition.X, (int)tilePosition.Y, _tileSize, _tileSize, PixelInteralFormat.CompressedRgbaS3tcDxt5Ext, data.Length, data);
> Should it be possible to specify a compressed texture format in this call?
> Thanks
> -BraveSirAndrew

> Hmm this looks like an API bug. Easy workaround is to just use the InternalPixelFormat enum and cast it to PixelFormat
> (PixelFormat)InternalPixelFormat.CompressedRgbaS3tcDxt5Ext
> -Frazzle

Copied pertinent text from forum post for posterity. Closing due to age.
