### ISSUE TITLE
Compile with .NET Framework higher than 4.0 - adjust AssemblyInfo.cs

### ISSUE THREAD

**Issue by edgar005** [opentk/opentk#206]
Hi
in order that OpenTK compiles with .NET Framework versions higher than 4., a line in the AssemlbyInfo.cs of OpenTK, Compatibility and GLControl and  has to be added

[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]

(similar to the already existing lines, which are added only for .NET version 4.0)
BEst
Edgar

**Comment by Frassle** [comment]
Closing this now. The develop branch is designed for .NET 2.0, for proper .NET 4.5 support use the net45 branch.
