### ISSUE TITLE
Missing enum values on SizedInternalFormat

### ISSUE THREAD

**Issue by JcBernack** [opentk/opentk#207]
Currently the SizedInternalFormat enum only contains the color formats, but at least the GL.TexStorage*() methods should also accept depth and stencil formats, GL.BindImageTexture() however should not. So there should be an additional enum.

There already is something related to this in the overrides.xml, but I don't really understand whats going on there. Seems like it is for the ES2 namespace:

```
<!-- gles2 3.0 enums -->
<add name="gles2" version="3.0">
... 700 lines later
  <enum name="SizedDepthStencilFormat">
    <use token="DEPTH_COMPONENT16" />
    <use token="DEPTH_COMPONENT24" />
    <use token="DEPTH_COMPONENT32F" />
    <use token="DEPTH24_STENCIL8" />
    <use token="DEPTH32F_STENCIL8" />
  </enum>
  <enum name="SizedInternalFormat">
    <reuse enum="SizedColorFormat"/>
    <reuse enum="SizedDepthStencilFormat"/>
  </enum>
...
</add>
```

If I figure out how this all works I might submit a pull request.

**Comment by daerogami** [comment]
@varon Let me know if you think this is still an issue. Seems pretty trivial.
