### ISSUE TITLE
Missing ExtTextureFilterAnisotropic in OpenGL4 namespace

### ISSUE THREAD

**Issue by achlubek** [opentk/opentk#212]
Enabling anisotropic filtering is impossible when using OpenGL4 namespace.
Importing OpenGL namespace under different name and using it works ok even with OpenGL4.
This is because OpenGL4 is missing MaxTextureMaxAnisotropyExt
Example code to workaround this:

`````` csharp
using OpenTK.Graphics.OpenGL4;
using OldGL = OpenTK.Graphics.OpenGL;
//(... and when texturing...)
float maxAniso;
GL.GetFloat((GetPName)OldGL.ExtTextureFilterAnisotropic.MaxTextureMaxAnisotropyExt, out maxAniso);
GL.TexParameter(TextureTarget.Texture2D, (TextureParameterName)OldGL.ExtTextureFilterAnisotropic.TextureMaxAnisotropyExt, maxAniso);```
``````

**Comment by varon** [comment]
This is a bit inconvenient to use, but works 100% fine. Closing.
