### ISSUE TITLE
Can't link programs containing either geometry shaders or tesselation eval/control shaders

### ISSUE THREAD

**Issue by achlubek** [opentk/opentk#213]
Linking those progras causes application to hang and nothing can be done about that.
Moreover: if I comment out any gl_Position setting lines in shaders it doesn't hang - but of course doesn;t draw triangles with those shaders.

**Comment by Frassle** [comment]
Can you post the shader and application code?

**Comment by achlubek** [comment]
Geometry shader source: http://pastebin.com/jM1sutSV
when you comment out the gl_Position line it doesn't hang.
Application code is at https://github.com/achlubek/vengine
and the shader compilation is at https://github.com/achlubek/vengine/blob/master/VEngine/ShaderProgram.cs
and the particular one material where I test geometry shader is at https://github.com/achlubek/vengine/blob/master/VEngine/SingleTextureMaterial.cs
If you have trouble reproducing the crash please contact me at skype 'aeroflyluby', I tested it on my own Radeon R7 250x and on my friend mobile nvidia (don't know exact version but it supports 4,4). 
Before, I was using beta drivers and LinkProgram caused heap corruption in ntdll after beign invoked by ATI driver, but after downgrading it hangs just some instructions after that, no matter what those instructions are.

**Comment by achlubek** [comment]
I have tested the issue on both official binary release and then compiled devel branch minutes ago on my own with Release settings, nothing changed. The same behaviour happens when I try to use tesselation shaders. Every shader compiles OK.

**Comment by Frassle** [comment]
Thanks, I'll try to repro this week.

**Comment by achlubek** [comment]
Than you so much!

**Comment by Frassle** [comment]
Did some tests with geometry shaders, can't reproduce any issues. Can you put together as small a program as you can that reproduces the problem (preferably a single source file I can just grab off gist), I'll see if that repros here (nVidia and ATI cards here) and debug if it does.

**Comment by varon** [comment]
Ancient report. Seems to be a usage error. Please re-open if you are still encountering this.
