### ISSUE TITLE
Binding generator requires documentation

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#216]
There are currently a few issues open due to various GL enums or methods being incorrect or missing (#203, #207, #212). These are probably easy to fix but due to the lack of written process for dealing with the binding generator it's not clear what should be done.

We should both document how the binding converter and generator work, and what process should be followed to fix issues with the bindings. These documents can be simple text files in the repo.

**Comment by varon** [comment]
This would be nice to have, but ultimately isn't something we're going to act on at the moment.
