### ISSUE TITLE
Linux + mono + fglrx = black window

### ISSUE THREAD

**Issue by roman-yagodin** [opentk/opentk#217]
Simple examples like `GameWindowSimple.cs` produce only black screen (no errors). App main cycle are working (responding to the keys). System configuration:

OpenTK version 1.1.1589.5942
AMD fglrx proprietary driver 1:13.8~beta1-3 
uname -a: Linux simargl 3.11-2-amd64 #1 SMP Debian 3.11.8-1 (2013-11-13) x86_64 GNU/Linux

fglrxinfo:

```
display: :0  screen: 0
OpenGL vendor string: Advanced Micro Devices, Inc.
OpenGL renderer string: AMD Radeon HD 7660G
OpenGL version string: 4.3.12438 Compatibility Profile Context 13.20.5
```

mono --version:

```
Mono JIT compiler version 3.12.0 (tarball Sat Feb  7 19:12:57 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen
```

**Comment by roman-yagodin** [comment]
Manually copying `OpenTK.dll.config` from NuGet packages directory to project output (e.g. `bin/Release`) seems to solve the issue for me. With other system configuration on VM (same Debian version (but 32-bit), same Mono version + VirtualBox video driver) samples working without config file.

**Comment by Frassle** [comment]
.config is probably required to find the right libraries to load. But it should probably be in the project output anyway, and should probably give some sort of message if libraries aren't loading correctly.

**Comment by Frassle** [comment]
Thanks for the pull request, I'll leave this bug open to have a look to see if the NuGet package can be set up to do this automatically.

**Comment by cra0zy** [comment]
It would be nice if opentk had a set of default linux and mac libraries even when config file is absent.

**Comment by Frassle** [comment]
I don't know if that's possible. The whole point of .config files is a mono workaround because DllImport only has one parameter to name the library to call, which is nearly always filled in with the Windows name of the library, e.g. opengl.dll. .configs map that Windows name to Linux and Mac names when running under Mono on those platforms, no .config no default names (or more correctly, one default name: the Windows one).

**Comment by cra0zy** [comment]
In code checking would be a possibility, if there is a config file, load from config file, else check the running system and load predefined library.

**Comment by Frassle** [comment]
Like I said this is a Mono thing, it's very hard/impossible to override. But we should see if the NuGet package can be set up to make sure the config is correctly installed.

**Comment by varon** [comment]
The config should be included by default now.
