### ISSUE TITLE
Site Issue, issue tracker inaccessible

### ISSUE THREAD

**Issue by PaulGWebster** [opentk/opentk#225]
http://www.opentk.com/node/add/project-issue/opentk is unable to be accessed, screenshot attached.

![screenshot 2015-02-25 at 13 16 39](https://cloud.githubusercontent.com/assets/401142/6371160/9c4722c0-bcf0-11e4-84f0-af02bad7a06b.png)

**Comment by Nihlus** [comment]
@varon Invalid issue, old site is gone.
