### ISSUE TITLE
Site Issue, Forum post does not redirect back to post location

### ISSUE THREAD

**Issue by PaulGWebster** [opentk/opentk#226]
When posting on the forum http://www.opentk.com/forum/2 you will be redirected to page 1 of the thread you was reading. Which is a little disorientating.

To fix would need to pass pageid in with the post submit and include the pageid in the redirect back, NOTE if the post is going to a new page (posted from page 2, post will be on page 3) this may still redirect back to the wrong page unless, you also pass the 'posts displayed' to calculate which page the post will land on!

**Comment by Nihlus** [comment]
@varon Invalid issue, old site is gone.
