### ISSUE TITLE
Feature Request, IRC 'tab' on opentk site

### ISSUE THREAD

**Issue by PaulGWebster** [opentk/opentk#227]
It would be nice to implement cgi::irc or other on the main site, to try get our community on our IRC channel talking together. Get the community spirit going and all :)

I also had a fun idea to implement a passive IRC chat which integrates more directly, the way that would work is that when a user signs into the website a callout is made to a peice of software I designed (perl im afraid not c# :() which creates a faux user on the network under the nickname of the signin user.

Then a small form is placed on the page that allows kind of one off communication using the IRC server as a backend.

Just an idea

-- Paul

**Comment by PaulGWebster** [comment]
Confirmed with freenode staff this is possible with notification :)

**Comment by varon** [comment]
Replaced by gitter
