### ISSUE TITLE
DisplayDevice.Bounds does not change

### ISSUE THREAD

**Issue by xanather** [opentk/opentk#231]
DisplayDevice.Bounds does not change after changing the resolution of that same DisplayDevice. It could be intended behavior and therefore is designed to keep the actual desktop bounds it was created with but its hard to tell.

If DisplayDevice.Bounds is supposed to change after ChangeResolution, there is a high chance the other DisplayDevice instances will need their respective Bounds modified/checked too (as the whole desktop bounds are usually different after resolution changes).

DisplayDevice.Width and DisplayDevice.Height do change automatically.

Edit: This is on Windows

**Comment by xanather** [comment]
If this is a bug, I can upload a test case.

**Comment by xanather** [comment]
(On Windows)

I can confirm that changing the resolution permanently from the actual desktop settings while an OpenTK program is running still results in DisplayDevice.Bounds not changing for any displays. This could be a problem for programs that rely on the Bounds propery of DisplayDevices for determining what monitor the NativeWindow/GameWindow is displaying.

**Comment by Frassle** [comment]
This looks very much like a bug, or at the very least under-specified/not very useful behaviour.

Test cases are always useful. I do plan on getting proper support for regressions tests in at some point for now just post it as a snippet here.

**Comment by xanather** [comment]
Okay, well its basically just this:

```C#
DisplayDevice device = DisplayDevice.GetDisplay(DisplayIndex.First);
Rectangle prev = device.Bounds

//Change the resolution of the first display device here, either manually with desktop settings, or device.ChangeResolution()

if (prev == device.Bounds)
{
    //We have a problem
}
```

**Comment by Frassle** [comment]
Cool, simple is good. I'll experiment with this at the weekend.

**Comment by Frassle** [comment]
So the basic problem is that bounds is kept as a separate variable that is never updated in the DisplayDevice. Probably simple to fix the issue of ChangeResolution not updating that, but if the user changes the resolution it needs to be re-queried. I think the best thing is to re-architect DisplayDevice to minimize caching and to forward all query calls to the platform driver to get the current real values. That's a bit of work but I'll get started on it in a new branch.

**Comment by Frassle** [comment]
Started working on this at https://github.com/Frassle/opentk/tree/displaydevice. Bit of simple testing on a single monitor I seem to have at least fixed this issue reported here. Needs some testing on multi-monitor setups to make sure the change hasn't screwed up screen bound calculations. The OSX and Linux changes also need testing, but I think the code should be mostly fine.

**Comment by xanather** [comment]
Looks interesting, I do have a multi monitor Windows and Linux/Ubuntu to test on which I will,  I do not have a mac to test it on though.

**Comment by Frassle** [comment]
Any testing you can do is appreciated, feel free to send pull requests to that branch in my repo if you fix anything as well. Otherwise you can report issues in this ticket.

**Comment by xanather** [comment]
Works good on multi-monitor Windows, even the X/Y positions of other monitor bounds correct itself after a resolution on a different display has changed. Going to test Ubuntu now.

**Comment by xanather** [comment]
I am getting NotImplementedException on ubuntu when checking the Bounds value.

https://github.com/Frassle/opentk/commit/46dcb9707a60f0e018d1c4dccd3de3b7cbffe439#diff-56fd694fc210cfdfa5dda9959a8212d7R443

**Comment by Frassle** [comment]
Hmm I thought I'd done that code. Either I misremember or forgot to upload it, I'll try to take a look when I get home tonight. Thanks for testing!

**Comment by Frassle** [comment]
Ok I must of forgot to write the X11 code. I'll see if I can put it together now.

**Comment by Frassle** [comment]
Ok pushed the X11 code to https://github.com/Frassle/opentk/tree/displaydevice

Haven't tested at all yet, I really need to get my ubuntu box and raspberry pi running again!

**Comment by Frassle** [comment]
Started looking into this again. Got it rebased on latest develop, not checked Windows yet but Linux is pretty broken.

**Comment by Frassle** [comment]
I've got an ubuntu 14.04, windows 7 and windows 10 machines to test this on. Once I've got those happy would be good to get some others Linux variations and MacOS tested if anyone has access to those?

**Comment by Nihlus** [comment]
I've a Mint 18.2 box available :)

**Comment by Frassle** [comment]
Pushed PR #610 to fix this. It needs a lot of testing which I'm not currently set up to do however.

**Comment by VPeruS** [comment]
What test cases need to test?

**Comment by Frassle** [comment]
That you can get a DisplayDevice for each attached screen. That the resolution reported by display device (dev.CurrentResolution) matches what the OS says it should be and that if you change the resolution in the OS that dev.CurrentResolution updates. Plus anything else you can think of. Try and break it :stuck_out_tongue_closed_eyes:

**Comment by varon** [comment]
Closed by 4.x
