### ISSUE TITLE
Unit and Regresion Tests

### ISSUE THREAD

**Issue by LaylConway** [opentk/opentk#232]
I saw these are planned to be added to OpenTK. I could make a pull request with some basic tests on OpenTK.Math, but need a few details on what the plans are for this.
- What testing framework should be used?
  I myself am using xunit 2 for my projects, which I've been really enjoying using and is easy to integrate with CI. However, it's still in pre-release (though it's in release candidate stage now).
- What naming standards should be used on test cases?
  I use `[Type Name]Tests.[Method]_[Data]_[ExpectedResult]` myself just for lack of anything else/better.
- Should unit tests be checked by Travis CI?
  I would say a definite yes myself but perhaps there's reasons not to.

**Comment by Frassle** [comment]
I started putting together a branch with [NUnit](https://github.com/Frassle/opentk/tree/nunit), but there isn't any agreed consensus yet so happy to take a look at xunit.

It would be good if we could get them checked by Travis, I don't see any reason not to except further latency with Travis builds but we aren't time constrained there (most things take a long time to pull in due to lack of human testing and review resources).

**Comment by Frassle** [comment]
See pull request #195.

**Comment by LaylConway** [comment]
I'll make some example tests to compare xunit and nunit.

**Comment by Frassle** [comment]
Had a quick look at xUnit looks like an modern nUnit so as long as it plays nice with VS and MonoDevelop it should be fine.

**Comment by LaylConway** [comment]
It does work well with VS and MonoDevelop, rather than installing a plugin, you have to install a runner nuget package into the project. I'm not sure what package that is for MonoDevelop, but there's a specific one for Visual Studio.

**Comment by Frassle** [comment]
If you want to start putting together a pull request, happy to help review and improve an xUnit addition to OpenTK.

**Comment by LaylConway** [comment]
Sure, it will take a bit as I'm a bit busy right now but I should have a project with some examples tomorrow.

**Comment by LaylConway** [comment]
My attempts so far seem to have trouble building on mono. It seems currently xUnit 2 targets a minimum of .NET 4.5, and so far I could not get that to work for just the unit test project on the travis build bot. I don't know if xUnit 2 is going to bring back support for .NET 2.0 on release and if xUnit 1 supports .NET 2.0.

**Comment by Frassle** [comment]
Mono have [dropped support for pre .NET 4.5](http://www.mono-project.com/docs/about-mono/releases/4.0.0/) so we should probably follow suit. That would resolve the xUnit on 4.5 only issue.
@thefiddler could we branch to have a bugfix only 2.0 branch and update master to 4.5?
@LaylConway can I ask you keep looking into xUnit 2 on a 4.5 build of OpenTK?

**Comment by LaylConway** [comment]
I'll make a new fork to try to get it working on mono with 4.5 target.

**Comment by Frassle** [comment]
@LaylConway do you want to try with xUnit again on the [net45 branch](https://github.com/opentk/opentk/tree/net45)? If you need to use nuget you might want to remove the 3.2.8 build from the .travis.yml.

**Comment by LaylConway** [comment]
I'll take a look at getting it to work later today. It probably does require nuget to work yea.

**Comment by Nihlus** [comment]
@varon @daerogami Since we've now merged in #507, I would consider this issue closed. The remaining classes and methods which are not covered by unit tests could be tracked as a project, milestone, or separate smaller issues.
