### ISSUE TITLE
[Input] Key.KeypadDivide is never raised

### ISSUE THREAD

**Issue by xanather** [opentk/opentk#237]
Key.KeypadDivide is never raised with NativeWindow OnKeyDown or OnKeyUp, pressing the divide key on the numpad instead activates Key.Slash.

All other Keypad Key's work fine so I assume its a bug. I am currently working with the Win32 API for my Direct3D backend and its definately possible to differenticate between the Slash and Numpad Divide keys.

Platform: Windows 8.1 64-bit, not using SDL

**Comment by xanather** [comment]
I'm writing these issues in my private repo for my engine too since it affects it, once I have my engine almost done I'll look to see if I can get any of these bugs ironed out (if they haven't been looked at since then). I'm sure this one is a simple fix.

Also, maybe it is time to move OpenTK to use .NET 4.0 by default? I don't think .NET 2,0 is supported by mono very soon

**Comment by xanather** [comment]
Think I found why NumpadDivide is not working. WinKeyMap.cs uses the Scancode for determining the key to use. Scan code returns a slash key when the numpad divide key is pressed. https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Platform/Windows/WinKeyMap.cs#L166 The vkey variable can be used to check if a Key.Slash is actually a NumpadDivide.

I'll submit a PR once OpenTK has been converted to 4.0 (however its going to be done).

**Comment by Frassle** [comment]
Can you check that #244 fixes this, testing locally suggests it does.

**Comment by xanather** [comment]
Yep this fix works.
