### ISSUE TITLE
TextureTarget and TextureTarget2d in OpenGL ES3

### ISSUE THREAD

**Issue by l3m** [opentk/opentk#238]
I am not sure if this is by intention or oversight, but some  OpenGL ES3 methods use the enum TextureTarget, others use TextureTarget2d. 

Shouldn't this be unified so it always uses TextureTarget? Currently, it forces a user to jump through hoops like this: 

``` c#
    void LoadTexture(byte[] rgba, TextureTarget target)
    {
        GL.BindTexture(target, _texture_id);
         // switch or method call or casting hacks
        var target2d = GetTarget2dForTarget(target);
        GL.TexImage2D(target2d, ... );
        // ....
    }
```

I think it would be clearer if TextureTarget would be used consistently. 

What do you think?

**Comment by varon** [comment]
Closing, might be nice, but it's an incredibly minor thing and super old.
