### ISSUE TITLE
Code example for fixing X11 aborting the application

### ISSUE THREAD

**Issue by xanather** [opentk/opentk#241]
When running OpenTK on Linux under X11, X11 may abort the application abruptly in native code if an X11 error occurs. This will prevent that. Most of these errors should be recoverable, and if not, it will allow the debugger to catch the error/exception anyway.

``` C#
        [StructLayout(LayoutKind.Sequential)]
        internal struct XErrorEvent
        {
            internal int type;
            internal IntPtr display;
            internal int resourceid;
            internal int serial;
            internal byte error_code;
            internal byte request_code;
            internal byte minor_code;
        }

        internal delegate short XErrorHandler(IntPtr display, ref XErrorEvent error_event);

        [DllImport("X11")]
        internal extern static short XSetErrorHandler(XErrorHandler error_handler);

        private static bool x11handlerEnabled;
        private static XErrorHandler x11handler;

        private void EnableX11Handler()
        {
            if (!x11handlerEnabled)
            {
                x11handler = new X11API.XErrorHandler(EmptyX11Handler);
                X11API.XSetErrorHandler(x11handler);
                x11handlerEnabled = true;
            }
        }

        private short EmptyX11Handler(IntPtr display, ref X11API.XErrorEvent error_event)
        {
            //throw error here, could use http://tronche.com/gui/x/xlib/event-handling/protocol-errors/XGetErrorText.html for more detailed exception.
            throw new X11Exception(error_event.error_code);
        }


```

**Comment by Frassle** [comment]
So we can't throw an exception at that point as it's not safe to propagate exceptions through unmanaged code. I do think it's worth us trapping these errors and reporting them back someway, I'll think over it.

**Comment by xanather** [comment]
The managed exception should bubble back up through the managed->native call that caused the X11 error. That's what happened for me.

**Comment by Frassle** [comment]
Hmm ok that's useful to know. I'll see if I can find some citations on if this is safe on Mono and not just luck. (I guess we don't really care how .NET works here given it won't be running X11 code)

**Comment by Frassle** [comment]
OK so Mono say the stack will unwind correctly but your potentially going to be wrecking any native code that won't handle the exception, see [mono documentation](http://www.mono-project.com/docs/advanced/pinvoke/#runtime-exception-propagation). So throwing the exception is not right, but we can catch it and log it and report it back once back in mangaged land. Probably a nice way to do that.

**Comment by xanather** [comment]
Sounds like a good idea, overhead would be having to check if a error flag is set after each X11 call - which isn't a big problem and I think it would be worth it.

**Comment by xanather** [comment]
I'm thinking about working on fixing this, how should it be approached? Should I wrap all the X11 Interop methods with checking for a flag (which will be set by the X11 error handler) after their executions or do it another way instead?

**Comment by Frassle** [comment]
That sounds like the best approach, bit annoying to do have to do it all manually (wishes .NET had better aspect support). Might be worth spending a small amount of time seeing if it's easily doable via the OpenTK rewrite system or T4 templates but I suspect they'll be more complex than the effort they save.

All we really need is to set the error callback in the static constructor, then in the callback save the XErrorEvent value to a static field (Maybe a Nullable<XErrorEvent>). After every X call we just check that field and if it's been set translate it into an exception and throw.

**Comment by xanather** [comment]
Looking at the code it looks like rewriting may be a better solution. There are a lot of methods to wrap (and I mean alot!). It would balloon the lines of code for \Platform\X11\Functions.cs and \Platform\X11\API.cs classes.

The rewriter could look for any external P/Invoke Xlib functions and generate a wrapper method for those methods. Not sure if its possible to get other code referencing those P/Invoke methods to use the wrapper method instead. Maybe its possible to make the wrapper method to have the same signature as the Xlib functions, then change the actual Xlib function signature before finishing.

However I don't have much experience rewriting compiled assemblies and such a thing could be difficult for me implement. I am interested in learning about MSIL more, though I won't be able to implement such a thing for a while.

If you think its just better to add new methods directly then I'll still do that, it seems easy enough, but keep in mind that it will probably increase the size of the codebase for those files probably 4 times or more since each native Xlib call will need a copy/paste wrapper (could add a another partital class though).

**Comment by Frassle** [comment]
Ah yeh that's awkward that they're currently pinvoke methods and we can't rewrite those so whatever we do we'll need wrapper methods.

Might be doable with T4 templates rather than CIL rewriting (T4 templates are also easier!). If we had a table of all the X11 methods and their type we could then write some T4 code to spit out a private pinvoke for it, and a public wrapper method. 

You can see some T4 templates I was working on (here)[https://github.com/Frassle/opentk/tree/t4math]. Won't be the same as what you need but should give a good idea of what T4 is capable of.

**Comment by xanather** [comment]
I use Visual Studio 2013 Ultimate and it has the ability to show the amount of references for each method in the code view easily. There is actually a lot of unused X11 Interop methods which could result in a lot of unnecessary wrapping methods. It could be risky to remove them however, especially if they were to be used in the future.

Should I bother trying to clean up API.cs and Function.cs or just apply a wrapper method to all [DllImport(X11)] methods? I just don't want to make changes that might not get accepted.

**Comment by Frassle** [comment]
Better keep them, they're exposed publicly so would be a breaking change to take them out.

**Comment by xanather** [comment]
What do you think about these changes? https://github.com/xanather/opentk/commit/c7a6325d26c5d1497fd43db59e669fe023b2dede

I'll happily add the wrapper methods to the rest of the Xlib DllImport methods if they're good (including the methods in Function.cs aswell)

**Comment by Frassle** [comment]
So I'm doing some more reading on this, and I'm wondering if this is actually the correct approach. The documentation states that the error handler might not be called while a function is executing, but only later once a response has been received from the X server. This asynchronous nature makes wrapping the functions with checks kinda pointless as we might miss the error.

So I'm of two minds at the moment, given that we expose XSetErrorHandler in the X11.Functions already if devs need to they can override it to work around the default behavior of exiting on any error. On the other hand that requires devs to check if their running on X11 and doesn't really fit with our normal library design of just hiding issues likes this.

Give me some time to read more on this, and chime in if you've got any info to add.

**Comment by Frassle** [comment]
Do feel free to make a pull request for https://github.com/xanather/opentk/commit/9bf3c6bb1b61f971173e012060524694b4d9fd32, I can merge that in straight away.

**Comment by xanather** [comment]
Damn, that sucks, why can't X11 be more like the Win32 API :(

"On the other hand that requires devs to check if their running on X11 and doesn't really fit with our normal library design of just hiding issues likes this."

Yeah, that's what I am currently doing. Really creates for some out of place code in my classes.

I thought X11 XSetErrorHandler was synchronous, I mean, currently I get an exception called back on the same thread even when throwing an exception inside the native handler (which I should not be doing now I know, but still). The exception is thrown on the method that caused the X11 error.

I guess it depends on the context though.

**Comment by Frassle** [comment]
> I guess it depends on the context though.

Probably. Even if it seems to work now there doesn't seem to be any guarantees in the spec about when it will trigger, it's a very annoying case to work around :(

I'll leave this issue open and keep thinking about it. There might be something we can do to make this easier to deal with.

**Comment by varon** [comment]
There doesn't appear to be an easy solution to this based on the conversation thread here.

Please re-open if you come up with an actionable suggestion.
