### ISSUE TITLE
Moving to .NET 4.5

### ISSUE THREAD

**Issue by xanather** [opentk/opentk#242]
Is there anything preventing the change to .NET 4.5?

Mono is killing/killed off .NET 2.0 support.

I notice that compiling with .NET 4.0+ will not work without the [assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)] flag, I am still not completely sure about what this flag does but the docs says its for compatibility reasons. Maybe its best to fix this before upgrading? If its not a problem I am willing to submit a PR that converts all projects to compile with .NET 4.5 (or .NET 4.0) by default.

Would such a PR be accepted? Are we willing to make the switch?

I would really like such a change because my workstation does not have .NET 2.0 SDK's and having to convert back for ensuring any repo changes work with .NET 2.0 is a pain.

Windows 8 and Windows 10 do not include .NET 2.0 by default.

**Comment by Frassle** [comment]
#206 is tracking the issue with security rules. I've had a bit of a look and put together a PR #215 to fix it. Not 100% sure that's the right fix though.

We also discussed this issue in #232 as xUnit only had support for 4.5.

If you put together a PR I'm happy to start a new net45 branch so at least some collaborative work can be done on it. If people want 4.5 they can grab that branch, and @laylconway could continue xUnit work based on that branch. Does have the down side that we will have to duplicate fixes to both master and net45 until we're sure we can drop .NET 2.0 support and make net45 = master.

**Comment by xanather** [comment]
I can test https://github.com/opentk/opentk/pull/215 if you want and have it included in the PR to switch to 4.5 if it works. It would avoid having two separate branches. If your uncomfortable with completely switching to 4.5 that its fine - there is a high chance other things can go wrong.

Either way working with a 4.5 branch wherever would be good and allow me to get some of the issues Ive posted fixed.

**Comment by xanather** [comment]
https://github.com/opentk/opentk/pull/215 does indeed fix the issue.

**Comment by xanather** [comment]
Done

https://github.com/opentk/opentk/pull/243

I can create another PR that excludes https://github.com/opentk/opentk/pull/215 if needed/wanted.

**Comment by Frassle** [comment]
net45 branch created and switched to build for .NET 4.5. Most commits will have to go to develop and net45. Features that required .NET 4.5 can now be put onto the net45 branch, this will hopefully include @LaylConway's work with #232.
