### ISSUE TITLE
Access Violation Exception at OpenTK.Input.Joystick.GetState function.

### ISSUE THREAD

**Issue by NinjaFighter** [opentk/opentk#251]
This exception can be easily generated with an XBox360 gamepad (with battery), and some other joysticks at same time. If you put the GameWindow States example, and wait until XBox360 gamepad auto disables itself (near to 10 minutes of inactivity) (doesn't work if you unplug or remove batteries). When try to get the other Joystick's state, you get an Access Violation Exception. This could be very problematic in some cases. If you don't use Joystick.GetState and use only GamePad.GetState, this doesn't happen, but that means we can't support Joysticks properly on our apps/games.

**Comment by Frassle** [comment]
Assuming this on Windows? Do you know if your using the SDL2 backend or not?

> When try to get the other Joystick's state

What do you mean other? Not the XBox360 controller, but another plugged in?

Something like:
GetState(0) // get xbox controller state
// wait for xbox to disconnect
GetState(1) // try to get other joystick state, crash

**Comment by NinjaFighter** [comment]
Yes, Im using windows 7 and I'm using the latest binaries from the official site, I think that version of opentk uses winmm or something like that... I don't see anything about SDL2, but I'm really sure about that.

I can say that I have a Twin Usb Joystick adaptor with two playstation 2 controllers connected, and an Xbox360 Wireless gamepad. If Xbox gamepad going to "sleep" (to preserve batteries, about 10 minutes of inactivity), when I try to read a single state of a Joystick, (using OpenTK.Input.Joystick.GetState method), the application leads to an Access Violation Exception, and I can't using "try/catch" to catch exception, because it's an unhandled exception. You don't have to program anything to test this bug, simply run the GameWindowStates example, with an Xbox Wireless controller on, and another joysticks, and see what happens when Xbox controller sleeps.

**Comment by Frassle** [comment]
> latest binaries from the official site

If you can I'd recommend building from source. Our distribution story isn't great and both the website and nuget lag behind in updates and fixes.

I think I've got some PS4 and XBox360 controllers at home so I'll see if I can repro this.

**Comment by Frassle** [comment]
OK I unfortunately don't have a wireless part for the xbox controller so can't repro this as is. I did have a look through the controller and joystick code to see if there was anything obvious, but I'm just more confused. Gamepads are all routed through our joystick driver so I'm not sure how something could cause an error in the Joystick driver but not the Gamepad driver!

If it's possible could you get the latest code from the (develop branch here on github)[https://github.com/opentk/opentk/tree/develop], and try to get a stacktrace or step through to better locate where in OpenTK this is crashing.

**Comment by NinjaFighter** [comment]
Thanks for the advice, I will switch to develop branch instead, and see what happens. But... anyway... I'm trying to figure what can be the problem (on the fly for now). I'm always suprised about how opentk deals with joysticks input... I mean... I can't rise events instead using a "getstate" function?, maybe this "getstate" functions leads to problems... think about that... it's an "access violation" when reads a joystick state... so... probably, is trying to read a generic joystick state, from pointer that is currently pointing to a Xbox Gamepad state or even an unregistered data, and this leads to read incorrect size of memory. I think that the best way to deal with input, could be rising events instead of using "getstate" functions, in fact, usually people write is own "joystick access" class, to deal only with only matters values, instead of get the full information about an input device.

**Comment by Frassle** [comment]
> probably, is trying to read a generic joystick state, from pointer that is currently pointing to a Xbox Gamepad state or even an unregistered data

That is one of my suspicions. However it doesn't explain why your not getting issue with Gamepad.GetState which works in exactly the same way, and is very tricky for me to hunt down without an xbox wireless controller to reproduce the disconnect scenario.

>  I think that the best way to deal with input, could be rising events instead of using "getstate" functions

I didn't write the joystick/gamepad code but I think this might be due to underlying platform issues. That is the platform doesn't expose events just polling, so that's what we expose.

**Comment by NinjaFighter** [comment]
Hmm, let's see something... Gamepad.GetState actually works, and even return a valid gamestate, but, for example... if you do "Gamepad.GetState(0)", and then "Joystick.GetState(0)", it works, even if you don't have joysticks/gamepad plugged. However... in this specific case, looks like Gamepad.GetState(0) is returning some valid data, but when you do Joystick.GetState(0) looks like is trying to read a JoystickState by a pointer that points to GamepadState instead. So, probably there's nothing about pointing unregistered data, because (as you said) Gamepad.GetState works.
I think this bug is because Gamepad is in the "list", but looks like it doesn't count. So, if you have 2 gamepads and disconnect one, the second gamepad becomes the first one... and in that case, looks like the first gamepad doesn't count, but is here!. I think that will explain why Gamepad.GetState doesn't crash in that case. Maybe... who knows...

**Comment by Frassle** [comment]
Are you running that with build of the latest develop branch?

**Comment by NinjaFighter** [comment]
Not for now, but I will switch surely next week.

**Comment by Frassle** [comment]
Hmm ok. If you could get back to this when your running the latest code that would be good, I guess we must of changed the input system substantially over the last year, so hard to help until your on the latest code base.

**Comment by NinjaFighter** [comment]
Ok, I couldn't resist, and downloaded the last develop branch... and... good news! there are no crashes this time! And even, I notice that something was wrong about the latest stable releases of the official site... because this recongnise as "gamepad" only my xbox controller, and another ones only as "joysticks", and now with latests source, opentk recognises all mi joysticks just like a "gamepads". So, I don't know what may have been, but is gone! So, there's no bug now =)
