### ISSUE TITLE
Linux/Ubuntu always only obtains 1 Display

### ISSUE THREAD

**Issue by xanather** [opentk/opentk#254]
My code iterates over the GetDisplay() method, stopping when null is returned and storing any obtained DisplayDevice's.

Linux always seems to obtain only 1 display, even though multiple displays may be connected. The desktop resolution for the first DisplayIndex is stretched over the multiple displays if they are connected (this is very different functionality to Windows, also seems wrong/bugged).

**Comment by xanather** [comment]
This is excluding changes made to https://github.com/Frassle/opentk/tree/displaydevice . DisplayDevice throws an exception on that branch for Linux/X11 programs anyway so I can't test that.

**Comment by Frassle** [comment]
I assume this is with X11 not KMS? 
displaydevice should be working for X11 now, can you let me know what exception your getting on that branch?

**Comment by xanather** [comment]
Ah, didn't notice you pushed the X11 changes to https://github.com/Frassle/opentk/tree/displaydevice (which fixes that NotImplementException). And yes it is with X11. Will be testing this on https://github.com/Frassle/opentk/tree/displaydevice branch.

**Comment by Frassle** [comment]
This is still an issue on my branch, it's returning two monitors but both have the same size which is the size of the one virtual monitor covering both physical ones.

**Comment by renanyoy** [comment]
I think it's normal it's how linux works, only one monitor/view linked on multiple displays

**Comment by varon** [comment]
Not a bug? Old issue? Closing. Re-open if it's affecting you.
