### ISSUE TITLE
GL.GenVertexArrays fails on MacOS but not GL.GenVertexArray

### ISSUE THREAD

**Issue by evanolds** [opentk/opentk#255]
I'm seeing a consistent issue where several overloads of GL.GenVertexArrays (plural) fail. By "fail" I mean that they simply do not create a valid new VAO ID, but there's no crash. They seem to work fine on Windows (same hardware) but not MacOS. On the other hand, GL.GenVertexArray (singular) works fine and gives me a new VAO ID. Here's an excerpt from my code showing a few things that fail and what succeeds:

// Commented-out code doesn't work on my Mac (OpenTK bug?)
//int[] arrs = new int[]{ -1 };
//GL.GenVertexArrays(1, arrs);
//m_vao = arrs[0];

// This doesn't work either on MacOS:
//GL.GenVertexArrays(1, out m_vao);

// But this does:
m_vao = GL.GenVertexArray();

**Comment by Frassle** [comment]
Is the VAO id passed in (arrs, m_vao) modified at all or does it just keep it's original value? If it does change what's it changing to?

**Comment by evanolds** [comment]
For the GenVertexArrays call it's always keeping the original value. I just noticed this, and I overlooked it before because my app was producing the correct visual results, but the GenVertexArray call is returning 0, which I believe also indicates failure. It just so happens that a VAO of 0 didn't cause any problems in one of my apps, but it's problematic in other apps (because it's not actually generating a valid VAO). This exact same behavior is observed on two different Macs, one with Radeon and the other with NVidia GeForce. Both give 0 for all GenVertexArray calls and leave the output unmodified for GenVertexArrays. I'm using the latest official release but not the latest build of OpenTK.dll. On my Windows machine GenVertexArray gives back 1 (this is on the same hardware as the Radeon Mac) and everything works fine.

**Comment by Frassle** [comment]
You can call GL.GetError to see what error the GenVertexArrays call is returning. I assume the driver behavior is on error to return the array unmodified, doesn't sound like an OpenTK issue.

**Comment by evanolds** [comment]
It's an OpenGL profile version thing I think. Just to ensure this is not an OpenTK bug, let me inquire as to what's the expected behavior here. I create the graphics context specifying version 3.0:

m_gc = new OpenTK.Graphics.GraphicsContext(
            	GraphicsMode.Default,
                m_wi, 3, 0, GraphicsContextFlags.Default);

In a later call to GL.GetString(StringName.Version) I get "2.1 ATI-1.32.20" meaning it's using 2.1, which doesn't support VAOs. But my drivers are updated and I have support for OpenGL 4.1 on the machine. Is there somewhere else where I have to specify that I want to use OpenGL version 3.0? Is it expected that the GraphicsContext constructor can instantiate an object that doesn't use the specified version indicated by the major and minor version parameters? The documentation states that "the context will use the highest version that is compatible with the version you specified", which doesn't seem to match up here.

**Comment by Frassle** [comment]
Hmm that might be a bug, I know OSX GL profiles are weird so I'll have to do some reading up before confirming this.

> Is it expected that the GraphicsContext constructor can instantiate an object that doesn't use the specified version indicated by the major and minor version parameters

I don't know what the original intention was but we've had a lot of issues with getting drivers to load in the right mode (we ask for GL3 they say sure and load GL2!) but we never added checks after loading to see what version we actually got and if that matched what we asked for. I guess we could add an exception in that case but that's a breaking change so will have to wait for a major version update.

**Comment by varon** [comment]
Old issue, extremely edge case. Seems to be a driver bug. Re-open if it's affecting you.
