### ISSUE TITLE
Windows input ignores keyboard layout

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#260]
Notified from https://github.com/mono/MonoGame/issues/3836.

**Comment by Frassle** [comment]
Started looking into this. We currently have a translation from scancodes to OpenTK.Keys (bar one special case were we check the Windows virtual key to return the Pause key instead of NumLock).

To support this we need to stop using scan codes and make use of the virtual keys instead. We'll probably still have to make some use of the scancode to pass into MapVirtualKey to get left right distinction (which the virtual key posted as part of WM_KEY* doesn't seem to do) and to check for the extended bit for some other corner cases (maybe).

**Comment by varon** [comment]
Considering the game focus of OpenTK, this is going to be closed.

See discussion at #269 

Instead, we would want to support actual text input from the OS directly, which would account for things like special characters, IME, keyboard layouts, etc.
