### ISSUE TITLE
GameWindow: Distinguish CursorVisible and CursorGrab

### ISSUE THREAD

**Issue by AdamsLair** [opentk/opentk#265]
## Problem Description

The GameWindow class currently exposes a `CursorVisible` property. However, setting it to true does not only make the cursor invisible, it also grabs the cursor while the window has focus. This may not be desired in all cases.
## Proposed Solution
- Distinguish between `CursorVisible` and `CursorGrab`.
- **CursorVisible** will hide the cursor as long as it hovers over the client area of a GameWindow. This will allow non-fullscreen games to render their own (animated, custom, etc.) ingame-cursor while not interfering with the operating system cursor.
- **CursorGrab** will grab the cursor when the GameWindow is focused. It does not necessarily need to hide the cursor as well, since the other setting would already allow this.

Alternatively, if there was support for setting the OS cursors position using the `X` and `Y` setters of a `MouseDevice`, CursorGrab could be cut out entirely, because it should be easy to emulate using CursorVisible and game code that keeps the cursor at the center of the game window.

**Comment by Frassle** [comment]
Sounds reasonable, I'll look into it. But two new properties is quite an API change so will probably have to wait for a major release to merge in.

For now another workaround you might want to try is setting the Cursor property to MouseCursor.Empty, has a similar effect to hiding the cursor but doesn't grab it. Arguably users should be setting Cursor to render their own custom cursors as well.

**Comment by SirCmpwn** [comment]
Is there any word on this?

**Comment by varon** [comment]
Closed by 4.x
