### ISSUE TITLE
Programmatically Disabling SDL2 Support

### ISSUE THREAD

**Issue by AdamsLair** [opentk/opentk#266]
As far as I can tell, there is no working GLControl when using the SDL2 backend. Not using it when requiring a GLControl is a perfectly fine workaround and I'm completely okay with that.

However, this appears to be not a viable solution when users have SDL2 in their PATH, as the .dll can be found and loaded even when not placing it in the execution directory. So, from the perspective of an OpenTK-based tools developer with game developers as a target audience (where having SDL2 in PATH is not *that* unlikely), this is [an issue](https://github.com/AdamsLair/duality/issues/192).

I'm developing an editor that is based on GLControl, and it isn't able to start as long as a user has SDL2 in their PATH. Requiring users to remove it from there is a working, but really bad solution, because they might want to have it there for other projects.

A possible solution would be to allow disabling SDL2 support in OpenTK programmatically. Something like:

```OpenTKSettings.SupportSDL2 = false;```

If there already is such functionality that I am unaware of, please disregard this issue. [It doesn't appear like there is](https://github.com/opentk/opentk/blob/7e903d6c0b313898f339a3bd108665c7ae1dfd2b/Source/OpenTK/Configuration.cs#L199) though - feel free to point me in the right direction, if I'm wrong here.

**Comment by Frassle** [comment]
Initialize the toolkit with the PreferNative flag:

    var options = new ToolkitOptions();
    options.Backend = PlatformBackend.PreferNative;
    Toolkit.Init(options);

**Comment by AdamsLair** [comment]
That looks like it should solve it. I'll check it out. Thanks!
