### ISSUE TITLE
MonoDevelop does not run custom commands in project files

### ISSUE THREAD

**Issue by mcmonkey4eva** [opentk/opentk#268]
This line here: https://github.com/opentk/opentk/blob/develop/.gitignore#L4
Why does it exist?

Source/GlobalAssemblyInfo.cs is a **REQUIRED** file for building... at least under MonoDevelop on Linux.

I was able to make it build as a workaround by adding a file under that name containing only
```
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
```

(The header copied off OpenTK's assemblyinfo).

But still... it should build without requiring guesswork + luck.

**Comment by Frassle** [comment]
That file should be auto-generated by the build process!
```
// This file is auto-generated through Source/Build.Tasks/GenerateAssemblyInfo.cs.                                      
// Do not edit by hand!
```
It woul seem MonoDevelop isn't running all our build commands for some reason!

**Comment by mcmonkey4eva** [comment]
I'm going to post this here to keep the two issues separated.

Based on
```
That should work. Can you try running xbuild from the command line (just running that from the same folder OpenTK.sln is in should work) and try running again, might just be a MonoDevelop issue. Also what version of Mono and MonoDevelop?
```
I got it to build correctly. `xbuild` does it. MonoDevelop... nope!

MonoDevelop is v4.0.12
Xbuild = 12.0
Mono = 3.2.8.0

**Comment by Frassle** [comment]
Ok. I'll track the MonoDevelop issues here and leave the other ticket for the OpenGL crash. I'll try and repo this on one of my Linux machines, in the meantime at least xbuild is a functional workaround.

**Comment by cra0zy** [comment]
My conclusion for this is:
1) It works alright with MonoDevelop 5 on Linux
2) MonoDevelop 4 is outdated... you can get the newest version from: http://www.monodevelop.com/download/
3) Don't bother supporting older versions of MonoDevelop... no point

**Comment by Frassle** [comment]
Linux support for up-to-date versions of MonoDevelop was pretty poor, but reading through that link sounds like the story is much better today. I'll agree with @cra0zy.

**Comment by mcmonkey4eva** [comment]
Gah, why does MonoDevelop not auto-update to new release versions?! Didn't even know there was one. Thanks, @cra0zy
