### ISSUE TITLE
NativeWindow: Minimum Size

### ISSUE THREAD

**Issue by ChillyFlashER** [opentk/opentk#271]
Would it be possible to support minimum size on **NativeWindow**?

**Comment by Frassle** [comment]
Leaving some links:

Win32: https://msdn.microsoft.com/en-us/library/windows/desktop/ms632605.aspx
X11: https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-normal-hints.html
OSX: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWindow_Class/index.html#//apple_ref/occ/instp/NSWindow/minSize

**Comment by varon** [comment]
Closing for now as we sadly don't have the resources to do this.

We would welcome any PR to add this functionality.
