### ISSUE TITLE
[Mono] Switching to WindowBorder.Fixed increases window size by 4 pixels

### ISSUE THREAD

**Issue by derrickcreamer** [opentk/opentk#275]
Here's another bug that appears on Windows (7) while using Mono, but not while using .NET. (Not yet tested on Linux.)

Setting WindowBorder to Fixed from either Resizable or Hidden increases both the height & width of the window by 4 pixels each, instead of staying the same as expected. (This does not happen while switching between Resizable and Hidden - only Fixed.)

Code to reproduce:

``` c#
using OpenTK;
namespace TKFixedBugReport{
    public static class BugReportMain{
        public static void Main(){
            GameWindow w = new GameWindow(200,100,OpenTK.Graphics.GraphicsMode.Default,"Testing");
            w.KeyDown += (sender, e) => {
                if(w.WindowBorder == WindowBorder.Fixed){
                    w.WindowBorder = WindowBorder.Resizable;
                }
                else{
                    w.WindowBorder = WindowBorder.Fixed;
                }
            };
            w.Run();
        }
    }
}
```

**Comment by derrickcreamer** [comment]
I'm trying to track this one down myself. Here's what I've learned so far. Most of the relevant code is in WinGLNative.cs in WindowBorder-set.

- The value of 'rect' is identical on Mono and .NET, before and after the call to Functions.AdjustWindowRectEx. This doesn't seem to be the source of the problem.

- When the bug happens, ClientSize changes when SetWindowLong and SetWindowPos are called.

- .NET and Mono report different window styles for the final 'new_style' when setting to WindowBorder.Fixed. Under .NET it is "Tiled, MinimizeBox, SystemMenu, Caption, ClipChildren, ClipSiblings", and under Mono it is "MinimizeBox, SystemMenu, Caption, ClipChildren, ClipSiblings" - Tiled is missing. I realize that TILED/OVERLAPPED have a value of zero and might be treated as defaults, but I thought this might be worth noting anyway.

**Comment by varon** [comment]
Closing as this is an ancient issue relating to a very old version of mono on windows, which isn't a supported configuration.
