### ISSUE TITLE
Extended HID Controller Support (OS X)

### ISSUE THREAD

**Issue by eswick** [opentk/opentk#277]
HID PlayStation 4 controllers are not recognized on OS X. Is it possible to have support added?

This may provide some insight:
https://github.com/slembcke/CCController

**Comment by varon** [comment]
We'll need someone with a PS4 controller and a mac to PR in a fix for this.

**Comment by eswick** [comment]
I've got both & willing to help

**Comment by varon** [comment]
@eswich - You're a hero! We'll eagerly await your help on this!

**Comment by varon** [comment]
Closing until someone cares enough to do this.
