### ISSUE TITLE
Numeric pad keys stuck given NumLock and shift held

### ISSUE THREAD

**Issue by genstein** [opentk/opentk#279]
_Tested in both the OpenTK latest release from SourceForge, 2014-07-23 (1.1.1664.6217) and on a  clone of this github repo, taken on 2015-07-06 (my debug build shows 1.1.2011.6405). Both on this machine which is Windows 7 SP1, a 64 bit i7-3930K with a junky Logitech K120 vanilla USB wired keyboard, and a Razer Imperator mouse, no other USB or input devices connected, fully Windows Update'd._

Appears to apply only to all numeric pad keys whose face values change given NumLock, so Keypad0 through Keypad9, KeypadPeriod.

To reproduce, create a new console application from Visual Studio, add a reference to OpenTK, and replace Program.cs with:

``` C#
class Program
{
    static void Main(string[] args)
    {
        for(;;)
        {
            var state = OpenTK.Input.Keyboard.GetState();
            if (state.IsKeyDown(OpenTK.Input.Key.Keypad0))
            {
                System.Console.WriteLine("Keypad0");
            }
            else
            {
                System.Console.Clear();
            }
        }
    }
}
```

Hold down either Shift key and press and then release NumPad 0 with the Shift key still held down. Keypad0 is stuck. (Compare holding down either Shift key, pressing NumPad 0, releasing the Shift key, then releasing NumPad 0. Once stuck, stop the flow by pressing and releasing NumPad0 without the Shift key held down.)

<hr>

I switched to OpenTK.Input because neither GetKeyState() nor WM_(SYS)KEYDOWN solutions can detect shifted numeric pad keys in a NumLock-agnostic fashion or tell AltGr from Ctrl + Alt; I imagine there's something equally funky happening with the Win32 Raw Input API re the numeric pad and shift.

To throw in a potential red herring, there may be a solution buried in the comment thread at https://molecularmusings.wordpress.com/2011/09/05/properly-handling-keyboard-input/ but I only took a cursory glance at a badly formatted comment so am likely utterly wrong ;) Thanks for any work on this, I'm nowhere near game release yet but I've plans for Ctrl, Alt, Shift and the numeric pad in combination (roguelike).

**Comment by Frassle** [comment]
Can you see if #269 fixes it?

**Comment by genstein** [comment]
Not exactly, but thanks to #269 and the [comment thread](https://molecularmusings.wordpress.com/2011/09/05/properly-handling-keyboard-input/) I mentioned I have a [proposed fix](https://gist.github.com/genstein/c943d44300c77945c10e), see what you think. That's a patch to be applied after #269.

This also filters out the spurious "escape sequences" the comment thread refers to, and which occur with NumLock/Pause. As a side issue, NumLock and Pause still aren't distinguished properly for me, but I don't have a good portable fix for that right now (though filtering escape sequences seems a good first step as they confuse things).

**Comment by genstein** [comment]
I could also have been clearer: the reason this proposed fix works is that the spurious shift keys it filters out are actually keyboard events which come in with a virtual key code of VirtualKeys.SHIFT but the scancode of the relevant numeric pad key. Since #269 runs these scancodes past MapVirtualKey, the code was previously translating the spurious shifts into extra up/downs, leading to an apparently stuck key.

**Comment by varon** [comment]
Closing, as this relates to #269. If this is still an issue affecting you, please feel free to open it again.
