### ISSUE TITLE
Exception: No context is current in the calling thread

### ISSUE THREAD

**Issue by shorowit** [opentk/opentk#280]
I have a .NET application that uses the OpenTK.GLControl. One of our users gets the following exception(s):

The type initializer for 'OpenTK.DisplayDevice' threw an exception.
No context is current in the calling thread (ThreadId: 1).

This occurs with both 1.1.4 as well as the latest dev code. The user has an Intel HD Graphics Family graphics card with version 9.18.10.3220 (6/24/2013). 

Can you help diagnose the issue? We have not had any other reports of similar issues for hundreds of other users.

Thanks,
Scott

**Comment by Frassle** [comment]
DisplayDevice is platform specific so I need to know which OS so I can look at the right code.

Although "No context is current in the calling thread" is generated by a GraphicsContextMissingException, and none of the DisplayDevice code should be touching any graphics context stuff.

**Comment by shorowit** [comment]
This is on the Windows operating system. Do you need the specific version of Windows?

**Comment by Frassle** [comment]
Shouldn't matter we don't have any logic based on which Windows version it is. I'll try and step through the code this weekend see if I can find what might be triggering this, a quick scan earlier wasn't very enlightening.

**Comment by Frassle** [comment]
Also if you can get a full stack trace that would be really useful.

**Comment by varon** [comment]
Closed due to age.
