### ISSUE TITLE
Exceptions when using rewrite.exe with visual studio 2015

### ISSUE THREAD

**Issue by joshuabogue** [opentk/opentk#284]
Exceptions when trying to use rewrite.exe with the visual studio 2015 due to two issues:
1. The line var fs = new FileStream(keyfile, FileMode.Open); fails and has to be changed to var fs = new FileStream(keyfile, FileMode.Open, FileAccess.Read);
2. I had to move to a new version of the Mono.Cecil.Pdb library was getting a PdbDebugException "Unknown custom metadata item kind: 6"

After I made those two changes I was able to use rewrite with visual studio 2015.

**Comment by dahliaT** [comment]
Have same issue both with latest release zip and with HEAD as of 9/7/2015 using Visual Studio 2015 community but your solution didn't work for me.

**Comment by SnowmanTackler** [comment]
I'm having the same issue.

**Comment by SnowmanTackler** [comment]
I'm only seeing this on my Windows 7 Machine.  My Windows 10 machine does not have the issue.

**Comment by IAbstract** [comment]
I'm getting the following when compiling Rewrite:

Error	1	Cryptographic failure while signing assembly 'd:\OpenTK\Source\Generator.Rewrite\obj\Debug\Rewrite.exe' -- 'Error signing assembly -- Access is denied. '	D:\OpenTK\Source\Generator.Rewrite\CSC	Generator.Rewrite

The 'ReadOnly' property will not change on the folder. When I change, the property reverts and I cannot change it.

How do I update the Mono.Cecil.pdb library? From where? (assuming I need this)

**Comment by Frassle** [comment]
Which version of Cecil helped with this 0.9.6?

**Comment by SnowmanTackler** [comment]
https://github.com/jbevain/cecil

^^ Download Mono.Cecil from here.  I used the latest version.  Build it, and replace all the Mono.Cecil*.dll binaries in the OpenTK/Dependencies/managed folder

**Comment by Frassle** [comment]
Looks like cecil is on nuget https://www.nuget.org/packages/Mono.Cecil/
As nuget seems to be the The One True Way to set up dependencies in .NET land now I'll see about reconfiguring the projects to just download it from there.

The FileStream fix should be even easier, will get that pushed up soon.
