### ISSUE TITLE
GameWindow.KeyPress KeyChar on OSX - No Unicode support

### ISSUE THREAD

**Issue by NotImplementedException** [opentk/opentk#285]
On Windows GameWindow.KeyPress returns Unicode characters.
On Mac GameWindow.KeyPress returns only ASCII code of key. Always lowercase.
How to read Unicode keyboard input on Mac?

https://github.com/opentk/opentk/blob/d12643cf442a0c0c634352bf8af574d47298304c/Source/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L571

I think this line should be modified to use "UCKeyTranslate" function.

http://stackoverflow.com/questions/22566665/how-to-capture-unicode-from-key-events-without-an-nstextview

[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=25310502)](https://www.bountysource.com/issues/25310502-gamewindow-keypress-keychar-on-osx-no-unicode-support?utm_source=25310502&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by varon** [comment]
This isn't a bug - we're relaying raw input scan codes without translation for OpenTK's current input system.

See #260, #279, etc.

If this functionality is desired,  then we'll need to PR this in as a separate input system or input event.
