### ISSUE TITLE
Keyboard is recognized as two GamePad devices

### ISSUE THREAD

**Issue by AdamsLair** [opentk/opentk#286]
I've stumbled upon a confusing issue with the latest master branch version of OpenTK: 

- There are two "phantom" GamePads connected, which appear to exhibit a constant state. 
- Upon further investigation, it turned out that the origin of these two devices is my keyboard. They disappear when disconnecting it and reappear when connecting it again.
- I'm unaware of a way to distinguish between these phantom GamePads and the real ones prior to receiving input, making it a problem in Options screens, and a nuisance in Player Select screens.
- This issue was not present in old OpenTK versions, I'm guessing around 1-2 years old, but I'm not sure which was the latest version I tested with where the issue was not present.

A screenshot of the problem: http://i.imgur.com/b4LMwpZ.png

I'm on a Windows 8.1 system, running regular .Net 4.5 and using a Logitech K200 keyboard, nothing fancy. I'm not using the SDL2 backend, as I require a GLControl. Stepping through the code led me to the WinRawJoystick class, so I guess that's the backend implementation to investigate?

Help and background information on this issue would be very much appreciated.

**Comment by Frassle** [comment]
WinRawJoystick is probably the right place to look, gamepads are just a mapping over joysticks (https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Platform/MappedGamePadDriver.cs).

https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Platform/Windows/WinRawJoystick.cs#L233 should be skipping over keyboard and mouse devices.

**Comment by AdamsLair** [comment]
> https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Platform/Windows/WinRawJoystick.cs#L233 should be skipping over keyboard and mouse devices.

Unfortunately, my keyboard identifies itself as three devices: One keyboard and two generic HID devices, so the last two punch right through.

One of them isn't able to determine its capabilities (`GetDeviceCaps` returns false), but is added as a joystick anyway, and the other one fails to map to any known axes or buttons, resulting in a joystick with zero buttons and zero axes. The corresponding mapped GamePad is somehow created anyway in both cases.

**Comment by Frassle** [comment]
Right so the first issue is probably because QueryDeviceCaps returns true at the end, which it will hit straight away if GetDeviceCaps fails, that looks wrong. The return true should be moved up into the clause where GetDeviceCaps succeeded and that default return should be false.

The other issue we probably just need a check to see if buttons and axis are both empty and to return false in that case.

**Comment by AdamsLair** [comment]
I implemented a fix in the linked Pull Request, but this leads to a strange issue of not detecting controllers depending on the context in which OpenTK is executed. Quoting from there:

- It worked perfectly fine in `OpenTK.Examples`
- However, using the same binary in my own project resulted in not detecting any controllers.
- I tracked the issue down to `HidProtocol.GetButtonCaps` in line 642 of `WinRawJoystick.cs` behaving differently depending on whether OpenTK was run from within the Examples project or my own. All calls to the mentioned function failed with a Win32 error code of 203 - but not in the Example browser. I have no idea why this is. Any insight appreciated.

**Comment by AdamsLair** [comment]
Actually, this might have something to do with the controller being a standard XBox360 Gamepad and thus likely being an XInput device. Maybe XInput devices still need to pass the `QueryDeviceCaps` check, even if retrieving HID device capabilities fails?

If this is the case, then `HidProtocol.GetButtonCaps` behaving strangely context-dependent and passing in the `Examples` project while failing in my own might be insignificant, or the result of "undefined" behavior. Not sure though.

Looking at the commit history of `WinRawJoystick.cs`, @thefiddler probably has a better idea of its inner workings - any word on this?

**Comment by mrhelmut** [comment]
I'm having trouble with this issue too.
Is there any progress?

**Comment by mrhelmut** [comment]
Got it. #335 

You were both right, it is required that ```QueryDeviceCaps``` fails correctly to avoid HID devices with no capability to be added, while still allowing XInput device to pass. XInput devices are supposedly HID-compliant, but for some reason, this can fail (maybe when the device is successfully acquired by XInput).

cc @AdamsLair
