### ISSUE TITLE
WindowInfo has invalid handle

### ISSUE THREAD

**Issue by Dia6lo** [opentk/opentk#290]
I tried this:

    [DllImport("user32.dll", SetLastError = true)]
    static extern uint GetWindowLong(IntPtr hWnd, int nIndex);

    // Somewhere next
    const int GWL_STYLE = -16;
    var windowHandle = WindowInfo.Handle;
    var style = GetWindowLong(windowHandle, GWL_STYLE);
    var error = Marshal.GetLastWin32Error();
And after this code i have 0 in style and 1400 in error. As https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms681385(v=vs.85).aspx states, error 1400 is for invalid window handle.

**Comment by Frassle** [comment]
That's not really enough of a repro case. How did you create the GameWindow? at what point are you calling GetWindowLong? Does it work apart from this method call?

**Comment by Dia6lo** [comment]
Huh, it was quite, sorry for delay. We've got this error in old version and haven't got it again. I guess this issue can be closed.
