### ISSUE TITLE
DSA version of TexPageCommitmentExt is missing

### ISSUE THREAD

**Issue by AlexHild** [opentk/opentk#294]
Currently the non DSA version of sparse texture commitment is implemented:

GL.Arb.TexPageCommitment =>

void TexPageCommitmentARB(enum target,
                                  int level,
                                  int xoffset,
                                  int yoffset,
                                  int zoffset,
                                  sizei width,
                                  sizei height,
                                  sizei depth,
                                  boolean commit);

The DSA version is missing:

void TexturePageCommitmentEXT(uint texture,
                                      int level,
                                      int xoffset,
                                      int yoffset,
                                      int zoffset,
                                      sizei width,
                                      sizei height,
                                      sizei depth,
                                      boolean commit);

**Comment by varon** [comment]
It should be here. Grepping through the source revealed
```static extern void glTexturePageCommitmentEXT(UInt32 texture, Int32 level, Int32 xoffset, Int32 yoffset, Int32 zoffset, Int32 width, Int32 height, Int32 depth, bool resident);```
