### ISSUE TITLE
Drm Cursor Hot Point

### ISSUE THREAD

**Issue by jpbruyere** [opentk/opentk#296]
It looks like drmModeMoveCursor does not remember HotXY for cursor, so to have it correct:

`Drm.MoveCursor(d.FD, d.Id, p.X - Drm.CurrentCursor.X, p.Y - Drm.CurrentCursor.Y);`

That's an ugly hack, maybe you'll find a better place to make it work.

**Comment by varon** [comment]
@nihlus  - Reckon we can close this? What's the deal here?

**Comment by Nihlus** [comment]
I don't see anything in libdrm that promises to remember anything about the x or y coordinates of the cursor. Furthermore, OpenTK's use of libdrm is strictly a direct binding to whatever libdrm does itself.

@jpbruyere Please provide more detailed information on what you expect to happen, what does happen, and any relevant documentation for this function from libdrm.

In the meantime, I'm closing this issue.

**Comment by jpbruyere** [comment]
@Nihlus : The problem is in libdrm, I'll make a bug report there. Thx.

**Comment by varon** [comment]
Cheers for letting us know, @jpbruyere.

**Comment by jpbruyere** [comment]
@varon: this could have been handled in otk with this dirty fix.
