### ISSUE TITLE
OpenTK.csproj: error : Command 'mono ./Rewrite.exe /OpenTK.snk -debug' exited with code: 255.

### ISSUE THREAD

**Issue by renanyoy** [opentk/opentk#299]
can't build opentk on osx and Linux with xamarin studio since I updated with the last version

**Comment by Frassle** [comment]
Can't replicate with mono develop on Ubuntu. Have the cecil packages been fetched from nuget?

**Comment by renanyoy** [comment]
Ok, tried you solution and it works; 
but if I use my solution and include rewrite and openTK projects in my solution, it doesn't build.
you have a clue on what change you made that can break the possibility to include openTK in another solution ?

**Comment by renanyoy** [comment]
Ok, find it.
it's because you replaced the relative path from projects, by relative path from solution in the after build commands
