### ISSUE TITLE
System.DllNotFoundException: openal32.dll 

### ISSUE THREAD

**Issue by renanyoy** [opentk/opentk#300]
if I build Opentk with the command line on linux, I get this error at runtime:

System.DllNotFoundException: openal32.dll
  at (wrapper managed-to-native) OpenTK.Audio.OpenAL.Alc:OpenDevice (string)
  at OpenTK.Audio.AudioDeviceEnumerator..cctor () [0x00026] in <filename unknown>:0

**Comment by renanyoy** [comment]
it was working nicely before..

**Comment by Frassle** [comment]
openal32.dll not libopenal.so.1? Odd.

**Comment by Frassle** [comment]
Might be related to this https://github.com/mono/MonoGame/issues/657

**Comment by bsclifton** [comment]
I was getting this too on Ubuntu... what solved it for me was marking OpenTK.dll.config as "content" and specifying to copy it to the output directory.  Like it says in https://github.com/mono/MonoGame/issues/657, this shouldn't be needed.  I'm not sure why the project template didn't do this?

**Comment by varon** [comment]
OpenTK.dll.config is expected to come in as content. This is done automatically when you install the NuGet package.

Closing.
