### ISSUE TITLE
GameWindow emits wrong (?) MouseLeave / MouseEnter events while MouseButton pressed

### ISSUE THREAD

**Issue by ilexp** [opentk/opentk#301]
When holding a mouse button while hovering the OpenTK `GameWindow` with the mouse cursor, `MouseEnter` and `MouseLeave` events are emitted continuously, in addition to `MouseMove`. 

You can easily spot this behavior when launching the `GameWindow States` Example and take a look at the "Mouse inside / outside" debug text while holding a mouse button and moving around: The text suddenly states that the mouse is "outside", even though it clearly is inside the window - which is caused by reacting to the aforementioned mouse events, which seem to be fired erroneously.

This throws some input tracking game code (especially for windowed games) off tracks, and while there is a workaround available, this seems counter-intuitive.

**Comment by Frassle** [comment]
Platform?

**Comment by ilexp** [comment]
> Platform?

Windows, without SDL2

**Comment by Frassle** [comment]
Thanks I'll look into it tomorrow.

**Comment by Frassle** [comment]
Had time to look at it today. Can you confirm that the above pull request fixes the issue.

**Comment by ilexp** [comment]
Can confirm! Seems to be fixed.
