### ISSUE TITLE
Application behaves unstably inside debugging environment.

### ISSUE THREAD

**Issue by ThatOneCheetah** [opentk/opentk#303]
https://youtu.be/xzCrnKDhIEs

Running OpenTK 1.1.0.0, Visual Studio 2013 on .NET 4 Framework (NOT client profile)
Updaterate = 200/sec
Framerate = 60/sec

Application works properly outside of debugging environment but not inside (???)

**Comment by ThatOneCheetah** [comment]
It seems that the updaterate and framerate is halved inside of visual studio.

**Comment by ThatOneCheetah** [comment]
?!?, Framerate is set to 60.0, when vsync is applied the actual framerate inside of VS is 20.0, without vsync it is 30.0 and outside of vs it is always 60.0???

**Comment by Frassle** [comment]
Firstly can't replicate exactly what your describing. Secondly running a debug build with the debugger attached isn't designed to run at full speed. Thirdly 200/sec update rate is REALLY high. Most games get by with 30 or less.

**Comment by ThatOneCheetah** [comment]
I understand that 200/sec is high, but as this will be a rhythm game I cannot go lower than the frames/sec or the game might feel unresponsive.

**Comment by Frassle** [comment]
Well there's not really anything we can do to make code built with debug features and with a debugger process attached run as fast normal release code, hopefully the slow down isn't enough to impact testing. 

The odder thing with this is that vsync seems to be behaving oddly. Can you run some tests and fill in the following numbers:

Test | Build | Fullscreen | VSync | F5 FPS | Ctrl + F5 FPS | Outside VS FPS
------ | --------------- | ------------- | -------- | ---------- | ----------------- | --------------------
1 | Debug | True | On | - | - | -
2 | Debug | True | Off | - | - | -
3 | Debug | False | On | - | - | -
4 | Debug | False | Off | - | - | -
5 | Release | True | On | - | - | -
6 | Release | True | Off | - | - | -
7 | Release | False | On | - | - | -
8 | Release | False | Off | - | - | -

Hope to see if it's debug, windowed mode, vsync, the debugger or visual studio that's causing the framerate drop.

**Comment by ThatOneCheetah** [comment]
Test 	Build 	Fullscreen 	VSync 	F5 FPS 	Ctrl + F5 FPS 	Outside VS FPS
1 	Debug 	True 		On 	30 	60		60
2 	Debug 	True 		Off 	30 	60 		60
3 	Debug 	False 		On 	30 	60 		60
4 	Debug 	False 		Off 	30 	60 		60
5 	Release True 		On 	30 	60 		60
6 	Release True 		Off 	30	60 		60
7 	Release False 		On 	30 	60 		60
8 	Release False 		Off 	30 	60 		60

**Comment by Frassle** [comment]
Ok so that looks like it's only when a debugger is attached. It's possible that your graphics driver is detecting that and changing behavior. I'll do some browsing but I don't think there's anything we can do about it.

**Comment by ThatOneCheetah** [comment]
The update rate also behaves oddly with the debugger attached, afaik this shouldn't have anything to do with the graphics driver.

**Comment by Frassle** [comment]
I'd expect the update rate to slow a little, at 200 updates/sec it's only got 5ms per update. It doesn't take much to go over that, and the extra prints from having the debugger attached is probably enough. I'll do some more tests but I don't have high hopes for solving this.

**Comment by ThatOneCheetah** [comment]
I've tried running at lower update rates, same results, even at update rates of 15 / 30.

**Comment by varon** [comment]
Related to an ancient version. This doesn't seem to be a current problem.
