### ISSUE TITLE
The "MaxComputeWorkGroupCount" parameter is absent among indexed parameters

### ISSUE THREAD

**Issue by FatumR** [opentk/opentk#305]
There is no way to get the value for GL_MAX_COMPUTE_WORK_GROUP_COUNT in OpenTK. The GL.GetInteger should be used for this purpose, but "MaxComputeWorkGroupCount" is presented only enums "All" and "ArbComputeShader". Please. fix it.

**Comment by Frassle** [comment]
As a work around you can always cast from the All enum to the one required

    (GetPName)All.MaxComputeWorkGroupCount

**Comment by FatumR** [comment]
Right (one correctness it should be GetIndexedPName), but for me as a new user of the library I spent a lot of time to figure out if this constant is exists at all in the library. Btw, the similar situation MaxShaderStorageBlockSize.

**Comment by varon** [comment]
Solved by casting like a lot of parameters require.
