### ISSUE TITLE
OpenTK without System.Drawing.DLL

### ISSUE THREAD

**Issue by SirusDoma** [opentk/opentk#316]
I'm creating a simple game engine that should stay away from referencing System.Drawing.DLL for some reasons.
However, OpenTK seems depend on it.

There several questions regarding this situation:
1. Is it possible to compile OpenTK without relying on System.Drawing.DLL? are the framework heavily depend on it?
2. In most OpenTK example, Texture loaded using BMP Constructor, is it possible to load texture with another method that not depend on System.Drawing.DLL? if so, can someone provide me example codes?

**Comment by SirusDoma** [comment]
It's seems I found that OpenTK can be compiled using two conditionals compilation symbols that can replace the System.Drawing.DLL.

The symbols are `MINIMAL` and `NO_SYSDRAWING`, by doing so it replace System.Drawing objects into custom created classes / structs that defined under `Minimal.cs`.

However, seems a lot of implementations isn't defined yet, especially the `Bitmap`, `BitmapData` and `Image` class, I also notice that "Minimal" version of OpenTK might intended for mobile purpose, but I think it will good idea to bring it on everywhere, not only mobile.

So my questions.. are the devs going complete the "Minimal" implementations? if so, can someone clarify approximate releases (or time) before it can be use?

**Comment by mellinoe** [comment]
The `MINIMAL` build configuration should be usable, but like you noticed you will need to supply your own image/texture data from some other library, that isn't built into OpenTK at all. Take a look at something like https://github.com/JimBobSquarePants/ImageProcessor, it could work for you depending on what platforms you are trying to target.

**Comment by SirusDoma** [comment]
I tried to use `MINIMAL` build configuration, but it's seems that `GL.Viewport` defined twice, because the one that relies on System.Drawing.DLL still there..
And also, I think you need to add `Assert` function on your wrapper `Debug` class.

About texture loading, do I really need to upload the pointer of bmp lockbits / constructor into the `GL.TexImage2D` parameter? can I load the image into array of byte and just pass them?

To be honest, I'm not really sure what kind data that passed into GL.TexImage2D

**Comment by mellinoe** [comment]
> I tried to use MINIMAL build configuration, but it's seems that GL.Viewport defined twice, because the one that relies on System.Drawing.DLL still there..

Yes, you're actually right. The MINIMAL build doesn't work right now because of those issues. I thought it was working at this point because there was a recent PR that was fixing some of these issues up. I hadn't tried to build it any time recently, but I just synced to the head of develop, and it doesn't work like you said. I've been using OpenTK from another branch, basically the same as the one in this PR: https://github.com/opentk/opentk/pull/308, but it is actually based off of the MINIMAL build configuration.

You basically just need to delete those extra definitions of GL.Viewport, I think they actually never make sense to be there. You will also need to declare a dummy for Debug.Assert, like you said.

> can I load the image into array of byte and just pass them?
To be honest, I'm not really sure what kind data that passed into GL.TexImage2D

Essentially, yeah, you can do that. You just need to pass a pointer to the start of the image data, stored  how you have it. However, you need to pass other parameters, like the width, height, pixel format, etc. which you need to track somehow. So it probably won't be very convenient to just store a byte array for your image data. The System.Drawing.Bitmap class has all that extra information on it, but if you use another library then you will need to figure out how that information is exposed there.

**Comment by SirusDoma** [comment]
> You basically just need to delete those extra definitions of GL.Viewport, I think they actually never make sense to be there. You will also need to declare a dummy for Debug.Assert, like you said.

I wrapped those extra definitions to `#if !MINIMAL` and added `#elif MINIMAL` to get it work, also I declare `Debug.Assert` and finally, it's compiled!

> Essentially, yeah, you can do that. You just need to pass a pointer to the start of the image data, stored how you have it. However, you need to pass other parameters, like the width, height, pixel format, etc. which you need to track somehow. So it probably won't be very convenient to just store a byte array for your image data. The System.Drawing.Bitmap class has all that extra information on it, but if you use another library then you will need to figure out how that information is exposed there.

To be honest, I'm not really good at pointers. but it's seems i got the idea there.
However, I just noticed there is `T8[]` and `T8[,]` overload, I wonder if i could just pass the array of byte there.. (I cannot test this for a while)

I'm also considering to build a simple image processor to workaround against this that would fit for OpenTK usage.

The another problems arise from removing System.Drawing.dll is Text Rendering.
AFAIK, most OpenTK Text Rendering examples really depend on `System.Drawing.Graphics`

Is it possible to render without that? if so, can you give me an example code?

**Comment by mellinoe** [comment]
> To be honest, I'm not really good at pointers. but it's seems i got the idea there.
However, I just noticed there is T8[] and T8[,] overload, I wonder if i could just pass the array of byte there.. (I cannot test this for a while)

Yeah, OpenTK has overloads that let you just pass in arrays as well, which could be convenient depending on how your data is stored. I would guess that it is pinning the array behind the scenes and passing the pointer that way (just a guess).

I would guess that adding image processing directly into OpenTK is probably a bit outside the scope of what the library is supposed to do (just wrap OpenGL). There are some other image processing libraries, but most of them either build on top of System.Drawing or don't support all the way down to .NET 2.0. If you don't want to use System.Drawing (I believe it's supported on .NET 2.0 though, right?), your best bet might be to fork another project like the above and try to cross-compile it for .NET 2.0.

And yeah, text rendering will also be something you'll need a library for without System.Drawing. You can look at something like https://github.com/Robmaister/SharpFont, but I don't have any experience with it and it will definitely be more difficult than using System.Drawing.

**Comment by SirusDoma** [comment]
OK, I finally figure out how to compile the ImageProcessor in .NET 2.0
However, it's seems the texture isn't loaded properly.

here the codes I use to load the image into opengl texture:

```
            // Check if the Texture is already disposed
            if (IsDisposed)
                throw new ObjectDisposedException(ToString());

            // Generate Texture Name (if not exist)
            if (_textureId <= 0)
            {
                GLChecker.Check(() => GL.GenTextures(1, out _textureId));

                // Check whether the texture name has been generated properly.
                if (_textureId <= 0)
                    // Return false because its not created properly..
                    return false;
            }

            Width = image.Width;
            Height = image.Height;

            // Bind Texture to Upload Texture Image
            Texture.Bind(this);

            // Upload Texture Image
            GLChecker.Check(() => GL.TexImage2D(
                TextureTarget.Texture2D,
                0, // level
                PixelInternalFormat.Four,
                image.Width, image.Height,
                0, // border
                PixelFormat.Bgra,
                PixelType.Float,
                image.Pixels
                ));

            // Apply Smooth Filter (Default: Smoothed)
            GLChecker.Check(() => GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter,
                ((_isSmooth) ? (int)TextureMinFilter.Linear : (int)TextureMinFilter.Nearest)));
            GLChecker.Check(() => GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter,
                ((_isSmooth) ? (int)TextureMagFilter.Linear : (int)TextureMagFilter.Nearest)));

            // Apply Repeat Filter (Default: No Repeat)
            GLChecker.Check(() => GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapS,
                (_isRepeated ? (int)TextureWrapMode.Repeat : (int)TextureWrapMode.ClampToEdge)));
            GLChecker.Check(() => GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapT,
                (_isRepeated ? (int)TextureWrapMode.Repeat : (int)TextureWrapMode.ClampToEdge)));

            // Unbind Texture
            Texture.Bind(null);
            return true;
```

When I render it, no texture appear in my game
Any ideas?

**Comment by SirusDoma** [comment]
Nevermind, I figure it out already!

My first though that this was impossible.
But with your help, finally I able to figure out how to make my game run without System.Drawing.dll
Many Thanks!!
