### ISSUE TITLE
SDL2 not generating joystick events unless in a gamewindow

### ISSUE THREAD

**Issue by leezer3** [opentk/opentk#317]
Build a Windows Forms application, and use OpenTK to take input from a joystick, via Joystick.GetState()
If the SDL2 backend is used, then unless a GameWindow is running, then Joystick.GetState() returns 'Released' for all buttons, and all axis appear centered.

As far as I can see, it's correctly initializing the SDL joystick subsystem (As evidenced by the fact that the joystick capabilities are correctly enumerated), but somewhere along the line the events are getting dropped when the GameWindow is not active.
I'm not entirely sure this is intended to work, but it does with the other backends.

It's not so much a big deal; This is just causing my menu based control configuration to break on some systems, but would like to know if it should work before trying to rewrite the configuration system :)

**Comment by varon** [comment]
@leezer3 if this is still affecting you after the input changes in #453, please re-open the issue.
