### ISSUE TITLE
OpenTK.Graphics.OpenGL.GL.ProgramUniform1(Int32 program, Int32 location, Int32 count, Single[] value) does not exist

### ISSUE THREAD

**Issue by GiefSeMoney** [opentk/opentk#323]
Whereas
OpenTK.Graphics.OpenGL.GL.ProgramUniform2(Int32 program, Int32 location, Int32 count, Single[] value)
OpenTK.Graphics.OpenGL.GL.ProgramUniform3(Int32 program, Int32 location, Int32 count, Single[] value)
OpenTK.Graphics.OpenGL.GL.ProgramUniform4(Int32 program, Int32 location, Int32 count, Single[] value)
exist.

**Comment by Frassle** [comment]
This overload is now generated. Was fixed by 7e5b937bc51b1cee8e11bae50806db19f9303615, which regenerated bindings with new Khronos XML specs which had been updated to set "value"'s count attribute to "count" instead of "1".
