### ISSUE TITLE
OpenTK Native Compilation with .NET Core

### ISSUE THREAD

**Issue by SirusDoma** [opentk/opentk#324]
Now, we are able to compile OpenTK with `MINIMAL` Configuration Build and able to run without `System.Drawing`.

I got few question about this:
1. Is `MINIMAL` version of OpenTK is compatible with .NET Core?
2. If I was not mistaken, .NET Core provide native compilation with `dotnet compile --native --cpp` (I know it's not yet done and not ready yet for real application), will OpenTK support this?

I did some quick research with alternative native compilation based on .NET Core with [csnative](https://csnative.codeplex.com), however it's not working due to Post Build action that performed by OpenTK (`Rewrite.exe` the built binaries) [here](https://csnative.codeplex.com/workitem/6) the details.

I know native compilation that provided by .NET Core might have different mechanism, however I just need some clarification whether this library will play nicely with that stuffs.

Thanks in advance!

**Comment by Frassle** [comment]
Related to #308

**Comment by SirusDoma** [comment]
Oh that's good, so we'll have OpenTK that works well with .NET Core.
Now the question will be Native compilation.

I'm not sure that native compilation will works against generated library, but I hope opentk work with it

**Comment by Frassle** [comment]
From codeplex:
> you should not use the generated library as it will not work but it will generate C code which could be compiled but the next step is to remove all method which throw "NotImplementedException" and replace then with actual native API call

That is what the rewite step does. In the C# code all the OpenGL methods are just

    { throw new NotImplementedException(); }

So when the C# compiler compiles OpenTK that's what the MSIL is to start with. But Rewrite looks up all those methods (any method with an AutoGenerated attribute) and changes it's MSIL code to something like

    // void ActiveShaderProgram(int32 pipeline, int32 program	) cil managed 
    IL_0000: ldarg.0
    IL_0001: ldarg.1
    IL_0002: ldsfld native int[] OpenTK.Graphics.OpenGL4.GL::EntryPoints
    IL_0007: ldc.i4.0
    IL_0008: ldelem.i
    IL_0009: calli System.Void(System.UInt32,System.UInt32)
    IL_000e: ret

This loads the two arguments passed in, loads the entry point function pointer table and fetches the function pointer for this method from it and then does a **calli** instruction to call the function pointer with the given arguments.

If I had to take a guess at whats causing csnative to fail it would be that **calli** instruction.

**Comment by SirusDoma** [comment]
I see!
you make things more clearly now
however, it's seems not gonna be a problem if csnative cannot handle it / opentk isnt compatible with it

but I hope it is compatible on .NET Core, including the native compilation that provided by .NET Core, I don't know the mechanism, but i got no luck with it, I can't even do native compilation of hello world project, it seems still long way to go

But im getting excited about this, imagine create native game with OpenTK and C#
That's would be cool man!

**Comment by manu-silicon** [comment]
As mentioned, thanks to #308, I have OpenTK running under CoreCLR on Windows. I'm now working on running it for CoreCLR on Linux. Once this is working, I do not see why it will not work with CoreRT (aka .NET native) once it is fully implemented.

**Comment by Labris** [comment]
Here are my 2 cents regarding this.

I would say there is no hurry to go with new .net coreclr just yet., mainly because it's missing some much needed features that opentk needs (would cause lot of rewriting).

Most notable is missing of dllmap, discussion here: [https://github.com/dotnet/coreclr/issues/930](url)
Without dllmap, all P/Invoke's would need to made differently for each OS/library combo supported, one route to achieve this would be to get rid of rewrite (to get rid of cecil and to allow easier framework version jumping) and do code generator for OpenGL wrapping, kinda like what Mono guys did with Vulkan:  [https://github.com/mono/VulkanSharp](url). Then make different versions of generated files based on OS/ library scheme. And of course as said earlier, even after supporting new coreclr, jumping to native compilation would require getting rid of rewrite step anyhow.

Another route would be to keep coreclr opentk windows only and wait for dllmap to popup (this can happen at near or far future, or not at all, as you can see how derailed discussion of it has gone now and then in coreclr issue).

And yet another would be to stay within .net 4.5 and mono. As mono has been taking some gigantic steps forward with stability and feature support thanks to microsoft open sourcing.

Then there is complete reworking, get rid of rewrite, bring in other things that coreclr offers (simd vectors), then wait for dllmap (propably needs voicing need of it towards coreclr/corefx team). This would most likely mean totally new take on OpenTK.

**Comment by manu-silicon** [comment]
@Labris As of today, I have OpenTK working both on Windows and Linux with CoreCLR. I only use the Minimal version of OpenTK for this as I mostly needed the OpenGL wrapping part. I do not remember doing anything special to make this work.

**Comment by Labris** [comment]
@manu-silicon I take that you are using mono mscorlib, as mono implements dllmap there, have you tried running it with corefx version of mscorlib [https://github.com/dotnet/corefx](url)

**Comment by manu-silicon** [comment]
Actually I do not use Mono. The end result is using mscorlib coming from CoreCLR and all the assemblies from CoreFX.

**Comment by mellinoe** [comment]
As @manu-silicon said, OpenTK works fine with minimal changes on CoreCLR, at least on Windows and Linux. I actually have created a [NuGet package](https://www.nuget.org/packages/OpenTK.NETCore/)  which I use for a lot of my projects targeting CoreCLR.

You are correct in that CoreCLR/.NET Core has no concept like "dllmap". This can be circumvented by compiling separately for each platform (and simply referencing the appropriate native library). Regardless, this doesn't seem to be necessary at all. OpenTK doesn't use PInvokes for most of the main functionality (GL calls), it uses `calli`, with manually-loaded function pointers. I'm sure that there are bugs related to this that probably need to be fixed, but I've never hit them (i.e. I've never hit a `DllNotFoundException`). It looks like most of the dllmap entries are for things like X11 and SDL2, which are probably only hit in fallback cases anyways (X11 isn't the default on OSX, and SDL2 isn't the default on Linux).

Regarding the IL rewriting that Generator.exe does here: Why is that a problem? There were some changes that needed to be made there to accomodate .NET Core as well, but it wasn't too complicated.

**Comment by Labris** [comment]
@mellinoe Regarding IL rewriting, as @SirusDoma said and what this issue originally is about, is native compiling with coreclr, but mainly how it seems to work it should eat IL assemblies, so rewriting isn't really problem there, unless native compiling cannot for some reason handle what it produces.

Another part in Rewriting IL vs. Generating/Rewriting cs files is how much there is under the hood action and steps involved. If you think .NET as building a computer, then writing cs is like putting components together, tweaking IL is more closer to soldering new jumps on motherboard to get more current to somewhere (as in needs more tools and time to do / debug / change). Performance wise `calli` is surely faster than standard pinvoke, but alternatives on c# side are pinvokes with suppressed security and generating `calli` and other opcodes with `ILGenerator`. Then there is IL rewriting being extra step in build process meaning that as .net evolves and rolls around, there may again be need to tune IL rewriter when pure c# approach wouldn't need nothing. 

Then there  is legacy factor, as OpenTK development has been quite roller coaster, there may be point at future when there is no one around that can fast do anything to rewriter which leads to situation who and with what skills can use OpenTK on what ever new platform has come to light.
In this case there is also need to factor in Mono.Cecil and its future. As seeing that Mono is going through lot of changes and it's unknown if it will be around for how long (Currently there are still distinctive uses for Mono project, but how MS is going around with .net open sourcing, policies and Xamarin, there will be point in future when Mono becomes redundant and either starts to wither away or gets integrated with .NET).

But then, with current minimal, dllmap isn't needed (probably some dark magic library name shmucks in coreclr), but then there has risen new question, does SDL2 work with it?

**Comment by feliwir** [comment]
How are things looking with .Net core 2.0?

**Comment by Frassle** [comment]
The plan is do one more release targeting .NET Framework 2.0, which will be the 3.0 release. After that we will target .netstandard 2.0 and release that as OpenTK 4.0.  It's still a while off, we need to do 3.0 first!

**Comment by WinInsider** [comment]
Are there specific set of APIs in .NET Standard 2.0 that are used by OpenTK that are missing in .NET Standard 1.3?  If was possible to get away with running on lower/broader .NET Standard version...

**Comment by Nihlus** [comment]
There are numerous APIs that are in 2.0 that aren't in earlier versions of the standard which OpenTK depends on. Targeting a lower standard would be difficult at best.

**Comment by WinInsider** [comment]
@neico, there is [NuGet](https://www.nuget.org/packages/OpenTK.NETCore/) package of OpenTK by @mellinoe that targets .net standard 1.3

**Comment by Nihlus** [comment]
@WinInsider Not at this point, no - that branch has diverged too far from the main branch to be easily merged. On top of that, we are planning some rather sweeping changes to the library moving forward.

**Comment by ilexp** [comment]
Would appreciate a lower .NET Standard version than 2.0 as well. Are there specific roadblock preventing going with 1.3?

**Comment by Nihlus** [comment]
@ilexp 
1.3 lacks a bunch of API that OpenTK uses. If you need 1.3, please chip in and help us port it.

**Comment by ilexp** [comment]
Alright, makes sense 🙂 Thanks!

**Comment by varon** [comment]
Super old issue. Will need to revisit this post 4.0.
