### ISSUE TITLE
GL.DrawBuffer(DrawBufferMode.ColorAttachment0) arise GLError INVALID_ENUM

### ISSUE THREAD

**Issue by SirusDoma** [opentk/opentk#327]
I tried to implement FBO
so, before the rendering process begin, I use following code to define the draw buffer mode:

```
GL.DrawBuffer((DrawBufferMode)FramebufferAttachment.ColorAttachment0Ext)
```

But it give me INVALID_ENUM error, also I tried to use the one from `DrawBufferMode` enum, since it has equal integer with `FramebufferAttachment` (36160)

```
GL.DrawBuffer(DrawBufferMode.ColorAttachment0);
```

but still give me same error.
I think it's a bug, because it doesn't accept any enum.

**Comment by varon** [comment]
This looks like a usage error. Please re-open with a full test case if this is affecting you still.
