### ISSUE TITLE
Operators for Matrix/Vector and Quaternion/Vector transformation

### ISSUE THREAD

**Issue by varon** [opentk/opentk#329]
Unity3D offers a multiplication operator for [Matrix-Vector transformation](http://docs.unity3d.com/ScriptReference/Matrix4x4-operator_multiply.html), as well as [Quaternion-Vector transformations](http://docs.unity3d.com/ScriptReference/Quaternion-operator_multiply.html)

I would suggest that we implement this operator as follows:
  * `(*) (Mat3, Vec3) -> Vec3`
  * `(*) (Mat4, Vec4) -> Vec4`
  * `(*) (Quaternion, Vec3) -> Vec3`
  * `(*) (Quaternion, Vec4) -> Vec4`

It would greatly cut-down on code verbosity to have this available.

If this were to be done in a PR, would you accept this?

**Comment by WardBenjamin** [comment]
I definitely support this. We definitely have Matrix4.Transform(Vec4), for example, and I like how you kept these internally.

**Comment by cra0zy** [comment]
Closing since the operations were added.

**Comment by arekbulski** [comment]
Matrix4 still does not support matrix4*vector3 nor has a Transform method.

**Comment by winterhell** [comment]
Technically Matrix4*Vector3 is undefined. Do you pad the Vector to Vector4 with W = 1, and then return only the XYZ of the result?

**Comment by arekbulski** [comment]
Ah appologies, I meant there is no Matrix3*Vector3. But I also extend with W=1 and such.

**Comment by varon** [comment]
I do believe we expose two operations `Vector3.TransformPosition` and Vector3.TransformNormal` which might be what you're looking for.
