### ISSUE TITLE
Mac OS: NSView, OpenTK and NullReferenceException

### ISSUE THREAD

**Issue by bchavez** [opentk/opentk#330]
Hello,

I'm having a hard time getting an `NSView` (from MonoMac) working with OpenTK working on **mac**.

I'm working on a Map Editor for a game. My map editor has two GL surfaces as shown below:

![Map Editor](https://raw.githubusercontent.com/bchavez/SharpFlame/eto/graphics/Screenshot1.jpg)

Left surface shows loaded terrain textures (via GL) and right side is the 3D rendered map (via GL). On **windows** and **linux** everything works perfectly. Both GL surfaces share texture graphic contexts.

**Mac**, however, has been somewhat of a pain.  On the **mac** platform, both left and right panels are `NSView`s. I cannot get shared contexts between both surfaces using OpenTK.
### Attempt 1

Originally, I tried manually creating an `NSOpenGLContext` (from MonoMac) and passing it to OpenTK _as an externally created_ context, but didn't get very far. I get a somewhat related issue: https://github.com/opentk/opentk/issues/52 where `CreateDummyContext` that kept throwing a "key not found" exception.
### Attempt 2

My current attempt is to try and use `CreateMacOSWindowInfo` and hopefully have OpenTK manage both graphics contexts automatically. However, my current attempt runs into a `NullReferenceException` when I use any of the GL methods like `GL.ClearColor`. My current code is here: https://github.com/bchavez/SharpFlame/blob/eto/source/Eto.Gl.Mac/MacGLView8.cs#L115

```
public void InitGL()
{
  OpenTK.Graphics.GraphicsContext.ShareContexts = true;

  var gpxMode = GraphicsMode.Default;

    this.windowInfo = OpenTK.Platform.Utilities.CreateMacOSWindowInfo(this.Window.Handle, this.Handle);

  this.openTK = new OpenTK.Graphics.GraphicsContext(gpxMode, this.windowInfo, 1, 0, GraphicsContextFlags.ForwardCompatible);

  this.openTK.MakeCurrent(this.windowInfo);

  //Null Reference Exception Here
  GL.ClearColor(OpenTK.Graphics.Color4.CornflowerBlue);

  this.IsInitialized = true;
```

![screen542](https://cloud.githubusercontent.com/assets/478118/12082074/f6623858-b240-11e5-8693-f8eec416e065.png)

My guess is, OpenTK didn't setup the `GraphicsContext` I received correctly, somewhere.

My open source project can be found here: https://github.com/bchavez/SharpFlame/

I'd appreciate it if anyone could help me solve this issue.

Thanks,
Brian

**Comment by varon** [comment]
@UnknownShadow200  - here's a mac issue that would be worth looking at.

**Comment by UnknownShadow200** [comment]
Don't have OSX I'm afraid

**Comment by deccer** [comment]
No sure if its still alive, but i noticed
`this.openTK = new OpenTK.Graphics.GraphicsContext(gpxMode, this.windowInfo, 1, 0, GraphicsContextFlags.ForwardCompatible);
` the `1, 0` in there looks like you are creating a 1.0 GL context? Or what is 1, 0 there for in that particular instance.

If so, if you are using still legacy opengl, try going with `2, 1` instead. If no legacy gl is used (no glMatrixMode, glBegin, glEnd, glVertex, ...) then try going with `3, 3`

**Comment by varon** [comment]
Presumably closed by 4.x
