### ISSUE TITLE
Scrolling with GLControl

### ISSUE THREAD

**Issue by Phyyl** [opentk/opentk#338]
I have a GLControl inside a Panel that is scrollable (AutoScroll = true). When I scroll, the back GLControl gets all messy and glitchy. I thought maybe it was not refreshing, so I called its Invalidate method from the parent Panel when the latter is scrolled or resized. It's a bit better, but it's now flickering on every scroll increment.

To reproduce this, you can simply put a GLControl that is larger than the form, setting the form's AutoScroll property to true and clearing the OpenGL color bit buffer with a color of your choice in the OnPaint event.

**Comment by varon** [comment]
Closing due to age and lack of repro/platform information. If this is still affecting you, please re-open it.
