### ISSUE TITLE
Why does GLControl now derive from System.Windows.Form

### ISSUE THREAD

**Issue by rhegner** [opentk/opentk#341]
I tried to switch from (non-NuGet) version 1.1.2 to the latest NuGet version 1.1.2225.

When loading my forms which contain a GLControl derived control in the Visual Studio designer I got the exception "Top-level control cannot be added to a control". The same exception also appears at runtime.

I noticed in the Object Browser that GLControl is derived from System.Windows.Form. For this reason it cannot be placed on a from. I had to go back to version 1.1.1589.5942 of OpenTK.GLControl, where the GLControl is derived from UserControl (as it should, in my opinion).

Was this change from UserControl to Form as the base class for GLControl intended or is that a bug in the latest NuGet package?

**Comment by bdachev** [comment]
Same situation here. Now that GLControl is a Form is there an easy way to create a child control with OpenGL context?

**Comment by rold2007** [comment]
I had the same problem and rolled back to the previous version too.

**Comment by wcdeich4** [comment]
Please download the  newest version from https://github.com/opentk/opentk

**Comment by bdachev** [comment]
I can see that in https://github.com/opentk/opentk GLControl is still UserControl.
But similar to the first post I am trying to use the latest build exposed on NuGet.
Who is responsible for creating that build? 
It seems to be created from a ppy's fork instead of the official OpenTK's one.

**Comment by wcdeich4** [comment]
When you go to https://www.nuget.org/packages/OpenTK the username of the guy is "exDreamDuck".  I emailed him to update from the latest version on https://github.com/opentk/opentk and he said he will, but I don't know if he has yet.  All I can say for now is the latest code is at https://github.com/opentk/opentk

**Comment by wcdeich4** [comment]
BTW, this is probably the best WinForm GLControl example: 

https://github.com/opentk/opentk/blob/develop/Source/Examples/OpenTK/GLControl/GLControlGameLoop.cs

**Comment by bdachev** [comment]
Thanks for doing that. Let's hope that the inconsistency will be resolved soon. It is a bit odd as NuGet way of getting the project is recommended in the README. One would expect that the copy in NuGet is maintained by the same people who are contributing/controlling the main repository.

**Comment by bdachev** [comment]
With regard to your last comment I was using the GLControl in a similar manner and changing it base from UserControl to Form broken my code. Which was a good opportunity to check how is GLControl implemented internally and make use of the code there to make my own GL control. :)

**Comment by wcdeich4** [comment]
Here is another example: 

https://github.com/thefiddler/opentk-wpf

**Comment by koonyook** [comment]
Seems like it has not been fixed yet in the latest version (1.1.2349.61993)

**Comment by varon** [comment]
Closing as this refers to an older version. Please see #432 for current discussion.
