### ISSUE TITLE
Support for Vulkan

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#342]
Vulkan is now released https://www.khronos.org/registry/vulkan/

I started doing a bit of work for this (https://github.com/Frassle/opentk/tree/vulkan) but never had time to finish it.

Might serve as a useful starting point. Take as much or as little as is useful.

**Comment by cra0zy** [comment]
I would help with this but my driver doesn't support Vulkan :(

**Comment by Xerexus** [comment]
I can probably do a bit. Although, I'm currently working on another project. I'll do what I can.

**Comment by feliwir** [comment]
Used Vulkan only with C++ so far, but I'd like to help with this after my exams. The mono community is already working on Vulkan bindings for C# so maybe we could use some of that: https://github.com/mono/VulkanSharp

**Comment by ilexp** [comment]
What is the stance on this issue by the current team of maintainers? Will we see Vulkan support for OpenTK at some point? If yes, is there a roadmap for evaluating, implementing, testing and integrating it?

**Comment by cra0zy** [comment]
As stated above my graphics card doesn't support Vulkan so I can't really write any code for it... tho the support for it is on horizon: http://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-SI-Next-4.9

I am however very interested in getting Vulkan support for OpenTK so if someone was to start working on it I would happily merge it.

cc. @amulware @varon

**Comment by varon** [comment]
This is definitely something we'd like to look at in the future, but we do not have the resources to commit to at present.
