### ISSUE TITLE
Vector2 GetHashCode gives non-ideal results

### ISSUE THREAD

**Issue by RMCKirby** [opentk/opentk#355]
This may also apply to the `GetHashCode` implemetations of other`IEquatable` value types throughout the codebase.

Currently, the hashing implementation simply computes the `xor` between each field.
This is problematic, e.g. both `Vector2.Zero` and `Vector2.One` will give the same result, when ideally they should yield different values.

See here for further reading: http://stackoverflow.com/questions/1008633/gethashcode-problem-using-xor

I'd be happy to submit a pull request for this.

**Comment by RMCKirby** [comment]
Seems a similar, if not duplicate, was raised in #167 and closed prematurely.

It still remains that:
`Vector2.Zero.GetHashCode() == Vector2.One.GetHashCode()` ==> `true`
`Vector2.UnitX.GetHashCode() == Vector2.UnitY.GetHashCode()` ==> `true`

**Comment by amulware** [comment]
I agree that this is a problem, and we should do something about it.

Right now I'm thinking about xoring the hash values of the different components while multiplying them with different primes.

For example, for Vector2:

```
(X.GetHashCode() * 397) ^ Y.GetHashCode()
```

This is how ReSharper automatically implements GetHashCode() (including the prime 397), and it seems to work very well.

If there are no contrary opinions, I'll do a pull request in the next few days.

**Comment by amulware** [comment]
Regarding types with more than two components, ReSharper uses the same method, nested as follows:

```
(((a *  397) ^ b) * 397) ^ c ...
```

I suggest we just do exactly this.

**Comment by RMCKirby** [comment]
I usually stick with the pattern suggested in http://stackoverflow.com/questions/263400/what-is-the-best-algorithm-for-an-overridden-system-object-gethashcode

But if the ReSharper approach is fine then go ahead.

On another note, I've seen that the project has switched hands, and am just wondering what the current process is for maintaining and updating the OpenTK package on `nuget`? i.e. when can I expect an updated package with fixes?

Additionally, I see that currently, there exist no unit tests. An issue was raised in #232 but seems to have never progressed.
Changes like this one are good candidates for introducing regression tests. Thoughts?

**Comment by amulware** [comment]
The switching hands situation is complicated. I am actually not sure who has control over the nuget package. The only thing that we (@cra0zy, @wcdeich4 and me) have - as far as I know - is push access to the repo. So at least development can continue to some degree.

There are a few other people talking about creating unit tests over at https://gitter.im/opentk/opentk

Maybe between the few of you, you can come up with something.

**Comment by RMCKirby** [comment]
Hi again,

Just joined the chat and am willing to aid in getting unit tests setup, shall move the conversation to there.

Cheers!

**Comment by wcdeich4** [comment]
The NuGet.org username of the person who made the OpenTK nuget package is "exDreamDuck" 

https://www.nuget.org/profiles/exDreamDuck
