### ISSUE TITLE
Input GetState() : NullReferenceException

### ISSUE THREAD

**Issue by chingham** [opentk/opentk#358]
I just found a bug in Input on Windows 10
When a do a Mouse.GetState() or Keyboard.GetState, it throws a TypeInitializationException with this InnerException:
ArgumentNullException, argument cannot be null. Parameter name: window

   at OpenTK.Platform.Windows.WinRawMouse..ctor(IntPtr window)
   at OpenTK.Platform.Windows.WinRawInput.CreateDrivers()
   at OpenTK.Platform.Windows.WinInputBase..ctor()
   at OpenTK.Platform.Windows.WinFactory.get_RawInputDriver()
   at OpenTK.Platform.Windows.WinFactory.CreateMouseDriver()
   at OpenTK.Input.Mouse..cctor()

Seems like Native.WindowInfo.Handle is equal to IntPtr.Zero for some reason
Of course I don't have this problem on OSX

```
class Window : OpenTK.GameWindow {
	public Window()
		: base(1024, 768, new OpenTK.Graphics.GraphicsMode(32, 24, 8)) {
	}
	protected override void OnLoad(EventArgs e) {
		base.OnLoad(e);

		Mouse.GetState();
	}
}
```

**Comment by varon** [comment]
I'm getting the same issue.

A temporary workaround is to use the NuGet package version `1.1.1589.5942` instead of the latest `1.1.2225`, in which this issue isn't present.

If one of the maintainers (@amulware @cra0zy @wcdeich4) could suggest the quickest way to fix this, I don't mind doing a PR for it.

**Comment by Costigan** [comment]
I'm getting the same bug under windows 7 64-bit.  The same workaround worked.

**Comment by opcon** [comment]
Are you using the nuget package? I had this same bug with the latest NuGet package, but building OpenTK directly from the develop branch (commit 663d8e4 for reference) does not produce the crash, so I think it has already been fixed.

**Comment by varon** [comment]
Yeah, It's an absolutely critical bug. Anyone using the input in this way cannot use the latest NuGet package. Could the maintainers push a patch release?

**Comment by cra0zy** [comment]
None of the current maintainers have access to the NuGet, so we can't push a patch, we can only maintain this repo.

**Comment by varon** [comment]
Ah, thanks for the explanation, @cra0zy.

I can build it locally on my own NuGet server and use that, but I'd rather depend upon public package. What can we do to un-break the current package?

If we can't get hold of the guy pushing the NuGet packages at the moment, I'd suggest just creating a new package altogether that we can use. What are your thoughts on this?

**Comment by varon** [comment]
@BenjaminNitschke  - Here's a mention, as I think you might be the guy who's got the NuGet package.

**Comment by cra0zy** [comment]
> I'd suggest just creating a new package altogether that we can use. What are your thoughts on this?

Lately I've been thinking the same thing.

**Comment by ala53** [comment]
What should it be named? We can't just name it "OpenTK"...
Maybe use a space in the name? Or maybe version it?
E.g. `Open-TK`, `Open TK`, or `OpenTK 1.1`.

**Comment by varon** [comment]
@ala53 We're not actually going to change namespaces or code here, only the NuGet package ID, if we do this.

I'd suggest something like OpenTK.Official

**Comment by wcdeich4** [comment]
I emailed https://www.nuget.org/profiles/exDreamDuck the nuget OpenTK package owner & he agreed to update it w/ the latest from the repo - a few months ago.  I just emailed him again if there is a way we could work more close together...

**Comment by wcdeich4** [comment]
@varon - how hard would it be to go into the source code & basically add one or more if statements to test if the reference is null, and if so, instantiate it before it is used?

**Comment by wcdeich4** [comment]
@thefiddler @cra0zy @amulware - if exDreamDuck aka @BenjaminNitschke doesn't want to share ownership of the OpenTK NuGet package, we can bump up the build number to say 2.0 & make a new NuGet package OpenTK2 --- the NuGet package for NUnit 3+ is actually a different NuGet package - (Install-Package Nuget3 instead of Install-Package Nuget).  In their case it is because there were major code changes & the syntax of NUnit3 tests is different than NUnit2 tests.

**Comment by varon** [comment]
@wcdeich4 Very, actually.

It's an inner exception inside a type initialization exception on a static class.
Not much we can do to solve that without an updated package.

```
{System.TypeInitializationException: The type initializer for 'OpenTK.Input.Keyboard' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: window
   at OpenTK.Platform.Windows.WinRawMouse..ctor(IntPtr window)
   at OpenTK.Platform.Windows.WinRawInput.CreateDrivers()
   at OpenTK.Platform.Windows.WinInputBase..ctor()
   at OpenTK.Platform.Windows.WinFactory.get_RawInputDriver()
   at OpenTK.Platform.Windows.WinFactory.CreateKeyboardDriver()
   at OpenTK.Input.Keyboard..cctor()
   --- End of inner exception stack trace ---
   at OpenTK.Input.Keyboard.GetState()
   at Program.main(String[] argv) in C:\Work\personal\f#\playground\playground\Program.fs:line 11}	System.Exception {System.TypeInitializationException}
```

**Comment by wcdeich4** [comment]
I'm sorry to hear that.  But if we're having this problem w/ Windows10, probably others are too.  You might try scouring the internet to see if anyone else has a solution

**Comment by varon** [comment]
@wcdeich4 It could be worse, I suppose. The bug occurs on W7 and W8 as well. I've posted a workaround earlier in this conversation (which is downgrading to `1.1.1589.5942`) , and a fix has already been pushed to master.

It seems as though I've got it building locally on my internal CI server. Would anyone object if I took responsibility and pushed up NuGet packages with the ids`OpenTK.Community` and `OpenTK.Community.GLControl` ?

**Comment by wcdeich4** [comment]
@varon, forgive me I've been really busy @ work - what fix has been pushed to master? I thought I had caught up on reading all the posts, but I don't remember that one.  If you're still looking for ideas for how to fix it, you could also try copying the OpenTK & GLControl folders from the OpenTK source code directly into your project (instead of using the dll) & trigger the exception so you can debug directly in the source code.  Also using GitHub, it should be possible to trace the code changes between version 1.1.1589.5942 and the current version.

**Comment by wcdeich4** [comment]
About the NuGet package, I don't have any objection to @varon taking the initiative on this - although, we should make sure the package has multiple owners - the problem w/ the old package is  @BenjaminNitschke put it under his NuGet account w/ no co-owners & left the project. 

Also, we should discuss the name. I'm ok w/ OpenTK.Community - another possibility would be OpenTK2 - like NUnit3 (discussed above).

**Comment by varon** [comment]
@wcdeich4  No trouble. This is all volunteer work after all. I'm not sure if it's on master, but @opcon indicates that dev has the fix already:
>I had this same bug with the latest NuGet package, but building OpenTK directly from the develop branch (commit 663d8e4 for reference) does not produce the crash, so I think it has already been fixed."

To find the commit that fixes it and bring it over to master won't be super hard, but we're facing a bigger issue of not being able to update the currently broken package.

As for the package, I've opened up an issue here: 382

**Comment by wcdeich4** [comment]
@varon now that I know it is not Win10 only, can you provide a small code snippet that gets the error to occur? I hope @opcon is correct, but there's a chance he was just lucky it didn't occur on his system, so let's test my system too.

**Comment by varon** [comment]
Literally just call `Keyboard.GetState()` and it'll throw an exception.

________________________________

**Comment by varon** [comment]
@wcdeich4 You can just call `Keyboard.GetState()`

**Comment by varon** [comment]
Hi All. We've just pushed out a pre-release package which should fix this issue. Sorry for the incredible delays in doing so.

>The pre-release packages can be downloaded here:
https://www.nuget.org/packages/OpenTK.Next/1.2.2336.6514-pre
https://www.nuget.org/packages/OpenTK.Next.GLControl/1.2.2336.6514-pre

(Note, that if you wish to install from your IDE or the command line, you might need to enable "show pre-releases" for them to appear)

Please comment on this if you encounter difficulties. Closing for now.
