### ISSUE TITLE
MouseState.Wheel / Scroll : Always 0 on OSX

### ISSUE THREAD

**Issue by chingham** [opentk/opentk#359]
As stated in the title, on OSX El Capitan, Mouse.GetState() always return a MouseState with Wheel/WheelPrecise/Scroll values at 0, even if I scrolled
I don't know if it has anything to do with the issue but I have a Logitech Mouse with the Logitech Control Center installed

**Comment by varon** [comment]
Tested this. The scroll wheel events from a trackpad require windowing to be registered, as it's not a mouse device. The wheel works correctly through an external mouse device.
