### ISSUE TITLE
Update license header in all files

### ISSUE THREAD

**Issue by amulware** [opentk/opentk#361]
As discussed here: https://github.com/opentk/opentk/pull/356#issuecomment-193390544
We would like to make the license text of all files more succinct and future proof.
@cra0zy suggests shortening it to:

```
// Copyright (c) Open Toolkit library.
// This file is subject to the terms and conditions defined in
// file 'License.txt', which is part of this source code package.
```

I do have to point out that currently, there is no license file at all in this repository. However, the readme specifies the MIT license somewhere half way through.

We may want to change that as well.

Personally, I am not a big fan of licenses to begin with, and would be happy to just completely un-license the code as well. (Specifically, I would not mind to NOT have any such comments at the top of all the files. I do not really see what purpose they serve.)

Thoughts?

**Comment by varon** [comment]
I don't think it's particularly necessary to include license headers, especially if it's under a permissive license anyway.

I do think consistency is important, though, so I'd chip in that it's pretty easy to update/remove all license headers in a project with Resharper.

**Comment by cra0zy** [comment]
License file is in documkentation: https://github.com/opentk/opentk/blob/develop/Documentation/License.txt

**Comment by cra0zy** [comment]
PS. License header needs to be included with every file so it's known if the files is licensed under MIT and people can do whatever they want with it, or if it's licensed under some other license.

**Comment by varon** [comment]
Well, that's the only argument I've heard for or it against it. Should I do a PR the proposed snippet on all files?

**Comment by cra0zy** [comment]
Sure, go ahead.

**Comment by varon** [comment]
Closing. Very low priority and not actually an issue.
