### ISSUE TITLE
Unclear README.md

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#364]
This seems to be the most active fork of opentk and it's contributors (i assume?) have no longer access to the website or sourceforge. 

It would help a lot for other devs to identify this fork as the most active one if the README.md would reflect that. (e.g. remove links to nuget, sourceforge, remove news section)

Also taging the repos for new releases (even if it's alpha/beta) would be very helpful for identifying how stable this fork is.

**Comment by amulware** [comment]
I think those are good ideas. Thanks!

**Comment by wcdeich4** [comment]
Yes & we should also update the Changelog to reflect recent pull requests that got approved - especially #350 "Invert Y axis on all GamePad" - I understand it was to match XNA which is what our documentation says - but if anyone has built their application expecting it the other way, they need to be warned the new version will do it the correct XNA way.

**Comment by varon** [comment]
We now have a RELEASE_NOTES.md file, and this has been marked as the root fork from Github. I think we can safely close this.
