### ISSUE TITLE
Remove component-wise vector multiplication operators

### ISSUE THREAD

**Issue by amulware** [opentk/opentk#365]
PR #84 added component-wise multiplication operators for all vector types.

As mentioned in #79 this is not actually how `VectorN * VectorN` would be defined mathematically and may proof confusing.

I personally am a strong proponent of type safety, and letting incorrect code fail at compile time.

Since multiplication between two vectors could be interpreted in at least three different way (inner product, cross product, component-wise), I would argue that `VectorN * VectorN` should be a compile error, and that people should use named methods.

I am not 100% on this, but I think I would prefer removing these operators (and make sure the different multiplication methods exist).

Thoughts?

**Comment by Phyyl** [comment]
I know this was brought in the other issue, but I really feel like this is important... GLSL has vector multiplication using the `*` operator, it will do component-wise multiplication. If I'm correct, in math, there's 3 operators for vectors: `*`, `•` and `x`. Right? I understand this can be a bit confusing when there's an operator but it doesn't say which one, but I also think it's clear that the star doesn't mean a cross or dot product. In addition, There's a nice comment over the operator, so anyone using it can see this is a component wise multiplication. I see it the same as a vector-to-float multiplication, except there's multiple components. Does that make sense..?

Also, what do you mean by "letting incorrect code fail at compile time"? Do you mean trial and error?

**Comment by amulware** [comment]
There are three operators in mathematics, but I do not think that anybody would use a * operator (at least I have never seen it). In fact, in several years of studying mathematics I have never seen any vectors multiplied component-wise. But that may just be a bad sample.

Just for completeness, when I see `v • w` I would generally assume the inner product, though this is also often written as `<v, w>`.
`v × w` on the other hand almost certainly would mean a cross product.

Since neither of these are valid operators in C#, I think the meaning of `*` is not necessarily clear in this context.

---

Either way, back on topic:

I agree that the argument from GLSL is an important one, and maybe it is good enough to allow for this  slight change of confusion.

I would not compare this with vector*float multiplication however, since that is a **scalar** multiplication, which is perfectly well defined and very common in mathematics. It is not the same as a **component-wise** multiplication.

---

What I mean by "letting incorrect code fail at compile time" is the following:

Say I write a line of code that multiplies several matrices and vectors as follows:

```
var result = v * w * m;
```

Let's say `m` is a matrix, and the other two are vectors.

If we leave the component-wise multiplication in tact, this line of code is perfectly valid. If we remove thee operators, it will fail at compile time (or the IDE will detect the type missmatch).

Now, maybe I know what I am doing and I WANT to multiply the two vectors component-wise, and then transform the result by the matrix. But maybe there is a typo/thinko here, and I think that `w` is actually a matrix. So I am actually trying to transform `v` with two matrices.

If we remove the operator, we remove the possibility for this mistake to cause bugs, since the line of code will never compile. Finding the error that way is very easy. (This is what I meant with the quote.)

In the case where I DO want the component-wise multiplication, I would simply change it into:

```
var result = Vector3.ComponentWiseMultiply(v, w) * m;
```

(or something similar, I do not know if we have a method for that right now)

This makes it clear to both myself, and a future reader (including myself) that this indeed performs a component-wise multiplication, and that I MEANT to do that.

---

And - sorry for the length of the post :D - another thing I just noticed:

With `v, w` being vectors, and `m` being a matrix and consider:
```
var result1 = (v * w) * m; // == v * w * m
var result2 = v * (w * m);
```

These two calculations are not equivalent. In other words: component-wise multiplication is not associative with 'regular' vector-matrix multiplication.

I would argue that vector-matrix multiplication is the 'default' multiplication on vector spaces.

Or, more mathematically, component-wise multiplication breaks matrix algebra (vectors are 'just' 1d matrices) (see: https://en.wikipedia.org/wiki/Algebra_over_a_field).

Therefore, having another kind of multiplication mixing with it that is NOT associative might also result in confusion.

If we forced users to use a method for this operation, they have to make a clear decision on the order they want the calculations to be performed in.

**Comment by amulware** [comment]
Small note: Despite the length of my post I dont consider this a clear and shut case.

I do think I have a strong case from a 'hardcore' mathematical standpoint, but we may well decide that that is not what we want from OpenTK.

More comments would be welcome!

**Comment by Phyyl** [comment]
I completely understand what you mean, and agree with most of it. One thing I keep thinking of, that would *sort of* fit both our use cases: Add a method for component-wise multiplication, just like you are describing, but keep the operator. I personally have used the operator in many cases where I was not using matrices (perhaps that's why I never questioned the priority thing you described in your third paragraph). 

I still think OpenTK, being mainly an OpenGL wrapper, should reflect what OpenGL and its shading language do. Adding a method for vector-wise multiplication would give you the 3 possible multiplications in Method form, and allow you to say: Only use method multiplications for clarity. That's what I would do at least. What do you think?

Your analysis is very good, but I'm really curious at what GLSL would do in the case of `var result = v * w * m;`!

**Comment by wcdeich4** [comment]
@Phyyl wrote "in math, there's 3 operators for vectors:  * ,  •  and  x" - yes, but C# can't make • or x operators, so we have to chose which to use the * operator for.  Even though I might personally prefer to use operator * for cross product to streamline my math code - we have to give very heavy weight to not breaking existing code, like the code @Phyyl write, unless the old way it was definitively wrong  - which this is not - we can chose which type of vector multiplication operator * stands for - one way would be more natural for mathematicians & one way would be more natural for GLSL programmers, but neither is absolutely right or wrong.  (@amulware I think *. in MatLab would do a component-wise multiplication for matrices or vectors - Matlab supports 2 symbol operators, so they could do that)

Therefore, I have to recommend we just leave the component-wise vector operator * functions as they are.  It's not how I would have written it in the first place, but I don't see a compelling reason to break existing code by changing this part of the API.

**Comment by Phyyl** [comment]
@wcdeich4 cross product is not noted as `*` in math, that's what I meant... But Thanks for your input. I have to say I'm not surprised MathLab also does component-wise...

**Comment by amulware** [comment]
Just out of curiosity, and a bit off topic: What do you (others) actually use component wise multiplication of vectors for?

I cannot remember doing so in any of my games or any other applications over the last few years.

**Comment by Phyyl** [comment]
personally, I use it for movement, ray tracing, some custom algorithms related to octrees. I use it in other ways, but that's mainly it

**Comment by amulware** [comment]
Funny. I've worked with all those things... :D

In either case, let's see if there will be anybody else commenting (tell us what you think, people!).

If not, I suppose we'll keep it.

**Comment by varon** [comment]
Either approach (matching GLSL or having a type-error) should be fine as long as it's documented.

**Comment by amulware** [comment]
Closing this until someone makes a more convincing argument than I did. Thanks for your comments everyone!
