### ISSUE TITLE
Resolution switch fails using nvidia driver, Linux Mint 17.3

### ISSUE THREAD

**Issue by leezer3** [opentk/opentk#366]
Original bug report from my repo:
https://github.com/leezer3/OpenBVE/issues/38

Resolution switch is failing under Linux Mint 17.3, using the nvidia proprietary driver.

Tests:
I'm triggering the resolution switch as follows:

> for (int i = 0; i < resolutions.Count; i++)
>                     {
>                         //Test each resolution
>                         if (resolutions[i].Width == Interface.CurrentOptions.FullscreenWidth &&
>                             resolutions[i].Height == Interface.CurrentOptions.FullscreenHeight &&
>                             resolutions[i].BitsPerPixel == Interface.CurrentOptions.FullscreenBits)
>                         {
>                             OpenTK.DisplayDevice.Default.ChangeResolution(resolutions[i]);
>                             Program.currentGameWindow = new OpenBVEGame(resolutions[i].Width, resolutions[i].Height,currentGraphicsMode, GameWindowFlags.Default);
>                             Program.currentGameWindow.Visible = true;
>                             Program.currentGameWindow.WindowState = WindowState.Fullscreen;
>                             break;
>                         }
>                     }

Appears relatively reasonable, and resolution switches correctly on Windows and the Ubuntu testing VM I have here.

Have tried with both the native X11 & SDL2 backends.

We next attempted to use the resolution switch from the examples.
This fails with the same symptons.

Final test was with a modified resolution switch test, as the examples one uses a method marked as **Obsolete**
This was as follows:

> // This code was written for the OpenTK library and has been released
> // to the Public Domain.
> // It is provided "as is" without express or implied warranty of any kind.
> 
> using System;
> using System.Collections.Generic;
> using System.Text;
> using System.Windows.Forms;
> using System.Diagnostics;
> using System.Threading;
> 
> using OpenTK;
> 
> namespace Examples.Tests
> {
>     public class TestResolutionChanges
>     {
>         public static void Main()
>         {
>             for (int i = 0; i < 6; i++)
>             {
>                 DisplayDevice dev = DisplayDevice.GetDisplay(DisplayIndex.First + i);
>                 if (dev != null)
>                 {
>                     Trace.WriteLine(dev.ToString());
>                     MessageBox.Show(dev.ToString());
>                     dev.ChangeResolution(dev.SelectResolution(640, 480, 32, 0)); // HERE: 60,0f -> 0
>                     Thread.Sleep(1000);
>                     MessageBox.Show(dev.ToString());
>                     dev.RestoreResolution();
>                     Thread.Sleep(1000);
>                     MessageBox.Show(dev.ToString());
>                 }
>             }
>         }
>     }
> } 

I will submit a pull request to remove the obsolete method from the examples later, but any thoughts anyone?

**Comment by leezer3** [comment]
Sorry, didn't mean obsolete method....

The resolution test requests a fixed refresh rate of 60.0hz, which would seem to be broken on displays that physically don't support this refresh rate. (Some TVs come to mind)

**Comment by varon** [comment]
Please re-open this if it's still an issue.
