### ISSUE TITLE
Rollback the website

### ISSUE THREAD

**Issue by RayKoopa** [opentk/opentk#372]
I know that this is not the correct place to talk about it, but it really is a "bug" to me in the OpenTK project.

The OpenTK website, its pages and the forum, are completely filled with spam, and bots continued to spam it up. Looks like you successfully combatted new spam in the forum, at least there are no new posts at all anymore since weeks.

But the spam is still there. I recommend rolling it back to 2 or 3 months ago when all that spam started (I can't even find the starting point of it in the forum, as it fills too many pages).

Right now, the website is useless.

**Comment by wcdeich4** [comment]
@RayKoopa Thank you for contacting us. The problem is we're currently locked out of maintaining our own site. We are working to rectify the problem.

**Comment by RayKoopa** [comment]
Thanks for the reply. Sorry if I sounded a bit steamy... if I can help with anything when you can maintain the website again, e.g. deleting threads later on on the forum, I'd be glad to help out.

**Comment by platinum95** [comment]
Just thought I'd add that I've been going through some of the wiki spam entries on the Documentation page and editing them to indicate what they are. I can't delete them and I know it's not a huge help but it's at least giving some order back to the place. 
The amount of spam is huge though so the editing is quite slow to do.

**Comment by amulware** [comment]
You efforts are appreciated, but clearly we will not be able to make any significant progress before at least some of us have access to the website/forum.

Here is hoping that will happen sooner rather than later. Otherwise we may have to consider creating a replacement website.

**Comment by varon** [comment]
see #389
