### ISSUE TITLE
Mouse and Keyboard drivers result in type initialization exception

### ISSUE THREAD

**Issue by ala53** [opentk/opentk#375]
Trying to access the Mouse or Keyboard drivers (in my code) results in a type initialization exception. The error can be traced back to (in the case of the mouse):
```
Value cannot be null.\r\nParameter name: window
at OpenTK.Platform.Windows.WinRawMouse..ctor(IntPtr window)\r\n   
at OpenTK.Platform.Windows.WinRawInput.CreateDrivers()\r\n   
at OpenTK.Platform.Windows.WinInputBase..ctor()
```

Looking deeper, it seems that, in WinInputBase, the `Native` window is never created, which results in an ArgumentNullException on passing the window to WinRawMouse.

I am not sure if this is relevant to the issue, but I am using a custom event loop looking loosely like so:
```
public void Run()
        {
            window = new GameWindow()
            //Keep a custom event loop going
            while (true)
            {
                //Process input / resize / etc
                window.ProcessEvents();
                //Break if we're exiting
                if (window.IsExiting) return;
                ClearFrame();               

                //This is broken
                Mouse.SetPosition(1,2)
                //Drawing here
            }
        }
```

**Comment by opcon** [comment]
Same error as #358?

**Comment by varon** [comment]
It's the same error.

**Comment by varon** [comment]
Closing due to a dupe. @ala53  @opcon - [please read this comment for a fix](https://github.com/opentk/opentk/issues/358#issuecomment-221730455)
