### ISSUE TITLE
Mono crashes when creating new GameWindow on Windows.

### ISSUE THREAD

**Issue by tzachshabtay** [opentk/opentk#376]
Hi, when I create a GameWindow on Windows, mono crashes. The error:

Unhandled exception at 0x7752F70B (ntdll.dll) in mono.exe: 0xC0000374: A heap has been corrupted (parameters: 0x77564270).

I'm using Mono 4.2.3 and OpenTK-1.1-4c.
Reproduced on two different machines, one on Windows7 and the other on Windows10 (works on dotnet, but if I compile with mono it crashes).
I debugged into OpenTK and it crashes in WinDisplayDevice, line 127, on the call to Functions.EnumDisplaySettingsEx(dev1.DeviceName.ToString(), DisplayModeSettingsEnum.CurrentSettings, monitor_mode, 0)

The code to reproduce is as simple as can be:
public static void Main (string[] args)
        {
            using (GameWindow window = new GameWindow ()) {}
        }

**Comment by wcdeich4** [comment]
Did you make sure OpenTK.dll.config in in the output directory (i.e. bin\Debug) ? 

Also, forgive me for being dense, but what does "Hi, when I create a GameWindow on Windows, mono crashes" mean?  Did you build it in Visual Studio in Windows, then re-open it in MonoDevelop in Linux?

**Comment by tzachshabtay** [comment]
No, Linux is not involved.
I build & run (i.e just press the play button) from Xamarin Studio Community 2015 in Windows after settings the runtime as Mono (Project -> Active Runtime -> Mono 4.2.3). 
To my understanding I don't need to put OpenTK.dll.config in the output directory for Windows (based on http://www.opentk.com/doc/chapter/1/windows, it's only required for osx and linux), am I wrong?

**Comment by wcdeich4** [comment]
Since you're using Xamarin w/ Mono runtime, it might be necessary - but it certainly never hurts to have OpenTK.dll.config - I always add it to my projects & set it to automatically copy the the binary folder.

**Comment by cra0zy** [comment]
The crash might be cause by the fact that mono on Windows is 32 bit, while it's trying to load 64 bit library.

> To my understanding I don't need to put OpenTK.dll.config in the output directory for Windows (based on http://www.opentk.com/doc/chapter/1/windows, it's only required for osx and linux), am I wrong?

You are right.

> Since you're using Xamarin w/ Mono runtime, it might be necessary

Nope, .dll.config files are used to overwrite constants, and are usually used for redirecting Windows libs to Linux/Mac libs. In out case it has no use on Windows.

**Comment by varon** [comment]
@cra0zy @thefiddler Are we supporting this configuration? It seems really unusual.

**Comment by varon** [comment]
Closing. Mono on windows isn't a supported configuration.
