### ISSUE TITLE
Can't build examples project with vs2013 whitout GTK?

### ISSUE THREAD

**Issue by NinjaFighter** [opentk/opentk#378]
Looks like Examples project needs GLWidget, and looks like GLWidget needs GTK, and it was not included on dependences.
I only want to check some things on examples, there's a way to run these examples without gtk?

**Comment by cra0zy** [comment]
Gtk# isn't something that can easily be included in repo dependencies, but you can grab the Gtk# installer from http://www.mono-project.com/download/#download-win

I'll add a note about it in dependencies readme file.

**Comment by cryptocompress** [comment]
Removing GLWidget project and example worked for me.

**Comment by cryptocompress** [comment]
Alternatively examples from ``mono/opentk`` worked by increasing Framework Version to 4.5 and loading Nuget packages for OpenTK and OpenTK.GLControl. :)

**Comment by cra0zy** [comment]
The reason Gtk is needed in the examples is because one of the example shows you how to use OpenTK together with Gtk... yes, removing that example will allow you to run without Gtk but that example is needed in the repo...

**Comment by varon** [comment]
Examples are no longer in the core repo.
