### ISSUE TITLE
Some Gamepad/Joystick doesn't recognize first Stick position. #bug

### ISSUE THREAD

**Issue by NinjaFighter** [opentk/opentk#379]
I notice that some gamepads doesn't work properly, because the first stick always gets a freezed negative value (just like this was always pressed to left side).
It happens on some generic usb joystick and one of my testers had the same problem with a ps4 controller too.

Edit: 
I have some news about this bug. My tester shows me what happen with ps4 controller and something very strange happens: First axis was moving with nonesense, just like it was reading some strange memory instead of real axis position. So, that was different of what happen with another generic usb joystick (axis freezes at left), but... the problem was at very first axis too!... maybe, is reading an incorrect memory location to obtain this value?

**Comment by varon** [comment]
Possibly fixed by #453 and related PRs. Please re-open if this is still an issue.
