### ISSUE TITLE
Recover NuGet package

### ISSUE THREAD

**Issue by varon** [opentk/opentk#382]
See #358 for the history here.

## The current situation
@BenjaminNitschke , aka _exdreamduck_ holds ownership over the current NuGet package, located at https://www.nuget.org/packages/OpenTK/.

This package has a critical bug, which we would like to push a fix for. See #358 and #375

After nearly three weeks of waiting, @BenjaminNitschke has yet to reply to our requests for ownership on the package.

## Consensus so far

So we've discussed, and there seems to be general consensus that we're going to create a new NuGet package. I'm happy to take responsibility for this initiative, as I'm already building it locally on my CI server.

However, to actually make a new release, we'll need to assemble the following info:

1. A new package name (OpenTK.Community or OpenTK2 or ??)
1. A release version (1.2 or ??)
1. A changelog (??)
1. Compatibility listing (??)
1. An updated copyright (??)
1. One or more active maintainers to share ownership with me on this.

## Current proposal

I'd suggest the following scheme:

1. Name isn't critical. Let's go with OpenTK.Community.
1. (current release + patch letter incremented)
1. A changelog I'll need some help with, but it shouldn't be huge.
1. Should be compatible, as it's a maintenance release.
1. I'll also need some help with the copyright.
1. Any of the maintainers could do here.

Any thoughts would be appreciated on this from @amulware @cra0zy  @wcdeich4 @thefiddler @BenjaminNitschke.

**Comment by cra0zy** [comment]
The account used for NuGet should be an account (only/all) admins have access to.

**Comment by wcdeich4** [comment]
Looks good to me

**Comment by farzadmf** [comment]
Any news on this one? This library is too good to be left alone and not updated

**Comment by varon** [comment]
@farzadmf I'm not a maintainer, so I'm hesitant to move ahead until some more feedback is brought in.

@amulware @wcdeich4 are the people we need input from here.

**Comment by varon** [comment]
Thanks to @wcdeich4, I'm now part of the team. I'm going to go ahead and suggest that unless any new feedback is offered, I'll set up the NuGet package (based on my proposal) at the end of the week.

**Comment by cra0zy** [comment]
@varon Did @thefiddler or @wcdeich4 invite you?

**Comment by varon** [comment]
@cra0zy It was @wcdeich4. I've sent him an email with some direct contact details as well.

**Comment by cra0zy** [comment]
So @thefiddler gave admin access to the entire team this morning... that means anyone can invite new people but...

Bad news:

@wcdeich4 Don't randomly invite people to the opentk organization without talking to other team members, I moved your privilege to member...

@varon I am sorry but I need to remove you from the organization because of the above. 

Good news:

I was gonna do some stuff for the OpenTK nuget package and website later today so I'll mention it here when it's done.

**Comment by varon** [comment]
@cra0zy - I'm a bit annoyed at having been messed around like this, but I'll live. Good luck with the package.

However, it does seems rash to demote @wcdeich4 here.

In the interest of transparency, could you explain how the hierarchy of the project works, and what gives you executive authority to make such a decision?

**Comment by cra0zy** [comment]
> I'm a bit annoyed at having been messed around like this, but I'll live. Good luck with the package.

Yea, I am very sorry about that.

> In the interest of transparency, could you explain how the hierarchy of the project works, and what gives you executive authority to make such a decision?

When you are a part of the organization on GitHub you are either a member or an owner:
 - members can maintain repos
 - owners can invite new people to the organization or add new repos to the organization namespace

Now the reason why I made the decision is because of 2 reasons:
 - what gave @wcdeich4 executive authority to invite you into the organization... nothing... he just randomly did it without talking to the rest of the admins about it
 - the amount of stuff I had to fix after @wcdeich4 is astonishing, no offense @wcdeich4

**Comment by varon** [comment]
@cra0zy Thanks for the prompt answer.
I understand how the Github system works, but what I'm confused about is the _OpenTK hierarchy_. While @wcdeich4 might have done something less than ideal, _you've only provided a justification as to why you did so, not a justification of your authority to do it_.

To re-phrase my question more directly:

Who are the maintainers of the project? Previously @thefiddler  was in charge, followed by @frassle. At the moment, there seems to be a group rather than a specific individual, and I don't see what makes you outrank @wcdeich4 here.

**Comment by cra0zy** [comment]
> Who are the maintainers of the project?

@thefiddler Should be back as the maintainer at some point. Until then it's @amulware @wcdeich4 and me.

> At the moment, there seems to be a group rather than a specific individual, and I don't see what makes you outrank @wcdeich4 here.

Nothing.

Tho you can see the difference on our experience pretty easily:
https://github.com/amulware
https://github.com/wcdeich4
https://github.com/cra0zy

**Comment by cra0zy** [comment]
#386

After it get's merged I'll make OpenTK.Devel package public.

**Comment by wcdeich4** [comment]
Actually @thefiddler only made me an owner back on 4/19.  But I've been busy working 12 hour days @ work, so I decided last night to make @cra0zy @amulware & @varon owners also b/c I don't have enough time now.  And honestly, @varon has worked as hard as any of us (We should consider @leezer3 also), definitely harder than me unless you count all the hours I spent emailing people trying to get people involved to breath live back into this project of which many people google "Is OpenTK dead?" 

@cra0zy clearly a genius from your MonoGame work & Vuklan research, but you're so hard to get along with, I'm afraid you may push away other people we need. 

And @cra0zy, sorry I don't do everything how you want, but why do you get so pissed about how things are done in an opensource community project?  Even when you were just a member, if you didn't like what some other member checked in, you could always just go back & fix it your way.  A community project ought to be more community lead & this isn't the first time you took unilateral action after criticizing me for doing something myself.  I understand you would have liked me to ask you before promoting @varon as well as you & @amulware, but @varon  is really working hard & you didn't ask anyone before demoting me, like you want to merge linux code by yourself, but you get very upset if anyone else merges w/out your approval. …. bro, you seriously need to lighten up before you get an ulcer.

**Comment by wcdeich4** [comment]
But if you guys really care about saving OpenTK, not just squabbling, start brushing up on Mono.Cecil.

Remember, when @thefiddler said “a separate program patches that .dll to bind the OpenGL function calls and the reason for this is to enable a faster DllImport mechanism that cannot be expressed directly in C# code”?? 

Well it involves Mono.Cecil, and when I tested changing the OpenTK & GLControl project target frameworks to .NET 4.0 Mono.Cecil stopped working & even when I switched to the newest NuGet version of Mono.Cecil, it still didn’t work.

There’s nothing wrong with leaving some of the projects in the OpenTK solution as .NET 2.0 for now, but eventually Microsoft will stop supporting .NET 2.0, so if we don’t find some solution for this, eventually, OpenTK is eventually doomed.

https://www.nuget.org/packages/Mono.Cecil/

http://www.mono-project.com/docs/tools+libraries/libraries/Mono.Cecil

https://github.com/jbevain/cecil

**Comment by cra0zy** [comment]
1. Big difference between "contributor" and "maintainer", you only need a few maintainers per repo, not every contributor should be promoted to maintainer, that would be pointless.
  - having to many maintainers is a mess, how would anything get decided then
  - "promotion" doesn't exist in open source projects
  - community project doesn't mean everyone is a maintainer, it means anyone can contribute
  - new maintainers are added only when there are too little maintainers or the old maintainers step down
2. Don't do stuff on your own that affect the team/repo without talking to the rest of the team, the only things I've done without talking to the rest of the team is undo stuff you did, which is irritating because you keep doing stuff on your own over and over and over... I am very strict about quality control
3. I would really recommend you trying to watch another open source project to see what maintainers do in it.

**Comment by varon** [comment]
Frankly I'd rather have a lively and active project with a few flaws that continues to improve and evolve, than a dusty ivory tower of intended perfection that nobody dares to contribute to.

While your rigorous approach usually is something I'd be heavily in favor of, OpenTk really isn't structured, "designed" in that way. It's a collection of not the neatest, but very useful tools. I think a somewhat ad-hoc approach to the library is inevitable, so encouraging users and contributors should take significantly higher precedence than attempting to preserve the elegance of the already pretty messy code base.

Only with significant investment by the community will OpenTk have enough manpower to undertake the serious refactors to bring it into the modern age. In that regard, I urge you to use your technical ability and domain knowledge to encourage and assist contributors and other maintainers, not attempt to do everything yourself.




On Tue, May 17, 2016 at 11:58 PM -0700, "Harry" <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  Big difference between "contributor" and "maintainer", you only need a few maintainers per repo, not every contributor should be promoted to maintainer, that would be pointless.
     *   having to many maintainers is a mess, how would anything get decided then
     *   "promotion" doesn't exist in open source projects
     *   community project doesn't mean everyone is a maintainer, it means anyone can contribute
     *   new maintainers are added only when there are too little maintainers or the old maintainers step down
  2.  Don't do stuff on your own that affect the team/repo without talking to the rest of the team, the only things I've done without talking to the rest of the team is undo stuff you did, which is irritating because you keep doing stuff on your own over and over and over... I am very strict about quality control
  3.  I would really recommend you trying to watch another open source project to see what maintainers do in it.

-

**Comment by cra0zy** [comment]
Just gonna mention that I don't have time to read and respond to everything in here so I'll skip reading anything in here until this or next weekend...

**Comment by wcdeich4** [comment]
For whatever it's worth, I didn't mean there should be a free for all where anyone commits & anyone corrects; I just meant if someone commits incorrectly it's not too hard to fix

**Comment by cra0zy** [comment]
> I just meant if someone commits incorrectly it's not too hard to fix

It's worse than you thing:
 - undoing commits / rewriting history is bad because you brake compatibility with forks, this should be avoided
 - undoing stuff by adding more commits also isn't good, because you are adding pointless commits in total

There isn't a good way to fix them, we should be careful...

**Comment by leezer3** [comment]
Sitting on the fence TBQH.

Commits with issues are a problem even in a single user project, and are going to be a nightmare in a project this size.
Similarly, trying to keep a consistant code style is definitely a good idea.

On the flip side, there's a lot of stuff which could do with being actively worked on, and breaking a few bits along the way is par for the course.

No good answer, sorry..........

**Comment by wcdeich4** [comment]
I think @leezer3 is right; both extremes are wrong.  We can't have chaos, but too much relentless pursuit of perfection can lead to bureaucratic nightmares.

@leezer3 & @varon - theoretically the way you avoid adding flaws / breaking a few bits is with unit tests.  I deeply wish I had time to write more unit tests now, but I've been working late day after day.... but at least we have a unit test project now. 

Of course Unit Tests are not a panacea, but the more you have, the more likely you are to know a "seemingly unrelated" change introduces a regression of some previously established functionality.

**Comment by varon** [comment]
@wcdeich4, Generally test coverage does help prevent regressions, but even if we did have tests, getting it right still helps, and it helps a lot in the cases we inevitably miss when testing, which is what I believe @cra0zy is saying. 100% test coverage doesn't mean it's bug free.

Back to the actual issue/proposal, @cra0zy has set up a few private NuGet packages, which are being tested at the moment. Hopefully we'll get them out by the end of this weekend.

I'll post any updates here as soon as they happen.

**Comment by leezer3** [comment]
Tests are handy, but I'm sure we've all come across cases where something works perfectly under test but throws an absolute fit when subjected to the general public.

They should be used in tandem with code review, hopefully taking some of the workload off those doing it, not as a replacement for it.

**Comment by cra0zy** [comment]
I am confused... :/

**Comment by varon** [comment]
@cra0zy - The conversation kinda derailed into the merits of testing.

As for the update, there's a PR at #386. Conversation will continue there.

**Comment by varon** [comment]
We did it! #392 adds a pre-release NuGet packages.

For now, these packages should fix pressing issues, and can be downloaded here:
https://www.nuget.org/packages/OpenTK.Next/1.2.2336.6514-pre
https://www.nuget.org/packages/OpenTK.Next.GLControl/1.2.2336.6514-pre

Note, that if you wish to install from your IDE or the command line, you'll need to show pre-releases for them to appear.

We'll continue to work hard on getting a stable release to you guys as soon as possible.

**Comment by varon** [comment]
I'm going to close this issue, as we've technically 'recovered' it.

**Comment by wcdeich4** [comment]
@leezer3 is 100% correct "Tests are handy, but I'm sure we've all come across cases where something works perfectly under test but throws an absolute fit when subjected to the general public." - there is a way to make a unit pop open a GameWindow & draw something to test that feature - but then it's not "unit-ish"
