### ISSUE TITLE
Did Xamarin open source their OpenTK dlls?

### ISSUE THREAD

**Issue by pauldendulk** [opentk/opentk#388]
I can't find it in the android repo. Here is some in iOS:
https://github.com/xamarin/xamarin-macios/tree/2edb2ae4f5bb371a7006731987717c01f8725420/src/OpenGLES

Perhaps this seems like a stupid question but for me it is not easy to judge whether this is all.

**Comment by cra0zy** [comment]
Xamarin OpenTK has been opensource for a long time now: https://github.com/mono/opentk

**Comment by cra0zy** [comment]
Ups wrong button.

**Comment by pauldendulk** [comment]
Thanks, I missed that. 

There is not much activity on that repo. Is there any continued development on those components? Any plans to integrate it in here?

**Comment by cra0zy** [comment]
There is #142, tho no one is working on it right now. Also had a conversation about this subject this morning on gitter: https://gitter.im/opentk/opentk if that interest you.

**Comment by pauldendulk** [comment]
huh, odd how relevant that gitter conversation is to my question :) Posted just today.

I won't be able to help with this merge myself unfortunately but am interested in any progress. Thanks for the info!
