### ISSUE TITLE
Recover the website

### ISSUE THREAD

**Issue by varon** [opentk/opentk#389]
We'd like to recover the OpenTK website, and perhaps bring it out of the dark ages into a simple and working form.

Based on a discussion by the team, the current plan is to move to GitHub pages.

I'll be prototyping that over the weekend, and will post my findings here.

**Comment by amulware** [comment]
Looking forward to more info. Thanks a lot for taking a look!

**Comment by cra0zy** [comment]
The negative side of having "github website" is that it needs to be just client side code, so no forums, but I think with Gitter and "Issues" tab we don't really need it.

:+1: from me.

On a related side note should we use Wiki or the website for future documentation?

**Comment by varon** [comment]
Here's the prototype link: http://varon.github.io/opentk-gitpages/

Basically, Jekyll and Github pages are really easy to work with (surprise surprise). You can produce a good-looking, simple to maintain site with minimal effort.

From here, we'd probably need to change the landing page to something useful, stick the blog somewhere on there, and write a bunch of tutorials we can point to.

**Comment by cra0zy** [comment]
We can have a blog, but it should not be in the main page, separate tab for it would be better.

As for the main page, we need stuff like "Download", "Documentation", "Small explanation of what OpenTK is", etc.  Big buttons on the center might also be good. Take a look at these websites:
 - https://dotnet.github.io/
 - https://fna-xna.github.io/

Both of them are different, yet they both provide with the needed info right from the home page.

**Comment by varon** [comment]
You're 100% right. At the moment, we still need to decide if Github Pages are the way to go, and if the example site can do what we need. The actual layout of the website should be as you've said.

I'm in favour of this approach, and if we get some consensus on that, can look at re-working the layout to match what you've suggested.

**Comment by amulware** [comment]
![](https://studentaffairscollective.org/wp-content/uploads/2015/02/1296931_orig.jpg)

**Comment by varon** [comment]
After a chat with @amulware, we've decided that he'll fork my repo and sort out the structure/html/templating. I'll continue to write and refine the copy for the website.

**Comment by D4Water** [comment]
Any chance I could volunteer my time to help out with cleaning up the spam on the forum ? I have a lot of experience with forums. I would like to go in there and just start clearing out the spam off the forum so we can get OpenTK back to working order again. Once I get it back into shape, I could check it once a day for spam and remove as needed if I was a moderator.

**Comment by hammus** [comment]
I'm happy to help out with the Documentation stuff (as it's what I really need at the moment). Happy to get started immediately. PM `@hammus` on Gitter if I can help out

**Comment by varon** [comment]
We still need some documentation, but it's close enough.
https://opentk.github.io
