### ISSUE TITLE
GameWindow constructor hangs on mono 4.2 and nvidia in Linux

### ISSUE THREAD

**Issue by toadicus** [opentk/opentk#393]
I have been writing a simple OpenGL program on OpenTK using mono 4.2 and nvidia for some months.  I took about a 3 week break, and when I came back the window no longer opens when I construct the GameWindow object.  To demonstrate the problem simply, I have written the following reproduction case:

``` cs
using System;
using OpenTK;

namespace Program {
    public static class Program {
        public static int Main() {
            Console.WriteLine("Before construction");
            using (GameWindow window = new GameWindow(1280, 720)) {
                Console.WriteLine("Constructed window");
                window.Load += (object sender, EventArgs args) => {
                    Console.WriteLine("OnLoad");
                };

                window.UpdateFrame += (object sender, FrameEventArgs args) => {
                    Console.WriteLine("UpdateFrame");
                };
            }

            return 0;
        }
    }
}

```

The only output to the Console is "Before construction".

For your use, I have also attached the output of mono --trace and strace: ~~[OpenTKGameWindowTest_Traces.zip](https://github.com/opentk/opentk/files/285788/OpenTKGameWindowTest_Traces.zip)~~

I ran the program for exactly ~~15~~ **75** seconds before killing it, thus:

```
toad ~/ws/opentk/Binaries/OpenTK/Debug $ free -h
              total        used        free      shared  buff/cache   available
Mem:            15G        3.5G        7.0G        137M        5.2G         11G
Swap:            0B          0B          0B
toad ~/ws/opentk/Binaries/OpenTK/Debug $ mono --trace OpenTKGameWindowTest.exe > mono_trace.txt & mono_pid=$!; sudo strace -p $mono_pid &> strace.txt & sleep 75; kill $mono_pid
```

Thanks in advance!

_**EDIT__: I forgot to prime sudo so the strace in the archive above is blank.  Also, apparently the strace slows down the failure process a lot so mono hadn't got to the point where it appears to hang and just do nothing.  I increased the duration to 75 seconds.  *_Here's the new zipball with proper logs*_:_

[OpenTKGameWindowTest_Traces.zip](https://github.com/opentk/opentk/files/285815/OpenTKGameWindowTest_Traces.zip)

**Comment by toadicus** [comment]
Thought of a couple other bits of potentially-relevant info:

```
$ uname -a; pacman -Q nvidia mono glibc
Linux saya 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux
nvidia 364.19-3
mono 4.2.2.30-2
glibc 2.23-4
```

**Comment by toadicus** [comment]
So, I found what might be a workaround, or an un-break-around, or something.  I forgot I had set __GL_THREADED_OPTIMIZATIONS=1 globally a while ago.  It seems like OpenTK doesn't like that at all; when I run thus:

`__GL_THREADED_OPTIMIZATIONS=0 mono OpenTKGameWindowTest.exe`

it works as expected.  So, not sure if this is something you all want to try to resolve on your end or not.  If nothing else, hopefully this helps a future googler. :)

**Comment by alakanu** [comment]
Don't want to seem stupid but, aren't you missing a window.Run() somewhere?

**Comment by toadicus** [comment]
A window.Run() call would only be relevant if the GameWindow constructed, which it did not.  The test case is sufficient to demonstrate that the object never constructs and that OpenTK hangs during the constructor when `__GL_THREADED_OPTIMIZATIONS=1`.

**Comment by varon** [comment]
@thefiddler, @cra0zy You guys are probably the people to ask about this.

**Comment by cra0zy** [comment]
What version of OpenTK are you using, NuGet, source, some binaries?

**Comment by cra0zy** [comment]
Looking at your code you are not doing `window.Run();`

**Comment by toadicus** [comment]
I'm aware there's no `window.Run();` in the example code; that was intentional because the problem occurs during the `GameWindow()` constructor and no code after the constructor, `Run()` or otherwise, will ever run.

This occurs when `__GL_THREADED_OPTIMIZATIONS=1`, but not when `__GL_THREADED_OPTIMIZATIONS=0`.

This was tested using OpenTK 1.1-4c in Linux, so I didn't use NuGet or anything like that.  I tried it using precompiled OpenTK binaries from the website, and a locally-compiled version.

**Comment by cra0zy** [comment]
I see what you are talking about, I guess it's probably a bug with NVidia driver. Googleing around a bit does reveal bunch of bugs that occur with that flag enabled.

**Comment by varon** [comment]
Closed as this uses an old version, and looks to be likely on the nvidia side. If we're still experiencing this, please re-open a new issue.
