### ISSUE TITLE
unable to open opentk.sln with VS2015

### ISSUE THREAD

**Issue by jddde** [opentk/opentk#394]
After pulling the git repo and trying to open the solution, I get the following output:
[Failure] Could not find file 'C:\Users\deschamps\Source\Repos\opentk2\Source\GlobalAssemblyInfo.cs'.

**Comment by jddde** [comment]
Sorry, the solution was opened but Solution Explorer was closed...

**Comment by jddde** [comment]
All is good:
========== Build: 11 succeeded, 0 failed, 0 up-to-date, 4 skipped ==========

**Comment by varon** [comment]
Not to worry. Thanks for actually taking the time to close the issue and report what it was!
