### ISSUE TITLE
how to draw a texture using point sprites

### ISSUE THREAD

**Issue by jddde** [opentk/opentk#395]
Hello,

I am quite new in openGL. I have drawn a 3D picture using a panel and System.Drawing. It is very slow though.
So I want to use OpenGL. I have pulled the opentk/opentk repo, compiled it and succeded reproducing the tutorial there: http://www.opentk.com/doc/chapter/2/glcontrol
Now, I am looking for a tutorial to draw a png on a point sprite in a GLControl

For example, I add the following vertex : (0.1f , 0.1f , 0.9f)
The camera is looking toward z direction.
On this vertex, I draw a pic.png using the point sprite method.

What would be the code ? Where could I find a opentk tutorial to do that ?

Thanks

**Comment by varon** [comment]
Hi there! We're currently working on a new website with more up-to-date documentation (which would probably be a better reference).

If you could provide the full source of your project, I'll be happy to take a look and see if I can spot what's wrong.

**Comment by jddde** [comment]
Hello,

My project is on visual studio online. I can give you access but I am not sure it would help.

The purpose is to show a map of the sky.
The observer is in the middle of a sphere bearing the stars and the planets.
I know all the 3D coordinates. I would like to draw a png on each star and planet.

As a first step, I could draw a 2D map (I have already calculated the 2D coordinates)
And afterwards, I would try to draw the sphere.

The 2D map code would be:
`
using OpenTK.Graphics;
using OpenTK.Graphics.OpenGL;

namespace AlmicantaratDesktop
{
    public partial class FormOpenGL : Form
    {
        bool glControlIsLoaded = false;

        public FormOpenGL()
        {
            InitializeComponent();
        }

        private void glControl_Load(object sender, EventArgs e)
        {
            glControlIsLoaded = true;
            GL.ClearColor(Color.DarkBlue);
            SetupViewport();
        }
        private void SetupViewport()
        {
            int w = glControl.Width;
            int h = glControl.Height;
            GL.MatrixMode(MatrixMode.Projection); // Is it OK for point sprites ???
            GL.LoadIdentity();
            GL.Ortho(0, w, 0, h, -1, 1);
            GL.Viewport(0, 0, w, h);
        }

        private void glControl_Paint(object sender, PaintEventArgs e)
        {
            if (!glControlIsLoaded)
                return;

            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
            GL.MatrixMode(MatrixMode.Modelview); // Is it OK for point sprites ???
            GL.LoadIdentity();
// Should I use that: http://www.opentk.com/doc/graphics/textures/loading
// to load my PNGs?
            GL.Begin(PrimitiveType.Triangles); //What PrimitiveType for point sprites ??
            GL.Vertex2(100, 80); // The the first sprite 2D coordinates...
//How to draw the png centered on the Vertex2(100, 80)?
            GL.End();
            glControl.SwapBuffers();
        }
    }
}
`
Thanks for your help

**Comment by varon** [comment]
@jddde It seems as though you're trying to do this in immediate mode. This is the very old, deprecated OpenGL API. I would advise using the 
`OpenTK.Graphics.OpenGL4` namespace instead, especially if you're wanting to learn from this.

Looking through your code, there seems to be a lot of misunderstandings as to how things work. [I would suggest you follow the tutorials here](http://learnopengl.com/#!Introduction) through to completion for a much better understanding of what's going on. They're very easy to translate to the OpenTK API, and should help you get closer to what you want to draw.

If you'd rather not invest the time to learn the low level API that OpenTK provides, I would suggest you look at MonoGame or Unity3D for an approach that requires less learning.

**Comment by jddde** [comment]
@varon Thank you for having examined my code.
This very old and deprecated immediate mode is not mine but the code I found on [http://www.opentk.com/doc/chapter/2/glcontrol](http://www.opentk.com/doc/chapter/2/glcontrol) !!
I guess opentk documentation needs to be updated.

I began to read [OpenGL Programming Guide Eighth Edition](https://www.ics.uci.edu/~gopi/CS211B/opengl_programming_guide_8th_edition.pdf) 
But the operating system is GLUT
[The tutorial you suggest](http://www.learnopengl.com/#!Getting-started/Creating-a-window) uses the operating system GLFW.

I am not afraid to learn core-profile or low level API but I would need a small tutorial to understand how to use GLControl, just to try the codes explained in [OpenGL Programming Guide Eighth Edition](https://www.ics.uci.edu/~gopi/CS211B/opengl_programming_guide_8th_edition.pdf) and in [learnopengl.com](http://www.learnopengl.com)

But as you wrote

> They're very easy to translate to the OpenTK API

I will try by myself...

**Comment by varon** [comment]
@jddde No problem.
>This very old and deprecated immediate mode is not mine but the code I found on http://www.opentk.com/doc/chapter/2/glcontrol !!
I guess opentk documentation needs to be updated.

It definitely does. In fact, we're in the process of building a new website for it.

To answer your question about GLUT/GLFW, they're used to provide cross-platform windowing, which is hard to do from C++.

This is already included in OpenTK, so instead of fiddling with GLControl, I'd suggest that you use the OpenTK `GameWindow` class, which is very easy to work with. [You can find an example here](http://www.opentk.com/doc/chapter/0).

Note that the tutorial also includes out of date OpenGL code, but at least shows you how to create a window and where everything goes.
