### ISSUE TITLE
Confusing to find the last version

### ISSUE THREAD

**Issue by FastFrench** [opentk/opentk#397]
It's a bit confusing: on SourceForge, last stable version is labeled 1.1.4. but last changes were done in 2014. 
https://sourceforge.net/p/opentk/news/2014/07/the-open-toolkit-library-114/ 

Same version 1.1.4 appears on what looks like the official website:
http://www.opentk.com/news/opentk-1.1.4-stable-released-with-kms-backend
The last binary link goes to SourceForge (so 1.1.4), where the source link goes here, on GitHub. 

But here the project seems more active, but current version is 1.1.1. 

So I Wonder what is the most up-to-date branch? 

Thank you for your good job ;)

**Comment by alakanu** [comment]
If I am not mistaken, the NuGet package should contain the latest stable version, my friend.

**Comment by FastFrench** [comment]
Actually, I've checked there too, but the result is even more confusing for me. No 1.1.1 or 1.1.4 anymore here, but:
PM> Find-Package OpenTK

Id                                  Versions                                 Description                   
--                                  --------                                 -----------                   
OpenTK                              {1.1.2225}                               The Open Toolkit library (O...
Lyncee.OpenTK                       {1.1.1173.43181}                         Unofficial OpenTK Package     
OpenTK.Rift.Windows                 {1.1.1529.101}                           OpenTK.Rift.Windows adds Wi...
OpenTK.Rift.Linux                   {1.1.1527.101}                           OpenTK.Rift.Linux adds Linu...
OpenTK.Rift.Mac                     {1.1.1529.101}                           OpenTK.Rift.Mac adds Mac OS...
Lyncee.OpenTK.Compatibility         {1.1.1173.43181}                         Unofficial OpenTK Compatibi...
Lyncee.OpenTK.GLControl             {1.1.1173.43182}                         Unofficial OpenTK GLControl...
OpenTK.Rift                         {1.1.1529.101}                           OpenTK.Rift is an intuitive...
DeltaEngine.OpenTK                  {1.1.0}                                  OpenGL Version of the Delta...
OpenTK.NETCore                      {1.1.2287.6424}                          The Open Toolkit library (O...
Str1ker.OpenTK                      {1.1.2253}                               The Open Toolkit library (O...
ppy.OpenTK                          {1.1.2225.1}                             The Open Toolkit library (O...
OpenTK.GLControl                    {1.1.2225}                               Add OpenGL graphics to your...
OpenTK.Next                         {1.1.1616.8959}                          The Open Toolkit library (O...
Axiom.RenderSystems.OpenGL.OpenTK   {0.8.3376.12322}                         Axiom.RenderSystems.OpenGL....
Str1ker.OpenTK.GLControl            {1.1.2253.1}                             Add OpenGL graphics to your...
ppy.OpenTK.GLControl                {1.1.2225}                               Add OpenGL graphics to your...
AdamsLair.OpenTK                    {1.1.6}                                  A custom version of OpenTK ...
AdamsLair.OpenTK.GLControl          {1.1.6}                                  A custom version of OpenTK ...
Axiom.Platforms.OpenTK              {0.8.3376.12322}                         Axiom.Platforms.OpenTK

**Comment by varon** [comment]
Thanks for keeping us posted with your comments, @FastFrench. 

As things stand, we're working on a new website and an updated NuGet package (which there is already a pre-release for). This should help alleviate this confusion. If you need any further help, drop by the [Gitter chat room](https://gitter.im/opentk/opentk) and ask!
