### ISSUE TITLE
IME API?

### ISSUE THREAD

**Issue by CallumDev** [opentk/opentk#398]
I require some more fine control over how IME is set up. When using Eto.Forms (or any GTK2-based toolkit) before running OpenTK, candidate lists appear in the top left of the window whenever a key is down. The expected behaviour is for the key to repeat.

A function to disable IME, or to allow a way to modify the behaviour is required. (Example of an API:  https://wiki.libsdl.org/Tutorials/TextInput ). Test Case:

```
using System;
using OpenTK;
using Eto.Forms;
namespace SDLTest
{
    class MainClass : GameWindow
    {
        public static void Main(string[] args)
        {
            new Application().Run(new Form());

            using (var m = new MainClass())
            {
                m.KeyPress += delegate (object sender, KeyPressEventArgs e) {
                    Console.WriteLine(e.KeyChar);
                };
                m.Run(60);
            }
        }
    }
}
```

Operating System: Mac OS 10.11.5
Architecture: 32-bit
Backend: SDL2

**Comment by varon** [comment]
Thanks for the report, @CallumDev.
Can you provide a minimal code example, the system configuration, and finally what the current and expected behaviours are?

**Comment by CallumDev** [comment]
I've re-written the bug report with some useful information.

**Comment by varon** [comment]
How does this relate to #437 ?

**Comment by Nihlus** [comment]
Closing as a duplicate of #437.
