### ISSUE TITLE
Usage of SIMD via System.Numerics

### ISSUE THREAD

**Issue by MaitreDede** [opentk/opentk#401]
Hi :)

After reading [this blog post](http://instil.co/2016/03/21/simd-with-csharp.html), I wonder if using System.Numerics code would be better.

Any idea ?

**Comment by varon** [comment]
Thanks for the suggestion, @MaitreDede.

When OpenTK was authored, no such library existed, so we had to roll our own. The `System.Numerics` ones are pretty good, but are pretty 'minimal', meaning they provide no 2x2 or 3x3 matrices, no half precisions, etc. We'd need to carefully look at where the holes in our API would arise from this.

OpenTK is currently still currently targeting .Net 2.0, which means we don't have RyuJIT available for SIMD. We're currently looking at moving this up to a less ancient version in the next release.

@thefiddler, could you give us a quick 1 to 10 feasibility assessment on this?

**Comment by varon** [comment]
We've moved up to a new .Net version, but I'm going to close this as it's pretty old. It's probably worth re-looking at at after .Net Standard 2.0.
