### ISSUE TITLE
GPU affinity

### ISSUE THREAD

**Issue by myier** [opentk/opentk#402]
Nvidia has created in 2006 an [extension](https://www.opengl.org/registry/specs/NV/gpu_affinity.txt) for GPU affinity: ability to choose on which GPU an OpenGL application will be executing. OpenGL defaults to the first, and I haven't seen a way to change this behaviour in OpenTK.
Would it be possible to provide access to a similar feature in OpenTK?

Thank you

**Comment by varon** [comment]
Thanks for the report, @myier.

Have you tried playing around with manual context creation? Take a look at `OpenTK.Graphics.GraphicsContext`.

**Comment by myier** [comment]
Hello varon, thanks for the hint, but I'm sorry, I don't see what I can change that relates to that or I don't understand what you mean. I already use the GraphicsContext constructor that takes a GraphicsMode, a window from Utilities.CreateWindowsWindowInfo() and OpenGL version and flags. Can you be more specific?

**Comment by varon** [comment]
[Try this constructor](https://github.com/opentk/opentk/blob/9976a4a4229c842d3c514c6fc6a525a63c7454c2/Source/OpenTK/Graphics/GraphicsContext.cs#L228).

It takes a handle to a GraphicsContext created outside of OpenTK, which should allow you to create it however you please.

**Comment by myier** [comment]
Thank you varon. It's a bit too difficult for me, so I'll probably not do it. I have found that this extension is not available on windows unless the system contains a quadro GPU anyway, what a shame. The extension can be controlled by an environment variable, which is easier to deal with than coding.
Example: OGL_DEFAULT_RENDERING_GPU=id,2.0:17F010DE,00008400,GL - (288,0,161) @ (12288)
Nvidia also installs an extension to windows explorer in that allows in a more friendly way to select the GPU on which to run applications.
But since this is only for quadros, it's as good as useless for the general public.
