### ISSUE TITLE
Centering the mouse

### ISSUE THREAD

**Issue by mcmonkey4eva** [opentk/opentk#406]
What is the correct method to center the mouse in a window?
I've been using this code:

```
            Point center = Window.PointToScreen(new Point(Window.Width / 2, Window.Height / 2));
            Mouse.SetPosition(center.X, center.Y);
```

This works great for me, however a user is reporting it leads to the mouse being slight up and to the left of the exact center, causing lots of issues.
The user also reports that mouse position is reading wrong at times (IE, not aligning to the rendered image. The user is hovering the mouse in one spot, and it's showing a slightly offset item as highlighting). That mouse position is track by the window mouse move event with this code:

```
        public static void Window_MouseMove(object sender, MouseMoveEventArgs e)
        {
            mx = e.X;
            my = e.Y;
        }
```

The user reporting this error is on XUbuntu 14.

**Comment by mcmonkey4eva** [comment]
From a recent update by the user, it sounds like `PointToScreen` is not transforming the point at all, but rather returning the input value on his setup. This was shown by moving the window around - if the window is at the top-left of the screen, it is centered correctly, but at any other position, it's position is as though the window were in the top left regardless.

**Comment by mcmonkey4eva** [comment]
Update: Upon updating OpenTK fully, user said this:
"""
so if the window is full height, shrunk in width, and pined to the left side of the screen it works as expected. If i move that window to the right side of the screen, now instead of the mouse staying where it was and appearing as if it is to the left of the crosshairs, it has moved to the right of the cross hair. Shrinking the height is all donked up. So i maxed the width but shrunk the height and pinned to the top of the screen, the pointer is below the crosshair by about the height of the window ittle bar. moving the window to the bottom of the screen, the pointer is below the crosshair by about the distance of the move plus the height of the titlebar
"""

**Comment by varon** [comment]
Closing due to this hopefully being resolved. (and the fact that it's ancient!)
