### ISSUE TITLE
All GetProgramResourceName marked obsolete.

### ISSUE THREAD

**Issue by ToddBertaOldham** [opentk/opentk#415]
All overloads for GL.GetProgramResourceName are marked as obsolete with the message "Use out overload instead". I found an [old post](https://github.com/opentk/opentk/issues/152) with the same issue for a different method. Turned out to be a generator bug.

**Comment by varon** [comment]
Thanks for the report, @DoctorEclipse. Which version was this occuring on?

**Comment by DoctorEclipse** [comment]
This was occurring on 1.2.2336.6514-pre, the latest NuGet version. Should I go ahead and close this?

**Comment by rjamesnw** [comment]
Having the same issue. (using the latest on nuget).

**Comment by klotzambein** [comment]
Having the same issue on .Net Core (also latest on NuGet)
