### ISSUE TITLE
OnMouseMove called without moving the mouse

### ISSUE THREAD

**Issue by tzachshabtay** [opentk/opentk#416]
I'm getting the above message on my debug output a lot. I get it on a Windows10 laptop (using its built in mouse pad). I get the message to the point that I can't see my own debug messages due to all of the noise from this message.

I looked into it and saw that GetMouseMovePointsEx (called from WinGLNative.HandleMouseMove) returns two consecutive identical points in its 64 points history, and there's no check against that in WinGLNative.
So we should either add the check in WinGLNative and avoid calling OnMouseMove for 2 consecutive identical points, or alternatively simply remove the debug message from NativeWindowBase (as it already does the same check for all platforms).

**Comment by varon** [comment]
Thanks for the report, @tzachshabtay. Does this occur only on your specific hardware configuration, or can you reproduce it on a 'traditional desktop' ?

**Comment by tzachshabtay** [comment]
I reproduced it on a Win7 desktop with a mouse.
