### ISSUE TITLE
MultiDrawElements has an incorrect generated parameter type

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#423]
For half a day I've been trying to figure out why my game rendering is borked when built with x64 as target platform. Turns out this is due to the fact that MultiDrawElements's parameter "const GLvoid \* const \* indices" seems to be a memory pointer which goes in 8 byte increments on x64, the method however accepts an array of ints through opentk, ergo it reads 2 ints in every step instead of 1

Source: https://www.opengl.org/discussion_boards/showthread.php/182391-How-to-use-glMultiDrawElements-and-glDrawElements

Aaand, I could also just confirm & work around this issue by adding a 4 byte padding after every index: 

```
        // For 64 bit architecture we'll pretend sending a long[] array.
        if (IntPtr.Size == 8)
        {
            int[] paddedIndices = new int[indices.Length * 2];
            for (int i = 0; i < indices.Length; i++)
            {
                paddedIndices[i * 2] = indices[i];
            }
        }

        GL.MultiDrawElements(...)
```

With this code in place the game renders correctly again. Though I would very much prefer not to use slow ugly hacks to make it work.

**Comment by varon** [comment]
@tyronx Thanks for the report. As strange as this may be, it does appear to be 'correct' OpenGL behaviour. 

On a practical level, do you really need to support 32 bit versions?

**Comment by varon** [comment]
After carefully re-reading this, it seems as though this is more of an API limitation in OpenTK, as the CLR treats int/long sizes independent of platform. Even if we changed the API to take longs, we'd probably have the reverse occurring on 32 bit platforms.

It might be worth digging around some other open projects to see how they work around this.

@cra0zy  - any ideas here?

**Comment by tyronx** [comment]
Maybe just offering an additional api call that takes in a long[] array would be enough already.

**Comment by mellinoe** [comment]
Based on the docs [here](https://www.opengl.org/sdk/docs/man/html/glMultiDrawElements.xhtml), the `indices` parameter should probably be an array of `IntPtr`, not `Int32`.

**Comment by Frassle** [comment]
Just checked the bindings for glMultiDrawElements. They either take a plain IntPtr or a generic array. We don't create bindings to take int[].

I agree with @mellinoe that it should probably generate an IntPtr[] binding to make it clear, but in the mean time there's nothing stopping users from doing that now `MultiDrawElements<IntPtr>(...)`

**Comment by varon** [comment]
New bindings generator should fix this.
