### ISSUE TITLE
Update debian package

### ISSUE THREAD

**Issue by jpbruyere** [opentk/opentk#424]
opentk version in debian sid is still 1.1, is it possible to make a 1.2 release.

The step to make it are:
- create a release in GitHub tagged 1.2.
- check with debian-cil team if some changes are required in the debian directory. (I will do this)

**Comment by varon** [comment]
As discussed at length in Gitter, I'm against maintaining a random debian package for OpenTK, as it's completely obsoleted by NuGet.

If another maintainer wishes to take this on, they're welcome to do so. @amulware @cra0zy.

**Comment by cra0zy** [comment]
I am fine with doing a 1.2 release.

@varon I don't see what you are talking about considering on our side we only need to do a GitHub release, we are not the ones that will be maintaining the debian package. Most developers don't maintain distro specific packages of their software.

**Comment by varon** [comment]
Yeah, I realise we wouldn't have to maintain that package, but rather I'm against encouraging inferior solutions to NuGet. If you want to do it, no objections at all.

**Comment by jpbruyere** [comment]
Now that the 2.0.0 is released, could you please create a Release in GITHUB, so that debian package could be updated. Thanks in advance.

**Comment by cra0zy** [comment]
https://github.com/opentk/opentk/releases

**Comment by jpbruyere** [comment]
Wonderful, thanks a lot!
