### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by wheybags** [opentk/opentk#425]
Hey, so I know this is probably not the right place for this, but as the issue relates to the website being unusable, I think this is the only place I can raise the issue.
The website is:
1. Full of spam. Even in the documentation: http://www.opentk.com/doc (and of course the forum http://www.opentk.com/forum/2)
2. So slow as to be sueless. Probably because of issue 1.

Is anyone in charge of this? It really doesn't look good :s
My recommendation would be to just move to a simple static site on github pages.

**Comment by alakanu** [comment]
It is an open issue, github pages are already under construction. However I am quite positive that peole who took charge of the work could use an extra hand, but i'm not 100% sure :). There should be an open thread here about this issue :)

**Comment by varon** [comment]
You're 100% right.
We've completely scrapped it, and you can view a new website at [opentk.github.io](https://opentk.github.io)

Unfortunately the only maintainer, @thefiddler who has access to the OpenTK.com domain hasn't yet pointed it to the new site.

**Comment by Krythic** [comment]
I'm really glad to hear that OpenTK is not dead, and keeps having life breathed back into it. I always have the source code saved, and plan on the eventuality of continuing your guys work in the off chance that the project does actually die. This framework is just too important; the only thing it's seriously missing is an off-branching Vulkan API...and some physics collision data types. Forgive me, I started rambling.

**Comment by kiwidoggie** [comment]
@varon The new website doesn't have all of the documentation, tutorials, etc. Have those at least been retained from the previous site to be put up as an archive? I'm currently in the middle of a pretty large OTK project and this is very inconvenient.

**Comment by varon** [comment]
@kiwidoggie You're correct on this. As best I can tell, none of the active maintainers have any idea why the website was taken down. We're still trying to get in touch with @thefiddler to get the domain pointed across.

As for the tutorials, what are you trying to do? Perhaps I can help. Otherwise [ask in gitter](https://gitter.im/opentk/opentk) if you run into a specific issue.

**Comment by kiwidoggie** [comment]
Well I was in the middle of using OpenTK and GLControl for a map editor (I'm also relatively new to OpenGL in general) so I was looking at a bunch of previous examples and the forums for other's work :)

**Comment by varon** [comment]
For the OpenGL stuff, which seems to be most troublesome, you can easily use any C++ resource. These are generally vastly better written than the ancient OpenTK/GL tutorials.

Check out http://learnopengl.com/
If you really need some OpenTK specific documentation, this is ancient, but might help:
https://github.com/mono/opentk/blob/master/Documentation/Manual.pdf

**Comment by jackmott** [comment]
I've also noticed you can get at the old website info via the google cache (click the green arrow on the search results)

That will only last so long though!

**Comment by jps** [comment]
Would it be possible to host the source of the new site on github then other people can maintain an contribute articles?

**Comment by varon** [comment]
It's on GitHub already! We'd love to get some contributions. 

https://github.com/opentk/opentk.github.io

**Comment by varon** [comment]
https://opentk.github.io

**Comment by LMLB** [comment]
You can also get to the old website via the wayback machine:
https://wayback.archive.org/web/20150205231043/http://www.opentk.com/

**Comment by jackmott** [comment]
Might be a good idea to scrape that wayback machine and put all that stuff into an archive of some kind on the new site.

**Comment by LMLB** [comment]
I agree.

If, in the future, someone were to add a `robots.txt` that disallows web crawlers from crawling all/parts of the site, the wayback machine would retroactively exclude whatever the `robots.txt` disallows.
