### ISSUE TITLE
Multiple mice on macOS

### ISSUE THREAD

**Issue by Phyyl** [opentk/opentk#429]
### Description

Multiple mice connected to a macOS only registers events from the first one (e.g. trackpad on a MacBook).
### Repro steps
1. Connect at least two mice
2. Call `Mouse.GetState()` and print the button states to the console
3. Click using the first mouse
4. Click using the second mouse
5. Only the events from the first mouse should appear
### Expected behavior

I'd expect mice to be merged
### Actual behavior

Only the first mouse is registered
### Related information
- OSX 10.11.3
- Native backend
- 1.1.1589.5942 (Nuget)
- .Net Framework 4.5.2

**Comment by varon** [comment]
Thanks for the report.

We expose multiple devices, try using the `Mouse.GetState(int)` function, it should allow you to index into the others.

**Comment by varon** [comment]
Let me know if that works, then we can wrap this up.

**Comment by Phyyl** [comment]
I realized the problem was somewhat deeper than that and I made  another issue. We can close this one. Here's the actual [issue](https://github.com/opentk/opentk/issues/456)
