### ISSUE TITLE
Where is the document or sample?

### ISSUE THREAD

**Issue by akinobufujii** [opentk/opentk#435]
### Description

issues is the title Street
### Repro steps

> Project website: http://www.opentk.com/

Web site does not exist.
Github in no sample is present.
Where do you want to present documents or samples?

I want to use this framework.
However, the document also be no sample.
in trouble.
I want you to help.

**Comment by GameKyuubi** [comment]
I'm in a similar situation.  I'm trying to use this nice looking tool, but documentation is very sparse and outdated.

**Comment by varon** [comment]
Hi Chaps, 

At the moment, the website is currently in limbo. We need someone to write basic tutorials on how to create a window and receive input.

Where are you stuck? OpenTK includes a very decent XML documentation. This should show up in-line in your IDE as you work.

For OpenGL, we advise using [learnopengl.com](http://learnopengl.com/), which is trivially easy to port over to OpenTK.

If you really need some OpenTK specific documentation, this is ancient, but might help:
https://github.com/mono/opentk/blob/master/Documentation/Manual.pdf

**Comment by WernerWenz** [comment]
As a minimal setup example I'd suggest starting off with something like this:

- Create a new project in VS or MonoDevelop
- Install the OpenTK NuGet package or reference OpenTK.dll
- Use something like the following code:

```csharp
using OpenTK;
using OpenTK.Graphics.OpenGL;

namespace OpenTKQuickStart
{
    static class Program
    {
        static void Main()
        {
            using (var win = new GameWindow())
            {
                win.Load += (s, e) => { /* init global GL resources here */ };
                win.Unload += (s, e) => { /* dispose global GL resources here */ };
                win.RenderFrame += (s, e) =>
                {
                    // Rendercode goes here
                    GL.ClearColor(0.8f, 0.8f, 1.0f, 1.0f);
                    GL.Clear(ClearBufferMask.ColorBufferBit);
                    win.SwapBuffers();
                };
                win.Run();
            }
        }
    }
}
```

from there on you can follow pretty much most OpenGL examples for other languages.

**Comment by toddcarnes** [comment]
The web site is https://opentk.github.io/, not http://www.opentk.com/.

**Comment by palhotel** [comment]
Hi , there is a doc. [https://developer.xamarin.com/api/namespace/OpenTK/](https://developer.xamarin.com/api/namespace/OpenTK/)

**Comment by rejurime** [comment]
This could help http://neokabuto.blogspot.com.ar/ and the Github repo is https://github.com/neokabuto/OpenTKTutorialContent
