### ISSUE TITLE
Feature request: IME support

### ISSUE THREAD

**Issue by WernerWenz** [opentk/opentk#437]
### Description

This ticket shall provide a place to discuss on how to add IME support to OpenTK.
### Current state

As of now OpenTK offers Keyboard input feedback via either polling the keyboard state or Key\* events.
As OpenTK translates Keys to an OpenTK specific Key enum it makes using an external IME library even harder.

There is not really a feasable way, a user could build a internationalizable GUI based on OpenTK.
Preferably users should have some way to tell OpenTK that input shall run through an IME processor and get callbacks from that processor.
### Details

For flexibility we should have some IME-Context object. Users would create such a context for example for each GUI element they want to add. At most one context can be active on an OpenTK window. If an context is active, key handling shall run through this context. The context object shall have events the user application can subscribe to in order to signal display of pre-edit text or commited text.
### Implementation

On Linux based systems libibus can be used and an ibus_input_context may mapped quite straigh to an IME-Context object.

On Windows the window message loop has to handle the WM_IME_\* messages
### References

[QT's implementation](https://www.kdab.com/qt-input-method-depth/) might be used as reference.
However it is probably way above the complexity level we'd need, as OpenTK is just a low level library and not an GUI framework.

[libibus](https://github.com/ibus/ibus/)
[IME on windows](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318653%28v=vs.85%29.aspx) 
### Possible discussion points
- Shall IME support be part of OpenTK?
- How shall the required Interface(s) look alike?
- Support of other OS's

**Comment by tzachshabtay** [comment]
Should this be merged into #398 ?

**Comment by WernerWenz** [comment]
@tzachshabtay: Of course,  that'd make sense.

Here I'd pretty much like to flesh out the interface OpenTK should expose.
After that I could add support for windows and ibus. 

The minimal functionality I'd suggest would consist of signaling preedits and commits.
Additional functionality might be for example enumarating installed IMEs and selecting/switching between them programatically.

**Comment by WernerWenz** [comment]
So far I could implement basic functionality on Linux:
![Screenshot](https://github.com/WernerWenz/IbusTest/blob/master/ss.png?raw=true)
[Sample App](https://github.com/WernerWenz/IbusTest/blob/master/ImeTest/ImeTest/Program.cs)

The Interface is pretty basic at the moment:

public Action<string, int, bool> UpdatePreedit;
public Action<string, int, bool> UpdateAxuiliary;
public Action<string[], bool, uint> UpdateCandidates;
public void ProcessKey(RawKeyEventArgs args, bool down);

where RawKeyEventArgs wraps the original X11 key input before translating them to OpenTK Keys.
If possible i'd like to keep the IME Context as seperate from the native window implementations as possible.
Reasons here being:
- It may be useful to reuse the IME processor for different implementations (SDL/X11 etc.)
- More control for the OpenTK user (you can decide what to pass to the IME processor via ProcessKey and what not)

Any thoughts on it?

**Comment by varon** [comment]
Having thought about this, are you sure IME doesn't work when you're using event-based input, i.e. listening to `Window.KeyPress` ?

**Comment by WernerWenz** [comment]
This won't work unfortunately, because the IME processors need the raw key args and not translated ones. You could try to translate  key events back but this would be a lossy conversion (might not work properly or at all) or expose some way to process the raw events. In the sample app I just exposed these.

I'd definitly suggest to decouple the IME processor from the actual window processing code.
Reason being, that it may be possible to use the IME processor for different platforms i.e. use the Linux/Windows IME processor with the SDL, in case SDL ever happens to expose raw events or some IME functionality.

On windows things get even messier btw. I couldnt find any way to postprocess events via IME. The normal way it works is that you "just" process special IME messages, that windows automagically supplies.

**Comment by varon** [comment]
Closing until someone can PR this in.
