### ISSUE TITLE
Touch screen (fingers, pen) support

### ISSUE THREAD

**Issue by mcmonkey4eva** [opentk/opentk#438]
How would I go about supporting a touch screen's input in OpenTK?

There are two sub-categories of touch screen:
- finger touching (wide)
- and pen touching (precise)

Both need to be handled neatly, separately from mouse input.

At the moment, they're just recognized as twitching about the mouse, which isn't particularly effective to work with.

EDIT: Also, multi-touch is a thing. That needs to be handled as well.

**Comment by alakanu** [comment]
Hey, I think you might want to get a look at #437

**Comment by varon** [comment]
Fair question. Seems nobody ever actually got round to answering.

There's basically two approaches to input, Event or Polled.
OpenTK supports both for different use cases.

Event is pretty simple to write - just listen to whatever events the OS is giving you and wrap them up in nice and friendly OpenTK types, such as Vector2, etc. You can expose these by adding them to NativeWindow or something.

The Polling approach is slightly lower level, but arguably more flexible. I'd conceptually approach it like we do for all of the other input categories:
TouchDevice
PenDevice

Specifically, you would want to add these to the factories, with platform-specific implementations added for each one. On Android/iOS, you would probably need to listen to and track the platform specific events too.

Hopefully that helps.

Catch us on Gitter for follow up questions, etc.
