### ISSUE TITLE
OpenTK's homepage is down

### ISSUE THREAD

**Issue by JanWosnitza** [opentk/opentk#440]
http://www.opentk.com/ is down.

![image](https://cloud.githubusercontent.com/assets/2276629/19263168/403c07f0-8f9b-11e6-92c3-114c5c4abccd.png)

**Comment by alakanu** [comment]
github pages are live https://opentk.github.io/

**Comment by JanWosnitza** [comment]
Then change the link on root/READ.md?

![image](https://cloud.githubusercontent.com/assets/2276629/19303190/ff6c70c0-9067-11e6-9a8b-f71ce3c71f05.png)

**Comment by alakanu** [comment]
Yup, the correct link is in the news section.

**Comment by billypilgrim-uk** [comment]
on a related note, the documentation doesn't seem to be present on the new website. the example projects listed all point to the old website.

it would be handy to have some tutorials up there.

**Comment by wcdeich4** [comment]
@billypilgrim-uk the new site is https://opentk.github.io  but we are slowly rebuilding. Please be patient, but if you get any of the old examples to work with the new OpenTK on your github, we'd love for you to send us a link to it :)

**Comment by rejurime** [comment]
@billypilgrim-uk I use this https://github.com/neokabuto/OpenTKTutorialContent (http://neokabuto.blogspot.com.ar/) tutorials and work fine with the OpenTK 2.0.0 nuget dependecy

**Comment by billypilgrim-uk** [comment]
thanks :-)
