### ISSUE TITLE
Clarification about state of OpenCL support

### ISSUE THREAD

**Issue by hokb** [opentk/opentk#441]
### Description

I heard that OpenTK once supported OpenCL. In the docs there are some references to OpenCL 1.0 types & signatures. However, most code is inside an 'Experimental' region currently and not included by default. 

Are there any plans to support OpenCL officially?

Any plans to update to OpenCL 2.0? 

If not: what was the reason, if any, to abandon it from OpenTK? This project looks pretty close? 
I am considering to contribute some efforts regarding this topic but find it hard to find a direction to start? In my naive expectation OpenCL signatures should work very similar to the other, namely OpenGL, OpenAL,... ,no ?

**Comment by varon** [comment]
@cra0zy - Any ideas on this?

**Comment by blackcity** [comment]
Same question here:
Can anybody please explain why OpenTK stopped this. As I can see there was a PR from @thefiddler back in 2014 that included bindings for OpenCL 2.0.

**Comment by winterhell** [comment]
Somewhat related question, On the wikipedia for Nvidia GeForce, it says even the newest cards support only OpenCL 1.2. So if you are with a GeForce, does that mean OpenCL 2.0 is only usable on the CPU and you dont get the advantages of hardware acceleration on the GPU?

**Comment by varon** [comment]
At the moment, OpenTK does not provide OpenCL bindings. The SOLE reason is a lack of manpower at the moment.

We would like someone to help add them, but we'll need an external PR for that.
