### ISSUE TITLE
IMPOSSIBLE to create Cubemap Arrays (added repro info)

### ISSUE THREAD

**Issue by livinamuk** [opentk/opentk#442]
### Description

It is not possible to use a cube map array in OpenTK because to allocate storage you must specify the TextureTarget3d type and there is no GL_TEXTURE_CUBE_MAP_ARRAY equivalent.   
### Repro steps

To reproduce the issue, enter the GL.TexStorage3D function name and attempt to use a cubemap array for the first parameter. `OpenTK.Graphics.OpenGL4.GL.TexStorage3D(TextureTarget3d.CubeMapArray, 0, format, width, height, depth));` is not allowed.  IntelliSense will show the only available options:

TextureTarget3d.ProxyTexture2DArray
TextureTarget3d.ProxyTexture3D
TextureTarget3d.ProxyTextureCubeMap
TextureTarget3d.Texture2DArray
TextureTarget3d.Texture3D
TextureTarget3d.TextureCubeMap
### Version

Still absent in OpenTK.Next 1.2.2336.6514-pre

**Comment by livinamuk** [comment]
Surely this is a huge deal. Without cubemap arrays it's basically impossible to achieve multiple dynamic point light shadows.

**Comment by varon** [comment]
Apologies for leaving this for so long. Are you still encountering this issue?

If you could offer a PR for this, I'd be happy to merge it in.

**Comment by varon** [comment]
This is available via the extension `ArbTextureCubeMapArray`.
