### ISSUE TITLE
OpenGL ES 3.1 support

### ISSUE THREAD

**Issue by matyasf** [opentk/opentk#443]
Will OpenGL ES 3.1 supported in the future? The old OpenTK had this feature.
Thanks
- Operating system  
  Windows
- What version of OpenTK (Installer, NuGet, Source Code)  
  NuGet 2.0.0 
- What runtime (.NET Framework, CoreCLR, Mono)  
  Xamarin

**Comment by wcdeich4** [comment]
@cra0zy @varon @amulware - I know there is a need to move on to newer features, but can can we keep the older versions of OpenGL for  while?

**Comment by matyasf** [comment]
Hmm OpenGL ES 3.1 is not old..it was released in 2014, and it's supported by Android 5.0 or greater. And OpenTK still supports OpenGL ES 2.0 (rightfully so, its used by most mobile game engines)

**Comment by wcdeich4** [comment]
@cra0zy   @varon   @amulware - @matyasf was talking about using OpenGL ES 3.1 & @iOutSide was talking about OpenGL 1.1.0.  My personal laptop only supports OpenGL 2.0.  I think we need to decide what the cut off should be.  It would be nice if we could support legacy code forever, but there has to be a cutoff somewhere.  Why don't you guys discuss what the cut off should be?

**Comment by varon** [comment]
@wcdeich4 
I think we need to draw a distinction between providing bindings for, and supporting.

#### OpenGL
The lowest I profile I would be in favour of supporting would be 3.x. For any new development, I suggest 4.1 Core as the recommended context. 

However, we've already got the bindings for earlier versions. There's no point removing these until we can review the IL rewrite part of the compilation. Once we do this, removing them is a good thing, as it would prevent a lot of incorrect and deeply inefficient OpenGL coding practice.

#### GLES

Supporting and providing bindings for 2.0 and 3.0 seems like a reasonable approach at this time.

3.1 is the 'cutting edge' version. It runs on a [vanishingly small percentage of devices](https://developer.android.com/about/dashboards/index.html) (<13% at the time of writing).

@matyasf You mentioned that the "The old OpenTK had this feature" when referring to GLES 3.1 bindings. Which version and fork was this? Once we've identified it, hopefully we can put together a PR to get it merged back into here.

**Comment by matyasf** [comment]
@varon the one that came with Xamarin I guess? Its version 1.0.0 and supports android too.

**Comment by varon** [comment]
@matyasf Ah, drat. That's literally an ancient fork from YEARS ago.

It looks like #142 might have related to this functionality, but it was never merged (and ended up incompatible now anyway).

I'd be more than happy to add support for 3.1 or 3.2 if we can get a PR for it.

**Comment by varon** [comment]
Closing due to manpower shortage. If someone can PR in this, we'd love to add it.
