### ISSUE TITLE
Problem with 'Stencil buffer', incorrect representation of the example 'Stencil CSG'

### ISSUE THREAD

**Issue by migueltk** [opentk/opentk#444]
# _Operations in the 'stencil buffer' do not take any effect to run the example "Stencil CSG"._

---

**Observe the problem in the following configurations**:
   Ubuntu 16.04 and 16.10 (64bit and 32bit), using X11 and SDL2
   Fedora 24 64bit, using X11 and SDL2
   Windows 7 (64bit and 32bit) only using SDL2

---

**Runs smoothly in the following configurations**:
   Ubuntu 16.04 and 16.10 (64bit and 32bit), using X11 and SDL2 (virtualized with VirtualBox 5.1.6)
   Windows 7 (64bit and 32bit) only using Native backend

---

**Using**:
   OpenTK 2.0 (from NuGet)
   mono/.net 4.5
   SDL2 (libSDL2-2.0.so.0.4.0)

---

 **Related information**:
   In this other project I also note the problem "CsNanoVG" (ported from C to C# for me, available to the community and available in "https://sites.google.com/site/bitiopia/").
Want to emphasize that the native version of NanoVG in C and using GLFW shown no problems in my graphics hardware, then, is not a problem associated with Gallium 0.4.

Below, "framebuffers channels: Stencil Bits = 0", this worries me ... Having relation to the problem?

---

**OpenGL diagnostics**:

Vendor: X.Org
Renderer: Gallium 0.4 on AMD KAVERI (DRM 2.46.0 / 4.8.0-26-generic, LLVM 3.8.1)
GL Version: 4.1 (Core Profile) Mesa 12.0.3
Unsupported Token: MajorVersion
MinorVersion: 1
GLSL Version: 4.10
Extensions: 

--- Framebuffer ---
Doublebuffer: True
MaxColorAttachmentsExt: 8
MaxDrawBuffers: 8
AuxBuffers: 0
DrawBufferExt: Back
MaxSamples: 8
MaxViewportDims: ( 16384, 16384 )
Viewport: ( 0, 0 ) ( 80, 60 )
--- Framebuffer channels ---
RedBits: 8
GreenBits: 8
BlueBits: 8
AlphaBits: 8
DepthBits: 24
StencilBits: 0
AccumRedBits: 0
AccumGreenBits: 0
AccumBlueBits: 0
AccumAlphaBits: 0
--- Textures ---
MaxCombinedTextureImageUnits: 160
MaxVertexTextureImageUnits: 32
MaxTextureImageUnits: 32
MaxTextureUnits: 8
MaxTextureSize: 16384
Max3DTextureSize: 2048
MaxCubeMapTextureSize: 16384
MaxRenderbufferSizeExt: 16384
MaxTextureLodBias: 16
--- UN-supported Texture formats ---
Alpha, Alpha4, Alpha8, Alpha12Ext, Alpha16, RestartSun, ContextCompatibilityProfileBit, R8ui, Rg8ui, Rgb8ui, Rgba8uiExt, R16ui, Rg16ui, Rgb16ui, Rgba16uiExt, R32ui, Rg32ui, Rgb32uiExt, Rgba32uiExt, R8i, Rg8i, Rgb8i, Rgba8i, R16i, Rg16i, Rgb16i, Rgba16iExt, R32i, Rg32i, Rgb32i, Rgba32i, CompressedLuminanceLatc1Ext, CompressedLuminanceAlphaLatc2Ext, CompressedRgbFxt13Dfx, CompressedRgbaFxt13Dfx, CompressedSignedLuminanceAlphaLatc2Ext, CompressedSignedLuminanceLatc1Ext,  
--- SUPPORTED Texture formats ---
AlphaFloat16Apple   Alpha  HalfFloat
AlphaFloat32Ati   Alpha  Float
DepthComponent   DepthComponent  Int
DepthComponent16Arb   DepthComponent  Float
DepthComponent24   DepthComponent  Float
DepthComponent32   DepthComponent  Float
DepthComponent32f   DepthComponent  Float
DepthStencilNv   DepthStencil  UnsignedInt248
Depth24Stencil8Ext   DepthStencil  UnsignedInt248
Depth32fStencil8   DepthStencil  Float32UnsignedInt248Rev
Rgb   Rgb  UnsignedByte
Rgba   Rgba  UnsignedByte
Srgb   Rgb  UnsignedByte
SrgbAlphaExt   Rgb  UnsignedByte
Srgb8   Rgb  UnsignedByte
Srgb8Alpha8Ext   Rgba  UnsignedByte
R16f   Red  HalfFloat
Rg16f   Rg  HalfFloat
RgbFloat16Ati   Rgb  HalfFloat
Rgba16f   Rgba  HalfFloat
R32f   Red  Float
Rg32f   Rg  Float
Rgb32f   Rgb  Float
RgbaFloat32Ati   Rgba  Float
R8   Red  UnsignedByte
Rg8   Rg  UnsignedByte
Rgb8   Rgb  UnsignedByte
Rgba8   Rgba  UnsignedByte
R3G3B2   Rgb  UnsignedByte
Rgb10A2   Rgba  UnsignedByte
Rgb5A1Ext   Rgb  UnsignedByte
Rgb9E5Ext   Rgb  UnsignedByte
R11fG11fB10fExt   Rgb  UnsignedByte
CompressedAlphaArb   Alpha  UnsignedByte
CompressedIntensity   Luminance  UnsignedByte
CompressedLuminanceArb   Luminance  UnsignedByte
CompressedLuminanceAlphaArb   LuminanceAlpha  UnsignedByte
CompressedRed   Red  UnsignedByte
CompressedRedRgtc1   Red  UnsignedByte
CompressedRgRgtc2   Rg  UnsignedByte
CompressedRg   Rg  UnsignedByte
CompressedRgRgtc2   Rg  UnsignedByte
CompressedRgbArb   Rgb  UnsignedByte
CompressedRgbaArb   Rgba  UnsignedByte
CompressedSignedRedRgtc1Ext   Red  UnsignedByte
CompressedSignedRgRgtc2   Rg  UnsignedByte
CompressedSluminance   Luminance  UnsignedByte
CompressedSluminanceAlpha   LuminanceAlpha  UnsignedByte
CompressedSrgbExt   Rgb  UnsignedByte
CompressedSrgbAlphaExt   Rgba  UnsignedByte
CompressedSrgbS3tcDxt1Ext   Rgb  UnsignedByte
CompressedSrgbAlphaS3tcDxt1Ext   Rgba  UnsignedByte
CompressedSrgbAlphaS3tcDxt3Ext   Rgba  UnsignedByte
CompressedSrgbAlphaS3tcDxt5Ext   Rgba  UnsignedByte
CompressedRgbS3tcDxt1Ext   Rgb  UnsignedByte
CompressedRgbaS3tcDxt1Ext   Rgba  UnsignedByte
CompressedRgbaS3tcDxt3Ext   Rgba  UnsignedByte
CompressedRgbaS3tcDxt5Ext   Rgba  UnsignedByte

--- Point&Line volumes ---
AliasedPointSizeRange: ( 1, 16384 )
PointSizeMin: 0
PointSizeMax: 16384
SmoothPointSizeGranularity: 0,1
SmoothPointSizeRange: ( 0, 16384 )
AliasedLineWidthRange: ( 1, 16384 )
LineWidthGranularity: 0,1
LineWidthRange: ( 1, 16384 )
--- VBO ---
MaxElementsIndices: 3000
MaxElementsVertices: 3000
MaxVertexAttribs: 16
--- GLSL ---
MaxCombinedFragmentUniformComponents: 262144
MaxCombinedGeometryUniformComponents: 262144
MaxCombinedVertexUniformComponents: 262144
MaxFragmentUniformComponents: 16384
MaxVertexUniformComponents: 16384
MaxCombinedUniformBlocks: 87
MaxFragmentUniformBlocks: 15
MaxGeometryUniformBlocks: 15
MaxVertexUniformBlocks: 15
MaxUniformBlockSize: 65536
MaxUniformBufferBindings: 87
MaxVaryingFloats: 128
--- Transform Feedback ---
MaxTransformFeedbackInterleavedComponents: 128
MaxTransformFeedbackSeparateAttribs: 4
MaxTransformFeedbackSeparateComponents: 128
--- Fixed-Func Stacks, GL.Push\* and GL.Pop\* ---
MaxClientAttribStackDepth: 16
MaxAttribStackDepth: 16
MaxProjectionStackDepth: 32
MaxModelviewStackDepth: 32
MaxTextureStackDepth: 10
MaxNameStackDepth: 64
--- Fixed-Func misc. stuff ---
MaxEvalOrder: 30
MaxClipDistances: 8
MaxArrayTextureLayers: 2048
MaxListNesting: 64
MaxLights: 8
MaxTextureCoords: 8

**Comment by varon** [comment]
Thanks for the very detailed report.

Could you clarify exactly what the expected behaviour is, and what it's actually doing?

**Comment by migueltk** [comment]
In the following two images I show the problem:

![stencil-opentk-fail](https://cloud.githubusercontent.com/assets/6094037/20844167/ec266852-b8be-11e6-9cb1-e17780d36a24.png)
Fault: The sphere does not create a hole.

![stencil-opentk-ok](https://cloud.githubusercontent.com/assets/6094037/20844227/27fbcc50-b8bf-11e6-8215-83a96d5d62bd.png)
Hit: The sphere creates a hole. This is the expected behavior.

**Comment by varon** [comment]
Could you try manual graphics mode creation with a stencil buffer bit set? 
```
var def = GraphicsMode.Default
var custom = new GraphicsMode(def.ColorFormat, def.Depth, 1, def.Samples, def.ColorFormat, def.Buffers, def.Stereo)
```

**Comment by migueltk** [comment]
I have isolated the test code "Stencil CSG" in the attached project, for quick tests, and I have tried the proposed code but there are no positive results.
[TestStencil.zip](https://github.com/opentk/opentk/files/629005/TestStencil.zip)

**Comment by varon** [comment]
That's really strange.

If you do manage to come up with an answer or fix, we would be happy to merge it in.

**Comment by migueltk** [comment]
@varon
There is a possible solution to the problem, thanks to the help of @jpbruyere, see https://github.com/memononen/nanovg/issues/332#issuecomment-282685771

It is necessary to specify the version of OpenGL (major / minor) in the call to build the GameWindow window, I have tried between 2.0 and 3.0 and it works, otherwise it is not displayed correctly.
In Linux, you also need to specify SDL2 as 'PlatformBackend.Default', with X11 also not working.

**Comment by varon** [comment]
Solved
