### ISSUE TITLE
GL.ClearColor(xxx) didnot work on os x 10.11.3

### ISSUE THREAD

**Issue by chenjd** [opentk/opentk#445]
### Description

when i call GL.ClearColor(..) when OnRenderFrame, the method block process
### Repro steps

Please provide the steps required to reproduce the problem
call  "GL.ClearColor(Color.Blue); " when OnRenderFrame
### Expected behavior

clear with color
### Actual behavior

blocking process
### Related information
- Operating system
  os x 10.11.3
- Native backend
- What version of OpenTK (Installer, NuGet, Source Code)
  NuGet 2.0.0
- What runtime (.NET Framework, CoreCLR, Mono)
  Mono
- Workarounds (if any)

**Comment by varon** [comment]
Thanks for the report.

Could you provide a full code sample to reproduce the issue? Last I checked, I had no trouble calling this on OSX.

**Comment by varon** [comment]
Still waiting for that repro.

**Comment by varon** [comment]
Closing, @chenjd is AWOL and it seems like an API usage error.
