### ISSUE TITLE
OpenTK does not support .NetCoreApp v1.0

### ISSUE THREAD

**Issue by loicmorvan** [opentk/opentk#446]
### Description

OpenTK 2.0 does not seem to support .NetCoreApp v1.0.
### Repro steps

On macOS:
1. On a new .Net Core project, configure project.json to reference "OpenTK": "2.0.0" as dependency and "netcoreapp1.0" as framework.
2. Run the command "dotnet restore".
### Expected behavior

The nuget package OpenTK should be downloaded and ready to be used in my project.
### Actual behavior

An error message shows up when running "dotnet restore":
"Package OpenTK 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package OpenTK 2.0.0 supports: net20 (.NETFramework,Version=v2.0)"
### Related information
- macOS Sierra
- OpenTK 2.0 via NuGet
- .NetCoreApp v1.0

Thanks !

**Comment by mellinoe** [comment]
Related: https://github.com/opentk/opentk/issues/245, https://github.com/opentk/opentk/pull/308

I published a nuget package with roughly the changes from #308 above that I use in my own projects. https://www.nuget.org/packages/OpenTK.NETCore/. It doesn't have some of the latest changes in the master branch here, but is otherwise stable.

**Comment by loicmorvan** [comment]
OK, I replaced the regular OpenTK package by OpenTK.NETCore and it seems to work well.

Do you manage to merge your changes into OpenTK, so that we can have the latest bindings?

Thanks a lot!

**Comment by mellinoe** [comment]
> Do you manage to merge your changes into OpenTK, so that we can have the latest bindings?

Yeah, I would like to do that eventually. It's definitely not my goal to have a separate fork, but at the time it was just easier to publish something quick and dirty that I could use in my own projects. My current thinking is that we should try to push forward with an updated version of #308 when support for [.NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) arrives. It will be easier to integrate with the current build configurations, and we won't need to make any code changes at all to support it (the current PR makes a few inconsequential code changes to work around API differences).

**Comment by loicmorvan** [comment]
Your post and the article about .NET Standard 2.0 are extremely interesting!

Thanks again ^^

**Comment by varon** [comment]
@mellinoe some relevant chat from Gitter. Perhaps you could link up with @SirusDoma on this?
>@SirusDoma
>Hello, what preventing us to use .NET Core? I mean what we should do? perhaps i could help
@varon
>There's nothing stopping us at all! We just need a PR that matches the requirements:
> - Compiles on whatever .Net version we're currently targeting
> - Compiles for .Net core
> - Actually runs on all platforms (with demonstration or statement of testing included in the PR)
> We'd absolutely love to get OpenTK running on .net core, in fact, it's one of the major goals for the coming year!
> I would highly advise speaking to @mellinoe , who I believe has done some work on this.

**Comment by ChillyFlashER** [comment]
GamePad's doesn't work in OpenTK.NETCore. Just to let you guys know. :)

**Comment by varon** [comment]
Targeting .Net core or a .Net standard is one of the major goals of the project, but we do not officially support it yet. Closing.
