### ISSUE TITLE
No printouts (and errors getting swallowed) on Android

### ISSUE THREAD

**Issue by tzachshabtay** [opentk/opentk#447]
### Description

It seems that on Android, the "Minimal" configuration (https://github.com/opentk/opentk/blob/d50c2fcea0696d3cc82aeb339e15c049405129ba/src/OpenTK/Minimal.cs) is used which is using empty stubs for Debug.WriteLine & Trace.WriteLine, which means all errors that are printed by OpenTK are not shown.

As far as I can see, System.Diagnostics can be used in Xamarin Android so no reason not to use it?

### Reproduction Steps

1. Open an audio context with OpenAL on Android.
2. The printout "Enumerating audio devices." for example will not be printed (from https://github.com/opentk/opentk/blob/d50c2fcea0696d3cc82aeb339e15c049405129ba/src/OpenTK/Audio/AudioDeviceEnumerator.cs) and also error are not printed.

### Expected behavior

Printouts from OpenTK should be printed.

### Actual behavior

Printouts from OpenTK are not printed.

### Related information 

* Android
* Native backend
* OpenTK from source code (The Nuget version is missing the android code)

**Comment by varon** [comment]
Do the current builds still work this way? I believe we've nuked the 'minimal' configuration.

**Comment by tzachshabtay** [comment]
Well, actually, the ANDROID compilation flag is also inside Minimal.cs, and the file is included in the android project, so this still applies, as far as I can tell.
