### ISSUE TITLE
OpenTK graphics not displaying on Surface Pro 3/4 tablet

### ISSUE THREAD

**Issue by ronoruganti** [opentk/opentk#449]
Hi,

I have 2 Surface tablets - pro 3 and pro 4 both running Windows 10 and I am trying to run an application that uses OpenTK to view 3D medical images. The graphics card in the surface is: pro3-Intel HD graphics 5000, pro4-Intel HD Graphics 520. I was previously able to view the images on my desktop that has an NVidia Quadro 4000. On the tablets however, the images don't display at all. In the event logs I did see the graphics related error detailed below but I am not sure it is related to my problem).

Log Name:      Application
Source:        igfxCUIService2.0.0.0
Date:          11/14/2016 10:13:50 AM
Event ID:      0
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      SWENGSurface
Description:
The description for Event ID 0 from source igfxCUIService2.0.0.0 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

 The specified service does not exist

The request is not supported

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="igfxCUIService2.0.0.0" />
    <EventID Qualifiers="0">0</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-11-14T15:13:50.884932400Z" />
    <EventRecordID>6973</EventRecordID>
    <Channel>Application</Channel>
    <Computer>SWENGSurface</Computer>
    <Security />
  </System>
  <EventData>
    <Data> The specified service does not exist</Data>
  </EventData>
</Event>

Looking in visual studio the version number for opentk.dll: 1.1.0.0 and for OpenTK.GLControl also 1.1.0.0. I tried using Nuget to upgrade the OpenTK version to 2.0.0.0 but I now get an exception when calling openTK.GLControl.MakeCurrent() (on the machine where openTK was previously functional)

What might be preventing opentk from displaying the images? Per intel's website, openGL is supported. 

Thanks

OS: windows 10
target .NET version for application: 4.5.2
Opentk version: 1.1.0.0 - (openTK1.1 in Control Panel)

**Comment by varon** [comment]
Did you manage to find a solution to your problem?

**Comment by ronoruganti** [comment]
Yes I did thank you for checking. It was actually an error in my code.
