### ISSUE TITLE
iOS and Android configuration

### ISSUE THREAD

**Issue by aloisdeniel** [opentk/opentk#452]
Hi,

I'm a little bit confused : on main page a support for iOS and Android is stated but I've not found any sample on how to configure it.

The unique dll contained in the NuGet package (version 2) seems to have **OpenTK.Platform.<>** for a various set of platforms, but I can't figure out the usage.

How can I create a UIView, UIWindow and start the rendering loop from this ?

Thanks.

**Comment by varon** [comment]
Hi there,

The NuGet package for OpenTK 2.0.0 is for desktop usage.
The OpenTK.Android and OpenTK.iOS packages are not yet released as 2.0.0. If you'd like to play with them, I'd suggest trying to build from source for now.

**Comment by aloisdeniel** [comment]
Okay, thanks, I'll try to build it by myself then! 

Maybe integrating the various platforms in the same package could be easier no ? If the various platform dlls are located in `lib` subfolders, the platform corresponding dll will be referenced  when installing the package (check out the [MvvmLight source code](https://mvvmlight.codeplex.com/SourceControl/latest) for example).

**Comment by varon** [comment]
@aloisdeniel You're 100% correct on this, and that would be the way I'd prefer to have done it.

However, from what I understand, there's actual differences between the code for different platforms. It's not just a different compilation target, which is why we have separate packages for them.

We're in desperate need for some more help on the mobile side of things. If you can get it working, we would hugely appreciate PRs for package builds!

**Comment by aloisdeniel** [comment]
Even with completely different source code (but I'm sure some parts could be shared, this can be achieved by having the iOS and Android specific solutions integrated into develop. Then the packaging script would simply build each solution and copy each `.dll` from `.nuspec` file. But that seems a lot of work since all platform source code isn't in the same branch.

**Comment by varon** [comment]
That's a very fair observation, @aloisdeniel.  The platform code should be in the same branch, actually. Everything should be in develop.

We could do the packaging that way, but I'd regard it as really strange that the same package would have different APIs on different platforms. The current recommended approach is to use shared projects.

From my side, I don't touch mobile at all, so I'm not really familiar with the ins and outs.

Ideally I'd like to see OpenTK refactored into a way more modular library. That way you would just pull in OpenGL on desktop, or GLES on mobile.

**Comment by aloisdeniel** [comment]
You're right, having a clean Portable abstraction, and only platform specific code in dedicated assemblies would be perfect for me. It depends how you want the library to be used.

After starting studying the iOS code, I've seen some Monotouch references that have been replaced by Xamarin.iOS since newer versions of Xamarin. I will submit a pull request with the modifications.

**Comment by varon** [comment]
Awesome, thanks!

**Comment by varon** [comment]
Still looking forward to that PR!

**Comment by varon** [comment]
Closing due to age. No PR at the moment.
