### ISSUE TITLE
GLControl broken with angle

### ISSUE THREAD

**Issue by cpages** [opentk/opentk#457]
I was trying this sample from https://github.com/thefiddler/opentk-wpf, which uses the glcontrol to draw to a wpf app, and with the opentk binaries provided work fine.

When I change those for the nuget ones: (both opentk and opentk.glcontrol v1.1.2349, since there is no glcontrol for 2.0) the gles path fails with an unhandled exception in the glControl.MakeCurrent(); call. The gl (non-es) path, which doesn't use angle, works just fine.

All this is in a windows 10 machine with an nvidia card, if that matters.

**Comment by varon** [comment]
Hi there!

Could you try compiling the GLControl from current dev source and see if you still get the error?

**Comment by cpages** [comment]
That was fast 👍 But now it doesn't even reach that point, with the built dlls and xmls I get a XAML parse exception.

**Comment by varon** [comment]
Is the exception occurring during the build of the extension, or at run-time?

Can you paste the exception?

**Comment by cpages** [comment]
Sorry, I had failed to change the reference (only changed the runtime dlls). Now I get not implemented exceptions:
```
for angle:
public static void ClearColor(Single red, Single green, Single blue, Single alpha) { throw new NotImplementedException(); }
```
```
with gl:
string GetExtensionsString(IntPtr hdc)
{
    throw new NotImplementedException();
}
```

Maybe I did something wrong on build time?

**Comment by bentorkington** [comment]
@cpages I have got this working by using NuGet version 1.1.5849.5941

**Comment by xlphs** [comment]
I also ran into NotImplementedException on Mac 10.11 when I call `ClearColor`, changed to 1.1.1616.8959 from NuGet and it worked. Maybe there is something wrong with NuGet Version 2.0.0.

**Comment by varon** [comment]
Can you guys paste your context versions? That's really odd. I'm using 2.0 on mac here myself, no trouble with that.

**Comment by varon** [comment]
Clarification: If you're experiencing this with GLControl, then it's worth noting that we don't have a 2.0 package for it yet for this reason. If we can figure out what's going on or what causes it, perhaps with a report showing it working, I'll be happy to release a suitable 2.0 package.

**Comment by xlphs** [comment]
@varon I'm actually using GLWidget for GTK#, with NuGet 2.0 version, I tried OpenGL 3.2 and 2.0, they all threw exception. Then I downloaded latest develop branch and compiled OpenTK myself, replaced DLL files, still got exception, so I figured maybe try an older version and that finally worked. I have 2015 retina macbook pro using geforce gt 650m.

**Comment by varon** [comment]
Closing as we're consolidating GLControl issues in #432
