### ISSUE TITLE
Is it possible to use OpenTK without a window?

### ISSUE THREAD

**Issue by Thraka** [opentk/opentk#459]
### Description

I want to use OpenTK to do some graphics processing, but the program will be running as admin and without a user, it cannot show a window. Is this possible?

I essentially want to render a scene of my game engine and output it to a screenshot.

### Related information 

* Operating system  
Windows 10
* SDL or Native backend
* What version of OpenTK  
NuGet

* What runtime  
.NET Framework

* Workarounds (if any)

**Comment by WernerWenz** [comment]
If it is OK to create an invisible window see [this sample]( https://gist.github.com/WernerWenz/67d6f3ebd0309498ed89bcff6c1889a7).

Otherwise you'd have to manually create a GL RenderContext using WinAPI, supplying the DC of an offscreen render target.

**Comment by Thraka** [comment]
Thanks for the sample. Unfortunately it just renders as a black image on the remote server. Locally it works correctly.

**Comment by winterhell** [comment]
If the image is created properly on the local machine then
a) have you tried it with having a window and a user anyway? If it still doesnt work then you have a problem with the transfer.
On that note, are you even receiving the image properly? Try to inspect the data, it might turn out to be correct and you are not displaying it, OR you are not receiving it.

**Comment by Thraka** [comment]
The remote machine is running windows server without a login, so AFIAK there is no GUI host running until the user logs in.

**Comment by winterhell** [comment]
Yes I understand that it is not expected to have a GUI, but can you try it anyway with a logged in user as a test case?

**Comment by Thraka** [comment]
Oh sorry, i misunderstood what you meant. So I just tested it and it's not working correct. It seemed to have grabbed part of the screen, flipped it along the X and Y axis and wrote that to the graphic file. Running locally with the test app it worked as thought.

The test app I did was a winform app that had a button that runs the code.

Perhaps there is no HW acceleration on the server machine..

**Comment by varon** [comment]
From what I can recall, I don't think it's possible to create a graphics context without being logged in as a user on Windows. You can't do certain things as services.
