### ISSUE TITLE
GL.DrawElements doesn't work with hybrid graphix card

### ISSUE THREAD

**Issue by AlexKerman** [opentk/opentk#46]
Graphics card: Intel® HD Graphics 4000 / NVIDIA GeForce 730M.
Tested with two notebooks (Win7 pro and Win8.1).
Code here: https://github.com/AlexKerman/Tentacles/blob/master/FourTentacles/Geometry/Mesh.cs

**Comment by emadhamdybri** [comment]
@hokb @thefiddler How to fix this problem.
