### ISSUE TITLE
Depth testing does not work on Linux

### ISSUE THREAD

**Issue by Nihlus** [opentk/opentk#464]
### Description

Depth testing before the shader using GL.Enable(EnableCap.DepthTest) does not work. Instead, everything is drawn as if the depth buffer is not enabled at all. However, when viewing the depth buffer (simply by passing the value of the depth buffer as the fragment colour), it turns out it is written to, but the values are out of order.

![image](https://cloud.githubusercontent.com/assets/2340428/21289025/3397cbe8-c492-11e6-9e12-ff143e362a7e.png)
Screenshot of issue in another application

![image](https://cloud.githubusercontent.com/assets/2340428/21289027/415f708c-c492-11e6-890a-8e52d780affa.png)
Ditto, with another model

![image](https://cloud.githubusercontent.com/assets/2340428/21289042/ba8b7622-c492-11e6-9993-1d82b5e17a6a.png)
Example code displaying peculiar depth buffer data

### Repro steps

Please provide the steps required to reproduce the problem
Reproducible sample code: [GLWidgetTest.zip](https://github.com/opentk/opentk/files/659015/GLWidgetTest.zip)

1. Open the provided example code

2. Restore NuGet packages and compile. The sample requires GTK3 to be installed. If you're using Windows, get the libraries here: https://download.gnome.org/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi and extract this into the binary folder: [share.zip](https://github.com/opentk/opentk/files/659016/share.zip)

3. Run "GLWidgetTestGTK3". WASD to move, hold right click to rotate and move.

4. Move very close to one of the cubes. You should see incorrect depth data drawn from the buffer.

5. If desired, open "/Shaders/FragmentShader.glsl" and change the fragment shader colour from depth buffer data to passed fragment colour to see the problem in a more typical environment.

### Expected behavior

Depth testing should discard fragments and write the correct values to the buffer.

### Actual behavior

Depth testing does not discard fragments due to issues with the data written to the depth buffer.

### Related information 

* Operating system: Linux Mint 18, x64 (Cinnamon Edition)
* Native backend
* OpenTK.Next 1.2.2336.6514-pre
* Mono
* NVIDIA Binary Driver version 375.26-0ubuntu0~gpu16.04.1

**Comment by varon** [comment]
Thanks for the report.

I suspect this is likely an OpenGL usage issue, or something to do with context creation.


Could you try uncomment line 328 in `MainWindow.cs`?
```			//GL.DepthFunc(DepthFunction.Less);```
Even if you've enabled depth testing, you might need to choose a function to have it work.

**Comment by Nihlus** [comment]
I've previously tested all the depth functions. Unfortunately, none of them produce a different result.

**Comment by winterhell** [comment]
Have you tried with the latest SourceForge version OpenTK 1.1.4c from 24 July 2014?
https://sourceforge.net/projects/opentk/files/opentk/opentk-1.1/stable-5/
Depending if works with those binaries it'll make it easier to track where is the problem.

**Comment by Nihlus** [comment]
I can confirm that the issue occurs using that version of OpenTK as well. I do remember it working with the last NuGet package in OpenTK (not OpenTK.Next), however, that now crashes due to not getting any XVisualInfo structures for some reason.

I'm suspecting it's some peculiarity with the graphics drivers - some regression which has surfaced, or some change by NVIDIA. However, I've tried rolling back the drivers without result.

**Comment by winterhell** [comment]
You can try an OpenGL 3D game that is known to work on Linux. Quake 3 perhaps?

**Comment by Nihlus** [comment]
I play other games on the regular, and those all work fine :( Same with things like Unreal Engine 4 (both in OpenGL 3 and 4 mode)

**Comment by Nihlus** [comment]
More testing done. glGet and glIsEnabled both report the depth test to be enabled and the function set to Less. glGetError reports no error after any of the calls.

**Comment by wcdeich4** [comment]
Wait. Is that bad depth testing, or incorrect face culling? The more I stare at that screen shot, it looks like the "front" face of the cube is not being drawn b/c it is inside the "near plane" but the back faces of the cube are still being drawn, which suggests that no face culling was performed.  If you get so close to one of the cubes that the triangles of the face violate the near plane constraint, those faces should disappear.  If the "back faces" are being culled, then the the cube should "disappear" & not be visible at all.  If the back faces are not culled, then you see the cube "inside out." - I know that's really basic stuff, but that is what it looks like to me

**Comment by Nihlus** [comment]
That could be true, but I've disabled backface culling in that specific image to emphasize the issue (with face culling enabled, it's only visible at a few very specific angles for a simple cube). The first two screenshots have face culling enabled, and you can see that any polygons rendered at an oblique angle such that they are facing the viewer but should be occluded by other geometry are still rendered on top.

**Comment by wcdeich4** [comment]
@Nihlus, in the first 2 screenshots, do you know what near plane value they are using?

**Comment by Nihlus** [comment]
Yes - the near plane is at 0.1f, and the far plane at 1000.0f - relevant source code can be read here: https://github.com/WowDevTools/Everlook/blob/master/Everlook/Viewport/Camera/ViewportCamera.cs

**Comment by wcdeich4** [comment]
Cool. What is the near plane for GLWidgetTest?

**Comment by Nihlus** [comment]
It's the same.

**Comment by Nihlus** [comment]
I've found a workaround! Dropping the BPP of the depth buffer from 32 to 16 makes the application behave as expected.

**Comment by winterhell** [comment]
16 bit is very poor precision, at least with the default behaviour. 
If you have the near plane at 1 meter, the far plane at 800 meters, an object that is 600 meters away can be occluded by objects that are 5.2 meters behind him!
Can you try with 24bit? That precision was common in the past as well.

**Comment by Nihlus** [comment]
24 seems to work as well.

**Comment by Nihlus** [comment]
No, nevermind. It's still an issue on my NVIDIA rig. Dropping to 24 bits worked on my Intel laptop, but neither 16 nor 24 works on the NVIDIA machine.

**Comment by varon** [comment]
Can we mark this as resolved? Did we come up with a solution?

**Comment by winterhell** [comment]
It should work properly if rendering to a Framebuffer with a depth attachment.
Modern OpenGL applications that do post processing and HDR rendering would do it anyway. 
It seems the backbuffer depth precision varies with driver implementation, and you can only choose between 16 and 24 bits there, while with a Framebuffer you have more options.
In that light I dont think its a problem, just render to a framebuffer.

**Comment by Nihlus** [comment]
This issue is not yet resolved, unfortunately. There is no workaround.

It only happens on NVIDIA hardware (and for all buffer size values, not any particular ones), however, so I'm currently talking to NVIDIA support and getting a bug report registered. It should be noted, though, that programs which do not use OpenTK function as expected, so it's in all likelihood a problem in both softwares. 

On top of that, programs which use OpenTK on any driver version 378.13 or higher never makes it past any MakeCurrent calls, and simply hang there.

**Comment by varon** [comment]
Closing for now. If we encouter some way of fixing this, we can re-open a new issue.

Thanks for the feedback guys. Good luck, @Nihlus !

**Comment by ahuillet** [comment]
Two issues are being reported here. The depth issue isn't a NVIDIA bug and has to do with OpenTK (or the test application) not choosing its visual ID correctly, as has been discussed privately with Nihlus.
The other issue is a deadlock at startup under certain conditions that may or may not be a NVIDIA bug, but can't at this point be described as not an OpenTK bug.
