### ISSUE TITLE
Binary Shaders

### ISSUE THREAD

**Issue by zameran** [opentk/opentk#466]
### Description

So. I wanna precompile my shaders and use it later, but i can't, cuz of OpenTK does not implements some functionality.

OpenTK.Graphics.OpenGL.BinaryFormat is empty enum.
OpenTK.Graphics.OpenGL4.BinaryFormat is empty enum.
OpenTK.Graphics.OpenGL.ArbGetProgramBnary is not used directly enum.
OpenTK.Graphics.OpenGL4.ArbGetProgramBnary is not used directly enum.

Can't get compiled shader binary length. [Maybe i don't know how]

### Repro steps

1. Try save shader in binary representation.
2. Try load binary representation of shader.

### Expected behavior

All should work fine. I guess.

### Actual behavior

Shader/Program binary save/load doesn't work.

### Related information 

* Operating system: Ubuntu 16.10
* SDL or Native backend: Native 
* What version of OpenTK (Installer, NuGet, Source Code): 2.0 [NuGet]
* What runtime (.NET Framework, CoreCLR, Mono): Mono
* Workarounds (if any): Implement described stuff, or check Binder.

**Comment by winterhell** [comment]
Oh? I forgot you could cache binary shaders.
I just tried 
```
            byte[] binaryShader = new byte[256*1024];
            int binaryShaderLength;
            BinaryFormat binaryFormat;
            GL.GetProgramBinary(vertexColorShader.program, binaryShader.Length, out binaryShaderLength,                           out binaryFormat, binaryShader);
```
The shaderLength was just short of 8KB. If the length you provide in the second parameter is lower than what it needs, it throws an error, but then I think you can read the out value it gives you and try again.

**Comment by zameran** [comment]
Oh...
@winterhell, let me test it out...

Of pretty simple shader i've get this: [http://pastebin.com/DvZHFQW0](url)
Is it normal?
Looks like calling **GL.ProgramBinary** with this binary is good and without errors.
Can you provide more info about that?

**Comment by winterhell** [comment]
This looks like the shader assembly. 
I'm reading the documentation from here
https://www.opengl.org/registry/specs/ARB/get_program_binary.txt

To use the shader it seems you do 
vertexColorShader.program = GL.CreateProgram();
GL.ProgramBinary(vertexColorShader.program, binaryFormat, binaryShader, binaryShaderLength);
where the variables are the ones from the above example.
When you already have the binary in byte [] shaderBinary, you probably don't need to call GL.ShaderSource /  CompileSource / AttachShader /LinkProgram/ GetShader / GetProgram.
Remember, you need to compile the shader from the source text at least the first time you run it on a certain configuration. If you change the hardware, the shader binaries wont work anymore and you'll have to recompile them.

**Comment by zameran** [comment]
@winterhell, yeah, i know, that shaders should be compiled once per GPU-OpenGLVersion.
Thanks for your reply!

**Comment by winterhell** [comment]
Let me know if it works, I havent tried it myself.
Btw have you timed your shaders compilation time? I imagine it takes noticeable amount for you to want to have them cached.

**Comment by zameran** [comment]
@winterhell so i will post some metric later, if you want.
BTW looks like ~x10 speed-up on 10-100 shaders, and ~x2.5-6.8 on 200-600 shaders.
Another info will be posted later. Be in touch.

Cheers!

**Comment by winterhell** [comment]
Yeah I'm curious if its worth it.

**Comment by zameran** [comment]
It's worth it. Trust me.
Yeah, no reason to make binary save/load, if you only have < 100 shaders. I think.

**Comment by varon** [comment]
W-why on earth would you need 100+ shaders?

Can't you just compile them upfront once off?

**Comment by zameran** [comment]
@varon Cuz i wanna render and calculate the whole universe...
