### ISSUE TITLE
VSync Spikes / Stuttering

### ISSUE THREAD

**Issue by ilexp** [opentk/opentk#467]
### Description

I'm using OpenTK on the backend side of the Duality game engine and recently noticed "stuttering" when rendering frames with VSync on. With a constant rendered scene, there are irregular but persistent spikes in frame time measured in SwapBuffers which jumps up from 16ms to about 33ms and causes a visible stutter. 

However, without VSync, frame times stay below 10ms and don't come close to exceeding the 16ms mark (which would be expected to cause a 33ms spike), and some tests indicate differences between using the SDL2 backend vs. just OpenTK.

### Repro steps

_Edit2:_ I've [created a GitHub repo with a simple testing application](https://github.com/ilexp/OpenTKVSyncDebug) that reproduces this behavior on my machine. You can check it out directly or download the [pre-built binaries of the sample](https://github.com/ilexp/OpenTKVSyncDebug/raw/master/Build.zip). The sample was created using the latest (2017-03-23) commit from the develop branch of OpenTK and it reproduces the problem on my machine immediately. [This](https://gfycat.com/HighWaterloggedAntipodesgreenparakeet) is how it looks like.

1. Can someone else verify this behavior on another machine? The more the better.
2. Can someone take a brief look at the [sample code](https://github.com/ilexp/OpenTKVSyncDebug/tree/master/OpenTKSandbox) to verify that the problem is not due to errors on my side?

> While I'm using a [non-head branch of OpenTK](https://github.com/AdamsLair/opentk/tree/duality-master), I looked through the history of changes since branching off and it doesn't appear that anything related to this was modified since. I also reproduced the behavior in the OpenTK "GameWindow States" sample as well:
> 
> 1. Download the latest OpenTK repo state that still contains the sample projects. As far as I can see, [this](https://github.com/opentk/opentk/tree/f81b846a03d86d14f9036b322d60aedd8f9342ee) shouldn't be too bad.
> 2. [Adjust the OpenTK GameWindow States sample](https://github.com/opentk/opentk/blob/f81b846a03d86d14f9036b322d60aedd8f9342ee/Source/Examples/OpenTK/Test/GameWindowStates.cs) to [use `Run()` instead of `Run(30)`](https://github.com/opentk/opentk/blob/f81b846a03d86d14f9036b322d60aedd8f9342ee/Source/Examples/OpenTK/Test/GameWindowStates.cs#L727) so we get the maximum update rate.
> 3. Run the sample with VSync on.
> 4. Switch to fullscreen mode (number key 3) and observe the moving rectangle at the bottom.
> 
> You will notice that its movement is only smooth 95% of the time, while the other 5% there is a visible "stuttering" effect - assuming that the issue is not hardware / driver / OS dependent and does occur on your system too.
> 
> _Edit:_ Added a Duality-based repro sample [here](https://github.com/opentk/opentk/issues/467#issuecomment-268839922) and an OpenTK-only repro sample [below](https://github.com/opentk/opentk/issues/467#issuecomment-268865187).

### Analysis

- Disabling VSync fixes the problem, but choosing tearing over stuttering is not really great and, for some games, unacceptable.
- Using `VSyncMode.Adaptive` instead of `VSyncMode.On` does not fix the problem.
- **Using the SDL2 backend appears to fix the problem (?)** However, it appears to lack some features, like backbuffer MSAA or GLControl support, so this is not viable as a workaround right now. _Edit:_ It's unclear whether it fixes the problem or just improves it. This may or may not be a wrong lead.
- Enabling triple buffering in the NVidia control panel does not fix the issue. Forcing adaptive VSync globally does not either.
- Setting the rendering process to "high priority" in the task manager did not have an effect.
- The stuttering gets worse when focusing a different application on the second screen.

Frame times with OpenTK:
![without_sdl2](https://cloud.githubusercontent.com/assets/14859411/21431126/66d87d2c-c866-11e6-9d38-1c370daf5b1f.png)

Frame times with SDL2 backend dropped in:
![with_sdl2](https://cloud.githubusercontent.com/assets/14859411/21431040/006686d8-c866-11e6-88b2-4ce9887654fe.png)

### Related information 

* Windows 10, 64 Bit
* .Net Framework 4.5+
* Geforce GT 730, driver version 376.33
* Default settings in NVidia control panel.
* I have multiple screens, both at 60 Hz. The tests have all been run on the primary screen.

**Comment by ilexp** [comment]
This sample project demonstrates the issue: You should see an occasional spike in the movement of the test image when it "jumps" while otherwise moving smoothly:

[VSyncTest.zip](https://github.com/opentk/opentk/files/669266/VSyncTest.zip)

You can press F2 to F4 to toggle some performance views, though I recommend to keep them closed to rule out any interference by their updates. In any case, **adding `SDL2.dll` to the directory next to `DualityLauncher.exe` fixes the issue**.

The above is not intended for actual debugging, but to illustrate the issue. A similar sample could be set up using raw OpenTK.

**Comment by winterhell** [comment]
GeForce 650 here.
If I turn Vsync On, there are no frame dropping, everything is about 16.7 -16.8 ms.
If I turn Vsync Off, frametimes are 2.8ms.

If you turn Vsync off, what frametimes are you getting? Are some frames still overflowing the 16.(6)ms barrier? You should know that the GPU and CPU are not synced, so the GPU might be rendering the past frame while the CPU is sending commands on the new frame.
After you check the frametimes, you can add GL.Flush() and GL.Finish() before the SwapBuffer() and only then you can time your frames properly. 
I was working on a 2D game that has fixed frame times, so going over 60fps is a no-no, and this was the only approact viable to ensure no stuttering( without vsync).
If the client has forced vsync off in the drivers, or is on AMD Radeon, then you wont have any VSync at all.

**Comment by ilexp** [comment]
> After you check the frametimes, you can add GL.Flush() and GL.Finish() before the SwapBuffer() and only then you can time your frames properly.

As far as I know, SwapBuffers [already implies a flush / finish](http://stackoverflow.com/a/2143752/2015377). When measuring frame times, these measurements include the time SwapBuffers blocks, the measurements so far should also include all rendering times.

> If you turn Vsync off, what frametimes are you getting?

Without VSync, I'm at about 2ms per frame, but I still see spikes. Both frame update and drawcall submission are pretty constant and sum up to the about 2ms of frame time, but the SwapBuffers call itself, isolated with its very own measurement, occasionally spikes up to > 10 ms.

You've seen the sample above, it's just a moving textured quad. There's nothing happening that should suddenly increase rendering complexity so that executing commands on the GPU and blocking until they're done should take anything next to 10ms all of the sudden when it ran with 2ms before.

So at this point, I'm honestly a bit confused.

**Comment by winterhell** [comment]
With Vsync if you get over 16.6 ms yes it'll snap to 33.3 ms, but if it was without vsync, 17ms simply means you get 58-59fps which you wont notice vs 60fps.
GL.Flush and Finish force the CPU to wait for the GPU, i.e. syncs up.

**Comment by ilexp** [comment]
> With Vsync if you get over 16.6 ms yes it'll snap to 33.3 ms, but if it was without vsync, 17ms simply means you get 58-59fps which you wont notice vs 60fps.

Yes, but that's not really telling us anything. As far as I can see, the time spent updating and submitting drawcalls sums up to about 2ms, which equals frame time without VSync. This means that _with_ VSync, **it should snap to about 16ms every single frame**. Why should it ever snap to 33m when it only uses 2ms per frame in total without VSync?

I currently have various theories about what's going on:

1. There is a problem in my code that is causing the application to stall for a significant time at irregular intervals.
2. There is something going on behind the scenes (OS window management, drivers, etc) that causes these spikes.
3. Garbage Collection

For now, I would rule out item (3) because I track collection counts in profiling, and so far I wasn't able to spot any correlation between those counters increasing and the occurrence of a spike. I suspect that either (1) or (2) are causing this, but since I can observe the problem in OpenTK only samples, theory (2) might be worth investigating as well.

**Comment by ilexp** [comment]
Here is an OpenTK only sample project using the latest source code from the `develop` branch that reproduces this on my machine:

[JitterSample.zip](https://github.com/opentk/opentk/files/669568/JitterSample.zip)

The moving rectangle turns red whenever a spike occurs to make the effect easier to spot visually.

**Comment by winterhell** [comment]
Did you try it with Flush and Finish?

**Comment by ilexp** [comment]
> Did you try it with Flush and Finish?

Can you clarify what I should try? I'm not sure I know what you mean.

**Comment by winterhell** [comment]
Just put them before SwapBuffer()

**Comment by ilexp** [comment]
Tried that with a local copy of the OpenTK-only repro sample linked above, the problem persists.

**Comment by ilexp** [comment]
I investigated this a bit more. For reference, I was heavily relying on [this article](http://make-aitee-work.blogspot.de/2014/02/diagnose-frame-skips-and-stutter-in.html) and the Windows SDK tool [GPUView](http://graphics.stanford.edu/~mdfisher/GPUView.html), which is part of the [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk). I first recorded an ETL event trace of [VSyncTest](https://github.com/opentk/opentk/files/669266/VSyncTest.zip) using the Windows Performance Recorder from the SDK and then opened the trace with GPUView.

### OpenTK Without SDL2 Backend

In the first test using only OpenTK without its SDL2 backend, the VSync spikes described in the initial posting were recorded. Zooming in on one of those spikes / stutters a bit, you can sort of see that something is wrong:

![gpuview1](https://cloud.githubusercontent.com/assets/14859411/21462544/a6b50f12-c95d-11e6-80e0-6dc262169a9d.PNG)

In the above image, the green and the blue line are VSync interrupts of each of my two monitors. I was running the application in a borderless fullscreen window on my primary screen which, according to the graph, is probably the green line. 

Each of those blocks represent work units of either threads or GPU commands, and the general way these things seem to work on Windows is that an application submits GPU commands via graphics API (DirectX / OpenGL), which are stored in the process context and moved to the GPU hardware queue by the operating system.

Now as you can see in the image, after each of the green VSync signals, the GPU immediately gets to work and processes commands that were previously scheduled in the process context, while the process itself schedules new GPU commands, which both summed up takes less than 5ms, after which the entire remaining time slice is spent waiting for the next VSync, denoted by the crossed-out block in the Flip Queue 1.

All of this is very regular, **except** in that one stutter frame where VSync does something weird: For some reason the primary monitor VSync signal is recorded at exactly the same time as the one from the secondary monitor, which somehow leads to a full frame drop. Afterwards, things are back to normal.

One thing that I noticed is the sudden absence of CPU Core 0 from the OS idle thread (meaning it suddenly started doing things) in the critical time frame, as well as the sudden return of CPU Core 3 to idle (meaning it is no longer doing stuff that it was doing before), and I suspect that there is a connection here. Note that CPU Core 3 is otherwise busy with rendering and waiting in SwapBuffers of the VSyncTest application, and it's sudden return to idle could be a symptom of some sort of synchronization issue that is happening in the background.

And this is where CPU Core 0 is going:

![gpuview2](https://cloud.githubusercontent.com/assets/14859411/21462752/ef68ac62-c95f-11e6-89e4-f503a9c167b1.PNG)

A thread from the system display driver process doing "something".

### OpenTK Using the SDL2 Backend

As the stuttering went away with using the SDL2 backend, I did a second trace for that and opened that in GPUView as well:

![gpuview3](https://cloud.githubusercontent.com/assets/14859411/21462780/4357c4b6-c960-11e6-9ca4-675af33b155a.PNG)

Even when fully zoomed out and scrubbing the latency chart (not displayed here), there is not a single spike in the entire runtime of the process, except at the very first or second frame. When zooming in (see above), you notice that processing looks very regular. I wasn't able to find any spot where the two VSync signals "change pace" or suddenly overlap or delay.

Another intersting thing is that the hardware queue only has about three items to process after VSync, unlike the 4-7 items in the OpenTK only version - even though this is the same application with the exact same rendering code. So something is definitely happening that works differently than in the stutter-free SDL2 backend.

At this point I must admit that I'm a bit stuck. Insights and ideas by more experienced people would be hugely appreciated.

**Comment by winterhell** [comment]
This might be Windows 10 related. 
Is it possible for you to try on 7 or on Linux? There are a lot of problems with Win 10, I have a guy that cant start my program on a dektop with GeForce Titan, but it works on his notebook, both Win 10...

**Comment by ilexp** [comment]
> Is it possible for you to try on 7 or on Linux?

Don't have a non-Win10 system to test this on. I have a laptop, but that has its own array of problems, which I don't want to mix with this issue here.

**Comment by tzachshabtay** [comment]
Interesting!
I'm not an expert, so just random thoughts that might or might not help:

1. Maybe it's related to having multiple monitors? Did you test when the secondary monitor is disconnected? Also seeing this: http://forums.libsdl.org/viewtopic.php?t=9926&sid=baa88e10cf39b278d76510368e245c77, according to that only one monitor will have vsync, so maybe opentk is doing vsync on the wrong monitor? Did you try running the game on the secondary monitor and seeing if there's a difference? Did you try switching the monitors? Is there a difference of the refresh rate of the monitors?

2. When running with the SDL backend, I would try calling SDL_GL_GetSwapInterval and see if it's 0, 1 or -1 (the three available configurations, see: https://wiki.libsdl.org/SDL_GL_GetSwapInterval). Then I would try setting it to the other 2 configurations and see if there's a difference.

3. Is there a difference between borderless vs full screen vs windowed?

**Comment by ilexp** [comment]
> Maybe it's related to having multiple monitors? Did you test when the secondary monitor is disconnected?

It's definitely related to multiple monitors, as the problem disappears when I unplug my second monitor completely, see my last edit at the bottom of the GPUView post.

> according to that only one monitor will have vsync, so maybe opentk is doing vsync on the wrong monitor?

What striked me as a bit weird initially is that in GPUView, the blue VSync signal is supposed to be VSync 1 and the green is VSync 2 - so I would expect my primary monitor's VSync to be blue. However, it's actually green and both variants (SDL / OpenTK) sync to the green signal. Maybe this hints at something being a non-default case that OpenTK might not account for, but SDL does?

> Did you try running the game on the secondary monitor and seeing if there's a difference?

No difference for OpenTK, but it seems to get distinctly worse with SDL2.

> Did you try switching the monitors?

I can't, since one uses VGA and one uses HDMI plus DVI adapter.

> Is there a difference in the refresh rate of the monitors?

They support different refresh rates (59 / 60 vs 60 / 75) and the SDL mode with index zero actually differs in refresh rate (60 vs 75), but the system configuration definitely assigns 60 Hertz to both. Checked in both the NVidia system config and the windows display settings.

> When running with the SDL backend, I would try calling SDL_GL_GetSwapInterval and see if it's 0, 1 or -1 (the three available configurations, see: https://wiki.libsdl.org/SDL_GL_GetSwapInterval).

Getting these results:

```
SDL.GL.GetSwapInterval = 1
SDL.GetCurrentDisplayMode(0) = 1920, 1080, 370546692, 60
SDL.GetCurrentDisplayMode(1) = 1280, 1024, 370546692, 60
```

Again, while the selected display modes match in refresh rates, the indices zero would have differed, so it definitely didn't just pick the first mode for each display.

> Is there a difference between borderless vs full screen vs windowed?

None that I can see. Doesn't seem to affect the problem.

----

I also checked `DisplayDevice.Default` in OpenTK and can verify that it's my primary monitor at 60 Hertz and that both available `DisplayDevice` instances report 60 Hertz. When checking `AvailableResolutions` on each, the one with index zero has the same refresh rate mismatch as reported by SDL, but since the main / current property is properly set to 60, I guess that shouldn't be a problem. In my own code, I never specify a display device to run on and let OpenTK select.

**Comment by ilexp** [comment]
Stack traces for that idle thread that suddenly starts doing things in the critical / frame drop time period:

![gpuview2](https://cloud.githubusercontent.com/assets/14859411/21462752/ef68ac62-c95f-11e6-89e4-f503a9c167b1.PNG)

I clicked on every time slice in GPUView, but will only quote a few representatives here, since without debug symbols on these files it's only a matter of different jump addresses, and that probably doesn't tell us much. Most of the ones below appear repeatedly with differing address offsets in the middle part without symbols.

The very first one is singled out, like an initial "signal" of sorts, after which the thread goes back idle, only to wake up almost immediately after:
```
Type: Unknown / Multiple (36), Time: 546893892 (54,689.3892ms), TaskId: 0, Version: 2
Context Switch
NewThreadID: 6264
OldThreadID: 0
NewThreadPriority: 12
OldThreadPriority: 0
PreviousCState: 2
NewThreadPriorityDecrement: 0
OldThreadWaitReason: 0 Executive
OldThreadWaitMode: 0
OldThreadState: 2
OldThreadIdealProcessor: 0
NewThreadWaitTime: 19
OldThreadRemainingQuantum: 394720400
0 0xFFFFF800019C6ADF ntoskrnl.exe!SwapContext+0x31F 
1 0xFFFFF800019C6506 ntoskrnl.exe!KiSwapContext+0x76 
2 0xFFFFF800018DCF5C ntoskrnl.exe!KiSwapThread+0x17C 
3 0xFFFFF800018DC9FF ntoskrnl.exe!KiCommitThreadWait+0x14F 
4 0xFFFFF8000190E557 ntoskrnl.exe!KeRemovePriQueue+0x1B7 
5 0xFFFFF8000190E150 ntoskrnl.exe!ExpWorkerThread+0x80 
6 0xFFFFF80001879729 ntoskrnl.exe!PspSystemThreadStartup+0x41 
7 0xFFFFF800019C6BB6 ntoskrnl.exe!KiStartSystemThread+0x16 
```

This is the first time slice sample from after wakeup:
```
Type: Unknown / Multiple (36), Time: 546894856 (54,689.4856ms), TaskId: 0, Version: 2
Context Switch
NewThreadID: 6264
OldThreadID: 0
NewThreadPriority: 13
OldThreadPriority: 0
PreviousCState: 2
NewThreadPriorityDecrement: 0
OldThreadWaitReason: 0 Executive
OldThreadWaitMode: 0
OldThreadState: 2
OldThreadIdealProcessor: 0
NewThreadWaitTime: 0
OldThreadRemainingQuantum: 394720180
0 0xFFFFF800019C6ADF ntoskrnl.exe!SwapContext+0x31F 
1 0xFFFFF800019C6506 ntoskrnl.exe!KiSwapContext+0x76 
2 0xFFFFF800018DCF5C ntoskrnl.exe!KiSwapThread+0x17C 
3 0xFFFFF800018DC9FF ntoskrnl.exe!KiCommitThreadWait+0x14F 
4 0xFFFFF800018DE7C7 ntoskrnl.exe!KeWaitForSingleObject+0x377 
5 0xFFFFF801D799CC43 nvlddmkm.sys+0x1ACC43
6 0xFFFFF801D79A23B1 nvlddmkm.sys+0x1B23B1
7 0xFFFFF801D79B150D nvlddmkm.sys+0x1C150D
8 0xFFFFF801D79B1306 nvlddmkm.sys+0x1C1306
9 0xFFFFF801D7981F31 nvlddmkm.sys+0x191F31
10 0xFFFFF801D78EBD4D nvlddmkm.sys+0xFBD4D
11 0xFFFFF801D78EBF42 nvlddmkm.sys+0xFBF42
12 0xFFFFF801D791A9C4 nvlddmkm.sys+0x12A9C4
13 0xFFFFF801D8104671 nvlddmkm.sys+0x914671
14 0xFFFFF801D8106918 nvlddmkm.sys+0x916918
15 0xFFFFF801D80FF330 nvlddmkm.sys+0x90F330
16 0xFFFFF801D80FFF8A nvlddmkm.sys+0x90FF8A
17 0xFFFFF801D80FE6CD nvlddmkm.sys+0x90E6CD
18 0xFFFFF801D80A3DC0 nvlddmkm.sys+0x8B3DC0
19 0xFFFFF801D808A3C9 nvlddmkm.sys+0x89A3C9
20 0xFFFFF800018CBD11 ntoskrnl.exe!IopProcessWorkItem+0x81 
21 0xFFFFF8000190E1B9 ntoskrnl.exe!ExpWorkerThread+0xE9 
22 0xFFFFF80001879729 ntoskrnl.exe!PspSystemThreadStartup+0x41 
23 0xFFFFF800019C6BB6 ntoskrnl.exe!KiStartSystemThread+0x16 
```

All the following ones are variants of the following:
```
Type: Unknown / Multiple (46), Time: 546902343 (54,690.2343ms), TaskId: 0, Version: 2
Process: System
IP: 0xFFFFF801D79C701C nvlddmkm.sys+0x1D701C
0 0xFFFFF801D79C701C nvlddmkm.sys+0x1D701C
```
```
Type: Unknown / Multiple (51), Time: 546932318 (54,693.2318ms), TaskId: 0, Version: 2
IP: 0xFFFFF80001C96840 ntoskrnl.exe!NtWaitForMultipleObjects 
```
```
Type: Unknown / Multiple (46), Time: 546912319 (54,691.2319ms), TaskId: 0, Version: 2
Process: System
IP: 0xFFFFF801D798DFA9 nvlddmkm.sys+0x19DFA9
0 0xFFFFF801D798DFA9 nvlddmkm.sys+0x19DFA9
1 0xFFFFF801D79C4167 nvlddmkm.sys+0x1D4167
```
```
Type: Unknown / Multiple (46), Time: 546922313 (54,692.2313ms), TaskId: 0, Version: 2
Process: System
IP: 0xFFFFF80001953867 ntoskrnl.exe!KzLowerIrql+0x7 
0 0xFFFFF80001953867 ntoskrnl.exe!KzLowerIrql+0x7 
1 0xFFFFF801D79C235E nvlddmkm.sys+0x1D235E
2 0xFFFFF801D79C6FFF nvlddmkm.sys+0x1D6FFF
3 0xFFFFF801D79C6CD7 nvlddmkm.sys+0x1D6CD7
4 0xFFFFF801D7A0F1F2 nvlddmkm.sys+0x21F1F2
5 0xFFFFF801D7A0F617 nvlddmkm.sys+0x21F617
6 0xFFFFF801D7A0EE08 nvlddmkm.sys+0x21EE08
7 0xFFFFF801D7B3A70D nvlddmkm.sys+0x34A70D
8 0xFFFFF801D7B3B5E0 nvlddmkm.sys+0x34B5E0
9 0xFFFFF801D7CF07CF nvlddmkm.sys+0x5007CF
10 0xFFFFF801D7CF0FEB nvlddmkm.sys+0x500FEB
11 0xFFFFF801D7CF0B95 nvlddmkm.sys+0x500B95
12 0xFFFFF801D7CEEC75 nvlddmkm.sys+0x4FEC75
13 0xFFFFF801D7D1B4E0 nvlddmkm.sys+0x52B4E0
14 0xFFFFF801D7D1BDB3 nvlddmkm.sys+0x52BDB3
15 0xFFFFF801D7D1B765 nvlddmkm.sys+0x52B765
16 0xFFFFF801D7CF61C4 nvlddmkm.sys+0x5061C4
17 0xFFFFF801D79B1910 nvlddmkm.sys+0x1C1910
18 0xFFFFF801D7D019FB nvlddmkm.sys+0x5119FB
19 0xFFFFF801D79B09D5 nvlddmkm.sys+0x1C09D5
20 0xFFFFF801D79B1531 nvlddmkm.sys+0x1C1531
21 0xFFFFF801D79B1306 nvlddmkm.sys+0x1C1306
22 0xFFFFF801D7981F31 nvlddmkm.sys+0x191F31
23 0xFFFFF801D78EBD4D nvlddmkm.sys+0xFBD4D
24 0xFFFFF801D78EBF42 nvlddmkm.sys+0xFBF42
25 0xFFFFF801D791A9C4 nvlddmkm.sys+0x12A9C4
26 0xFFFFF801D8104671 nvlddmkm.sys+0x914671
27 0xFFFFF801D8106918 nvlddmkm.sys+0x916918
28 0xFFFFF801D80FF330 nvlddmkm.sys+0x90F330
29 0xFFFFF801D80FFF8A nvlddmkm.sys+0x90FF8A
30 0xFFFFF801D80FE6CD nvlddmkm.sys+0x90E6CD
31 0xFFFFF801D80A3DC0 nvlddmkm.sys+0x8B3DC0
32 0xFFFFF801D808A3C9 nvlddmkm.sys+0x89A3C9
33 0xFFFFF800018CBD11 ntoskrnl.exe!IopProcessWorkItem+0x81 
34 0xFFFFF8000190E1B9 ntoskrnl.exe!ExpWorkerThread+0xE9 
35 0xFFFFF80001879729 ntoskrnl.exe!PspSystemThreadStartup+0x41 
36 0xFFFFF800019C6BB6 ntoskrnl.exe!KiStartSystemThread+0x16 
```

This one here seems to be related to event tracing itself, however it only occurred once and in only one of many spike tracks. Event tracing itself causing the stuttering issues can be ruled out, as it's reproducible with or without tracing enabled. I'd carefully classify this as an artifact:

```
Type: Unknown / Multiple (46), Time: 547012317 (54,701.2317ms), TaskId: 0, Version: 2
Process: System
IP: 0xFFFFF8000190D762 ntoskrnl.exe!RtlpLookupFunctionEntryForStackWalks+0xC2 
0 0xFFFFF8000190D762 ntoskrnl.exe!RtlpLookupFunctionEntryForStackWalks+0xC2 
1 0xFFFFF8000190BB5F ntoskrnl.exe!RtlpWalkFrameChain+0x2FF 
2 0xFFFFF8000190B673 ntoskrnl.exe!RtlWalkFrameChain+0x93 
3 0xFFFFF80001A976C6 ntoskrnl.exe!EtwpGetStackExtendedHeaderItem+0x4E 
4 0xFFFFF800019F81FB ntoskrnl.exe! ?? ::FNODOBFM::`string'+0x2766B 
5 0xFFFFF800019342BB ntoskrnl.exe!EtwWriteEx+0x15B 
6 0xFFFFF8000193414C ntoskrnl.exe!EtwWrite+0x2C 
7 0xFFFFF801D59B18F9 dxgkrnl.sys!Template_q+0x4D 
8 0xFFFFF801D59B895A dxgkrnl.sys!DpiFdoMessageInterruptRoutine+0x4A 
9 0xFFFFF800018CE5D6 ntoskrnl.exe!KiCallInterruptServiceRoutine+0x106 
10 0xFFFFF800019C298A ntoskrnl.exe!KiScanInterruptObjectList+0x13A 
11 0xFFFFF800019C2687 ntoskrnl.exe!KiChainedDispatch+0x37 
12 0xFFFFF80001953867 ntoskrnl.exe!KzLowerIrql+0x7 
13 0xFFFFF801D79A2BD8 nvlddmkm.sys+0x1B2BD8
14 0xFFFFF801D7A0F630 nvlddmkm.sys+0x21F630
15 0xFFFFF801D7A0EE08 nvlddmkm.sys+0x21EE08
16 0xFFFFF801D7B3A70D nvlddmkm.sys+0x34A70D
17 0xFFFFF801D7B3B5E0 nvlddmkm.sys+0x34B5E0
18 0xFFFFF801D7CF07CF nvlddmkm.sys+0x5007CF
19 0xFFFFF801D7CF0FEB nvlddmkm.sys+0x500FEB
20 0xFFFFF801D7CF0B95 nvlddmkm.sys+0x500B95
21 0xFFFFF801D7CEEC75 nvlddmkm.sys+0x4FEC75
22 0xFFFFF801D7D1B4E0 nvlddmkm.sys+0x52B4E0
23 0xFFFFF801D7D1BDB3 nvlddmkm.sys+0x52BDB3
24 0xFFFFF801D7D1B765 nvlddmkm.sys+0x52B765
25 0xFFFFF801D7CF61C4 nvlddmkm.sys+0x5061C4
26 0xFFFFF801D79B1910 nvlddmkm.sys+0x1C1910
27 0xFFFFF801D7D019FB nvlddmkm.sys+0x5119FB
28 0xFFFFF801D79B09D5 nvlddmkm.sys+0x1C09D5
29 0xFFFFF801D79B1531 nvlddmkm.sys+0x1C1531
30 0xFFFFF801D79B1306 nvlddmkm.sys+0x1C1306
31 0xFFFFF801D7981F31 nvlddmkm.sys+0x191F31
32 0xFFFFF801D78EBD4D nvlddmkm.sys+0xFBD4D
33 0xFFFFF801D78EBF42 nvlddmkm.sys+0xFBF42
34 0xFFFFF801D791A9C4 nvlddmkm.sys+0x12A9C4
35 0xFFFFF801D8104671 nvlddmkm.sys+0x914671
36 0xFFFFF801D8106918 nvlddmkm.sys+0x916918
37 0xFFFFF801D80FF330 nvlddmkm.sys+0x90F330
38 0xFFFFF801D80FFF8A nvlddmkm.sys+0x90FF8A
39 0xFFFFF801D80FE6CD nvlddmkm.sys+0x90E6CD
40 0xFFFFF801D80A3DC0 nvlddmkm.sys+0x8B3DC0
41 0xFFFFF801D808A3C9 nvlddmkm.sys+0x89A3C9
42 0xFFFFF800018CBD11 ntoskrnl.exe!IopProcessWorkItem+0x81 
43 0xFFFFF8000190E1B9 ntoskrnl.exe!ExpWorkerThread+0xE9 
44 0xFFFFF80001879729 ntoskrnl.exe!PspSystemThreadStartup+0x41 
45 0xFFFFF800019C6BB6 ntoskrnl.exe!KiStartSystemThread+0x16 
```

**Comment by Ollhax** [comment]
Only skimmed the text above, but one thing you can try that helped me when I was plagued by VSync spikes: Disable "Threaded optimization" in the NV control panel.

**Comment by ilexp** [comment]
> Disable "Threaded optimization" in the NV control panel.

Tried it, but that didn't help. Even if it did however, that would only be a workaround and not a fix - wouldn't be that great if we had to fight default driver settings for games to render smoothly on some systems.

Still experiencing this issue, did some more Google research. One thing that came up was a potential interference between the Windows DWM and OpenGL VSync. The GLFW library has actually introduced some code to work around this, see [this commit](https://github.com/glfw/glfw/commit/8309e0ecb09fe5cf670dff5df1e7ca71821c27bd#diff-75a196c530b729f7087f6aba24a9d81dR573). Since the problem disappears on my machine when using the SDL2 backend, it could be worth investigating whether they're doing something similar in there.

**Comment by ilexp** [comment]
I've [created a GitHub repo with a simple testing application](https://github.com/ilexp/OpenTKVSyncDebug) that reproduces this behavior on my machine. You can check it out directly or download the [pre-built binaries of the sample](https://github.com/ilexp/OpenTKVSyncDebug/raw/master/Build.zip). The sample was created using the latest (3 days ago) commit from the develop branch of OpenTK and it reproduces the problem on my machine immediately. [This](https://gfycat.com/HighWaterloggedAntipodesgreenparakeet) is how it looks like.

1. Can someone else verify this behavior on another machine?
2. Can someone take a brief look at the [sample code](https://github.com/ilexp/OpenTKVSyncDebug/tree/master/OpenTKSandbox) to verify that the problem is not due to errors on my side?

**Comment by varon** [comment]
@ilexp Thanks for the sample.

I ran the repo on my side. Absolutely no stuttering. White squares all the way.
driver version: 4.5.0 NVIDIA 376.53
renderer:GeForce GTX 670/PCIe/SSE2
vendor:NVIDIA Corporation
ShaderVersion:4.50 NVIDIA

**Comment by winterhell** [comment]
Windows 7 64-bit
GeForce GTX 650
driver version: 378.49

VSync ON, OFF, Adaptive
Threaded optimization : ON, OFF, Auto
Windows size: default, maximized

Its all right cos its all white(no problems whatsoever).
It only goes red for a half second when I start it or when i change the window size.

**Comment by Ollhax** [comment]
> Tried it, but that didn't help. Even if it did however, that would only be a workaround and not a fix - wouldn't be that great if we had to fight default driver settings for games to render smoothly on some systems.

Sorry to hear it didn't work, but if anyone else has trouble with it, it _should_ be possible to disable it programmatically. See: http://stackoverflow.com/questions/36959508/nvidia-graphics-driver-causing-noticeable-frame-stuttering/37632948#37632948

**Comment by varon** [comment]
@ilexp  - Any resolution? I'd like to get this wrapped up and closed if we have any approximation of a solution.

**Comment by ilexp** [comment]
Nope, no resolution. As I've run into a wall with the investigation and it doesn't seem to be widespread enough for others to join in, feel free to close this issue as part of the cleanup process. Maybe link to it when something similar comes up in a new one.

It may just be an artifact on my machine, caused by a very specific combination of factors. VSync is an eternal mystery.

**Comment by varon** [comment]
Thanks, @ilexp. Appreciate you checking back in promptly! Let us know if there's anything else we can help with!
