### ISSUE TITLE
Mouse wheel event firing twice

### ISSUE THREAD

**Issue by Raptor2277** [opentk/opentk#468]
### Description

Mouse wheel event firing twice.

### Repro steps

https://snag.gy/PSUABZ.jpg

### Expected behavior

Mouse wheel event firing once.

### Actual behavior

Mouse wheel event firing twice.

### Related information 

* Windows 10
* IDK
* 2.0 NuGet
* .NET 4.5

When the I call the OnMouseWheel function, the event only fires once.

**Comment by varon** [comment]
Did you come right here?
