### ISSUE TITLE
No CursorVisible or SetPosition function in NuGet OpenTK 2.0.0

### ISSUE THREAD

**Issue by jammln** [opentk/opentk#470]
### Description

I have been trying to set the position of the mouse to the center of the screen (for FPS camera view) and I couldn't find the OpenTK.Input.Mouse.SetPosition method or the CursorVisible property. I have reverted to the one in the github develop branch and that has fixed the issue although I am unsure if it is version 2.0.0.

### Repro steps

Please provide the steps required to reproduce the problem

1. Install NuGet package OpenTK 2.0.0
2. Use GameWindow to make a temporary game
3. Try to access CursorVisible property or OpenTK.Input.Mouse.SetPosition()

* Operating system: Windows 7 x64
* SDL or Native backend: Native backend (using GameWindow)
* What version of OpenTK (Installer, NuGet, Source Code) NuGet 2.0.0
* What runtime (.NET Framework, CoreCLR, Mono) .NET Framework
* Workarounds (if any) Compiling from the develop branch (unsure if this is the same version as the NuGet package.)

**Comment by varon** [comment]
It's definitely there -  can you try the pre-release package and see if that works for you?

https://www.nuget.org/packages/OpenTK/3.0.0-pre

**Comment by varon** [comment]
It's definitely in 3.0.0-pre. Closing.
