### ISSUE TITLE
Joysticks- No Access to LogicalMin / LogicalMax

### ISSUE THREAD

**Issue by leezer3** [opentk/opentk#480]
Another issue with the joystick driver, but I'm not sure how to solve this one best without asking you guys.

There appear to be two distinct HID joystick implementations returning different values for the logical min / max.

**Type 1:**
These return a range from 0 - 256 for each axis.
(PS3 pad via USB, Xbox 360 pad, Logik Strike Pro)

**Type 2:**
These return a range from -128 to 128.
(Speedlink Black Widow, Leo Bodnar board)

_Edited Note:_
I've just dug into the specs, and the min and max values appear to be entirely arbitrary, but these are the examples I've got on hand.....

We set the axis here:
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinRawJoystick.cs#L408
This is reasonable enough, just get the scaled range between the LogicalMin and LogicalMax.

The problem is that we don't expose the LogicalMin / LogicalMax to the user, and I've just tripped over this....
There are two distinct places I can think of to expose this:
The _JoystickCapabilities_ struct- https://github.com/opentk/opentk/blob/develop/src/OpenTK/Input/JoystickCapabilities.cs
I'd add a new Axis array exposing LogicalMin / LogicalMax here. 

The other place would be to rewrite the JoystickAxis enum as a class, so that we return the axis and it's minimum/ maximum when State.GetAxis() is called.
Don't like this, but I'm punting it out there....

@varon  @wcdeich4 
Thoughts? Can hack something together no trouble, but we need consensus on how to do this.
The other (nasty....) thought I've got would just be to add the LogicalMin to our axis value if below zero, but that's not clever at all.....

**Comment by leezer3** [comment]
OK, a quick implementation of this:
https://github.com/leezer3/opentk/commit/8902880d461ce96221afbd11b32142a230de17e3

Not entirely thrilled by the way it's been done, but I don't want to start re-writing the HID drivers if I can avoid it, as that's well out of my comfort zone.

Feedback/ thoughts?

**Comment by varon** [comment]
@leezer3 Is this closed by #481?

Need some input still?

**Comment by leezer3** [comment]
#481 fixes the bug, but it doesn't expose these values.

I'm in two minds as to whether this is necessary; 99% of people will never
need these, but it's situations like #481 and possibly calibration type
dialogs that might benefit from this.

I can run up a PR if we think this is a good idea, but we need consensus
before adding a feature :)

**Comment by varon** [comment]
Closing and agreeing with leezer3 here. If someone needs, it's pretty easy to compile a custom build with this on.
