### ISSUE TITLE
[Tracking Issue] Joystick Mapping Bugs

### ISSUE THREAD

**Issue by leezer3** [opentk/opentk#483]
Follow-on from this PR: https://github.com/opentk/opentk/pull/453

# Windows Native

1. ~~Xbox 360 Controller- D-Pad not recognized (Fixed by https://github.com/opentk/opentk/pull/484 )~~
2. ~~Thrustmaster T.Flight stick HOTAS-X not recognized (Reported at http://bveworldwide.unlimitedboard.com/t1351-joystick-control#15385 ) (Fixed by https://github.com/opentk/opentk/pull/565 )~~
3. ~~Thrustmaster T.Flight stick HOTAS-X hat not returning to center properly, sticks to left position. (Fixed by https://github.com/opentk/opentk/pull/568 )~~

# Linux Native

1. Logik Starfighter- Axis 3 is phantom, hat 2 is phantom. All axes work OK.
2.  ~~Hats & Xbox 360 D-Pad- sticks on last pressed direction. (Fixed by https://github.com/opentk/opentk/pull/485 )~~
3. RailDriver buttons don't work, but appear to be recognised. ( http://raildriver.com/ 44 buttons, 7 axis....)

# OS-X Native

1. Xbox 360 Controller- Not recognized.

# SDL-2

**Comment by varon** [comment]
Any progress on this from the PRs?

What do we need to fix this?

**Comment by leezer3** [comment]
I haven't got as far as digging into why the Logik has phantom axis, or why the Xbox controller is broken on Mac, but the other are now OK after the noted PRs

**Comment by varon** [comment]
@leezer3  - Any updates?

**Comment by leezer3** [comment]
Sorry, not really, this is where I am on the joystick issues I can reproduce/ have been reported to me:

The button increase for Joysticks under Windows has now been verified by one of my users with a physical stick with over 32 buttons, so that's good.
However, the path doesn't appear to be perfect under Linux, as whilst this gets the RailDriver cab controller detected (separate user) , it's buttons don't work.
I've added this to my list above, but I really need to get my hands on a physical something with excess numbers of buttons to test.

The Logik Starfighter issue would appear to be evdev's fault, as it's detecting these erroneously. I suppose I could probably blacklist these two axis based upon the reported ID values, but that's a horrid solution when evdev should be fixing it themselves. (I'm not going anywhere near kernel level drivers!)

Xbox controller on Mac:
I think this is a Mac issue, in that they simply don't seem to have implemented a first-party driver for it. Installing this would probably work, but needs testing:
https://github.com/360Controller/360Controller
On my list of things to look into at some stage.......

**Comment by varon** [comment]
Thanks for the update, @leezer3.

Appreciate the detail.

Is there anything actionable on OpenTK's side, or reckon I can close this for now?

**Comment by leezer3** [comment]
The Raildriver is almost certainly an issue with the Linux X11 driver, I'd guess a casting issue somewhere is probably causing garbage data to be output when it goes over the 32 buttons limit.
I need something physical to easily check this though....

Have come across this:
https://github.com/Vantskruv/wejoy
This seems to allow creation of a virtual stick with 53 buttons, which might work, but I haven't tried building it......


Other than that, it really depends on how you want to organize your bugs. These are all 'issues' & I personally prefer to keep open a root issue for known unfixed things in a single component, even when they aren't exactly my fault.
Easy enough to close and either open specific issues for 'our' bugs or otherwise though.

**Comment by varon** [comment]
Closing. Re-open if this is still affecting anyone.
