### ISSUE TITLE
opentk user manual link incorrect

### ISSUE THREAD

**Issue by ashumeow** [opentk/opentk#486]
### Description

Entered into https://github.com/opentk/opentk/wiki

### Expected behavior

Tried to access manual link http://www.opentk.com/doc

### Actual behavior

Link is broken. 

### Request

Kindly provide a correct link and So, I can access user manual for opentk

**Comment by winterhell** [comment]
https://web.archive.org/web/20160406041123/http://www.opentk.com/doc
There you go

**Comment by ashumeow** [comment]
Thank you ;)
