### ISSUE TITLE
gl_PointSize doesn't work

### ISSUE THREAD

**Issue by 8Observer8** [opentk/opentk#489]
Hello

I want to draw a point with custom size in C# OpenGL3.3 OpenTK like this: https://jsfiddle.net/8Observer8/cc72u1u5/

But I see the point with size 1 pixel

I [attached the project HelloPoint1](https://www.dropbox.com/s/65ojmmsaiepzr0r/OpenTKExamples_HelloPoint1.zip?dl=0). Everyone can run it in VS 2012 - VS 2015

```
using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using OpenTK;
using OpenTK.Graphics.OpenGL;
using Utils;

namespace HelloPoint1
{
    class MainWindow : GameWindow
    {
        string VSHADER_SOURCE = null;
        string FSHADER_SOURCE = null;

        bool canDraw = false;

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);

            // Load shaders from files
            ShaderLoader.LoadShader("./Shaders/vShader.glsl", out VSHADER_SOURCE);
            ShaderLoader.LoadShader("./Shaders/fShader.glsl", out FSHADER_SOURCE);
            if (VSHADER_SOURCE == null || FSHADER_SOURCE == null)
            {
                Console.WriteLine("Failed to load shaders from files");
                return;
            }

            // Specify the color for clearing
            GL.ClearColor(Color.Black);

            GL.Enable(EnableCap.ProgramPointSize);

            canDraw = true;
        }

        protected override void OnRenderFrame(FrameEventArgs e)
        {
            base.OnRenderFrame(e);

            if (!canDraw) return;

            GL.Clear(ClearBufferMask.ColorBufferBit);

            // Draw a point
            GL.DrawArrays(PrimitiveType.Points, 0, 1);

            GL.Flush();

            SwapBuffers();
        }
    }
}
```

**Comment by varon** [comment]
`GL.Enable(EnableCap.ProgramPointSize);` only allows for you to change the point size. You would have to specify it (up to the maximum permitted by your driver using `GL.PointSize(float)` (see [glPointSize](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPointSize.xhtml)).

This isn't a bug with OpenGL, but rather a usage error - I'd advise asking on Gitter if you want help while learning - it helps reduce issue clutter and also gets a very fast response time, generally speaking.
