### ISSUE TITLE
Reopening of bug 2506? GLControl inside a user control crashes during design time

### ISSUE THREAD

**Issue by epiuze** [opentk/opentk#49]
I would like to fill a request to reopen bug 2506:
http://www.opentk.com/node/2506

I've tried both compiling OpenTK 1.1-rc1 from sources and the current release (opentk-2014-01-15) to no avail. 

My code compiles and runs fine, but visual studio 2012 crashes when I enter design mode for a form into which I put a custom user control that contains a docked GLControl.

Copied from link above, the workflow looks like this: 

1. Create new WinForms project
2. Add new user control called UserControl1
3. Drop a GLControl on to the user control
4. Rebuild project
5. Drop UserControl1 on to main form
6. GLControl should crash

**Comment by wcdeich4** [comment]
Should this issue thread remain open?

**Comment by varon** [comment]
It's ancient. Can re-open if needed.
