### ISSUE TITLE
How should OpenTK.Android be used?

### ISSUE THREAD

**Issue by amerigo14** [opentk/opentk#494]
When trying to extend from AndroidGameView while referencing OpenTK.Android, the project fails to compile with the following error:

error: package opentk1_1.platform.android does not exist extends opentk_1_1.platform.android.AndroidGameView.

Changing the Register attribute to either opentk_1_0 or opentk compiles, but at run time the graphics context is never created.

This issue is found on Windows using Visual Studio and the latest OpenTK on the Develop branch.

**Comment by DhirenSarup** [comment]
I also received the same error.

**Comment by varon** [comment]
Any luck guys?

**Comment by DhirenSarup** [comment]
Mono Android in Visual Studio 2015/17 ships only with OpenTK versions 0.9.9 and 1.0.0. Hence, if a higher version of OpenTK is required, in my opinion the only solutions are that Microsoft should provide a higher version of OpenTK (such as 2.0) along with the Mono Android framework, or the developer must himself compile the Mono project and use the latest version of OpenTK (which may not be such an easy task).

**Comment by varon** [comment]
Thanks for the update, @DhirenSarup.

That's pretty odd though - OpenTK.Android should be a drop-in replacement for that DLL. I suspect it'll have a lot to do with linking settings, etc. We definitely shouldn't have to recompile mono Android.

I'm going to rename this issue to something more descriptive. Hopefully someone can chip in with an answer.
