### ISSUE TITLE
Where can I post my questions about OpenTK?

### ISSUE THREAD

**Issue by 8Observer8** [opentk/opentk#497]
Hello,

Is this a forum about OpenTK? If not where can I find them?

My question was closed: [Drawing points by mouse click.](https://github.com/opentk/opentk/issues/496)

I want to port the example from WebGL: [ch02/ClickedPoints](https://jsfiddle.net/8Observer8/xf4fnc0o/) This example draws points with size 10px by mouse click

But my code doesn't work. It doesn't redraw the point in a new position: [DrawPointsByClick_Problem.zip](https://dl.dropboxusercontent.com/s/pa9j0i4e56kfrim/DrawPointsByClick_Problem.zip)

Please, run it. Maybe is it a bug of OpenTK?

Where can I ask my questions? I cannot find forums about OpenTK.

**Comment by jpbruyere** [comment]
[here](http://stackoverflow.com/questions/tagged/opentk)

**Comment by 8Observer8** [comment]
jpbruyere, thank you very much!
