### ISSUE TITLE
OpenTK Optimus Enablement

### ISSUE THREAD

**Issue by 8Observer8** [opentk/opentk#498]
These examples show how to run your apps in high-end graphics card instead integrated card.

- [OpenTkOptimusEnablementDotNet2.rar](https://dl.dropboxusercontent.com/s/xv2n73v5qggyva1/OpenTkOptimusEnablementDotNet2.rar) 
- [OpenTkOptimusEnablementDotNet4.rar](https://dl.dropboxusercontent.com/s/mxuuuerfzc5kll3/OpenTkOptimusEnablementDotNet4.rar)

See the article: [Exporting data symbols in C# for NVIDIA Optimus](http://lucasmagder.com/blog/2014/05/exporting-data-symbols-in-c-for-nvidia-optimus/)

[Screenshot](https://dl.dropboxusercontent.com/s/fxo3nnhvxd8r5x2/OpenTkOptimusEnablementDotNet2.png)

**Comment by daerogami** [comment]
@8Observer8 What is this in reference to? I can't tell if this is a question, bug report or simply a statement.
If you are wanting to have this added as a reference on the website, open an issue here https://github.com/opentk/opentk.github.io

**Comment by 8Observer8** [comment]
@daerogami  No, it is not a question. It is a very useful issue.

**Comment by daerogami** [comment]
@8Observer8 This appears to be reference material. Issues are best for discussions on current development items and reporting bugs. It is not ideal for reference material as issues are eventually closed and generally more difficult to find than say a wiki entry. Please see my comment above about creating an issue for adding this to the website.

**Comment by wcdeich4** [comment]
@8Observer8 I looked at the code & the NvOptimusEnablementExporter is awesome, except "[DllImport("kernel32.dll", SetLastError = true)]" is Windows specific.  That is why @thefiddler setup OpenTK using Mono.Cecil.
