### ISSUE TITLE
Client mouse position without system drawing

### ISSUE THREAD

**Issue by Tygrak** [opentk/opentk#499]
I am trying to get the position of the mouse cursor on the GameWindow. Right now I just subtract the height of the border to get the real position but that wouldnt work on another system. Is it impossible to get the accurate client mouse position without system.drawing? There is a way to get the height and width of the window, but as far as I know not the height of the window including the border.
Is there some other way other then using System.Drawing.Point with GameWindow.PointToClient or System.Drawing.Rectangle with GameWindow.Bounds?

Thank you for your help. Also I am sorry if this is not the right place to ask similiar questions, I am not really sure where to ask.

**Comment by daerogami** [comment]
@Tygrak Point and Rectangle are fairly simple objects, you could roll your own.
Where `WIndow` is your `GameWindow` instantiation: `Window.X` and `Window.Y` should give you your window position; `Window.Width` and `Window.Height` should help you determine your bounds.

I haven't done any cross platform work with OpenTK, but I'm surprised you're using GameWindow without System.Drawing.

If `Window.X` and `Window.Y` are including your border you may want to look into loading symbols for your platform's Window Manager and de-referencing `Window.WindowInfo.Handle` to get that information. This shouldn't be necessary though.

gitter.im/opentk/opentk is a more responsive resource for questions like these. I'm closing this and we can continue this discussion there. Be sure to mention what platform you are on and provide a minimum working example ([MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example))
