### ISSUE TITLE
Vector math assignment to out parameters could be optimized

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#500]
I have been reviewing the vector math code of OpenTK and found many instances of the following pattern:

```c#
public static void Add(ref Vector3 a, ref Vector3 b, out Vector3 result)
{
    result = new Vector3(a.X + b.X, a.Y + b.Y, a.Z + b.Z);
}
```

The assignment of a new ```Vector3``` struct to the result ```out``` parameter performs an unecessary copy of the entire vector structure. Instead, this pattern should be preferred:

 ```c#
public static void Add(ref Vector3 a, ref Vector3 b, out Vector3 result)
{
    result.X = a.X + b.X;
    result.Y = a.Y + b.Y;
    result.Z = a.Z + b.Z;
}
```

In fact, this is already the pattern that is used to implement the instance versions of the methods, so there is no reason why the same code should not be reused directly in the static methods. This should result in a significant speedup of all the static math methods, since the extra copy is entirely avoided.

I wrote a small benchmark to validate that this is indeed the case:

```c#
using System;
using System.Diagnostics;

namespace TestTK
{
    struct Vector3
    {
        public float X;
        public float Y;
        public float Z;

        public Vector3(float x, float y, float z)
        {
            X = x;
            Y = y;
            Z = z;
        }

        public static Vector3 Add(Vector3 left, Vector3 right)
        {
            Vector3 result;
            result.X = left.X + right.X;
            result.Y = left.Y + right.Y;
            result.Z = left.Z + right.Z;
            return result;
        }

        public static void Add(ref Vector3 left, ref Vector3 right, out Vector3 result)
        {
            result.X = left.X + right.X;
            result.Y = left.Y + right.Y;
            result.Z = left.Z + right.Z;
        }

        public static void AddCopy(ref Vector3 left, ref Vector3 right, out Vector3 result)
        {
            result = new Vector3(left.X + right.X, left.Y + right.Y, left.Z + right.Z);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            // JIT all code (run once)
            var a = new Vector3(1, 1, 1);
            var b = new Vector3(2, 2, 2);
            Vector3.Add(a, b);
            Vector3 result;
            Vector3.Add(ref a, ref b, out result);
            Vector3.AddCopy(ref a, ref b, out result);

            float total = 0f;
            const int Iterations = 100000000;
            var sw = Stopwatch.StartNew();
            for (int i = 0; i < Iterations; i++)
            {
                var r = Vector3.Add(a, b);
                total += r.X;
            }
            sw.Stop();
            Console.WriteLine("Using return value: {0}", sw.ElapsedMilliseconds);

            sw = Stopwatch.StartNew();
            for (int i = 0; i < Iterations; i++)
            {
                Vector3 r;
                Vector3.AddCopy(ref a, ref b, out r);
                total += r.X;
            }
            Console.WriteLine("Using out parameter (copy): {0}", sw.ElapsedMilliseconds);

            sw = Stopwatch.StartNew();
            for (int i = 0; i < Iterations; i++)
            {
                Vector3 r;
                Vector3.Add(ref a, ref b, out r);
                total += r.X;
            }
            Console.WriteLine("Using out parameter (assign fields): {0}", sw.ElapsedMilliseconds);
        }
    }
}
```

The results on my machine running in Release mode outside of VS (to ensure all JIT optimizations are enabled) for this benchmark are:

|                      | Return value | Out parameter (Copy) | Out parameter (Assign fields) |
|---------------| -------------- | ------------------------ | ---------------------------------|
|       **x86**      |   330ms        |  150 ms                       |   30ms                                     |
|       **x64**   |   121ms        |  119 ms                       |   119ms                                     |

**Update:** While reading more about struct optimization and the JIT compiler in C#, I decided to rerun the benchmark in the 64-bit configuration, with surprising results (see above). Apparently under some conditions, the 64-bit JITter can actually inline away all of the copy overhead, even for the return value Add method.

Interestingly, we cannot get the big performance boost of direct field assignment in this case, most likely due to variable mis-alignment, as detailed in [this SO question](http://stackoverflow.com/questions/32114308/weird-performance-increase-in-simple-benchmark).

Nevertheless, it still seems beneficial to change the implementation to favor direct field assignment, since it might generate opportunities for JIT optimization and in general for consistency with most of the math code (I only found this copy assignment pattern to be used in a minority of the methods).

If there is no objection, I will prepare a PR with these optimizations applied to all Vector and Matrix objects.

**Comment by varon** [comment]
Thanks, @glopesdev. That's an amazingly good spot.

The only issue I can think of is that we don't have testing in place to verify there isn't a typo or error in the new code.

If it's not too much to ask, do you reckon you could possibly set up some tests beforehand, then do the code changes?

**Comment by glopesdev** [comment]
@varon I was thinking of doing this by using a regular expression find-and-replace, so I wouldn't actually have to type anything. Nevertheless, I agree it would be good to have basic vector math unit tests in place.

Since it would be a lot of repetitive code, I wonder if it makes sense to consider this in the context of issue #77 where @Frassle was proposing the use of T4 templates to generate more complete math classes (we can't have immutable structs though, as this would precisely kill the possibility to have optimized vector math operations such as this).

I wonder if there is any work already in place to extend the build system for this?

**Comment by varon** [comment]
I think, by and large, 95-99% of our users are going to be sticking to the 'standard' types using 32-bit precision. Getting those running fast should be our first goal, and will get us by far the majority of the benefit. Moving to T4 code-generation would be ideal, but I suspect it's a separate issue to optimizing the most common cases.

If you want to look at testing schemes, I'm strongly in favour of property-based testing for this.

For instance, we know, a-priori, that, given vectors A and B, and Vector C = A + B, then:
C.x = A.x + B.x
C.y = A.y + B.y
C.z = A.z + B.z

We can express rules and relations for all operations, which would give us strong guarantees about the correctness of our code. The suggested method to do this would be using [FsCheck](https://fscheck.github.io/FsCheck/QuickStart.html).

I'm willing to update the build process and testing system to support this, if you're willing to help with writing the actual properties to be tested.

**Comment by glopesdev** [comment]
@varon I didn't know about FsCheck, it sounds like a really interesting idea!

Alright, count me in for writing the properties. I'll do some reading on property-based testing to get myself up to speed.

Let me know how it would be best to coordinate. I'm thinking that I could start optimizing the code on my local branch and later merge any build system changes before writing the tests in preparation for the PR.

**Comment by winterhell** [comment]
So  Vector3 Add(Vector3 left, Vector3 right) is twice as slow as AddCopy() because it allocates memory for Vector3 result at the moment of declaration?
If this would increase the speed of Vector3.Dot and Vector3.Cross by a factor of 2 to 10 times would be amazing.

**Comment by glopesdev** [comment]
Interestingly, I found that the optimization benefits do not hold so clearly for this benchmark if it is compiled and run in a 64-bit architecture. I've updated the table above with the results.

As I mention in the updated issue, I still believe there are benefits to making the change as it has the biggest chances of providing opportunities for JIT optimization.

**Comment by winterhell** [comment]
The 64-bit version could be better optimized by the JIT because of larger number of registers and their size, so they can inline Vector functions that previously were a tad too big? This purely speculation on my part.
Edit: Oh, you wrote about that.
If so, would be interesting to know about the difference in Matrix performance. Maybe that would benefit 64-bit as well?

**Comment by varon** [comment]
As for matrices, it would be really great if we could stop them from allocating memory. `unsafe stackalloc` or something!

Beyond that, though: I'm in favour of writing correctly optimized code rather than relying on compiler wizardry. Especially at the library level.

In this case, it also happens to better express our intent, while also being generally less lines of code.

**Comment by varon** [comment]
@glopesdev @winterhell @daerogami 

I've submitted a PR which includes a framework for property based testing, along with examples for the Vector2 type. See #507 .

Ideally we'd like to express the older test that have been removed as properties on the new system. I'll spend a few more minutes adding these to it.

If we can all pile in and write these properties, it'll help out massively in getting our testing covering a lot more code.

**Comment by varon** [comment]
Thanks to @Nihlus  - we've merged in a PR with a massive amount of testing.

With this, we can be confident in performing the optimizations that we're not going to break anything. @winterhell @glopesdev

**Comment by Frassle** [comment]
#643 fixed a lot of these. I'm leaving this issue open to also take a chance to look into matrix optimizations as commented on by @varon above.

**Comment by varon** [comment]
I'm going to mark this as completed in the interest of expiditing 3.0.0.

We can revisit the matrix operations later on.
