### ISSUE TITLE
Quaternion internal fields should be exposed as public

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#501]
Two reasons mainly:
1. Consistency: all other OpenTK vector and math types already expose their internal backing fields publicly. Also XNA and most other managed math libraries for games also expose public backing fields.
2. Performance: exposing the fields of a struct as public allows passing these fields directly into ```ref``` or ```out``` parameters, even if the struct is part of an array.

This is critical for allowing users to implement their own optimized math methods on top of the ```Quaternion``` types, where you want to be able to assign fields directly to ```out``` variables.

**Comment by varon** [comment]
I see no problem with doing this.

**Comment by varon** [comment]
Added by #532
