### ISSUE TITLE
Missing file when compiling for android/iOS

### ISSUE THREAD

**Issue by UnknownShadow200** [opentk/opentk#502]
### Description

The android and ios .csproj files have this line:
```
<Compile Include="Input\JoystickButton.cs" />
```
However, this file does not exist.

### Repro steps

1. Attempt to compile either Android or iOS projects.

### Expected behavior

The projects compile.

### Actual behavior

Compilation error with "Source file 'Input\JoystickButton.cs' could not be found (CS2001)".

### Related information 

* Windows 7
* Backend irrelevant
* Latest source code from github
* Framework version irrelevant
* Workaround: removing the entry from both the .csproj files fixes compilation errors

**Comment by tzachshabtay** [comment]
That file was removed by @leezer3 as part of #453.
Other than fixing this compilation issue, I think the main takeaway should be that we need the CI build to compile Android&IOS as well, which would have rejected that PR.

**Comment by varon** [comment]
@tzachshabtay Good spot.

They were disabled in the CI environment, as we need to figure out how to one-step include xamarin to build them. Typically in my usual workflow I have a version installed on the build server in a shared capacity, and just utilize that, it's a bit more tricky with the publically available services, and needs some investigation.

I'm incredibly short on time at the moment - if anyone wants to give a bash at getting those running, I would be totally happy to help out from here or on gitter. It's a very simple task, just needs some basic problem solving.

**Comment by leezer3** [comment]
Agreed- The CI should definitely compile Android / IOS.

Unfortunately, we've just tripped over one of the prime problems of a multi-platform build: Not having comprehensive enough tests.....

I'll note that I was in favor of keeping that particular enum for backwards compatibility, but there we go :)

Do you want me to spin up a PR to fix this?

**Comment by tzachshabtay** [comment]
I have zero knowledge about how to use Paket, however I have a repo with CI for Android that I've setup with appveyor, which might or might not help: https://github.com/tzachshabtay/MonoAGS/blob/master/appveyor.yml

I had to add an environment variable for AppVeyor, I was using their instructions here:
https://www.appveyor.com/docs/lang/xamarin/
