### ISSUE TITLE
PlatformNotSupportedException when trying to debug the application with GLSL-Debugger.

### ISSUE THREAD

**Issue by mrAppleXZ** [opentk/opentk#509]
### Description

The PlatformNotSupportedException occurred when I tried to debug the application with GLSL-Debugger(glslDevil) on Linux.

### Repro steps

1. Open GLSL-Debugger

2. Select an .exe with GLSL-Debugger

3. Click "Start Program" (F5)

### Expected behavior

The application isn't crashing.

### Actual behavior

The application is crashing.

### Related information 

* Operating system: Linux
* SDL or Native backend: mesa 17.0.1, nvidia 378.13
* What version of OpenTK (Installer, NuGet, Source Code): Nuget (2.0.0)
* What runtime (.NET Framework, CoreCLR, Mono): Mono

**Comment by MikiraSora** [comment]
You can use a software named "renderdoc"

**Comment by varon** [comment]
Sadly we can't support every debugger under the sun.
If you come up with any ideas on how to get this working, let us know.
