### ISSUE TITLE
Intel HD 4000 Gpu + GLControl

### ISSUE THREAD

**Issue by eafreak** [opentk/opentk#511]
![image](https://cloud.githubusercontent.com/assets/12842322/24658259/830050b8-1949-11e7-915d-cc662453cfd5.png)

Using the GLControl with a Intel HD 4000 gpu creates random effect near the edges of an object. The random effects/distortion does not happen with GameWindow or when running the software with nVidia gpu.

Reading through an older (2014) post, I think it boils down to using GL.DrawElements

Drivers are up to date.
GLControl 1.1.2349.6199

Sample Code:

	GL.BindBuffer(BufferTarget.ArrayBuffer, VBO);
	GL.BufferData(BufferTarget.ArrayBuffer, (IntPtr)(Vertices.Count * Vertex.Size), Vertices.ToArray(), BufferUsageHint.StaticDraw);
	// Vertex Position
	att = ShaderProgram.Attributes["Position"];
	GL.EnableVertexAttribArray(att.Location);
	GL.VertexAttribPointer(att.Location, 3, VertexAttribPointerType.Float, false, Vertex.Size, Vertex.Offset(x => x.Position));
	// Vertex Color
	att = ShaderProgram.Attributes["Color"]; // TODO, replace with a Material Class for strongly typed code
	GL.EnableVertexAttribArray(att.Location);
	GL.VertexAttribPointer(att.Location, 4, VertexAttribPointerType.Float, false, Vertex.Size, Vertex.Offset(x => x.Color));
	GL.BindBuffer(BufferTarget.ElementArrayBuffer, EBO);
	GL.BufferData(BufferTarget.ElementArrayBuffer, (IntPtr)(Indices.Count * sizeof(int)), Indices.ToArray(), BufferUsageHint.StaticDraw);
	/////////
	Draw
	//////
	GL.BindBuffer(BufferTarget.ElementArrayBuffer, EBO);
	GL.DrawElements(BeginMode.Triangles, Indices.Count, DrawElementsType.UnsignedInt, 0);
	GL.DrawElements(BeginMode.Points, Indices.Count, DrawElementsType.UnsignedInt, 0);
	GL.BindBuffer(BufferTarget.ElementArrayBuffer, 0);

**Comment by winterhell** [comment]
You have a problem with the depth precision of the default backbuffer. 
Find where the glControl1(or whatever you've renamed it to) is initialized( Form.designer.cs?) and replace
`this.glControl1 = new OpenTK.GLControl();`
with
`this.glControl1 = new OpenTK.GLControl(new OpenTK.Graphics.GraphicsMode(OpenTK.Graphics.ColorFormat.Empty,24), 3, 3, OpenTK.Graphics.GraphicsContextFlags.ForwardCompatible);`
For a 24 bit depth buffer.
The alternative is to use a Framebuffer with a depth attachment, which can be 16, 24 or 32bit and then copy the colour buffer to the backbuffer.

**Comment by eafreak** [comment]
Hallo, thanks.

Adding "new OpenTK.Graphics.GraphicsMode(OpenTK.Graphics.ColorFormat.Empty, 24)" did fix the problem.

I am curios to learn about the FrameBuffer. Can you perhaps point me to some samples or reading?

**Comment by winterhell** [comment]
https://learnopengl.com/#!Advanced-OpenGL/Framebuffers
https://web-beta.archive.org/web/20140829083913/http://www.opentk.com/doc/graphics/frame-buffer-objects

**Comment by subchannel13** [comment]
What is default depth precision in GLControl 1.1.2349.6199? I'm using the control on Intel HD 3000 and never had such issue. Could the artifacts be fixed with other options like face culling and projection?

**Comment by winterhell** [comment]
Depends on the combination you have with your GPU and driver.
In the worse case its 16 bit or less.

**Comment by subchannel13** [comment]
That is true but what I'm get at that there might be a program issue which higher precision would only delay. 2^16 is about 65000 which should be big enough for displaying a cube given an appropriate projection. The largest cube edge is 115 pixels so 2^16 is already few orders of magnitude more then necessary.

@eafreak Do you call GL.DepthFunc anywhere? This looks like it might be the result of allowing equal depths (Lequal instead of Less).

**Comment by winterhell** [comment]
If there is Z-fighting, Less vs Lequal wont help the situation.
The Z-buffer is not linear, and there are reasons for that. Anyway, here are some numbers
16bit precision: If the near plane is 1 meter away, and the far plane is 100 meters away, at a distance of 85 meters, the error is 0.1 meters, or 10 centimeters. That is more than 1/1000th of the whole depth range. Imagine you are seeing a human 85 meters away from you, and a part of him is 10centimeters off in a certain direction.
With a 24-bit buffer the error is not 0.1 but whopping 0.0003, or 3/10 of a millimeter.

**Comment by daerogami** [comment]
Closing: Reason question appears to be resolved.
