### ISSUE TITLE
Resolved - GLControl crach no exception - PhongShader

### ISSUE THREAD

**Issue by eafreak** [opentk/opentk#515]
Hallo

I am using the shader from https://learnopengl.com/#!Lighting/Multiple-lights and it works 100% in GLWindow, however, the GLControl simply crash without any exception. The only output log worth something is 

> The program '[18572] Test.OpenGL.Forms.exe' has exited with code -1073740940 (0xc0000374).

Eventually I found the program crashes at the GL.GetActiveUniform in the following code. Depending how fast I step with Visual studio, I get different amounts of uniforms. If I go fast, I get 5-12 uniforms and slower I get 39+.

I run this code in the GLControl's Load event.
``` C#
    private Dictionary<string, Parameters.Uniform> GetUniforms()
    {
        var items = new Dictionary<string, Parameters.Uniform>();
        int count = 0;
        GL.GetProgramInterface(ID, ProgramInterface.Uniform, ProgramInterfaceParameter.ActiveResources, out count);
        for (int i = 0; i < count; i++)
        {
            var uniform = new Parameters.Uniform();
            int len = 0; // can be ignoreed

            GL.GetActiveUniform(ID, i, 256, out len, out uniform.size, out uniform.type, uniform.name);
            uniform.location = GL.GetUniformLocation(ID, uniform.Name);

            items.Add(uniform.Name, uniform);
        }
        return items;
        }
```

GLControl 1.1.2349.6199

**Comment by UnknownShadow200** [comment]
What is the definition of Parameters.Uniform

**Comment by eafreak** [comment]
The Parameters.Uniform stores the uniform's info.
``` C#
StringBuilder name
ActiveUniformType type
int location
int size
```

**Comment by UnknownShadow200** [comment]
What capacity does name have when assigned in the constructor? 256 too?

**Comment by eafreak** [comment]
name = new StringBuilder()

I have tried changing the 256 to 512 but made no difference.

If the StringBuilder is the culprit, why does it work fine with GLWindow?

**Comment by UnknownShadow200** [comment]
Does trying new StringBuilder(256) instead help? 

Not sure why it would only work for GLWindow though.

**Comment by eafreak** [comment]
Sorry, only tried 512 with GL.GetActiveUniform.

I will test StringBuilder later when I am back at my pc. Thanks

**Comment by eafreak** [comment]
Digging through the opentk repository I found a better solution: 
''' C# 
string GetActiveUniform(int program, int uniformIndex, out int size, out ActiveUniformType type)
'''

It seems that StringBuilder's dynamic capacity does not work well here.
https://msdn.microsoft.com/en-us/library/system.text.stringbuilder.capacity(v=vs.110).aspx

**Comment by UnknownShadow200** [comment]
yeah it won't dynamically resize, under the hood, GetActiveUniform works like:
```CSharp
public unsafe static void GetActiveUniform(int programObj, int index, int maxLength, 
   out int length, out int size, out ArbShaderObjects type, [Out] StringBuilder name)
{
	IntPtr temp = Marshal.AllocHGlobal((IntPtr)name.Capacity);
	calli(programObj, index, maxLength, &length, &size, &type, temp, GL.EntryPoints[669]);
	BindingsBase.MarshalPtrToStringBuilder(temp, name);
	Marshal.FreeHGlobal(temp);
}

```
Probably would be better using maxLength instead of name.Capacity. 

Is your issue fixed now though?

**Comment by eafreak** [comment]
So far it seems good thanks, still testing though as the shader is only started with development.

The new line I am using get the max capacity first with GL.GetProgram(ID, GetProgramParameterName.ActiveUniformMaxLength, out MaxCapacity), but yea, using maxLength would have been better I think.
