### ISSUE TITLE
Intel.GetPerfQueryIdByName not handled properly?

### ISSUE THREAD

**Issue by UnknownShadow200** [opentk/opentk#519]
Reading the OpenGL extension description at https://www.khronos.org/registry/OpenGL/extensions/INTEL/INTEL_performance_query.txt, it seems this is a (if the only one?) case where the StringBuilder is treated as input to an OpenGL function instead of output.

The rewritten function treats the StringBuilder as output, however, I have not been able to test whether this causes any issues.

**Comment by varon** [comment]
There should be a few of these - specifically the shader programs, etc.

Let us know if you run into any issues.

**Comment by UnknownShadow200** [comment]
My GPU doesn't support this extension hence why I opened the issue

**Comment by varon** [comment]
Ah, sure - then let's leave it for now until someone runs into it. They'll possibly find this with a search function.
