### ISSUE TITLE
SDL2 Drag&Drop

### ISSUE THREAD

**Issue by VPeruS** [opentk/opentk#520]
SDL2 d&d handling is enabled by default, but not handled in framework, isn't it cause memory leak, as sdl return event with pointer to char that user responsible to delete by himself?

SDL window, Mono 4.6.1, Linux

**Comment by varon** [comment]
This isn't a feature we support at present. There shouldn't be a memory leak, as I believe you have to enable the event before SDL broadcasts it to you.

If you would like to add this functionality, we would welcome a PR.

Closing for now.
