### ISSUE TITLE
Does linux/Mac support DllImport?

### ISSUE THREAD

**Issue by bitzhuwei** [opentk/opentk#522]
### Does linux/Mac support DllImport?

I don't think so. But in OpenTK such code exists:
```
            [System.Runtime.InteropServices.DllImport(GL.Library, EntryPoint = "glAttachShader", ExactSpelling = true)]
            internal extern static void AttachShader(UInt32 program, UInt32 shader);
```
So, this is where I'm confused, can this work on linux/Mac?

**Comment by mellinoe** [comment]
Why wouldn't they support DllImport? They do.

**Comment by bitzhuwei** [comment]
So linux support "opengl32.dll"?

**Comment by mellinoe** [comment]
No, although that's a different question. Most OpenGL functions imported in OpenTK actually don't use DllImport, but rather custom function pointer loading. The DllImport's probably rely on [DllMap](http://www.mono-project.com/docs/advanced/pinvoke/dllmap/) to work on Mono.

**Comment by bitzhuwei** [comment]
Thank you!

**Comment by UnknownShadow200** [comment]
See https://github.com/opentk/opentk/blob/develop/src/OpenTK/OpenTK.dll.config

**Comment by varon** [comment]
Thanks for chipping in here @mellinoe, @UnknownShadow200! You guys are an enormous help.

Closing, because we've answered this.
