### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by swiftsword7** [opentk/opentk#525]
Hello!  Anybody know what this error means?  
"An unhandled exception of type 'OpenTK.Graphics.GraphicsContextException' occurred in OpenTK.dll Additional information: Failed to swap buffers for context 65537 current. Error: 6".  
I can't seem to find any documentation on what "context 65537 current" is or "Error: 6".  Thanks!

**Comment by UnknownShadow200** [comment]
Line of interest: https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinGLContext.cs#L263

65537 is the context ID and is not too important, but the 'error 6' is. Looking up the list of win32 errors at https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx
```
ERROR_INVALID_HANDLE
6 (0x6)
The handle is invalid.
```


As for why you are getting that error, can't pinpoint without some further context/details. A guess for why it might happen though:
a) you previously disposed of the window or OpenGL context

**Comment by swiftsword7** [comment]
@UnknownShadow200 Thanks!!!  I really appreciate it!

**Comment by MSDOSGuy** [comment]
> Line of interest: https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/Windows/WinGLContext.cs#L263
> 
> 65537 is the context ID and is not too important, but the 'error 6' is. Looking up the list of win32 errors at https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx
> ```
> ERROR_INVALID_HANDLE
> 6 (0x6)
> The handle is invalid.
> ```
> 
> 
> As for why you are getting that error, can't pinpoint without some further context/details. A guess for why it might happen though:
> a) you previously disposed of the window or OpenGL context
> 

Thanks, that fixed it!!
