### ISSUE TITLE
Incorect cast?

### ISSUE THREAD

**Issue by VPeruS** [opentk/opentk#534]
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/Cocoa/NSFloat.cs#L109

Why not double?

**Comment by varon** [comment]
No idea. Doubt anyone does except the person that wrote it.

If it's not working, let us know by re-opening this issue, but things generally seem to be okay there.

**Comment by UnknownShadow200** [comment]
@varon  I'm pretty sure it is a bug, if you try this test code:

```
NSFloat F = 102456.0;
double x = F; Console.WriteLine(x);
float y = F; Console.WriteLine(y);
```

On 32 bit mode x outputs 102456.0, but on 64 outputs 0.
On 32 bit mode y outputs 102456.0, and on 64 bit it outputs 102456.0.

---
Changing to * (double*) instead returns 102456.0 in the aforementioned case.

**Comment by varon** [comment]
Whelp, that's open again.

**Comment by varon** [comment]
Any observable negative effects of this change?

**Comment by UnknownShadow200** [comment]
There is one usage of it I can see from using ILSpy, around line 640 in CocoaNativeWindow
```
                    case NSEventType.LeftMouseDragged:
                    case NSEventType.RightMouseDragged:
                    case NSEventType.OtherMouseDragged:
                    case NSEventType.MouseMoved:
...
                                // See CocoaDrawingGuide under "Converting from Window to View Coordinates"
                                p = new Point(
                                    MathHelper.Clamp((int)Math.Round(rf.X), 0, Width),
                                    MathHelper.Clamp((int)Math.Round(Height - rf.Y), 0, Height));
```
rf.X uses implicit convert to double since Math.Round works with double

I don't have OSX myself so can't determine what effect it has.

**Comment by varon** [comment]
Mhrhmrhrm. I'll give this a test on a mac here when I can remember to do so.

**Comment by VPeruS** [comment]
On Mac you will receive incorrect mouse position and then line that UnknowShadow200 mention make it 0.
