### ISSUE TITLE
Run-Time Exception while trying to click with mouse on screen

### ISSUE THREAD

**Issue by Omar-Bsoul** [opentk/opentk#544]
### Description

I was trying to resize the window and click on drawing area multiple times, but it crush suddenly.

### Repro steps

Please provide the steps required to reproduce the problem

1. Resize the window.
2. Move the window.
3. Press on the corner of drawing area multiple times while moving the mouse a little bit with time.

### Expected behavior

Not Expecting any Crush

### Actual behavior

Crushed

### Related information 

* Windows 10 Pro N 64-bit OS
* version of OpenTK is 2.0.0
* .NET Framework 4.6.2

* Exception Details: 
Managed Debugging Assistant 'FatalExecutionEngineError'  occurred
  HResult=0x00000000
  Message=**Managed Debugging Assistant 'FatalExecutionEngineError' :** 'The runtime has encountered a fatal error. The address of the error was at 0xa4955a08, on thread 0x33b4. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.'

**Comment by varon** [comment]
Could you paste a minimal code example?

**Comment by Omar-Bsoul** [comment]
I have written a minimal code similar to what I have used, But didn't crushed.
And I was using GC.Collect(); method, I think it's the reason, because when I commented all of it's occurrences everything become well.

The Code:
using OpenTK;
using OpenTK.Graphics.OpenGL;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenGL
{
    public static class MainProgram
    {
        public static void Main(string[] args)
        {
            using (Window w = new Window())
            {
                w.VSync = VSyncMode.Off;
                w.Run();
            }
        }
    }

    public class Window : GameWindow
    {
        private int quadVao;
        private int quadVbo;

        private int shaderProgram;

        private static string vs =
            @"#version 330 core

            layout(location = 0) in vec3 position;
            layout(location = 1) in vec2 texCoords;

            out vec2 TexCoords;

            void main()
            {
                gl_Position = vec4(position, 1.0);
                TexCoords = texCoords;
            }
            ";

        private static string fs =
            @"#version 330 core

            in vec2 TexCoords;

            out vec4 color;

            void main()
            {
                color = vec4(TexCoords, 0.0, 1.0);
            }
            ";

        public Window() : base(1024, 640)
        {
            // Events
            Load += Window_Load;
            Unload += Window_Unload;
            MouseDown += Window_MouseDown;
            KeyDown += Window_KeyDown;
            RenderFrame += Window_RenderFrame;
        }

        private void Window_KeyDown(object sender, OpenTK.Input.KeyboardKeyEventArgs e)
        {
            if (e.Key == OpenTK.Input.Key.Escape)
                Exit();
        }

        private void Window_Unload(object sender, EventArgs e)
        {
            // Deallocate Memory
            GL.DeleteBuffer(quadVbo);
            GL.DeleteVertexArray(quadVao);
            GL.DeleteProgram(shaderProgram);
        }

        private void Window_Load(object sender, EventArgs e)
        {
            // Quad Data
            quadVao = GL.GenVertexArray();
            quadVbo = GL.GenBuffer();
            float[] quad_vertices = new float[] {
                -0.5f, -0.5f, +0.0f, 0.0f, 0.0f,
                +0.5f, -0.5f, +0.0f, 1.0f, 0.0f,
                +0.5f, +0.5f, +0.0f, 1.0f, 1.0f,

                -0.5f, -0.5f, +0.0f, 0.0f, 0.0f,
                +0.5f, +0.5f, +0.0f, 1.0f, 1.0f,
                -0.5f, +0.5f, +0.0f, 0.0f, 1.0f
            };

            GL.BindVertexArray(quadVao);

            GL.BindBuffer(BufferTarget.ArrayBuffer, quadVbo);
            GL.BufferData(BufferTarget.ArrayBuffer, sizeof(float) * quad_vertices.Length, quad_vertices, BufferUsageHint.StaticDraw);
            GL.VertexAttribPointer(0, 3, VertexAttribPointerType.Float, false, 5 * sizeof(float), 0);
            GL.EnableVertexAttribArray(0);
            GL.VertexAttribPointer(1, 2, VertexAttribPointerType.Float, false, 5 * sizeof(float), 3 * sizeof(float));
            GL.EnableVertexAttribArray(1);

            GL.BindBuffer(BufferTarget.ArrayBuffer, 0);
            GL.BindVertexArray(0);


            // Sahder
            int vert_shader = GL.CreateShader(ShaderType.VertexShader);
            GL.ShaderSource(vert_shader, vs);
            GL.CompileShader(vert_shader);

            int frag_shader = GL.CreateShader(ShaderType.FragmentShader);
            GL.ShaderSource(frag_shader, fs);
            GL.CompileShader(frag_shader);

            shaderProgram = GL.CreateProgram();
            GL.AttachShader(shaderProgram, vert_shader);
            GL.AttachShader(shaderProgram, frag_shader);
            GL.LinkProgram(shaderProgram);
            GL.DetachShader(shaderProgram, vert_shader);
            GL.DetachShader(shaderProgram, frag_shader);
            GL.DeleteShader(vert_shader);
            GL.DeleteShader(frag_shader);
        }

        private void Window_RenderFrame(object sender, FrameEventArgs e)
        {
            GL.ClearColor(Color.Gray);
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);

            GL.UseProgram(shaderProgram);

            GL.BindVertexArray(quadVao);
            GL.DrawArrays(PrimitiveType.Triangles, 0, 6);
            GL.BindVertexArray(0);

            GL.UseProgram(0);

            SwapBuffers();
        }

        private void Window_MouseDown(object sender, OpenTK.Input.MouseButtonEventArgs e)
        {
            byte[] pixel = new byte[3];
            GL.ReadPixels(e.X, Height - e.Y, 1, 1, PixelFormat.Rgb, PixelType.UnsignedByte, pixel);
            foreach (byte color in pixel)
                Console.Write(color + " ");

            Console.WriteLine();
        }
    }
}

**Comment by UnknownShadow200** [comment]
If you keep the GC.Collect but remove the GL.ReadPixels does it work?

**Comment by UnknownShadow200** [comment]
Also providing GPU manufacturer and model would be useful.

**Comment by Omar-Bsoul** [comment]
Yes it works.

Cpu: Intel i5 2450M 
Gpu: Intel HD graphics 3000

**Comment by Frassle** [comment]
Closing this as we don't have a repro case for it. Feel free to reopen with example code that reproduces the problem.
