### ISSUE TITLE
GLControl 3.0.0 doesn't automatically repaint

### ISSUE THREAD

**Issue by Omar-Bsoul** [opentk/opentk#546]
### Description

I was using OpenTK.GameWindow class to draw my scene.
Now, I want to use GLControl to draw my scene on it, but the Paint Event doesn't have been called more than once!!

I knew that because I'm calling a method to move around in the scene, but actually nothing happens!!
```
private void gLControl_Paint(object sender, PaintEventArgs e)
{
            GL.ClearColor(Color.Black);
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);

            // Move The Camera ...
            // Draw Stuff ...

            gLControl.SwapBuffers();
}
```

### Related information 

* Win 10 N 64-bit OS
* OpenTK 3.0.0 pre (NuGet)
* .NET Framework 4.6.2

**Comment by subchannel13** [comment]
In WindowsForms controls don't repaint themselves constantly, only when something "invalidates" visible area and same is true for GlControl paint event. For instance, you'd see paint working when resizing window. You have to roll you own repaint provoking mechanism.

If you don't need submilisecond precision then standard WinForms timer would work. To be honest I'm not 100% clear how to reliably tell a control to repaint itself but `gLControl.Invalidate();` works for me.

**Comment by Nihlus** [comment]
Closing as this has to do with how WinForms is structured.
