### ISSUE TITLE
Posible input desynchronisation?

### ISSUE THREAD

**Issue by VPeruS** [opentk/opentk#548]
OpenTK has two different Keyboard states which can be used at same time. Why window just doesn't use driver state? 
Code lines:
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/NativeWindowBase.cs#L58
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/X11/X11Keyboard.cs#L43

**Comment by Nihlus** [comment]
Test it and see if there is an actual issue. OpenTK is a very large and very old codebase, and general design & structure questions like these are difficult to answer. Still, I appreciate that you're bringing it to our attention.

Closing until an actual issue is shown.

**Comment by varon** [comment]
Well, the issue is that there's two ways of doing the same thing.

Ideally the NativeWindowBase should be refactored to use Keyboard.GetState() to avoid wierd issues.
