### ISSUE TITLE
Different behavior SDL for OpenTK.Input.Mouse.SetCursorPosition 

### ISSUE THREAD

**Issue by VPeruS** [opentk/opentk#550]
First issue:
When you try to set cursor position directly on all platform except SDL2 you didn't recieve mouse move event back.

Step to reproduce:
1) set handler for keyboard key that will move cursor
2) set handler for mouse move event to display coordinate where mouse moved
3) test on SDL and Window

Result:
1) Window: mouse move handler doesn't called
2) SDL2: will fire event every time you press key

Second issue:
When you call SetCursorPosition  SDL will set related to window not to global screen(Window, X11 set global coordinate)

**Comment by Nihlus** [comment]
Thanks for the report! I'll have a look at this along with some other mouse issues I recently hit.
Note for self and anyone who wants to lend a hand:

- Issue 1 may not be easily solvable. Not sure if we can generate mouse move events manually, but it's worth having a look at.
- Issue 2 is fairly simple to solve - in Platform/SDL2/Sdl2Mouse.cs:157, SDL.WarpMouseInWindow should be SDL.WarpMouseGlobal.

**Comment by VPeruS** [comment]
What about remove SDL2 event instead of injecting events?

**Comment by Nihlus** [comment]
@VPeruS SDL generates a mouse move event on its own according to its documentation, so it's not something that happens on the OpenTK side. I do agree that this behaviour should be documented :)

**Comment by VPeruS** [comment]
Anyway it need equal behavior for different platfroms.

**Comment by VPeruS** [comment]
Hmm, I think there is way to go, I didn't try it yet. Move mouse with warpMouseGlobal(), enable relative mode setRelativeMouseMode() it will flush mouse events.

**Comment by varon** [comment]
Fixed by 4.x
