### ISSUE TITLE
AccessViolationException when trying to use NativeWindow

### ISSUE THREAD

**Issue by braddabug** [opentk/opentk#552]
I'm trying to initialize OpenTK without using GameWindow, but I can't get it to work. As soon as I call any OpenGL methods after creating the NativeWindow and GraphicsContext I get an AccessViolationException.

Here's some code that demonstrates the problem:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace opentktest
{
    class Program
    {
        static void Main(string[] args)
        {
            //OpenTK.Toolkit.Init(); // makes no difference whether I call this or not
            OpenTK.Graphics.GraphicsMode mode = new OpenTK.Graphics.GraphicsMode(new OpenTK.Graphics.ColorFormat(32), 24, 0, 0);
            OpenTK.NativeWindow window = new OpenTK.NativeWindow(640, 480, "test", OpenTK.GameWindowFlags.Default, mode, OpenTK.DisplayDevice.Default);
            window.Visible = true;

            var ctx = new OpenTK.Graphics.GraphicsContext(mode, window.WindowInfo, 3, 0, OpenTK.Graphics.GraphicsContextFlags.Default);
            ctx.MakeCurrent(window.WindowInfo);

            OpenTK.Graphics.OpenGL.GL.GetError(); // exception here!
        }
    }
}
```

I can see the window pop up, and when I debug it looks like ctx contains a valid OpenGL context, so I don't know what else I need to do.

This is with Windows 7 and Visual Studio 2015.

**Comment by VPeruS** [comment]
(ctx as OpenTK.Graphics.IGraphicsContextInternal).LoadAll(); After ctx.MakeCurrent()

**Comment by UnknownShadow200** [comment]
By using NativeWindow, you're responsible for handling OpenGL context stuff yourself - including loading the pointers to all the OpenGL functions.

As such, you should either:
a) call ctx.LoadAll() after calling ctx.MakeCurrent();
b) use GameWindow instead, which handles this for you.

**Comment by Nihlus** [comment]
@braddabug What the previous comments have said is correct. Closing.
