### ISSUE TITLE
Enumerate supported GraphicsModes?

### ISSUE THREAD

**Issue by braddabug** [opentk/opentk#554]
Is there a way to enumerate all the supported GraphicsModes? Something like SDL_GetNumDisplayModes and SDL_GetDisplayMode in SDL2?

**Comment by Nihlus** [comment]
Avoid creating issues for support requests. Please ask on Gitter instead.

**Comment by braddabug** [comment]
For anyone searching who finds this, try OpenTK.DisplayDevice.Default.AvailableResolutions
