### ISSUE TITLE
[Tracking Issue] Cleanup and modernization of codebase

### ISSUE THREAD

**Issue by varon** [opentk/opentk#566]
As #559, #563, and #564 pretty much nuked every fork and outstanding branch from orbit, we might as well go the whole hog here for 3.0.0.

These suggestions are based on [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/index) and a bit extra from the [CoreFX guidelines](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)

#### Mark non-extensible types as sealed

Mark anything not explicitly designed as an extension point as sealed. A good heuristic for when something should be sealed is if none of its methods are abstract or virtual.

This can have positive effects on performance, as well as provide stronger constraints on how the library is intended to be used.

#### Add method contracts
Correctly annotate method contracts with [Pure] and [CanBeNull] attributes, (especially for the math operations). To do this, please perform a source inclusion of the annotations through ReSharper, rather than using the NuGet package as a dependency.

#### Fix non-public variable naming
  - fix all non-public variable naming, `snake_case` should go to `PascalCase` or `camelCase`.
  - prefix booleans with `is`, `can`, `has`, etc.
Generally follow the guidelines outlined

#### Fix public API naming
  - Fix incorrectly named properties and methods, but leave the old ones as aliases marked as obsolete to help the upgrade process.

If there are any other suggestions on things to tackle for the cleanup, it's probably worth discussing here.

@Nihlus @Frassle

**Comment by Nihlus** [comment]
Sounds like a plan! Sealing the classes might be better done as a part of the library split, since we're going to significantly alter the structure of the library there anyway, and it will be easier to track which parts of the library have been correctly sealed.

I've also written a draft of some extended contribution guidelines, which I think will help solidify and congrue our intents for the code and the project. While it hasn't been done yet, I think we should also summarize the code style rules we've adopted from both MSDN and CoreFX so that new contributors can have a quick and simple overview.

Finally, here's a list of quick and automated cleanup passes I have planned after #564, in no particular order.

* Use of nameof expressions wherever possible
* Use of expression-bodied members wherever possible
* Use of string interpolation instead of String.Format and in Debug.Print/Write/WriteLine calls wherever applicable
* Removal of redundant method calls (there's a lot of .ToString() which aren't needed)
* Enforcing of modifier order in type and method declarations
* Use of readonly for compatible fields
* Use of null propagation wherever possible
* Removal of redundant modifiers (such as sealed overrides in sealed classes)
* Removal of redundant qualifiers (such as System.
* Removal of redundant preprocessor statements (there's a number of cases where they are being used for control flow and even commenting). It is my hope that we'll eventually be able to remove all of them.

In addition, I'd like to enforce the one type per file rule. This would mostly affect the native interop portions, and would follow a similar pattern in all of them. Preferably, that change would be paired with namespace changes to better reflect the structure of these portions, so I believe it's best to do this as a part of the library split as well.

**Comment by Frassle** [comment]
> In addition, I'd like to enforce the one type per file rule. This would mostly affect the native interop portions, and would follow a similar pattern in all of them.

That could get very verbose for the interop libraries. The rest of your list looks good.

> If there are any other suggestions on things to tackle for the cleanup, it's probably worth discussing here.
One thing I'd like to see considered is the removal of generated files from the repo. I don't think there's any value in storing the spec files, the signature files and the generated binding files in the repo. They should just be generated fresh as part of the build process. Would also make it very clear when trying to do fixes if you can edit the file directly or if you have to change a generator.
Side effect of this is we'd be more likely to stay in sync with Khronos, when was the last time someone re-fetched all spec files and ran the binding process and committed?

I'm also in the process of looking at DisplayDevice for #231. It might be worth redesigning that quite heavily to show the difference between adaptors and monitors, and removing the OrigionalResoloution property (if people want to restore change and restore they're much better placed to save the CurrentResolution just before they change it).

**Comment by varon** [comment]
@nihlus I'm with @frassle here on the one-type per file. For internal stuff used only in one place and tiny classes, it results in a lot of context switching. A lot of this kind of thing really should be moved to inner types anyway.

Removing the generated files makes sense IFF we can add a test to prove the generation process is deterministic. We can trivially automate fetching the schemas from Khronos as part of the build process, which would ensure constant parity.

**Comment by varon** [comment]
Actually, before we go around in circles, the one-type-per-file thing doesn't really matter anyway. If the guidelines are prescriptive on this, we should just stick with what they say for simplicity.

**Comment by Nihlus** [comment]
@Frassle @varon The consensus across the C# ecosystem is pretty clear - one type per file. However, I do think we should make an exception for delegates in the interop libraries - if we did, we'd have one file per function in many cases. 

I do, however, firmly believe that structures and classes should have their own files, and nested types have a [section](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types) on MSDN which I agree with. Our structures and enumerations will be publicly exposed, and that makes nested types an avoid if at all possible. The same logic applies to multiple types in one file.

**Comment by Nihlus** [comment]
@Frassle I'm behind a redesign of DisplayDevice - monitors and adapters are very distinct devices in modern computing, and the underlying code should definitely reflect that.

**Comment by varon** [comment]
Okay, sure - then let's just stick with what is standard practice in C#. Frassle and I are probably both adapting from F# where modules are used as a means of organization.

**Comment by tzachshabtay** [comment]
> Removal of redundant method calls (there's a lot of .ToString() which aren't needed)

Regarding removing "ToString", need to be careful here: ToString might seem to be redundant but can help removing memory allocations, for example:

```
string a = $"Today is {DateTime.Now}"; 
string b = $"Today is {DateTime.Now.ToString()}";
```

Resharper will tell you that the "ToString" is redundant, but without it, DateTime, as a value type, will be boxed to object which will trigger an unnecessary memory allocation.

If you are using Resharper, then I recommend installing the [Heap Allocation Viewer](https://blog.jetbrains.com/dotnet/2014/06/06/heap-allocations-viewer-plugin/) plugin, which will show you the allocations as you write.

**Comment by Nihlus** [comment]
@tzachshabtay I'll keep that in mind when going over them :D

However, almost all of the string calls aren't happening in performance-critical or memory-critical sections - it's unlikely that they'll be called an inordinate number of times. In fact, almost all of them are part of debug logging or single-pass steps in the supporting tools. In these cases, I would argue that a more concise and readable source is more valuable than a slight optimization.

**Comment by Nihlus** [comment]
Here's another thing - thoughts on enforcing use of braces? I've seen missing brace bugs bite people in the arse more than once - [quite spectacularly](http://embeddedgurus.com/barr-code/2014/03/apples-gotofail-ssl-security-bug-was-easily-preventable/), in fact! 

The only argument against it would be that it will take up a bit more vertical space, but I think that's worth the improved robustness.

**Comment by wcdeich4** [comment]
I like using more braces to be sure the the compiler knows what you mean.  Personally I don't think it is really a bad thing if a file gets long, as long as all of the functions inside that object are a functionality that object should logically have.  My only concern would be, are we going to break any old code, like for example if someone wrote if (x) return y; all on one line?

**Comment by Frassle** [comment]
I favour always putting braces. I have been following the existing style of simple single lines not being braced but it always makes me worry 😟 In fact earlier I got bit by exactly this when I made a one line if into two lines and forgot to brace it!

**Comment by Nihlus** [comment]
@wcdeich4 ReSharper takes care of the old code quite nicely - it's been pretty battle tested and I trust it :)

**Comment by varon** [comment]
@Nihlus : @tzachshabtay is spot on here. Given its game focus, it's preferable if OpenTK can avoid allocations at all costs.

**Comment by Nihlus** [comment]
@varon Well, as I said, almost all of them are in debug clauses which aren't even executed in the release build, and the others belong to other ToString methods which are rarely called in a production environment. They're not used in "normal" game code.

Furthermore, if we really do care all that much about a slight increase in allocations for this code, it should be done everywhere, and not just here and there as it is now. The current calls are, at a glance, not done with intent, but rather as leftovers from someone coding on autopilot.

**Comment by varon** [comment]
@Nihlus That makes sense. It's definitely something we want to look at removing.

Some things like matrix transposition and/or inversion also allocate, which is deeply annoying.

**Comment by Nihlus** [comment]
@varon Related to #500, I'd say. Could look into that during the same pass.

**Comment by varon** [comment]
Perfect.

**Comment by UnknownShadow200** [comment]
There's a number of places (such as WinRawJoystick) where a ```ContainsKey``` is followed by an indexer access - could replace them with ```TryGetValue```.

**Comment by varon** [comment]
Closing as 4.0 should largely be doing this by now.
