### ISSUE TITLE
Input Bug: Wrong keydown events when fn + function keys (or special keys) are pressed on laptops

### ISSUE THREAD

**Issue by NinjaFighter** [opentk/opentk#579]
### Description

Wrong keydown events when fn+keys (or special keys like volume control) are pressed on laptops.
For example:
   On Alienware M17 notebook:
      -Fn+F4 (Increase Screen Brightness) gets keydown event for Key.Number5
      -Button for decrease volume (not a fn combination), gets Key.Quote
      -Button for increase volume (not a fn combination), gets Key.X
     -Fn + F9  gets Key.BackSlash
     -Fn + F12 gets Key.Escape
     -Etc (every fn + function key (or notebook special key) gives a wronk keydown event.)

Note: This is not a new issue, this happens on old versions too, and it happens on every laptop that I've tested in (3 in total).

### Related information 

* Operating system: Windows 7 (Home premium & Professional)
* SDL or Native backend: Native (?)
* What version of OpenTK (Installer, NuGet, Source Code): Last from source code (and previous ones)
* What runtime (.NET Framework, CoreCLR, Mono): .NET Framework

**Comment by tyronx** [comment]
Long known issue, nobodies fixing it ^_^
If want it resolved, you can use my fork: https://github.com/anegostudios/opentk

**Comment by VPeruS** [comment]
Why not pull request it to upstream?

**Comment by Nihlus** [comment]
@tyronx If you have a confirmed fix, please submit it as a pull request.

**Comment by tyronx** [comment]
I did, but nobody ever merged it: https://github.com/opentk/opentk/pull/409

**Comment by tyronx** [comment]
@Nihlus Ok, I'll keep it in the back of my head to make it somewhen

**Comment by varon** [comment]
Closed by 4.x
