### ISSUE TITLE
'Package Restore Failed' when installing OpenTK NuGet package

### ISSUE THREAD

**Issue by drok0920** [opentk/opentk#584]
Hello,
I have been trying to use OpenTK once again after taking a break from coding but when i create a new project and try to install OpenTK through NuGet i get an error stating 'Package restore failed'.  This seems to only happen when installing OpenTK and on any version of OpenTK.  Any ideas on why this is happening or how i can fix this would be greatly appreciated.

**Comment by daerogami** [comment]
@drok0920 What OS are you on and what IDE? If VS, what year?

There should also be additional error information for NuGet.

I have seen it recommended in the past to delete the *.suo file as that can be the cause of weird caching issues. (https://stackoverflow.com/questions/20859591/nuget-package-restore-failed-for-project-miscellaneous-files-value-cannot-be-nu)

**Comment by drok0920** [comment]
I am on windows ten using VS 2017 an as far as i am aware there is no additional info for the error.  I will try to delete the .suo file and see if that fixes it.

**Comment by drok0920** [comment]
@daerogami i could not find a .suo file to delete

**Comment by drok0920** [comment]
Ok i found the problem.  I did not have a recent enough .NET Framework selected or even installed!
