### ISSUE TITLE
Can't build Test.API.Desktop project

### ISSUE THREAD

**Issue by osvaldlaszlo** [opentk/opentk#587]
**Description**

Unfortunately I can't build the _Test.API.Desktop_ project.
Thx!

**Related information**

    Operating system: Windows 10 Enterprise
    SDL or Native backend: Native
    What version of OpenTK (Installer, NuGet, Source Code): Last from source code
    What runtime (.NET Framework, CoreCLR, Mono): .NET Framework

**Comment by Nihlus** [comment]
That particular project is currently unsupported and quite outdated. You can safely ignore it.

**Comment by varon** [comment]
@Nihlus - I was under the impression that that test was just 'see if it compiles properly' to check the bindings were generated as expected.

If it's not like that, then we should just remove it entirely?

**Comment by Nihlus** [comment]
@varon It's a bit like that, but it looks automatically generated as well, which doesn't help much if the generator has a problem. Furthermore, it's all in one humongous source file, so it can't be easily edited or changed to match the current code base. I would be for removing it (preferably by way of mothballing it somewhere in case we need to pull it back out).

**Comment by varon** [comment]
@Nihlus - it's already mothballed in the git history anyway. Might as well drop it.
The more code we can remove the better.

**Comment by osvaldlaszlo** [comment]
Thanks guys!!! :-)
