### ISSUE TITLE
Create OpenTK documentation 

### ISSUE THREAD

**Issue by talyian** [opentk/opentk#599]
### Description

There used to be docs at opentk.com/docs. There should be a new version of that on opentk.github.io. Useful features from the old docs:

1) Autogenerated HTML API reference
2) multiple-step Hello World tutorial  - something like https://learnopengl.com/ for OpenTK.
3) There used to be an examples project that covered a bunch of different OpenGL features
4) There were pages on common tasks or OpenTK libraries like using QuickFont for text rendering.

**Comment by wcdeich4** [comment]
Great idea!!!!!

**Comment by alexeymrkn** [comment]
You should at least consider fixing (or removing) links to documentation in your Readme.
In my opinion it is better to have old/outdated docs than nothing.

**Comment by Frassle** [comment]
1. Might be worth looking into [docfx](http://dotnet.github.io/docfx/) for the API reference documentation.
2. I think is probably better covered by a well documented examples project
3. I don't think we need the examples project as part of the opentk repo itself, but I'll talk to the team about getting an examples repo setup under the opentk github organization.
4. Again maybe better as examples, not sure.

**Comment by Secticide** [comment]
In terms of tutorials / examples it might be worth setting up a 'getting started' md file. With some examples of window setup / selecting OpenGL versions etc.

This could be easily linked via the readme to give people an easy to access place to go rather than googling their issues.

**Comment by realvictorprm** [comment]
@talyian It's worth to pickup the tutorial idea coupled with F#. If there's serious interest here then I would start it. I would just need a pointer to how it's preferred to be added.

According documentation, I agree on that it should be autogenerated.

**Comment by wcdeich4** [comment]
@realvictorprm Thank you for all your hard work.  A lot of people need to learn F# as well as OpenTK, plus people who already knew OpenTK need to know how it has changed.

**Comment by Frassle** [comment]
I actually started doing OpenTK examples with F# at https://github.com/Frassle/OpenTKExamples.

**Comment by realvictorprm** [comment]
Great @Frassle I didn't know that so many F#ers are around here :)

**Comment by sourceskyboxer** [comment]
I really need advanced of GameWindow if I switch fullscreen and windowed? 
Nothing find live documents :( I already searched  time.

If I use GameWIndow.flags or other method for GameWindowFlags? If I want.

Do you have ideas?`We need for game development if our game should swicth mode of full screen and windowed like any games have arguments "-windowed", "-sw" ( Half-Life, Steam-Windowed" )

If it happens I write Game () : base(.... GameWindowFlags.Fullscreen... )

How do I switch window mode like example my code:
```
using OpenTK;
using OpenTK.Graphics;
using OpenTK.Graphics.OpenGL4;
using BulletSharp;
using System;
using System.Drawing;
using System.Windows;

namespace Engine
{
    public class Client
    {
        private SDLWindow game;
        string jWidth = "";
        string jHeight = "";
        string jWindowed = "";
        string jGameDir = "";

        private Point CenterWindowOnScreen()
        {
            int screenWidth = (int)SystemParameters.PrimaryScreenWidth;
            int screenHeight = (int)SystemParameters.PrimaryScreenHeight;
            int gameWidth = game.Width;
            int gameHeight = game.Height;
            return new Point((screenWidth / 2) - (gameWidth / 2), (screenHeight / 2) - (gameHeight / 2));
        }

        public int Host(string[] args)
        {
            game = new SDLWindow();;
            for (int i = 0; i < args.Length; i++)
            {
                if (args[i] == "-width" || args[i] == "-w")
                {
                    jWidth = args[i + 1];
                    game.Width = int.Parse(jWidth);
                }

                if (args[i] == "-height" || args[i] == "-h")
                {
                    jHeight = args[i + 1];
                    game.Height = int.Parse(jHeight);
                }

                /**
                 *  -windowed or -sw or -nofs ( no fullscreen )
                 */
                if(args[i] == "-windowed" || args[i] == "-sw" || args[i] == "-nofs")
                {
                    jWindowed = args[i];
                    if (jWindowed == "-windowed")
                        GameWindowFlags.FixedWindow; // ????
                }

                if (args[i] == "-game")
                {
                    jGameDir = args[i + 1];
                }
            }

            game.Location = CenterWindowOnScreen();
            game.Run(60);
            return 0;
        }
    }

    class SDLWindow : GameWindow
    {
        public SDLWindow() : base(640, 480, GraphicsMode.Default,
            "Half-Life CSharp", options: GameWindowFlags.Fullscreen,
            device: DisplayDevice.Default, major: 4, minor: 5, flags: GraphicsContextFlags.Embedded)
        {
            WindowBorder = WindowBorder.Fixed;
        }

        protected override void OnResize(EventArgs e)
        {
            GL.Viewport(0, 0, Width, Height);
        }

        protected override void OnLoad(EventArgs e)
        {
            CursorVisible = true;
        }

        protected override void OnRenderFrame(FrameEventArgs e)
        {
            Color4 backColor;
            backColor.A = 1.0f;
            backColor.R = 0.1f;
            backColor.G = 0.1f;
            backColor.B = 0.3f;
            GL.ClearColor(backColor);
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);

            SwapBuffers();
        }
    }
}
```
Can I have to read documents of OpenTK 2.0 / 3.0pre?

Thanks! PS: I don't know if nothing has example like my idea for switchable mode full scren or window if I use button or write via command line argument

**Comment by talyian** [comment]
hi @sourceskyboxer , this is probably better to ask on StackOverflow or something, but the answer is you can just set "window.WindowState = WindowState.FullScreen" or "window.WindowState = WindowState.Normal". Keep in mind that just as in other opengl applications you'll have to re-calculate your viewport based on the current window size.

**Comment by sourceskyboxer** [comment]
Hi @talyian , oh you mean calculate with viewport of OpenTK and I need to write like 1:1 = normal window with current resolution and fullscreen mode of native resolution and game window resolution  => (native resol) : (gamewindow resol). Thanks I hope I can....

**Comment by winterhell** [comment]
If you are ok with rendering according to the native resolution then perhaps
  protected override void OnResize(EventArgs e)
        {
        GL.Viewport(0, 0, Width, Height);
        }
If you want your game at a specific aspect ratio you can calculate the letterboxing or pillarboxing and put it in GL.Viewport.

**Comment by daerogami** [comment]
@sourceskyboxer @talyian Your thread has been migrated to #654 to keep this issue on topic. You are encouraged to further discuss on gitter, thank you!

**Comment by djohns451** [comment]
@daerogami, @talyian, I have a preview of the available documentation that I will be hosting soon on my fork.

**Comment by djohns451** [comment]
https://djohns451.github.io/opentk/index.html

Serving from the `gh-pages` branch currently.

**Comment by DylanFPS** [comment]
Done in opentk/opentk.github.io#12
