### ISSUE TITLE
Improve performance of bindings using strings

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#611]
The current way string bindings work is pretty inefficient. When passing in a string in we allocate new unmanaged heap memory convert the string data to ANSI (copying it to the new heap memory) then pass that to OpenGL and then free the heap memory. String arrays are even more allocations as we allocate for the array and then every string in the array. For out parameters we allocate unmanaged heap memory for OpenGL to write to, then convert that to a string (which is a managed allocation).

We also do all our conversions using the ANSI encoding, OpenGL actually states that strings are UTF8. So there's a hell of a bug waiting to happen here! There's probably also scope for length bugs here (although I have nothing concrete to prove it) where we pass the wrong counts to OpenGL due to differences of UTF8 and UTF16.

All in all things aren't very performance friendly and there's almost certainly some bugs.
We could probably do some checks to allocate small unmanaged strings on the stack. 
We should change encoding/decoding to use UTF8.

**Comment by varon** [comment]
New generator, so closing this.

**Comment by varon** [comment]
The issue was mistagged; this is not the generator but the rewriter.

**Comment by DylanFPS** [comment]
The rewriter is being retired (#854), so this is irrelelvant.
