### ISSUE TITLE
Add length checks to array parameters

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#612]
PR #588 added CountAttributes to all array and string parameters. We should use that count parameter to emit length checks when rewriting the methods.

Need to take into account that lengths are often in terms of bytes while if we have generic type overloads we'll need to divide/multiple by the type's size.

**Comment by varon** [comment]
I'm generally against this for the bindings. It's pretty easy for the client to do, and would be annoying to eat a bounds check on stuff that we know isn't OOB. I'd prefer if we could approach zero overhead over the C bindings.

Perhaps only in debug mode?

**Comment by daerogami** [comment]
If it does end up in debug mode it should be an opt-in behavior.
While it can be assumed that debug adds overhead, performance should still be preserved as much as possible.
@Frassle What would happen if the length check failed?

**Comment by varon** [comment]
@daerogami it should add almost no overhead, even in debug mode. We definitely want it in there by default. We're talking like <1% speed changes.

If the length check failed it would probably throw a suitable invalidArg or IndexOutOfRange exception I'd guess. If we didn't have the length check, it would potentially segfault at some point in the future.

**Comment by varon** [comment]
@Nihlus  - Any updates or info on this?

Reckon you could do it?

**Comment by varon** [comment]
@FreezyLemon too.

**Comment by FreezyLemon** [comment]
Before I can answer this, there is an important, general question:
What is the role of the rewriter going forward?

Let's for example look at #805, which in its current state completely obsoletes the rewriter (making this suggestion something to implement in ADL, the library that all the "rewriting" is offloaded to):

>No build-time doctoring of the assembly is required. All of the native binding code is generated once at application startup (or when the given API endpoint is called) - effectively, a managed IL JIT. This makes Generator.Rewrite effectively obsolete.

Of course I'm not saying that ADL will definitely be used like its shown in that PR, just that there should be a discussion on what to do.

**Comment by DylanFPS** [comment]
Is this a non-issue given that we've retired the rewriter in favour of ADL?

**Comment by DylanFPS** [comment]
I'm writing the binder for ADL, and I don't think we can do length checks without overcomplicating everything (I don't even think it's possible!)

The count attribute will be retained.

**Comment by varon** [comment]
This should be fixed by 5.x
