### ISSUE TITLE
X11 backend doesn't behave synchronously

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#616]
Many GameWindow properties can behave strangely on the X11 backend. A read-change-write-read loop gives unexpected results (see issue #259).

For example the following mini test can sometimes fail!
```
var width = gameWindow.Width;
width += 1;
gameWindow.Width = width;
AssertEqual(gameWindow.Width, width);
````

The underlying issue is due to the fact that X11 is a buffered and asynchronous protocol. We call xlib to resize the window, it creates an event and puts it on an output buffer, at some point that buffer is flushed and sent to the server, and then some point later the server actually acts on the resize request and then some point later it sends back a ConfigureEvent.
This is how X is designed to work, but it doesn't match our API which looks synchronous. That is once the setter for Width has returned the programmer expects that their window now has that width, not that it will maybe have that width later.

PR #567 was a first attempt at fixing this, and it seemed to fix #259. But while working on #590 more cases were found that sometimes failed and trying the same fix didn't help.

After spending some time looking into this and trying a couple of other approaches I feel this is going to be a very tricky problem to fix properly. Any input, ideas, guidance would be helpful!

The three ideas I already tried:
A) Just calling XSync before ProcessEvents. This doesn't guarantee that we will of got the events back even if the server has operated on them. That is the window should of resized but we might not hear about it.

B) Calling XSync then sending a client event and waiting for that. This still missed events. I'm not sure why my reading of the X specification suggests all requests have to be acted on in order and events queued in order so I suspect it was probably window manager shenanigans.

C) Calling ProcessEvents until our backing data matches up with what we think it should be. For example the end of the Bounds setter would have a loop with:
```
while(Bounds != value) { ProcessEvents(); }
```
This caught all events and passed all synchronous tests, but it will dead lock the application in the event that we make a request that the X server doesn't act on (a very simple way to break this would be to send an X coordinate larger than 2^16, I'm sure there's many other more common ways).

**Comment by VPeruS** [comment]
Why not just behave like "Everything OK! We changed bourders for you!"? If reponse "cannot change res" pop up throw exception("With explanation that cannot change resolution." + docs that changing resolution can throw exception).

**Comment by VPeruS** [comment]
Approach C can have timeout + boolean

**Comment by tzachshabtay** [comment]
Another possibility would be to make yet another breaking change and have the API async.
From my experience trying to shoehorn an async workflow to a sync API is always hacky and buggy.

**Comment by Nihlus** [comment]
While I reserve my opinion until I've had some time to understand the whole issue, one option is to just live with it and make a note to users that window changes may not propagate right away.

**Comment by leezer3** [comment]
Having just been hit by this one (see linked bug above), I'm not sure what the answer is.

Changing to full-screen is an operation that I've definitely seen totally fail, and this is why I had the check immediately after calling the full-screen switch.
It's been worked around by adding a 20ms delay before making the check, so it's not of absolute importance, but it's still an operation which I need to know whether it's succeeded or not.

From my perspective, approach C is the best of a bad bunch, but I'm not convinced it's worth the trouble.
Having the possibility to completely deadlock the app (even with a timeout) isn't at all good, and it adds extra spinning loops.

**Comment by varon** [comment]
Closed by 4.x
