### ISSUE TITLE
(windows) GameWindow starts off-center when DPI Scaling is not 1:1

### ISSUE THREAD

**Issue by talyian** [opentk/opentk#617]
### Description

the default window location is `(display.Left + (display.Width - window.Width) / 2), 
    display.Top + (display.Height - window.Height) / 2)` as seen in https://github.com/opentk/opentk/blob/4f60f956078d08288923b51936097dcf0129eda4/src/OpenTK/NativeWindow.cs#L73.

The fundamental issue is the same as #47 -- The GameWindow constructor on Windows uses scaled points but just about everything else uses pixels.

A kind of quick-ish fix would be to add a DisplayResolution.DPIScaling property and take that into consideration at the one location here, but uniformly using pixels or points across the interface (so that GameWindow.Width returns the same value as the constructor) would be preferable.

### Repro steps

1. Set windows DPI to 200% on your primary monitor.
2. Start a `new GameWindow(400, 400)`
3. Observe it lurking at the lower right corner of the screen.

### Expected behavior
Window appears in center of screen

### Actual behavior
see Repro

### Related information 
Windows, recent-ish OpenTK `develop` branch.

**Comment by talyian** [comment]
Looking at the code further,  the `scaled_x = ScaleX(x)` stuff in `WinGLNative.cs` that is exacerbating the problem -- it is unnecessary since x comes from the DisplayDevice and is in what windows considers scaled coordinates already. However, the (device.Width - window.Width) / 2 in `NativeWindow.cs` is subtracting the window's (pixel) width from the devices (scaled) width, so the ScaleX/Y stuff needs to happen earlier (preferably when the display resolutions are enumerated).

**Comment by varon** [comment]
Thanks for the super detailed report!

**Comment by Frassle** [comment]
Probably related to #47.

**Comment by varon** [comment]
Fixed by 4.x
