### ISSUE TITLE
Add OpenGL 4.6 Support

### ISSUE THREAD

**Issue by Secticide** [opentk/opentk#621]
### Description

OpenGL 4.6 has recently been released, [here](https://www.khronos.org/news/press/khronos-releases-opengl-4.6-with-spir-v-support) is some information regarding it's additional features.

It would be great to see OpenGL 4.6 support within OpenTK.

### Additional Information

* [OpenGL 4.6 Core Profile Specification](https://khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf)
* [OpenGL Shading Language 4.60 Specification](https://khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf)

The above information and more can be found [here](https://www.khronos.org/opengl/).

**Comment by Frassle** [comment]
Hopefully a simple case of grabbing new specs from https://github.com/KhronosGroup/OpenGL-Registry and rerunning convert and bind. I'll give it a shot.
