### ISSUE TITLE
Retrieving shader info log after unsuccessful compilation on Intel and printing it throws AccessViolation

### ISSUE THREAD

**Issue by TGEnigma** [opentk/opentk#629]
### Description

Calling `GL.GetShaderInfoLog( int shader )` after an unsuccessful compilation of a fragment shader and printing the value to the console causes an AccessViolationException on a system with an Intel IGPU.

### Repro steps

```
GL.GetShader( shader, ShaderParameter.CompileStatus, out int compileStatus );
if ( compileStatus == 0 )
{
	GL.GetShader( shader, ShaderParameter.InfoLogLength, out int infoLogLength );

	if ( infoLogLength > 0 )
	{
		// OK
		var shaderInfoLog = GL.GetShaderInfoLog( shader );
                // Causes AccessViolationException
		Console.WriteLine( shaderInfoLog );
	}
}
```

### Expected behavior

Shouldn't crash.

### Actual behavior

Should print the shader info log as normal.
What's curious is that it crashes the instant I attempt to write the log to the console, and not when I retrieve it.

### Related information 

Windows 8
Native GL
Source
.NET Framework
Tested on an Intel HD 4400

I don't have a text dump of the console output (it didn't happen on a system I own personally) but I do have an image of it.
![](https://media.discordapp.net/attachments/153593230024245248/343180421326045184/unknown.png)

**Comment by Frassle** [comment]
Maybe related to #515 and #517?

**Comment by subchannel13** [comment]
Which version of OpenTK?

**Comment by UnknownShadow200** [comment]
GLSL source of the shader that fails to compile might be handy too.

**Comment by TGEnigma** [comment]
OpenTK was built from source.

Fragment shader source:

```
#version 330 core

// in
in vec3 fragVertNrm;
in vec2 fragVertTex0;
in vec4 fragVertClr0;

// out
out vec4 fragColor;

// uniform
uniform sampler2D diffuse;
uniform bool isTextured;

void main()
{
	vec4 diffuseSample = vec4( 1f, 1f, 1f, 1f );

	if ( isTextured )
	{
		diffuseSample = texture2D( diffuse, fragVertTex0 );
	}

	// simple lambert diffuse lighting
	vec3 lightDirection = vec3( 0f, 0f, -1f );
	float lightIntensity = 1.2f;

	float lambertDiffuse = max( 0.0f, dot( lightDirection, fragVertNrm ) );
	lambertDiffuse = clamp( lambertDiffuse * lightIntensity, 0.75f, 2.0f );

	fragColor = vec4( ( diffuseSample * fragVertClr0 * lambertDiffuse ).rgb, diffuseSample.a );
} 
```

**Comment by Nihlus** [comment]
If you inspect the value in the debugger, what do you see?

**Comment by TGEnigma** [comment]
Accessing the string value in any way be it by evaluating the expression in the debugger or indexing into the string manually throws an access violation.
Interesting to note is that I accidentally circumvented the crash by setting the GraphicsContextFlags.ForwardCompatible flag in the window graphics context flags.

**Comment by Frassle** [comment]
@TGEnigma you said you built OpenTK from source, can you let us know what revision that was. We've recently made a big change to string parameters, if you don't have that change it would be worth updating it and trying it, and if you do have that change we've screwed something up!

You can tell if you have the string change as you'll have an overload for GetShaderInfoLog which looks like:
```void GetShaderInfoLog(uint shader, int bufSize, out int length, out string infoLog)``` the old version used a StringBuilder in the last parameter.

If you have that overload it would be good to try using it directly like:
```
GL.GetShader( shader, ShaderParameter.CompileStatus, out int compileStatus );
if ( compileStatus == 0 )
{
	GL.GetShader( shader, ShaderParameter.InfoLogLength, out int infoLogLength );

	if ( infoLogLength > 0 )
	{
		// OK
                int dummy;
		string shaderInfoLog;
                GL.GetShaderInfoLog( shader , infoLogLength + 1, out dummy, out shaderInfoLog );
                // Causes AccessViolationException
		Console.WriteLine( shaderInfoLog );
	}
}
```

**Comment by Nihlus** [comment]
@TGEnigma Any updates on this?
