### ISSUE TITLE
GLControl in MDI , how to change active window to desired mdi children?

### ISSUE THREAD

**Issue by Kojimag** [opentk/opentk#636]
I'm using dockpanelsuite  in mdi condition.  GLControl is used in each mdi children.  After creating some 
mdi children for example mdi1, mdi2,mdi3, focus is in the mdi3, I can move drawing in mdi3 by mouse.   Then when I click mdi1, I cannot move drawing in mdi1. Even if using focus(), Topmost, refresh(),activate() on mdi1. Only mdi3 drawing can move.  When checking by debug  both of "this" in the  this.glControl1_Paint and this.glControl1_MouseMove_1 showing mdi1 already. however could not move drawing on the mdi1.
But can move mdi3.
How can I get focus changed on mdi1 and  could move drawing on mdi1? 

* Windows10, 64bit
* OpenTK 3.0.0-pre,GLControl 3.0.0-pre
* .NET Framework 4.6.1

**Comment by Nihlus** [comment]
Support questions should be asked on Gitter or Discord. The github issues are for bugs and feature discussions.
