### ISSUE TITLE
GL.ReadPixels does not work with Windows 7

### ISSUE THREAD

**Issue by phucpd53** [opentk/opentk#638]
### Description

I have tried to save OpenTK Screen to bitmap using GL.ReadPixels in .NET 4.5 Framework. It works perfectly in Windows 10. However, when I ran it in Windows 7, the saved picture is black (every pixel seems to be recorded as zero). I wonder just because OpenTK does not support Windows 7 or I need to install some dependencies to make it work?

I have tried OpenTK Ver 1.1.1616.8959 and Ver 3.0.0
### Repro steps

Here is my code:
                    
                    int renderWidth;
                    int renderHeight;
                    Bitmap bmp = new Bitmap(renderWidth, renderHeight);

                    GL.ClearColor(Color.White);
                    GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
                    GL.Enable(EnableCap.DepthTest);
                    GL.Viewport(0, 0, renderWidth, renderHeight);

                    SetProjectionMatrix(i);
                    SetModelViewMatrix(i);
                    DrawModel(i);
                    GLrefresh();
                    {
                        System.Drawing.Imaging.BitmapData dat = bmp.LockBits(
                            new Rectangle(0, 0, renderWidth, renderHeight),
                            System.Drawing.Imaging.ImageLockMode.WriteOnly, System.Drawing.Imaging.PixelFormat.Format32bppArgb);

                        GL.Finish();
                        GL.ReadBuffer(ReadBufferMode.Back);
                        GL.ReadPixels(0, 0, renderWidth, renderHeight, PixelFormat.Bgra, PixelType.UnsignedByte, dat.Scan0);
                        bmp.UnlockBits(dat);
                        bmp.Save(targetImgFilename);
                    }
### Related information 

* Operating system: Windows 7 ServicePack1 64bit
* OpenTK 3.0.0 installed from Nugets
* .Net 4.5

**Comment by UnknownShadow200** [comment]
What GPU do you have?

**Comment by phucpd53** [comment]
Windows 7: Intel(R) HD Graphics 520
Windows 10: Intel(R) HD Graphics 2000

**Comment by winterhell** [comment]
Windows 7 SP1 64bit here, GeForce GTX 650
Both OpenTK 2.00 something, under .Net Framework 2.0 application 
And latest pull from github under .Net Framework 4.0 application GL.ReadPixels fine.

**Comment by phucpd53** [comment]
So nothing wrong with the OS I guess. Maybe the video card is too old or something like that. Thanks for your time

**Comment by Frassle** [comment]
It's worth trying two things.
1) Write white to the image before calling ReadPixels and see if it's still black. If it's white it means ReadPixels isn't actually reading back anything, if it's black ReadPixels is reading all black.
2) Add a call to glGetError after ReadPixels to see if there's an GL error been raised (if your using a debug build of OpenTK it should do this for you)

**Comment by winterhell** [comment]
Have you ever installed drivers for the GPU? Intel provides such and I've seen newer drivers unbreak software I've written with OpenTK before.

**Comment by phucpd53** [comment]
I have found the solution for this: https://github.com/opentk/opentk/issues/3
All I need to do is to bring every render thing to PaintEvent. Even I still do not know how the old code works with my Windows 10 PC, thanks every one for helping me
