### ISSUE TITLE
Mega Drive 6 button pad only counts half the buttons

### ISSUE THREAD

**Issue by winterhell** [opentk/opentk#640]
I'm using an original Sega MegaDrive 6 button pad, (actually 8 buttons), via adapter "USB Genesis RetroPort". 
the GamePad class recognizes START, A, B, C as "A, B, X, Y" from its internal buttons, and then duplicates their states with MODE, X, Y, Z.
Same with the Joystick class.
The D-Pad detects values  -1.000031, 1 on negative and positive press, and -0.003936888 on neutral position. I can round them, but it might be a different issue.
This is on Windows 7.

Emulators like Kega Fusion and Dolphin properly recognize all 8 buttons individually.

**Comment by winterhell** [comment]
> Using WinRawJoystick.
>     [WinRawJoystick] Registered for raw input
>     [WinRawJoystick] Querying joystick 0008f000-0000-0000-0000-504944564944
>         Analyzing value collection 0  
>         Found axis 0 (GenericDesktop / Y)
>         Analyzing value collection 1  
>         Found axis 1 (GenericDesktop / X)
>         Analyzing button collection 0 range 
>         Found button 0 (Button / 1)
>         Found button 1 (Button / 2)
>         Found button 2 (Button / 3)
>         Found button 3 (Button / 4)
>         Analyzing button collection 1 range 
>         Found button 4 (Button / 1)
>         Found button 4 (Button / 2)
>         Found button 4 (Button / 3)
>         Found button 4 (Button / 4)
If I print the buttons they come out 
0 1 2 3 0 1 2 3

**Comment by varon** [comment]
Fixed by 4.x
