### ISSUE TITLE
Rewrite.exe is adding spurious references to .NET 4.0 assemblies to OpenTK.dll

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#642]
Rewrite.exe is resolving 2.0 assembly references to 4.0 assemblies and then adding this assembly dependencies to OpenTK.dll when writing it back out.

**Comment by Frassle** [comment]
I think a498da9448ce84b034bc6f39b144465cb7c966ad fixed this on Windows at least. Need to check Linux, I think Mono.Cecil is probably still resolving assemblies badly there.

**Comment by Nihlus** [comment]
@Frassle Is this fixed?

**Comment by Frassle** [comment]
Haven't been on my linux machine in a while to check. I'll try to get round to it over the Christmas holidays!

**Comment by Frassle** [comment]
Ok this is still an issue when compiling on Linux.

**Comment by Frassle** [comment]
Is an issue in cecil. I've pushed a PR to them to fix it, and I'll get a short term fix in place and add a PR here for it.
