### ISSUE TITLE
Remove generated bindings from source control

### ISSUE THREAD

**Issue by varon** [opentk/opentk#648]
### Description

Including the generated bindings in source control makes little sense. 
We should generate them as part of the build script.

This will avoid the majority of the clutter, such as what is caused by #622.

### Steps to solve

1. Remove bindings from source control
2. Add suitable .gitignore to the bindings
3. Generate the bindings as a task in the build.fsx script

### Considerations

We want to make sure we can still build in the IDE. It is acceptable to have to run `build.sh` or `build.cmd` once before the IDE will compile.

We also want to ensure the bindings generator is determinstic if we do this.

If at all possible, we also want to avoid having the IDE parse the entire generated source files every time we open OpenTK. This causes significant slowdowns and harms analysis.

**Comment by varon** [comment]
@Frassle @Nihlus - We've discussed this before, and it seems like a good idea. This shouldn't be too hard for you bindings wizards.

**Comment by varon** [comment]
@realvictorprm - This is a pretty easy one if you want to help out. Even a bit of F# here and there.

**Comment by Nihlus** [comment]
@varon The binding generator is at present deterministic, given that the XML specifications in source control are the ones that are used (e.g, same input every time).

In order to explicitly omit the generated files from StyleCop, we can add autogenerated file headers to them as well.

**Comment by Frassle** [comment]
> In order to explicitly omit the generated files from StyleCop, we can add autogenerated file headers to them as well.

I think the intention wasn't to omit them from style checks but instead to not have them committed so style changes don't have to be thousand line PR's to just update auto-generated files.

> Generate the bindings as a task in the build.fsx script

It might actually be worth making them MSBuild tasks. I'll try and find some time to look into it.

**Comment by varon** [comment]
Sounds good.
