### ISSUE TITLE
AxisAngle to Quaternion Inconsistent

### ISSUE THREAD

**Issue by eafreak** [opentk/opentk#655]
Hallo

I may be wrong in my assumption that Quaternion.FromAxisAngle should be the same as new Quaternion(Axis, Angle). The the following UnitTest methods should yield the same result, however It seems that Quaternion.FromAxisAngle fails.

The expected W should be 3.14159274, yet the result is : -4.371139E-08

[TestMethod]
public void OpenTK_QuaternionNewAxisAngle()
{
var a = MathHelper.DegreesToRadians(180);
var q = new Quaternion(-Vector3.UnitX, a);

Assert.AreEqual(-1, q.X);
Assert.AreEqual(0, q.Y);
Assert.AreEqual(0, q.Z);
Assert.AreEqual(a, q.W);

System.Diagnostics.Trace.WriteLine(q);
}

[TestMethod]
public void OpenTK_QuaternionFromAxisAngle()
{
var a = MathHelper.DegreesToRadians(180);
var q = Quaternion.FromAxisAngle(-Vector3.UnitX, a);

Assert.AreEqual(-1, q.X);
Assert.AreEqual(0, q.Y);
Assert.AreEqual(0, q.Z);
Assert.AreEqual(a, q.W);

System.Diagnostics.Trace.WriteLine(q);
}

**Comment by eafreak** [comment]
Ok, it seems the problem is with the System.Math.Cos(angle), it cannot handle too many decimals. Adding Math.Round(angle, 3) is a workaround.

But once again, I am only assuming here

**Comment by UnknownShadow200** [comment]
If you use an angle of 45/90 degrees for example, you will get vastly different results between the two ways. 

I doubt changing the existing of new Quaternion by that much is a good idea.

**Comment by drdbkarron** [comment]
I found a wobble in quaternions that should not be there. This needs a full validation suite; i can contribute my demonstration of the problem.  I abandoned using this package because of this.

**Comment by varon** [comment]
As soon as someone gets some time, we'll just need to go check the maths and implementations are working as expected. Based on @UnknownShadow200 's comment, it looks like it could be a handedness issue.

@drdbkarron  - Most of the maintainers are using this kind of thing extensively in fairly elaborate 3D programs without any difficulty. Quaternions included.

We actually have extremely good test coverage of just about everything (apparently except for this) so if you can provide an example we can get a fix for you fairly shortly.

**Comment by Frassle** [comment]
It's Quaternion(Vector3 v, float w), it isn't axis & angle. That constructor is for assigning the vector and float part of the Quaternion directly, it does no translation.

Arguably a confusing constructor but not a bug.
