### ISSUE TITLE
Very unreliable keyboard events on Mac OS

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#657]
### Description

As I'm trying port my game to Mac OS I realize the keyboards events that work perfectly well on windows/.net and linux/mono hardly work at all on macos/mono

The keydown, keypress and keyup events seem to fire only every few dozen upon hitting the key.

Not sure but it might be related to the games frame rate. I'd love to debug this stuff, but OpentK won't compile on Xamarin. The Rewrite post build event fails.
 
I'm currently trying to just emulate the events by checking the keyboard state every render frame, which works but that is turning out to get real ugly with virtual key mapping and stuff.

### Related information 

Mac OS Yosemite 10.10.5
Native
NuGet 2.0.0
.net framework 4.5.2

**Comment by Nihlus** [comment]
Please try the latest version. v2.0.0 is very old, and these issues may no longer be present.

**Comment by tyronx** [comment]
Ok I tried the latest dev version built from the devlop branch via build.sh and made sure my game uses this version. I don't fell much of a difference.

**Comment by tyronx** [comment]
omg i found the problem. Somewhere in the legacy code base there was a call to Application.DoEvents(); inside the render loop. It probably ate away most of they keyboard events.
