### ISSUE TITLE
Depth test fails while using frame buffer with depth attachment

### ISSUE THREAD

**Issue by dhirendvs** [opentk/opentk#660]
### Description

The depth test fails while rendering to a frame buffer with a depth attachment.

### Repro steps

1. Initialization code for creating frame buffer with color and depth attachments:

```csharp
// frameBuffer, colorBuffer and depthBuffer are class members of type uint
GL.GenFramebuffers( 1, out frameBuffer );
GL.GenRenderbuffers( 1, out colorBuffer );
GL.GenRenderbuffers( 1, out depthBuffer );

GL.BindFramebuffer( FramebufferTarget.Framebuffer, frameBuffer );

// bind color buffer to frame buffer
GL.BindRenderbuffer( RenderbufferTarget.Renderbuffer, colorBuffer );
GL.RenderbufferStorage( RenderbufferTarget.Renderbuffer, RenderbufferStorage.Rgb32f, Width, Height );
GL.FramebufferRenderbuffer( FramebufferTarget.Framebuffer, FramebufferAttachment.ColorAttachment0,
	RenderbufferTarget.Renderbuffer, colorBuffer );

// bind depth buffer to frame buffer
GL.BindRenderbuffer( RenderbufferTarget.Renderbuffer, depthBuffer );
GL.RenderbufferStorage( RenderbufferTarget.Renderbuffer, RenderbufferStorage.DepthComponent24, Width, Height );
GL.FramebufferRenderbuffer( FramebufferTarget.Framebuffer, FramebufferAttachment.Depth,
	RenderbufferTarget.Renderbuffer, depthBuffer );

// verify frame buffer bindings
if( GL.CheckFramebufferStatus( FramebufferTarget.Framebuffer ) !=
	FramebufferErrorCode.FramebufferComplete )
{
	throw new Exception();
}

// unbind frame buffer
GL.BindFramebuffer( FramebufferTarget.Framebuffer, 0 );
GL.BindRenderbuffer( RenderbufferTarget.Renderbuffer, 0 );
```

2. Rendering code for verifying depth bits for default frame buffer and custom frame buffer:

```csharp
int depth = 0;
GL.GetInteger( GetPName.DepthBits, out depth ); // depth = 24 as expected for default frame buffer

GL.BindFramebuffer( FramebufferTarget.Framebuffer, frameBuffer );

depth = 0;
GL.GetInteger( GetPName.DepthBits, out depth ); // depth = 0 which means depth buffer is not attached
```

### Expected behavior

The Depth test should work while rendering to a frame buffer with a depth attachment.

### Actual behavior

The Depth test fails and the rendering occurs as in the case when depth test is disabled.

### Related information 

* Operating system: Windows 10
* OpenTK: Version 2.0
* .Net: 4.5.2
* The same problem occurs even while using OpenTK 1.0 on Android

**Comment by dhirendvs** [comment]
Another reference link related to the same issue:
https://stackoverflow.com/questions/24109208/opengl-framebuffer-depth-buffer-not-working

**Comment by varon** [comment]
Thanks for the report. I edited your post to add some syntax formatting. I'll take a look and see if I can spot the error.

**Comment by varon** [comment]
try swapping

```csharp
GL.FramebufferRenderbuffer( FramebufferTarget.Framebuffer, FramebufferAttachment.Depth, RenderbufferTarget.Renderbuffer, depthBuffer );
```


to
```csharp
GL.FramebufferRenderbuffer( FramebufferTarget.Framebuffer, FramebufferAttachment.DepthAttachment, RenderbufferTarget.Renderbuffer, depthBuffer );
```

**Comment by dhirendvs** [comment]
Based on your suggestion, I used FramebufferAttachment.DepthAttachment instead of FramebufferAttachment.Depth as the 2nd parameter to GL.FramebufferRenderbuffer(), and the problem is now solved.

This issue was my mistake and not an OpenTK bug. Thanks a lot.

**Comment by varon** [comment]
Any time! Good luck with the project.

Feel free to join us in Gitter to ask this kind of thing.
https://gitter.im/opentk/opentk
