### ISSUE TITLE
MouseWheelEventArgs deltaPrecise and valuePrecise 10 times smaller on MacOS

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#664]
### Description

Using the latest opentk build, firing the window.MouseWheel event through a turn of the mouse wheel by a single notch:

- On a Mac delta/value are 0, deltaPrecise/valuePrecise change in ~0.1 increments
- On a Windows PC delta is -1/1, value changes in increments of 1; deltaPrecise/valuePrecise change in increments of 1.

The values reported under Windows are the expected behavior, I presume. All in all the values on mac seem almost exactly divided by 10. Which means slow turning of the mousewheel causes delta always to be 0. 

When turning the mousewheel quickly however, the delta is in the range of about [-8, 8].

The same issue happens when using the 2 finger mouse wheel feature of the touch pad on my MacBook Air.

### Related information 

* macOS High Sierra 10.13 / Standard USB mouse
* Native OpenTK Backend
* Latest build from source code
* Mono 4.5

**Comment by tyronx** [comment]
Perhaps related to https://github.com/davekeck/DisableExtremeScrollAcceleration

**Comment by VPeruS** [comment]
iirc wheel not work in previous version. Code that handle event -> https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L761

**Comment by VPeruS** [comment]
So it seems https://github.com/opentk/opentk/blob/9bd713fb084fad3a4fc8137bae2eaa36b06e70e7/src/OpenTK/Platform/MacOS/MacOSFactory.cs#L37 is problem

**Comment by tyronx** [comment]
Interesting, Looks almost like it was done on purpose.

**Comment by VPeruS** [comment]
There is TODO above const.

**Comment by tyronx** [comment]
So I guess this behavior can be attributed to the different mousewheel scrolling behavior of MacOS.

I guess it would be ok to close this issue and leave a note on the Website FAQ that this difference exists.
