### ISSUE TITLE
NativeWindow.CursorVisible reseting mouse position to 0/0

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#668]
### Description

Setting NativeWindow.CursorVisible to false then true again seems to set the mouse position to 0/0 (absolute coordinate) on MacOS instead of remembering the previous position

This causes problems because a moue click then activates the mac os menu and unfocuses the game window.

I had a closer look at the mac os implementation in opentk but I couldn't find anything could cause such a behavior. I'm almost inclined to blame it on the mac os.

Something seems unusual though, the official documentation at https://developer.apple.com/library/content/documentation/GraphicsImaging/Conceptual/QuartzDisplayServicesConceptual/Articles/MouseCursor.html suggests to make use of CGDisplayHideCursor, which opentk doesn't. Unfortunately apples documentation is inconclusive as to whether this could be the cause of the problem.

### Related information 

* Mac OS High Sierra 10.13
* Native backend
* Latest build
* Mono

**Comment by tyronx** [comment]
Upon further investigation even a call to Mouse.SetPosition(100, 100) places the mouse cursor at 0/0

**Comment by tyronx** [comment]
...and now the bug disappeared as mysteriously as it appeared. wtf.

**Comment by tyronx** [comment]
Argh, starting my game from inside visual studio (on mac) works, but running it from console produce the bug. wtffff.

**Comment by VPeruS** [comment]
different version are used while running

**Comment by tyronx** [comment]
I checked, in both cases the same mono runtime version is used.

**Comment by VPeruS** [comment]
What version of opentk are you using?

**Comment by tyronx** [comment]
The latest version from the develop branch.

**Comment by Nihlus** [comment]
@tyronx Have you been able to reliably reproduce this issue?

**Comment by tyronx** [comment]
Yes, the bug appeared consistently as long as i started my game not within visual studio.

**Comment by Nihlus** [comment]
I'm referring to a cause as to why it's not happening in VS, or some condition that would reproduce that behaviour outside of VS. We've also discovered that this is also the case on Linux (#696). If you have a Windows machine on hand, it would be very helpful if you attempted to reproduce the bug there as well.

**Comment by tyronx** [comment]
I am usually on windows, there everything mouse related (using the same opentk methods) works flawlessly.
I'll see if i can further track down the issue on the mac side once i get access to a macbook again

**Comment by VPeruS** [comment]
@tyronx take a look at https://github.com/opentk/opentk/pull/589 it separete visibility and confining

**Comment by tyronx** [comment]
@VPeruS neat, will do when i got access to my macbook again, in about 12 days

**Comment by tyronx** [comment]
@Nihlus the issue is reliably reproducable, now also in Visual Studio on MacOS High Sierra
I'm using the latest build, including the PR from @VPeruS  (@copygirl was nice enough to merge that stuff for me into https://github.com/anegostudios/opentk/tree/mouse-fixes)

**Comment by NogginBops** [comment]
Is this still open or should this be closed? Seems there are some commits that fix this issue?

**Comment by tyronx** [comment]
A fix for has been merged into the 3.x branch, so can be closed, i think

**Comment by varon** [comment]
Thanks.
