### ISSUE TITLE
Modifier keys not detected as individual keypresses on macOS

### ISSUE THREAD

**Issue by swoolcock** [opentk/opentk#669]
### Description

~~Key events are inconsistent for modifier keys on macOS.~~
1. Modifier keys do not fire `OnKeyDown`/`OnKeyUp`
2. Printable keys fire `OnKeyPress` even if modifier keys are held
3. Non-printable keys such as `home` and `end` fire `OnKeyPress` with large keychar values

### Repro steps

~~1. Write some code that should trigger on any keypress event.
2. Press the command key, or something similar.~~

Write some code that will catch/log `OnKeyUp`, `OnKeyDown`, and `OnKeyPress` events, then:
1. Press and release individual modifier keys.
2. Press and release some non-printable keys (such as home/end/pgup/pgdown)
3. Hold a modifier key (such as control) and press a printable key (any letter)

### Expected behavior

~~Code triggers.~~
1. Modifier keys fire individual `OnKeyUp` and `OnKeyDown` events, but not `OnKeyPress`
2. Non-printable keys should fire `OnKeyUp` and `OnKeyDown` events, but not `OnKeyPress`
3. Pressing printable keys with a modifier should fire `OnKeyUp` and `OnKeyDown` events, but not `OnKeyPress`

### Actual behavior

~~Code does not trigger.~~
1. Modifier keys do not fire any events
2. Non-printable keys correctly fire `OnKeyUp` and `OnKeyDown`, but incorrectly fire `OnKeyPress`
3. Modified printable keys correctly fire `OnKeyUp` and `OnKeyDown`, but incorrectly fire `OnKeyPress`

### Related information 

macOS Sierra 10.12.6

After investigating the OpenTK source and doing some Cocoa tests in Xcode, it appears that the `NSWindow.keyDown:` selector used by OpenTK for key events is not used for modifier keys.  OpenTK will need to accommodate for the `NSWindow.flagsChanged:` selector, which will handle modifiers.

Edit: Description/steps/behaviour updated.

I've implemented some workarounds in a PR for osu!framework for these issues if you'd like to check them out.  Specifically the usage of `flagsChanged:`, since it will let you differentiate between left and right modifier keys.  I am sad that the macOS interop wrappers in OpenTK are flagged `internal`.  :(

https://github.com/ppy/osu-framework/pull/1084

**Comment by VPeruS** [comment]
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L649 opentk doesn't use selectors for key event presses. Also https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L679 is for checking mods. All what you need to do add calls for OnKeyDown and OnKeyUp to solve 1 into right place in switch. 2 and 3 is here https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L665.

**Comment by VPeruS** [comment]
Also if you want to make fix, check behavior on different platforms thay should be equal

**Comment by varon** [comment]
Should be fixed for 4.0 via GLFW.
