### ISSUE TITLE
Failed to compile OpenTK project from source code on Ubuntu 16.04 LTS in monodevelop

### ISSUE THREAD

**Issue by barnoy1** [opentk/opentk#671]
### Description
mono version - 5.2.0
os - ubuntu 16.04 LTS

I tried to compile the project out of the box under monodevelop.
After installing the mono.cecil package under rewrite project
I received the an System.ArgumentOutOfRangeException exception after invoking the following
line in Generator.Rewrite/program.cs 
var assembly = AssemblyDefinition.ReadAssembly(file, read_params);

### Repro steps

Please provide the steps required to reproduce the problem

1. Download source code, brach origin/1.1

2. open OpenTK project from mondevelop 

3. Install mono.cecil Nuget package in Generator.Rewrite (latest version is 0.9.6.4)

4. set all projects framework to MONO / .NET 4.5.

4. set Generator.Rewrite.program arguments to  ../../../OpenTK/bin/Debug/OpenTK.dll ../../../../OpenTK.snk -debug

5. Build solution.

### Expected behavior
All project should pass. The whole solution suppose to compile

### Actual behavior

System.ArgumentOutOfRangeException exception after invoking the following
line in Generator.Rewrite/program.cs 

### Related information 

* Operating system: Linux
*  version of OpenTK Source Code - (origin/1.1)
*  runtime 4.5 NET Framework 
* Workarounds:
 in Generator.Rewrite/program.cs, change line 102 from
var assembly = AssemblyDefinition.ReadAssembly(file, read_params);
to
 AssemblyDefinition assembly= AssemblyDefinition.ReadAssembly(file);
as described in http://www.mono-project.com/docs/tools+libraries/libraries/Mono.Cecil/faq/

**Comment by VPeruS** [comment]
Why you use 1.1 branch?

**Comment by Nihlus** [comment]
The 1.1 branch is severely outdated and is not supported. This issue has been fixed in the master branch.

**Comment by barnoy1** [comment]
what the name of the master branch? the most updated is devlop. Should I pull from 45net branch which dated from august? in my case I work on monodevelop in ubuntu and using mono

**Comment by Nihlus** [comment]
The latest branch is the `develop` branch, yes.

**Comment by barnoy1** [comment]
Thanks.
there is no OpenTK.Compatibility.dll in this source code? who can i generate this dll for linux mapping?

**Comment by Nihlus** [comment]
There is not. Only one assembly (OpenTK.dll) is generated by the current
codebase, and it is the one that should be used for all platforms.

**Comment by barnoy1** [comment]
hello,
I was wondering if you could help me

I receive an expection when invoking the following line:
GraphicsContext graphicsContext = new GraphicsContext(mode, windowInfo); 

ex	{System.InvalidCastException: Specified cast is not valid.   at OpenTK.Platform.X11.X11GLContext..cto…}	System.InvalidCastException

**Comment by VPeruS** [comment]
You should init thing before using. Look at opentk windows class

**Comment by barnoy1** [comment]
Hi,

I used the snippet provided as is (with the suggest fix) and everything compiled and I was able to create the context. 

However, in my application, I need to create **windowInfo out of a window handle (System.IntPtr)**  - not just create new native window like the one found in the snippet. For example, in runtime the WindowHandle value is 0x4800014.

To create a IWindowInfo object out of windows handle I use the openTk utilities namespace:
`
IWindowInfo windowInfo = Utilities.CreateWindowsWindowInfo(WindowHandle);
`

When I modified my code to use that windowInfo described above:
```
1. OpenTK.Toolkit.Init(); 
2. // using  IWindowInfo instead of NativeWindow
3. //OpenTK.NativeWindow window = new OpenTK.NativeWindow(640, 480, "test", 
4. OpenTK.GameWindowFlags.Default, mode, OpenTK.DisplayDevice.Default);
5. IWindowInfo windowInfo = Utilities.CreateWindowsWindowInfo(WindowHandle);
6. var ctx = new OpenTK.Graphics.GraphicsContext(mode, windowInfo, 3, 0, 7. OpenTK.Graphics.GraphicsContextFlags.Default); // exception thrown here
```

I got the same error: _System.InvalidCastException: Specified cast is not valid._
when I debugged the code I think I found the root cause. After creating the IWinfowInfo object (line 5)
I saw that there is something wrong with the device content property:
_DeviceContext:System.EntryPointNotFoundException: GetDC._

**_My question is how to solve this exception? or what is the proper way in OpenTk to create a valid windowInfo out of a windowHandle which can be used in order to create a valid GraphicsContext?_**

**Comment by barnoy1** [comment]
Ok, the problem is probably in line 5, where I accidentally used  
`Utilities.CreateWindowsWindowInfo(WindowHandle);`
where I should have properly use **Utilities.CreateX11WindowInfo( )**
since I'm running on **linux**. 
However, it is not clear to me how to use this function properly.
I looked at the signature: 
`public static IWindowInfo CreateX11WindowInfo (IntPtr display, int screen, IntPtr windowHandle, IntPtr rootWindow, IntPtr visualInfo);
`
could you please direct me to some kind of sample of how to use this method?

**Comment by barnoy1** [comment]
for anyone how come across the same issue, here is my working solution:
			Type xplatui = Type.GetType ("System.Windows.Forms.XplatUIX11, System.Windows.Forms");
			IntPtr display = (IntPtr)GetStaticFieldValue (xplatui, "DisplayHandle");
			IntPtr rootWindow = (IntPtr)GetStaticFieldValue (xplatui, "RootWindow");
			int screen = (int)GetStaticFieldValue (xplatui, "ScreenNo");

			IWindowInfo x11window = null;
			x11window = Utilities.CreateX11WindowInfo (display, screen, WindowHandle, rootWindow, IntPtr.Zero);
