### ISSUE TITLE
OpenTK.dll throws AccessViolationException on Intel HD 530

### ISSUE THREAD

**Issue by entitification** [opentk/opentk#673]
Hi,
This problem has been bothering me for a while now. I have controls written by OpenGL and OpenTK. I use OpenTK for extensions (vs native opengl functions). The thing is my controls work OK on nearly any dedicated GPU or on other intel GPUs. But on Intel 530, all function calls to extension methods (e.g. DrawArrays, etc.) result in the following exception:
"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
As just an example, stack top is:   "at OpenTK.Graphics.OpenGL.GL.DrawArrays(PrimitiveType mode, Int32 first, Int32 count)"

1. My current OS is windows 10 64bit, but this happens on other OS versions too.
2. I've has this issue since .Net 4.5 till now (4.7)
3. I've updated 530 drivers accordingly, my current driver is 22.20.16.4815.
4. This has happened since OpenTK 1.1.4 till now (2.0.0 from nugget)

now, it's clearly an issue with Intel 530 drivers, but some questions remain:
- Why do all my native OpenGL calls work just fine? (either via my extern methods or OpenTK wrappings)
- Why do my controls work fine on older and newer Intel GPUs and approximately all dedicated GPUs.
- If this is an Intel related problem, how do OpenTK users get around it right now? 

Regards.

**Comment by Nihlus** [comment]
Please try reproducing this issue on the latest OpenTK build. You can install it from the development feed linked in the readme. 

This is typical of instances where the OpenGL function pointers cannot be properly loaded. You can try running a from-source or debug build of OpenTK to get more information.
