### ISSUE TITLE
Mouse.GetState/GetCursorState do not report scroll wheel values on X11

### ISSUE THREAD

**Issue by Nabile-Rahmani** [opentk/opentk#674]
### Description

Unlike the `GameWindow.MouseWheel` event, calls to `Mouse.GetState()` or `Mouse.GetCursorState()` do not report scroll wheel values other than 0, rendering applications that do no use the window event unable to respond to mouse wheel scrolls.

### Repro steps

1. Call `Mouse.GetState()` or `Mouse.GetCursorState()` in a loop.

2. Watch the `Scroll`-related variables.

3. Scroll the mouse wheel.

### Expected behavior

Scroll values should be reflected in the `MouseState` structure when scrolling the mouse wheel, just like how the `MouseWheel` event args currently do.

### Actual behavior

`MouseState` never returns a value other than 0 for scroll variables.

### Related information 

* Operating system: Debian 9
* Native backend
* OpenTK NuGet
* Mono, targeting .NET 4.6.1
* Workarounds: use the `GameWindow.MouseWheel` event

**Comment by VPeruS** [comment]
Hello, thanks for report, here is my code sample https://gist.github.com/VPeruS/46ef61ba8381870e20309c383e0168e5.

And output: 
![image](https://user-images.githubusercontent.com/7927055/32145550-4b665c8c-bcd3-11e7-9f5c-e9c98b2648b4.png)

X11 + ArchLinux

**Comment by VPeruS** [comment]
Is it KDE de? Try `xev` program and check if events generates(button 4-5 press) on mouse wheel move

**Comment by Nabile-Rahmani** [comment]
It's GNOME. The wheel events do generate:
![image](https://user-images.githubusercontent.com/15223353/32146096-dd91496a-bcd2-11e7-926c-ad30d64e957a.png)

**Comment by VPeruS** [comment]
And from gnome:
![gnome](https://user-images.githubusercontent.com/7927055/32147123-839b4290-bcea-11e7-82ed-ff0df6454568.png)

**Comment by Nabile-Rahmani** [comment]
Sorry for the delay. I have set up a fresh virtual machine and ran both `xev` and the OpenTK test.
Both yield the same results as my physical machine.

Here's the OpenTK test output (which was a pain to get as VBox lagged to death :p):
![virtualbox_debian_08_11_2017_18_43_35](https://user-images.githubusercontent.com/15223353/32564818-a16bdd5c-c4b5-11e7-9d9f-af69ec3df12a.png)

So I'm guessing something's wrong on the Debian end ?

**Comment by VPeruS** [comment]
It is not necessary Debian problem, try to look which device driver opentk use(Xinput2 or standard). Try to install SDL2 and check what that give

**Comment by VPeruS** [comment]
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/X11/X11Factory.cs#L43 here is method where you can set breakpoint to check.

**Comment by varon** [comment]
Fixed by 4.x
