### ISSUE TITLE
Quaternion * Vector3 is not implemented for double precision

### ISSUE THREAD

**Issue by TheJhonny007** [opentk/opentk#678]
While there is a function for vector rotation with Quaternion and Vector3 there is none for Quaterniond and Vector3d

```C#
//exists
var newVec = new Quaternion() * new Vector3();

//doesn't exist
var newVec = new Quaterniond() * new Vector3d();
```

Version OpenTK 3.0pre

**Comment by ThomasD13** [comment]
As I started to do a quick PR for this, I discovered that this Issue will be fixed with #679. So this issue seems redundant to me.

**Comment by Kavignon** [comment]
Since #679 has been closed, and covers the issue at hand, shouldn't this be close too?

**Comment by VPeruS** [comment]
Closed but not merged ;_;
