### ISSUE TITLE
Using glad to load GL

### ISSUE THREAD

**Issue by pavelkouril** [opentk/opentk#680]
I'm creating a WPF C# editor/debug UI for a native C++ OpenGL renderer, and have trouble setting up the context.

The C++ renderer uses glad for loading the GL functions etc., and I would like to keep it that way, because I also have a "standalone" runner that uses GLFW+glad and is purely in C++; therefore, to have as much logic as possible in the C++ code, I would like to use GLControl purely for the creation of context in my WPF app (by putting it into WindowsFormsHost), and offload everything to the C++ engine.

The setup with GLFW is done using `gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)`, [as shown here](http://www.glfw.org/docs/latest/quick_guide.html#quick_example) - is there any equivalent way for using glad with OpenTK?

(If there is no such thing, please, treat it as a suggestion issue.)

**Comment by Nihlus** [comment]
This is a discussion better suited for the Gitter channel - please ask there.
