### ISSUE TITLE
OpenTK.Input Keyboard.GetState() throws System.ArgumentNullException in Windows

### ISSUE THREAD

**Issue by theWildSushii** [opentk/opentk#683]
### Description

Calling `Keyboard.GetState()` throws `System.ArgumentNullException`
Call stack:
_Note: OS language is Spanish, translation may be wrong_
```
Void Enter(System.Object)
  in System.Threading.Monitor.Enter(Object obj)
  in OpenTK.Input.Keyboard.GetState()
  in _The function below_
  in _GLControl.Paint event_
```

[Repo](https://github.com/DesertHareStudios/Hare-Engine/blob/master/Hare%20Engine/Input.cs)

### Repro steps

1.-
```
private static KeyboardState ks;
private static KeyboardState prevks;

public static void UpdateData() { //Exception point to this function
    prevks = ks;
    ks = Keyboard.GetState(); // Exception points to this line
    ...
}
```

2.- Call `UpdateData()` in `GLControl.Paint` event.

### Expected behavior

Get the state of the keyboard

### Actual behavior
Getting  `System.ArgumentNullException` exception

### Related information 

OS: Windows 10 x64
Native backend
OpenTK v2.0.0 (From NuGet)
Runtime: .NET

**Comment by Nihlus** [comment]
Please try using the latest development release from the myget feed.
