### ISSUE TITLE
OpenTK Crashed On Win10(VirtualBox 5.2.2)

### ISSUE THREAD

**Issue by qingliangcn** [opentk/opentk#684]
### Description

Run UnityStudio, then it crashed, i got this log from system log:

```
应用程序: Unity Studio.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.AccessViolationException
   在 OpenTK.Graphics.OpenGL.GL.CreateProgram()
   在 Unity_Studio.UnityStudioForm.initOpenTK()
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(System.Windows.Forms.Message ByRef)
   在 System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   在 System.Windows.Forms.Form.WmShowWindow(System.Windows.Forms.Message ByRef)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
```

### Repro steps

1. Download UnityStudio 0.8.0 from https://github.com/Perfare/UnityStudio/releases

2. Run UnityStudio 0.8.0 exe

### Expected behavior

The app could start sucessfully.

### Actual behavior

The app crashed.

### Related information 

* Windown 10 64
* Host: Mac 10.13.1
* OpenTK： 2.0
* .NET Framework 4

**Comment by Nihlus** [comment]
Please report this to Unity Studio instead.

**Comment by qingliangcn** [comment]
Unity Studio told me: please report this to OpenTK ......

**Comment by Nihlus** [comment]
This could be due to any number of things, and the version of OpenTK that Unity Studio uses is severely outdated. My guess is that it's due to missing hardware acceleration in VirtualBox.

**Comment by VPeruS** [comment]
But Windows provide some kind of driver for OpenGL(1.1 1.2 versions) and VirtualBox emulate some hardware.
