### ISSUE TITLE
How I can recompile 

### ISSUE THREAD

**Issue by bpocnitura** [opentk/opentk#685]
I want to compile Source into a dll(refence) for my project. But it gives me the errors(this is the log):

`1>------ Build started: Project: OpenTK, Configuration: Release Any CPU ------
2>------ Build started: Project: Generator.Bind, Configuration: Release Any CPU ------
3>------ Build started: Project: Generator.Convert, Configuration: Release Any CPU ------
4>------ Build started: Project: Generator.Rewrite, Configuration: Release Any CPU ------
2>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll' could not be found
2>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.dll' could not be found
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CommandLine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
3>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll' could not be found
3>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.dll' could not be found
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "CommandLine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Mono.Cecil". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Mono.Cecil.Mdb". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Mono.Cecil.Pdb". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Mono.Cecil.Rocks". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
4>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll' could not be found
4>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.dll' could not be found
1>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll' could not be found
1>CSC : error CS0006: Metadata file '..\..\packages\StyleCop.Analyzers\analyzers\dotnet\cs\StyleCop.Analyzers.dll' could not be found
5>------ Build started: Project: OpenTK.GLControl, Configuration: Release Any CPU ------
6>------ Build started: Project: OpenTK.GLWidget, Configuration: Release Any CPU ------
7>------ Build started: Project: Test.API.Desktop, Configuration: Release Any CPU ------
5>CSC : error CS0006: Metadata file 'C:\Users\Fish's computer\Desktop\opentk-develop\src\OpenTK\bin\Release\OpenTK.dll' could not be found
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "cairo-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
6>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1988,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "gio-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
6>CSC : error CS0006: Metadata file 'C:\Users\Fish's computer\Desktop\opentk-develop\src\OpenTK\bin\Release\OpenTK.dll' could not be found
7>CSC : error CS0006: Metadata file 'C:\Users\Fish's computer\Desktop\opentk-develop\src\OpenTK\bin\Release\OpenTK.dll' could not be found
========== Build: 0 succeeded, 7 failed, 0 up-to-date, 0 skipped ==========`

I open it from opentk.sln

**Comment by VPeruS** [comment]
Compile it with build.cmd or build.sh from command line

**Comment by Nihlus** [comment]
As VPerusS said, use the build script at least once. You're missing nuget packages.

**Comment by tzachshabtay** [comment]
@Nihlus just ran into this too. Isn't there a way to fix this so a developer wouldn't have to run the script at least once? It's a barrier of entry for contributing developers.

If not, then at the very least, this should be written as a requirement in the readme (currently this is only mentioned as an alternative build).

**Comment by Nihlus** [comment]
@tzachshabtay I agree, the readme should be updated. The reason the IDE doesn't automatically install the required Nuget packages is that we use Paket.

**Comment by tzachshabtay** [comment]
But isn't there a way to trigger Paket restore (or whatever it's called on Paket) from msbuild?

**Comment by Nihlus** [comment]
Not easily, at least not as far as I know.
