### ISSUE TITLE
Missing enums for anisotropic texture filtering

### ISSUE THREAD

**Issue by xenapior** [opentk/opentk#688]
### Description

OpenTK (3.0.0-pre) does not support texture anisotropic filtering

### Repro steps

In OpenGL 4.6, anisotropic filtering finally became a core feature. However, OpenTK does not include corresponding strings for GL_MAX_TEXTURE_MAX_ANISOTROPY in the GetPName/GetIndexedPName enum as well as for GL_TEXTURE_MAX_ANISOTROPY in the TextureParameterName enum.
btw: AF has been an _EXT feature since OpenGL 1.2 and supported by nearly all graphics cards, but could not become core for patent issues.

### Expected behavior

Features in corresponding enums.

### Actual behavior

No matching enum strings when using GL.GetFloat() for query and GL.TexParameter()/TextureParameter() for setting anisotropic filtering parameter.

### Related information 

* Operating system   Windows 10 x64
* SDL or Native backend  Native
* What version of OpenTK (Installer, NuGet, Source Code)  nuget/3.0.0-pre
* What runtime (.NET Framework, CoreCLR, Mono)     .net framework 4.6.1
* Workarounds (if any)

**Comment by Frassle** [comment]
This is correct per [current Khronos specification](https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/681c365c012ac9d3bcadd67de10af4730eb460e0/xml/gl.xml). GL_MAX_TEXTURE_MAX_ANISOTROPY is not part of the GetPName group, Likewise GL_TEXTURE_MAX_ANISOTROPY is not part of the TextureParameterName group.

You can raise an issue about this on their github repo: https://github.com/KhronosGroup/OpenGL-Registry/issues. If they agree it's incorrect and change it, you can then raise an issue on us to update (although we try to update fairly frequently anyway).

**Comment by Frassle** [comment]
Workaround to use these enums:
You can cast from All.MaxTextureMaxAnisotropy to GetPName
```
GL.GetFloat((GetPName)All.MaxTextureMaxAnisotropy);
```
