### ISSUE TITLE
Multiple GLControl's in one WinForms Application

### ISSUE THREAD

**Issue by ajos6183** [opentk/opentk#689]
### Description

If a form has many `GLControl` controls, only one works as expected. 

### Repro steps

I have created a sample application to demonstrate the problem I am facing. Essentially, i have created a custom `GLContol` that starts with a red background. The background color is changed to green when the control is clicked and back to blue when the click is released.

### Expected behavior

All controls change colors to green when clicked and then back to blue when the click is released.

### Actual behavior

Only one or two controls work, usually the one created last.

### Sample Code

[Test.zip](https://github.com/opentk/opentk/files/1535424/Test.zip)

**Comment by xenapior** [comment]
You probably did not call MakeCurrent() when painting.
OpenGL contexts are thread-bound. All gl* commands are sent to CURRENT context. When one changes to another thread to render a gl context, MakeCurrent() must be called first to all gl* commands to make sure they are issued to the correct thread.

**Comment by ajos6183** [comment]
Thank you so much for your help. Using MakeCurrent() solves my problem.

Also thanks for the extra information. For my usage, I will only be painting one control at a time. So hopefully this means OpenTK is sufficient for my needs.
