### ISSUE TITLE
'if else' vs 'switch' in matrix4d getter/setter

### ISSUE THREAD

**Issue by daerogami** [opentk/opentk#690]
I tried searching past issues and I couldn't find any discussion on this.
I was poking through the math libs while looking into another issue and noticed we are using 'if else' for something that would lend itself much better readability from a switch statement.
Since its less than five items there won't be a performance improvement but maybe this has been discussed in the past and I'm beating a dead horse.

**Comment by wcdeich4** [comment]
Interesting, a lot of code style gurus are now saying not to use switch statements, although I think they're nice as long as it is a clean small block of code, not sprawling over so many lines of code you forget you're inside a switch block.  Of course we have much bigger fish to fry hehe ;)

**Comment by Nihlus** [comment]
I'd say using switch is fine. In almost all cases, the performance benefits are negligible, and a switch is a better-suited construct for long chains of if/else if statements.

**Comment by varon** [comment]
Yeah, I think it's okay to just keep what we have. It's very static code, unlikely to change or need revision in future.
