### ISSUE TITLE
MouseState should include a property differentiating types of movement input

### ISSUE THREAD

**Issue by FreezyLemon** [opentk/opentk#693]
There should at least be a differentiation between absolute and relative movement, so that if an application wants to use raw input data, it can correctly apply it to the screen. Currently, there's no way of telling the difference between a tablet or touchscreen and a mouse on the end-user's side.

I started implementing this but quickly arrived at some problems. I most likely need help with it, especially on how to "read" the current drivers (where is raw input processed? some are easy to understand, others not so much).

**Comment by FreezyLemon** [comment]
Okay, so a ~~little~~ update with some questions regarding this:
1. What types of movement? I initially thought there would only be a differentiation between relative and absolute movement, but I noticed that (at least technically), `XI2MouseKeyboard` supports absolute and relative for each X and Y coords separately. Should this just be overridden in some way ('If one is absolute, both count as absolute'?) or maybe be handled with something like `AbsoluteX` and `AbsoluteY`?
2. It might also be a good idea to have `None` as an option (seems somewhat easily done) since it would prevent end users from unnecessarily checking for position changes when the framework already knows the event only contains a button click or similar. Opinions on this?
3. This is very important: How to handle the merging of mouse states with absolute movement? For relative movement the coordinate and scroll deltas are usually just added up (which works) but what if we have multiple devices and one of them is absolute? Should it override the other two?
And what if there are multiple absolute 'mice'? just use the first one?

My opinion on these so far:
1. This one special case seems so rare (what input device would give relative coordinates on one axis and absolute ones on the other?) that I would suggest just overriding it if one of them is absolute.
2. I think this would be nice to have, but it might be harder to implement than it seems (as in: if the movement type is not explicitly set to anything, it's `None`. this would mean not a single case where movement is conveyed can be missed in the code or something would break -> maintainability?)
3. not completely sure myself, but from a 'user expectation' point of view I would go with 'if one device uses absolute positioning, override the other relative ones'. no clue what to do with the other scenario (multiple absolute).


On a side note:
Since this will affect ~~pretty much~~ all platforms in some way, this will be very hard to test for me personally. How would the testing work in case of a PR?

**Comment by varon** [comment]
It's pretty nightmarish. Any luck @FreezyLemon ?

**Comment by FreezyLemon** [comment]
Well, it's been a while since I had a look at this, but IIRC, it seemed doable.
That said, the questions above still stand, and I don't just want to assume that what I think is correct, so some more input on this would be nice.

**Comment by varon** [comment]
Fixed by 4.x
