### ISSUE TITLE
Game window- add config for separate update thread

### ISSUE THREAD

**Issue by tzachshabtay** [opentk/opentk#694]
### Description

Currently the render event and the update event from the game window are called on the same thread.
I'd like to add a configuration which will allow the update event to be called from a separate thread.
Potential advantages for that approach:
1. It will allow for more utilization of the cpu.
2. It will allow for designing an isolated server-client architecture like Electron or Godot.
3. It might help with responsiveness and various async/await scenarios (the update thread will be able to await rendering events from the render thread or vice versa which isn't easily possible if you only have one synchronization context).

I can work on this if there are no objections (I'll keep it single threaded by default).

**Comment by xenapior** [comment]
Well, maybe a good idea, but actually I don't think an empty UpdateFrame() will take much cpu time provided you limit the update frequency. And if you do have some heavy work on other threads, why not simply use a polling in UpdateFrame()? Also, The GLControl class may be an alternative, too.

**Comment by tzachshabtay** [comment]
> but actually I don't think an empty UpdateFrame() will take much cpu time provided you limit the update frequency.

Not sure I follow: do you mean implement my own update thread and just ignore the UpdateFrame? That's what I'm doing now as a workaround, but that means I have almost identical code to the code that's already in GameWindow, and I'll need to maintain it separately and merge back any fixes or functionality that's being pushed to OpenTK. Also that might cause confusion in the future, as I'll have 2 update events and I ignore one of them.

> And if you do have some heavy work on other threads, why not simply use a polling in UpdateFrame()?

I don't follow.

> Also, The GLControl class may be an alternative, too.

Isn't that for Windows Forms? I don't use Windows Forms and don't want to use it.

**Comment by Frassle** [comment]
This sounds reasonable, and can easily be done in a backward compatible manner. So sure, if you have a use case for it I don't see why not.
