### ISSUE TITLE
Draw 2D Text in 3D space

### ISSUE THREAD

**Issue by ThinkingInXyZ** [opentk/opentk#701]
Hello,

I am sorry if this is not the right place to ask. If so I want to apologize in advance. But I was hopping if anyone could help me on how I can draw 2D text in 3D space, Like using gl.DrawText() together with gl.RasterPos(x, y, z); so then the text is rotating but always facing the camera.

I am trying to achieve something like this:

![axis2](https://user-images.githubusercontent.com/34493970/34380242-ee18f8b6-eaf7-11e7-8a0e-2b1af34c8be6.gif)

Thanks in advance for your help!

Kind Regards
**Ting**

**Comment by Nihlus** [comment]
This is a question better suited for the gitter or Discord chat. Please ask there.

**Comment by tzachshabtay** [comment]
@Nihlus there's a discord? I don't see any mention of it in the readme or the website?

**Comment by Nihlus** [comment]
@tzachshabtay We haven't added it yet, since the bridging application we use to link it with gitter hasn't been very stable. It's working now, though, so we may add it soon. I can send you a link in gitter, if you want.

**Comment by ThinkingInXyZ** [comment]
@Nihlus Thank you a for the info. I didnt know about Discord or Gitter. I am going to join them and look for OpenTK.
