### ISSUE TITLE
Integers Stop Changing Values after WIndow is being Opened

### ISSUE THREAD

**Issue by WhiteRedWolf** [opentk/opentk#724]
While the OpenTK Winow i Open, I need a Counter Integer which needs to Add Every Milisecond 1, And while the Window is Open The Console Just stops Working Which is Not Supposed to Happen. And the Integers Start working after i Close the Window.

It Happens Always when The Window is Being Opened or Is Open.

I expected the Integers to Work in the Background which They DId not.

The Integers Stopped Adding Values or Changing Values in General

Windows 10 Home (64 Bit)
Visual Studio 2017
Installer
.NET Framework

**Comment by WhiteRedWolf** [comment]
Why Closed?

**Comment by Nihlus** [comment]
This is not a support forum for your application's architecture. I
recommend joining the OpenTK or C# discord server for issues that are not
bugs or feature requests.
