### ISSUE TITLE
Long unifrom variable names causes the application to crush

### ISSUE THREAD

**Issue by Omar-Bsoul** [opentk/opentk#726]
### Description

I have noticed that when I use long uniform variable names in the shaders, the application seems to be unstable; such that, it may crush at the start or maybe at the end.
But when replacing the long name with shorter one; the problem solved.
Although the same code(with long variable names) run on C++ without any problem.

### Repro steps

I don't know if my code contains something wrong, if so please correct me.
and here is my code:

`

    public class WindowTest : GameWindow
    {
        private int vbo;
        private int vao;
        private int shaderProgram;
        private string vertexShader;
        private string fragmentShader;
        private Matrix4 transformation;
        private Dictionary<string, int> shaderUniforms;

        public WindowTest() : base(1024, 600)
        {
            Resize += WindowTest_Resize;
            Load += WindowTest_Load;
            RenderFrame += WindowTest_RenderFrame;
            Closing += WindowTest_Closing;
        }

        private void WindowTest_Resize(object sender, EventArgs e)
        {
            GL.Viewport(0, 0, Width, Height);
        }

        private void WindowTest_Load(object sender, EventArgs e)
        {
            InitializeShaderCode();
            InitializeShader();
            InitializeVaoAndVbo();
            transformation = Matrix4.Identity;

            GL.ClearColor(0.0f, 0.0f, 0.0f, 1.0f);
            GL.Enable(EnableCap.DepthTest);
        }

        private void WindowTest_RenderFrame(object sender, FrameEventArgs e)
        {
            GL.Clear(ClearBufferMask.DepthBufferBit | ClearBufferMask.ColorBufferBit);

            GL.UseProgram(shaderProgram);
            GL.UniformMatrix4(shaderUniforms["_transformation_matrix"], false, ref transformation);
            GL.BindVertexArray(vao);
            GL.DrawArrays(PrimitiveType.Triangles, 0, 3);
            GL.BindVertexArray(0);
            GL.UseProgram(0);

            SwapBuffers();
        }

        private void WindowTest_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            GL.DeleteBuffer(vbo);
            GL.DeleteVertexArray(vao);
            GL.DeleteProgram(shaderProgram);
        }

        private void InitializeShaderCode()
        {
            vertexShader = @"
                #version 330 core
                layout (location = 0) in vec3 vPos;
                
                uniform mat4 _transformation_matrix;
                
                void main()
                {
                    gl_Position = _transformation_matrix * vec4(vPos, 1.0);
                }
            ";

            fragmentShader = @"
                #version 330 core
                out vec4 FragColor;
                
                void main()
                {
                    FragColor = vec4(1.0, 0.5, 0.2, 1.0);
                }
            ";

        }

        private void InitializeShader()
        {
            int vs = GL.CreateShader(ShaderType.VertexShader);
            GL.ShaderSource(vs, vertexShader);
            GL.CompileShader(vs);
            GL.GetShader(vs, ShaderParameter.CompileStatus, out int success);

            if (success == 0)
            {
                string infoLog = GL.GetShaderInfoLog(vs);
                GL.DeleteShader(vs);
                Console.WriteLine("ERROR " + ShaderType.VertexShader.ToString() + " COMPILATION_FAILED" + Environment.NewLine + infoLog);
            }

            int fs = GL.CreateShader(ShaderType.FragmentShader);
            GL.ShaderSource(fs, fragmentShader);
            GL.CompileShader(fs);
            GL.GetShader(fs, ShaderParameter.CompileStatus, out success);

            if (success == 0)
            {
                string infoLog = GL.GetShaderInfoLog(fs);
                GL.DeleteShader(fs);
                Console.WriteLine("ERROR " + ShaderType.FragmentShader.ToString() + " COMPILATION_FAILED" + Environment.NewLine + infoLog);
            }

            shaderProgram = GL.CreateProgram();
            GL.AttachShader(shaderProgram, vs);
            GL.AttachShader(shaderProgram, fs);
            GL.LinkProgram(shaderProgram);

            GL.GetProgram(shaderProgram, GetProgramParameterName.LinkStatus, out success);
            if (success == 0)
            {
                string infoLog = GL.GetProgramInfoLog(shaderProgram);
                GL.DetachShader(shaderProgram, vs);
                GL.DetachShader(shaderProgram, fs);
                GL.DeleteShader(vs);
                GL.DeleteShader(fs);
                GL.DeleteProgram(shaderProgram);
                Console.WriteLine("ERROR SHADER PROGRAM LINKING_FAILED" + Environment.NewLine + infoLog);
            }

            GL.DetachShader(shaderProgram, vs);
            GL.DetachShader(shaderProgram, fs);
            GL.DeleteShader(vs);
            GL.DeleteShader(fs);

            shaderUniforms = new Dictionary<string, int>();

            GL.GetProgram(shaderProgram, GetProgramParameterName.ActiveUniforms, out int uniformCount);

            for (int i = 0; i < uniformCount; i++)
            {
                int unifromAddress;
                StringBuilder name = new StringBuilder();
                GL.GetActiveUniform(shaderProgram, i, 256, out int length, out int size, out ActiveUniformType type, name);

                unifromAddress = GL.GetUniformLocation(shaderProgram, name.ToString());
                shaderUniforms.Add(name.ToString(), unifromAddress);
            }
        }

        private void InitializeVaoAndVbo()
        {
            float[] vertices = {
                -0.5f, -0.5f, 0.0f,
                 0.5f, -0.5f, 0.0f,
                 0.0f,  0.5f, 0.0f
            };
            vao = GL.GenVertexArray();
            vbo = GL.GenBuffer();
            GL.BindVertexArray(vao);
            GL.BindBuffer(BufferTarget.ArrayBuffer, vbo);
            GL.BufferData(BufferTarget.ArrayBuffer, vertices.Length * sizeof(float), vertices, BufferUsageHint.StaticDraw);
            GL.VertexAttribPointer(0, 3, VertexAttribPointerType.Float, false, 3 * sizeof(float), 0);
            GL.EnableVertexAttribArray(0);
            GL.BindVertexArray(0);
        }

        static void Main()
        {
            using (WindowTest window = new WindowTest())
            {
                window.Run();
            }
        }
    }

`

### Expected behavior

![image](https://user-images.githubusercontent.com/29519391/35228037-5c52c96a-ff98-11e7-9208-f967b8f50903.png)

![image](https://user-images.githubusercontent.com/29519391/35227923-19b84594-ff98-11e7-9df9-bae9ed8c4565.png)

### Related information 

* Windows 10 Pro N 64-bit (10.0, Build 16299)
* GPU Intel(R) HD Graphics 3000
* NuGet, OpenTK 3.0.0-pre
* .NET Framework 4.6.2

**Comment by Nihlus** [comment]
This sounds like a driver issue. Can you reproduce the problem on other graphics hardware?

**Comment by Omar-Bsoul** [comment]
Actually, I don't have any other graphics hardware.
And I have forgot to mention that, it works perfectly on C++ OpenGL.

**Comment by UnknownShadow200** [comment]
I recall in the past there being an issue with passing StringBuilder into functions which have a capacity  different to the buffer size argument (see issue #515)
```
StringBuilder name = new StringBuilder();
GL.GetActiveUniform(shaderProgram, i, 256, out int length, out int size, out ActiveUniformType type, name);
```

What happens if you change to:
```
StringBuilder name = new StringBuilder(256);
GL.GetActiveUniform(shaderProgram, i, name.Capacity, out int length, out int size, out ActiveUniformType type, name);
```

**Comment by Omar-Bsoul** [comment]
Thank you that completely solved the problem.

**Comment by Omar-Bsoul** [comment]
Thank you that completely solved the problem.

**Comment by Frassle** [comment]
The latest version of OpenTK no longer uses StringBuilders so this bug should be impossible to hit now.
