### ISSUE TITLE
Serious mouse issues with X11

### ISSUE THREAD

**Issue by copygirl** [opentk/opentk#727]
### Description
There's a bunch of issues I keep running into, so I've created a project just to find out all the quirks. I know there may already some open issue on this, but perhaps it's useful to keep my observations and the questions I have separate..?

It's impossible to write a game with `CursorVisible` due to the large amount of strange behavior, having to resort to setting the cursor to `MouseCursor.Empty`.

### Repro steps
See my [opentk-mouse-issue](https://github.com/copygirl/opentk-mouse-issue) repository for code.

### Observed incorrect behavior
- `Mouse.GetState()` and `Mouse.GetCursorState()` (when updated to be relative to window) don't align at all. The mouse appears to only get updated with relative movement delta as long as the cursor is over the window.
- If `CursorVisible` is `false`, `Mouse.SetPosition()` doesn't cause mouse state or `MouseMove` position to update.
- When `CursorVisible` is set back to `true`, the cursor will jump back to the position where it was hidden (last known position?).
- Regardless of `CursorVisible`, holding down any mouse button will restrict the mouse to the window bounds.
- When moving the mouse against the window bounds and reported mouse position doesn't change,  `MouseMove` isn't fired.
- Oddly enough, in the above case, when `CursorVisible` is `false`, the mouse state will still be updated, and it's possible to drag it to ridiculous values such as `-10000,20000`.

### Expected behavior
That is the question. What even **is** the expected behavior?

I'm thinking of fixing this in a PR myself, but I'd first have to know about this.

### Information
- **OS:** Arch Linux
- **OpenTK:** `3.0.0-git00038`
- **Runtime:** Mono `5.4.1.7`

**Comment by VPeruS** [comment]
Take a look at pr 589, maybe some issues will be fixed or you will find more.

**Comment by Frassle** [comment]
As @VPeruS said, checkout #589 for a first pass at sanitising the behaviours here.
Most platform APIs distinguish between cursor visible and cursor confined (e.g. WIN32 has ShowCursor and ClipCursor).

If we can add that support I'd hope that makes some behaviours more sensible. There would still be an oddity of the difference between setting the cursor to be invisible vs setting its image to be empty.
There's also the question of if OpenTK should handle some management of the cursor state automatically (like restoring the system cursor when the mouse moves outside the window).

There's also the legacy problem of us having at least three different ways to get mouse state (MouseMove events, the windows MouseDevice, the global Mouse object), which probably aren't consistent (and given deprecation maybe shouldn't be).

If you want to help with this picking up #589 would be a good start (I'm inclined to commit the API changes to develop and leave the platforms un-implemented so at least it's easier for people to help with just one platform)

**Comment by copygirl** [comment]
Closing in favor of #589. Will PR some changes to the PR branch itself.
