### ISSUE TITLE
SDL2 backend eats input event exceptions

### ISSUE THREAD

**Issue by jealouscloud** [opentk/opentk#735]
### Description

When an unhandled exception occurs in the body of an input event handler, the SDL2 nativewindow catches it silently without any notification.

Changing backends to X11 or windows by hiding sdl2 causes exceptions to be thrown normally.

### Reproduction
Example code:
```        
class window : GameWindow
{
    public window() : base(300, 300) { }
    protected override void OnKeyDown(OpenTK.Input.KeyboardKeyEventArgs e)
    {
        throw new Exception();
    }
    protected override void OnMouseMove(OpenTK.Input.MouseMoveEventArgs e)
    {
        throw new Exception();
    }
    protected override void OnMouseDown(OpenTK.Input.MouseButtonEventArgs e)
    {
        throw new Exception();
    }
    public static void Main(string[] args)
    {
        new window().Run();
    }
}
```
Run with the SDL2 backend and the example events will not hinder execution of the application.

### Expected behavior

Unhandled exceptions by the user to not magically disappear, crash the application and hit the AppDomain.UnhandledException event, if applicable.

### Actual behavior

Exceptions are secretly thrown away without notification to the developer or user

### Related information 

* Arch Linux
* SDL or Native backend
* OpenTK 2.0, though it appears in the current develop.
* Workarounds: Catch all exceptions in every input event and close the window if an input event has an unhandled exception.

Tracing backwards, this is where the issue occurs:
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/SDL2/Sdl2NativeWindow.cs#L219

**Comment by VPeruS** [comment]
Remove catch
