### ISSUE TITLE
OpenTK.Graphics.GraphicsModeException: Requested GraphicsMode not available.

### ISSUE THREAD

**Issue by theluckyone17** [opentk/opentk#736]
### Description
When launching [VintageStory](https://vintagestory.at), an error is thrown: "OpenTK.Graphics.GraphicsModeException: Requested GraphicsMode not available." The game then fails to launch.

### Repro steps

Please provide the steps required to reproduce the problem

1. Install Vintage Story.

2. Run it via **mono Vintagestory.exe**

### Expected behavior

The application to launch and run normally.

### Actual behavior
The referenced error is thrown and the application crashes.

### Related information 

* O/S: Gentoo AMD64 (rolling release, updated this week)
* SDL or Native backend: Not sure.
* What version of OpenTK (Installer, NuGet, Source Code): Not sure.
* What runtime (.NET Framework, CoreCLR, Mono): Mono 5.8.0.22. Have also attempted 5.4.1.6, 4.4.1.0
* Workarounds (if any): Application launches and shows logon window if opened via wine (vanilla 2.0.3) using wine-mono-4.6.4.
* Video card: NVidia GeForce GTX 970 (correction: 980) Ti; NVidia proprietary drivers version 390.25 (also tested with 384.90)

Full error: See attached

**Comment by theluckyone17** [comment]
[Error.dos.txt](https://github.com/opentk/opentk/files/1769364/Error.dos.txt)
[Error.linux.txt](https://github.com/opentk/opentk/files/1769365/Error.linux.txt)

**Comment by theluckyone17** [comment]
Should also note that glxgears runs normally, as does X-Plane 11.

**Comment by VPeruS** [comment]
I bet your driver didn't loaded correctly, search for GL errors from logs

**Comment by theluckyone17** [comment]
Output of **dmesg | grep -i nvidia**:
[nvidia.txt](https://github.com/opentk/opentk/files/1769478/nvidia.txt)

And **glxinfo**:
[glxinfo.txt](https://github.com/opentk/opentk/files/1769479/glxinfo.txt)

Any other logs that might be pertinent?

**Comment by tyronx** [comment]
For completeness sake, this is the graphics mode request in VS that I presume, fails:

`GraphicsMode mode = new GraphicsMode(OpenTK.DisplayDevice.Default.BitsPerPixel, 24);`

**Comment by winterhell** [comment]
Does this game have a free demo we can try?

**Comment by theluckyone17** [comment]
If TyronX isn't able to work something out, I'd be happy to gift a license.

**Comment by VPeruS** [comment]
Did you post problem on their forum?

**Comment by tyronx** [comment]
Well, you don't really need a game account to get to the error. If you can get to the login screen then the graphics mode acquisition was already successful. Here's the full release for linux: https://account.vintagestory.at/files/stable/vs_archive_1.5.1.5.tar.gz

**Comment by VPeruS** [comment]
![mar02 014440](https://user-images.githubusercontent.com/7927055/36876033-9f37ed3c-1dbb-11e8-835f-58091180f5c0.png)

**Comment by VPeruS** [comment]
Try use nouveau

**Comment by theluckyone17** [comment]
Recompiled the kernel, building the nouveau driver as a module (leaving the pre-existing kernel available for the nvidia blob per [the Gentoo guide](https://wiki.gentoo.org/wiki/Nouveau_%26_nvidia-drivers_switching)). Using the Gallium mesa driver, I'm able to launch VintageStory without issue. No go with the NVidia driver, however.

**Comment by Nihlus** [comment]
NVIDIA's drivers are notorious for having issues... see #366, #464 etc
I suggest looking into the way the buffers are set up and which attributes are passed to the NVIDIA drivers. See if you can get other permutations working.

**Comment by VPeruS** [comment]
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Graphics/GraphicsMode.cs#L189. I think there should be possibility to query availiable Modes(don't see any function that can return list).

**Comment by varon** [comment]
Seems like an application error. please re-open if it's still affecting you.
