### ISSUE TITLE
Linux X11 crash while creating window

### ISSUE THREAD

**Issue by zbendefy** [opentk/opentk#740]
### Description
 
On Linux Mint 18.3 64bit, creating a window crashes with the following error:

> Exception has occurred: CLR/System.Runtime.InteropServices.MarshalDirectiveException
> An unhandled exception of type 'System.Runtime.InteropServices.MarshalDirectiveException' occurred in OpenTK.dll: 'Cannot marshal 'parameter #12': Unknown error.'
>    at OpenTK.Platform.X11.Functions.XCreateWindow(IntPtr display, IntPtr parent, Int32 x, Int32 y, Int32 width, Int32 height, Int32 border_width, Int32 depth, Int32 xclass, IntPtr visual, IntPtr valuemask, XSetWindowAttributes* attributes)
>    at OpenTK.Platform.X11.X11GLNative..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
>    at OpenTK.Platform.X11.X11Factory.CreateNativeWindow(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
>    at OpenTK.NativeWindow..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
>    at OpenTK.NativeWindow..ctor(Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
>    at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext)
>    at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title)
>    at StarterKit.Game..ctor() in /home/zoltan/dev/monoengine/Program.cs:line 46
>    at StarterKit.Game.Main() in /home/zoltan/dev/monoengine/Program.cs:line 105

### Repro steps

I was running this example: https://gist.githubusercontent.com/ashwin/5727049/raw/72bfd67dcaed554190d3bbfc2ad0e7ffb51c7f1c/OpenTKExample.cs

I added OpenTK via NuGet manager like this:

>  <PackageReference Include="OpenTK" Version="3.0.0-pre"/>

OS: Linux Mint 18.3 64bit Cinnamon
IDE: VSCode 1.20.1
.NET runtime: mono

**Comment by VPeruS** [comment]
What is output of mono -V?

**Comment by zbendefy** [comment]
mono -V displays:

> Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           __thread
> 	SIGSEGV:       altstack
> 	Notifications: epoll
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug 
> 	LLVM:          supported, not enabled.
> 	GC:            sgen
>

**Comment by VPeruS** [comment]
Try update your mono, it may solve problem, as it cannot use TypeName* as argument type in interop.

**Comment by zbendefy** [comment]
the problem might be that I'm using .net core. I'll  try to switch to regular .net of mono
Here's my full .vcsproj btw.:
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="3.0.0-pre"/>
  </ItemGroup>
</Project>

**Comment by VPeruS** [comment]
data is a little bit broken, try github gist

**Comment by zbendefy** [comment]
sorry about that, I updated my previous post.

**Comment by zbendefy** [comment]
I found the solution. As I'm using .net core, i must use the OpenTK .netcore package from nuget. It works now. 

`
    <PackageReference Include="OpenTK.NETCore" Version="*"/>`

**Comment by VPeruS** [comment]
;) didn't do much, don't forget to close issue
