### ISSUE TITLE
GLWidget with wrong Widget GLArea! Please change to DrawingArea!

### ISSUE THREAD

**Issue by sourceskyboxer** [opentk/opentk#741]
Exception with bad Widget GLArea!
Exception thrown at 0x00000000 in PowerEditor.exe: 0xC0000005: Access violation executing location 0x00000000.

Please change to DrawingArea.

Because I am using OpenTK C# and Gtk Sharp 3 and gtk 3.x libs from C:\msys64\mingw32\bin I am using Windows 10 Pro x64

Why do I need stupid error with access violation executing location.

GL.ClearColor(Color4) is really sensitive to GLArea - Please use DrawingArea of Gtk Thanks!

**Comment by Nihlus** [comment]
We cannot use Gtk's DrawingArea to acquire an OpenGL context that works properly with modern versions of Gtk. GLArea is the recommended (and the only supported) widget for use with OpenGL drawing in Gtk 3.

**Comment by sourceskyboxer** [comment]
But for me why does it not work?

GLArea is really shit because it throws error: I prove you.
![error_gl_from_glarea_with_msys2](https://user-images.githubusercontent.com/3496136/37374753-e7335b84-271c-11e8-9cd3-1db0a31a8483.PNG)

You know I am using Gtk 3 Runtime from msys64/mingw32/bin/*.dll all are installed by pacman but it throws error why?

**Comment by Nihlus** [comment]
Your Gtk version may not be recent enough. GLArea was added in Gtk 3.16. The error in question doesn't look like it's because of GLArea - ensure that you are using the latest version of OpenTK.

**Comment by sourceskyboxer** [comment]
Hello I already downloaded OpenTK Preview 3.00 from Nuget Server.
But I am using Gtk Sharp 3.22.6.4

**Comment by Nihlus** [comment]
That is an old version of OpenTK. If you are using the GLArea-based widget, you need to use the package from MyGet. If you are not using the package from MyGet, you are using the old version of GLWidget that does use DrawingArea.

**Comment by sourceskyboxer** [comment]
Ah okay thank you for help now. I have downloaded source from OpenTK's github and I tried. Wow it works fine 100 %. I didn't know before why does old version of OpenTK not remove from Nuget. PS: I am feelling not okay because they scam to stupid users since old version on nuget server. I wish you have to information to Github

OpenTK latest version is here.
OpenTK from nuget server is old version and do not use nuget server!

**Comment by sourceskyboxer** [comment]
And I have problem with SizeAllocated:

![image](https://user-images.githubusercontent.com/3496136/37398877-27d5d870-2780-11e8-8277-1e922a26adc0.png)

```
private void glSizeAllocatedHandler(object o, SizeAllocatedArgs args)
        {
            GL.Viewport(0, 0, args.Allocation.Width, args.Allocation.Height);
        }
```
You know OpenGL.net has not problem with SizeAllocated if you GLWidget resizes if you start gtk application with viewport and viewport should resize.

But I already tried newest version of OpenTK but it won't work because access violation argues my gtk application.

**Comment by sourceskyboxer** [comment]
And @Nihlus where is fix OpenTK for SizeAllocated ?

Check my full code - If you have got exception "**Access violation executing location**"

And do you have to fix bug from OpenTK ( I use latest version of OpenTK from yesterday - I have downloaded and compiled into ssemblies )

Still I have exception from OPenTK yet...

**Comment by sourceskyboxer** [comment]
@varon  Did you reproduce it? Because it is buggy SizeAllocate if you use GL.Viewport();

**Comment by sourceskyboxer** [comment]
No suggestion for dynamic loading at start of application??????

I wait longer...... Grrr Does OpenTK have bugs? With Gtk Sharp 3 events.
Actived - working - but it doesn't see - if GL.Viewport() doesn't make...
ConfigureEvent - Crashed = Access violation
Shown - Crashed = Access violation
SizeAllocated - Crashed = Access violation
Other events - Sometimes crashed = Access violation

Too many Access violations :( It looks like before old version but now new version but it has same problem.....
