### ISSUE TITLE
Accessing the accumulation API

### ISSUE THREAD

**Issue by Unknown6656** [opentk/opentk#742]
I would like to access the accumulation buffer in order to render some depth of field, however I was unable to find out how to access it in OpenTK (e.g. the native method `glAccum(...)` has no OpenTK equivalent).

Could someone maybe give me a pointer concerning the handling of the accumulation buffer?
If no accumulation buffer support should exist in the current API's iteration, would it be possible to access the appropriate functions using P/Invoke calls to the OpenGL-Libraries?

Thank you.

-------------
_Edit: I am using OpenTK v.2.0 with OpenGL v. 4.6_

_Edit №2: When my university exams are over - I can of course contribute to this repository in order to add the missing functions should they not exist._

**Comment by Nihlus** [comment]
OpenTK 2.0 is deprecated, and we do not provide support for it. Use the latest development version from MyGet.

**Comment by Unknown6656** [comment]
OK - Thank you for the information.
I shall close this issue.
