### ISSUE TITLE
System.DllNotFoundException: openal32.dll on Mac

### ISSUE THREAD

**Issue by joshwyant** [opentk/opentk#745]
### Description

Can't load OpenAL on Mac when instantiating AudioContext

### Repro steps

1. instantiate AudioContext

### Expected behavior

I shouldn't get an exception. I also tried getting it to work by manually creating an OpenTK.dll.config, but I think that's only for Mono.

### Actual behavior

`Unhandled Exception: System.DllNotFoundException: openal32.dll
   at OpenTK.Audio.AudioContext.CreateContext(String device, Int32 freq, Int32 refresh, Boolean sync, Boolean enableEfx, MaxAuxiliarySends efxAuxiliarySends)
   at OpenTK.Audio.AudioContext..ctor()
...
`

### Related information 

* Mac OS X High Sierra
* Nuget 3.0.0-pre
* dotnet standard 2.0
* no workarounds

**Comment by VPeruS** [comment]
You have openal installed?

**Comment by joshwyant** [comment]
Sorry, I didn't see your comment. No, Mac has OpenAL already installed.

**Comment by VPeruS** [comment]
As far as I know every dotnet standart application must resolve native deps by itself as well as provide them. As workaround try to put .dylib where your .exe file placed and name it openal32.dll
