### ISSUE TITLE
High DPI support doesn't seem to be per monitor

### ISSUE THREAD

**Issue by tiffany352** [opentk/opentk#746]
### Description

When I use EnableHighResolution, I notice that the values are correctly scaled for one monitor, but when I drag the window to another monitor with a different DPI scaling factor, the resolution doesn't change. The application appears to just use the DPI scaling factor of whatever monitor it was first created on. Windows then seems to scale the application to the correct scale for that monitor.

I might be doing something wrong, but it isn't obvious what.

### Repro steps

1. Make an OpenTK app that prints GameWindow.ClientSize every time it changes. Make it use the default window size of 640x480.
2. Have a dual monitor setup, with the primary monitor set to 1.25x scaling, and a secondary monitor set to 2x scaling. (In my case, a 1440p and a 4k monitor).
3. Open the application. It will appear on the primary monitor with a reported ClientSize of 800x600 ( = 640x480 * 1.25).
4. Move the window to the second monitor.
5. It does not resize. It should resize to 1280x960 ( = 640x480 * 2.0), but it instead stays 800x600.
6. Maximize the window. It should resize to a number whose width is a few pixels shy of 3840 ( = 1920 * 2.0) (on a 4k monitor anyway), but it instead resizes (in my case) to 2400x1271 ( = 1920x1080 * 1.25).

### Expected behavior

It should resize based on the current monitor, like other applications do.

### Actual behavior

Scaling artifacts, like this (nearest neighbor upscaled 5x for clarity):

![image](https://user-images.githubusercontent.com/1254344/37880299-d370ab52-303a-11e8-86cb-77e9cc8c9062.png)

### Related information 

* Windows 10
* Native backend
* NuGet package (OpenTK.NETCore, 1.1.2749.6433)
* .NET Core, Visual Studio 2017

**Comment by UnknownShadow200** [comment]
Possible fix is using `SetProcessDpiAwareness` with 'PROCESS_PER_MONITOR_DPI_AWARE' instead of `SetProcessDPIAware` for windows  10 (OpenTK/Platform/Windows/WinFactory.cs line 64)

**Comment by varon** [comment]
Fixed by 4.x
