### ISSUE TITLE
Mac- pressing a modifier key sends event for the second modifier as well

### ISSUE THREAD

**Issue by tzachshabtay** [opentk/opentk#747]
### Description

Press the left alt key -> key down event is fired for both left and right alt keys. Same goes for shift & ctrl keys.

### Repro steps

```csharp

GameWindow gameWindow = new GameWindow();
gameWindow.KeyDown += (sender, e) =>
{
      Debug.WriteLine(e.Key);
}

```

Run this from a mac, press the left alt key.

### Expected behavior

Only the left alt key down event should be fired.

### Actual behavior

Both left alt key and right alt key events are fired.

### Related information 

* Operating system: MacOS
Darwin
    17.3.0
    Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
    x86_64
* SDL or Native backend: Native (Using HIDInput.)
* What version of OpenTK (Installer, NuGet, Source Code): Source code
* What runtime (.NET Framework, CoreCLR, Mono): Mono
* Workarounds (if any): None

**Comment by tyronx** [comment]
I can reproduce this issue as well

**Comment by leezer3** [comment]
We're catching the global shift / alt modifer, not the key specific one.
https://github.com/opentk/opentk/blob/develop/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L595

We would I think need to update the NSEventModiferMask enum to include the values for the specific keys.
Might also require some hacking in the calling function, as it then pushes back to a NativeWindow function we probably shouldn't be messing with on a platform specific basis.

I can't find a decent source for them off the top of my head though for these values :/
Best I can currently do is here:
https://stackoverflow.com/questions/10715910/is-there-a-way-to-differentiate-between-left-and-right-shift-keys-being-pressed#comment13919442_10716369

Haven't downloaded or tried this one, but might want merging with this PR to slightly rehack the entire modifier function:
https://github.com/opentk/opentk/pull/759

**Comment by varon** [comment]
Fixed by 4.x
