### ISSUE TITLE
Bind.exe can't generate bindings for es20

### ISSUE THREAD

**Issue by CleiK** [opentk/opentk#748]
### Description

Can't build OpenTK because the binding generator fails on es20.

### Repro steps

1. Clone OpenTK in Visual Studio 2017

2. Run build.cmd

3. Try bind.exe -mode:es20

### Expected behavior

OpenTK should be compiled

### Actual behavior

build.cmd fails while trying to retrieve ES20.cs
![opentk_issue_2](https://user-images.githubusercontent.com/29407538/38755791-563140de-3f67-11e8-882d-55d20f270d21.PNG)

bind.exe fails on parsing string to number (apiversion)
![opentk_issue_1](https://user-images.githubusercontent.com/29407538/38755790-55fa8850-3f67-11e8-9946-6b5f16018c20.PNG)

### Related information 

* Operating system: Windows 10 64 bits
* What version of OpenTK (Installer, NuGet, Source Code) Source code version 3.0.0-pre
* What runtime (.NET Framework, CoreCLR, Mono) .NET Framework 4.6.1

**Comment by Nihlus** [comment]
You should not need to run the binder yourself. It runs as a part of the build process. Is this the latest source from git?

**Comment by CleiK** [comment]
Hi, I first used build.cmd but I was trying to find the problem and it looks like it's coming from Bind.exe. I'm using the latest source from git.
