### ISSUE TITLE
OpenAL second offset is only applied when set after AL.SourcePlay()

### ISSUE THREAD

**Issue by NathanielGlover** [opentk/opentk#753]
### Description

Setting the OpenAL source parameter for playback offset (to start playing a sound a few seconds in, as opposed to starting at the beginning) using AL.Source(source, ALSourcef.SecOffset, time) while the sound is not playing should affect the next call to AL.SourcePlay(source), but it doesn't.

### Repro steps

Please provide the steps required to reproduce the problem

1. Initialize OpenTK

2. Set up a valid OpenAL device and context

3. Load sound data into a buffer, and bind it to an OpenAL source

4. Use AL.Source(source, ALSourcef.SecOffset, time) to set a nonzero time at which the next call to AL.SourcePlay(source) will begin playing the sound at

5. Call AL.SourcePlay(source) and observe that the previous step has been undone

### Expected behavior

When AL.Source(source, ALSourcef.SecOffset, 20.5f), for example, is run while AL.GetSourceState(source) does not return ALSourceState.Playing or ALSourceState.Paused, the next call to AL.SourcePlay(source) should begin playing 20.5 seconds into the sound. This behavior is outlined in the [OpenAL 1.1 Specifications](https://www.openal.org/documentation/openal-1.1-specification.pdf) on page 39.

### Actual behavior

After setting the second offset with AL.Source(source, ALSourcef.SecOffset, 20.5f) while the source is not in ALSourceState.Playing or ALSourceState.Paused states, the next call to AL.SourcePlay(source) resets the second offset to 0 and then plays the sound from the beginning. The only way to get a sound to start at any time other than 0 seconds is to call AL.Source(source, ALSourcef.SecOffset, time) after calling AL.SourcePlay(source).

### Related information 

* macOS High Sierra
* Native backend
* NuGet version of OpenTK
* Mono
* Workaround: Set the offset time after calling AL.SourcePlay(). This is an easy fix, but I figured I'd mention this issue because it is not consistent with the OpenAL 1.1 specifications

**Comment by winterhell** [comment]
Could this be a bug in the actual OpenAL backend?

**Comment by Nihlus** [comment]
Yeah, we're not doing anything except providing direct bindings and some utility functions. Not a bug on our end.
