### ISSUE TITLE
Use .NET Core hardware intrinsics to improve math performance?

### ISSUE THREAD

**Issue by Krakean** [opentk/opentk#755]
Hello.
Recently .NET Core (2.1) enabled hardware intrinsics to generate SIMD instructions from SSE to AVX2. And more instructions are added into the .NET Core API interface. The instruction list can be found at https://github.com/dotnet/coreclr/blob/master/src/jit/hwintrinsiclistxarch.h.

Is it feasible to use .NET Core hardware intrinsics to rewrite some math functions so that the performance could be improved by SIMD instructions? Have you any plans on that?

**Comment by FreezyLemon** [comment]
Honestly, I think this should definitely be in the first .NET Standard release of OpenTK.
.NET Core currently (I think even since 1.0) has had SIMD support for Vectors (RyuJIT implemented it somewhere along the way), so it might make sense to replace the OpenTK Vector (and maybe other numeric types) by the .NET Core/Standard implementations when that time comes.

**Comment by MutterOberin** [comment]
I think this would be a big improvement. As a quick test I did some simple benchmark comparing System.Numerics.Vector4 with OpenTK.Vector4 in both debug and release. My results are here:

// 100.000.000 Vector4 Add Operations with Random Values

1) OpenTK Vector4 Debug

01:00:  Test Result     (Time: 00:00:02.05)
01:00:  Test Result     (Time: 00:00:02.00)
01:00:  Test Result     (Time: 00:00:01.96)

2) OpenTK Vector4 Release

01:01:  Test Result     (Time: 00:00:01.24)
01:01:  Test Result     (Time: 00:00:01.26)
01:01:  Test Result     (Time: 00:00:01.21)

3) System Numerics Vector4 Debug

01:10:  Test Result     (Time: 00:00:00.78)
01:11:  Test Result     (Time: 00:00:00.79)
01:11:  Test Result     (Time: 00:00:00.80)

4) System Numerics Vector4 Release

01:12:  Test Result     (Time: 00:00:00.68)
01:12:  Test Result     (Time: 00:00:00.68)
01:12:  Test Result     (Time: 00:00:00.67)

**Comment by peppy** [comment]
Regardless of performance, using the new data types is a huge win in terms of reducing local implementation complexity 👍

**Comment by varon** [comment]
This would be great to do, but without extra from someone who can champion it, It should come as a slightly lower priority than the existing 4.0 goals (perhaps for 5.0?) in terms of where we're directing our efforts at the moment.

**Comment by Nihlus** [comment]
Agreed, although I'd like to aim for 4.0.

**Comment by DylanFPS** [comment]
> perhaps for 5.0
We need to stop bumping that major number and use SemVer i.e. 4.1, 4.2.

> using the new data types is a huge win in terms of reducing local implementation complexity
I agree that the built in types are brilliant, but they're currently only single-precision, so we should put off implementing them for now. See dotnet/corefx#25334 for more.

**Comment by Perksey** [comment]
We had a discussion in Discord yesterday regarding this, and we have decided that in 4.0 we will provide overloads for the System.Numerics.Vectors types in addition to the vector types provided by OpenTK.Math.

**Comment by varon** [comment]
*try to.
We'll probably need some help getting a PR together for this.

**Comment by MutterOberin** [comment]
I would offer my help for doing that but I can't promise anything since time is always an issue.

**Comment by Perksey** [comment]
That's fine, we need to get #871 and #864 merged first.

**Comment by Perksey** [comment]
Another update: We've recently acquired [MathSharp](https://github.com/opentk/MathSharp) - a WIP library which offers hardware-accelerated math ops using intrinsics. MathSharp has its own vector types but also includes support for other popular options such as the types in OpenTK.Math and System.Numerics.Vectors. I'm pretty sure @johnkellyoxford has some benchmarks to hand regarding the massive speed boost that MathSharp provides. At some point in the 4.0 development cycle, we will introduce these extension packages:

* OpenToolkit.Math.Extensions.Intrinsics - includes extension methods which use intrinsics for OpenTK.Math vector operations. These extension methods will be identical to the ones OpenTK already provides, but with a suffix. This will need to be championed by someone.
* OpenToolkit.OpenGL*.Extensions.Intrinsics - includes overloads for MathSharp's vector types.

**Comment by Kavignon** [comment]
What needs to be done in here?

**Comment by varon** [comment]
This needs a champion. Someone that can work with MathSharp to get this integrated. Having the new bindings generator is a huge help towards this.

**Comment by Kavignon** [comment]
Can F# be considered here as well? 😏

**Comment by varon** [comment]
Well; the major point is we need to use the math library types in the function signatures we're generating. With the new binder it's definitely going to involve some F#.

**Comment by Kavignon** [comment]
What would this involve? how big would this be likely to be? I’d like to make sure I understand the scope before jumping into something

**Comment by varon** [comment]
More than anything we'd need someone to champion the entire process - we'd love for this to be included if you're willing to take this on. As a starting point, we'd need to do the following steps:

1) Review MathSharp.Net's API surface and compare it to our current one.
2) Document or add any major omissions.
3) Update the brand new shiny binder to work with the MathSharp types.
4) Migrate the internal OpenTK code to use the new math types (windowing, input etc)
5) Remove the old math library.

The most likely error we'll hit is a lack of parity for the more esoteric types (int vectors, half, etc). If these are missing, these will likely need to be contributed to MathSharp or the existing ones from OpenTK used.

Some mentions: @realvictorprm @john-h-k

**Comment by realvictorprm** [comment]
I think I can pair with @John-h-k and @kavignon on this with me adjusting the binder.

**Comment by Kavignon** [comment]
I’ll start with step 1 & 2. 
When we say document, do we mean a GitHub page ?

When a type is missing, am I the one in charge of updating MathSharp so we can use it here or do I create the missing type in OpenTK?

I’ve not look at the code yet, so maybe what I’ll say is incorrect. For documentation, I’m thinking of adding DocFX on top this repo plus the repo of MathSharband quickly compare the diff from the math library perspective. How does that sound?

**Comment by varon** [comment]
This would be an amazing contribution to OpenTK. Absolutely awesome that you're jumping in on this. 

3.0 (and 4.0 presently) has a very comprehensive math library, but it's written entirely in managed code.  The broad goal is to replace as much as possible with MathSharp (which is orders of magnitude faster)

If a type isn't yet available in MathSharp, we have two choices:
1) either implement it ourselves in MathSharp
1) continue using our current managed types


I believe we have DocFX somewhere doing something on the website side of things. You might want to [check the website repo](https://github.com/opentk/opentk.net) for that. 
As for where you document the general API differences; just about anything is fine. Let's keep it super simple and start with a Gist. Can always move it over to a wiki page later on.

**Comment by john-h-k** [comment]
MathSharp has a slightly different style to the current OpenTK Math library, which allows it to be significantly faster. Instead of using your `Vector3` type everywhere, it distinguishes between storage and operation types. Storage types like `Vector3, Matrix2x4, Vector2`, etc, are used as your fields and sometimes arguments. You then transform these types into the operational types, like `Vector128<float>, MatrixSingle, Vector256<double>` etc using the included conversion extension methods, and operate on them, before returning them to their storage type.
(this code is random, might not make any application sense)
E.g:
```cs
public struct World
{
    public Vector3 DefaultView;
}


Vector3 NormalizeViewAndSquare(World w)
{
    Vector128<float> vec = w.DefaultView.Load();
    vec = Vector.Normalize(vec);
    vec = Vector.Multiply(vec, vec);
    Vector3 v;
    vec.Store(out v);
    return v;0
} ```

**Comment by Kavignon** [comment]
@varon You mentioned starting with a gist, but isn't those only for source code?
I've checked the website and found the API documentation for the math structures of OpenTK. I guess can start by making a PR to MathSharp to support DocFX so we can see what we're dealing with. 

As for the differences, for me, it feels more natural to create a new Page directly on the repo and link it to the PR I'll make for this issue.

I know some math, but it's been a while since I've done any 2/3D math. There might be some elements I'll miss so having the support of @john-h-k is really appreciated :)

**Comment by Kavignon** [comment]
@john-h-k From what I see, I feel like even if I bring the new C# lib, I feel F# is more suited for these kind of operations, such as elevating a type with an effect, doing the work on the type and then bringing the effect back to the 'normal' world.

I've checked MathSharp on NuGet, and I didn't find it. How do you plan on distributing that package?

**Comment by varon** [comment]
@Kavignon almost all of the development discussion is currently taking place on The OpenTK Discord.

Would be ideal if you can join us here.

https://discordapp.com/invite/6HqD48s

**Comment by john-h-k** [comment]
@Kavignon , nuget, just haven't put it on there yet :)

**Comment by Kavignon** [comment]
@john-h-k I’ve already started by adding the documentation issue on MathSharp. When I get the green light from there, I’ll get started on building the documentation website!

**Comment by varon** [comment]
Closed as out of scope for now.
