### ISSUE TITLE
System.DllNotFoundException : Unable to load DLL 'gbm' on Ubuntu 16.04 - NetCore

### ISSUE THREAD

**Issue by gourky** [opentk/opentk#756]
### Description

Initialization of OpenTK fails with a _System.DllNotFoundException : Unable to load DLL 'gbm'_ message on a Ubuntu 16.04 with an Intel Corei5-6200U CPU internal graphics or the Radeon R5 M300. I tried the amdgpu graphic driver with the same problem.

### Repro steps

1. Create a new console program with visual studio code. Just add a GameWindow. You can use the "test" folder as example.
[test.tar.gz](https://github.com/opentk/opentk/files/2002395/test.tar.gz)

2. Debug

### Expected behavior

GameWindow initialized

### Actual behavior

System.DllNotFoundException : Unable to load DLL 'gbm'

![capture du 2018-05-14 21-57-03](https://user-images.githubusercontent.com/39279898/40021126-4d11fa8c-57c4-11e8-8b39-e27626403fb3.png)

### Related information 

* Fresh install of Ubuntu 16.04 and Ubuntu 18.04
* OpenTK.Netcore 1.1.2749.6433
* Dotnet Core 2
* None

**libgbm1** is already the most recent (17.2.8-0ubuntu0~16.04.1).

**OpenGL info** : glxinfo | grep "version" 
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.3.3
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 17.3.3
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.3.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```

**Comment by Nihlus** [comment]
You are running OpenTK under .NET Core. This is, at the moment, an unsupported configuration and will cause issues like the above.
