### ISSUE TITLE
Can't type @ on MacOS with a german keyboard layout

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#758]
### Description

Typing @ on a german keyboard layout is ALT+L, but the keypress event contains only 'l' (lowercase L)

### Related information 

* Mac OS High Sierra
* Native backend
* 3.0.0, i think
* Mono

**Comment by varon** [comment]
We definitely should have responded, but I know the IME/input system is a bit dodgy.
Please re-open if this is still affecting you.

**Comment by tyronx** [comment]
This is still a problem and its caused by the fact that someone decided to ignore modifier keys when querying for the characters types: https://github.com/opentk/opentk/blob/master/src/OpenTK/Platform/MacOS/CocoaNativeWindow.cs#L848

After changing that to characters on line 73 and line 657 I can type @ using ALT+L again

**Comment by DylanFPS** [comment]
This is awkward because OpenTK.Input was never really meant for typing as OpenGL is a low-level API. As such, I'm not sure how to tackle this one. Open to suggestions.

I've marked this as "needs verification" so we can determine if it's still an issue once GLFW is implemented.

**Comment by tyronx** [comment]
Tweaking 2 lines of code fixed the issue for me: https://github.com/anegostudios/opentk/commit/322c1fe1262f809420aeb4f1f1f5ddaec983d628

**Comment by tyronx** [comment]
> OpenTK.Input is meant to be extremely barebones

OpenTK supports keyboard inputs. Either support it properly or not at all, imho. 

> Also, if possible, can we see if this applies to all platforms?
On windows definitely. There OpenTK currently receives [CHAR Window Messages](https://github.com/anegostudios/opentk/blob/develop/src/OpenTK/Platform/Windows/WinGLNative.cs#L755).

**Comment by DylanFPS** [comment]
> OpenTK supports keyboard inputs. Either support it properly or not at all, imho.

We do support it properly. Imagine this: you're playing a game and the developer sets a default key to `,`. On a german keyboard, you'd need to press 2 keys to achieve that. Modifiers mess with input, and our consumers need to be able to receive raw input.

> In other words you'd break cross platform consistency if the macos implementation would not allow modifiers.

Do me a favour and check how GLFW receives keyboard input? We're offloading all input to them in 4.0, so in the next update you're in their hands.

**Comment by tyronx** [comment]
> We do support it properly. Imagine this: you're playing a game and the developer sets a default key to `,`. On a german keyboard, you'd need to press 2 keys to achieve that. Modifiers mess with input, and our consumers need to be able to receive raw input.

That developer should use keydown events for that which are language and layout independent. KeyPress events on the other hand are not. 

> Do me a favour and check how GLFW receives keyboard input? We're offloading all input to them in 4.0, so in the next update you're in their hands.

 Seems to properly support key input and text input: 
https://www.glfw.org/docs/latest/input_guide.html#input_key / https://www.glfw.org/docs/latest/input_guide.html#input_char

**Comment by DylanFPS** [comment]
Okay. We should add an overload so you can get both the modified input and raw input once GLFW is done.

**Comment by varon** [comment]
Fixed by 4.x
