### ISSUE TITLE
GL.MapBufferRange returns null

### ISSUE THREAD

**Issue by Belfer** [opentk/opentk#762]
### Description

I am trying to use the compute shaders for OpengGL 4.3. I've been trying to get a simple test going and this is currently what I have:

```csharp
GL.GenBuffers(1, out _posBuffer);
OpenGlHelper.CheckNoError();

var posBuffSize = (IntPtr)(NumParticles * sizeof(float) * 4);

GL.BindBuffer(BufferTarget.ArrayBuffer, _posBuffer);
GL.BufferData(BufferTarget.ArrayBuffer, (IntPtr)(posBuffSize), IntPtr.Zero, BufferUsageHint.DynamicCopy);
OpenGlHelper.CheckNoError();

const BufferAccessMask bufferMask = BufferAccessMask.MapReadBit | BufferAccessMask.MapInvalidateBufferBit;
unsafe
{
    IntPtr points = GL.MapBufferRange(BufferTarget.ArrayBuffer, IntPtr.Zero, posBuffSize, bufferMask);
    OpenGlHelper.CheckNoError(); // <- Throws invalid operation exception
    //var 
}
GL.UnmapBuffer(BufferTarget.ArrayBuffer);
```

As far as I can tell, this is all valid. Yet it fails when I try to reference the buffer. I've tried looking for examples of doing this with OpenTK and C#, but, I was only able to find C++ examples.
I'm unsure as to whether this is a bug or if there's is a different approach to this when using OpenTK/C#.

**Comment by UnknownShadow200** [comment]
See Errors at https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glMapBufferRange.xhtml

```
GL_INVALID_OPERATION is generated for any of the following conditions:
...

GL_MAP_READ_BIT is set and any of GL_MAP_INVALIDATE_RANGE_BIT, GL_MAP_INVALIDATE_BUFFER_BIT or GL_MAP_UNSYNCHRONIZED_BIT is set.
```

**Comment by Belfer** [comment]
Ah yes, of course. Terribly sorry for opening an issue for this. And, since this isn't an issue, I'll be closing this thread.
Cheers!
