### ISSUE TITLE
OpenTK looks at the wrong path for ogl on Gentoo?

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#769]
### Description

I have a player that required to add a symlink to the correct opengl library on Gentoo / Mono otherwise the game wouldn't launch.

See following commont and follow up comment.
https://www.vintagestory.at/forums/topic/353-linux-critical-error-requested-graphicsmode-not-available/?tab=comments#comment-2960

Maybe adapt OpenTK.dll.config to specifically target a different lib on gentoo?

### Related information 

* Gentoo Linux
* Native backend
* OpenTK 3.0.0, i think
* Mono 4.x
* Workaround: Create a symlink to the correct opengl path

**Comment by Nihlus** [comment]
I don't think we can differentiate between different distros like this. In our case, we're relying on Mono's DllImport attribute to load the OpenGL library, and we are not looking in any particular directories - all we're doing is passing in the name of the library (libGL.so.1, in this case) and letting Mono resolve the rest.

If this isn't an issue with Gentoo, it's an issue with Mono.

**Comment by VPeruS** [comment]
You can create simple shell script that choose correct mono config for dlls and then run your application

**Comment by UnknownShadow200** [comment]
[Relevant information](http://www.mono-project.com/docs/advanced/pinvoke/#linux-shared-library-search-path) on how mono finds directories for native libs

**Comment by Nihlus** [comment]
Closing, since there's not been an update in a while, and it's highly unlikely this is due to OpenTK.
