### ISSUE TITLE
Better math library

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#77]
In reference to #70, there's a lot of things that could be added to the OpenTK math library. Using T4 templates OpenTK could easily have math classes for different sizes and types easily. A first start would be making sure OpenTK is at least as feature complete as other libraries such as XNA and SharpDX. Secondly would be adding integer vector types as in #70. Other ideas are making structs immutable (mutable structs are odd), I'm sure there's more.

Any thoughts?

**Comment by daerogami** [comment]
Closed due to age.
