### ISSUE TITLE
Default Depth-Buffer bits

### ISSUE THREAD

**Issue by yoavmil** [opentk/opentk#780]
### Description

We had a problem of Z fighting on some laptops, after upgrading to the Nuget dlls. After some investigation I've found that the default Default Depth-Buffer bits changed from 24 to 16. the commit title is "Use 16bit depth in GraphicsMode.Default, 16bits appear to be better supported than 24bits on virtual machines.". Took me a day to find it. (I'm not 100% it's that)

### Repro steps

run on a laptop with Intel HD 520 graphic card, see the Z buffer fighting.

### Expected behavior

have the default depth buffer bit set to 24, unless the card couldn't handle it.

### Actual behavior

depth buffer bit set to 16 on some machines.

### Related information 

* Windows 10
* graphic card: Intel HD 520
* NuGet V3
* C#
* set the depth bit to 24 in the `new OpenTK.GLControl`. see https://github.com/opentk/opentk/issues/511

**Comment by varon** [comment]
By moving to 24 bits as the default (when not all platforms support it) is likely to cause surprise the other way around.

(otherwise, could you give us some stats on % of hardware supporting/not supporting 24 bit buffers?)

Is it not possible to re-structure your data and distances to work within the 16-bit buffer?

**Comment by winterhell** [comment]
15/16 bit is very restrictive and generally worked only on old games with resolution of 640 x 480 which masked the rounding errors.
Could you try using an FBO with a 24-bit Depth Buffer instead? With 3D games you usually want to have some postprocessing so you'll need an FBO anyway, and not use the default depth buffer.

**Comment by yoavmil** [comment]
@varon , I think that PCs with Nvidia worked by default with 24 bits, and PCs with Intel worked with 16 bits.
@winterhell, I'm don't know enough OpenGL to understand what you're saying. please elaborate.

**Comment by winterhell** [comment]
By default you are rendering to the OpenGL backbuffer(basically the screen) which consists of the color and the depth buffers, and is shown when you SwapBuffers();
Most 3D games however want to apply effects to the screen -Bloom, Depth of Field, High Dynamic Range(HDR) tone mapping, Vignetting, Filmic color correction, Screen Space Ambient Occlusion, you name it. For that to be possible the games render to their own set of color and depth buffer, transform the results, and finally output to the OpenGL backbuffer.

**Comment by Nihlus** [comment]
If there's an option for you to set the bit depth yourself, you should use that. Could you provide a link to the commit in question, and the PR it was introduced in?

**Comment by yoavmil** [comment]
@winterhell thanks, I do use front and back buffers, and swap them. But what difference does it make if I render to the default back buffer, or to my own depth buffers, in means of memory and render time?

@Nihlus https://github.com/opentk/opentk/commit/f4360beb74191c80143bbf7dc470ddde69a33973 - it from 2013!

**Comment by tzachshabtay** [comment]
@yoavmil did you try creating your own graphics mode with 24 bits instead of using the default?

**Comment by yoavmil** [comment]
@tzachshabtay yes I have, like sugested at #511. and it works.

**Comment by winterhell** [comment]
>>What difference does it make, in means of memory and render time
Using your own 1920 x 1080 color buffer + 24 bit depth buffer means you'll use a little under 12 MB Video RAM extra. Your GPU probably has 1GB, 2GB or more so thats a drop in the ocean. 
For a 4K resolution It'll be 48MB.
There isn't going to be an impact on performance/render time. Your game needs to be rendering at way more than 1000FPS for you to notice a difference.
