### ISSUE TITLE
Implement touch input

### ISSUE THREAD

**Issue by thefiddler** [opentk/opentk#80]
We should add a public API for touch events. A prototype using SDL2 exists at https://github.com/thefiddler/opentk/tree/touch

The public API will have two components:
- a low-level interface that returns raw touch points
- a high-level gesture recognizer, such as [$P](https://duckduckgo.com/l/?kh=-1&uddg=https%3A%2F%2Fdepts.washington.edu%2Faimgroup%2Fproj%2Fdollar%2Fpdollar.html), that converts raw touch points to gestures.

Open questions:
1. Is Win7 support worth the effort? Win8 offers a much simpler API.
2. Is gesture support worthwhile? If yes, how extensible should it be? (XNA gestures = not extensible; SDL2 $1 gestures = extensible; $P gestures = extremely extensible.)
3. Windows always directs gestures to an active window. This means we cannot implement a stateless API that can be used with WinForms etc. Should we attempt to hack it, or do go with the flow and bind the touch API to `INativeWindow`?

**Comment by mcmonkey4eva** [comment]
Old issue but this is a useful thing to add!
It'd be very useful even to add only the first step, IE raw touch input data!

**Comment by varon** [comment]
Closing for now as we don't have the resources to allocate to this in the immediate future.

**Comment by mcmonkey4eva** [comment]
That's really a shame :( this and every other issue you're closing with this same reason D:

**Comment by tzachshabtay** [comment]
I agree. I don't think an issue should be closed for that reason. IMO, issues are not for what we want to do now, that's what a road-map is for, but for the general backlog of the project. Maybe you can put the "Help-Needed" label on those issues and keep them open?

**Comment by varon** [comment]
You can think of this being closed as out of scope. It's not that we don't think it's useful, it's just that there are more important things to work on with our very limited resources available.

If someone did wish to contribute touch input, then opening a WIP PR would be a much better way of showing that.
