### ISSUE TITLE
How do I merge two wave files into one?

### ISSUE THREAD

**Issue by PartySky** [opentk/opentk#808]
### Description

I tried to merge two wave files with same bits per sample and sapmle rate. 

1) To do this I get this [example](https://github.com/mono/opentk/blob/master/Source/Examples/OpenAL/1.1/Playback.cs) 

2) make 2 byte areas:
```
var sound_data1 = LoadWave(path1, FileMode.Open), out channels, out bits_per_sample, out sample_rate);

var sound_data2 = LoadWave(path2, FileMode.Open), out channels, out bits_per_sample, out sample_rate);
```

3) make sum for each byte and devide it to 2
```
for (int i = 0; i < sound_data1; i++)
{
result_sound_data[i] = (byte)((sound_data1[i] + sound_data2[i]) / 2);
}

```
4) then:

```
AL.BufferData(buffer, GetSoundFormat(channels, bits_per_sample), result_sound_data, result_sound_data.Length, sample_rate);

AL.Source(source, ALSourcei.Buffer, buffer);
AL.SourcePlay(source);

```
An finaly I got some damaged sound instead of mixed signal. How do I solve it?

**Comment by UnknownShadow200** [comment]
At a guess, is bits_per_sample 16? If so, probably need to be averaging the samples as shorts instead of bytes.

**Comment by Nihlus** [comment]
This is unrelated to OpenTK.
