### ISSUE TITLE
Error message under VS2017

### ISSUE THREAD

**Issue by dapeng17951** [opentk/opentk#809]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Properties\AssemblyInfo.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\OpenGL\GLEnums.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\OpenGL\GL.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\OpenGL4\GL4Enums.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\OpenGL4\GL4.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\ES20\ES20.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\ES20\ES20Enums.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\ES11\ES11.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\Graphics\ES11\ES11Enums.cs' could not be found.	OpenTK	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK\CSC	1	Active
Error	FS0225	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\tests\OpenTK.Tests.Generators\AssemblyInfo.fs' could not be found	OpenTK.Tests.Generators	FSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\Generator.Bind\Properties\AssemblyInfo.cs' could not be found.	Generator.Bind	D:\Software\第三方库\OpenTK\opentk-develop\src\Generator.Bind\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\Generator.Converter\Properties\AssemblyInfo.cs' could not be found.	Generator.Convert	D:\Software\第三方库\OpenTK\opentk-develop\src\Generator.Converter\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\Generator.Rewrite\Properties\AssemblyInfo.cs' could not be found.	Generator.Rewrite	D:\Software\第三方库\OpenTK\opentk-develop\src\Generator.Rewrite\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK.GLControl\Properties\AssemblyInfo.cs' could not be found.	OpenTK.GLControl	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK.GLControl\CSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK.GLWidget\Properties\AssemblyInfo.cs' could not be found.	OpenTK.GLWidget	D:\Software\第三方库\OpenTK\opentk-develop\src\OpenTK.GLWidget\CSC	1	Active
Error	FS0225	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\tests\OpenTK.Tests\AssemblyInfo.fs' could not be found	OpenTK.Tests	FSC	1	Active
Error	FS0225	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\tests\OpenTK.Tests.Integration\AssemblyInfo.fs' could not be found	OpenTK.Tests.Integration	FSC	1	Active
Error	CS2001	Source file 'D:\Software\第三方库\OpenTK\opentk-develop\tests\OpenTK.Tests.Math\Properties\AssemblyInfo.cs' could not be found.	OpenTK.Tests.Math	D:\Software\第三方库\OpenTK\opentk-develop\tests\OpenTK.Tests.Math\CSC	1	Active
Warning		Could not resolve this reference. Could not locate the assembly "CommandLine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Generator.Convert			
Warning		The referenced component 'CommandLine' could not be found.	Generator.Convert			
Warning		Could not resolve this reference. Could not locate the assembly "Mono.Cecil.Pdb". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Generator.Rewrite			
Warning		The referenced component 'Mono.Cecil' could not be found.	Generator.Rewrite			
Warning		Could not resolve this reference. Could not locate the assembly "Mono.Cecil.Mdb". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Generator.Rewrite			
Warning		The referenced component 'Mono.Cecil.Mdb' could not be found.	Generator.Rewrite			
Warning		Could not resolve this reference. Could not locate the assembly "Mono.Cecil". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Generator.Rewrite			
Warning		The referenced component 'Mono.Cecil.Pdb' could not be found.	Generator.Rewrite			
Warning		Could not resolve this reference. Could not locate the assembly "Mono.Cecil.Rocks". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Generator.Rewrite			
Warning		The referenced component 'CommandLine' could not be found.	Generator.Rewrite			
Warning		Could not resolve this reference. Could not locate the assembly "CommandLine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Generator.Rewrite			
Warning		The referenced component 'Mono.Cecil.Rocks' could not be found.	Generator.Rewrite			
Warning		The referenced component 'pango-sharp' could not be found.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "glib-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget			
Warning		The referenced component 'gdk-sharp' could not be found.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "gio-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget			
Warning		The referenced component 'gtk-dotnet' could not be found.	OpenTK.GLWidget			
Warning		The referenced component 'gtk-sharp' could not be found.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "cairo-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget			
Warning		The referenced component 'gio-sharp' could not be found.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "gdk-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "atk-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget			
Warning		The referenced component 'atk-sharp' could not be found.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "gtk-dotnet". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget			
Warning		The referenced component 'cairo-sharp' could not be found.	OpenTK.GLWidget			
Warning		The referenced component 'glib-sharp' could not be found.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "gtk-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget			
Warning		Could not resolve this reference. Could not locate the assembly "pango-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	OpenTK.GLWidget

**Comment by VPeruS** [comment]
Looks like you forget to do `nuget restore`
