### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by dapeng17951** [opentk/opentk#811]
A System.AccessViolationException exception occurred while drawing the primitive!
How can I solve it? OpenGL4.0
platform:
1.win10
2.vs2017
3.OpenTK.GLControl -Version 3.0.1
4..Net Framework4
Attachment: My complete code
[Draw_triangle_modern.zip](https://github.com/opentk/opentk/files/2359339/Draw_triangle_modern.zip)

**Comment by Nihlus** [comment]
This is not a support forum. Please join the Discord server for help with your code.
