### ISSUE TITLE
Important OpenTK.GLWidget has wrong GtkSharp3 from MyGet

### ISSUE THREAD

**Issue by deleteaccount1234567890** [opentk/opentk#812]
Hello everyone, 

I have fixed bonus I already recompiled GtkSharp 3.22.8 from GtkSharpKit/GtkSharp from Github

I have tried my recompiled GtkSharp with GLWidget from MyGet OpenTK.GLWidget without wrong GtkSharp3 and It works fine.

Please do not forget to remove wrong gtksharp3 because it doesn't work for Ubuntu 18.04 - I found stable [GtkSharp 3.22.8 ](https://github.com/GSharpKit/GtkSharp)

Thanks for replacing OpenTK's GLWidget with newest version of Gtk Sharp 3

**Comment by DylanFPS** [comment]
3.22.8 is not stable, and as such OpenTK is unlikely to use it. You can track the released (stable) builds [here](https://www.nuget.org/packages/gtk-sharp-3/).

**Comment by varon** [comment]
Closing based on vague issue and dodgy names.
