### ISSUE TITLE
Example of Audio Capture and Playback

### ISSUE THREAD

**Issue by turowicz** [opentk/opentk#816]
### Description

I'm trying to make a simple audio recorder app with playback at the end of the capture.

### Repro steps

There aren't many resources to learn from. I've found the `Parrot` example but it doesn't work as expected: a lot of high pitch squeeky sounds coming out.

### Related information 

* OSX and Windows 10
* C# .NET Core 2.1
* OpenTK.NETCore

**Comment by Nihlus** [comment]
OpenTK.NETCore is an unofficial package, and is not supported by us.
