### ISSUE TITLE
Manual merge of Gamepad input bugfixes in (incompatible) OpenTK fork

### ISSUE THREAD

**Issue by ilexp** [opentk/opentk#819]
### Description

While investigating Gamepad and Joystick input issues in the OpenTK backend of Duality, I found and fixed several issues that were present in the `develop` branch of the original / this repository. Judging from an admittedly brief look into the `4.0` branch, I'm assuming that the issues are still present there as well. I would like to propose merging these fixes into the OpenTK main repository.

The reason I'm opening a new issue instead of a series of PRs is that the OpenTK backend we're using is not based on `4.0`, making automatic merging somewhat difficult. I suspect that this will be a series of manual merge operations, which I will probably not manage to do anytime soon, as I'm already pretty occupied with maintaining the other project. I figured it still makes sense to report these fixes here, in case anyone else would be willing to step in, perhaps even to gain some Hacktoberfest points this month.

The following is a list of commits that I made on our OpenTK fork, reflecting recent changes and fixes:

- [Removed Gamepad Thumbstick Y Flip](https://github.com/AdamsLair/opentk/commit/d83f5726c1597e37f91ad7efb0274d0cae085b2b)
- [Gamepad Mapping Support for Range + Inversion Operators](https://github.com/AdamsLair/opentk/commit/cde37312d6811f9de7543bf527bc48a1a8a45ca7) to ensure compatibility with SDL Gamepad configuration database entries
- [Updated to new SDL >= 2.0.6 Format for Controller Mappings](https://github.com/AdamsLair/opentk/commit/caacfb7159a8a1225f4cc5cef005ed87ca92e381), now using the same GUID generation pattern that SDL does from 2.0.6 upwards, fixing a gamepad mapping mismatch when using the OpenTK SDL backend.
- [Fixed Windows Joystick GUI Generation to Match SDL2 Database GUIDs](https://github.com/AdamsLair/opentk/commit/60b7dccead820a03096c413c771efbf90c5e3012), a fix to the previous commit.
- [Simplified some WinRawJoystick Code](https://github.com/AdamsLair/opentk/commit/e843cdb4f3ae46c4cd406751d70e54f014faabd9)
- [Fixed Reporting Joysticks Without any Axes, Buttons or Hats](https://github.com/AdamsLair/opentk/commit/e85d1293e58dcac2e74432e458817233fa0162e5), addressing an issue where sometimes "phantom" joysticks would be reported that do not have any input capabilities.
- [Fixed Joystick Axes with Invalid / Zero Usage Value Overwriting the First Axis](https://github.com/AdamsLair/opentk/commit/9bad0fe8ea61bff31b2de2595185284a67284d27)
- [Replaced OpenTK Joystick Axis / Button / Hat Index Mapping Code](https://github.com/AdamsLair/opentk/commit/57dd4f115b525e9a1da0db21408774c2d9f3980c). This addresses an issue where SDL would reflect an HID input device reporting an axis multiple times, and OpenTK would not, creating a mismatch in axis indices that are used in the Gamepad configuration database. For example, this would cause an iNNEXT SNES controller to be mapped wrong without SDL backend, despite selecting the correct mapping and receiving the same input data.

For context, you can find the issue with my worklogs on this [here](https://github.com/AdamsLair/duality/issues/683).

Please do note that I was only able to test the above fixes on Windows, and only with a limited set of controllers. There is still an unresolved issue with a certain PS4 controller, but as far as I know, it did exist before and were not introduced by the above changes.

**Comment by Nihlus** [comment]
As it is right now, `develop` is frozen and will not receive any more updates. It is the final version of 3.0, and if you need any patches against it you are advised to do so on your own fork. 

Currently, we are developing `4.0`, which is a major restructuring and refactoring of the library as a whole. If you'd like your fixes to be in the official OpenTK version, we'll gladly accept them on the 4.0 branch :)

**Comment by Nihlus** [comment]
We might consider minor releases for critical problems, but only if those fixes also go into 4.0. It'll have to be really, really severe issues, though.

**Comment by DylanFPS** [comment]
This will serve as a good reference when working on 4.0, however like Jax said, these changes will not be added to 3.0 as the branch is frozen. If you feel like a challenge, you could PR into the 4.0 branch - that'll make our job a little easier! :)

**Comment by leezer3** [comment]
I've always had mixed feelings about the freeze TBQH.
A feature freeze is 100% fine, and a freeze on stuff like documentation commits and functionality tweaks is also fine. 
Freezing with (now) known bugs is far more dicey, especially in a library intended to be consumed by end-user applications, and IMHO a hotfix is appropriate in this case.

I can rebase these onto 4.0 if we want, but we really need to decide on the exact direction that we want to take with regards to SDL: There was talk of dropping the WinRaw backend altogether, as well as all the restructuring going on- Pointless effort?

**Comment by DylanFPS** [comment]
To be honest, 4.0 still has many pending structural changes, so I think it’s best to hold off on the rebase - I’ll manually add the changes later unless someone says otherwise (I actively monitor the discord)

**Comment by Nihlus** [comment]
The intent of the freeze is and has always been to refocus efforts towards 4.0, where OpenTK's future firmly lies. 

With that said, I could accept a critical bug fix that is applicable to and goes into both 3.0 and 4.0. 3.0-only stuff is not worth it right now. 

Dropping the native windows backend will, unfortunately, cripple a few features - namely, embedding OpenGL surfaces in UI toolkits. That, right now, just isn't doable with SDL.

**Comment by ilexp** [comment]
> Dropping the native windows backend will, unfortunately, cripple a few features - namely, embedding OpenGL surfaces in UI toolkits.

(Slightly off topic, but) just wanted to acknowledge that this is a critical feature for the project I'm on.

**Comment by DylanFPS** [comment]
@ilexp Not off-topic at all, good to know 👍

**Comment by varon** [comment]
This discussion shows the importance of getting 4.0 into a point where people can contribute. Is there a tracking issue or something where we can see what needs to be done to get it into a 'contributable' state?

**Comment by Nihlus** [comment]
@varon Getting a todo list up and running is something that really needs getting done. I'm down for talking it through in the chat and nailing down what needs to be done. I've got a full-time job now, so that takes a lot of time from me.

**Comment by ilexp** [comment]
> This discussion shows the importance of getting 4.0 into a point where people can contribute. Is there a tracking issue or something where we can see what needs to be done to get it into a 'contributable' state?

From a somewhat involved user's perspective:

Duality has been using OpenTK for quite a while now, and always based on a custom fork that exists to ensure stability, and a fast-tracking path for bugfixes or tweaks that we need. I would suspect that a setup like this is common in bigger, more long-term projects. Contributing back to OpenTK is definitely a goal, but also kind of a side effect: In this situation, contributions mostly happen when we can easily push back changes that we had to do for our use cases anyway. 

Of course that's all a bit tricky with the 3.x / 4.0 divide, because there will be a medium to long period where we will lag behind on the 3.x side while OpenTK develops on the 4.0 side. A contributable state of 4.0 would be a state that is stable and compatible enough to allow us to update without too much of a risk - probably a while after its official release, and after it has been used by enough smaller projects to indicate it's production ready. Every big update has a big threshold to overcome because of the required research, testing and risk of breaking things in a way that is outside the field of expertise of the developer who introduced it.

From an outside view, it currently looks like OpenTK is in the middle of a big refactoring, with failing build states on the readme page and not a lot of real world tests so far - or if there are, they're not easily visible. The 4.0 branch needs to reach a stable, battle-tested state that evokes both spontaneous and informed trust in people who are not maintainers and its main developers, so it can gather users who can contribute back changes from their projects.

On a similar note, OpenTK needs to be careful with big refactorings, especially those that are mostly style changes, and those that bump the minimum required C# version: They make it very hard to merge with custom changes, while at the same time being somewhat frustrating because there's nothing to gain that still exists after compiling - both of which increases the lag between upstream OpenTK and user OpenTK. Requiring a new C# version can even affect other projects build pipelines that integrate custom OpenTK forks, potentially even blocking an update from that side for whatever reason.

Alright, I hope this outside view helps a bit. Maybe it was obvious, but I figured it couldn't hurt to share anyway. That said, I think we got a bit off topic here, so feel free to ping me in case you continue this discussion elsewhere.

**Comment by Nihlus** [comment]
Updating an established 3.0 project with its own custom fork to 4.0 is
something I feel will be a lot of effort for marginal gain, unless that
also comes with a retargeting effort or multitargeting effort for the
project.

4.0's intent is to break away from the legacy mindset of 3.0 and use the
modern C# environment to its fullest extent.

The point of a major point release is to be able to rethink, redo, and
rewrite.

**Comment by varon** [comment]
To echo @Nihlus , we're taking a very long term view here. Once 4.0 is out and fully working, it should be extremely easy to contribute. Everything from build process to tests to formatting should make it as frictionless as possible to contribute.

The eventual wish would be that the thousands of forks out there would converge upon 4.+ and start helping give back to the project.

You're absolutely right that we're suffering from instability in 4.0 at the moment, and we'll double down on efforts to get it into a "contributable" state.

**Comment by DylanFPS** [comment]
Will contribute once I the maintainers have knuckled down and produced a TO-DO list :)

**Comment by varon** [comment]
Fixed by 4.x
