### ISSUE TITLE
Implement NativeWindow.Pause and Resume events

### ISSUE THREAD

**Issue by thefiddler** [opentk/opentk#82]
These events are necessary for Android, iOS and WinRT. In response to a pause event, applications should save their state and pause any processing they are performing. The operating system may kill or Resume the application at any point after this.

Applications that fail to obey a Pause event may be abruptly terminated by the operating system.

**Comment by varon** [comment]
This is too necessary to close. Wish we could get a contribution here.

**Comment by subchannel13** [comment]
I have some experience with Android, how can I help?

**Comment by Nihlus** [comment]
@subchannel13 If you have the time, find the relevant code and put together a pull request - it would awesome if you could get support for this implemented.
