### ISSUE TITLE
Exception in internal handling of mouse move event

### ISSUE THREAD

**Issue by ChristophHornung** [opentk/opentk#820]
### Description

I have recently upgraded a program to the latest OpenTk version. On some machines an exception now infrequently pops up on handling the mouse move inside the game loop:
```
System.ComponentModel.Win32Exception (0x80004005): Zugriff verweigert
   bei OpenTK.Platform.Windows.WinGLNative.HandleMouseMove(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
   bei OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   bei OpenTK.Platform.Windows.WinGLNative.ProcessEvents()
   bei OpenTK.NativeWindow.ProcessEvents(Boolean retainEvents)
   bei OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   bei App.Client.Library.Layout.Engine.Start(String[] args)
```

### Repro steps

I see the exception in the logs on some machines but never caught one with the debugger attached. They seem to happen infrequently and from what I can tell they mostly seem to happen when the program was left idling for a long time. 

### Related information 

* Operating system: Windows (7 and 10)
* SDL or Native backend: unclear
* What version of OpenTK (Installer, NuGet, Source Code): NuGet
* What runtime (.NET Framework, CoreCLR, Mono): .NET Framework
* Workarounds (if any): none so far

I am not too familiar with the win32 api, but might the messageTime passed with the mouseMovePoint have something to do with the bug occurring when the program was left running for a long time?

**Comment by DylanFPS** [comment]
Can you translate the first line for me please?

**Comment by DylanFPS** [comment]
Okay. Can we see the code you're using to create the window?

**Comment by ChristophHornung** [comment]
I am inherting from GameWindow
```
internal class BasicGameWindow : GameWindow
	{
		private readonly bool maximized;
		private readonly bool fullscreen;
		private readonly bool showMousePointer;
		private long prevTime;

		public BasicGameWindow(Vector size, bool fullscreen = false,
			bool showMousePointer = true, bool maximized = true) : base(size.x, size.y,
			new GraphicsMode(new ColorFormat(8, 8, 8, 8), 8, 8), Engine.Title)
		{
			this.maximized = maximized;
			this.fullscreen = fullscreen;
			this.showMousePointer = showMousePointer;

			this.VSync = VSyncMode.On;

			this.MouseDown += this.OnMouseDown;
			this.MouseMove += this.OnMouseMove;
			this.MouseUp += this.OnMouseUp;
			this.MouseWheel += this.OnMouseWheel;
			this.KeyDown += this.OnKeyDown;
			this.KeyUp += this.OnKeyUp;
			this.KeyPress += this.OnKeyPress;
		}

		public void Init()
		{
			GL.Hint(HintTarget.PerspectiveCorrectionHint, HintMode.Nicest);
			GL.Enable(EnableCap.Texture2D);
			GL.Enable(EnableCap.Blend);
			GL.ClearColor(0f, 0, 0, 0f);
			this.prevTime = Engine.Realtime;

			this.Icon = new Icon(Engine.AppPath + "Icon.ico");
			Engine.OnPrepareFirstDraw(EventArgs.Empty);
			Engine.OnInit(EventArgs.Empty);
			
			this.Title = Engine.Title;

			this.CursorVisible = this.showMousePointer;

			if (this.fullscreen)
			{
				this.WindowState = WindowState.Fullscreen;
			}
			else if (this.maximized)
			{
				this.WindowState = WindowState.Maximized;
			}
		}

		protected override void OnResize(EventArgs e)
		{
			Engine.NotifyResize(this);
			this.OnRenderFrame(null);
		}

		protected override void OnRenderFrame(FrameEventArgs e)
		{
			Engine.Excecute();
		}

		protected override void OnWindowStateChanged(EventArgs e)
		{
			Component.HandleDraw(forceRedraw: true);
		}

		protected override void OnFocusedChanged(EventArgs e)
		{
			Component.HandleDraw(forceRedraw: true);
		}
		
		... EventHandline (no more overrides)
```

and start with

```
size = new Vector(DisplayDevice.Default.Width, DisplayDevice.Default.Height);
    using (var gameWindow = new BasicGameWindow(size, true, true, true))
			{
			        gameWindow.Init();
				gameWindow.Run(30,30);
			}
```

**Comment by tyronx** [comment]
A user of mine also experienced this exception once. I haven't heard of further reports anymore. 
-> https://github.com/anegostudios/VintageStory-Issues/issues/174

**Comment by ChristophHornung** [comment]
I had the chance to talk to one of the users where the exception happens frequently. According to his account the exception is thrown after the program is idling for a while and he is returning to his computer. He does have an active screensaver. I am not sure yet whether the exception happens while the screensaver is active or immediately afterwards.

Since the old version of OpenTk that was upgraded from did not yet use GetMouseMovePointsEx the error only occurs on the latest version. 

Maybe it makes sense to change the code to always return the X/Y coordinates of the mouse move point when the method fails? Currently this only seems to happen for the lastWin32Error 1171.

**Comment by tyronx** [comment]
This just happened to me for the first time in OpenTK 3.1. Seems to be a super rare race condition. I think it happened right after I alt+tabbed out of the game window.

**Comment by ChristophHornung** [comment]
@tyronx This should not happen in OpenTK 3.1 anymore since the error handling was changed, so that on error the input coordinates are returned. What error code did you get?

**Comment by tyronx** [comment]
Exactly the same one. Ohwait, thats my bad, I have not yet updated to the official OpenTK 3.1. Ok, adding to my todo list :D

**Comment by varon** [comment]
Fixed by 4.x
