### ISSUE TITLE
MacOS Random crash, presumably related to the mouse cursor

### ISSUE THREAD

**Issue by tyronx** [opentk/opentk#822]
### Description

The Mac OS WindowServer crashes and the user is thrown back to the login screen.
Proooobably (randomly?) caused by changing the state of the mouse cursor. 

window.CursorVisible = value;
window.CursorGrabbed = !value;

As reported by https://github.com/anegostudios/VintageStory-Issues/issues/210

Crashlogs: 
[WindowServer_2018-10-11-184357_MBP-18.log](https://github.com/opentk/opentk/files/2472340/WindowServer_2018-10-11-184357_MBP-18.log)

### Related information 

* Mac OS X 10.13.6 (17G2307)
* Native backend
* 3.0

**Comment by leezer3** [comment]
I wonder if this is related:
https://github.com/opentk/opentk/commit/eab88bf5995e0bfa2ac2012c21a61a5b46f24c24

This is only patched in 4.0, and I wonder if a newer Mono / OS-X update means that custom cursors are now corrupting memory they shouldn't somewhere, as opposed to just being harmless.

**Comment by tyronx** [comment]
Ow, interesting that you mention that. I also had a mac os user crash really hard, apparently due to mouse cursor related issues (https://github.com/anegostudios/VintageStory-Issues/issues/210)

**Comment by tyronx** [comment]
hm no, this is not related. That patch fixes custom cursors. I never set any custom cursor on mac os as it was broken.

**Comment by varon** [comment]
Fixed by 4.x
