### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by WebFreak001** [opentk/opentk#824]
There should be the possibility to access & write text to/from the system clipboard with OpenTK.

SDL, Win32 and Cocoa is globally usable without window reference but could also be wrapped under the same API.

On X11 custom event handling for the window would be required which would be handled by OpenTK. If it's implemented like the other APIs it will only support the clipboard selection and not the primary selection (which is set when just selecting a text and pasted using middle mouse button instead of ctrl-c, ctrl-v)

Using an API like this, text inputs in games could be made more user friendly.

**Comment by subchannel13** [comment]
This is something System.Windows.Clipboard class should handle, not OpenTK. If there are any issues with the class it's up to Mono team.

**Comment by WebFreak001** [comment]
that class isn't available under dotnet core though

**Comment by FreezyLemon** [comment]
Agree, I think this could be useful for games (and other usages too).
I'm actually kind of surprised that the .NET standard doesn't contain this..

**Comment by UnknownShadow200** [comment]
Not sure how useful this is (not great quality and definitely not thread safe), but [I wrote some](https://gist.github.com/UnknownShadow200/a927cd2a710100694b93f3a9cd379062) code for handling clipboard for older OpenTK.

**Comment by varon** [comment]
@UnknownShadow200  - It would be nice to get that in a usable form for 4.0... for sure...

**Comment by Ollhax** [comment]
There's also this library that handles clipboard on dotnet core: https://github.com/SimonCropp/TextCopy

**Comment by WebFreak001** [comment]
that library doesn't use the clipboard APIs and relies on a third party app which is not installed by default (xclip). The only way to properly implement it is by including it in the window event loop as shown in the code above for X11.

**Comment by DylanFPS** [comment]
Slated this for post-4.0. Once we have GLFW stable, we should be able to do this.

**Comment by devvoid** [comment]
Will be closed by #867.
