### ISSUE TITLE
Test OpenTK on WinRT

### ISSUE THREAD

**Issue by thefiddler** [opentk/opentk#83]
[SDL2 hg tip](https://www.libsdl.org/hg.php) implements preliminary support for WinRT. We should test this and make sure OpenTK is working as expected.

Desktop OpenGL is not supported on WinRT, so this requires an up-to-date build of [ANGLE](https://chromium.googlesource.com/angle/angle).

**Comment by daerogami** [comment]
Closed due to age.

**Comment by varon** [comment]
Ahahaha, oh man, WinRT! Fallen into the depths of obscurity!
