### ISSUE TITLE
Vsync does not work correctly in GameWindow.OnLoad()

### ISSUE THREAD

**Issue by Lyrcaxis** [opentk/opentk#830]
### Description

Detected Heavy CPU Usage(Full thread) even on empty GLWindow, VSync or no VSync, when specifying target FrameRate/UpdateRate. 

### Repro steps

Simply make a new project using my settings and add this in your Program.cs

```
 [STAThread]
 static void Main() {
	using (var gw = new GameWindow()) {
 		gw.Run(1,1);
 	}
 }
```

### Related information 

Running on Windows10 x64 with latest Nvidia drivers.
OpenTK v3.0.1 downloaded from NuGet, with .Net Framework 4.7.1

The workaround I use is having the GameWindow just Run() --without specifying target framerate/updaterate and activating VSync after 2 seconds.. Not sure about the specifics but it seems to fix the issue

```
 //Program.cs
 [STAThread]
 static void Main() {
 	using (var gw = new MainWindow()) {
 		gw.Run();
 	}
 }

 //MainWindow.cs
 protected override async void OnLoad(EventArgs e) {
     VSync = VSyncMode.Off;
     await System.Threading.Tasks.Task.Delay(2000);
     ActionQueue.Add(() => VSync = VSyncMode.On);
 }
 
 List<Action> ActionQueue = new List<Action>();
 protected override void OnUpdateFrame(FrameEventArgs e) {
     for (int i = ActionQueue.Count - 1; i >= 0; i--) {
         ActionQueue[i].Invoke();
         ActionQueue.RemoveAt(i);
     }
 }
```

**Comment by subchannel13** [comment]
That's how GameWindow works, it dishes out frames as fast as possible, potentially being wasteful if nothing changes in the scene. There was pull request where this was discussed in greater detail:

https://github.com/opentk/opentk/pull/472

**Comment by Lyrcaxis** [comment]
-- I'm really new on OpenGL/OpenTK so I'll be just assuming stuff:

Yes, while VSync _works_ if turned in OnLoad or the first few frames, (here works was used as in limit the FrameRate), the CPU usage wont drop down to 0,5% unless VSync is turned on _AFTER_ the (what I assume is ) _PREWARM_ happens.

**Comment by varon** [comment]
@Nihlus  - this is a really interesting one...

**Comment by varon** [comment]
@Lyrcaxis - If you've got time and interest, this could be pretty fun to try and figure out what's going on. 
We're always looking for more contributors, and would be more than happy to help if you wanted to learn a bit more about OpenTK.

**Comment by Lyrcaxis** [comment]
@varon Sure, I'm willing to contribute.. and I'd be more than happy to accept help :D 

From the info I got, VSync cannot be enabled until some time passes. 
I've tried with 0,200,500,1000 and 2000ms delay since load. the first few aren't working. And the CPU issue wont fix itself until GameWindow.VSync is set again (narrows down to the failure to call the extern functions). 

Found these to be possibly related :
WinGLContext.cs(329), WinGLContext.cs(346), WglHelper.cs(100), WGL.cs(263)

PS: I cannot seem to be able to compile and actively try to bug-fix since these files are missing from git source http://prntscr.com/l98mv9 .

**Comment by tzachshabtay** [comment]
@varon he can't work off 4.0 as it's not even in a compiling state yet.

**Comment by varon** [comment]
@tzachshabtay It's good to see you around. We'll hopefully have that sorted today.

**Comment by varon** [comment]
Fixed by 4.x
