### ISSUE TITLE
Strange compilation errors on Linux building Generator.Bind

### ISSUE THREAD

**Issue by dnstag** [opentk/opentk#835]
### Description

The actual 4.0 source produces strange building output and behaviour on Linux with dotnet 2.1.403

Trying to build the Binding Generator but it shows massive errors complaining about violation of a StyleCop rule.

```
[yseibert@xenon ~]$ dotnet build src/Generator.Bind/Generator.Bind.csproj

...

XML/Signatures/SignatureReader.cs(5,1): error SA1200: Using directive should appear within a namespace declaration [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
XML/Signatures/SignatureReader.cs(6,1): error SA1200: Using directive should appear within a namespace declaration [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
XML/Signatures/SignatureReader.cs(7,1): error SA1200: Using directive should appear within a namespace declaration [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
XML/Signatures/SignatureReader.cs(8,1): error SA1200: Using directive should appear within a namespace declaration [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
XML/Signatures/SignatureReader.cs(9,1): error SA1200: Using directive should appear within a namespace declaration [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
XML/Signatures/SignatureReader.cs(10,1): error SA1200: Using directive should appear within a namespace declaration [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
XML/Signatures/SignatureReader.cs(11,1): error SA1200: Using directive should appear within a namespace declaration [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
    784 Warning(s)
```

after a ```dotnet build OpenTK.sln``` with over 11.000 Errors, a ```dotnet build src/Generator.Bind/Generator.Bind.csproj``` now produces just the following 2 Errors:

```
[yseibert@xenon ~]$ dotnet build src/Generator.Bind/Generator.Bind.csproj

...

"/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj" (Standardziel) (1) ->
"/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj" (Build Ziel) (1:2) ->
(FodyTarget Ziel) -> 
  MSBUILD : error : Fody: Could not find path to weavers file. Searched '/home/yseibert/Development/opentk/src/Generator.Bind/../FodyWeavers.xml', '/home/yseibert/Development/opentk/src/Generator.Bind/FodyWeavers.xml'. [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]


"/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj" (Standardziel) (1) ->
"/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj" (Build Ziel) (1:3) ->
  MSBUILD : error : Fody: Could not find path to weavers file. Searched '/home/yseibert/Development/opentk/src/Generator.Bind/../FodyWeavers.xml', '/home/yseibert/Development/opentk/src/Generator.Bind/FodyWeavers.xml'. [/home/yseibert/Development/opentk/src/Generator.Bind/Generator.Bind.csproj]
```
as @Nihlus stated before, it may be a bug in the path resolution.

### Repro steps

```
dotnet build src/Generator.Bind/Generator.Bind.csproj (SA1200 Error)
dotnet build OpenTK.sln (>11k Errors)
dotnet build src/Generator.Bind/Generator.Bind.csproj (StyleCop Rule Violation)
```
### Expected behavior

Should compile without these errors.

### Actual behavior

Compiles with the errors stated above.

### Related information

* Arch Linux w/ Kernel 4.8.16
* actual OpenTK 4.0 source
* CoreCLR, dotnet v2.1.403
* At this time i got no workaround

**Comment by DylanFPS** [comment]
Hmm looks like stylecop is severely interfering with the build. I was going to take a look at this, but it’s probably best if someone who knows their way around stylecop looks at this (@Nihlus )

**Comment by dnstag** [comment]
What i don't get is why the stylecop errors disappear after building the whole solution (even with errors).

**Comment by Nihlus** [comment]
The issue here is that the StyleCop ruleset location is relative to the solution's root. If you build each project individually, it's not guaranteed that it'll be able to resolve that. 

This issue is partially solved by the OpenAL PR - I had the same issue there, and I solved it by a hybrid approach.

**Comment by dnstag** [comment]
Okay, so wouldn't it make more sense to help you get the code buildable on linux before i begin working on #829?
________________________________

**Comment by Nihlus** [comment]
Oh, it's absolutely buildable on Linux - it's my main env. The OpenAL PR should solve this.

**Comment by WonyoungChoi** [comment]
https://github.com/opentk/opentk/blob/cd06d933a3ab2da120f569974e24c9b1690ce494/stylecop.ruleset#L79
I think the rule SA1200 should be ignored. This rule is not appropriate for this project.

**Comment by morguldir** [comment]
Why not? The use case for placing them inside a namespace seems to be if you have multiple namespaces inside one file, which shouldn't happen in the first place.

**Comment by Nihlus** [comment]
@WonyoungChoi In what way is it not appropriate?

**Comment by WonyoungChoi** [comment]
@Nihlus SA1200 is a styling rule about ordering using directives. This rule forces all using directives into the namespace. If you do not want to modify all the code, you should disable this rule.
SA1200 : http://stylecop.soyuz5.com/SA1200.html
more article about this : https://blogs.msdn.microsoft.com/abhinaba/2006/08/21/stylistic-differences-in-using/

**Comment by Nihlus** [comment]
The rule is configured to force using directives to be outside the
namespace, not inside the namespace. The above errors are because the
configuration file could not be properly resolved due to the project being
compiled without a solution context.

**Comment by dnstag** [comment]
After merging the al-adl branch from @Nihlus into 4.0 the build errors are gone, so i'm closing this issue.
