### ISSUE TITLE
[4.0] Some OpenTK.NT considerations

### ISSUE THREAD

**Issue by FreezyLemon** [opentk/opentk#838]
This will probably have implications for the other low-level, native projects as well.

I'm currently in the process of transferring the HID functions etc. too, and had some ideas that I'd like some input on:

## Move away from using windows "typedefs" in C#

Example:
windows data type:
```c++
typedef unsigned short USHORT;
```

OpenTK.NT:
```c#
using USHORT = System.UInt16;

public struct Something
{
    public readonly USHORT SomeField;
}
```

Reasoning: It's more work, and really not necessary at all. I don't know how I thought that was a good idea when I started doing it.

## Change the folder structure and namespace structure

In hindsight, I dislike my approach a lot. Mostly because everything (yes, everything) is in `OpenTK.NT.Native`. Try Intellisense-ing into it. With a new namespace should come a new folder structure so file name & position == namespace again.

## Decide on some guidelines for function overloads

A lot of the time, when porting old code, I had to just blindly decide (and probably inconsistently did so) on what function overloads to provide when there are multiple possibilities. This is also connected to "convenience functions".

Some examples:
```C#
public static unsafe extern int MyFunction(byte* myByteArray, int arrayLength);
```

Should we:
A. Provide a convenience function that just takes a managed array?
B. Provide the shown (unsafe) method and let the consumer worry about it?
C. Provide an overload with an `IntPtr` instead of the `byte*` pointer?
D. Provide any combination of the above?

Ninja edit:
E. Just provide whatever we need internally?

**Comment by jvbsl** [comment]
Well I think it's ok to use a wrapper struct for such types, If we use something like ADL, which in turn than should have the possibility to use the internal value directly, as an optimization, because with DllImport structs do take extra time to their primitive counter parts.

Same goes for IntPtr which is slower if you use int(32-bit) or long(64bit arch) respectively.

On function overloads if it should be for public use, I think D would be best, where A should be optional(as it would not be easily possible with something like automatic code generation)

**Comment by FreezyLemon** [comment]
Not sure what you mean by wrapper struct... for clarification, those `using` statements are only *renaming* the .NET types to whatever they would be called in the [Windows data types](https://docs.microsoft.com/en-us/windows/desktop/WinProg/windows-data-types)
-> There's no actual `typedef` going on in OpenTK

The problem I personally have with D is that providing multiple functions can bloat the assembly quickly, and that there are some functions that have very long documentation (e.g. CreateWindow / CreateWindowEx) which would have to be repeated, resulting in a ton of redundant code.

**Comment by jvbsl** [comment]
> Not sure what you mean by wrapper struct...
I actually meant stuff like.
`Using Device = IntPtr;`
Where I would introduce a wrapper struct.

For other primitive types I would discourage usage of using-aliases.
Because they make the Code hard to read if you need to lookup the underlying type:
e.g. System.Uint16 has ushort alias in C# anyway, why the need to introduce USHORT?

**Comment by FreezyLemon** [comment]
>I wouldn't suggest that we need sub-namespaces for the structs/enums/delegates. Those could live in the parent ones (like Shell32) with a lot less clutter this way.

Definitely agree. If there are sub-namespaces, it should be handled like in User32 (separation by concern, not by object type). I hope there aren't too many "shared" types though, but I think there are only a few.

>As for exactly how to expose the ones we need, I think choosing the fastest safe way would be best here.

I don't have any benchmarks, but I'd assume that unsafe pointers (direct invocation without any wrapper) would be faster than any safe alternative. This might require testing before a decision is made..

I didn't state my opinion before, but I basically agree with your statement. I'd always choose speed over "safety" (unsafe code really isn't a problem in low-level stuff like this), but try to only expose functions we actually call in OpenTK code. This would prob. mean cutting down on a lot of functions as it is right now, but expanding later shouldn't be too difficult.

**Comment by DylanFPS** [comment]
Closing as we ditched the NT backend
