### ISSUE TITLE
nuget package points to wrong website

### ISSUE THREAD

**Issue by freakinpenguin** [opentk/opentk#850]
### Description

The link on the page https://www.nuget.org/packages/OpenTK/ points to the website www.opentk.com which is no longer available.

### Repro steps
Go to website and click the link.

### Expected behavior

The correct url.

### Actual behavior

The wrong url.

### Related information

**Comment by DylanFPS** [comment]
Nothing we can do until 4.0 I'm afraid - we've already fixed the URL for the 4.0 packages.

**Comment by varon** [comment]
We can't update the package description by uploading a 3.0.1.1?

**Comment by DylanFPS** [comment]
We could, but 3.0 is frozen and this isn't really an issue that warrants a NuGet patch imo

**Comment by varon** [comment]
Fair enough. I agree with that assessment.

**Comment by freakinpenguin** [comment]
No problem, just wanted to let you guys know...

**Comment by varon** [comment]
Thanks though @freakinpenguin. We do appreciate this even though there's nothing we can reasonably do right now.

**Comment by DylanFPS** [comment]
Nope, not possible - tried it before.

**Comment by ChristophHornung** [comment]
Since there was a 3.1.0 nuget release (which sadly did not include the fix for the url) shouldn't this be integrated into the code that might become a 3.1.1 or 3.2.0 release?
