### ISSUE TITLE
An approach to multiple windows using OpenTK

### ISSUE THREAD

**Issue by migueltk** [opentk/opentk#851]
### Description

An approximation to the code needed to implement multiple windows using OpenTK.

Animated by the project [SummerGUI](http://www.kroll-software.ch/products/summergui/), I recommend it, I have created this [NeoGUI](https://drive.google.com/open?id=1AhwoS-vkY478_69KsVI-slwrtf_-4LMf) application that allows to create multiple windows (left mouse button a non-modal window, right button a modal window).

In principle works well in both Windows 7 and Ubuntu 18.04, however, I consider myself a programmer above OpenTK, I have doubts.

1. Is the correct way to implement multiple windows ?. 
```
        protected override void OnRenderFrame(FrameEventArgs e)
		{
			base.OnRenderFrame(e);

			if (!Exists)
				return;

			Context.MakeCurrent(WindowInfo);
			UpdateResize();
			float aspectRadio = Width / (float)Height;
			DoDemoRender(aspectRadio, e.Time);
			SwapBuffers();

			double ts = 0;

			WindowForm[] wndsGUI = new WindowForm[WindowsChild.Count];
			WindowsChild.CopyTo(wndsGUI, 0);
			foreach (WindowForm wndChild in wndsGUI)
			{
				if (wndChild != null
				    && !wndChild.IsDisposed
				    && wndChild.Visible
				    && wndChild.Exists)
				{
					wndChild.Context.MakeCurrent(wndChild.WindowInfo);
					wndChild.UpdateResize();
					wndChild.RaiseRenderFrame(e.Time, ref ts);
					wndChild.ProcessEvents();
				}
			}
		}

```
In the OnRenderFrame () method we first render the parent window and then the childs.
2. Sometimes the mouse cursor gets caught trapped in the internal limits of the window, in Linux-SDL2. This only happens when there are several windows. I have tried to solve the problem with this code but it still fails.
 ```
       protected override void OnMouseMove(MouseMoveEventArgs e)
        {
            base.OnMouseMove(e);
            // ¿Evita que el cursor del ratón quede atrapado en los límites 
            // internos de la ventana, en Linux-SDL2. Esto solo ocurre
            // cuando hay varias ventanas?
            // Prevent the mouse cursor from getting caught in the 
            // internal limits of the window in Linux-SDL2. This happens only
            // when there are several windows?
            if (Environment.OSVersion.Platform == PlatformID.Unix)
            {
                CursorVisible = true;
            }
        }
```

3. To avoid the processing of events in a parent window when a modal is open, it is necessary to filter each of the events. This could be simplified if the ProcessEvents () method of GameWindow was accessible by the subclasses, is an idea. For example;
```
protected override void OnMouseDown(OpenTK.Input.MouseButtonEventArgs e)
{
	if (CanProcessEvent())
	{
		base.OnMouseDown(e);

                WindowForm win;
                if (e.Button == OpenTK.Input.MouseButton.Left)
                {
                    win = new WindowForm("WindowChild", 520, 360, this);
                    win.Show();
                }
		if (e.Button == OpenTK.Input.MouseButton.Right)
		{
                    win = new WindowForm("WindowChild", 520, 360, this, null, GameWindowFlags.FixedWindow);

                    win.WindowBorder = WindowBorder.Fixed;
					win.ShowDialog();
				}
 			}
		}

```
4. In Ubuntu 18.04 (sdl2-2.8) sometimes a warning appears "Warning: SDL2 requires a shared context to be current before sharing. Sharing failed.", it is out of my knowledge.

It would be interesting, perhaps necessary, for OpenTK to incorporate multi-window support.

Any help and suggestion will be well received.

**Comment by varon** [comment]
Thanks for the suggestion and idea, @migueltk.

We're currently super busy with moving stuff to 4.0. It's possible we could look at doing this via GLFW, which is being worked on as a prototype in #867 .

**Comment by varon** [comment]
Should be possible in 4x.
