### ISSUE TITLE
[4.0] Use Indirect Calls with ADL

### ISSUE THREAD

**Issue by Perksey** [opentk/opentk#855]
Through internal investigations, we've discovered that using delegates with ADL is much more inefficient than using indirect calling (calli). A table proving this is shown below:
![image](https://user-images.githubusercontent.com/11160611/48315316-8dce5980-e5cc-11e8-80a4-66656fceab5b.png)
These numbers were collected using [a benchmarker](https://github.com/DylanFPS/lazarus-benchmarker). We should alter the following lines in APILoader.cs
```cs
            _options = ImplementationOptions.EnableOptimizations |
                       ImplementationOptions.SuppressSecurity |
                       ImplementationOptions.GenerateDisposalChecks |
                       ImplementationOptions.EnableDllMapSupport;
```

To something more efficient. The calli tests on the table used the following options:
```cs
ImplementationOptions.UseIndirectCalls |
ImplementationOptions.EnableDllMapSupport |
ImplementationOptions.EnableOptimizations |
ImplementationOptions.SuppressSecurity
```

**Comment by jvbsl** [comment]
ADL isn't gonna be used anymore...(As you already now since long ago :D)
