### ISSUE TITLE
[4.0] Move Windowing subsystem into the new project.

### ISSUE THREAD

**Issue by daerogami** [opentk/opentk#866]
This issue will serve as a discussion for various aspects of the moving/re-implementation of the Windowing subsystem for the 4.0 milestone.

The related PR can be found in #867. Discussion specific to that should occur there.

There are a handful of items to discuss; the most prominent item on the table is moving to GLFW.

**Comment by DylanFPS** [comment]
Well, we’re going really modular in 4.0, so it would make sense to have these in separate projects. It’s also critical that we can bridge/use both GLFW and the GTK backends (i.e. for GLControl and GLWidget)

**Comment by Nihlus** [comment]
@DylanFPS - it's not needed for GTK. It operates without any backends, since it creates its own GL context.

**Comment by DylanFPS** [comment]
So GLFW is fully compatible with Android and the GLControls then?

**Comment by jvbsl** [comment]
GLControls should be possible, but Android and iOS are as far as I can tell not(yet?) supported by GLFW:
https://github.com/glfw/glfw/pull/1087

**Comment by Nihlus** [comment]
I suspect we'll have to use the native views on mobile platforms. I'm not familiar enough with them to make any assumptions.

**Comment by DylanFPS** [comment]
After extensive searching, Android and iOS aren't *officially* supported by GLFW. There is a PR open for Android support, and I'm sure there's a fork out there with iOS support somewhere; but I think we shouldn't use GLFW for those platforms - which isn't a problem at all, we'll just use GameViews like we did before.

**Comment by DylanFPS** [comment]
We've been talking about package/project structure/names in the Discord and we've determined that this is the best structure for the windowing subsystem:

- OpenToolkit.GraphicsLibraryFramework
  - Raw GLFW bindings
- OpenToolkit.Windowing.Desktop
  - GameWindow and NativeWindow using GLFW
- OpenToolkit.Windowing.Common
  - IGameWindow and INativeWindow
- OpenToolkit.Windowing.Android
  - AndroidGameView
- OpenToolkit.Windowing.iOS
  - AppleGameView

**Comment by Perksey** [comment]
Documenting the recent discussion in the Discord:

We (Nihlus, Void, and I) have decided that we are going to merge the Windowing and Input subsystems, as they are so closely related that it doesn't make sense to have an enitrely new subsystem solely for Input. Check the #development channel in the discord for this discussion.

**Comment by varon** [comment]
Closing as we've basically finished discussion here.
