### ISSUE TITLE
Vector3 (and mb another Vectors) GetHashCode function work wrong (has collision)

### ISSUE THREAD

**Issue by ALEXGREENALEX** [opentk/opentk#868]
### Description
Vector3(3f, 2f, 1f) hash is equal to Vector3(3f, 1f, 2f) hash. Maybe this collision works for another Vectors.

### Repro steps in Linq Pad (code changed for tests only!)
void Main()
{
	GetHashCode(3f, **2f**, **1f**).Dump();
	GetHashCode(3f, **1f**, **2f**).Dump();
}

int GetHashCode(float X, float Y, float Z)
{
    unchecked
	{
		var hashCode = X.GetHashCode();
		hashCode = (hashCode * 397) ^ Y.GetHashCode();
		hashCode = (hashCode * 397) ^ Z.GetHashCode();
		return hashCode;
	}
}

### Results:
1438646272
1438646272

### Possible solution, based on https://stackoverflow.com/a/892640/5849511:
return unchecked((713 + X.GetHashCode() * 31 + Y.GetHashCode()) * 31 + Z.GetHashCode());

**Comment by ALEXGREENALEX** [comment]
Yep, my fault, you are right. I have some troubles with comparing big arrays of Vector3 values at model loading process, it was too slow, and I wanted to use Hashes but founded collision at first tests, now I using vectors equal comparing instead and different algorithm. Sorry for wasting your time, good luck. Issue can be closed.

**Comment by jvbsl** [comment]
Dependent on what you are trying to do it could be faster to use precalculated hash and if there are collisions using direct comparison for exact results. But if it is already fixed it should not matter
