### ISSUE TITLE
How to initialize OpenGL bindings without creating window

### ISSUE THREAD

**Issue by WhoseTheNerd** [opentk/opentk#869]
**Not an issue.**

Can I initialize OpenTK GL bindings? I want to replace OpenTK window system with my own using Glfw.
OpenGL.Net is not perfect for me. Some functions are not close to OpenGL 3.
Neither Tao.OpenGL.

**Comment by jvbsl** [comment]
https://github.com/opentk/opentk/blob/3.0/src/OpenTK/Toolkit.cs#L81
so OpenTK.Toolkit.Init(), there is one overload as well...

**Comment by WhoseTheNerd** [comment]
Unfortunately it doesn't work. I get System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'.

**Comment by jvbsl** [comment]
https://github.com/opentk/opentk/blob/e911f0b7698e7bc32fa1c4eab37f9e50f7bd92a3/src/OpenTK.GLControl/GLControl.cs#L106
Perhaps this one helps. Otherwise I'm actually not too sure myself.
Which OS are you using?

**Comment by DylanFPS** [comment]
> I want to replace OpenTK window system with my own using Glfw
#867 coming in 4.0 :wink: :wink:

Also you should look into [GraphicsContext](https://opentk.net/api/OpenTK.Graphics.GraphicsContext.html) and [how the GameWindow uses it](https://github.com/opentk/opentk/blob/3.0/src/OpenTK/GameWindow.cs#L193).

**Comment by WhoseTheNerd** [comment]
> > I want to replace OpenTK window system with my own using Glfw
> 
> #867 coming in 4.0 😉 😉
> 
> Also you should look into [GraphicsContext](https://opentk.net/api/OpenTK.Graphics.GraphicsContext.html) and [how the GameWindow uses it](https://github.com/opentk/opentk/blob/3.0/src/OpenTK/GameWindow.cs#L193).

Only thing is that I cannot find _WindowInfo_, only thing I found was _IWindowInfo_. _GraphicsContext_ and _GraphicsContext.MakeCurrent_ requires it

**Comment by DylanFPS** [comment]
Let's have a look at what you actually need to do here. You've challenged yourself with using GLFW, awesome! So using whatever method creates a window handle in GLFW, you need to run that and get an `IntPtr`. Once you've got that, you can make your own implementation of `IWindowInfo` and what have you.

FYI, `WindowInfo` is the name of a property in `NativeWindow`.

**Comment by WhoseTheNerd** [comment]
I tried.
_System.InvalidCastException: 'Unable to cast object of type 'CopeEngine.WinInfo' to type 'OpenTK.Platform.Windows.WinWindowInfo'.'_

Code: https://pastebin.com/DATWG5qQ

**Comment by DylanFPS** [comment]
Can I have the full exception to ease investigation?

**Comment by WhoseTheNerd** [comment]
This was Full exception?
This is my exception in output: https://pastebin.com/skErLwd6
Pastebin, because hard to read that in this limited width comment section.

**Comment by DylanFPS** [comment]
I'm afriad it's likely you're going to need to make a whole GLFW [platform](https://github.com/opentk/opentk/tree/e911f0b7698e7bc32fa1c4eab37f9e50f7bd92a3/src/OpenTK/Platform) for this, as the other ones are still trying to take initiative, so this is going to be a big task for you. Optionally, you could wait until the `GameWindow` API maps to GLFW in 4.0 - so you could write your engine with the current GameWindow API, and then it's a matter of updating to be able to use GLFW.

**Comment by WhoseTheNerd** [comment]
Is OpenTK 4.0 going to be modular? Bindings in separate module, windowing in another, and etc?

**Comment by DylanFPS** [comment]
Yep, fully modular.

**Comment by WhoseTheNerd** [comment]
I guess issue can be closed.
