### ISSUE TITLE
[4.0] AOT Build Step for iOS (and, optionally, all platforms)

### ISSUE THREAD

**Issue by Perksey** [opentk/opentk#870]
## Premable

With great restrictions on the reflection functionality on iOS, we have to do some maneuvering to get ADL working. Luckily, the repo includes an AOT compiler that we could utilise so that instead of assemblies being generated at runtime, all we have to do is load a DLL file. 

## My Proposal
- We add a target which will execute the AOT compiler.
- This target will convert the exported assembly into an `EmbeddedResource`, so that it can be loaded in without extra DLLs being exported.
- We'll need to add an AOT overload to the library loader that will get the assembly for the given subsystem, and check for an embedded resource starting with DLSupportDynamicAssembly. This way we can still use non-AOT for debugging, and it's just a lot smarter tbh.

I'm willing to work on this one.

#### ~~Blocked by Firwood-Software/AdvanceDLSupport#63~~

**Comment by Nihlus** [comment]
Something to note is that the AOT compiler for ADL is currently experimental, and needs some love to be a publishable, usable project for general consumption. Primarily, it produces multiple files (an assembly and separate modules), which is not ideal, and it's also not available in an easily consumable form, like a nuget package.

PRs to ADL to address these issues, and any other that might crop up, will be neccesary.
