### ISSUE TITLE
Please stop "ban" to me!

### ISSUE THREAD

**Issue by SourceSkyBoxer** [opentk/opentk#874]
Hello everyone,

What do you mean "ban"? If you ban. It like you are kidding me. I will report you and I will show you to police in Germany. I didn't rarest. I help you. Thank you for hurting!

I will remove my account Discord now.
Because I can't use other. you understand me wrong. I always explain explain explain explain explain explain. I will report your to government now

Jan... is kidding banner

Thank you for ignoring my tutorials. I am very disappointed now. I will call police. Whatever

I AM SERIOUS DEAF! WHY DO YOU HURT MY DEAFNESS???

I EXPLAIN SINCE AUGUST 2018 - Why do you about "SPAM" THAT IS NOT CORRECTLY. YOU MISS UNDERSTAND - I WILL REMOVE YOUR OPENTK NOW: I DON'T CARE YOU NOW - BYE BYE

**Comment by Nihlus** [comment]
You were banned for spamming, insulting multiple members of the server, insinuating that gender played a role in our choice of tutorials, and being a general pain in the ass. Goodbye, and happy holidays.

**Comment by DylanFPS** [comment]
This is not a place to raise issues for our Discord server, but let me address your points anyway.

> I will report you and I will show you to police in Germany.

You were harassing people on social media. You will not be able to make a criminal case out of this, and if you did there's reasonable evidence to suggest that you're in the wrong.

> I will remove my account Discord now. Because I can't use other. you understand me wrong. 

You have no need to do this, but ok.

> I always explain explain explain explain explain explain. I will report your to government now

Same point made in the police argument.

> Thank you for ignoring my tutorials. I am very disappointed now.

Is this really what this is about? Your tutorials? We have our own tutorials in the making and, while you could sensibly contribute to them by opening a PR in Devvoid's repo, you instead bombarded our Discord needlessly. 

> I AM SERIOUS DEAF! WHY DO YOU HURT MY DEAFNESS???

We are not discriminating against your disability, nor did we ever imply that we was.

> Why do you about "SPAM" THAT IS NOT CORRECTLY.

You *were* spamming though, and I did make a suggestion that would stop the spam having such an impact. You were breaking the rules of our discord server, and as they state moderators have the final say. Regardless of whether you argue, you were in violation of our rules!

**Comment by DylanFPS** [comment]
Another point to note that you keep brining up.

> I EXPLAIN SINCE AUGUST 2018

The time in which you made these tutorials is irrelevant if you didn't pitch them to us at that time! @devvoid was the first to pitch LearnOpenTK to us and, as such, he is the author of our official tutorials.

**Comment by varon** [comment]
Well done @Nihlus / @DylanFPS . That was very professionally handled.

This seems like a good candidate for using the new permanent issue deletion functionality as it has no relation to OpenTK at all. Unless we get some objections I'll permanently remove this issue in the next few days.

**Comment by Perksey** [comment]
@varon I think it's safe to say this can be permenantly removed.
