### ISSUE TITLE
Android EGL Segfault

### ISSUE THREAD

**Issue by DeathByAlgorithm** [opentk/opentk#879]
### EGL GetAddress SEG_FAULT

Ran into a problem running OpenTK on Android that I've fixed in my own native library recently, thought I would share.

[EGL_KHR_get_all_proc_addresses](https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_get_all_proc_addresses.txt)

Since using _EGL_NO_DISPLAY_ with **eglQueryString** isn't supported until EGL 1.5 and the client extension _EGL_KHR_client_get_all_proc_addresses_ is retrieved that way, I'm going to ignore it here and focus on the display/context extension.

If _EGL_KHR_get_all_proc_addresses_ does not exist in the extension list then it is safe to assume that retrieving via the native routes (**GetProcAddress**, **dladdr**, **dlsym**, ...) is fine.

If _EGL_KHR_get_all_proc_addresses_ exists then there should be an EGL version check and corrective action for loading functions
Case 1. EGL >= 1.5: only use **eglGetProcAddress** for obtaining both EGL extensions and GL functions
Case 2. EGL <= 1.4: Check for _EGL_KHR_get_all_proc_addresses_ if it exists then use Case 1 else use native routines.

[EglContext.cs :: 223](https://github.com/opentk/opentk/blob/master/src/OpenTK/Platform/Egl/EglContext.cs)
```cs
public override IntPtr GetAddress(IntPtr function)
{
    // Try loading a static export from ES2
    var address = GetStaticAddress(function, Renderable);// <-- This will always be non-zero

    // If a static export is not available, try retrieving an extension
    // function pointer with eglGetProcAddress
    if (address == IntPtr.Zero)// <-- This will always be false
    {
        address = Egl.GetProcAddress(function); // <-- Never retrieved
    }

    return address;
}
```

Any subsequent call to a function retrieved from **Egl.GetAddress** in it's current state will result in a segfault unless _EGL_KHR_get_all_proc_addresses_ wasn't in the extension list.

**Comment by varon** [comment]
If you managed to get OpenTK 3.0.x running on android, that's a pretty impressive feat!

We're not really maintaining that branch as all new work is focused on 4.0. We're happy to accept PRs against 3.0.x though, so please do submit a fix if you can spot where it's going wrong!

**Comment by varon** [comment]
Android is not currently a targeted platform, although we'd welcome PRs to help ensure it is.
