### ISSUE TITLE
CapEnableCap.AlphaTest can not be recongnized when using OpenTK.Graphics.OpenGL4

### ISSUE THREAD

**Issue by ShannonZ** [opentk/opentk#886]
### Description
I want to translate this project to C# using OpenTK. But I cannot find the equivalent  code using OpenTK
`glEnable( GL_ALPHA_TEST );   
glAlphaFunc( GL_GREATER, 0.03f );`

CapEnableCap.AlphaTest can not be recongnized when using Graphics.OpenGL4.

I've tried to use ` EnableCap.SampleAlphaToCoverage`  and other SampleAlphaXXX flags, but these all seem to not equivalent to C++ code `glEnable( GL_ALPHA_TEST );`.

### Related information 

* Win10 x64
* Native backend
* NuGet Latest Version 3.0.1.0
* .NET Framework 4.7

**Comment by jvbsl** [comment]
https://stackoverflow.com/questions/24302152/opengl-alpha-test-how-to-replace-alphafunc-deprecated
The reason that it is missing is, that it is deprecated since version 3.1, therefore you need to do it yourself in the fragment shader....

**Comment by ShannonZ** [comment]
Clear Enough! Thank you @jvbsl
