### ISSUE TITLE
point cloud processing: opentk algorithms for calculate the average of the points and eliminate outliers

### ISSUE THREAD

**Issue by nico144** [opentk/opentk#890]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe.

### Related information 

* Operating system
* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code)
* What runtime (.NET Framework, CoreCLR, Mono)
* Workarounds (if any)

**Comment by nico144** [comment]
point cloud processing: on opentk are there algorithms that calculate the average of the points and draw a line eliminating the outliers?

**Comment by jvbsl** [comment]
No, things like this need to be implemented by oneself. Easiest would be to do it in C# code directly before. Other possibility would be a computation shader which is gonna be more complex and dependent on where you need the data at the end not necessarily faster.

**Comment by subchannel13** [comment]
OpenTK is not statistics library. Maybe you can get average through shader and texture magic but I doubt you could get meaningful outlier elimination.

**Comment by nico144** [comment]
> No, things like this need to be implemented by oneself. Easiest would be to do it in C# code directly before. Other possibility would be a computation shader which is gonna be more complex and dependent on where you need the data at the end not necessarily faster.



and how to implement a computational shader?

**Comment by jvbsl** [comment]
https://www.khronos.org/opengl/wiki/Compute_Shader
like this. Or with things like OpenCL/CUDA, which where specifically made for GPU computation.
So if you do not intend to do anything like drawing later on with your data. It would make sense to use OpenCL/CUDA directly.
