### ISSUE TITLE
Glcontrol multithreading

### ISSUE THREAD

**Issue by nico144** [opentk/opentk#891]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe.

### Related information 

* Operating system
* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code)
* What runtime (.NET Framework, CoreCLR, Mono)
* Workarounds (if any)

**Comment by nico144** [comment]
I should display two glcontrol windows that display and process together and by looking at the various forums I noticed that one of the methods used is calling the MakeCurrent () method in every Glcontrol call. the problem with this method is that the processing does not take place simultaneously. so I thought I could use two threads that incorporate the two GlControls. however, seeing some examples on the internet I can't implement it in the GlControl_Paint having this errors 

![Immagine](https://user-images.githubusercontent.com/49307235/55783600-146d6100-5aaf-11e9-8d14-729a0f745bb1.png)

**Comment by jvbsl** [comment]
I don't get what you are trying to achieve by creating a thread in the paint event?
If you want to have to independant render loop, use two context and make them current on the thread you are working on. It just needs to be done once as contexts are thread bound...

**Comment by varon** [comment]
If you want to open an issue for discussion, please take the time to actually use the issue template.

**Comment by varon** [comment]
And for simple questions like this, feel free to ask in the [OpenTK Discord channel](https://discord.gg/6HqD48s).
