### ISSUE TITLE
[4.X] API Symmetry between System.Math and OpenToolkit.Math

### ISSUE THREAD

**Issue by Perksey** [opentk/opentk#893]
### Preamble 
We've been discussing with end users and they have found it's particularly annoying that OpenTK doesn't have common math functions such as cosine, sine, and tangent functions.

### Goals
We want to discuss whether it's worth implementing these functions to prevent the end user being forced to use both the System.Math and OpenToolkit.Math namespaces simultaneously.

### See also
#892 
#895

**Comment by frederikja163** [comment]
I think it would be a really nice improvement, as i find it annoying whenever im looking for something math related i have to first look in System.Math and if it is not in there i have to look in OpenToolkit.Math. I would even be the one doing all of this if it is just a question of who is going to do it.

**Comment by jvbsl** [comment]
If the Implementation itself uses System.Math, i think it is fine todo so an not that much work either.

**Comment by Perksey** [comment]
Yeah it's fine if it uses Sys.Math internally, still achieves the API symmetry we need. Open a PR ;)

**Comment by Perksey** [comment]
Fixed by #897
