### ISSUE TITLE
How can I stop textures from blurring?

### ISSUE THREAD

**Issue by Lauriethefish** [opentk/opentk#899]
### Description

Basically, When I try to render a low resolution texture it blurs  tons. I saw that in C++ you can do this to fix it:

glTexParameterf( GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

But I can't find the C# equivilants of "GL_TEXTURE_MAG_FILTER" and "GL_NEAREST"

### Repro steps

1. Render a texture with low resolution (32x32px onto a quad)

2. Run program

### Expected behavior

The texture appears and keeps its normal pixels and doesn't blur.

### Actual behavior

The texture is completely blurred and looks awful.

### Related information 

OS: Windows 10
Version: Installer
Framework: .NET Framework
Backend: Native (I think, I'm not sure)

**Comment by jvbsl** [comment]
There are TextureParameterName.TextureMagFilter(or All.TextureMagFilter) and TextureMagFilter.Nearest(or All.Nearest).

**Comment by Lauriethefish** [comment]
Thank You!
