### ISSUE TITLE
Change the official repository to normal repository

### ISSUE THREAD

**Issue by prokopst** [opentk/opentk#90]
Just a proposal: Please change the official repository from fork to normal repository. To do it, owner of the repository needs to contact the Support (see the [article](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile#how-are-commit-contributions-to-forks-counted) and click on the note)

Why? It was quite confusing for me that official OpenTK repository is a fork of [thefiddler/opentk](https://github.com/thefiddler/opentk), which is actually a fork of [andykorth/opentk](https://github.com/andykorth/opentk). Although I now understand the reason, it still might be confusing for all newcomers.

**Comment by Frassle** [comment]
@thefiddler probably needs to send the support request for this, his the only one marked as project owner, not sure if support will follow through a request like this from a contributor.

**Comment by varon** [comment]
Done.
