### ISSUE TITLE
Mouse.GetState() does not report mouse position of trackpad on Mac

### ISSUE THREAD

**Issue by pabakal1** [opentk/opentk#901]
### Description
Using Mouse.GetState() returns (0,0) for position when using the trackpad. Using an external mouse works. This cannot be fixed with Mouse.GetState(int).

### Repro steps
Call: Console.WriteLine(Mouse.GetState()); in an update frame function.

### Expected behavior
It should return the X and Y displacement of your mouse

### Actual behavior
It returns (0,0)

### Related information 

* MacOSX 10.13.6
* Native
* NuGet latest version
* .NET 
* Working workaround: plug in an external mouse

**Comment by varon** [comment]
Thanks for the report. This will probably be fixed via OpenTK 4.0.

Good work on the workaround.

**Comment by varon** [comment]
Should be fixed by 4.x

**Comment by BuslikDrev** [comment]
> Should be fixed by 4.x

Is it fixed in OpenTK v3.3.3 too?
