### ISSUE TITLE
Multiple glControl on same winform is not working - OpenTK C#

### ISSUE THREAD

**Issue by DivyaZolio** [opentk/opentk#907]
I have to show frames from two cameras in two openGl control separately at same time. For that I have put two opengl control in my form and pass those frames to opengl accordingly. But when running the app, only second opengl control is working. First one is remain with black screen. When i remove the second opengl control first one is working. Means only one is working at a time. Can I solve this? Please check my code.

     `Bitmap videoFrame = null;//should show this frames in glcontrol1
     Bitmap videoFrame2 = null;//should show this frames in glcontrol2
     IGraphicsContext control2Context;
     openTK obj_openTK = new openTK();//common class for opengl functions
     private void Show_Click(object sender, EventArgs e)
      {
     control2Context = new GraphicsContext(GraphicsMode.Default, glControl2.WindowInfo);
    GL.ClearColor(Color.MidnightBlue);
    GL.Enable(EnableCap.DepthTest);
    TexUtil.InitTexturing();
    GL.Hint(HintTarget.PerspectiveCorrectionHint, HintMode.Nicest);
    GL.DepthFunc(DepthFunction.Lequal);
    GL.ColorMaterial(MaterialFace.FrontAndBack, ColorMaterialParameter.AmbientAndDiffuse);
    GL.Enable(EnableCap.ColorMaterial);
    GL.Enable(EnableCap.Blend);
    GL.BlendFunc(BlendingFactor.SrcAlpha, BlendingFactor.OneMinusSrcAlpha);
    GL.Ext.BindFramebuffer(FramebufferTarget.FramebufferExt, 0); // render per default onto screen, not some FBO

    glControl1.Resize += new EventHandler(glControl1_Resize);
    glControl1.Paint += new PaintEventHandler(glControl1_Paint);
    glControl2.Resize += new EventHandler(glControl2_Resize);
    glControl2.Paint += new PaintEventHandler(glControl2_Paint);

    Application.Idle += Application_Idle;
    glControl1_Resize(glControl1, EventArgs.Empty);
    glControl2_Resize(glControl2, EventArgs.Empty);
    }
    private void Application_Idle(object sender, EventArgs e)
     {
    while (glControl1.IsIdle)
    {
    glControl1.MakeCurrent();
    Render();
    GL.Flush();
    glControl1.SwapBuffers();

    control2Context.MakeCurrent(glControl2.WindowInfo);
    Render2();
    GL.Flush();
    glControl2.SwapBuffers();
    }
    }
     public void Render ()
     {
       GL.BindFramebuffer(FramebufferTarget.Framebuffer, 0); // use the visible framebuffer
      if (videoFrame != null)
        lock (videoFrame)//frames from video 1
        {
            if (videoTexture != -1)
            GL.DeleteTextures(1, ref videoTexture);
            videoTexture = LoadTexture(videoFrame);
            videoFrame.Dispose();
            videoFrame = null;
        }
    GC.Collect();
    GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
    obj_openTK.DrawImage(videoTexture, glControl1);
      }
     public void Render2()
      {
      GL.BindFramebuffer(FramebufferTarget.Framebuffer, 0); // use the visible framebuffer
      if (videoFrame2 != null)
      lock (videoFrame2) // frames from video 2
        {
            if (videoTexture2 != -1)
            GL.DeleteTextures(1, ref videoTexture2);
            videoTexture2 = LoadTexture(videoFrame2);
            videoFrame2.Dispose();
            videoFrame2 = null;
        }
      GC.Collect();
      GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
      obj_openTK.DrawImage(videoTexture2,glControl2);
       }
     private void glControl1_Paint(object sender, PaintEventArgs e)
      {
    obj_openTK .Render();
     }
    private void glControl1_Resize(object sender, EventArgs e)
    {
    obj_openTK.Init();
    }
    private void glControl2_Paint(object sender, PaintEventArgs e)
    {
    obj_openTK.Render2();
     }
     private void glControl2_Resize(object sender, EventArgs e)
     {
      obj_openTK.Init();
      }
      ===========================================================
      class openTK
      {
        int positionLocation1;
        int program;
        int positionLocation;
        int vertShader;
        int fragShader;
        int buffer;
        float[] vertices = {
                // Left bottom triangle
                -1f, -1f, 0f,
                1f, -1f, 0f,
                1f, 1f, 0f,
                // Right top triangle
                1f, 1f, 0f,
               -1f, 1f, 0f,
               -1f, -1f, 0f
        };
  
        public int LoadTexture(Bitmap bitmap)
        {
            int tex = -1;
            if (bitmap != null)
            {
                GL.Hint(HintTarget.PerspectiveCorrectionHint, HintMode.Nicest);

                GL.GenTextures(1, out tex);
                GL.BindTexture(TextureTarget.Texture2D, tex);

                bitmap.RotateFlip(RotateFlipType.RotateNoneFlipY);
                BitmapData data = bitmap.LockBits(new System.Drawing.Rectangle(0, 0, bitmap.Width, bitmap.Height),
               ImageLockMode.ReadOnly, System.Drawing.Imaging.PixelFormat.Format32bppArgb);

                GL.TexImage2D(TextureTarget.Texture2D, 0, PixelInternalFormat.Rgba, data.Width, data.Height, 0,
                OpenTK.Graphics.OpenGL.PixelFormat.Bgra, PixelType.UnsignedByte, data.Scan0);
                bitmap.UnlockBits(data);

                GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)TextureMinFilter.Linear);
                GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)TextureMagFilter.Linear);
                GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapS, (int)TextureWrapMode.ClampToEdge);
                GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureWrapT, (int)TextureWrapMode.ClampToEdge);
            }
            return tex;
        }
        public void DrawImage(int image, GLControl glControl)
        {
            GL.MatrixMode(MatrixMode.Projection);
            GL.PushMatrix();
            GL.LoadIdentity();
            GL.MatrixMode(MatrixMode.Modelview);
            GL.PushMatrix();
            GL.LoadIdentity();
            GL.Disable(EnableCap.Lighting);
            GL.Enable(EnableCap.Texture2D);
            GL.ActiveTexture(TextureUnit.Texture0);
            GL.BindTexture(TextureTarget.Texture2D, image);
            GL.Uniform1(positionLocation1, 0);
            
            RunShaders();

            GL.Disable(EnableCap.Texture2D);
            GL.PopMatrix();

            GL.MatrixMode(MatrixMode.Projection);
            GL.PopMatrix();

            GL.MatrixMode(MatrixMode.Modelview);

            ErrorCode ec = GL.GetError();
            if (ec != 0)
                System.Console.WriteLine(ec.ToString());
            Console.Read();            
        }
    private void RunShaders()
    {
    GL.UseProgram(program);
    GL.DrawArrays(PrimitiveType.Triangles, 0, vertices.Length / 3);
    ErrorCode ec = GL.GetError();
    if (ec != 0)
        System.Console.WriteLine(ec.ToString());
    Console.Read();
     }   
       private void Init()
    {
    CreateShaders();
    CreateProgram();
    InitBuffers();
     }  
    private void CreateProgram()
    {
    program = GL.CreateProgram();
    GL.AttachShader(program, vertShader);
    GL.AttachShader(program, fragShader);
    GL.LinkProgram(program);
    }
     private void InitBuffers()
     {
    buffer = GL.GenBuffer();
    positionLocation = GL.GetAttribLocation(program, "a_position");
    positionLocation1 = GL.GetUniformLocation(program, "sTexture");
    GL.EnableVertexAttribArray(positionLocation);
    GL.BindBuffer(BufferTarget.ArrayBuffer, buffer);
    GL.BufferData(BufferTarget.ArrayBuffer, (IntPtr)(vertices.Length * sizeof(float)), vertices, BufferUsageHint.StaticDraw);
    GL.VertexAttribPointer(positionLocation, 3, VertexAttribPointerType.Float, false, 0, 0);
     }
        private void CreateShaders()
      {
    /***********Vert Shader********************/
    vertShader = GL.CreateShader(ShaderType.VertexShader);
    GL.ShaderSource(vertShader, @"attribute vec3 a_position;
                                varying vec2 vTexCoord;
                                void main() {
                                vTexCoord = (a_position.xy+1)/2 ;
                                gl_Position = vec4(a_position, 1);
                                }");
    GL.CompileShader(vertShader);

    /***********Frag Shader ****************/
    fragShader = GL.CreateShader(ShaderType.FragmentShader);
    GL.ShaderSource(fragShader, @"precision highp float;
    uniform sampler2D sTexture;varying vec2 vTexCoord; 
                         void main ()
                         {
                       vec4    color   = texture2D (sTexture, vTexCoord);
                       gl_FragColor    = color;                 
                         }");
    GL.CompileShader(fragShader);
        }`
      }`

**Comment by jvbsl** [comment]
You either use shared Contexts, so that both controls can access the OpenGL data, or you create all the data for each control seperately.
As far as I can tell the current implementation of GLControl cannot do context sharing. Therefore you would have to implement it yourself, or use the second option.
But there is a third option still: Do not use 2 GLControls, but use 2 Framebuffers and render your cameras into each one. Then you render the framebuffers into the one GLControl at the positions you want...

**Comment by DivyaZolio** [comment]
> you create all the data for each control seperately.
Can you please explain it ? Shall I need to write  "CreateShaders();
    CreateProgram();
    InitBuffers();" functions separately for two opengl controls?

> You either use shared Contexts,
I'm totally new to it. Is it easy to implement on my current code?

**Comment by jvbsl** [comment]
1. Well creating the data or each one can easily be done by creating a class which encapsulates the functionality into a class. Were you then create two instances of it(one for each control).
2. You can't as it is something that would need to be implemented into OpenTK itself. Meaning you would need to change the OpenTK code by yourself.

But there is still the third option I told you about, which - I could imagine - is the most fitting for your problem anyhow.

**Comment by DivyaZolio** [comment]
I was doing it by third option and it was working well. Now client asked to do it in two different  opengl controls. I will try with first option

**Comment by jvbsl** [comment]
Why does it need to be in two different Controls? Is it in different windows? Does they need to be moved around in a WinForms Window, with a lot of non GL controls?

**Comment by DivyaZolio** [comment]
No , they want to apply  a type of projection on these two different frames.

**Comment by jvbsl** [comment]
That is entirely possible with framebuffers though^^

**Comment by DivyaZolio** [comment]
But calculations will be bit more complex then. right? It will be not easy when need to apply cylindrical projection on one texture. and spherical on another one.

**Comment by jvbsl** [comment]
Well if it is about projections onto a Mesh or the projection of the scene itself, it is just the same as you would do it with GLControls.

**Comment by DivyaZolio** [comment]
I have tried as you suggested. But the result is same. only second glcontrol is working. Can you please guide me on this? what I have done is :
Created a separate class. 
And wrote below functions in it -  
" LoadTexture(), DrawImage(),RunShaders()CreateShaders();CreateProgram(),InitBuffers()"
which is called for both glcontrol. 
`   GL.ClearColor(Color.MidnightBlue);
    GL.Enable(EnableCap.DepthTest);
    TexUtil.InitTexturing();
    GL.Hint(HintTarget.PerspectiveCorrectionHint, HintMode.Nicest);
    GL.DepthFunc(DepthFunction.Lequal);
    GL.ColorMaterial(MaterialFace.FrontAndBack, ColorMaterialParameter.AmbientAndDiffuse);
    GL.Enable(EnableCap.ColorMaterial);
    GL.Enable(EnableCap.Blend);
    GL.BlendFunc(BlendingFactor.SrcAlpha, BlendingFactor.OneMinusSrcAlpha);
    GL.Ext.BindFramebuffer(FramebufferTarget.FramebufferExt, 0); // render per default onto screen, not some FBO
`
These lines are written as it is in page load. Is there any change made to it?

**Comment by jvbsl** [comment]
Well as you can't use different threads. You need to make the Context of each GLControl current, before doing anything OpenGL related(GLControl.MakeCurrent). And everything OpenGL related you do needs to be done for each GLControl seperately.
But still doing it with framebuffers would be much easier in my opinion and less error prone(easier to debug) as well.

**Comment by DivyaZolio** [comment]
@jvbsl 
Thankyou for your suggestion on framebuffer. But unfortunately i have to follow separate glcontrol method. As you said I have set GLControl current.

>  glControl1.MakeCurrent();
    Render();
    GL.Flush();
    glControl1.SwapBuffers();

    

> control2Context.MakeCurrent(glControl2.WindowInfo);
>     Render2();
>     GL.Flush();
>     glControl2.SwapBuffers();

Can you please check my current code? And suggest what causes the issue?

**Comment by jvbsl** [comment]
Unfortunately I can't see anything wrong at first.
How about ressource creation it needs to be done for each context individually as well.
Could you read GL errors and lookup if there is anything showing up?
If it does not show anything could you try getting debug Messages as well using following approach:
https://github.com/opentk/opentk/issues/880#issuecomment-455863791

**Comment by DivyaZolio** [comment]
No GL errors is showing. Tried to debug messages by using  _hijackCallback() . But it shows invalid argument exception at "Marshal.GetDelegateForFunctionPointer"

**Comment by jvbsl** [comment]
You need to lookup where the actual EntryPoint is in your version of OpenTK. For that you would need to decompile your OpenTK.dll(e.g. using dnSpy). Where you lookup the DebugMessageCallback method(be careful to use the correct GL class - the same you are actually using inside your code). There should be a Code like _entryPoints[SOMENUMBER]. Where you then use that "SOMENUMBER" and use it inside your hijackCallback function.

**Comment by DivyaZolio** [comment]
By making some changes in context of glcontrol I can now see first image in first glcontrol. But on scond glcontrol , it throws an exception 

> OpenTK.Graphics.GraphicsContextException: 'Failed to swap buffers for context 131072 current.

Can you help ?

**Comment by jvbsl** [comment]
Isn't there some additional message in that exception. Because in the sourcecode I saw there would be.
Which platform are you actually on?
One thing which I could see as a problem is the use of texture for both GLControl1 and 2. Better use texture1, texture2. As it seems one control now tries to delete a texture from the other context, which would be wrong...

**Comment by DivyaZolio** [comment]
Tried by using use texture1, texture2.  no luck.  One thing I found that , before completing "Render2" function of  glControl2_Paint event,  glControl1_Paint is calling. Thats why swapbuffer written in paint2 event throws exception

**Comment by jvbsl** [comment]
Wait, that should not be possible to happen, as they should be synchronous. They are in the same Form, right, and you did not something with threads, right?

**Comment by DivyaZolio** [comment]
no, I'm not performing anything with thread now. Is that the issue?

**Comment by jvbsl** [comment]
No, that was formulated wrongly on my side. You should not use threads in this case. And therefore Render and Render2 should be called completely synchronously.What is printed if you print Thread.CurrentThread.ManagedThreadId in both functions. (It should print the same value)

**Comment by DivyaZolio** [comment]
Thread.CurrentThread.ManagedThreadId =1 in both render and render2 functions

**Comment by DivyaZolio** [comment]
I have opened a new issue on this 
https://github.com/opentk/opentk/issues/916
Please check

**Comment by Perksey** [comment]
Conversation has been moved to #916
