### ISSUE TITLE
OpenTK.NetStandard context creation behaves differently when in debug mode in a netcore 3.0 app

### ISSUE THREAD

**Issue by erarz** [opentk/opentk#910]
### Description

OpenGL Context creation doesnt work when starting in debugmode using VisualStudio Code, but works correctly when starting manually.

### Repro steps

1. Step 1

Create a new netcoreapp(3.0) with dotnetnew and open it with VisualStudio Code

2. Step 2

Install OpenTK.NetStandard with NuGet

3. Step Create a Window and request a 3.0 context

```
class Window : GameWindow
{
    public Window(int width, int height, string title) : base(
            width, 
            height, 
            new GraphicsMode(), 
            title, 0,  
            DisplayDevice.Default, 3, 0, 
            GraphicsContextFlags.ForwardCompatible | GraphicsContextFlags.Debug)
    {
        Console.WriteLine(GL.GetString(StringName.Version));            
    }
}
```

### Expected behavior

A 3.0 context is always created if the hardware supports it

### Actual behavior

When starting the app by clicking the .exe the logging shows a 3.0 context
When starting the app by using dotnet run in the terminal logging shows a 3.0 context
When starting the app in debug in VisualStudio Code (F5) a 1.1.0 context is created instead
resulting in any modern GL function to crash (all of them work fine when started manually).

### Related information 

* Windows 10
* OpenTK.NetStandard
* Installed with NuGet latest Version
* Intel HD 3000 Graphics Card (Supports GL 3.0)

**Comment by Perksey** [comment]
OpenTK currently only supports .NET Framework. We will support .NET Standard in 4.0. OpenTK.NetStandard is an unofficial package.

**Comment by peppy** [comment]
Hesitant to still mention our (also) unofficial fork, but we are running without issue on netcore30 (windows, linux, mac, iOS) https://www.nuget.org/packages/ppy.OpenTK/.

I just double-checked on windows with Visual Studio 2019 and .net core 3.0 preview 5 and am getting a 4.x context successfully, debug or no debug:

```
2019-05-24 05:18:58: GL Initialized
2019-05-24 05:18:58: GL Version:                 4.6.0 NVIDIA 419.67
2019-05-24 05:18:58: GL Renderer:                GeForce GTX 1080 Ti/PCIe/SSE2
2019-05-24 05:18:58: GL Shader Language version: 4.60 NVIDIA
```

**Comment by Perksey** [comment]
At this point, I encourage the use of your fork for our 3.0 API as, let's be honest, we're not gonna provide support for 3.X after 4.0's

**Comment by peppy** [comment]
It's likely we will also not offer support after 4.0. More of an interim thing as we are pushing forward on development in other areas until 4.0 is in a stable state to assess upgrade or otherwise.

**Comment by Perksey** [comment]
Understood. An upgrade from 3.0 to 4.0 will be impressive, have told a few people that it’s too much of a breaking change to be feasible but I reckon you’re the sort of maniac to pull it off haha :D
