### ISSUE TITLE
Add debug build of OpenTK to nuget package

### ISSUE THREAD

**Issue by Frassle** [opentk/opentk#92]
One of the first responses to people having problems with OpenTK is to run their program with a debug build of OpenTK. Currently this requires them to download and build from source. We could instead put a debug build in the nuget package meaning that uses would just need to change the assembly reference. 

Added bonus if it's possible would be to change between release and debug version of OpenTK based on the users debug/release option in their project, I'm not sure if this part is possible.

**Comment by daerogami** [comment]
@opentk/maintainers Is this still relevant? I imagine most devs just pull source and compile for debug when things get hairy but having a nuget package for debug would be convenient.

**Comment by tzachshabtay** [comment]
I would say still relevant (counting the "added bonus" in that). I currently link a debug build of OpenTK to my debug option and a release build to OpenTK to my release option, so I get all the errors when developing. I would like to migrate to Nuget once the Android+IOS builds are included, and still have my debug option linked to the debug build.

**Comment by varon** [comment]
This is something we should look at.
From what I can tell, automated swapping isn't doable, at least not without requiring people manually edit project files for conditional inclusion.

My suggestion from here would be to set up a development feed for the NuGet Packages: We can publish development builds to that, and this also gives us an uncluttered way of pushing out a development package, too.

We'll just need to figure out how we want to do it and add it to the build process.
