### ISSUE TITLE
VB.Net function resolution failure

### ISSUE THREAD

**Issue by maxwills** [opentk/opentk#93]
In the forum I described a problem with function overloads in VB.Net.(http://www.opentk.com/node/3554)
When I installed the new (last version avaliable from the main page) this seemed solved. however, when I tried to build OpenTK from souce, to get a debug dll, the problem came back. The release build of OpenTk has the same problem also.
In the forum, "the fiddler" said it is working now, and I think it is, but only from the binaries that are obtained when installing opentk 1.1 installers. If I compile the solution from source, with visual studio 2010, the problem reapears.

**Comment by daerogami** [comment]
Closed due to age.
