### ISSUE TITLE
Using OpenTK with existing OpenGL(ES) context with custom glGetProcAddress

### ISSUE THREAD

**Issue by kekekeks** [opentk/opentk#939]
We have some existing code with pre-initialized OpenGL(ES) context that is sometimes provided by a custom native library. Is it possible to utilize it with OpenTK?

**Comment by realvictorprm** [comment]
As long as the calls being made are for the same native open gl lib OpenTK 4 should do what you need.

**Comment by kekekeks** [comment]
The thing is, we switch the native library dynamically. e. g. on Linux it might be the classic libGL or libEGL (either desktop GL or GLES, X11/Wayland/GBM) or libosmesa, on windows it could be WGL or ANGLE, on OSX it might be NSOpenGLContext or MoltenGL. Internally we use `*glGetProcAddress` pointer provided by the current configuration. We don't know in advance which one will be used on a particular system.

Is it possible to configure OpenTK with a custom `*glGetProcAddress` pointer?

**Comment by realvictorprm** [comment]
OK this can be made possible with the new OpenTK version

**Comment by realvictorprm** [comment]
we can talk about details on the OpenTK discord @kekekeks

**Comment by varon** [comment]
@kekekeks  this is possible now in 4.x. You just need to provide an `IBindingsContext` with your custom GetProcAddress to the `GL.LoadBindings` method.
