### ISSUE TITLE
BufferData method doesnt exist in OpenTK.Graphics.OpenGL.GL class.

### ISSUE THREAD

**Issue by metacritical** [opentk/opentk#942]
### Description
I was trying to follow OpenTK Tutorials and When i referred to the API documentation there is no `BufferData` class. So i tried to import the following class anyway.
`OpenTK.Graphics.OpenGL.GL`. So The namespace exist and i can call other methods like `BufferTarget` or `BindBuffer`.  But it doesnt seem to have `BufferData` and gives following error when attempted to call it.

`Unhandled Exception:
System.MissingMethodException: Cannot find member BufferData matching args`

### Repro steps

I am trying to use OpenTK from Clojure/CLR on Mono on a mac.  The Basic window opening creation and CornFlower window stuff worked. But when i tried to access `BufferData` method in `GL`class it doesnt exist.

### Expected behavior

Atleast according to the Learn OpenTK this method should exist but it is not even documented in API section. I am not sure what is the actual behavior.

### System Info

* MacOS
* SDL Backend.
* OpenTK-3.0.1
* Mono

**Comment by metacritical** [comment]
Works! Just needs correct signature.

**Comment by varon** [comment]
Glad you managed to solve it. Come and join us on [Discord](https://discord.gg/6HqD48s). It's a great place to ask this type of thing!

**Comment by metacritical** [comment]
Ohh i didnt know there was a Discord. Thankyou! @varon
