### ISSUE TITLE
[Feature Request] Pixels Per Inch / Dots Per Inch Property

### ISSUE THREAD

**Issue by utkumaden** [opentk/opentk#944]
### Description

Add a screen dpi/ppi property to ~`OpenTK.DisplayDevice`~ `OpenToolkit.Windowing.Desktop.NativeWindow`, which can be used to calculate the physical dimensions of a pixel for each display.

### Use Cases

* Hi-dpi environments.
* Typography
* Calculating how many pixels a given unit of length is (e.g. at 72 dpi 1 pixel is 1 postscript point or 0.3527 mm)

**Comment by subchannel13** [comment]
Is this even possible? As far as I've found out, on Windows 7 the best you can get is DPI set user/administrator in screen resolution settings. There was no way of ask a display about it native DPI or real world dimensions.

**Comment by utkumaden** [comment]
Solved in #945
