### ISSUE TITLE
NuGet package points to www.opentk.com

### ISSUE THREAD

**Issue by Danny252** [opentk/opentk#955]
The OpenTK NuGet package is associated with www.opentk.com (which is not registered, for better or worse!), rather than www.opentk.net.

For example: https://www.nuget.org/packages/OpenTK/3.1.0

**Comment by varon** [comment]
Appreciate the small things like this!

Once upon a time in the distant past, this was our domain. Sadly it lapsed and we no longer have access to it.

Hopefully someone will jump on fixing this; as it's a super easy PR for anyone that wants fancy blue text on the discord. Failing that, will try to remember this for the next release!
