### ISSUE TITLE
Some suggestions on the coding style

### ISSUE THREAD

**Issue by AlseinX** [opentk/opentk#957]
### 1. There should also be file names that contain multiple punctuation marks.

> 3.1.1 Files must be named correctly
The file ending shall be in all lower case, whereas the name of the file shall match the name of the type exactly. A single punctuation mark shall separate the name and file extension. No more than one punctuation mark may be present in the filename.

There should be an exception when a nested type is placed to a single file.
```csharp
// Foo.cs
public sealed partial class Foo
{
    //member definitions of Foo
}

// Foo.Bar.cs
public sealed partial class Foo
{
    private class Bar
    {
        //member definitions of Bar
    }
}
```

### 2. Files that contain generic type overload should be suffixed with the number of the generic parameters.

> 3.1.3 Names of files containing a generic type may be suffixed
If required, the name of a file that contains a generic type may be suffixed by the names of the generic arguments to the class, held within a set of braces.

It is a type name with the number of generic parameters who identify a type, not a type name with the generic parameter names. And also, [ .NET Core itself uses ``<Type Name>`<Number of Generic Parameters>.cs``](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/ObjectPool%601.cs).

### 3. Local functions might(?) be named according to `camelCase`.

> 3.2.7 Methods must be named correctly
All methods (including local methods) must be named according to `PascalCase`.

> 3.2.9 Locals must be named correctly
All locals (local variables, method parameters, lambda arguments, etc) must be named according to `camelCase`.

The current coding style does not seem to regard local functions as locals.

According to [the official document](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/local-functions), local functions are not "local methods", though it is actually implemented by private methods. Logically, they are functions as they are not members of a type, but subroutines as a part of the methods' procedure. Although local functions are `PascalCase`d in many projects, I still think it should be named as-is, for the name "local function" means that firstly it is a local, and then it is a normal function instead of a member method.

Additionally, many use cases of local functions are a static alternative of lambda delegates when they are called for multiple times and there is no need for delegates. It makes no sense if a name change is needed when replacing a lambda delegate with a local function just for code optimization without and logical change.

Example:
```csharp
Action<int> logInt = value =>
{
    Console.WriteLine(DateTime.Now);
    Console.WriteLine($"The value \"{value}\" is logged.");
}
// ...
logInt(5);
// ...
logInt(10);
```
Optimized with local functions when named according to `PascalCase`:
```csharp
void LogInt(int value)
{
    Console.WriteLine(DateTime.Now);
    Console.WriteLine($"The value \"{value}\" is logged.");
}
// ...
LogInt(5);
// ...
LogInt(10);
//This name change from `logInt` to `LogInt` is logically meaningless.
```

(Local functions would create an exception either for functions/methods' `PascalCase` or locals' `camelCase`, but I do believe local function is more a local than a method sense it is logically not a method.)

### 4. Named tuple items ***MUST*** be named according to `camelCase`.

> 3.2.10 Named `ValueTuple` members must be named correctly
Named `ValueTuple` members are, for all intents and purposes, considered public properties on a class. Therefore, they must be named according to `PascalCase`.

A typical misunderstanding of the concept "tuple" is taking a tuple as a convenient alternative of anonymous class. Tuple is logically not an object (otherwise it should have never been added in C#), but are multiple local variables that are grouped for passing (like multiple return values). To distinguish from object members, the tuple item names must be named like local variables, just as function parameters are.

Example:
```csharp
//Definition
public static (double radius, double azimuth) ConvertToPolarCoordinates (double x, double y)
{
    var radius = //...
    var azimuth = //...
    return (radius, azimuth);
}

//Invocation
var (x, y) = //...
var (radius, azimuth) = ConvertToPolarCoordinates(x, y);
```
`x` and `y` are inputs, and `radius` and `azimuth` are outputs. `radius` and `azimuth` are not encapsuled in an object, just as `x` and `y` are not as well. The 3 pairs of `radius` and `azimuth` (the local variables in the caller code, the return type definition, and the local variables to be returned in the callee code) should share the same naming, just as the 2 pairs of `x` and `y` (in the callee and the caller) share the same naming

### 5. Improper use of words in the document.

"Parameters" are the variables in the function definition that need to be assigned by callers, and "arguments" are the values given on calling that are assigned to parameters. So there are no "lambda arguments" because a lambda expression is a definition of function that is not passing arguments but defining parameters. These concepts also apply to generics, for a type with generic parameters is an open generic type and a type with generic arguments is a closed generic type.

**Comment by jvbsl** [comment]
Thanks for your suggestions, we can of course always discuss on stuff like that, so here are my opinions to some of your points, but first off:
Official MS documentation isn't really that valid of a point imho, because MS doesn't even follow them themselfes^^

1. I think a valid point, you have there.
2. Even though it corresponds to the created type name, I do like Foo{T}/Dictionary{TKey,TValue} better
I can't even give files a name containing ` in Rider :D
3. In my book local functions are functions, and not local variables. Because it isn't handled as delegates, but compiled to a normal function(with a special name) and called like any non virtual function, and also not invoked like delegates...
4. Just fyi Tuples where anonymous classes at the beginning :P Now they are basically anonymous structs. The code generated handles them as structs and unpacking is just syntactic sugar for e.g. `x = struct.Item1; y = struct.Item2;`(or ldfld in IL)
5.
If you can tell where these mixups are, that would be great.

All in all thanks a lot for your input, it's highly appreciated.

**Comment by realvictorprm** [comment]
I disagree with 1.

Its stupid to have one file per type.

**Comment by AlseinX** [comment]
@jvbsl Thanks for attention~

2. I think a filename should only be the identifier of its contained type, I like this in 3.1.2:
> no extra type information should be annotated in the file name

but the type parameter names are not the identifiers of generic types, only the number of the type parameters are.

3. Local functions are functions, though it is compiled to a private method in the IL output, but I think the coding style should be based on the logic more than the low-level implementation.

4. Tuples are structs with sugar indeed, but the logical meaning is different. That's why the coding style demands using named items rather than `Item1` `Item2`. Here is the same explanation as in point 3. The syntax is sugared because the raw code does not clearly represents what logically is, therefore the coding style should be sugared as well, no matter what the low-level implementation is.

5. As qouted within the points 1 to 4, there are already some mixups. If this point is accepted, a check through the whole document is needed.

**Comment by jvbsl** [comment]
2. I'll wait on more opinions on that.
3. Well to me a local function is logically speaking still a function, the low-level implementation was just meant as additional reason.
4. Well mathematically speaking tuples are a set of ordered values, which locals are not really. I never saw tuples as something local, that is not only for C# but for other languages containing tuples as well...
5. Alright...
...then let's get on the same page on all points and wait on other opinions and wrap it up if we've done that.

**Comment by AlseinX** [comment]
@realvictorprm 
The current coding style demands that the filename should be the contained type name therefore it is 1 file per type.
My opinion 1 is not to enforce 1 file per type but sometimes there could be a case that nested types are splitted to a single file for readability.

**Comment by jvbsl** [comment]
@realvictorprm I pretty much agree with @AlseinX on that one, because if nested types get big it is a lot easier to read and navigate if they are seperated

**Comment by AlseinX** [comment]
@jvbsl 
3. local functions are functions, but the vanilla C# did not have functions (which are not member methods, the same below) until anonymous functions comes out, then we had lambda expressions (though they are all implemented by special named private methods), but the functions were not named as they are anonymous. So there is not a saying that a function must be `PascalCase`d while methods are indeed all `PascalCase`d.

4. Do you agree that tuple (in C# or some other languages) stands for the `( , )` (construction and deconstruction) syntax? It is not simply like the one in mathematics otherwise it must be represented by some collection like `IList`. Each item in a tuple have its logical meaning, not only an ordered set. The use case of tuples are "1 variable to store multiple variables" rather than "1 object containing multiple properties".

**Comment by jvbsl** [comment]
But it goes both ways.
3. There is not a saying that they need to be camelCased :P The difference is that lambdas are stored in variables or at least on stack, while local functions(like functions) are not, that is why in my brain it just doesn't feel(and in reality it isn't :P) like what you do feel about it.
4. I do agree on your first sentence.
You know that in mathematics tuples are denominated with `( , )` as well. And in C# the applied meaning of tuples is the same like in mathematics, the meaning of contained values or the tuples are defined by their usage(or some other way to describe it).
E.g. `(int x, int y)` can very well be written as `(x ∈ Z, y ∈ Z)` so apart from the syntax it is basically the same. The general meaning of Tuples are nothing more than an ordered set, even in C#, of course meaning can be applied to it by it's usage or naming, but that can be done in mathematics as well...

**Comment by realvictorprm** [comment]
@jvbsl @alseinx nothing against that argument. I completely agree but in general deciding on that each file should contain only a single type is not what I think makes sense.

**Comment by AlseinX** [comment]
@jvbsl 
3. The point is not "function" but "local". It is not because of "function" but "local" so that camelCase. The "local" means it works inside the local context, it could be accessed within a single call to the host function or method and could access the local variables (including the arguments, which are including `this`). In other words, the context of a local function is scoped in a call to the host function or method rather than in the lifetime of the object. That's why it is called "local function" rather than something like "nested function" or "internal function" and that's why I think it should be camelCased.

4. Note that a concept from mathematics does not have to be exactly the same in programming. "Function" in maths means "a relation between sets that associates to every element of a first set exactly one element of the second set" but in programming, it means a subroutine that takes (or not) arguments and return a value (or not). A function in programming does not have to match the definition of that in maths.

**Comment by jvbsl** [comment]
3. Yeah I understood your reasoning already, but to me the "function" part prevails over the "local" part. I don't mean that what you say is wrong, but to me it seems to be more of a opinion than an absolute truth, don't know if you would agree with that?
4. I didn't mean to say that everything from mathematical concepts is done 1:1 in programming(or C#), there are programming languages which try to match the mathematical language much more closely.
But to me Tuples where made to be prettty much what tuples are in maths. I would think that there are more people who never heard of tuples in C# before, but from e.g. maths, or other languages, would understand them that way.

We probably can never agree on these two points :P Therefore I think we should wait for other opinions, and go with a democratical approach. Think that is acceptable for you?

**Comment by AlseinX** [comment]
3. Yeah I agree, that's why I used "might(?)".
4. Our discussion seem getting irrelative to the original proposal, but I believe that your understanding leads to use `Item1` `Item2` over named items.

Yeah, I believe we did explain our opinions detaily, it would be the better to wait for other opinions really.

**Comment by jvbsl** [comment]
4. Well no. It was only meant to argue against camelCase. While I, in that case don't particularly prefer PascalCase. I do understand the original reasoning just as well, and wanted to reason why that decision was made^^
Unnamed tuples are imho only okay if there is no access to specific items, but mostly you can name them anyway.

**Comment by varon** [comment]
This isn't a direct reply to the issue, but rather my thoughts on any coding standards at all.

In general, the coding standards should serve developers rather than developers serve the coding standards. The aim is to save time. That means improving readability, debuggability and consistency.

The project has shifted quite a bit since we first authored them, but I still feel they're in general incredibly draconian compared to what is actually necessary to have clean, readable code.

What we're seeing at the moment is that we're losing any advantage of having clean code by requiring developers spend a ton of time fighting with stylecop rules just to get something done.

From my side, I'd basically like to see them go away and be replaced with a 'best effort' auto format configuration for R# or something.

Even if it's not perfect, we can just automate this completely. Let's let machines do the hard work for us and let our contributors focus on the cool parts instead.

**Comment by AlseinX** [comment]
Can we remove some controversial rule in the coding standard so that it would be not so draconian?

Auto-fomarting still has some limitation, like, if we need to ensure the classes that are not designed to be inherited sealed, how could a automated mechanism identify them?

**Comment by varon** [comment]
We've made the coding standards way less crazy. This should be fixed.
