### ISSUE TITLE
How to add imgui?

### ISSUE THREAD

**Issue by ejamshidiasl** [opentk/opentk#958]
Hello
i want to add imgui to OpenTK and asked in discord too but i cannot do this until now.
i tested imgui.net but there is no OpenTK version or sample.
how to do this?

### Related information 
* win 10
* Native backend
* What version of OpenTK (NuGet)
* What runtime (.NET Framework)

**Comment by inputusernamehere** [comment]
I'm also looking for an example using those two technologies: https://github.com/mellinoe/ImGui.NET/issues/136

**Comment by NogginBops** [comment]
I just created an example of ImGui.NET running on OpenTK here:
https://github.com/NogginBops/ImGui.NET_OpenTK_Sample

**Comment by jvbsl** [comment]
As there are samples for OTK 3 and 4 in the linked repository I'm gonna close this ;)
