### ISSUE TITLE
GLFWProvider assumes that thread calling CreateGlfw is the "main thread"

### ISSUE THREAD

**Issue by PJB3005** [opentk/opentk#961]
This is not correct. The "main thread" is the thread to actually call `Main()` in the program. On macOS, getting this wrong will result in a crash in GLFW.

If there is a check for "is main thread" it should be correct at least.

**Comment by jvbsl** [comment]
well the function means the GLFW main thread, which is dependent on the thread it is initializes from. So it does what it is meant to do(while we can discuss on naming :D), but why would it crash on macOS? It shouldn't matter which thread the GLFW stuff is made from as long as most stuff happens on the thread it was initialized from

**Comment by PJB3005** [comment]
> well the function means the GLFW main thread, which is dependent on the thread it is initializes from.

No, it actually doesn't. That's the problem. The GLFW documentation *actually* means the "thread to call `main()` to start your program", or well in the .NET case it's `public static void Main(string args[])`

It crashes on macOS because their APIs just blow up if you don't call them from said thread.

**Comment by jvbsl** [comment]
You are right, I assumed wrongly, because I didn't see(or forgot) the part where it is documented that it has to explicitely be the main thread and that is the way I saw that solved in other libraries...

> Most GLFW functions must only be called from the main thread (the thread that calls main)
https://www.glfw.org/docs/latest/intro_guide.html#thread_safety

In that case we need to check on initialization that we are on the real main thread, then it will be correct.
But that still means that we currently don't do that, otherwise it shouldn't crash on macOS, right?

**Comment by PJB3005** [comment]
> But that still means that we currently don't do that, otherwise it shouldn't crash on macOS, right?
Yes

> In that case we need to check on initialization that we are on the real main thread, then it will be correct.

The problem is, I can't find a single sane way to actually *do* that.

**Comment by varon** [comment]
Possibly related? #1206

**Comment by NogginBops** [comment]
Moving this together with #1206 to the `4.7.1` milestone as there is no clear solution yet.

**Comment by NogginBops** [comment]
We could do a hacky solution for this which involves getting the current stack trace and comparing it to the assemblies entry point.
See https://stackoverflow.com/a/2374560/9316430
Then we could store that thread id and throw an exception if it isn't the main thread.
