### ISSUE TITLE
Memory Leak Intel HD Graphics (igdgmm32.dll) on Resizing GLControl

### ISSUE THREAD

**Issue by alindemannalltec** [opentk/opentk#977]
### Description

We are facing a memory leak when using GLControl with Intel HD graphics (inside igdgmm32.dll).
C# project to reproduce available.
When using NVidia or AMD graphicscard, there is no memory leak.
Since I am not sure what it is caused by I add it here for further analyzing possibilities.

### Repro steps

*Preconditions*
Intel HD Graphics
- verified with:
Intel UHD 630 (Driver: 26.20.100.6911), Windows 10 => igdgmm32.dll
Intel HD 530 (Driver: 21.20.16.4542), Windows 7 => ig9icd32.dll
Intel HD 620 (Driver: 26.20.100.6888), Windows 10 => igdgmm32.dll

1. Create Windows Form
2. Add GLControl (make sure property "Dock" is set to "DockStyle.Fill"
3. Shrink or grow GLControl on every frame

_Note: when removing the dock-style setting, the leak does not occure._
_Note: this is not representing the actual usage, this is just to make this issue occur more likely._

_Helper tool to reproduce this issue. To start the memory leak to happen, focus the Window and press "s". A thread will start to constantly resize the GLControl._
[MemleakTest.zip](https://github.com/opentk/opentk/files/3739615/MemleakTest.zip)

### Expected behavior

Memory usage does not grow constantly.

### Actual behavior

Memory usage grows constantly.

### Related information 

* Operating system
Windows 10 (OS build 17134.1006)

* SDL or Native backend
* What version of OpenTK (Installer, NuGet, Source Code)
NuGet: 
OpenTK 3.1.0
OpenTK GLControl 3.1.0

* What runtime (.NET Framework, CoreCLR, Mono)
.net Framework 4.6.1

* Workarounds (if any)

**Comment by jvbsl** [comment]
Unfortunately your test project doesn't work on Linux. And in Code I can't find anything in particular which looks like a memory leak.
Could you perhaps try creating a memory snapshot of before and after and look what objects cause the memory leak?
Because if there is no memory leak showing up there it is gonna be hard to find the actual problem, because it is gonna be somewhere native then...

**Comment by alindemannalltec** [comment]
Thanks for your quick response.

For my analysis I used Redgate ANTS Memory Profiler that showed an increasing memory allocation in igdgmm32.dll (User Mode Driver for Intel Graphics Technology).

I was hoping that you have better tools/techniques helping to identify or isolate the underlaying issue.

Attached you find a sceenshot showing the leaking unmanaged Module

![ANTS_ProfilerScreen](https://user-images.githubusercontent.com/56685821/67079143-ef128b80-f192-11e9-9b1d-cabe9c90f37b.png)

and the profiling result 
[MemleakTest_ProfilerResults_101819.zip](https://github.com/opentk/opentk/files/3742973/MemleakTest_ProfilerResults_101819.zip)

Link to download (a trial version of) Redgate ANTS Memory Profiler: https://www.red-gate.com/products/dotnet-development/ants-memory-profiler/

Thanks in advance.

**Comment by alindemannalltec** [comment]
Hi all,

is there any news to this issue?

Thanks,
Best Regards,
alindemann

**Comment by varon** [comment]
GLControl is largely obsolete. We would welcome a new implementation targeting 4.x.
