### ISSUE TITLE
Reference to buffer data arrays

### ISSUE THREAD

**Issue by HugoPeters1024** [opentk/opentk#978]
### Description
(Hyphothesis)
When calling GL.BufferData with an array as data, a reference to that array is kept, causing the array to persist beyond that scope.

### Repro steps
Create a buffer and fill it with a large array. See that the memory usage does not decrease after exiting that scope.

### Expected behavior
The local array is disposed.

* Operating system
* SDL
* NuGet
* .NET Framework

I am not very familiar with the C# garbage collector and this is just an hypothesis. I would love to hear it if anyone thinks something else is going on here.

**Comment by NogginBops** [comment]
Are you sure that the array is referenced somewhere? You could take a memory dump and see what references the array you think should be collected.
I haven't looked at the code but I find it weird (but not impossible) that the method keeps a reference alive. But would be really weird if it did.

**Comment by UnknownShadow200** [comment]
Are you calling GC.Collect(); afterwards to force a full garbage collection?

**Comment by HugoPeters1024** [comment]
I later tried to indeed call GC.Collect(). This made me realized that memory is usually only freed up when needed (so the array was invalidated but not yet erased). I still get out of memory exceptions but I think that is due to the large nature of my data. I sucks that you can't get an array out of a pointer without a double buffer. Anyways, I don't think the fault lies in OpenTK, thanks for your help I will close the issue.

**Comment by jvbsl** [comment]
sounds like you need to do memory pooling
