### ISSUE TITLE
How can I create a GraphicsContext from an IntPtr?

### ISSUE THREAD

**Issue by softwareantics** [opentk/opentk#979]
I'm just wondering if there's any way I can create a GraphicsContext from an IntPtr rather than passing through the `IWindowInfo` interface?

**Comment by mtosoftware** [comment]
After a further look, I suppose this is more of a feature request :(

**Comment by jvbsl** [comment]
Sorry for late reply.
Have you tried the overload which takes in a ContextHandle as the first parameter?
ContextHandle can be directly created from an IntPtr.

**Comment by varon** [comment]
Closing as this question is over a year old.
