### ISSUE TITLE
Context is created with OpenGL version older than requested, instead of exception

### ISSUE THREAD

**Issue by moritz-h** [opentk/opentk#980]
### Description
I want to create an OpenGL context with version 4.3. I would expect, that this should fail with an exception if OpenGL 4.3 is not available. Instead window and context creation is sucessful with an too old OpenGL verion.

### Repro steps
I am running this code:
```
using System;
using OpenTK;
using OpenTK.Graphics;
using OpenTK.Graphics.OpenGL4;

namespace GLTest
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            var win = new GameWindow(400, 300, GraphicsMode.Default, "Test", GameWindowFlags.Default, DisplayDevice.Default, 4, 3, GraphicsContextFlags.Default);
            win.MakeCurrent();
            Console.WriteLine("Version: " + GL.GetString(StringName.Version));
            win.Run(60);
        }
    }
}
```
I'm running this in a Virtual Box Windows 10 VM. Maximum supported OpenGL Version in Virtual Box is OpenGL 2.1.

### Expected behavior

I would expect an exception that an OpenGL 4.3 Context could not be created.

### Actual behavior

The window is shown with an OpenGL 2.1 context.

### Related information 

Windows 10
OpenTK 3.1.0 via NuGet
.Net Framework 4.5.1

**Comment by jvbsl** [comment]
I'm not sure what the best solution would be, as OpenGL is free to return whatever it wants. so if you request OGL 1.1 it could be that it returns 4.6 and the other way round.
So I don't know if we would really want to enforce that, as OpenTK tries to wrap OGL, and therefore it is debatable if we would want to expose different behaviour from OGL.
So the current thing is, if you want to force a version, you'd need to check it yourself.

**Comment by moritz-h** [comment]
What I'm trying to achieve is just make sure, when I call OpenGL 4.3 functionality, that the context is able to do so and otherwise do some kind of error handling for a clean shutdown or fallback.
I somehow automatically assumed the behavior of what GLFW is doing (see https://www.glfw.org/docs/latest/window_guide.html#window_hints_ctx)
> These hints are not hard constraints, but creation will fail if the OpenGL version of the created context is less than the one requested.

But you are right, this could be discussed and what I were thinking of is then probably just a design decision of GLFW.
But otherwise why can I specify an OpenGL version at all if it doesn't play any role for the context I receive in the end?

So ok for now I need to check the GL_VERSION string myself, at least as temporary workaround. But it would at least be very nice if you can write in the documentation what the expected behavior of OpenTK is.

**Comment by jvbsl** [comment]
It is for the OpenGL driver, because it can use this information. And a lot of applications request highest OGL, check the returned version and dependant on that use fallback versions.
OTK uses GPFW btw^^

**Comment by varon** [comment]
This should be handled differently (and solved) by 4.x
