### ISSUE TITLE
3.x branch build.cmd fails with compiler errors on machine with VS 2019

### ISSUE THREAD

**Issue by mludlum** [opentk/opentk#981]
### Description

I get the errors below when trying to build branch 3.x on my machine.  I think FAKEis using the wrong version of msbuild/csc.  How can I get this to work?  I've tried adding this to build.sfx but that does not work.  Not sure if the version of FAKErecognizes it.  First time I've even heard about FAKE.

**EnvironmentHelper.setBuildParam "VisualStudioVersion" "16.0"**

### Repro steps

Please provide the steps required to reproduce the problem

1. Run build.cmd on a machine with Visual Studio 2019 (and no other VS version) installed.

### Expected behavior
Successful build.

### Actual behavior

Build started 11/15/2019 10:24:56 AM.
     1>Project "C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj" on node 1 (Build target(s)).
     1>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreCompile:
         C:\Windows\Microsoft.NET\Framework\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitpreferred /warn:4 /doc:bin\Release\Bind.xml /baseaddress:285212672 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1
         \mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Fra
         mework\.NETFramework\v4.6.1\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll" /debug- /filealign:4096 /keyfile:..\..\OpenTK.snk /optimize+ /out:obj\Release\Bind.exe /subsystemversion:6.00 /target:exe /utf8output CSharpSpecW
         riter.cs FuncProcessor.cs GL2\GL4Generator.cs IBind.cs Main.cs DocProcessor.cs Settings.cs BindStreamWriter.cs EnumProcessor.cs Utilities.cs ISpecReader.cs Properties\AssemblyInfo.cs CL\CLGenerator.cs GL2\Generator.cs Structures\Type.cs Structures\Function.cs Structures\Constant.cs Structures\Enum.cs Struc
         tures\Delegate.cs Structures\Parameter.cs Structures\FlowDirection.cs ES\ESGenerator.cs XmlSpecReader.cs ES\ES2Generator.cs ES\ES3Generator.cs GL2\GL2Generator.cs Structures\Documentation.cs ES\ES31Generator.cs "C:\Users\Michael\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cs"
     1>Structures\Type.cs(39,56): error CS1519: Invalid token '=' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
     1>Structures\Type.cs(39,70): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
     1>Structures\Type.cs(199,55): error CS1519: Invalid token '=' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
     1>Structures\Type.cs(199,74): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
     1>Structures\Delegate.cs(152,46): error CS1519: Invalid token '=' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
     1>Structures\Delegate.cs(152,52): error CS1520: Method must have a return type [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
     1>Done Building Project "C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj" (Build target(s)) -- FAILED.

Build FAILED.

       "C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj" (Build target) (1) ->
       (CoreCompile target) ->
         Structures\Type.cs(39,56): error CS1519: Invalid token '=' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
         Structures\Type.cs(39,70): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
         Structures\Type.cs(199,55): error CS1519: Invalid token '=' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
         Structures\Type.cs(199,74): error CS1519: Invalid token ';' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
         Structures\Delegate.cs(152,46): error CS1519: Invalid token '=' in class, struct, or interface member declaration [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]
         Structures\Delegate.cs(152,52): error CS1520: Method must have a return type [C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj]

    0 Warning(s)
    6 Error(s)

Time Elapsed 00:00:00.09
Running build failed.
Error:
Building C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                     Duration
------                     --------
Clean                      00:00:00.0012202
AssemblyInfo               00:00:00.8033410
GenerateBindingsIfNeeded   Failure
Total:                     00:00:01.3013797
---------------------------------------------------------------------
Status:                    Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Building C:\DotNet\opentk\src\Generator.Bind\Generator.Bind.csproj failed with exitcode 1.
  2) CS1519: Structures\Type.cs(39,56): Invalid token '=' in class, struct, or interface member declaration
  3) CS1519: Structures\Type.cs(39,70): Invalid token ';' in class, struct, or interface member declaration
  4) CS1519: Structures\Type.cs(199,55): Invalid token '=' in class, struct, or interface member declaration
  5) CS1519: Structures\Type.cs(199,74): Invalid token ';' in class, struct, or interface member declaration
  6) CS1519: Structures\Delegate.cs(152,46): Invalid token '=' in class, struct, or interface member declaration
  7) CS1520: Structures\Delegate.cs(152,52): Method must have a return type
---------------------------------------------------------------------
### Related information 

* Operating system Windows 10 HOME
* What version of OpenTK (Installer, NuGet, Source Code)  3.x branch
* What runtime (.NET Framework, CoreCLR, Mono)  Not sure
* Workarounds (if any)

**Comment by jvbsl** [comment]
These error seems to me like your C# version is not recent enough...Property initialization should be possible with C#6
Do you actually have Mono installed?

**Comment by mludlum** [comment]
Yes, that is correct, because the build is using the stock version of .NET that comes with windows instead of what's in the VS 2019 folder.  No, I don't have Mono installed, but I have the .NET 4.7.2, 4.8, and Core 3.0 SDKs installed.   The build instructions do not mention Mono being a requirement.  On another machine, the build works fine because it's finding tools in the VS 2017 folder.  There are tickets on the web mentioning this issue with FAKE.  My guess is that the 3.x branch is using an old version of FAKE.   I'm posting to see if there are any workarounds because I'm don't want to install VS2017 just for this.

**Comment by mludlum** [comment]
My original guess about Fake was correct.   I got the build to work after doing these steps:
1.  Modify paket.dependencies to pin fake to newer version (> 5.0.0.0 won't work)
nuget FAKE 4.64.17
2.  Run this to pull the new version. 
.paket\paket.exe update fake

build.cmd will use the correct version of MSBUILD from my VS2019 folder.
