### ISSUE TITLE
Shader Memory Access Violations

### ISSUE THREAD

**Issue by Azeranth** [opentk/opentk#987]
### Description

Creating shaders with empty source codes will create invalid memory addressing, and ultimately results in crashes when later accessing/compiling/writing to these on certain version of windows/Radeon drivers.

### Reproduction

Create two shaders, immedaitely after one another, both with sources assigned to a null stream. Then, attempt to compile the first. The debugger will the catch the exception in the call. 
(Note the violation occurs in the call, not in the formation of the call itself)

Windows 10, version 1903 (This problem does not persist on version 1909)
.NET Framework 4.7.2

**Comment by Azeranth** [comment]
Note: An unusual workaround, seems that having at least a comment in the shader source, or any form of directives, even if they do not result in any compiled code being produced, the issue does not appear consistently, though this or a similar problem still occurs in some cases

**Comment by jvbsl** [comment]
Well I don't know if we can call that an issue, as I currently don't see the use in even doing that? Could you please describe a use case to me. While, yes it possibly shouldn't crash(would need to look what happens in native...e.g. C) I don't know why someone would want to do that^^

**Comment by Azeranth** [comment]
@jvbsl Short answer, no, I can't think of a use case. I just wanted to mention the existence of the crash case.

Although, as I understand it, compiling null shaders is the only way to increment shader pointer. So, what you could do with that information... ?

Perhaps if you need a valid shader pointer, but don't want to actually do anything with the shader.

**Comment by PJB3005** [comment]
> Well I don't know if we can call that an issue

Well if it doesn't crash when doing it from C I don't see why it should crash for us.

**Comment by deccer** [comment]
@Azeranth what's the use case for having a valid shader pointer for an empty shader?

**Comment by Azeranth** [comment]
> 
> 
> > Well I don't know if we can call that an issue
> 
> Well if it doesn't crash when doing it from C I don't see why it should crash for us.

I've looked into it more, and the issue looks like it might have more to do with the null filestream, rather than actual empty source? I stopped looking into it after a day

**Comment by varon** [comment]
workaround; use an empty string instead. Closing for now, as this is something we'll have to look at for 5.x anyway.
