### ISSUE TITLE
Can not pass paras to the shader when using AMD card (opengl4 API)

### ISSUE THREAD

**Issue by RussLE2018** [opentk/opentk#991]
### Description

I write a very simple shader, and using opengl4 API to render it. When I use gtx1060, it works fine, but when I use a WX5100 or RX580, the shader does not work. The driver is updated to the latest version. Have I do something wrong? How to make it work on a AMD graphic card? The project is attached.
Waiting for your kind reply

I pass the paras to the shader using:
           GL.UseProgram(_program);
            // add shader attributes here
            GL.VertexAttrib1(0, _time);
            GL.DrawArrays(PrimitiveType.Patches, 0, 3); 
            SwapBuffers();
The vertex shader:

#version 450 core

layout (location = 0) in float time;
layout (location = 1) in vec4 position;
out vec4 frag_color;

void main(void)
{
	gl_Position = position;
	frag_color = vec4(sin(time) * 0.5 + 0.5, cos(time) * 0.5 + 0.5, 0.0, 0.0);
}

the frag shader: 

#version 450 core
in vec4 frag_color;
out vec4 color;

void main(void)
{
	color = frag_color;
}

[opengl test.zip](https://github.com/opentk/opentk/files/4002010/opengl.test.zip)

**Comment by PJB3005** [comment]
Your code is using Tesselation features like `GL_PATCHES`, but you don't have a tessellation evaluation shader. I tried to run the code on Linux Intel Mesa drivers and it's spamming errors about Tessellation not being active.

**Comment by RussLE2018** [comment]
Thank you for your reply, I sent a wrong project by mistake. I did not use Tesselation features for my test. The project is enclosed  

[OpenTK.zip](https://github.com/opentk/opentk/files/4002187/OpenTK.zip)

waiting for your kind reply

**Comment by PJB3005** [comment]
Your second sample runs fine for me on Intel Mesa, and I can't find any problems with the code.

I'm gonna go and blame it on AMD having really bad OpenGL drivers on Windows.

**Comment by RussLE2018** [comment]
Thank you for your reply. I test it on PC with a intel graphic card and it works. It just does not work for AMD card. Now I'm gonna to use the old API to see if it works

**Comment by varon** [comment]
This happens when you confuse uniform locations for indices.
