### ISSUE TITLE
Improve build documentation

### ISSUE THREAD

**Issue by glopesdev** [opentk/opentk#995]
While studying the new build pipeline, I came across a few difficulties with the current documentation that I believe might be improved. Here are my thoughts:

1. Build instructions can currently be found both in README.md and CONTRIBUTING.md. Some of the git instructions seem outdated in CONTRIBUTING.md, for example it still [recommends doing work against the `develop` branch](https://github.com/opentk/opentk/blame/master/CONTRIBUTING.md#L87), which no longer exists.

2. None of the instructions mention the F# code generation pipeline, or how to get it to work, so I had to bump a bit against it until I figured it out. The batch scripts on the command-line are useful for this, but they also seem to be outdated. Specifically, the **SpecificationOpenGL** project requires the **gl.xml** file, which has to be obtained externally from the khronos.org website.

3. There are two files, `update-specifications.bat` and `update-bindings.bat`, that mention a **Generators** folder and two sub-projects (**Generator.Bind** and **Generator.Convert**) which no longer seem to exist. It's unclear in the build documentation what these projects are used for, e.g. which ones are for testing, and which ones for building?

4. The file `build.cmd` does not seem to get called correctly as a pre-build event on my machine using VS 2019. Furthermore, calling it manually from CLI always starts downloading the `dotnet` tool manually, even if it is already installed, so detection of latest version might not be implemented correctly. Currently had to manually call `dotnet fake run build.fsx -t UpdateBindings` myself to actually generate the bindings.

I imagine the project is maintained by a regular team who is already familiar with these procedures, so just wanted to share a bit of the perception that a complete outsider might have when coming into the code base.

I was eventually able to build all projects by manually downloading **gl.xml** from the khronos.org website and placing it where the **SpecificationOpenGL** project was looking for it. If someone is willing to walk me over the expected pipeline including the purpose of the FAKE scripts and code generators, I would be happy to offer pull requests to improve the docs!

**Comment by varon** [comment]
Thanks for the excellent feedback @glopesdev.

The entire project should fully bootstrap and build in one step via `build.cmd` or `build.sh` from having nothing installed. I've updated the fixed the steps in `README.md` to indicate that they need to be run.

The build scripts should download all dependencies, tools etc, then run `build.fsx` via [FAKE](https://fake.build/), which is implements the build logic across platforms.

The script itself automates a ton of steps, from fetching the `gl.xml` to the compilation, tests, nuget package generation and github releases.

Once all of that is done, open in IDE and work as usual.

**Comment by glopesdev** [comment]
I see, indeed being patient with the `build.cmd` script did work.

For some reason the `dotnet-install.ps1` script doesn't detect if there is an already an existing version of `dotnet` installed on the machine from the website. It seems that after installation it works, but have no idea if it replaced the .NET Core on my machine.

In any case, build completed successfully, but now it complains about failing to load `glfw3.dll`. Is there a pre-requisite to install it from somewhere else? Maybe that also needs to go in the README? At this point the README just mentions SDL2 which may have been discarded?

**Comment by varon** [comment]
dotnet typically installs all of the versions side-by-side. It shouldn't overwrite anything during that build process.
You can try type:
```
$ dotnet --list-sdks
1.0.4 [C:\Program Files\dotnet\sdk]
1.1.0 [C:\Program Files\dotnet\sdk]
2.0.2 [C:\Program Files\dotnet\sdk]
2.1.2 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.402 [C:\Program Files\dotnet\sdk]
2.1.504 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.508 [C:\Program Files\dotnet\sdk]
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.700 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
3.1.100 [C:\Program Files\dotnet\sdk]
$
```

All of the native, platform specific code as well as SDL2 has been removed from OpenTK for 4.0. Will update the readme there.

We're exclusively utilizing GLFW, which is way simpler, faster and most importantly provides consistent cross-platform behaviour.

**Comment by PJB3005** [comment]
> For some reason the `dotnet-install.ps1` script doesn't detect if there is an already an existing version of `dotnet` installed on the machine from the website.

I could've sworn I fixed that... Unless it's broken on Windows still.

> It seems that after installation it works, but have no idea if it replaced the .NET Core on my machine.

Pretty sure it installs into a directory under your user when doing it like this (since it asks for no admin privileges). As Varon said you can use `dotnet --list-sdks` to see where it ended up probably.

> Is there a pre-requisite to install it from somewhere else?

[opentoolkit.redist.glfw](https://www.nuget.org/packages/opentoolkit.redist.glfw]) has them but yes it is quite annoying that they're not available by default.

**Comment by varon** [comment]
Should be working fairly simply now.
